### ISSUE TITLE
IoTEdge Intermittent Connectivity Issues: Modules stop sending data

### ISSUE THREAD

**Issue by ilyas-it83** [Azure/iotedge#105]
IoT Edge modules stops working intermittently, but restarting edge restores it.

## Expected Behavior
Edge  modules continuously process and publish the data

## Current Behavior
IoT Edge modules stops working intermittently, but restarting edge restores it.

## Steps to Reproduce
Run tempSensor & filtermodule as per the instructions given in the doucment

### Device (Host) Operating System
Distributor ID: Ubuntu
Release:        17.10
Codename:       artful

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Mon Jun 25 21:07:53 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Mon Jun 25 20:43:05 2018
  OS/Arch:      linux/amd64
  Experimental: false

## Logs
 
    at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass11_1.<<PutOrUpdate>b__1>d.MoveNext() in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 88
   at Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore.Add(String endpointId, IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs:line 92
   at Microsoft.Azure.Devices.Routing.Core.Endpoints.StoringAsyncEndpointExecutor.Invoke(IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs:line 56
   at Microsoft.Azure.Devices.Routing.Core.Dispatcher.DispatchInternal(IEndpointExecutor exec, IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Dispatcher.cs:line 108
   at Microsoft.Azure.Devices.Routing.Core.Router.RouteAsync(IEnumerable`1 messages) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Router.cs:line 105
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.EventsLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/EventsLinkHandler.cs:line 54
2018-08-01 14:45:28.240 +00:00 [WRN] - Error opening events link for myEdgeDevice3/tempSensor
RocksDbSharp.RocksDbException: Invalid argument: Invalid column family specified in write batch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 79
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.Put(Byte[] key, Byte[] value) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs:line 36
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass11_1.<<PutOrUpdate>b__1>d.MoveNext() in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 88
   at Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore.Add(String endpointId, IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs:line 92
   at Microsoft.Azure.Devices.Routing.Core.Endpoints.StoringAsyncEndpointExecutor.Invoke(IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs:line 56
   at Microsoft.Azure.Devices.Routing.Core.Dispatcher.DispatchInternal(IEndpointExecutor exec, IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Dispatcher.cs:line 108
   at Microsoft.Azure.Devices.Routing.Core.Router.RouteAsync(IEnumerable`1 messages) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Router.cs:line 105
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.EventsLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/EventsLinkHandler.cs:line 54

## Logs - Somemore
2018-08-01 14:38:33.195 +00:00 [WRN] - Error opening events link for myEdgeDevice3/tempSensor
RocksDbSharp.RocksDbException: Invalid argument: Invalid column family specified in write batch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 79
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.Put(Byte[] key, Byte[] value) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs:line 36
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass11_1.<<PutOrUpdate>b__1>d.MoveNext() in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 88
   at Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore.Add(String endpointId, IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs:line 92
   at Microsoft.Azure.Devices.Routing.Core.Endpoints.StoringAsyncEndpointExecutor.Invoke(IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs:line 56
   at Microsoft.Azure.Devices.Routing.Core.Dispatcher.DispatchInternal(IEndpointExecutor exec, IMessage message) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Dispatcher.cs:line 108
   at Microsoft.Azure.Devices.Routing.Core.Router.RouteAsync(IEnumerable`1 messages) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Router.cs:line 105
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.EventsLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/EventsLinkHandler.cs:line 54

**Comment by varunpuranik** [comment]
@ilyas-it83, From the logs, it looks like the data store in the system has gotten into a bad state. I have not seen this before and I am not sure how it might have gotten into this state. 
Was this part of a test run that included frequent updates to the routes and/or frequent restarts of the EdgeHub module? 
Also, are you able to reproduce this consistently? If so, can you provide us the repro steps?

**Comment by ilyas-it83** [comment]
@varunpuranik, this seems to be an intermittent issue and i also could not re-produce the issue to get you the logs again. But restarting Edge helped me to overcome this issue.  Lastly, IoTEdge command also hangs most of the time, but the logs of edge deamon, edgeAgent, edgeHub looks quite OK. Let me know if there are any specific commands that i can test it against.

**Comment by varunpuranik** [comment]
Can you elaborate on the iotedge commands that are hanging for you? Note that a lot of the iotedge commands translate to docker commands and as such could take a bit before they respond.

**Comment by rydergillen-compacSort** [comment]
I encountered this issue today. I had updated the modules (but not the routes) a few times beforehand. The modules ran fine for an hour or so and then crashed.

Running IoT Edge 1.0.2 -Linux Containers on Windows 10 Pro

`RocksDbSharp.RocksDbException: Invalid argument: Invalid column family specified in write batch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 79
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.Put(Byte[] key, Byte[] value) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs:line 45
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass11_1.<<PutOrUpdate>b__1>d.MoveNext() in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 88
   at Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore.Add(String endpointId, IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs:line 96
   at Microsoft.Azure.Devices.Routing.Core.Endpoints.StoringAsyncEndpointExecutor.Invoke(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs:line 61
   at Microsoft.Azure.Devices.Routing.Core.Dispatcher.DispatchInternal(IEndpointExecutor exec, IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Dispatcher.cs:line 108
   at Microsoft.Azure.Devices.Routing.Core.Router.RouteAsync(IEnumerable`1 messages) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Router.cs:line 105
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.EventsLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/EventsLinkHandler.cs:line 56
2018-10-05 06:49:08.687 +00:00 [INF] - Closing link Events for CI/Sizer-Legacy-Stats
2018-10-05 06:49:09.028 +00:00 [INF] - Processing subscription Methods for client CI/Sizer-Legacy-Stats.
2018-10-05 06:49:09.188 +00:00 [WRN] - Error in connection established callback for client CI/Sizer-Legacy-Stats
RocksDbSharp.RocksDbException: Invalid argument: Invalid column family specified in write batch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 79
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.Put(Byte[] key, Byte[] value) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs:line 45
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass11_1.<<PutOrUpdate>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 88
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.GetTwinInfoWhenCloudOnlineAsync(String id, ICloudProxy cp, Boolean sendDesiredPropertyUpdate) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 254
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.<>c__DisplayClass16_0.<<ProcessConnectionEstablishedForDevice>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.ProcessConnectionEstablishedForDevice(IIdentity identity) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 88
2018-10-05 06:49:09.189 +00:00 [WRN] - Failed to update reported  properties for CI/$edgeHub with error Invalid argument: Invalid column family specified in write batch
2018-10-05 06:49:09.190 +00:00 [WRN] - Error handling device connected event for device CI/Sizer-Legacy-Stats
RocksDbSharp.RocksDbException: Invalid argument: Invalid column family specified in write batch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 79
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.Put(Byte[] key, Byte[] value) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs:line 45
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.Update(TK key, Func`2 updator) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 76
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesWhenTwinStoreHasTwinAsync(String id, TwinCollection reported, Boolean cloudVerified) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 334
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.ExecuteOnTwinStoreResultAsync(String id, Func`2 twinStoreHit, Func`1 twinStoreMiss) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 150
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesWithStoreSupportAsync(String id, IMessage reportedProperties) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 461
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesAsync(String id, IMessage reportedProperties) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 376
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.DeviceConnected(Object sender, IIdentity device) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 277`

**Comment by JMayrbaeurl** [comment]
I'm having the same problem, while developing a new custom module (Win 10 RS5 with 1.0.3). After several deployments and deletions of the module, I've got the following exception in edgeHub:

```
2018-10-18 09:59:31.383 +00:00 [INF] - Closing link Events for jurgenmaEdgeP50/TemperatureSimulatorModule
2018-10-18 09:59:31.612 +00:00 [WRN] - Error in connection established callback for client jurgenmaEdgeP50/TemperatureSimulatorModule
RocksDbSharp.RocksDbException: Invalid argument: Invalid column family specified in write batch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in /home/vsts/work/1/s/edge-util/src/Microso
ft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 79
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.Put(Byte[] key, Byte[] value) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.
Storage.RocksDb/ColumnFamilyDbStore.cs:line 45
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass11_1.<<PutOrUpdate>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Dev
ices.Edge.Storage/EntityStore.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edg
e.Storage/EntityStore.cs:line 88
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.GetTwinInfoWhenCloudOnlineAsync(String id, ICloudProxy cp, Boolean sendDesiredPropertyUpdate) in /home/vsts/wor
k/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 254
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.<>c__DisplayClass16_0.<<ProcessConnectionEstablishedForDevice>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub
/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.ProcessConnectionEstablishedForDevice(IIdentity identity) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.D
evices.Edge.Hub.Core/TwinManager.cs:line 88
2018-10-18 09:59:31.613 +00:00 [WRN] - Failed to update reported  properties for jurgenmaEdgeP50/$edgeHub with error Invalid argument: Invalid column family specified 
in write batch
2018-10-18 09:59:31.613 +00:00 [WRN] - Error handling device connected event for device jurgenmaEdgeP50/TemperatureSimulatorModule
RocksDbSharp.RocksDbException: Invalid argument: Invalid column family specified in write batch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in /home/vsts/work/1/s/edge-util/src/Microso
ft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 79
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.Put(Byte[] key, Byte[] value) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.
Storage.RocksDb/ColumnFamilyDbStore.cs:line 45
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.Update(TK key, Func`2 updator) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/Entit
yStore.cs:line 76
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesWhenTwinStoreHasTwinAsync(String id, TwinCollection reported, Boolean cloudVerified) in
 /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 334
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.ExecuteOnTwinStoreResultAsync(String id, Func`2 twinStoreHit, Func`1 twinStoreMiss) in /home/vsts/work/1/s/edge
-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 150
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesWithStoreSupportAsync(String id, IMessage reportedProperties) in /home/vsts/work/1/s/ed
ge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 461
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesAsync(String id, IMessage reportedProperties) in /home/vsts/work/1/s/edge-hub/src/Micro
soft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 376
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.DeviceConnected(Object sender, IIdentity device) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devi
ces.Edge.Hub.Core/EdgeHubConnection.cs:line 277
```

Looks like the RocksDB is in an invalid state. Is there a way to reset the RocksDB? I've tried to deinstall and install the Security Daemon, but that didn't help.

**Comment by myagley** [comment]
We believe the underlying bug for this was fixed in #369. However, it hasn't been released yet. It will be in the 1.0.4 release at the end of October.

The only current way to reset RocksDB is the recreate the Edge Hub container.
