### ISSUE TITLE
iotedge send no data over LTE connection

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/iotedge#1154]
## Expected Behavior
iotedge does send data to the iothub whatever there is a LTE or WLAN connection

## Current Behavior
Only if the pc is connected with WLAN data is send reliable

## Steps to Reproduce
Two different Scenarios:

1. First LTE (not working)
    1. Start Windows
    2. Connect to LTE
    3. Send Data
    4. data does not arrive at the iothub
    5. connect to WLAN and disconnect LTE
    6. Send Data
    7. all data is arrive at the iothub
    8. connect to LTE and disconnect WLAN
    9. send data
    10. data does not arrive at the iothub

2. First WLAN (working)
    1. Start Windows
    2. Connect to WLAN
    3. Send Data
    4. data is arrive at the iothub
    5. connect to LTE
    6. Send Data
    7. data is arrive at the iothub

### Device (Host) Operating System
Windows

### Architecture
amd64

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent
1.0

#### Edge Hub
1.0

## Logs

edgeHub
```
2019-04-16 15:38:21.438 +02:00 [INF] - Obtained edge hub config from module twin
2019-04-16 15:38:21.798 +02:00 [INF] - Set the following 1 route(s) in edge hub
2019-04-16 15:38:21.800 +02:00 [INF] - AkrobitFileWatcherToIoTHub: FROM /messages/modules/AkrobitFileWatcher/outputs/* INTO $upstream
2019-04-16 15:38:21.804 +02:00 [INF] - Updated message store TTL to 604800 seconds
2019-04-16 15:38:21.805 +02:00 [INF] - Updated the edge hub store and forward configuration
2019-04-16 15:38:21.805 +02:00 [INF] - Initialized edge hub configuration
2019-04-16 15:38:21.841 +02:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
2019-04-16 15:38:22.050 +02:00 [INF] - Scheduling server certificate renewal for "2019-07-08T10:47:55.0001679Z".
2019-04-16 15:38:22.053 +02:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2019-04-16 15:38:22.066 +02:00 [INF] - Starting MQTT head
2019-04-16 15:38:22.261 +02:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2019-04-16 15:38:22.499 +02:00 [INF] - Starting AMQP head
2019-04-16 15:38:22.519 +02:00 [INF] - Started MQTT head
2019-04-16 15:38:22.742 +02:00 [INF] - Started AMQP head
2019-04-16 15:38:22.751 +02:00 [INF] - Starting HTTP head
2019-04-16 15:38:23.025 +02:00 [INF] - User profile is available. Using '"C:\Users\ContainerUser\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2019-04-16 15:38:23.936 +02:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2019-04-16 15:38:23.988 +02:00 [INF] - Started HTTP head
2019-04-16 15:38:25.344 +02:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
2019-04-16 15:40:20.977 +02:00 [INF] - Attempting to connect to IoT Hub for client akrobit1/$edgeHub via AMQP...
2019-04-16 15:40:40.994 +02:00 [WRN] - Error creating cloud connection for client akrobit1/$edgeHub
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\ModuleClientWrapper.cs:line 48
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\ConnectivityAwareClient.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\ConnectivityAwareClient.cs:line 134
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(ITokenProvider newTokenProvider) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\CloudConnection.cs:line 126
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateNewCloudProxyAsync(ITokenProvider newTokenProvider) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\CloudConnection.cs:line 97
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.Create(IIdentity identity, Action`2 connectionStatusChangedHandler, ITransportSettings[] transportSettings, IMessageConverterProvider messageConverterProvider, IClientProvider clientProvider, ICloudListener cloudListener, ITokenProvider tokenProvider, TimeSpan idleTimeout, Boolean closeOnIdleTimeout, TimeSpan operationTimeout) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\CloudConnection.cs:line 86
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.<>c__DisplayClass15_1.<<Connect>b__2>d.MoveNext() in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\CloudConnectionProvider.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.Connect(IIdentity identity, Action`2 connectionStatusChangedHandler) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\CloudConnectionProvider.cs:line 129
```

## Additional Information

Support Case Number: 119042426000471

**Comment by veyalla** [comment]
@dineshgovindasamy Does Windows container networking work with LTE network adapters?

**Comment by enesuysal** [comment]
@dineshgovindasamy @veyalla  Do you have any update on that issue?

**Comment by dineshgovindasamy** [comment]
I am assuming this is using the NAT network mode. Then it should work with LTE as well as long as the host has network connectivity using LTE adapter. 

Can you collect logs and packet capture and send us the logs, we can take a look?

https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/Debug.md

**Comment by StefanSchoof** [comment]
I can not reproduce this any longer with iotedge 1.0.8
