### ISSUE TITLE
Iot edge module to module communication fail when using custom package. 

### ISSUE THREAD

**Issue by darthkurak** [Azure/iotedge#1195]
Hi! I have some magic voodoo behavior in Iot Edge, spent all day trying figure it out and failed. 
This is really strange, and i would be very thankful for some help. 

I have two modules:
FocusRoomModule in python
And CommunicationModule in c#

The idea is that python module should send messages to communication module where that message is wrapped with additional info and send further to IoT Hub.
Communication module use Nuget package PlatformClient which has all needed logic for that (it uses Device.Client Sdk).
The problem is that messages are not delivered. There are errors in edgeHub. 
The reason is the one line in PlatformClient code: 

var data = JsonConvert.DeserializeObject(messageString);

when i comment it - logs are displayed. 
I checked same scenario within module directly and JsonConvert line doesn't failure delivery.

It seems that somehow same code (moduleClient handling) with JsonConvert line referenced as custom package destroy iot edge but doesn't give any info what is going on. Logs and only on Initialization, no messages from input handler are displayed. No exception.
I really don't have any more idea what is going on here.

Please, help :D

## Expected Behavior
Message from python module should be received in CommunicationModule

## Current Behavior
Message are not delivered.

## Steps to Reproduce
1. Deploy modules
2. See how messages from python module are logged in CommunicationModule

### Device (Host) Operating System
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Architecture
 arm32

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent
Version - 1.0.7.21905529 (f455ae2cd66db716c4bd8e7aaa7984ce092481c0)

#### Edge Hub
 1.0.7.21905529 (f455ae2cd66db716c4bd8e7aaa7984ce092481c0)

#### Docker
docker version
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 17:16:17 2018
 OS/Arch:           linux/arm
 Experimental:      false

## Logs

edgeHub:

```
2019-05-09 17:25:24.935 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Did not receive ack for message 4f8c8047-29ea-434a-bd98-342fa091d18d from device/module kuba_02/CommunicationModule
2019-05-09 17:25:24.941 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint] - Error sending messages to module kuba_02/CommunicationModule
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 363
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 163
2019-05-09 17:25:24.945 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint] - Retrying 1 messages to kuba_02/CommunicationModule/platformInput.
2019-05-09 17:25:26.977 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:25:26.977 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:25:27.073 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:25:27.073 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:25:31.981 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:25:31.982 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:25:36.984 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:25:36.985 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:25:37.074 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:25:37.074 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:25:41.990 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:25:41.990 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:25:46.996 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:25:47.110 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:25:47.110 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:25:47.110 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:25:52.003 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:25:52.003 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:25:57.010 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:25:57.010 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:25:57.114 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:25:57.115 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:25:57.957 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionReauthenticator] - Reauthenticating connected clients
2019-05-09 17:25:57.958 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.IDeviceScopeIdentitiesCache] - Getting service identity for kuba_02/FocusRoomModule
2019-05-09 17:25:57.959 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeAuthenticator] - Client kuba_02/FocusRoomModule in device scope reauthenticated locally.
2019-05-09 17:25:57.959 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Authenticator] - Client kuba_02/FocusRoomModule re-authenticated successfully
2019-05-09 17:25:57.960 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionReauthenticator] - Reauthenticated client kuba_02/FocusRoomModule successfully
2019-05-09 17:25:57.960 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.IDeviceScopeIdentitiesCache] - Getting service identity for kuba_02/CommunicationModule
2019-05-09 17:25:58.075 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeAuthenticator] - Client kuba_02/CommunicationModule in device scope reauthenticated locally.
2019-05-09 17:25:58.076 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Authenticator] - Client kuba_02/CommunicationModule re-authenticated successfully
2019-05-09 17:25:58.077 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionReauthenticator] - Reauthenticated client kuba_02/CommunicationModule successfully
2019-05-09 17:26:02.012 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:02.012 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:07.018 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:07.019 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:07.116 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:26:07.117 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:26:12.019 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:12.020 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:17.026 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:17.026 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:17.146 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:26:17.146 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:26:22.033 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:22.033 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:24.942 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint] - Sending 1 message(s) to module kuba_02/CommunicationModule.
2019-05-09 17:26:24.943 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 0f6e684f-b67f-40fe-af66-3ec2f648a269 to kuba_02/CommunicationModule
2019-05-09 17:26:24.943 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.ClientConnectionHandler] - Sending telemetry message to kuba_02/CommunicationModule
2019-05-09 17:26:24.947 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler] - Sent message with id 0f6e684f-b67f-40fe-af66-3ec2f648a269 to device kuba_02/CommunicationModule
2019-05-09 17:26:27.039 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:27.040 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:27.147 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:26:27.148 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:26:32.045 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:32.046 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:37.052 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:37.053 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:37.149 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:26:37.149 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:26:42.055 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:42.055 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:47.061 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:47.062 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:47.151 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:26:47.152 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:26:52.069 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:52.069 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:54.953 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Did not receive ack for message 0f6e684f-b67f-40fe-af66-3ec2f648a269 from device/module kuba_02/CommunicationModule
2019-05-09 17:26:54.959 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint] - Error sending messages to module kuba_02/CommunicationModule
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 363
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 163
2019-05-09 17:26:54.963 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint] - Retrying 1 messages to kuba_02/CommunicationModule/platformInput.
2019-05-09 17:26:57.077 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:26:57.077 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:26:57.152 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:26:57.153 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:27:02.083 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:27:02.084 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:27:07.091 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:27:07.091 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
2019-05-09 17:27:07.181 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 982 with batch size 10.
2019-05-09 17:27:07.181 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 982.
2019-05-09 17:27:12.097 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id kuba_02/FocusRoomModule
2019-05-09 17:27:12.098 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from kuba_02/FocusRoomModule
```

**Comment by darthkurak** [comment]
This is PlatformClient code which is referenced as nugect package in CommunicationModule project.

```csharp
public class PlatformClient
    {
        private ModuleClient _moduleClient;

        private readonly string _deviceId;

        private readonly ILogger _logger;

        public PlatformClient(ILogger<PlatformClient> logger, string deviceId)
        {
            _logger = logger ?? (ILogger)NullLogger.Instance;
            _deviceId = deviceId; //TODO: Get deviceId and settings from external api
        }

        public async Task Init(string connectionString = null)
        {
            AmqpTransportSettings mqttSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
            ITransportSettings[] settings = { mqttSetting };

            // Open a connection to the Edge runtime
            ModuleClient ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await ioTHubModuleClient.OpenAsync();
            Console.WriteLine("IoT Hub module client initialized.");

            _logger.LogInformation("Setting input handler...");
            // Register callback to be called when a message is received by the module
            await ioTHubModuleClient.SetInputMessageHandlerAsync("platformInput", PipeMessage, ioTHubModuleClient);
            _logger.LogInformation("Setting input handler... DONE");
        }

        private async Task<MessageResponse> PipeMessage(Message message, object userContext)
        {
            _logger.LogInformation("CM: PipeMessage executed");

            var moduleClient = userContext as ModuleClient;
            if (moduleClient == null)
            {
                throw new InvalidOperationException("UserContext doesn't contain " + "expected values");
            }

            byte[] messageBytes = message.GetBytes();
            string messageString = Encoding.UTF8.GetString(messageBytes);
            _logger.LogInformation($"Received message: {messageString}");

            if (!string.IsNullOrEmpty(messageString))
            {
             //   var data = JsonConvert.DeserializeObject(messageString); //this line uncommented cause failure
                var pipeMessage = new Message(messageBytes);
                foreach (var prop in message.Properties)
                {
                    pipeMessage.Properties.Add(prop.Key, prop.Value);
                }
                await moduleClient.SendEventAsync("output1", pipeMessage);
                _logger.LogInformation("Received message sent");
            }

            return MessageResponse.Completed;
        }
    }
```

**Comment by myagley** [comment]
The warnings in the Edge Hub logs aren't errors per se. They are only indicating that an acknowledgement isn't being received in time, which would be consistent with an exception being thrown in the callback.

Is it possible to uncomment that line, wrap it in a try/catch and log the exception that is being thrown?

**Comment by darthkurak** [comment]
You are suggesting that unhandled exceptions in input message handler are not logged?
I tried wrapping it in try /catch and nothing change. Also, notice, that before commented line, there are other logger entries which should be displayed, but they are not. It behave like it never enter callback.

**Comment by darthkurak** [comment]
ls of CommunicationModule container:

```
CommunicationModule                                          System.ComponentModel.dll                       System.Net.Ping.dll                                    System.Security.Cryptography.Native.OpenSsl.a
CommunicationModule.deps.json                                System.Configuration.ConfigurationManager.dll   System.Net.Primitives.dll                              System.Security.Cryptography.Native.OpenSsl.so
CommunicationModule.dll                                      System.Configuration.dll                        System.Net.Requests.dll                                System.Security.Cryptography.OpenSsl.dll
CommunicationModule.pdb                                      System.Console.dll                              System.Net.Security.Native.a                           System.Security.Cryptography.Primitives.dll
CommunicationModule.runtimeconfig.json                       System.Core.dll                                 System.Net.Security.Native.so                          System.Security.Cryptography.ProtectedData.dll
DotNetty.Buffers.dll                                         System.Data.Common.dll                          System.Net.Security.dll                                System.Security.Cryptography.X509Certificates.dll
DotNetty.Codecs.Mqtt.dll                                     System.Data.dll                                 System.Net.ServicePoint.dll                            System.Security.Principal.Windows.dll
DotNetty.Codecs.dll                                          System.Diagnostics.Contracts.dll                System.Net.Sockets.dll                                 System.Security.Principal.dll
DotNetty.Common.dll                                          System.Diagnostics.Debug.dll                    System.Net.WebClient.dll                               System.Security.SecureString.dll
DotNetty.Handlers.dll                                        System.Diagnostics.DiagnosticSource.dll         System.Net.WebHeaderCollection.dll                     System.Security.dll
DotNetty.Transport.dll                                       System.Diagnostics.FileVersionInfo.dll          System.Net.WebProxy.dll                                System.ServiceModel.Web.dll
Lingaro.OpenIoT.CloudEvents.IotHub.dll                       System.Diagnostics.Process.dll                  System.Net.WebSockets.Client.dll                       System.ServiceProcess.dll
Lingaro.OpenIoT.CloudEvents.dll                              System.Diagnostics.StackTrace.dll               System.Net.WebSockets.dll                              System.Text.Encoding.Extensions.dll
Lingaro.OpenIoT.Common.dll                                   System.Diagnostics.TextWriterTraceListener.dll  System.Net.dll                                         System.Text.Encoding.dll
Lingaro.OpenIoT.PlatformClient.dll                           System.Diagnostics.Tools.dll                    System.Numerics.Vectors.dll                            System.Text.RegularExpressions.dll
Microsoft.Azure.Amqp.dll                                     System.Diagnostics.TraceSource.dll              System.Numerics.dll                                    System.Threading.Overlapped.dll
Microsoft.Azure.Devices.Client.dll                           System.Diagnostics.Tracing.dll                  System.ObjectModel.dll                                 System.Threading.Tasks.Dataflow.dll
Microsoft.Azure.Devices.Shared.dll                           System.Drawing.Primitives.dll                   System.Private.CoreLib.dll                             System.Threading.Tasks.Extensions.dll
Microsoft.CSharp.dll                                         System.Drawing.dll                              System.Private.DataContractSerialization.dll           System.Threading.Tasks.Parallel.dll
Microsoft.Extensions.Configuration.Abstractions.dll          System.Dynamic.Runtime.dll                      System.Private.Uri.dll                                 System.Threading.Tasks.dll
Microsoft.Extensions.Configuration.Binder.dll                System.Globalization.Calendars.dll              System.Private.Xml.Linq.dll                            System.Threading.Thread.dll
Microsoft.Extensions.Configuration.EnvironmentVariables.dll  System.Globalization.Extensions.dll             System.Private.Xml.dll                                 System.Threading.ThreadPool.dll
Microsoft.Extensions.Configuration.FileExtensions.dll        System.Globalization.Native.so                  System.Reflection.DispatchProxy.dll                    System.Threading.Timer.dll
Microsoft.Extensions.Configuration.Json.dll                  System.Globalization.dll                        System.Reflection.Emit.ILGeneration.dll                System.Threading.dll
Microsoft.Extensions.Configuration.dll                       System.IO.Compression.Brotli.dll                System.Reflection.Emit.Lightweight.dll                 System.Transactions.Local.dll
Microsoft.Extensions.DependencyInjection.Abstractions.dll    System.IO.Compression.FileSystem.dll            System.Reflection.Emit.dll                             System.Transactions.dll
Microsoft.Extensions.DependencyInjection.dll                 System.IO.Compression.Native.a                  System.Reflection.Extensions.dll                       System.ValueTuple.dll
Microsoft.Extensions.FileProviders.Abstractions.dll          System.IO.Compression.Native.so                 System.Reflection.Metadata.dll                         System.Web.HttpUtility.dll
Microsoft.Extensions.FileProviders.Physical.dll              System.IO.Compression.ZipFile.dll               System.Reflection.Primitives.dll                       System.Web.dll
Microsoft.Extensions.FileSystemGlobbing.dll                  System.IO.Compression.dll                       System.Reflection.TypeExtensions.dll                   System.Windows.dll
Microsoft.Extensions.Logging.Abstractions.dll                System.IO.FileSystem.AccessControl.dll          System.Reflection.dll                                  System.Xml.Linq.dll
Microsoft.Extensions.Logging.Configuration.dll               System.IO.FileSystem.DriveInfo.dll              System.Resources.Reader.dll                            System.Xml.ReaderWriter.dll
Microsoft.Extensions.Logging.Console.dll                     System.IO.FileSystem.Primitives.dll             System.Resources.ResourceManager.dll                   System.Xml.Serialization.dll
Microsoft.Extensions.Logging.dll                             System.IO.FileSystem.Watcher.dll                System.Resources.Writer.dll                            System.Xml.XDocument.dll
Microsoft.Extensions.Options.ConfigurationExtensions.dll     System.IO.FileSystem.dll                        System.Runtime.CompilerServices.Unsafe.dll             System.Xml.XPath.XDocument.dll
Microsoft.Extensions.Options.dll                             System.IO.IsolatedStorage.dll                   System.Runtime.CompilerServices.VisualC.dll            System.Xml.XPath.dll
Microsoft.Extensions.Primitives.dll                          System.IO.MemoryMappedFiles.dll                 System.Runtime.Extensions.dll                          System.Xml.XmlDocument.dll
Microsoft.VisualBasic.dll                                    System.IO.Pipes.AccessControl.dll               System.Runtime.Handles.dll                             System.Xml.XmlSerializer.dll
Microsoft.Win32.Primitives.dll                               System.IO.Pipes.dll                             System.Runtime.InteropServices.RuntimeInformation.dll  System.Xml.dll
Microsoft.Win32.Registry.dll                                 System.IO.UnmanagedMemoryStream.dll             System.Runtime.InteropServices.WindowsRuntime.dll      System.dll
Microsoft.WindowsAzure.Storage.dll                           System.IO.dll                                   System.Runtime.InteropServices.dll                     WindowsBase.dll
Newtonsoft.Json.dll                                          System.Linq.Expressions.dll                     System.Runtime.Loader.dll                              libclrjit.so
SOS.NETCore.dll                                              System.Linq.Parallel.dll                        System.Runtime.Numerics.dll                            libcoreclr.so
System.AppContext.dll                                        System.Linq.Queryable.dll                       System.Runtime.Serialization.Formatters.dll            libcoreclrtraceptprovider.so
System.Buffers.dll                                           System.Linq.dll                                 System.Runtime.Serialization.Json.dll                  libdbgshim.so
System.Collections.Concurrent.dll                            System.Memory.dll                               System.Runtime.Serialization.Primitives.dll            libhostfxr.so
System.Collections.Immutable.dll                             System.Native.a                                 System.Runtime.Serialization.Xml.dll                   libhostpolicy.so
System.Collections.NonGeneric.dll                            System.Native.so                                System.Runtime.Serialization.dll                       libmscordaccore.so
System.Collections.Specialized.dll                           System.Net.Http.Native.a                        System.Runtime.dll                                     libmscordbi.so
System.Collections.dll                                       System.Net.Http.Native.so                       System.Security.AccessControl.dll                      libsos.so
System.ComponentModel.Annotations.dll                        System.Net.Http.dll                             System.Security.Claims.dll                             libsosplugin.so
System.ComponentModel.DataAnnotations.dll                    System.Net.HttpListener.dll                     System.Security.Cryptography.Algorithms.dll            mscorlib.dll
System.ComponentModel.EventBasedAsync.dll                    System.Net.Mail.dll                             System.Security.Cryptography.Cng.dll                   netstandard.dll
System.ComponentModel.Primitives.dll                         System.Net.NameResolution.dll                   System.Security.Cryptography.Csp.dll                   sosdocsunix.txt
System.ComponentModel.TypeConverter.dll                      System.Net.NetworkInformation.dll               System.Security.Cryptography.Encoding.dll
```

**Comment by darthkurak** [comment]
Hi! I have update on this. This is really strange behavior and honestly, I don't have any ideas more, why.
Having:

```csharp
 _logger.LogInformation("Before setinputhandler");
await _moduleClient.SetInputMessageHandlerAsync("platformInput", PipeMessage, _moduleClient);
 _logger.LogInformation("After setinputhandler");
```

and following PipeMessage:

```csharp
private async Task<MessageResponse> PipeMessage(Message message, object userContext)
        {
            try
            {
               _logger.LogInformation("Enter pipe message");
                var messageBytes = message.GetBytes();
                var messageString = Encoding.UTF8.GetString(messageBytes);
                _logger.LogInformation("Before deserialization");
                JsonConvert.DeserializeObject(messageString);
                _logger.LogInformation("After deserialization");
                return MessageResponse.Completed;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unknown error occurred in PipeMessage! Abandon. (will be retried)");
                return MessageResponse.Abandoned;
            }
        }
```
Logs look like: 

> Before setinputhandler
> After setinputhandler

nothing more.

But changing:

`JsonConvert.DeserializeObject(messageString);`

to:

`Deserialize<IDictionary<string, object>>(messageString);`

where:

```csharp
        private T Deserialize<T>(string value)
        {
            var jsonSerializer = JsonSerializer.Create();

            using (var reader = new JsonTextReader(new StringReader(value)))
            {
                return (T)jsonSerializer.Deserialize(reader, typeof(T));
            }
        }
```
works perfectly fine and logs are:

Before setinputhandler
After setinputhandler
Enter pipe message
Before deserialization
After deserialization

and everything seems to work fine.

It seems that somehow JsonConvert.DeserializeObject method does something that "hang" solution. I can't figure out - what.
It only happens when code above is included in iot edge c# module as package!

I wonder if this can happen also using some different code from other libraries. 

Please, take look at this.
Thanks!

**Comment by lt72** [comment]
Closing, as it seems this issue is now stale. Please feel free to re-open as necessary.
