### ISSUE TITLE
Can't deploy modules on Windows

### ISSUE THREAD

**Issue by mbialecka** [Azure/iotedge#1208]
## Expected Behavior

Deployment/redeployment of a module should work reliably.
## Current Behavior

New module or new module version is not deployed
## Steps to Reproduce

1. Have a deployment running
2. Update one of the modules (like change the image URI) through the deployment manifest
3. The updated module is not started up on the edge device

### Device (Host) Operating System

Windows Server 2019
### Architecture

amd64
### Container Operating System

Windows containers
#### iotedged

iotedge 1.0.7~rc2 (03dff5f270fabe34e7903c04e334dca2665780a6)
#### Edge Agent

1.0.7
#### Edge Hub

1.0.7
#### Docker

Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.11.4
  Git commit:       5ec3138
  Built:            Thu Jan 24 17:16:18 2019
  OS/Arch:          windows/amd64
  Experimental:     false
## Logs

https://gist.github.com/mbialecka/5b479750b70148b0dbbf44f0e5164870

## Additional Information

First two deployments after environment startup worked fine. Then, after a couple of hours, the third deployment  didn't go through, it should have happened around 2019-05-13 08:02 mark. Instead, there are many timeout errors in the edgeAgent log.

**Comment by myagley** [comment]
Can you please run `iotedge check` on the device and post the results?

**Comment by mbialecka** [comment]
```
Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
× config.yaml has correct URIs for daemon mgmt endpoint
    docker: invalid reference format.
    See 'docker run --help'.
‼ latest security daemon
    Installed IoT Edge daemon has version 1.0.7~rc2 but version 1.0.7 is available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time
× container time is close to host time
    Could not query local time inside container
‼ DNS server
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry
√ production readiness: container engine
‼ production readiness: logs policy
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
√ host can connect to and perform TLS handshake with IoT Hub MQTT port
× container on the IoT Edge module network can connect to IoT Hub AMQP port
    Container on the nat network could not connect to blobstorage-hub.azure-devices.net:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS port
    Container on the nat network could not connect to blobstorage-hub.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port
    Container on the nat network could not connect to blobstorage-hub.azure-devices.net:8883
√ Edge Hub can bind to ports on host

One or more checks raised errors. Re-run with --verbose for more details.
```

**Comment by veyalla** [comment]
As the connectivity checks suggest, your edge device has connectivity issues from within the container environment. Please follow best practices here as documented  at https://aka.ms/iotedge-prod-checklist-dns (recommend Option 1). 

Confirm the connectivity checks pass, and then perform your testing.

**Comment by mbialecka** [comment]
I saw this issue again yesterday. This time `iotedge check` output was collected and it didn't detect connectivity issues:

```
Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
√ config.yaml has correct URIs for daemon mgmt endpoint
‼ latest security daemon
    Installed IoT Edge daemon has version 1.0.7 but version 1.0.7.1 is available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time
√ container time is close to host time
√ DNS server
‼ production readiness: certificates
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry
√ production readiness: container engine
‼ production readiness: logs policy
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
√ host can connect to and perform TLS handshake with IoT Hub MQTT port
√ container on the IoT Edge module network can connect to IoT Hub AMQP port
√ container on the IoT Edge module network can connect to IoT Hub HTTPS port
√ container on the IoT Edge module network can connect to IoT Hub MQTT port
√ Edge Hub can bind to ports on host

One or more checks raised warnings.
```

In the edgeAgent logs there are many errors like this: 

```
2019-05-28 07:13:57.859 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Service\Program.cs:line 168
```

**Comment by TerryWarwick** [comment]
@mbialecka 

I see you were experiencing this issue on an earlier release candidate.  Are you still encountering these issues on the most recent GA release 1.0.8?

**Comment by lt72** [comment]
Hi @mbialecka did you manage to try 1.0.8?

**Comment by lt72** [comment]
Closing as stale, please re-open as necessary.

**Comment by elliotrpmorris** [comment]
Still have this issue on 1.0.9

**Comment by omarine** [comment]
Hello,

Which dns have you used to resolve connectivity issues from your containers to iothub ?

I am trying to install iotedge runtime behind a proxy as well but i still have different issues including connectivity from containers to Iothub,the host can connect still.

Thanks
