### ISSUE TITLE
Clean up Temporary files created by edgeHub?

### ISSUE THREAD

**Issue by imZack** [Azure/iotedge#122]
## Expected Behavior
- Clean up temporary files routinely
- Maybe make the size of `temporary files` as a configurable variable

## Current Behavior

edgeHub can't work anymore due to no space available

## Steps to Reproduce

1. Run edge modules
2. Until the disks full

I could type `docker rm -f edgeHub` to fix this problem.

### Device (Host) Operating System
Debian 8

### Architecture
arm32

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
```
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Wed Jun 27 00:53:52 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Tue Jun 26 23:27:27 2018
  OS/Arch:      linux/arm
  Experimental: false
```

## Logs

```
2018-08-03 22:12:33.360 +00:00 [WRN] - Error handling device connected event for device Moxa-UC-8112-ME-T-DEMOKIT/modbus
RocksDbSharp.RocksDbException: IO error: No space left on device/tmp/edgeHub/002659.sst: No space left on device
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 79
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.Put(Byte[] key, Byte[] value) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs:line 36
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.Update(TK key, Func`2 updator) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs:line 76
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesWhenTwinStoreHasTwinAsync(String id, TwinCollection reported, Boolean cloudVerified) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 341
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.ExecuteOnTwinStoreResultAsync(String id, Func`2 twinStoreHit, Func`1 twinStoreMiss) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 154
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesWithStoreSupportAsync(String id, IMessage reportedProperties) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 468
   at Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager.UpdateReportedPropertiesAsync(String id, IMessage reportedProperties) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs:line 383
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.DeviceConnected(Object sender, IIdentity device) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 266
```

**Comment by imZack** [comment]
Oh I just realized this might related to persistent storage...let me try this again.

**Comment by imZack** [comment]
@dcrupel yeah the default logging file size/counts configuration for moby/docker is unlimited. It turns out the logs is too big and use all the space.

**Comment by m4masood** [comment]
Hi @dcrupel I had the same issue and I followed https://success.docker.com/article/no-space-left-on-device-error to clear the logs and I did container by container.

**Comment by veyalla** [comment]
@m4masood - Check out this guidance from the production checklist: https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist#place-limits-on-log-size
