### ISSUE TITLE
Excessive IoTHub Device Twin Calls on iotedge version upgrade

### ISSUE THREAD

**Issue by jmbrunskill** [Azure/iotedge#1234]
After upgrading an IoT Edge server to 1.0.7 from 1.0.6 we are seeing a `Reconcile failed because of an exception` error. We also see an excessive number of "Successful twin reads from devices" in IoT Hub. Causing us to go over quota for our IoTHub. After rebooting and upgrading out IoT Hub this issue appeared to be resolved. 

![image](https://user-images.githubusercontent.com/8287373/58062279-db57fe80-7bcd-11e9-843a-2419ab0daa53.png)

Note: Docker was upgraded from Client version 3.0.3 to 3.0.5 at the same time, which might affect this?

I also noticed that the docker tag for edgeAgent and maybe edgeHub didn't seem to be update as part of the deb package install. (I'm a little confused about it edgeHub was updated as I didn't capture status properly before running a docker pull command.

```
# docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/azureiotedge-hub                  1.0                 ed05376f97bd        2 weeks ago         155MB
mcr.microsoft.com/azureiotedge-agent                1.0                 e4917eb97425        3 months ago        146M
```
Then if I run 
```
docker pull mcr.microsoft.com/azureiotedge-agent:1.0
```
I get an updated agent image, which I presume relate to the 1.0.7 release?
```
# docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/azureiotedge-hub                  1.0                 ed05376f97bd        2 weeks ago         155MB
mcr.microsoft.com/azureiotedge-agent                1.0                 219c2aff4adc        2 weeks ago         140MB
```
 Is this tag update required or even recommended?

## Expected Behavior
After upgrading IoT Edge Version, edgeHub connections should be smoothly re-established and shoudn't cause and IoT Hub quota limit to be hit.

## Steps to Reproduce

1. Update ubuntu linux & moby versions (apt-get upgrade -y)
2. Restart iotedge (systemctl restart iotedge)
3. Check runtime status

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64

### Container Operating System
Linux Containers (Microsoft Supplied moby)

#### iotedged
iotedge 1.0.7 (f455ae2cd66db716c4bd8e7aaa7984ce092481c0)

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent                1.0                 e4917eb97425        3 months ago        146MB

#### Edge Hub

mcr.microsoft.com/azureiotedge-hub                  1.0                 ed05376f97bd        2 weeks ago         155MB
mcr.microsoft.com/azureiotedge-hub                  <none>              aa5599173272        3 months ago        161MB

#### Docker

docker version
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 22:01:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Logs

```
2019-03-22 03:11:24.578 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:11:29.583 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:11:34.593 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:11:39.597 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:11:44.601 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:11:49.602 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:11:54.602 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:11:59.602 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:12:04.607 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:12:09.610 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
2019-03-22 03:12:14.615 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115
```

After restart
```
2019-05-21 01:28:50.945 +00:00 [INF] - Error getting cloud connection for device nzs070iotedg01m/messageprocessor4j
Microsoft.Azure.Devices.Client.Exceptions.DeviceMaximumQueueDepthExceededException: {"errorCode":403002,"trackingId":"9bd740deb03c40bb90135ca2382ebaf5-G:10-TimeStamp:05/21/2019 01:40:55-G:10-TimeStamp:05/21/2019 01:40:55","message":"Total number of messages on IotHub '<REMOVED>' exceeded the allocated quota. Max allowed message count : '1200000', current message count : '1343556'. Send and Receive operations are blocked for this hub until the next UTC day. Consider increasing the units for this hub to increase the quota.","timestampUtc":"2019-05-21T01:40:55.7838401Z"}
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs:line 48
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 134
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(ITokenProvider newTokenProvider) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 126
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateNewCloudProxyAsync(ITokenProvider newTokenProvider) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 97
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.Create(IIdentity identity, Action`2 connectionStatusChangedHandler, ITransportSettings[] transportSettings, IMessageConverterProvider messageConverterProvider, IClientProvider clientProvider, ICloudListener cloudListener, ITokenProvider tokenProvider, TimeSpan idleTimeout, Boolean closeOnIdleTimeout, TimeSpan operationTimeout) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 86
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.<>c__DisplayClass15_1.<<Connect>b__2>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.Connect(IIdentity identity, Action`2 connectionStatusChangedHandler) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 129
2019-05-21 01:28:50.946 +00:00 [WRN] - Could not get an active Iot Hub connection for device nzs070iotedg01m/messageprocessor4j
```

**Comment by varunpuranik** [comment]
@jmbrunskill  - Looks like there are multiple things going on here - 
 - The multiple twin calls - this has been fixed in the latest bits, but you need to enable it explicitly (for version 1.0.7, we will make it default in the next version). Please set the environment variable TwinManagerVersion=v2 in EdgeHub. 

- The tags - we recommend using the full version tags (like 1.0.6 or 1.0.7) instead of just the 1.0 tag. The 1.0 tag points to the latest version (currently it points to 1.0.7, when 1.0.8 is released, it will point to that). But since updates are based on the actual image name, it does not detect that the edgeAgent needs to be updated if you use the 1.0 tag. So please set the images to use 1.0.7 and you should be good. 

- As for the reconcile failing because of the timeout, I have actually not seen this before. Does it repro consistently for you? It is possible you were running into the quota issue causing the EdgeAgent reconcile to fail. Can you try the above 2 mitigations and see if this issue repros?

**Comment by jmbrunskill** [comment]
Thanks @varunpuranik I'll try that TwinManagerVersion=v2 in our environment.
I have more devices that haven't been updated, so I can try reproducing this issue, the Quota Limit issue is definitely causing confusion as that may be affecting IoT Edge. 

Will do another update and let you know the results.

**Comment by jmbrunskill** [comment]
After upgrading the next site, the reconcile failed issue didn't re-occur. Perhaps this was because the previous time we were over our quota? 
We'll keep monitoring it to see if this re-occurs and hopefully can provide some more timely logs.

**Comment by myagley** [comment]
A release candidate for `1.0.8` was just released. You can try it out using the `1.0.8-rc1` tag on your images.

**Comment by jmbrunskill** [comment]
Thanks Mike,

We'll try this out tomorrow.

**Comment by jmbrunskill** [comment]
@myagley we've been running 1.0.8-rc1 in our dev environment for a couple of days. Deployment seemed to go smoothly and no evidence of this re-occuring yet. Not sure if the same conditions have been fully replicated though. I'll try to force a IoTHub quota limit issue tomorrow in dev to confirm this doesn't re-occur in that situation, but so far so good.

**Comment by arsing** [comment]
1.0.8 is released.
