### ISSUE TITLE
EdgeHub stops sending data after connection went down and then up using MQTT

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#1261]
EdgeHub stop sending data when connection to internet went down and later was brought back when using MQTT for UpstreamProtocol.

## Expected Behavior
edgehub should gracefully reconnect and send messages that were buffered

## Current Behavior
It throws exception that it is non retryable but in the message exception the inner exception is transient: 

2019-05-27 13:06:34.730 +00:00 [INF] - Device connection removed for device testedgedeviceadam/DispatcherModule
2019-05-27 13:06:34.767 +00:00 [INF] - Client testedgedeviceadam/DispatcherModule in device scope authenticated locally.
2019-05-27 13:06:34.767 +00:00 [INF] - Successfully generated identity for clientId testedgedeviceadam/DispatcherModule and username iot/testedgedeviceadam/DispatcherModule/?api-version=2018-06-30&DeviceClientType=.NET%2F1.20.0%20%28.NET%20Core%204.6.00001.0%3B%20Linux%204.15.0-50-generic%20%2354-Ubuntu%20SMP%20Mon%20May%206%2018%3A46%3A08%20UTC%202019%3B%20X64%29
2019-05-27 13:06:34.767 +00:00 [INF] - ClientAuthenticated, testedgedeviceadam/DispatcherModule, 1a615adc
2019-05-27 13:06:34.768 +00:00 [INF] - New device connection for device testedgedeviceadam/DispatcherModule
2019-05-27 13:06:34.768 +00:00 [INF] - Bind device proxy for device testedgedeviceadam/DispatcherModule
2019-05-27 13:06:34.768 +00:00 [INF] - Binding message channel for device Id testedgedeviceadam/DispatcherModule
2019-05-27 13:06:34.769 +00:00 [INF] - Processing subscriptions TwinResponse, DesiredPropertyUpdates for client testedgedeviceadam/DispatcherModule.
2019-05-27 13:06:34.769 +00:00 [INF] - Set subscriptions from session state for testedgedeviceadam/DispatcherModule
2019-05-27 13:06:34.771 +00:00 [INF] - Processing subscriptions TwinResponse, DesiredPropertyUpdates for client testedgedeviceadam/DispatcherModule.
2019-05-27 13:06:34.771 +00:00 [INF] - Set subscriptions from session state for testedgedeviceadam/DispatcherModule
2019-05-27 13:06:51.968 +00:00 [WRN] - **Non retryable exception occurred while sending message.
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.** ---> System.Net.Sockets.SocketException: Connection reset by peer
   at DotNetty.Transport.Channels.Sockets.TcpSocketChannel.DoReadBytes(IByteBuffer byteBuf)
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 134
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SendMessageAsync(IMessage inputMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 135
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SendMessageAsync(IMessage inputMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 141
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.<>c__DisplayClass22_0.<<ExecuteOperation>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.ExecuteOperation[T](Func`2 func, String operation) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 71
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.CloudEndpoint.CloudMessageProcessor.<>c__DisplayClass12_0.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/CloudEndpoint.cs:line 146

## Steps to Reproduce

1. Start sending data to edgeHub
2. ifconfig eth0 down wait for 30 min
3. ifconfig eth0 up
4. check edgeHub logs

### Device (Host) Operating System

Ubuntu 18.04.2
### Architecture

amd64
### Container Operating System

Linux
#### iotedged
iotedge 1.0.7 (f455ae2cd66db716c4bd8e7aaa7984ce092481c0)

#### Edge Agent
1.0.7.1.22377503

#### Edge Hub
Version - 1.0.7.1.22377503

#### Docker
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 22:01:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by AdamMachera** [comment]
This issue was related to problem that hyper-v was somehow unable to bridge properly wifi connection to underlying linux machine.
