### ISSUE TITLE
Linux arm64 device IoT Edge certification fail

### ISSUE THREAD

**Issue by githaff** [Azure/iotedge#1295]
## Expected Behavior
Certification process provides a connection string which should be used on the end device. I assume, device with provided connection string pulls required images, runs them and responses to certification service.

## Current Behavior
iotedge service searches for "mcr.microsoft.com/azureiotedge-agent:1.0" and fails to find it for the required platform.

## Steps to Reproduce
1. start device certificatification process from the partner dashboard
2. insert provided Connection String into /etc/iotedge/config.yaml on the device
3. select Ubuntu 18.04 system and start process
3. restart iotedge with "systemctl restart iotedge"
4. certification process expects answer from the device and fails after some time with messages:
```
4:47:03 PM  Checking if valid Azure IoT Edge runtime is present...
4:48:06 PM Azure IoT Edge runtime validated. Deploying test module to device...
4:53:09 PM Failed to deploy test module to device
```

### Output of `iotedge check --output json`

<details>
<summary>Click here</summary>

```json
{"os_info":{"id":"lsdk","version_id":null,"bitness":64},"checks":{"certificates-expiry":{"result":"ok"},"certificates-quickstart":{"result":"warning","details":["Device is using self-signed, automatically generated certs.\nPlease see https://aka.ms/iotedge-prod-checklist-certs for best practices."]},"config-yaml-well-formed":{"result":"ok"},"connect-management-uri":{"result":"error","details":["Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n","docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n"]},"connection-string":{"result":"ok"},"container-default-connect-iothub-amqp":{"result":"error","details":["Container on the default network could not connect to aics-prod-hub.azure-devices.net:5671","docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n"]},"container-default-connect-iothub-https":{"result":"error","details":["Container on the default network could not connect to aics-prod-hub.azure-devices.net:443","docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n"]},"container-default-connect-iothub-mqtt":{"result":"error","details":["Container on the default network could not connect to aics-prod-hub.azure-devices.net:8883","docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n"]},"container-engine-dns":{"result":"warning","details":["Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.\nPlease see https://aka.ms/iotedge-prod-checklist-dns for best practices.\nYou can ignore this warning if you are setting DNS server per module in the Edge deployment.","Could not open container engine config file /etc/docker/daemon.json","No such file or directory (os error 2)"]},"container-engine-is-moby":{"result":"warning","details":["Device is not using a production-supported container engine (moby-engine).\nPlease see https://aka.ms/iotedge-prod-checklist-moby for details."]},"container-engine-logrotate":{"result":"warning","details":["Container engine is not configured to rotate module logs which may cause it run out of disk space.\nPlease see https://aka.ms/iotedge-prod-checklist-logs for best practices.\nYou can ignore this warning if you are setting log policy per module in the Edge deployment.","Could not open container engine config file /etc/docker/daemon.json","No such file or directory (os error 2)"]},"container-engine-uri":{"result":"ok"},"container-local-time":{"result":"error","details":["Could not query local time inside container","docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n"]},"container-module-connect-iothub-amqp":{"result":"error","details":["Container on the azure-iot-edge network could not connect to aics-prod-hub.azure-devices.net:5671","docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n"]},"container-module-connect-iothub-https":{"result":"error","details":["Container on the azure-iot-edge network could not connect to aics-prod-hub.azure-devices.net:443","docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n"]},"container-module-connect-iothub-mqtt":{"result":"error","details":["Container on the azure-iot-edge network could not connect to aics-prod-hub.azure-devices.net:8883","docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev' locally\ndocker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev not found.\nSee 'docker run --help'.\n"]},"edgehub-host-ports":{"result":"error","details":["Could not check current state of Edge Hub container","docker returned exit code: 1, stderr = Error: No such object: edgeHub\n"]},"host-connect-iothub-amqp":{"result":"ok"},"host-connect-iothub-https":{"result":"ok"},"host-connect-iothub-mqtt":{"result":"ok"},"host-local-time":{"result":"ok"},"hostname":{"result":"ok"},"iotedged-version":{"result":"warning","details":["Installed IoT Edge daemon has version 1.0.8~dev but version 1.0.7.1 is available.\nPlease see https://aka.ms/iotedge-update-runtime for update instructions."]}}}
```
</details>

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
arm64

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.8~dev

#### Edge Agent
1.0.4

#### Edge Hub
1.0.4

#### Docker

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:12:09 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:59:19 2019
  OS/Arch:          linux/arm64
  Experimental:     false
```

## Logs

<details>
<summary>iotedged logs</summary>

```
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Configuring certificates...
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Finished configuring certificates.
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Initializing hsm...
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Finished initializing hsm.
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Detecting if configuration file has changed...
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Change to configuration file detected.
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Removing all modules...
Jun 05 13:02:12 localhost iotedged[3857]: 2019-06-05T13:02:12Z [INFO] - Finished removing modules.
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Provisioning edge device...
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Manually provisioning device "R0CaRWmIlW" in hub "aics-prod-hub.azure-devices.net"
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Finished provisioning edge device.
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Starting management API...
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Starting workload API...
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Starting watchdog with 60 second frequency...
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Listening on fd://iotedge.mgmt.socket/ with 1 thread for management API.
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Listening on fd://iotedge.socket/ with 1 thread for workload API.
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Checking edge runtime status
Jun 05 13:02:21 localhost iotedged[3857]: 2019-06-05T13:02:21Z [INFO] - Creating and starting edge runtime module edgeAgent
Jun 05 13:02:22 localhost iotedged[3857]: 2019-06-05T13:02:22Z [INFO] - Updating identity for module $edgeAgent
Jun 05 13:02:23 localhost iotedged[3857]: 2019-06-05T13:02:23Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0.4-linux-arm32v7...
Jun 05 13:04:09 localhost iotedged[3857]: 2019-06-05T13:04:09Z [INFO] - Successfully pulled image mcr.microsoft.com/azureiotedge-agent:1.0.4-linux-arm32v7
Jun 05 13:04:09 localhost iotedged[3857]: 2019-06-05T13:04:09Z [INFO] - Creating module edgeAgent...
Jun 05 13:04:17 localhost iotedged[3857]: 2019-06-05T13:04:17Z [INFO] - Successfully created module edgeAgent
Jun 05 13:04:17 localhost iotedged[3857]: 2019-06-05T13:04:17Z [INFO] - Starting module edgeAgent...
Jun 05 13:04:21 localhost iotedged[3857]: 2019-06-05T13:04:21Z [INFO] - Successfully started module edgeAgent
Jun 05 13:04:21 localhost iotedged[3857]: 2019-06-05T13:04:21Z [INFO] - Checking edge runtime status
Jun 05 13:04:21 localhost iotedged[3857]: 2019-06-05T13:04:21Z [INFO] - Edge runtime is running.
Jun 05 13:04:21 localhost iotedged[3857]: 2019-06-05T13:04:21Z [INFO] - Checking edge runtime status
Jun 05 13:04:21 localhost iotedged[3857]: 2019-06-05T13:04:21Z [INFO] - Edge runtime is running.
Jun 05 13:04:36 localhost iotedged[3857]: 2019-06-05T13:04:36Z [INFO] - Querying system info...
Jun 05 13:04:36 localhost iotedged[3857]: 2019-06-05T13:04:36Z [INFO] - Successfully queried system info
Jun 05 13:04:36 localhost iotedged[3857]: 2019-06-05T13:04:36Z [INFO] - [mgmt] - - - [2019-06-05 13:04:36.706282689 UTC] "GET /systeminfo?api-version=2018-06-28 HTTP/1.1" 200 OK 65 "-" "-" pid(4025)
Jun 05 13:04:37 localhost iotedged[3857]: 2019-06-05T13:04:37Z [INFO] - [work] - - - [2019-06-05 13:04:37.666413964 UTC] "POST /modules/%24edgeAgent/genid/636953354475448723/sign?api-version=2018-06-28 HTTP/1.1" 200 OK 57 "-" "-" pid(4025)
Jun 05 13:04:39 localhost iotedged[3857]: 2019-06-05T13:04:39Z [INFO] - [mgmt] - - - [2019-06-05 13:04:39.354079707 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:04:51 localhost iotedged[3857]: 2019-06-05T13:04:51Z [INFO] - [mgmt] - - - [2019-06-05 13:04:51.691449698 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:04:56 localhost iotedged[3857]: 2019-06-05T13:04:56Z [INFO] - [mgmt] - - - [2019-06-05 13:04:56.787652374 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:01 localhost iotedged[3857]: 2019-06-05T13:05:01Z [INFO] - [mgmt] - - - [2019-06-05 13:05:01.823723049 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:06 localhost iotedged[3857]: 2019-06-05T13:05:06Z [INFO] - [mgmt] - - - [2019-06-05 13:05:06.853312362 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:11 localhost iotedged[3857]: 2019-06-05T13:05:11Z [INFO] - [mgmt] - - - [2019-06-05 13:05:11.898156002 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:16 localhost iotedged[3857]: 2019-06-05T13:05:16Z [INFO] - [mgmt] - - - [2019-06-05 13:05:16.933193500 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:21 localhost iotedged[3857]: 2019-06-05T13:05:21Z [INFO] - Checking edge runtime status
Jun 05 13:05:22 localhost iotedged[3857]: 2019-06-05T13:05:21Z [INFO] - Edge runtime is running.
Jun 05 13:05:22 localhost iotedged[3857]: 2019-06-05T13:05:21Z [INFO] - [mgmt] - - - [2019-06-05 13:05:21.976733705 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:27 localhost iotedged[3857]: 2019-06-05T13:05:27Z [INFO] - [mgmt] - - - [2019-06-05 13:05:27.003683263 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:32 localhost iotedged[3857]: 2019-06-05T13:05:32Z [INFO] - [mgmt] - - - [2019-06-05 13:05:32.041842957 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:37 localhost iotedged[3857]: 2019-06-05T13:05:37Z [INFO] - [mgmt] - - - [2019-06-05 13:05:37.074111342 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:42 localhost iotedged[3857]: 2019-06-05T13:05:42Z [INFO] - [mgmt] - - - [2019-06-05 13:05:42.108938643 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:47 localhost iotedged[3857]: 2019-06-05T13:05:47Z [INFO] - [mgmt] - - - [2019-06-05 13:05:47.142680811 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:52 localhost iotedged[3857]: 2019-06-05T13:05:52Z [INFO] - [mgmt] - - - [2019-06-05 13:05:52.175374471 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:57 localhost iotedged[3857]: 2019-06-05T13:05:57Z [INFO] - [mgmt] - - - [2019-06-05 13:05:57.221387059 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4025)
Jun 05 13:05:58 localhost iotedged[3857]: 2019-06-05T13:05:58Z [INFO] - [work] - - - [2019-06-05 13:05:58.008006624 UTC] "POST /modules/%24edgeAgent/genid/636953354475448723/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1261 "-" "-" pid(4025)
Jun 05 13:05:59 localhost iotedged[3857]: 2019-06-05T13:05:59Z [INFO] - [mgmt] - - - [2019-06-05 13:05:59.289393853 UTC] "GET /identities/?api-version=2018-06-28 HTTP/1.1" 200 OK 210 "-" "-" pid(4025)
Jun 05 13:05:59 localhost iotedged[3857]: 2019-06-05T13:05:59Z [INFO] - [mgmt] - - - [2019-06-05 13:05:59.980725220 UTC] "PUT /identities/%24edgeHub?api-version=2018-06-28 HTTP/1.1" 200 OK 98 "-" "-" pid(4025)
Jun 05 13:06:00 localhost iotedged[3857]: 2019-06-05T13:06:00Z [INFO] - [mgmt] - - - [2019-06-05 13:06:00.182901124 UTC] "POST /identities/?api-version=2018-06-28 HTTP/1.1" 200 OK 100 "-" "-" pid(4025)
Jun 05 13:06:01 localhost iotedged[3857]: 2019-06-05T13:06:01Z [INFO] - Updating and starting module edgeAgent
Jun 05 13:06:01 localhost iotedged[3857]: 2019-06-05T13:06:01Z [INFO] - Removing module edgeAgent...
Jun 05 13:06:03 localhost iotedged[3857]: 2019-06-05T13:06:03Z [INFO] - Successfully removed module edgeAgent
Jun 05 13:06:03 localhost iotedged[3857]: 2019-06-05T13:06:03Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0...
Jun 05 13:06:03 localhost iotedged[3857]: 2019-06-05T13:06:03Z [WARN] - Could not pull image mcr.microsoft.com/azureiotedge-agent:1.0
Jun 05 13:06:03 localhost iotedged[3857]: 2019-06-05T13:06:03Z [WARN] -         caused by: no matching manifest for unknown in the manifest list entries
Jun 05 13:06:03 localhost iotedged[3857]: 2019-06-05T13:06:03Z [INFO] - [mgmt] - - - [2019-06-05 13:06:03.998299416 UTC] "PUT /modules/edgeAgent?api-version=2018-06-28&start=True HTTP/1.1" 500 Internal Server Error 203 "-" "-" pid(4025)
Jun 05 13:06:03 localhost iotedged[3857]: 2019-06-05T13:06:03Z [ERR!] - server connection error: (unknown)
Jun 05 13:06:03 localhost iotedged[3857]: 2019-06-05T13:06:03Z [ERR!] - error writing a body to connection: Broken pipe (os error 32)
Jun 05 13:06:21 localhost iotedged[3857]: 2019-06-05T13:06:21Z [INFO] - Checking edge runtime status
Jun 05 13:06:21 localhost iotedged[3857]: 2019-06-05T13:06:21Z [INFO] - Creating and starting edge runtime module edgeAgent
Jun 05 13:06:22 localhost iotedged[3857]: 2019-06-05T13:06:22Z [INFO] - Updating identity for module $edgeAgent
Jun 05 13:06:22 localhost iotedged[3857]: 2019-06-05T13:06:22Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0.4-linux-arm32v7...
Jun 05 13:06:22 localhost iotedged[3857]: 2019-06-05T13:06:22Z [INFO] - Successfully pulled image mcr.microsoft.com/azureiotedge-agent:1.0.4-linux-arm32v7
Jun 05 13:06:22 localhost iotedged[3857]: 2019-06-05T13:06:22Z [INFO] - Creating module edgeAgent...
Jun 05 13:06:24 localhost iotedged[3857]: 2019-06-05T13:06:24Z [INFO] - Successfully created module edgeAgent
Jun 05 13:06:24 localhost iotedged[3857]: 2019-06-05T13:06:24Z [INFO] - Starting module edgeAgent...
Jun 05 13:06:26 localhost iotedged[3857]: 2019-06-05T13:06:26Z [INFO] - Successfully started module edgeAgent
Jun 05 13:06:41 localhost iotedged[3857]: 2019-06-05T13:06:41Z [INFO] - Querying system info...
Jun 05 13:06:41 localhost iotedged[3857]: 2019-06-05T13:06:41Z [INFO] - Successfully queried system info
Jun 05 13:06:41 localhost iotedged[3857]: 2019-06-05T13:06:41Z [INFO] - [mgmt] - - - [2019-06-05 13:06:41.724648615 UTC] "GET /systeminfo?api-version=2018-06-28 HTTP/1.1" 200 OK 65 "-" "-" pid(4269)
Jun 05 13:06:42 localhost iotedged[3857]: 2019-06-05T13:06:42Z [INFO] - [work] - - - [2019-06-05 13:06:42.766864388 UTC] "POST /modules/%24edgeAgent/genid/636953354475448723/sign?api-version=2018-06-28 HTTP/1.1" 200 OK 57 "-" "-" pid(4269)
Jun 05 13:06:44 localhost iotedged[3857]: 2019-06-05T13:06:44Z [INFO] - [mgmt] - - - [2019-06-05 13:06:44.417529146 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4269)
Jun 05 13:06:56 localhost iotedged[3857]: 2019-06-05T13:06:56Z [INFO] - [mgmt] - - - [2019-06-05 13:06:56.892762271 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 465 "-" "-" pid(4269)
Jun 05 13:06:57 localhost iotedged[3857]: 2019-06-05T13:06:57Z [INFO] - [work] - - - [2019-06-05 13:06:57.674245674 UTC] "POST /modules/%24edgeAgent/genid/636953354475448723/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1261 "-" "-" pid(4269)
Jun 05 13:06:58 localhost iotedged[3857]: 2019-06-05T13:06:58Z [INFO] - [mgmt] - - - [2019-06-05 13:06:58.318589073 UTC] "GET /identities/?api-version=2018-06-28 HTTP/1.1" 200 OK 310 "-" "-" pid(4269)
Jun 05 13:06:58 localhost iotedged[3857]: 2019-06-05T13:06:58Z [INFO] - [mgmt] - - - [2019-06-05 13:06:58.810763372 UTC] "PUT /identities/tempSensor?api-version=2018-06-28 HTTP/1.1" 200 OK 100 "-" "-" pid(4269)
Jun 05 13:06:59 localhost iotedged[3857]: 2019-06-05T13:06:59Z [INFO] - [mgmt] - - - [2019-06-05 13:06:59.070840638 UTC] "PUT /identities/%24edgeHub?api-version=2018-06-28 HTTP/1.1" 200 OK 98 "-" "-" pid(4269)
Jun 05 13:07:00 localhost iotedged[3857]: 2019-06-05T13:07:00Z [INFO] - Updating and starting module edgeAgent
Jun 05 13:07:00 localhost iotedged[3857]: 2019-06-05T13:07:00Z [INFO] - Removing module edgeAgent...
Jun 05 13:07:01 localhost iotedged[3857]: 2019-06-05T13:07:01Z [INFO] - Successfully removed module edgeAgent
Jun 05 13:07:01 localhost iotedged[3857]: 2019-06-05T13:07:01Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0...
Jun 05 13:07:02 localhost iotedged[3857]: 2019-06-05T13:07:02Z [WARN] - Could not pull image mcr.microsoft.com/azureiotedge-agent:1.0
Jun 05 13:07:02 localhost iotedged[3857]: 2019-06-05T13:07:02Z [WARN] -         caused by: no matching manifest for unknown in the manifest list entries
Jun 05 13:07:02 localhost iotedged[3857]: 2019-06-05T13:07:02Z [INFO] - [mgmt] - - - [2019-06-05 13:07:02.074554591 UTC] "PUT /modules/edgeAgent?api-version=2018-06-28&start=True HTTP/1.1" 500 Internal Server Error 203 "-" "-" pid(4269)
Jun 05 13:07:02 localhost iotedged[3857]: 2019-06-05T13:07:02Z [ERR!] - server connection error: (unknown)
Jun 05 13:07:02 localhost iotedged[3857]: 2019-06-05T13:07:02Z [ERR!] - error writing a body to connection: Broken pipe (os error 32)
...
```
</details>

## Additional Information
I have seen the same behaviour while manually testing iotedge integration on our device with our own hub.

As I understand it is caused by the fact that azureiotedge-agent is marked as multi-arch but there is no version for arm64. Thus during manual testing I have configured a 32bit vertion azureiotedge-agent:1.0.4-linux-arm32v7 both in config.yaml and in Azure IoT Hub when registering device. During certification process there is no place to set the agent version on the 'other side', only in config.yaml.

If I understand correctly, that is the same issue why `iotedge check` failes. That is mcr.microsoft.com/azureiotedge-diagnostics:1.0.8-dev is not available for arm64.

Is there any way to somehow force or work around this behavior?

**Comment by myagley** [comment]
IoT Edge doesn't officially support arm64. Version 1.0.8 will add preview support for arm64. A release candidate was released yesterday. You can find arm64 packages here: https://github.com/Azure/azure-iotedge/releases/tag/1.0.8-rc1

Note that you will need to use the `1.0.8-rc1` image tag, as we only bump `1.0` tag for GA releases.

Out of curiosity, where did you get the `1.0.8~dev` version of `iotedged`? Did you build from source?

**Comment by githaff** [comment]
Thanks, will check out the rc1.
Yes, I iotedge was built from source.

**Comment by githaff** [comment]
I have moved to the 1.0.8-rc1 and respective agent image (mcr.microsoft.com/azureiotedge-agent:1.0.8-rc1). I see now that that this image has a arm64 version. But this still doesn't solve my issue. The issue I am having is particularly with the Edge certification process. What I can see is:

1. I configure my connection string and 1.0.8-rc1 agent image.
2. I create default empty device on the EdgeHub without changing anything. So it ends up with $edgeAgent module having desired image mcr.microsoft.com/azureiotedge-agent:1.0 and reported image: mcr.microsoft.com/azureiotedge-agent:1.0.8-rc1. As a result on the device side I see (in logs of the agent container):

```
<6> 2019-06-07 19:04:20.328 +00:00 [INF] - Started operation refresh twin config
<6> 2019-06-07 19:04:20.772 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2019-06-07 19:04:29.892 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2019-06-07 19:04:36.804 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2019-06-07 19:04:37.608 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2019-06-07 19:04:38.294 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 2 and reported properties version 3.
<6> 2019-06-07 19:04:41.776 +00:00 [INF] - Plan execution started for deployment 2
<6> 2019-06-07 19:04:41.990 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare update module edgeAgent]\n  [[Null]]\n  [Update and start module edgeAgent]\n)"
<3> 2019-06-07 19:05:00.954 +00:00 [ERR] - Executing command for operation ["update Edge Agent"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling prepare update for module module edgeAgent: Could not prepare update for module "edgeAgent"
	caused by: Could not pull image mcr.microsoft.com/azureiotedge-agent:1.0
	caused by: no matching manifest for unknown in the manifest list entries, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 123
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.PrepareUpdateAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 185
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
<3> 2019-06-07 19:05:01.150 +00:00 [ERR] - Step failed in deployment 2, continuing execution. Failure when running command Command Group: (
  [Prepare update module edgeAgent]
  [[Null]]
  [Update and start module edgeAgent]
). Will retry in 00s.
...
```

3. It is easily fixable for my own edge hub. Because I can set the same mcr.microsoft.com/azureiotedge-agent:1.0.8-rc1 in the $edgeAgent module (same with $edgeHub). But during edge certification process I don't have such option. It just provides a connection string. And the iotedged tries to pull the 1.0 version which it doesn't find, as can be seen in logs above.

So my main question is if there is a way to somehow 'force' this desired module version? Or maybe misunderstand the issue altogether altogether?

**Comment by myagley** [comment]
We just released the very first release candidate with `arm64` support a couple of days ago and it is still in preview. Because this is a release candidate, `1.0.8-rc1` doesn't map to the `1.0` tag yet. This will be updated when version `1.0.8` GA's in a couple of weeks. Your specific issue should be fixed then.

Note that `1.0.8` going GA does not mean that `arm64` support is GA. `arm64` support will remain in preview for several more months. While it may be interesting to try the certification process early, I would expect some rough edges while we iron out this support. And certainly no `arm64` devices will be considered certified until `arm64` support in general is GA.

**Comment by githaff** [comment]
Thanks for the help! The question is cleared.
