### ISSUE TITLE
Running iotedge on an ArmV7 embedded Device

### ISSUE THREAD

**Issue by OWarneke** [Azure/iotedge#1330]
## Expected Behavior
The edgeAgent should connect and then pull Configurations / edgeHub and other  

## Current Behavior
edgeAgent runs but does not recieve work.
HTTP/1.1" 404 Not Found 202 "-" "-" pid(123)

## Steps to Reproduce

1. Get my Device and Linux distribution 
2. Start edge Agent through iotedged -c /etc/config.yaml
3. modify permissions on unix///socket files

## Context (Environment)
Yocto Linux distribution without systemd  with armv7 

### Output of `iotedge check --verbose`

<details>
<summary>Click here</summary>

```json
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
√ config.yaml has correct URIs for daemon mgmt endpoint
‼ latest security daemon
    Installed IoT Edge daemon has version 1.0.7 but version 1.0.7.1 is available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time
^C
root@axcf2152:/opt# iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
√ config.yaml has correct URIs for daemon mgmt endpoint
‼ latest security daemon
    Installed IoT Edge daemon has version 1.0.7 but version 1.0.7.1 is available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time
√ container time is close to host time
√ DNS server
‼ production readiness: certificates
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry
‼ production readiness: container engine
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
√ host can connect to and perform TLS handshake with IoT Hub MQTT port
√ container on the default network can connect to IoT Hub AMQP port
√ container on the default network can connect to IoT Hub HTTPS port
√ container on the default network can connect to IoT Hub MQTT port
√ container on the IoT Edge module network can connect to IoT Hub AMQP port
√ container on the IoT Edge module network can connect to IoT Hub HTTPS port
√ container on the IoT Edge module network can connect to IoT Hub MQTT port
√ Edge Hub can bind to ports on host

One or more checks raised warnings.

```
</details>

### Device (Host) Operating System
Linux axcf2152 4.14.115-rt59-pxc #1 SMP PREEMPT RT Wed May 29 09:06:21 UTC 2019 armv7l armv7l armv7l GNU/Linux

### Architecture
 arm32

#### iotedged
iotedge 1.0.7

#### Edge Agent
Tried a lot
1.0.0
1.0.7
 1.0.8-rc1-linux-arm32v7 

#### Edge Hub
should be downloaded after agent connects?
but I also tried downloading and running the edgeHub manually.
1.0
1.0.7
1.0.8-rc1-linux-arm32v7

#### Docker
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.11.1
 Git commit:        51668a30
 Built:             Wed Jun  5 09:22:53 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.1
  Git commit:       489b8eda6674523df8b82a210399b7d2954427d0
  Built:            Wed Jun  5 09:20:18 2019
  OS/Arch:          linux/arm
  Experimental:     false

```
provisioning:
  source: "manual"
  device_connection_string: "HostName=myhostname.azure-devices.net;DeviceId=mydeviceID;SharedAccessKey=5aDEADb6xkDAlAX/JCODEx73DEADMXUSU0k="
agent:
  name: "edgeAgent"
  type: "docker"
  env: {}
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0.8-rc1-linux-arm32v7"
    auth: {}
hostname: "axcf2152"
connect:
  management_uri: "unix:///var/run/iotedge/mgmt.sock"
  workload_uri: "unix:///var/run/iotedge/workload.sock"
listen:
  management_uri: "unix:///var/run/iotedge/mgmt.sock"
  workload_uri: "unix:///var/run/iotedge/workload.sock"
homedir: "/var/lib/iotedge"
moby_runtime:
  docker_uri: "/var/run/docker.sock"
  network: "azure-iot-edge"

```

## Logs

<details>
<summary>iotedged logs</summary>

```
<6>2019-06-13T07:16:10Z [INFO] - Using config file: /etc/iotedge/config.yaml
<6>2019-06-13T07:16:10Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2019-06-13T07:16:10Z [INFO] - Version - 1.0.7
<6>2019-06-13T07:16:10Z [INFO] - Using runtime network id azure-iot-edge
<6>2019-06-13T07:16:10Z [INFO] - Initializing the module runtime...
<6>2019-06-13T07:16:10Z [INFO] - Initializing module runtime...
<6>2019-06-13T07:16:10Z [INFO] - Successfully initialized module runtime
<6>2019-06-13T07:16:10Z [INFO] - Finished initializing the module runtime.
<6>2019-06-13T07:16:10Z [INFO] - Configuring /var/lib/iotedge as the home directory.
<6>2019-06-13T07:16:10Z [INFO] - Configuring certificates...
<6>2019-06-13T07:16:10Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
<6>2019-06-13T07:16:10Z [INFO] - Finished configuring certificates.
<6>2019-06-13T07:16:10Z [INFO] - Initializing hsm...
<6>2019-06-13T07:16:10Z [INFO] - Finished initializing hsm.
<6>2019-06-13T07:16:10Z [INFO] - Detecting if configuration file has changed...
<6>2019-06-13T07:16:10Z [INFO] - No change to configuration file detected.
<6>2019-06-13T07:16:10Z [INFO] - Obtaining workload CA succeeded.
<6>2019-06-13T07:16:10Z [INFO] - Provisioning edge device...
<6>2019-06-13T07:16:10Z [INFO] - Manually provisioning device "PlcNextAlpha" in hub "PxCIoTHUB.azure-devices.net"
<6>2019-06-13T07:16:10Z [INFO] - Finished provisioning edge device.
<6>2019-06-13T07:16:10Z [INFO] - Starting management API...
<6>2019-06-13T07:16:10Z [INFO] - Starting workload API...
<6>2019-06-13T07:16:10Z [INFO] - Starting watchdog with 60 second frequency...
<6>2019-06-13T07:16:10Z [INFO] - Listening on unix:///var/run/iotedge/mgmt.sock with 1 thread for management API.
<6>2019-06-13T07:16:10Z [INFO] - Listening on unix:///var/run/iotedge/workload.sock with 1 thread for workload API.
<6>2019-06-13T07:16:10Z [INFO] - Checking edge runtime status
<6>2019-06-13T07:16:10Z [INFO] - Edge runtime status is stopped, starting module now...
<6>2019-06-13T07:16:10Z [INFO] - Starting module edgeAgent...
<6>2019-06-13T07:16:13Z [INFO] - Successfully started module edgeAgent
<6>2019-06-13T07:16:30Z [INFO] - Querying system info...
<6>2019-06-13T07:16:30Z [INFO] - Successfully queried system info
<6>2019-06-13T07:16:30Z [INFO] - [mgmt] - - - [2019-06-13 07:16:30.551379905 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 60 "-" "-" pid(14096)
<6>2019-06-13T07:16:32Z [INFO] - [mgmt] - - - [2019-06-13 07:16:32.908734873 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:16:34Z [INFO] - [work] - - - [2019-06-13 07:16:34.967840664 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:16:37Z [INFO] - [work] - - - [2019-06-13 07:16:37.557568182 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:16:38Z [INFO] - [work] - - - [2019-06-13 07:16:38.529649097 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:16:39Z [INFO] - [work] - - - [2019-06-13 07:16:39.377160945 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:16:43Z [INFO] - [mgmt] - - - [2019-06-13 07:16:43.748879969 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:16:45Z [INFO] - [work] - - - [2019-06-13 07:16:45.932825187 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:16:46Z [INFO] - [work] - - - [2019-06-13 07:16:46.730963802 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:16:53Z [INFO] - [mgmt] - - - [2019-06-13 07:16:53.757517651 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:17:00Z [INFO] - [work] - - - [2019-06-13 07:17:00.400946762 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:17:01Z [INFO] - [work] - - - [2019-06-13 07:17:01.099749611 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:17:03Z [INFO] - [mgmt] - - - [2019-06-13 07:17:03.764427403 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:17:10Z [INFO] - Checking edge runtime status
<6>2019-06-13T07:17:10Z [INFO] - Edge runtime is running.
<6>2019-06-13T07:17:13Z [INFO] - [mgmt] - - - [2019-06-13 07:17:13.769463745 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:17:23Z [INFO] - [mgmt] - - - [2019-06-13 07:17:23.777853136 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:17:32Z [INFO] - [work] - - - [2019-06-13 07:17:32.839895303 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:17:33Z [INFO] - [work] - - - [2019-06-13 07:17:33.567727212 UTC] "POST /modules/%24edgeAgent/genid/636954236858548777/sign?api-version=2018-06-28 HTTP/1.1" 404 Not Found 202 "-" "-" pid(14096)
<6>2019-06-13T07:17:33Z [INFO] - [mgmt] - - - [2019-06-13 07:17:33.784771237 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:17:43Z [INFO] - [mgmt] - - - [2019-06-13 07:17:43.793275278 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:17:54Z [INFO] - [mgmt] - - - [2019-06-13 07:17:54.116669929 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:17:57Z [INFO] - [mgmt] - - - [2019-06-13 07:17:57.741159940 UTC] "GET /modules/?api-version=2018-06-28 HTTP/1.1" 200 OK 550 "-" "-" pid(14357)
<6>2019-06-13T07:18:04Z [INFO] - [mgmt] - - - [2019-06-13 07:18:04.124226049 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 550 "-" "-" pid(14096)
<6>2019-06-13T07:18:10Z [INFO] - Checking edge runtime status
<6>2019-06-13T07:18:10Z [INFO] - Edge runtime is running.

```
</details>

<details>
<summary>edge-agent logs</summary>

```
<6> 2019-06-13 07:29:46.350 +00:00 [INF] - Initializing Edge Agent.
<6> 2019-06-13 07:29:48.620 +00:00 [INF] - Version - 1.0.8-rc1.22563438 (95c6254573c85635f3cf42fb90fa6ef7a92bb7da)
<6> 2019-06-13 07:29:48.625 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2019-06-13 07:29:53.628 +00:00 [INF] - Started operation refresh twin config
<6> 2019-06-13 07:29:54.041 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2019-06-13 07:29:59.754 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2019-06-13 07:30:06.263 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2019-06-13 07:30:08.709 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<4> 2019-06-13 07:30:08.121 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Error calling SignAsync: An error occurred while authorizing the HTTP request
	caused by: A module runtime error occurred.
	caused by: Could not top module edgeAgent
	caused by: ps: ps: invalid option -- 'e', StatusCode: 404) (Error calling SignAsync: An error occurred while authorizing the HTTP request
	caused by: A module runtime error occurred.
	caused by: Could not top module edgeAgent
	caused by: ps: ps: invalid option -- 'e', StatusCode: 404) ---> Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling SignAsync: An error occurred while authorizing the HTTP request
	caused by: A module runtime error occurred.
	caused by: Could not top module edgeAgent
	caused by: ps: ps: invalid option -- 'e', StatusCode: 404
   at Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmSignatureProvider.SignAsync(String moduleId, String generationId, String data)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.ModuleAuthenticationWithHsm.SafeCreateNewToken(String iotHub, Int32 suggestedTimeToLive)
   at Microsoft.Azure.Devices.Client.AuthenticationWithTokenRefresh.GetTokenAsync(String iotHub)
   at Microsoft.Azure.Devices.Client.IotHubConnectionString.Microsoft.Azure.Amqp.ICbsTokenProvider.GetTokenAsync(Uri namespaceAddress, String appliesTo, String[] requiredClaims)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher.InitLoopAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.AuthenticationRefresherCreator(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 184
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling SignAsync: An error occurred while authorizing the HTTP request
	caused by: A module runtime error occurred.
	caused by: Could not top module edgeAgent
	caused by: ps: ps: invalid option -- 'e', StatusCode: 404
   at Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmSignatureProvider.SignAsync(String moduleId, String generationId, String data)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.ModuleAuthenticationWithHsm.SafeCreateNewToken(String iotHub, Int32 suggestedTimeToLive)
   at Microsoft.Azure.Devices.Client.AuthenticationWithTokenRefresh.GetTokenAsync(String iotHub)
   at Microsoft.Azure.Devices.Client.IotHubConnectionString.Microsoft.Azure.Amqp.ICbsTokenProvider.GetTokenAsync(Uri namespaceAddress, String appliesTo, String[] requiredClaims)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher.InitLoopAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.AuthenticationRefresherCreator(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 184
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---

---> (Inner Exception #1) Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling SignAsync: An error occurred while authorizing the HTTP request
	caused by: A module runtime error occurred.
	caused by: Could not top module edgeAgent
	caused by: ps: ps: invalid option -- 'e', StatusCode: 404
   at Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmSignatureProvider.SignAsync(String moduleId, String generationId, String data)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.ModuleAuthenticationWithHsm.SafeCreateNewToken(String iotHub, Int32 suggestedTimeToLive)
   at Microsoft.Azure.Devices.Client.AuthenticationWithTokenRefresh.GetTokenAsync(String iotHub)
   at Microsoft.Azure.Devices.Client.IotHubConnectionString.Microsoft.Azure.Amqp.ICbsTokenProvider.GetTokenAsync(Uri namespaceAddress, String appliesTo, String[] requiredClaims)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher.InitLoopAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.AuthenticationRefresherCreator(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 184
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---

```
</details>

<details>
<summary>edge-hub logs</summary>
iotedge restart edgeHub
edgeHub
<6>2019-06-13T07:30:47Z [INFO] - Restarting module edgeHub...
<6>2019-06-13T07:30:50Z [INFO] - Successfully restarted module edgeHub

```
[2019-06-13 07:30:50 +00:00]: Starting Edge Hub
[06/13/2019 07:30:53.682 AM] Edge Hub Main()

Unhandled Exception: System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: uriString) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 46
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 49
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 30

```
</details>

## Additional Information
In my installation I am not able to do docker exec.
My guess is iotedge uses this to interact with the Containers is this correct?
Any clue why this is not working?

```
docker exec edgeAgent /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:337: starting container process caused "read init-p: connection reset by peer": unknown
```

**Comment by OWarneke** [comment]
Solved the  edgeAgent connection error by fixing ps version 
"ps -e " was not supported.
