### ISSUE TITLE
After network cable is unplugged and plugged again streamed data are not flowing

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#139]
Data are not being released from edgeHub to IotHub once network cable was disconnected and after 
We are trying to execute following test:

## Expected Behavior

After cable is reconnected streaming data should be received by the IotHub.

## Current Behavior

IotHub is not receiving data.

## Steps to Reproduce

1. Connect to the Hyper-V and from there to ubuntu edge and verify that the edge modules are running.
In a command-line terminal use the command: iotedge list to see a list of modules on the RSU. 
2. Open Azure Portal and check that data is being received from the IoT platform.
3. Remove the internet facing network cable from the Hyper-V machine for 1 hour.
4. Restore  Hyper-V network connectivity by reconnecting the network cable.
After a few minutes, connect to the Hyper-V (as described in step 1).
5. Open Azure Portal and check that data is being received from the IoT platform. 

## Context (Environment)
Hyper-V hosting Ubuntu.

### Device (Host) Operating System

Iot edge is running on Ubuntu 18.04.

### Architecture

amd64

### Container Operating System

Linux

#### iotedged

iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent:1.0
#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0
#### Docker

Client:
Version: 18.06.0-dev
API version: 1.37
Go version: go1.10.2
Git commit: daf021fe
Built: Mon Jun 25 21:07:53 2018
OS/Arch: linux/amd64
Experimental: false
Orchestrator: swarm

Server:
Engine:
Version: dev
API version: 1.37 (minimum version 1.12)
Go version: go1.10.2
Git commit: 9aac187
Built: Mon Jun 25 20:43:05 2018
OS/Arch: linux/amd64
Experimental: false
[logsAfterCableWasPlugged.txt](https://github.com/Azure/iotedge/files/2274318/logsAfterCableWasPlugged.txt)

## Additional Information

We are running separate module that is caching data for fileupload and after cable was plugged again this module was able to resend files once connection was reestablished. This channel is using directly DeviceClient fileupload to iothub method.

**Comment by varunpuranik** [comment]
Hi @AdamMachera - I have seen that sometimes, the device SDK takes a little while to re-establish the connection to IoTHub, but it should connect eventually after the connectivity is restored. Can you wait for some time to see if that happens? If it doesn't work even after say 20 mins or so, then we can look at the logs to see what is going on.

**Comment by AdamMachera** [comment]
No, progress, edgehub is running for 7 hours after cabel was plugged.

I'm still seeing this exception:
2018-08-09 22:28:58.617 +00:00 [INF] - Bind device proxy for device cmk21218-999                                                                                            99
2018-08-09 22:28:58.618 +00:00 [INF] - Initialized AMQP connection handler for c                                                                                            mk21218-99999
2018-08-09 22:28:58.620 +00:00 [INF] - Start listening for C2D messages for devi                                                                                            ce cmk21218-99999
2018-08-09 22:28:58.629 +00:00 [INF] - Opened link C2D for cmk21218-99999
2018-08-09 22:29:13.636 +00:00 [INF] - Closing link C2D for cmk21218-99999
2018-08-09 22:29:13.692 +00:00 [INF] - Attempting to connect to IoT Hub for client cmk21218-99999 via AMQP...
2018-08-09 22:29:13.697 +00:00 [INF] - Connected to IoT Hub for client cmk21218-99999 via AMQP, with client operation timeout 60000.
2018-08-09 22:29:13.697 +00:00 [INF] - Closing receiver for device cmk21218-99999
2018-08-09 22:29:58.451 +00:00 [INF] - Entering disconnected state
2018-08-09 22:29:58.455 +00:00 [WRN] - Error in connection established callback for client cmk21218-99999 - System.TimeoutException Operation timeout expired.
2018-08-09 22:29:58.619 +00:00 [ERR] - Error receiving message for device cmk21218-99999
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutMessage>b__63_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.CloudReceiver.SetupMessageListening(IClient deviceClient) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 239
2018-08-09 22:29:58.639 +00:00 [INF] - Cloud message receiver stopped for device cmk21218-99999
2018-08-09 22:29:58.639 +00:00 [ERR] - Error closing cloud proxy for device cmk21218-99999
Microsoft.Azure.Devices.Client.Exceptions.AssertionFailedException: An unexpected failure occurred. Applications should not attempt to handle this error. For diagnostic purposes, this English message is associated with the failure: The number of devices should be greater than zero.
   at Microsoft.Azure.Devices.Client.Fx.AssertAndThrow(String description)
   at Microsoft.Azure.Devices.Client.IotHubDeviceScopeConnectionPool.RemoveDeviceFromConnection(IotHubDeviceMuxConnection iotHubDeviceMuxConnection, String deviceId)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.CloseAsync()
   at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.CloseAsync()
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.CloseAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 46
2018-08-09 22:29:58.640 +00:00 [WRN] - Cannot complete operation RemoveDesiredPropertyUpdatesAsync for device cmk21218-99999 because cloud receiver is null
2018-08-09 22:29:58.640 +00:00 [INF] - New cloud connection created for device cmk21218-99999
2018-08-09 22:30:13.726 +00:00 [INF] - Attempting to connect to IoT Hub for client cmk21218-99999 via AMQP...
2018-08-09 22:30:13.730 +00:00 [INF] - Connected to IoT Hub for client cmk21218-99999 via AMQP, with client operation timeout 60000.
2018-08-09 22:30:13.730 +00:00 [INF] - Closed cloud proxy for device cmk21218-99999
2018-08-09 22:30:13.730 +00:00 [WRN] - Cannot complete operation RemoveDesiredPropertyUpdatesAsync for device cmk21218-99999 because cloud receiver is null
2018-08-09 22:30:13.730 +00:00 [INF] - New cloud connection created for device cmk21218-99999

**Comment by varunpuranik** [comment]
From the Logs, it seems like it is indeed able to connect to IoTHub. Receiving C2D timed out in the C# SDK (for some reason), but the other operations seem to be going fine. Are you sending any telemetry from your module? I didn't see that in the logs.

**Comment by AdamMachera** [comment]
How can I enable telemetry from module?

pt., 10 sie 2018 o 00:39 Varun Puranik <notifications@github.com>
napisał(a):

**Comment by varunpuranik** [comment]
You can simply call ModuleClient.SendEventAsync to send telemetry from the module, just like you would from a device.

**Comment by AdamMachera** [comment]
So we are already doing this.
We have DispatcherModule that collects data from socket and pushes them using ModuleClient.
Some code for reference
try
            {
                var message = new Message(msg.Content);
                message.Properties.Add(CustomMessageProperties.EpocProperty,
                    msg.Epoc.ToString(CultureInfo.InvariantCulture));
                message.Properties.Add(CustomMessageProperties.DeviceIdProperty, msg.DeviceId);

                Interlocked.Increment(ref this.messagesToBeSendOverPeriod);
// wrapper over ModuleClient that add semaphore locking
                await moduleClient.SendEventSafeAsync(message, this.CtsToken.Token);

                Interlocked.Increment(ref this.messagesSentOverPeriod);
                this.LogFirstMessageWasSent();
            }
            catch (OperationCanceledException ocex)
            {
                LogManager.Debug($"Operation is being cancelled ex: {ocex}");
            }
            catch (Exception ex)
            {
                LogManager.StreamNotHandledByPolicy(msg.DeviceId, ex);
                this.RecreateDeviceClient();
            }

I'm not getting any exception from this method and I see that field messagesSentOverPeriod increases over time.

DispatcherModule is not raising any exceptions.

Messages from DispatcherModule before cable was unplugged were delivered to edgeHub based on this routing

"routes": {
    "DispatcherModuleToIotHub": "FROM /messages/modules/DispatcherModule/* INTO $upstream"
   }
At least this is my understanding that before anything reaches cloud it is routed first to edgeHub sends it to cloud.

**Comment by varunpuranik** [comment]
I see. In that case the connectivity seems to be fine, but C2D seems to have a problem. I will have to test to see if I can repro this issue (C2D after drop in connectivity). 
Have you tried Method invocation? Does that work for you, after network is back?

**Comment by AdamMachera** [comment]
If I used DeviceExplorer app to send Method to edge device:

---------------------------
Device Twin Properties
---------------------------
Device {"Message":"{\"errorCode\":404103,\"trackingId\":\"f9062d371e054200983bd59aa8420f8c-G:10-TimeStamp:08/10/2018 23:23:56\",\"message\":\"Timed out waiting for device to connect.\",\"info\":{\"timeout\":\"00:00:00\"},\"timestampUtc\":\"2018-08-10T23:23:56.2614596Z\"}","ExceptionMessage":""} not registered
---------------------------
OK   
---------------------------

**Comment by varunpuranik** [comment]
On the Edge device, nothing connects to IoTHub as the device itself, only the modules connect to IoTHub. So you cannot really invoke a method on the Edge device (and the above exception is expected).

What I meant is, from your custom module, instead of trying to read C2D messages, can you register a callback to receive method invocations, and then try to invoke methods on that module after the device re-gains network connectivity? (Note that you might need to use a simple console app to invoke the method on the module).

**Comment by AdamMachera** [comment]
I have changed module code and added this part:

Task.Run(async () =>
            {
                try
                {
                    logger.Debug("Started SetMethodHandlerAsync IsAlive");
                    await clientForRestart.SetMethodHandlerAsync("IsAlive", (request, context) =>
                    {
                        logger.Debug($"Method from cloud: {request.DataAsJson}");
                        MethodResponse methodResponse = new MethodResponse(200);
                        return Task.FromResult(methodResponse);
                    }, null);
                }
                catch (Exception e)
                {
                    logger.Error("Unable to SetMethodHandlerAsync IsAlive", e);
                }
            }, cts.Token);

edgeAgent picked up new module version.
The problem with connection is still there:

2018-08-13 13:34:58.553 DEBUG Started SetMethodHandlerAsync IsAlive
2018-08-13 13:35:58.845 ERROR: Unable to SetMethodHandlerAsync IsAlive, error System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.InternalClient.<EnableMethodAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.InternalClient.<SetMethodHandlerAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IotPlatform.Edge.Common.Logic.ModuleClientWrapper.<SetMethodHandlerAsync>d__11.MoveNext() in /app/IotPlatform.Edge.Common/Logic/ModuleClientWrapper.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DispatcherModule.Logic.Managers.DispatchingManager.<>c__DisplayClass12_0.<<CreateManager>b__0>d.MoveNext() in /app/DispatcherModule.Logic/Managers/DispatchingManager.cs:line 1

Btw C2D messages are being received by leaf device not a custom edge module.

**Comment by varunpuranik** [comment]
The EdgeHub calls the DeviceSDK for some action (sending a message, receiving C2D message, etc), and whether that succeeds or times out depends on the interaction between the SDK and the underlying layers. So I am not sure why it is timing out even when the device connection is back.

From the thread and the logs, it seems like some operations are succeeding and some are failing. If you describe exactly what operations are failing, and your exact repro, I can try to reproduce this locally. That might help us narrow down whether it is an issue with the EdgeHub, the SDK or something else. 
Also if your code is available somewhere where I can look at it, that might help as well.

**Comment by AdamMachera** [comment]
Fixed in version 1.0.4
