### ISSUE TITLE
edgeAgent doesn't support null in create options

### ISSUE THREAD

**Issue by typeli** [Azure/iotedge#1553]
I want to run docker compose project on edge runtime
```docker-compose
version: '3.7'
services:
  myapp: 
    image: python:3
    volumes:
      - type: volume
        source: mydata
        target: /usr/src/app
volumes:
  mydata:
```
I extract generated create options from docker compose
```json
{
  "HostConfig": {
    "LogConfig": {
      "Type": "",
      "Config": {}
    },
    "Mounts": [{
      "Target": "/usr/src/app",
      "Source": "mydata",
      "Type": "volume",
      "ReadOnly": null
    }]
  }
}
```

and make a deployment.template.json
```json
{
  "$schema-template": "2.0.0",
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {
            }
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "modules": {
          "myapp": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "python:3",
              "createOptions": {
                "HostConfig": {
                  "LogConfig": {
                    "Type": "",
                    "Config": {}
                  },
                  "Mounts": [
                    {
                      "Target": "/usr/src/app",
                      "Source": "mydata",
                      "Type": "volume",
                      "ReadOnly": null
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {},
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
  }
}
```

## Current Behavior

edgeAgent cannot convert string `null` to boolean value `false`

## Expected Behavior

I try post create option to [ContainerCreate](https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate) API, docker engine handle this create options properly. edgeAgent should also accept this create options.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

20 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.

```
</details>

### Device (Host) Operating System

Linux 4.15.0-1031-azure #32~16.04.1-Ubuntu SMP Wed Oct 31 19:20:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Architecture

amd64

### Container Operating System

Linux containers

#### iotedged

iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)

#### Edge Agent

1.0.0

#### Edge Hub

1.0.0

#### Docker

```
Client:
 Version:           3.0.6
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        a63faebc
 Built:             Wed Jun 19 22:56:37 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       b07f53d
  Built:            Wed Jun 19 22:28:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```

        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2019-08-12 03:10:10.487 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false}
<6> 2019-08-12 03:10:11.049 +00:00 [INF] - Started operation refresh twin config
<6> 2019-08-12 03:10:11.120 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2019-08-12 03:10:12.267 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2019-08-12 03:10:13.432 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2019-08-12 03:10:13.670 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2019-08-12 03:10:13.773 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 22 and reported properties version 139.
<3> 2019-08-12 03:10:13.799 +00:00 [ERR] - Error updating deployment config from edge agent desired properties.
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Boolean'. Path 'HostConfig.Mounts[0].ReadOnly', line 1, position 143. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---

```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by philipktlin** [comment]
Refer to https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate, HostConfig > Mounts > Readonly should be boolean type.  You should provide either true or false for this field.

**Comment by arsing** [comment]
>I try post create option to [ContainerCreate](https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate) API, docker engine handle this create options properly. edgeAgent should also accept this create options.

Golang does not convert `null` to `false` for bool fields either. What appears to happen in Golang is that `encoding/json` simply skips the field that is `null`, so the field happens to retain its original value. For a default-initialized object this value is `false`, which is why it appears that `null` is deserialized as `false`.

See https://play.golang.org/p/L7rG29698cM . Observe how the second one prints `true`.

In Rust the generated code is more type-safe, so a `bool` field is both required and must be a `bool`, which `null` is not.

**Comment by typeli** [comment]
Thanks, this maybe an issue of docker compose. I will handle this corner case carefully.
