### ISSUE TITLE
1.0.9 RC 1 Default sock configuration doesn't work properly

### ISSUE THREAD

**Issue by mma-mm** [Azure/iotedge#1562]
Hi,

i just tried to make Verison 1.0.9 RC1 of the IoT Edge Security work.
In the default config.yaml, the sockets are configured like this:

    connect:
      management_uri: "unix:///var/lib/iotedge/mgmt.sock"
      workload_uri: "unix:///var/lib/iotedge/workload.sock"
    
    listen:
      management_uri: "unix:///var/lib/iotedge/mgmt.sock"
      workload_uri: "unix:///var/lib/iotedge/workload.sock"

whilst according to iotedge --help the default connect socket is:
    
    unix:///var/run/iotedge/mgmt.sock
    
so, commands like iotedge list won't work if  `-H unix:///var/lib/iotedge/mgmt.sock`is not provided.

The default configuration should work out of the box.

## Expected Behavior
After setting the connection string / dps information and iotedge started, `iotedge list` should give a result like this:
    
    NAME             STATUS           DESCRIPTION      CONFIG
    edgeAgent        running          Up 29 minutes    mcr.microsoft.com/azureiotedge-agent:1.0

    

## Current Behavior
Call to `iotedge list` never returns.

## Steps to Reproduce

1. pull, build and install iotedge security daemon Version 1.0.9 RC1
2. change config.yaml such that it uses dps with x509-certificates.
3. restart iotedge service
4. attempt to list modules with `iotedge list` -> won't return, needs to be canceled using ctrl+c
5. call `iotedge list -H unix:///var/lib/iotedge/mgmt.sock` -> the desired output is given.

## Context (Environment)

Ubuntu 18.04 (AMD64)
iotedge 1.0.9-rc1

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
× config.yaml has well-formed connection string - Error
    Device is not using manual provisioning, so Azure IoT Hub hostname needs to be specified with --iothub-hostname
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.9-rc1' locally
    docker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.9-rc1 not found: manifest unknown: manifest unknown.
    See 'docker run --help'.
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9-rc1 but 1.0.8 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
× container time is close to host time - Error
    Could not query local time inside container
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: identity certificates expiry - OK
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
× production readiness: certificates expiry - Error
    Could not parse /var/lib/iotedge/hsm/certs/device_ca_aliasazxVrrdEVxd7kvKvne1pOEyuSHF8EXSowNDhMzl30jI_.cert.pem as a valid certificate file
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
× Edge Hub can bind to ports on host - Error
    Could not check current state of edgeHub container

6 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
6 check(s) raised errors. Re-run with --verbose for more details.
9 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

#### iotedged
iotedge 1.0.9-rc1

#### Edge Agent
1.0

#### Edge Hub
?

#### Docker

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

## Logs

<details>
<summary>iotedged logs</summary>

```
Aug 13 10:57:02 ubuntu iotedged[3129]: 2019-08-13T08:57:02Z [INFO] - Checking edge runtime status
Aug 13 10:57:02 ubuntu iotedged[3129]: 2019-08-13T08:57:02Z [INFO] - Edge runtime is running.
Aug 13 10:57:07 ubuntu iotedged[3129]: 2019-08-13T08:57:07Z [INFO] - [mgmt] - - - [2019-08-13 08:57:07.213281009 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:12 ubuntu iotedged[3129]: 2019-08-13T08:57:12Z [INFO] - [mgmt] - - - [2019-08-13 08:57:12.219682976 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:17 ubuntu iotedged[3129]: 2019-08-13T08:57:17Z [INFO] - [mgmt] - - - [2019-08-13 08:57:17.221044971 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:22 ubuntu iotedged[3129]: 2019-08-13T08:57:22Z [INFO] - [mgmt] - - - [2019-08-13 08:57:22.230056164 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:27 ubuntu iotedged[3129]: 2019-08-13T08:57:27Z [INFO] - [mgmt] - - - [2019-08-13 08:57:27.233064179 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:32 ubuntu iotedged[3129]: 2019-08-13T08:57:32Z [INFO] - [mgmt] - - - [2019-08-13 08:57:32.235270993 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:37 ubuntu iotedged[3129]: 2019-08-13T08:57:37Z [INFO] - [mgmt] - - - [2019-08-13 08:57:37.235980854 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:42 ubuntu iotedged[3129]: 2019-08-13T08:57:42Z [INFO] - [mgmt] - - - [2019-08-13 08:57:42.236818824 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:47 ubuntu iotedged[3129]: 2019-08-13T08:57:47Z [INFO] - [mgmt] - - - [2019-08-13 08:57:47.242598070 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)
Aug 13 10:57:52 ubuntu iotedged[3129]: 2019-08-13T08:57:52Z [INFO] - [mgmt] - - - [2019-08-13 08:57:52.244513105 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 449 "-" "-" auth_id(-)

```
</details>

<details>
<summary>edge-agent logs</summary>

```
2019-08-13 08:49:04  Starting Edge Agent
2019-08-13 08:49:04.116 +00:00 Edge Agent Main()
<6> 2019-08-13 08:49:04.305 +00:00 [INF] - Initializing Edge Agent.
<6> 2019-08-13 08:49:04.476 +00:00 [INF] - Version - 1.0.8.23694809 (f5186c42ebb721893c5a497c789236803de42fb7)
<6> 2019-08-13 08:49:04.476 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2019-08-13 08:49:04.539 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false}
<6> 2019-08-13 08:49:04.966 +00:00 [INF] - Started operation refresh twin config
<6> 2019-08-13 08:49:04.982 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2019-08-13 08:49:05.566 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2019-08-13 08:49:06.234 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2019-08-13 08:49:06.397 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2019-08-13 08:49:06.473 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 7.
<6> 2019-08-13 08:49:06.478 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2019-08-13 08:49:06.481 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 245
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__29_0(Twin twin) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 176
<6> 2019-08-13 08:49:06.772 +00:00 [INF] - Updated reported properties

```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by myagley** [comment]
What host OS is this? `Ubuntu 16.04`, `Ubuntu 18.04`, etc.

**Comment by arsing** [comment]
>In the default config.yaml, the sockets are configured like this:
>
>```
>connect:
>  management_uri: "unix:///var/lib/iotedge/mgmt.sock"
>  workload_uri: "unix:///var/lib/iotedge/workload.sock"
>
>listen:
>  management_uri: "unix:///var/lib/iotedge/mgmt.sock"
>  workload_uri: "unix:///var/lib/iotedge/workload.sock"
>```

The package for Ubuntu 18.04 (which is actually the package for Ubuntu 16.04) defaults to:

```yaml
connect:
  management_uri: "unix:///var/run/iotedge/mgmt.sock"
  workload_uri: "unix:///var/run/iotedge/workload.sock"

listen:
  management_uri: "fd://iotedge.mgmt.socket"
  workload_uri: "fd://iotedge.socket"
```

Which package did you install that you see the defaults are `/var/lib` for `connect.*` and not using systemd sockets for `listen.*` ?

**Comment by arsing** [comment]
Actually, we haven't published 1.0.9-rc1 yet. So I assume you built it yourself. How exactly did you build it?

**Comment by mma-mm** [comment]
Its an Ubuntu 18.04 

    $ uname -a
    Linux ubuntu 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

For the build i used the instructions in `edgelet/doc/devguide.md` (rustup -> cargo build --all -> make && make install

**Comment by arsing** [comment]
There is no `make && make install` in the devguide, so I assume you just guessed you could do that.

`make install` is only used for CentOS builds, which is why the `config.yaml` it uses is for CentOS. Even then it's not meant to be used directly, but via `package.sh`

If you want packages for ubuntu 18.04, use `PACKAGE_OS=ubuntu18.04 PACKAGE_ARCH=amd64 ./edgelet/build/linux/package.sh`
