### ISSUE TITLE
Using Edge Device as Transparent Gateway - error authenticating downstream device?

### ISSUE THREAD

**Issue by blackchoey** [Azure/iotedge#1567]
The issue is filed incorrectly under https://github.com/azure/iotedgedev
Moving it to here on behalf of @ppavanm
Original issue: https://github.com/Azure/iotedgedev/issues/403

- iotedgedev Version: 0.9.0
- Python Version: 3.7.3
- Pip Version: 19.1.1
- Development machine OS Version: 1903 (OS Build 18362.239)
- IoT Edge device OS Version: 1809 (OS Build 17763.615)

I am trying to use my edge device as a transparent gateway. I have successfully provisioned my edge device and downstream device using DPS regular steps. I am using X.509 authentication to authenticate my downstream device but for some reason I am not able to authenticate my downstream device.

Hoping someone has come across this and can provide some guidance.

Notes: 
	- I am following the tutorial - https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway#install-certificates-on-the-gateway
	- Using the certificate creation script from iotedge repo (https://github.com/Azure/iotedge.git) 
	- Creating certificates on the edge device itself and working directory is - "C:\Temp\GWCerts"
	- My downstream device is an application running on the edge device itself

Steps to Reproduce:

1. Created the root CA certificate and intermediate certificate using following PowerShell command:
		New-CACertsCertChain rsa
		
2. Created the IoT Edge device CA certificate and private key with following command:
		New-CACertsEdgeDevice "myedgedevice"
	
3. Modified the IoT Edge security config file (config.yaml) to set certificate properties as:
	certificates:
	   device_ca_cert: "C:\\Temp\\GWCerts\\certs\\certs\\iot-edge-device-myedgedevice-full-chain.cert.pem"
	   device_ca_pk: "C:\\Temp\\GWCerts\\private\\iot-edge-device-myedgedevice.key.pem"
	   trusted_ca_certs: "C:\\Temp\\GWCerts\\certs\\azure-iot-test-only.root.ca.cert.pem"
	 
4. Restarted iotedge
	
5. Deployed edgeHub and ai_insights modules with following routes:
		"sensorToAIInsightsInput1": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint(\"/modules/ai_insights/inputs/input1\")",
	          "AIInsightsToIoTHub": "FROM /messages/modules/ai_insights/outputs/output1 INTO $upstream"
	
6. Registered root CA certificate to my IoT Hub
	
7. Created downstream device certificate using following command:
		New-CACertsDevice "myfirstchilddevice"
		
8. Created IoT Device programmatically using DPS
	a. Created individual enrollment using X509Attestation as follows:

		`using (var provisioningServiceClient = ProvisioningServiceClient.CreateFromConnectionString(provisioningConnectionString))
		{
			Attestation attestation = X509Attestation.CreateFromClientCertificates(new X509Certificate2(@"C:\Temp\GWCerts\certs\iot-device-myfirstchilddevice.cert.pem"));
				
			IndividualEnrollment individualEnrollment = new IndividualEnrollment("myfirstchilddevice", attestation)
				                        {
				                            DeviceId = "myfirstchilddevice",
				                            ProvisioningStatus = ProvisioningStatus.Enabled,
				                            Capabilities = new DeviceCapabilities { IotEdge = false }
				                        };
				
			IndividualEnrollment individualEnrollmentResult = await provisioningServiceClient.CreateOrUpdateIndividualEnrollmentAsync(individualEnrollment).ConfigureAwait(false);
		}`
			
	b. Registered device using Provisioning Device Client as follows:
			
		`using (var security = new SecurityProviderX509Certificate(new X509Certificate2(@"C:\Temp\GWCerts\certs\iot-device-myfirstchilddevice.cert.pfx")))
		{
			using (var transport = new ProvisioningTransportHandlerAmqp(TransportFallbackType.TcpOnly))
			{
				var provDeviceClient = ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, IdScope, security, transport);
					
				DeviceRegistrationResult result = await provDeviceClient.RegisterAsync().ConfigureAwait(false);
			}
		}`
			
9. Modified this IoT Device, myfirstchilddevice, on the portal to set the parent device as my edge device
	
10. Installed root CA Certificate on the edge device in Local Computer > Trusted Root Certification Authorities
	
11. Trying to connect my downstream device to my IoT Edge gateway as follows:
		
		`var auth = new DeviceAuthenticationWithX509Certificate("myfirstchilddevice", new X509Certificate2(@"C:\Temp\GWCerts\certs\iot-device-myfirstchilddevice.cert.pfx"));
		
		DeviceClient deviceClient = DeviceClient.Create("myIotHub.azure-devices.net", "my-edgedevice", auth, TransportType.Amqp_Tcp_Only);
		
		await deviceClient.SendEventAsync(new Message(Encoding.UTF8.GetBytes("Test Message"))).ConfigureAwait(false);`
		
	It throws exception for the SendEventAsync call, following is the exception:
	
	Unhandled Exception: System.AggregateException: One or more errors occurred. (TLS authentication error.) ---> System.Security.Authentication.AuthenticationException: TLS authentication error. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
	   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
	   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Net.Security.SslState.ThrowIfExceptional()
	   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
	   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
	   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
	   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
	   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
	   at Microsoft.Azure.Amqp.Transport.TlsTransport.HandleOpenComplete(IAsyncResult result, Boolean syncComplete)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
	   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
	   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
	   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.HandleTransportOpened(IAsyncResult result)
	   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.OnTransportOpened(IAsyncResult result)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector.InitializeTransport(TimeSpan timeout)
	   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector.OpenConnectionAsync(TimeSpan timeout)
	   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnection(TimeSpan timeout)
	   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.AmqpSessionCreator(DeviceIdentity deviceIdentity, ILinkFactory linkFactory, AmqpSessionSettings amqpSessionSettings, TimeSpan timeout)
	   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.OpenAsync(TimeSpan timeout)
	   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
	   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
	   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
	   --- End of inner exception stack trace ---
	   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
	   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
	   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
	   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
	   at Microsoft.Azure.Devices.Edge.Samples.EdgeDownstreamDevice.Program.SendEvents(DeviceClient deviceClient, Int32 messageCount) in C:\Temp\iotedge\samples\dotnet\EdgeDownstreamDevice\Program.cs:line 215
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Task.Wait()
	   at Microsoft.Azure.Devices.Edge.Samples.EdgeDownstreamDevice.Program.Main() in C:\Temp\iotedge\samples\dotnet\EdgeDownstreamDevice\Program.cs:line 84
	
**Update:**
The only way I am able to connect leaf device is - create leaf device manually and use Mqtt protocol.
If the device is created using regular DPS steps and manually set its parent device to make it leaf device then it is not able to connect (tried both Amqp and Mqtt).

**Comment by ppavanm** [comment]
@blackchoey Thank you!  I realized it after logging it but did not move it.

**Comment by lt72** [comment]
@kkdawkins can you please take a look at this one?

**Comment by lt72** [comment]
@damonbarry PTAL

**Comment by damonbarry** [comment]
I think we need to try to repro this on our side, confirm it's still a thing. I'll assign this over to @kkdawkins and ask him to have a look.

**Comment by kkdawkins** [comment]
Hi! Sorry for the delay. 

It looks like it is complaining about a remote certificate validation error. Did you install the "trust bundle" on the downstream device? See documentation here - https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device 

Thanks,
Kevin

**Comment by kkdawkins** [comment]
Hi @ppavanm - Were you able to resolve your issue?

**Comment by kkdawkins** [comment]
I'll go ahead and close this - feel free to reopen if you want more help!
