### ISSUE TITLE
Unable to run edgeHub on Rasberry Pi

### ISSUE THREAD

**Issue by solankigithub** [Azure/iotedge#158]
Hi,
I am trying to install the Azure Iotedge on Rasberry Pi 3.
I followed below link 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm

The edgeAgent is running fine but the unable to run edgeHub .

When i explicitly run the command : 
> pi@raspberrypi:~ $ sudo docker container run b5637d573d56

I get below error:

```
[2018-08-15 12:38:17 +00:00]: Starting Edge Hub
[08/15/2018 12:38:18.235 PM] Edge Hub Main()

Unhandled Exception: System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: uriString) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 56
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 31

```

I formatted the SD Card and again installed Rasbian-stretch, but  no help.
Please help.

Thanks
Sandeep

**Comment by solankigithub** [comment]
Ok Resolved.

**Comment by EnNico** [comment]
@solankigithub how could you fix this issue? i run into the same problem

**Comment by rsov** [comment]
Why you gotta do us dirty like that bro
