### ISSUE TITLE
Microsoft.Azure.Devices.Client 1.21.1 breaks inter module communication.

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iotedge#1720]
After updating DeviceClient to 1.21.1 in all my modules sending messages to BrokeredEndpoints did not work anymore.  Upstream messages where send though.

Here's the edgeHub log:

```
<6> 2019-09-16 05:10:27.437 +00:00 [INF] - Obtained edge hub config patch update from module twin
<6> 2019-09-16 05:10:27.452 +00:00 [INF] - Updating edge hub configuration
<6> 2019-09-16 05:10:27.475 +00:00 [INF] - Set the following 8 route(s) in edge hub
<6> 2019-09-16 05:10:27.476 +00:00 [INF] - PublisherToOpcDataToMessage: FROM /messages/modules/publisher/* INTO BrokeredEndpoint("/modules/OpcDataToMessage/inputs/input1")
<6> 2019-09-16 05:10:27.476 +00:00 [INF] - OpcDataToMessageToSupport: FROM /messages/modules/OpcDataToMessage/outputs/support INTO BrokeredEndpoint("/modules/Support/inputs/input1")
<6> 2019-09-16 05:10:27.477 +00:00 [INF] - DeviceMessageGeneratorToIoTHub: FROM /messages/modules/DeviceMessageGenerator/outputs/* INTO $upstream
<6> 2019-09-16 05:10:27.477 +00:00 [INF] - DeviceMessageGeneratorToAlarm: FROM /messages/modules/DeviceMessageGenerator/outputs/alarm INTO BrokeredEndpoint("/modules/Alarm/inputs/input1")
<6> 2019-09-16 05:10:27.477 +00:00 [INF] - SupportToIoTHub: FROM /messages/modules/Support/outputs/* INTO $upstream
<6> 2019-09-16 05:10:27.478 +00:00 [INF] - AlarmToIoTHub: FROM /messages/modules/Alarm/outputs/* INTO $upstream
<6> 2019-09-16 05:10:27.478 +00:00 [INF] - WebserverToIoTHub: FROM /messages/modules/Webserver/outputs/diary INTO $upstream
<6> 2019-09-16 05:10:27.479 +00:00 [INF] - WebserverToAlarm: FROM /messages/modules/Webserver/outputs/alarm INTO BrokeredEndpoint("/modules/Alarm/inputs/input1")
<6> 2019-09-16 05:10:27.479 +00:00 [INF] - Updated message store TTL to 604800 seconds
<6> 2019-09-16 05:10:27.480 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2019-09-16 05:10:27.610 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:10:55.197 +00:00 [INF] - Closing link Events for bewaPi2/OpcUa
<6> 2019-09-16 05:10:55.198 +00:00 [INF] - Closing link MethodSending for bewaPi2/OpcUa
<6> 2019-09-16 05:10:55.198 +00:00 [INF] - Closing link MethodReceiving for bewaPi2/OpcUa
<6> 2019-09-16 05:10:55.201 +00:00 [INF] - Closing link ModuleMessages for bewaPi2/OpcUa
<6> 2019-09-16 05:10:55.202 +00:00 [INF] - Setting proxy inactive for bewaPi2/OpcUa.
<6> 2019-09-16 05:10:55.202 +00:00 [INF] - Device connection removed for device bewaPi2/OpcUa
<6> 2019-09-16 05:10:55.205 +00:00 [INF] - Remove device connection for device bewaPi2/OpcUa
<6> 2019-09-16 05:10:55.363 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:10.597 +00:00 [INF] - Closing link Events for bewaPi2/Webserver
<6> 2019-09-16 05:11:10.599 +00:00 [INF] - Closing link MethodSending for bewaPi2/Webserver
<6> 2019-09-16 05:11:10.599 +00:00 [INF] - Closing link MethodReceiving for bewaPi2/Webserver
<6> 2019-09-16 05:11:10.600 +00:00 [INF] - Setting proxy inactive for bewaPi2/Webserver.
<6> 2019-09-16 05:11:10.600 +00:00 [INF] - Device connection removed for device bewaPi2/Webserver
<6> 2019-09-16 05:11:10.616 +00:00 [INF] - Remove device connection for device bewaPi2/Webserver
<6> 2019-09-16 05:11:10.768 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:12.050 +00:00 [INF] - New token received on the Cbs link
<6> 2019-09-16 05:11:12.418 +00:00 [INF] - Client bewaPi2/OpcUa in device scope authenticated locally.
<6> 2019-09-16 05:11:12.419 +00:00 [INF] - New device connection for device bewaPi2/OpcUa
<6> 2019-09-16 05:11:12.424 +00:00 [INF] - Bind device proxy for device bewaPi2/OpcUa
<6> 2019-09-16 05:11:12.424 +00:00 [INF] - Initialized device listener in the AMQP protocol head for bewaPi2/OpcUa
<6> 2019-09-16 05:11:12.424 +00:00 [INF] - Opened link Events for bewaPi2/OpcUa
<6> 2019-09-16 05:11:12.766 +00:00 [INF] - Opened link ModuleMessages for bewaPi2/OpcUa
<6> 2019-09-16 05:11:12.978 +00:00 [INF] - Opened link MethodSending for bewaPi2/OpcUa
<6> 2019-09-16 05:11:13.020 +00:00 [INF] - Opened link MethodReceiving for bewaPi2/OpcUa
<6> 2019-09-16 05:11:15.908 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:20.723 +00:00 [INF] - Closing link Events for bewaPi2/Alarm
<6> 2019-09-16 05:11:20.723 +00:00 [INF] - Closing link TwinSending for bewaPi2/Alarm
<6> 2019-09-16 05:11:20.723 +00:00 [INF] - Closing link TwinReceiving for bewaPi2/Alarm
<6> 2019-09-16 05:11:20.724 +00:00 [INF] - Closing link ModuleMessages for bewaPi2/Alarm
<6> 2019-09-16 05:11:20.724 +00:00 [INF] - Setting proxy inactive for bewaPi2/Alarm.
<6> 2019-09-16 05:11:20.728 +00:00 [INF] - Device connection removed for device bewaPi2/Alarm
<6> 2019-09-16 05:11:20.730 +00:00 [INF] - Remove device connection for device bewaPi2/Alarm
<6> 2019-09-16 05:11:21.066 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:22.259 +00:00 [INF] - New token received on the Cbs link
<6> 2019-09-16 05:11:22.611 +00:00 [INF] - Client bewaPi2/Webserver in device scope authenticated locally.
<6> 2019-09-16 05:11:26.307 +00:00 [INF] - New device connection for device bewaPi2/Webserver
<6> 2019-09-16 05:11:26.319 +00:00 [INF] - Bind device proxy for device bewaPi2/Webserver
<6> 2019-09-16 05:11:26.320 +00:00 [INF] - Initialized device listener in the AMQP protocol head for bewaPi2/Webserver
<6> 2019-09-16 05:11:26.320 +00:00 [INF] - Opened link Events for bewaPi2/Webserver
<4> 2019-09-16 05:11:26.430 +00:00 [WRN] - Module bewaPi2/Alarm is not connected
<6> 2019-09-16 05:11:26.538 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:26.709 +00:00 [INF] - Opened link MethodSending for bewaPi2/Webserver
<6> 2019-09-16 05:11:26.753 +00:00 [INF] - Opened link MethodReceiving for bewaPi2/Webserver
<4> 2019-09-16 05:11:27.461 +00:00 [WRN] - Module bewaPi2/Alarm is not connected
<4> 2019-09-16 05:11:29.517 +00:00 [WRN] - Module bewaPi2/Alarm is not connected
<6> 2019-09-16 05:11:33.037 +00:00 [INF] - Closing link Events for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:33.038 +00:00 [INF] - Closing link TwinSending for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:33.039 +00:00 [INF] - Closing link TwinReceiving for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:33.039 +00:00 [INF] - Closing link ModuleMessages for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:33.040 +00:00 [INF] - Setting proxy inactive for bewaPi2/OpcDataToMessage.
<6> 2019-09-16 05:11:33.040 +00:00 [INF] - Device connection removed for device bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:33.041 +00:00 [INF] - Remove device connection for device bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:33.206 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<4> 2019-09-16 05:11:33.260 +00:00 [WRN] - Module bewaPi2/Alarm is not connected
<6> 2019-09-16 05:11:37.459 +00:00 [INF] - New token received on the Cbs link
<6> 2019-09-16 05:11:37.866 +00:00 [INF] - Client bewaPi2/Alarm in device scope authenticated locally.
<6> 2019-09-16 05:11:37.867 +00:00 [INF] - New device connection for device bewaPi2/Alarm
<6> 2019-09-16 05:11:37.869 +00:00 [INF] - Bind device proxy for device bewaPi2/Alarm
<6> 2019-09-16 05:11:37.869 +00:00 [INF] - Initialized device listener in the AMQP protocol head for bewaPi2/Alarm
<6> 2019-09-16 05:11:37.869 +00:00 [INF] - Opened link Events for bewaPi2/Alarm
<6> 2019-09-16 05:11:38.173 +00:00 [INF] - Opened link ModuleMessages for bewaPi2/Alarm
<6> 2019-09-16 05:11:38.349 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:38.427 +00:00 [INF] - Opened link TwinSending for bewaPi2/Alarm
<6> 2019-09-16 05:11:38.466 +00:00 [INF] - Opened link TwinReceiving for bewaPi2/Alarm
<6> 2019-09-16 05:11:42.018 +00:00 [INF] - Opened link C2D for bewaPi2/Alarm
<6> 2019-09-16 05:11:43.713 +00:00 [INF] - New token received on the Cbs link
<6> 2019-09-16 05:11:44.068 +00:00 [INF] - Client bewaPi2/OpcDataToMessage in device scope authenticated locally.
<6> 2019-09-16 05:11:44.069 +00:00 [INF] - New device connection for device bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.077 +00:00 [INF] - Bind device proxy for device bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.078 +00:00 [INF] - Initialized device listener in the AMQP protocol head for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.078 +00:00 [INF] - Opened link Events for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.223 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:44.364 +00:00 [INF] - Opened link ModuleMessages for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.590 +00:00 [INF] - Opened link TwinSending for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.626 +00:00 [INF] - Opened link TwinReceiving for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.869 +00:00 [INF] - Closing receiver in cloud proxy 8456be57-a6ad-4ff3-a351-1851ab1c9960 for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.870 +00:00 [INF] - Closed cloud proxy 8456be57-a6ad-4ff3-a351-1851ab1c9960 for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:44.872 +00:00 [INF] - Retrying cloud proxy operation GetTwinAsync for bewaPi2/OpcDataToMessage.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IoT Client'.
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.ThrowIfDisposed()
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass24_0.<<SendTwinGetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 162
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.GetTwinAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 112
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.GetTwinAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 121
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.ExecuteOperation[T](Func`2 func, String operation)
<6> 2019-09-16 05:11:44.887 +00:00 [INF] - Attempting to connect to IoT Hub for client bewaPi2/OpcDataToMessage via AMQP...
<6> 2019-09-16 05:11:45.078 +00:00 [INF] - Cloud connection for bewaPi2/OpcDataToMessage is True
<6> 2019-09-16 05:11:45.078 +00:00 [INF] - Connection status for bewaPi2/OpcDataToMessage changed to ConnectionEstablished
<6> 2019-09-16 05:11:45.078 +00:00 [INF] - Client bewaPi2/OpcDataToMessage connected to cloud, processing existing subscriptions.
<6> 2019-09-16 05:11:45.079 +00:00 [INF] - Created cloud proxy for client bewaPi2/OpcDataToMessage via AMQP, with client operation timeout 20 seconds.
<6> 2019-09-16 05:11:45.079 +00:00 [INF] - Initialized cloud proxy c09dce78-70ed-4183-9e96-63cdab76e18b for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:45.079 +00:00 [INF] - Created cloud connection for client bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:11:48.756 +00:00 [INF] - Closing link Events for bewaPi2/DeviceMessageGenerator
<6> 2019-09-16 05:11:48.756 +00:00 [INF] - Setting proxy inactive for bewaPi2/DeviceMessageGenerator.
<6> 2019-09-16 05:11:48.756 +00:00 [INF] - Device connection removed for device bewaPi2/DeviceMessageGenerator
<6> 2019-09-16 05:11:48.758 +00:00 [INF] - Remove device connection for device bewaPi2/DeviceMessageGenerator
<6> 2019-09-16 05:11:49.372 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:55.567 +00:00 [INF] - Closing link Events for bewaPi2/publisher
<6> 2019-09-16 05:11:55.569 +00:00 [INF] - Closing link MethodSending for bewaPi2/publisher
<6> 2019-09-16 05:11:55.570 +00:00 [INF] - Closing link MethodReceiving for bewaPi2/publisher
<6> 2019-09-16 05:11:55.571 +00:00 [INF] - Setting proxy inactive for bewaPi2/publisher.
<6> 2019-09-16 05:11:55.571 +00:00 [INF] - Device connection removed for device bewaPi2/publisher
<6> 2019-09-16 05:11:55.581 +00:00 [INF] - Remove device connection for device bewaPi2/publisher
<6> 2019-09-16 05:11:55.732 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:11:59.929 +00:00 [INF] - New token received on the Cbs link
<6> 2019-09-16 05:12:00.311 +00:00 [INF] - Client bewaPi2/DeviceMessageGenerator in device scope authenticated locally.
<6> 2019-09-16 05:12:00.312 +00:00 [INF] - New device connection for device bewaPi2/DeviceMessageGenerator
<6> 2019-09-16 05:12:00.314 +00:00 [INF] - Bind device proxy for device bewaPi2/DeviceMessageGenerator
<6> 2019-09-16 05:12:00.314 +00:00 [INF] - Initialized device listener in the AMQP protocol head for bewaPi2/DeviceMessageGenerator
<6> 2019-09-16 05:12:00.314 +00:00 [INF] - Opened link Events for bewaPi2/DeviceMessageGenerator
<6> 2019-09-16 05:12:00.887 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:12:08.595 +00:00 [INF] - Reauthenticating connected clients
<4> 2019-09-16 05:12:11.501 +00:00 [WRN] - Did not receive ack for message 19f37cc8-601d-4d3d-86be-324aa25c1469 from device/module bewaPi2/Alarm
<4> 2019-09-16 05:12:11.511 +00:00 [WRN] - Error sending messages to module bewaPi2/Alarm
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 416
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 164
<6> 2019-09-16 05:12:11.718 +00:00 [INF] - Closing link Events for bewaPi2/Support
<6> 2019-09-16 05:12:11.719 +00:00 [INF] - Closing link ModuleMessages for bewaPi2/Support
<6> 2019-09-16 05:12:11.720 +00:00 [INF] - Setting proxy inactive for bewaPi2/Support.
<6> 2019-09-16 05:12:11.720 +00:00 [INF] - Device connection removed for device bewaPi2/Support
<6> 2019-09-16 05:12:11.726 +00:00 [INF] - Remove device connection for device bewaPi2/Support
<6> 2019-09-16 05:12:11.882 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:12:18.516 +00:00 [INF] - New token received on the Cbs link
<6> 2019-09-16 05:12:18.924 +00:00 [INF] - Client bewaPi2/publisher in device scope authenticated locally.
<6> 2019-09-16 05:12:18.926 +00:00 [INF] - New device connection for device bewaPi2/publisher
<6> 2019-09-16 05:12:18.937 +00:00 [INF] - Bind device proxy for device bewaPi2/publisher
<6> 2019-09-16 05:12:18.937 +00:00 [INF] - Initialized device listener in the AMQP protocol head for bewaPi2/publisher
<6> 2019-09-16 05:12:18.938 +00:00 [INF] - Opened link Events for bewaPi2/publisher
<6> 2019-09-16 05:12:19.088 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:12:19.223 +00:00 [INF] - Opened link MethodSending for bewaPi2/publisher
<6> 2019-09-16 05:12:19.252 +00:00 [INF] - Opened link MethodReceiving for bewaPi2/publisher
<6> 2019-09-16 05:12:23.259 +00:00 [INF] - New token received on the Cbs link
<6> 2019-09-16 05:12:23.620 +00:00 [INF] - Client bewaPi2/Support in device scope authenticated locally.
<6> 2019-09-16 05:12:23.622 +00:00 [INF] - New device connection for device bewaPi2/Support
<6> 2019-09-16 05:12:23.634 +00:00 [INF] - Bind device proxy for device bewaPi2/Support
<6> 2019-09-16 05:12:23.635 +00:00 [INF] - Initialized device listener in the AMQP protocol head for bewaPi2/Support
<6> 2019-09-16 05:12:23.635 +00:00 [INF] - Opened link Events for bewaPi2/Support
<6> 2019-09-16 05:12:23.911 +00:00 [INF] - Attempting to connect to IoT Hub for client bewaPi2/Support via AMQP...
<6> 2019-09-16 05:12:23.911 +00:00 [INF] - Opened link ModuleMessages for bewaPi2/Support
<6> 2019-09-16 05:12:24.125 +00:00 [INF] - Cloud connection for bewaPi2/Support is True
<6> 2019-09-16 05:12:24.126 +00:00 [INF] - Connection status for bewaPi2/Support changed to ConnectionEstablished
<6> 2019-09-16 05:12:24.126 +00:00 [INF] - Client bewaPi2/Support connected to cloud, processing existing subscriptions.
<6> 2019-09-16 05:12:24.126 +00:00 [INF] - Created cloud proxy for client bewaPi2/Support via AMQP, with client operation timeout 20 seconds.
<6> 2019-09-16 05:12:24.126 +00:00 [INF] - Initialized cloud proxy 0569758b-958b-4fc5-a93e-4a9970944dc6 for bewaPi2/Support
<6> 2019-09-16 05:12:24.127 +00:00 [INF] - Created cloud connection for client bewaPi2/Support
<6> 2019-09-16 05:12:24.232 +00:00 [INF] - Updated reported properties for bewaPi2/$edgeHub
<6> 2019-09-16 05:12:30.497 +00:00 [INF] - Opened link C2D for bewaPi2/OpcDataToMessage
<6> 2019-09-16 05:12:30.725 +00:00 [INF] - Opened link C2D for bewaPi2/Support
<4> 2019-09-16 05:12:56.048 +00:00 [WRN] - Did not receive ack for message de2e2557-a49c-443e-939d-b0fa529138b6 from device/module bewaPi2/Alarm
<4> 2019-09-16 05:12:56.053 +00:00 [WRN] - Error sending messages to module bewaPi2/Alarm
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 416
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 164
<4> 2019-09-16 05:12:59.740 +00:00 [WRN] - Did not receive ack for message 56084380-3b3e-4e9b-aa85-676e53363a09 from device/module bewaPi2/OpcDataToMessage
<4> 2019-09-16 05:12:59.746 +00:00 [WRN] - Error sending messages to module bewaPi2/OpcDataToMessage
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 416
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 164
<4> 2019-09-16 05:13:00.348 +00:00 [WRN] - Did not receive ack for message 972ed563-7be5-41cf-bfe1-ccd6a3d27b12 from device/module bewaPi2/Support
<4> 2019-09-16 05:13:00.353 +00:00 [WRN] - Error sending messages to module bewaPi2/Support
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 416
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 164
<4> 2019-09-16 05:13:30.749 +00:00 [WRN] - Did not receive ack for message 7e9aa55a-a11e-4367-a1bb-e28bd7230ab9 from device/module bewaPi2/OpcDataToMessage
<4> 2019-09-16 05:13:30.753 +00:00 [WRN] - Error sending messages to module bewaPi2/OpcDataToMessage
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 416
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 164
<4> 2019-09-16 05:13:31.357 +00:00 [WRN] - Did not receive ack for message 024680a2-6573-4392-8451-e2e476f41b19 from device/module bewaPi2/Support
<4> 2019-09-16 05:13:31.362 +00:00 [WRN] - Error sending messages to module bewaPi2/Support
System.TimeoutException: Message completion response not received

```
After that the `Message completion response not received` ErrorMessages repeat over and over again.

I was using edgeAgent + edgeHub 1.0.8.1 and hoped the errors might go away with 1.0.9-rc2 but they did not.  Restarting edgeHub and iotedge alltogether did not solve the problem either.

After reverting to DeviceClient 1.21.0 and restarting iotedge again, communication started to work again.

**Comment by japollac** [comment]
Hi @BewaControl-ReneDivossen.  Thanks for pointing that out. I already mentioned that problem in https://github.com/Azure/iotedge/issues/1715. 

Same problem and after reverting back to 1.21.0 the module to module communication works again as expected.

**Comment by dmaxwe22** [comment]
Same for me. When reverting to 1.21.0 connectivity between tempSensor and next module in the route worked. 2000 messages were uploaded to the IoT Hub then. My operating systrem is windows. 

Kept getting messages:

2019-09-17 11:30:28.357 -04:00 [WRN] - Error sending messages to module IotEdgeDellPc/SnmpModule
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azur
e.Devices.Edge.Hub.Core\device\DeviceMessageHandler.cs:line 363
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken t
oken) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\routing\ModuleEndpoint.cs:line 164

Solution is to revert back to Microosft.Devices.Client to 1.21.0
