### ISSUE TITLE
Module not started by edgeAgent after offline device restore connectivity

### ISSUE THREAD

**Issue by vteplyuk** [Azure/iotedge#1731]
After device restart and stay offline for some time, modules, that require connectivity, are not started by edgeAgent, even after connection restored.

## Expected Behavior
edgeAgent restart module indefinitely when restart policy "always" is used

## Current Behavior
edgeAgent restarted failed modules 20 times and did not start those modules anymore

## Steps to Reproduce
1. create deployment with container that fail w/o internet connection
2. deploy to edge device
3. disconnect device, reboot, leave offline until edgeAgent stop restarting failed module
4. restore connection to device, check modules status

### Device (Host) Operating System
Ubuntu 18.04.03

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)

#### Edge Agent
azureiotedge-agent:1.0 
Version - 1.0.8.1.24554792 (8a9cfedfc6c7455c080dcee6ee21978069024d2f)

#### Docker
moby-engine/bionic,now 3.0.6 amd64 [installed]

## Logs
<details>
<summary>iotedged logs</summary>

```
Sep 19 20:06:19 XXYYZZ iotedged[1489]: 2019-09-19T20:06:19Z [INFO] - Checking edge runtime status
Sep 19 20:06:19 XXYYZZ iotedged[1489]: 2019-09-19T20:06:19Z [INFO] - Edge runtime is running.
Sep 19 20:07:19 XXYYZZ iotedged[1489]: 2019-09-19T20:07:19Z [INFO] - Checking edge runtime status
Sep 19 20:07:19 XXYYZZ iotedged[1489]: 2019-09-19T20:07:19Z [INFO] - Edge runtime is running.
```
</details>

<details>
<summary>edge-agent logs</summary>
```
<6> 2019-09-19 14:54:35.064 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2019-09-19 15:54:35.066 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2019-09-19 15:54:35.125 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 10 and reported properties version 800.
<6> 2019-09-19 15:54:35.132 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2019-09-19 16:49:32.499 +00:00 [INF] - Starting compaction of stores
<6> 2019-09-19 16:49:32.500 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2019-09-19 16:49:32.501 +00:00 [INF] - Starting compaction of store default
<6> 2019-09-19 16:49:32.501 +00:00 [INF] - Starting compaction of store moduleState
<6> 2019-09-19 16:54:35.133 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2019-09-19 16:54:35.187 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 10 and reported properties version 800.
<6> 2019-09-19 16:54:35.195 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2019-09-19 17:54:35.198 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2019-09-19 17:54:35.246 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 10 and reported properties version 800.
<6> 2019-09-19 17:54:35.251 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2019-09-19 18:49:32.497 +00:00 [INF] - Starting compaction of stores
<6> 2019-09-19 18:49:32.497 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2019-09-19 18:49:32.498 +00:00 [INF] - Starting compaction of store default
<6> 2019-09-19 18:49:32.498 +00:00 [INF] - Starting compaction of store moduleState
<6> 2019-09-19 18:54:35.249 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2019-09-19 18:54:35.294 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 10 and reported properties version 800.
<6> 2019-09-19 18:54:35.304 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2019-09-19 19:54:35.305 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2019-09-19 19:54:35.357 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 10 and reported properties version 800.
<6> 2019-09-19 19:54:35.361 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2019-09-19 20:01:44.105 +00:00 [INF] - Plan execution started for deployment 10
<6> 2019-09-19 20:01:44.106 +00:00 [INF] - Executing command: "Start module modbusclient"
<6> 2019-09-19 20:01:45.763 +00:00 [INF] - Plan execution ended for deployment 10
<6> 2019-09-19 20:01:46.032 +00:00 [INF] - Updated reported properties
<6> 2019-09-19 20:01:51.268 +00:00 [INF] - Updated reported properties
```
</details>

## Additional Information
Some properties from Portal/IoT Edge Module Details:

"Restart Policy" : "always"
"Last Start Time UTC" : "Thu Sep 12 2019 18:14:38 GMT-0400 (Eastern Daylight Time)"
"Status Description" : "exited"
"Runtime Status" : "failed"
"Last Exit Time UTC" : "Thu Sep 12 2019 18:16:09 GMT-0400 (Eastern Daylight Time)"
"Exit Code" : "139"
"Last Restart Time UTC" : "Thu Sep 12 2019 18:14:36 GMT-0400 (Eastern Daylight Time)"
"Restart Count" : "20"

**Comment by veyalla** [comment]
@vteplyuk The restart count can be changed via an environment variable set for edgeAgent: `MaxRestartCount`. It is set to 20 by default.

**Comment by veyalla** [comment]
The type is an `int`, so `2147483647` per https://www.dotnetperls.com/int-maxvalue?

**Comment by vteplyuk** [comment]
Thank you, @veyalla, I continue testing offline mode with MaxRestartCount=2147483647 set for edgeAgent.

Last time module mbpa restarted on **2019-09-20 15:16:14.356 +00:00**, current system time: **Fri Sep 20 16:22:42 UTC 2019**, i.e. last hour module mbpa not restarted by edgeAgent.

Tail of edgeAgent log:
~~~text
<6> 2019-09-20 15:11:05.665 +00:00 [INF] - Executing command: "Stop module mbpa"
<6> 2019-09-20 15:11:05.670 +00:00 [INF] - Executing command: "Start module mbpa"
<6> 2019-09-20 15:11:07.471 +00:00 [INF] - Executing command: "Saving mbpa to store"
<6> 2019-09-20 15:11:07.474 +00:00 [INF] - Plan execution ended for deployment 11
<4> 2019-09-20 15:16:07.602 +00:00 [WRN] - Updating reported properties failed with error The operation has timed out. type Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException
<6> 2019-09-20 15:16:12.672 +00:00 [INF] - Plan execution started for deployment 11
<6> 2019-09-20 15:16:12.672 +00:00 [INF] - Executing command: "Start module modbusclient"
<6> 2019-09-20 15:16:14.341 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module mbpa]\n  [Start module mbpa]\n  [Saving mbpa to store]\n)"
<6> 2019-09-20 15:16:14.341 +00:00 [INF] - Executing command: "Stop module mbpa"
<6> 2019-09-20 15:16:14.356 +00:00 [INF] - Executing command: "Start module mbpa"
<6> 2019-09-20 15:16:16.305 +00:00 [INF] - Executing command: "Saving mbpa to store"
<6> 2019-09-20 15:16:16.305 +00:00 [INF] - Plan execution ended for deployment 11
<4> 2019-09-20 15:26:12.613 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 196
<4> 2019-09-20 15:36:17.689 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 196
<4> 2019-09-20 15:46:22.700 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 196
<4> 2019-09-20 15:56:27.708 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 196
<4> 2019-09-20 16:06:32.725 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 196
<6> 2019-09-20 16:09:57.541 +00:00 [INF] - Starting compaction of stores
<6> 2019-09-20 16:09:57.545 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2019-09-20 16:09:57.554 +00:00 [INF] - Starting compaction of store default
<6> 2019-09-20 16:09:57.554 +00:00 [INF] - Starting compaction of store moduleState
<4> 2019-09-20 16:16:37.737 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 196
~~~

**Comment by veyalla** [comment]
Can you confirm `docker exec edgeAgent printenv` is showing `MaxRestartCount` env var?

If not, you might need to perform the steps described here (presuming you're setting the env var in deployment for edge agent): https://github.com/Azure/iotedge/issues/1590#issuecomment-527545210

**Comment by vteplyuk** [comment]
Yes, it set to 2147483647:
```
...........
IOTEDGE_APIVERSION=2019-01-30
MaxRestartCount=2147483647
NetworkId=azure-iot-edge
...........
```

Actually, when gateway reconnected to internet, all modules restarted.

However, when gateway is offline, edgeAgent stop restarting modules, printing this error:
```
<4> 2019-09-20 15:26:12.613 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 196
<4> 2019-09-20 15:36:17.689 +00:00 [WRN] - Agent reconcile concluded with errors.
```

**Comment by veyalla** [comment]
Thanks for confirming. 

@philipktlin / @varunpuranik - can you PTAL?

**Comment by varunpuranik** [comment]
From the logs, it looks  like the EdgeAgent is getting stuck in a reconcile operation, and the subsequent reconcile operations are timing out. 

What is the version of the EdgeAgent that you are running? It should be at the beginning of the EdgeAgent logs. 

There was a locking issue in the EdgeAgent that was fixed in one of our recent releases. Can you try with 1.0.9-rc2 of the EdgeAgent and see if you can repro the issue?

**Comment by vteplyuk** [comment]
Thank you, @varunpuranik, currently it's edgeAgent 1.0.8.1.24554792; I'll try 1.0.9-rc2 and will post update

**Comment by vteplyuk** [comment]
Updated edgeAgent  to 1.0.9-rc2.24731616 (99d6942c58c3a73b1ff2827278f5f5407fd954da)

Device boot offline - modules continuously restarted, as expected.
After many hours of testing, device connected online - everything work w/o issues.

However, when device disconnected again, modules not restarted anymore, edgeAgent log show "reconcile errors", after that modules not restarted.
```
<6> 2019-09-24 18:28:03.299 +00:00 [INF] - Executing command: "Saving mbpa to store"
<6> 2019-09-24 18:28:03.300 +00:00 [INF] - Plan execution ended for deployment 13
<4> 2019-09-24 18:37:59.547 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 200
<4> 2019-09-24 18:48:04.603 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 200
```

Did it one more time - connected and disconnected device - module restarted for some time and, finally, "reconcile errors":
```
<6> 2019-09-24 18:55:24.591 +00:00 [INF] - Plan execution ended for deployment 13
<6> 2019-09-24 18:55:29.919 +00:00 [INF] - Module 'mbpa' scheduled to restart after 20s (16s left).
<4> 2019-09-24 19:00:29.960 +00:00 [WRN] - Updating reported properties failed with error The operation has timed out. type Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException
<6> 2019-09-24 19:00:35.037 +00:00 [INF] - Plan execution started for deployment 13
<6> 2019-09-24 19:00:35.038 +00:00 [INF] - Executing command: "Start module modbusclient"
<6> 2019-09-24 19:00:36.813 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module mbpa]\n  [Start module mbpa]\n  [Saving mbpa to store]\n)"
<6> 2019-09-24 19:00:36.813 +00:00 [INF] - Executing command: "Stop module mbpa"
<6> 2019-09-24 19:00:36.824 +00:00 [INF] - Executing command: "Start module mbpa"
<6> 2019-09-24 19:00:39.187 +00:00 [INF] - Executing command: "Saving mbpa to store"
<6> 2019-09-24 19:00:39.191 +00:00 [INF] - Plan execution ended for deployment 13
<4> 2019-09-24 19:05:39.406 +00:00 [WRN] - Updating reported properties failed with error The operation has timed out. type Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException
<6> 2019-09-24 19:05:44.490 +00:00 [INF] - Plan execution started for deployment 13
<6> 2019-09-24 19:05:44.491 +00:00 [INF] - Executing command: "Start module modbusclient"
<6> 2019-09-24 19:05:46.303 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module mbpa]\n  [Start module mbpa]\n  [Saving mbpa to store]\n)"
<6> 2019-09-24 19:05:46.303 +00:00 [INF] - Executing command: "Stop module mbpa"
<6> 2019-09-24 19:05:46.309 +00:00 [INF] - Executing command: "Start module mbpa"
<6> 2019-09-24 19:05:48.523 +00:00 [INF] - Executing command: "Saving mbpa to store"
<6> 2019-09-24 19:05:48.526 +00:00 [INF] - Plan execution ended for deployment 13
<6> 2019-09-24 19:06:40.544 +00:00 [INF] - Starting periodic operation refresh twin config...
<4> 2019-09-24 19:10:48.757 +00:00 [WRN] - Updating reported properties failed with error The operation has timed out. type Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException
<6> 2019-09-24 19:10:53.844 +00:00 [INF] - Plan execution started for deployment 13
<6> 2019-09-24 19:10:53.845 +00:00 [INF] - Executing command: "Start module modbusclient"
<6> 2019-09-24 19:10:55.591 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module mbpa]\n  [Start module mbpa]\n  [Saving mbpa to store]\n)"
<6> 2019-09-24 19:10:55.591 +00:00 [INF] - Executing command: "Stop module mbpa"
<6> 2019-09-24 19:10:55.598 +00:00 [INF] - Executing command: "Start module mbpa"
<6> 2019-09-24 19:10:57.930 +00:00 [INF] - Executing command: "Saving mbpa to store"
<6> 2019-09-24 19:10:57.939 +00:00 [INF] - Plan execution ended for deployment 13
<4> 2019-09-24 19:20:53.793 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 200
<4> 2019-09-24 19:30:58.804 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 200
<6> 2019-09-24 19:32:15.237 +00:00 [INF] - Starting compaction of stores
<6> 2019-09-24 19:32:15.239 +00:00 [INF] - Starting compaction of store moduleState
<6> 2019-09-24 19:32:15.242 +00:00 [INF] - Starting compaction of store default
<6> 2019-09-24 19:32:15.245 +00:00 [INF] - Starting compaction of store deploymentConfig
<4> 2019-09-24 19:41:03.820 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 200
<4> 2019-09-24 19:51:08.833 +00:00 [WRN] - Agent reconcile concluded with errors.
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 133
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 200

```

**Comment by philipktlin** [comment]
Would you please share deployment twin for your iotedge device? please remember to remove all sensitive data.

**Comment by vteplyuk** [comment]
@philipktlin, our deployment json:
```
{
    "id": "xxx-demo",
    "schemaVersion": null,
    "labels": {},
    "content": {
        "modulesContent": {
            "$edgeAgent": {
                "properties.desired": {
                    "modules": {
                        "mbpa": {
                            "settings": {
                                "image": "xxx.azurecr.io/xxx:3",
                                "createOptions": "{\"ExposedPorts\":{\"8889/tcp\":{}},\"HostConfig\":{\"PortBindings\":{\"8889/tcp\":[{\"HostPort\":\"8889\"}]}}}"
                            },
                            "type": "docker",
                            "version": "1.0",
                            "status": "running",
                            "restartPolicy": "always"
                        },
                        "fieldgateway": {
                            "settings": {
                                "image": "xxx.azurecr.io/yyy",
                                "createOptions": "{\"ExposedPorts\":{\"8888/tcp\":{}},\"HostConfig\":{\"Binds\":[\"data:/app/data\"],\"PortBindings\":{\"8888/tcp\":[{\"HostPort\":\"8888\"}]}}}"
                            },
                            "type": "docker",
                            "version": "1.0",
                            "status": "running",
                            "restartPolicy": "always"
                        },
                        "logmodule": {
                            "settings": {
                                "image": "xxx.azurecr.io/zzz:0.6",
                                "createOptions": "{\"ExposedPorts\":{\"8877/tcp\":{}},\"HostConfig\":{\"Binds\":[\"data:/app/data\"],\"PortBindings\":{\"8877/tcp\":[{\"HostPort\":\"8877\"}]}}}"
                            },
                            "type": "docker",
                            "version": "1.0",
                            "status": "running",
                            "restartPolicy": "always"
                        },
                        "analytics": {
                            "settings": {
                                "image": "xxx.azurecr.io/ccc:0.6",
                                "createOptions": "{\"ExposedPorts\":{\"5001/tcp\":{}}}"
                            },
                            "type": "docker",
                            "version": "1.0",
                            "status": "running",
                            "restartPolicy": "always"
                        },
                        "modbusclient": {
                            "settings": {
                                "image": "xxx.azurecr.io/ddd:0.1",
                                "createOptions": ""
                            },
                            "type": "docker",
                            "version": "1.0",
                            "status": "running",
                            "restartPolicy": "on-unhealthy"
                        }
                    },
                    "runtime": {
                        "settings": {
                            "minDockerVersion": "v1.25",
                            "registryCredentials": {
                            }
                        },
                        "type": "docker"
                    },
                    "schemaVersion": "1.0",
                    "systemModules": {
                        "edgeAgent": {
                            "settings": {
                                "image": "mcr.microsoft.com/azureiotedge-agent:1.0.9-rc2",
                                "createOptions": ""
                            },
                            "type": "docker",
                            "env": {
                                "MaxRestartCount": {
                                    "value": "2147483647"
                                }
                            }
                        },
                        "edgeHub": {
                            "settings": {
                                "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
                                "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"443/tcp\":[{\"HostPort\":\"443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}]}}}"
                            },
                            "type": "docker",
                            "status": "running",
                            "restartPolicy": "always"
                        }
                    }
                }
            },
            "$edgeHub": {
                "properties.desired": {
                    "routes": {
                        "route": "FROM /messages/* INTO $upstream"
                    },
                    "schemaVersion": "1.0",
                    "storeAndForwardConfiguration": {
                        "timeToLiveSecs": 7200
                    }
                }
            }
        }
    },
    "targetCondition": "deviceId='ggg'",
    "createdTimeUtc": "2019-09-23T19:27:44.402Z",
    "lastUpdatedTimeUtc": "2019-09-23T19:27:44.402Z",
    "priority": 10,
    "systemMetrics": {
        "results": {
            "appliedCount": 1,
            "reportedSuccessfulCount": 1,
            "reportedFailedCount": 0,
            "targetedCount": 1
        },
        "queries": {
            "Targeted": "select deviceId from devices where capabilities.iotEdge = true and deviceId='ddd'",
            "Applied": "select deviceId from devices.modules where moduleId = '$edgeAgent' and configurations.[[demo2]].status = 'Applied'",
            "Reporting Success": "select deviceId from devices.modules where moduleId = '$edgeAgent' and configurations.[[demo2]].status = 'Applied' and properties.desired.$version = properties.reported.lastDesiredVersion and properties.reported.lastDesiredStatus.code = 200",
            "Reporting Failure": "select deviceId from devices.modules where moduleId = '$edgeAgent' and configurations.[[demo2]].status = 'Applied' and properties.desired.$version = properties.reported.lastDesiredVersion and properties.reported.lastDesiredStatus.code != 200"
        }
    },
    "metrics": {
        "results": {},
        "queries": {}
    },
    "etag": "MQ=="
}
```

**Comment by lt72** [comment]
@darobs Please check this one.

**Comment by lt72** [comment]
@damonbarry  PTAL

**Comment by damonbarry** [comment]
I tried to repro this using a [simple module](https://github.com/damonbarry/my-azure-iot-snippets/tree/master/edge/modules/src/i-need-internet) that wakes up every minute and does an HTTP GET request for the [LICENSE](https://raw.githubusercontent.com/Azure/iotedge/master/LICENSE) file in our repo root.

I used the following commands on an Ubuntu 18.04 VM to simulate a loss of network connectivity:
```bash
nslookup {my-hub}.azure-devices.net  # returned xxx.xxx.xxx.xxx
nslookup raw.githubusercontent.com  # returned 151.101.184.133
docker network ls  # network ID of "azure-iot-edge" network is 8a58b6403551
ip addr show  # network interface for network with ID 8a58b6403551 is br-8a58b6403551

sudo tc qdisc add dev br-8a58b6403551 root handle 1: prio priomap 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
sudo tc qdisc add dev br-8a58b6403551 parent 1:2 handle 20: netem loss 100%
sudo tc filter add dev br-8a58b6403551 parent 1:0 protocol ip u32 match ip src xxx.xxx.xxx.xxx flowid 1:2
sudo tc filter add dev br-8a58b6403551 parent 1:0 protocol ip u32 match ip src 151.101.184.133 flowid 1:2
```

...and I used the following command to restore network connectivity:
```bash
sudo tc qdisc delete dev br-8a58b6403551 root
```

I've been dropping/reestablishing the connection over most of the day, and haven't reproduced the issue yet. I'm using recent bits from master (effectively 1.0.9-RC4), so something may have changed since @vteplyuk's last comments in late September. Also, my deployment is much smaller than the deployment described in the comments (just `$edgeAgent`, `$edgeHub`--which isn't doing anything, and my sample module), so there's potentially a lot less going on in the system. There might be differences in timing as well.

@vteplyuk is this still an issue for you? Logs with extra debug information would give us more details about those reconcile errors.
