### ISSUE TITLE
EdgeHub fails to update / merge desired properties from device twin

### ISSUE THREAD

**Issue by Aashikms** [Azure/iotedge#1741]
## Expected Behavior
When Desired properties of edgeHub should updated when deployed from azure portal

## Current Behavior
Showing error when edgeHub tries to get config information from the device twin.

### Device (Host) Operating System
Raspbian GNU/Linux 9.9 (stretch)

### Architecture
arm32v7

### Container Operating System
Linux

#### iotedged
1.0.6.1

#### Edge Agent
1.0.0

#### Edge Hub
1.0.0

<details>
<summary>edge-hub logs</summary>

```
2019-09-23 13:46:51 +00:00 Starting Edge Hub
2019-09-23 13:46:52.214 +00:00 Edge Hub Main()
[09/23/2019 01:46:57.815 PM] Found intermediate certificates: [CN=iotedged workload ca:10/23/2019 13:36:53],[CN=10.1.17.94.ca:10/23/2019 13:36:53],[CN=Azure IoT Hub Intermediate Cert Test Only:10/23/2019 13:35:47],[CN=Azure IoT Hub CA Cert Test Only:10/23/2019 13:35:19]
<6> 2019-09-23 13:47:02.427 +00:00 [INF] - Created persistent store at /tmp/edgeHub
<6> 2019-09-23 13:47:02.916 +00:00 [INF] - Initializing Edge Hub
<6> 2019-09-23 13:47:02.919 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2019-09-23 13:47:02.927 +00:00 [INF] - Version - 1.0.8.1.24554792 (8a9cfedfc6c7455c080dcee6ee21978069024d2f)
<6> 2019-09-23 13:47:02.927 +00:00 [INF] - OptimizeForPerformance=False
<6> 2019-09-23 13:47:02.944 +00:00 [INF] - Loaded server certificate with expiration date of "2019-10-23T13:36:53.0000000+00:00"
<6> 2019-09-23 13:47:03.131 +00:00 [INF] - Created device scope identities cache
<6> 2019-09-23 13:47:03.221 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2019-09-23 13:47:03.253 +00:00 [INF] - Created new message store
<6> 2019-09-23 13:47:03.299 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2019-09-23 13:47:04.018 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2019-09-23 13:47:04.334 +00:00 [INF] - Initialized storing twin manager
<6> 2019-09-23 13:47:04.444 +00:00 [INF] - Initializing configuration
<6> 2019-09-23 13:47:04.629 +00:00 [INF] - New device connection for device Pi1/$edgeHub
<6> 2019-09-23 13:47:05.326 +00:00 [INF] - Attempting to connect to IoT Hub for client Pi1/$edgeHub via AMQP...
<6> 2019-09-23 13:47:05.701 +00:00 [INF] - Starting periodic operation Get EdgeHub config...
<6> 2019-09-23 13:47:05.927 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2019-09-23 13:47:05.936 +00:00 [INF] - Initialized edge hub configuration
<6> 2019-09-23 13:47:06.056 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2019-09-23 13:47:06.773 +00:00 [INF] - Scheduling server certificate renewal for "2019-10-23T13:34:23.0006283Z".
<6> 2019-09-23 13:47:06.789 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2019-09-23 13:47:06.826 +00:00 [INF] - Starting MQTT head
<6> 2019-09-23 13:47:07.342 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2019-09-23 13:47:07.841 +00:00 [INF] - Starting AMQP head
<6> 2019-09-23 13:47:07.913 +00:00 [INF] - Started MQTT head
<6> 2019-09-23 13:47:08.389 +00:00 [INF] - Started AMQP head
<6> 2019-09-23 13:47:08.407 +00:00 [INF] - Starting HTTP head
<6> 2019-09-23 13:47:09.110 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
<6> 2019-09-23 13:47:09.328 +00:00 [INF] - Creating key {d957be80-3a15-4274-9952-8b6ef0776961} with creation date 2019-09-23 13:47:09Z, activation date 2019-09-23 13:47:09Z, and expiration date 2019-12-22 13:47:09Z.
<4> 2019-09-23 13:47:09.464 +00:00 [WRN] - No XML encryptor configured. Key {d957be80-3a15-4274-9952-8b6ef0776961} may be persisted to storage in unencrypted form.
<6> 2019-09-23 13:47:09.531 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-d957be80-3a15-4274-9952-8b6ef0776961.xml"'.
<4> 2019-09-23 13:47:11.984 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2019-09-23 13:47:12.179 +00:00 [INF] - Started HTTP head
<6> 2019-09-23 13:47:12.450 +00:00 [INF] - Exiting disconnected state
<6> 2019-09-23 13:47:12.476 +00:00 [INF] - Received device connected callback
<6> 2019-09-23 13:47:12.570 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2019-09-23 13:47:12.574 +00:00 [INF] - Processing subscriptions for client Pi1/$edgeHub.
<6> 2019-09-23 13:47:12.615 +00:00 [INF] - Cloud connection for Pi1/$edgeHub is True
<6> 2019-09-23 13:47:12.676 +00:00 [INF] - Connection status for Pi1/$edgeHub changed to ConnectionEstablished
<6> 2019-09-23 13:47:12.696 +00:00 [INF] - Client Pi1/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2019-09-23 13:47:12.734 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2019-09-23 13:47:12.811 +00:00 [INF] - Entering connected state
<6> 2019-09-23 13:47:12.841 +00:00 [INF] - Created cloud proxy for client Pi1/$edgeHub via AMQP, with client operation timeout 20 seconds.
<6> 2019-09-23 13:47:12.892 +00:00 [INF] - Initialized cloud proxy 9f49d15c-6d65-4fab-a22b-c7053ee2aa82 for Pi1/$edgeHub
<6> 2019-09-23 13:47:12.944 +00:00 [INF] - Created cloud connection for client Pi1/$edgeHub
<6> 2019-09-23 13:47:14.805 +00:00 [INF] - Updated reported properties for Pi1/$edgeHub
<4> 2019-09-23 13:47:16.278 +00:00 [WRN] - Error getting edge hub config from twin desired properties
System.InvalidOperationException: Error parsing route sensorToIoTHub - Exception of type 'Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException' was thrown. ---> Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException: Exception of type 'Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException' was thrown.
   at Microsoft.Azure.Devices.Routing.Core.Query.ErrorListener.Validate() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/query/ErrorListener.cs:line 24
   at Microsoft.Azure.Devices.Routing.Core.RouteFactory.ParseRoute(String routeString, IMessageSource& messageSource, String& condition, Endpoint& endpoint) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/RouteFactory.cs:line 52
   at Microsoft.Azure.Devices.Routing.Core.RouteFactory.Create(String routeString) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/RouteFactory.cs:line 31
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.GetEdgeHubConfig(DesiredProperties desiredProperties) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 231
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.GetEdgeHubConfig(DesiredProperties desiredProperties) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 237
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.GetConfigInternal() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 196
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.GetConfigInternal() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 204
<4> 2019-09-23 13:47:16.431 +00:00 [WRN] - Empty edge hub configuration received. Ignoring...
<6> 2019-09-23 13:47:16.438 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config
<6> 2019-09-23 13:47:20.330 +00:00 [INF] - Updated reported properties for Pi1/$edgeHub
<6> 2019-09-23 13:52:06.115 +00:00 [INF] - Reauthenticating connected clients
<6> 2019-09-23 13:57:06.056 +00:00 [INF] - Reauthenticating connected clients
<6> 2019-09-23 14:02:06.066 +00:00 [INF] - Reauthenticating connected clients
<4> 2019-09-23 14:04:01.386 +00:00 [WRN] - Error merging desired properties patch with existing desired properties for edge hub
System.InvalidOperationException: Error parsing route sensorsToIoTHub - Exception of type 'Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException' was thrown. ---> Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException: Exception of type 'Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException' was thrown.
   at Microsoft.Azure.Devices.Routing.Core.Query.ErrorListener.Validate() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/query/ErrorListener.cs:line 24
   at Microsoft.Azure.Devices.Routing.Core.RouteFactory.ParseRoute(String routeString, IMessageSource& messageSource, String& condition, Endpoint& endpoint) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/RouteFactory.cs:line 52
   at Microsoft.Azure.Devices.Routing.Core.RouteFactory.Create(String routeString) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/RouteFactory.cs:line 31
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.GetEdgeHubConfig(DesiredProperties desiredProperties) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 231
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.GetEdgeHubConfig(DesiredProperties desiredProperties) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 237
   at Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnection.PatchDesiredProperties(TwinCollection baseline, TwinCollection patch) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs:line 280
<6> 2019-09-23 14:04:01.732 +00:00 [INF] - Updated reported properties for Pi1/$edgeHub
```
</details>

## Additional Information
1. Only edgeAgent and edgeHub in running
2. edgeHub is acting as transparent gateway
3. Since routes are not getting updated because of stated issue, Message are not being forwarded to Iothub.

**Comment by myagley** [comment]
What does the route look like for `sensorToIoTHub`? It is failing to parse.

**Comment by Aashikms** [comment]
Thanks for insight on error.
Yes it was a mistake in my Route, I had typo error mentioned FROM in the route 2 times. I corrected it now it is working fine and i will close the issue.
