### ISSUE TITLE
iotedge module connection lose to edgeHub

### ISSUE THREAD

**Issue by scottmur** [Azure/iotedge#1804]
## Expected Behavior
data is collected via opc publisher and routed up stream to azure iot hub

## Current Behavior
Tell us what happens instead of the expected behavior
edgeHub loses connection. data is NOT routed to iothub

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. unknown.  Has occured by restarted iotedge modules 
2.
3.
4.

## Context (Environment)
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-65-generic x86_64)

root@nzs048iotedg01m:~# iotedge list
NAME                   STATUS           DESCRIPTION      CONFIG
opcpublisher           running          Up 20 hours      mcr.microsoft.com/iotedge/opc-publisher:2.5.1
messageprocessor4j     running          Up 20 hours      aothistoriannonprodacr.azurecr.io/messageprocessor4j:0.7.767
edgeAgent              running          Up 20 hours      mcr.microsoft.com/azureiotedge-agent:1.0.8
edgeHub                running          Up 20 hours      mcr.microsoft.com/azureiotedge-hub:1.0.8
logspout-loganalytics  running          Up 20 hours      veyalla/logspout-loganalytics:linux-amd64

root@nzs048iotedg01m:~# docker version
Client:
 Version:           3.0.6
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        a63faebc
 Built:             Wed Jun 19 22:56:37 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       b07f53d
  Built:            Wed Jun 19 22:28:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with IoT Hub MQTT port - Error
    Could not connect to aot-historian-ae-qa-iothub.azure-devices.net:8883
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
× container on the default network can connect to IoT Hub MQTT port - Error
    Container on the default network could not connect to aot-historian-ae-qa-iothub.azure-devices.net:8883
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the azure-iot-edge network could not connect to aot-historian-ae-qa-iothub.azure-devices.net:8883
√ Edge Hub can bind to ports on host - OK

15 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
3 check(s) raised errors. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS  Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-65-generic x86_64)
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [Linux containers]: 

### Runtime Versions
* iotedged [run `iotedge version`]:  1.08
* Edge Agent [image tag (e.g. 1.0.0)]:  1.08
* Edge Hub [image tag (e.g. 1.0.0)]:  1.08
* Docker/Moby [run `docker version`]: 3.06

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354757239+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=155
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354766152+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=156
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354775274+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=157
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354786440+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=158
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354797852+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=159
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354807274+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=160
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354822683+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=161
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354832543+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=162
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354843488+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=163
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354858423+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=164
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354867404+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=165
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354876459+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=166
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.354886850+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=167
Oct 3 14:45:51 nzs048iotedg01m dockerd[1400]: time="2019-10-03T14:45:51.355012093+13:00" level=warning msg="got error while decoding json" error="unexpected EOF" retries=168
Oct 3 14:45:51 nzs048iotedg01m iotedged[2640]: 2019-10-03T01:45:51Z [INFO] - [mgmt] - - - [2019-10-03 01:45:51.658773524 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3288 "-" "-" auth_id(-)
Oct 3 14:45:56 nzs048iotedg01m iotedged[2640]: 2019-10-03T01:45:56Z [INFO] - [mgmt] - - - [2019-10-03 01:45:56.659222164 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3288 "-" "-" auth_id(-)
Oct 3 14:46:01 nzs048iotedg01m iotedged[2640]: 2019-10-03T01:46:01Z [INFO] - [mgmt] - - - [2019-10-03 01:46:01.668120591 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3288 "-" "-" auth_id(-)
Oct 3 14:46:06 nzs048iotedg01m iotedged[2640]: 2019-10-03T01:46:06Z [INFO] - [mgmt] - - - [2019-10-03 01:46:06.677292972 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3288 "-" "-" auth_id(-)

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/$edgeHub
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/opcpublisher is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/opcpublisher changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/opcpublisher
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/messageprocessor4j is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/messageprocessor4j changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/messageprocessor4j
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/messageprocessor4j is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/messageprocessor4j changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/messageprocessor4j
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/$edgeHub is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/$edgeHub changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/$edgeHub
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/opcpublisher is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/opcpublisher changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/opcpublisher
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/messageprocessor4j is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/messageprocessor4j changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/messageprocessor4j
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Cloud connection for nzs048iotedg01m/$edgeHub is False
<6> 2019-10-03 00:01:50.141 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Connection status for nzs048iotedg01m/$edgeHub changed to Disconnected
<7> 2019-10-03 00:01:50.141 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Invoking cloud connection lost event for nzs048iotedg01m/$edgeHub
<6> 2019-10-03 00:01:50.140 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy] - Retrying cloud proxy operation SendMessageBatchAsync for nzs048iotedg01m/messageprocessor4j.
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.OperationCanceledException: The operation was canceled.
at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpLinkHelper.SendAmqpMessageAsync(SendingAmqpLink sendingAmqpLink, AmqpMessage message, TimeSpan timeout)
at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.SendMessageAsync(AmqpMessage message, TimeSpan timeout)
at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.SendEventAsync(AmqpMessage message, TimeSpan timeout)
at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendEventAsync(IEnumerable1 messages, CancellationToken cancellationToken) at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func1 asyncOperation)
--- End of inner exception stack trace ---
at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func1 asyncOperation) at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(IEnumerable1 messages, CancellationToken cancellationToken)
at Microsoft.Azure.Devices.Client.InternalClient.SendEventBatchAsync(IEnumerable1 messages) at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Cloud Proxy/ConnectivityAwareClient.cs:line 174 --- End of stack trace from previous location where exception was thrown --- at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azu
re.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 134
at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azu

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by scottmur** [comment]
Look at log analytics for last 48 hours
container_logs_CL
| where msg_s contains "IotHubCommunicationException" 
| summarize Count=count() by hostname_s
| top 100 by Count desc 

![image](https://user-images.githubusercontent.com/44758719/66164228-afc24600-e68e-11e9-8a8d-97fd77b6580a.png)

**Comment by jmbrunskill** [comment]
For some additional info on this problem.
My understanding is the Murray tried restarting the whole, iotedge service, as well as restarting docker as well. Only after rebooting the whole ubuntu server was this problem resolved.

**Comment by lt72** [comment]
@vipeller @varunpuranik can you please take a look at this one or re-route appropriately?

**Comment by veyalla** [comment]
Closing as I believe setting DNS server for the local environment helped here. 

Please re-open if that's not the case.
