### ISSUE TITLE
Host IP resolution fails when Docker Desktop is installed after IoT Edge on Windows.

### ISSUE THREAD

**Issue by iotblackbelt** [Azure/iotedge#1898]
When IoT Edge is installed on Windows (10) with Windows Containers, and Docker Desktop is installed afterwards, the resolution of the IP address of the host is failing and therefore custom modules (C#) are failing at OpenAsync() with a time-out.

`Unhandled Exception: System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector.InitializeTransport(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnection(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.AmqpSessionCreator(DeviceIdentity deviceIdentity, ILinkFactory linkFactory, AmqpSessionSettings amqpSessionSettings, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at CustomModule.Program.Init() in C:\app\Program.cs:line 70
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CustomModule.Program.Main(String[] args) in C:\app\Program.cs:line 36` 

## Expected Behavior
Based on the documentation IoT Edge and Docker Desktop can run on the same machine, without the modules failing. See: `https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows#manage-module-containers`.

## Current Behavior
When Docker Desktop is installed after IoT Edge, custom (C#) modules fail at OpenAsync(), because they can't resolve the IP address of the host. 

## Steps to Reproduce
Detailed set of steps to reproduce the bug:
1. Create a Windows 10 VM in Azure
2. Install IoT Edge using: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows.
3. Deploy the Simulated Temperature Sensor module
4. Execute the command "docker -H npipe:////./pipe/iotedge_moby_engine exec -ti <your_simulated_tempeparature_sensor_module_name> cmd".
5. Execute "ping <your_device_name>" at the command prompt. This should lead to the ping resolving the IP address and successfully executing the ping command.
6. Exit the cmd-line
7. Install Docker Desktop on the IoT Edge device
8. Repeat steps 4 and 5. This should lead to the ping not resolving the IP Address and ping failing.

## How to resolve
There are a couple of steps you can take to resolve this:

- Uninstall Docker Desktop and restart the IoT Edge device.
- Change the network setting in the config.yaml file from "nat" to the default "azure-iot-edge" network.
- Create a new network for IoT Edge using the driver "nat", f.i `iot-edge`: excute "docker -H npipe:////./pipe/iotedge_moby_engine network create --driver nat iot-edge", and change the network setting in the config.yaml file from "nat" to "iot-edge". Restart the IoT Edge service.

**Comment by dmolokanov** [comment]
Hello @iotblackbelt,
You are right, to re-create a network is the only solution here. We should probably update our docs that describe that installing docker desktop afterward is not a supporting scenario.
Thanks for pointing out!

**Comment by dmolokanov** [comment]
I'm closing this issue for the lack of activity. Feel free to re-open it if you additional questions. Thanks!

**Comment by seanmcd-msft** [comment]
I believe the issue here is that windows host networking service that provides the vnet service that  backs docker and does dhcp and mdns is single instance.  you can have multiple docker/moby instances installed. but, you can't have more then 1 of them running at a time.  if you do then the first service instance that starts gets the network resources and the other instance has weird networking problems.  this is described somewhat obliquely here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/advanced in the multiple NAT networks section.
