### ISSUE TITLE
EdgeHub container fails to start on raspberry pi 3

### ISSUE THREAD

**Issue by vishal-uttamchandani** [Azure/iotedge#22]
## Expected Behavior
EdgeHub container should start successfully

## Current Behavior
EdgeHub fails to start with status "Backoff" and exit code 132 displayed on Azure IoT Hub portal

## Steps to Reproduce
1. Setup an IoT device on Azure portal (IoT Hub)
2. Push deployment file containing images for edgeagent and edgehub (edgeHub is being passed an environment variable ```OptimizeForPerformance = false```). See Azure/iot-edge-v1#475 for the reason.
3. Install iotedgectl on rapsberry pi 3
4. setup iotedgectl by passing device connection string (obtained from the azure portal)
5. Run ```iotedgectl start``` on raspberry pi 3

## Context (Environment)
Images are being pulled down successfully, device is shown as connected on Azure portal, edge agent starts successfully. But edgehub fails to start due to some certificate error.

### Device (Host) Operating System
Raspbian stretch lite (April 2018)

### Architecture
ARM

### Container Operating System
linux containers

#### iotedged
```iotedgectl --version```
iotedgectl 1.0.0rc22

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:24:36 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:20:37 2018
  OS/Arch:      linux/arm
  Experimental: false
```

## Logs
[log from stopped edgehub container](https://git.io/fNYR9)
```
[2018-07-15 19:13:35 +00:00]: Starting Edge Hub
[07/15/2018 07:13:35.830 PM] Edge Hub Main()

Unhandled Exception: System.AggregateException: One or more errors occurred. (error:2006D080:BIO routines:BIO_new_file:no such file) ---> Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetServerCertificatesFromFile(String certPath, String certName) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 213
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 65
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 31
```

**Comment by neumanndaniel** [comment]
iotedgectl maybe the issue. With the Azure IoT Edge GA version provisioning for Edge devices has changed and you are not using iotedgectl anymore.

-> https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux
-> https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm
