### ISSUE TITLE
V2 - Why does the edgeHub module stop?

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/iotedge#228]
Hi

I've installed the IoT Edge runtime on my arm32v7 (armhf) device.

Before running below commands, I did a `docker login` on the device and to check that the device/I was able to `docker pull` the wanted module image.

Then, I started the IoT Edge runtime:

```bash
root@ddau3:/var/run/iotedge# IOTEDGE_HOMEDIR=/var/lib/iotedge /usr/bin/iotedged -c /etc/iotedge/config.yaml &> ~/iotedged.log &
[1] 18748
root@ddau3:/var/run/iotedge# tail -f ~/iotedged.log
<6>2018-08-30T12:38:06Z [INFO] - Provisioning edge device...
<6>2018-08-30T12:38:06Z [INFO] - Manually provisioning device "runes_device" in hub "hebh-IoT-Hub-Test.azure-devices.net"
<6>2018-08-30T12:38:06Z [INFO] - Finished provisioning edge device.
<6>2018-08-30T12:38:06Z [INFO] - Starting management API...
<6>2018-08-30T12:38:06Z [INFO] - Listening on unix:///var/run/iotedge/mgmt.sock with 1 thread for management API.
<6>2018-08-30T12:38:06Z [INFO] - Starting workload API...
<6>2018-08-30T12:38:06Z [INFO] - Listening on unix:///var/run/iotedge/workload.sock with 1 thread for workload API.
<6>2018-08-30T12:38:06Z [INFO] - Starting watchdog with 60 second frequency...
<6>2018-08-30T12:38:06Z [INFO] - Checking edge runtime status
<6>2018-08-30T12:38:06Z [INFO] - Edge runtime status is stopped, starting module now...
<6>2018-08-30T12:38:21Z [INFO] - [mgmt] - - - [2018-08-30 12:38:21.251400397 UTC] "GET /systeminfo?api-version=2018-06-28 HTTP/1.1" 200 OK 103 "-" "-" pid(18772)
<6>2018-08-30T12:38:22Z [INFO] - [work] - - - [2018-08-30 12:38:22.924611388 UTC] "POST /modules/%24edgeAgent/genid/636673481035774782/decrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1252 "-" "-" pid(18772)
<6>2018-08-30T12:38:24Z [INFO] - [mgmt] - - - [2018-08-30 12:38:24.919325119 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 912 "-" "-" pid(18772)
<6>2018-08-30T12:38:30Z [INFO] - [work] - - - [2018-08-30 12:38:30.306035213 UTC] "POST /modules/%24edgeAgent/genid/636673481035774782/decrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1252 "-" "-" pid(18772)
<6>2018-08-30T12:38:31Z [INFO] - [mgmt] - - - [2018-08-30 12:38:31.177189269 UTC] "GET /identities/?api-version=2018-06-28 HTTP/1.1" 200 OK 310 "-" "-" pid(18772)
<6>2018-08-30T12:38:31Z [INFO] - [mgmt] - - - [2018-08-30 12:38:31.644898063 UTC] "PUT /identities/vicStore-1?api-version=2018-06-28 HTTP/1.1" 200 OK 100 "-" "-" pid(18772)
<4>2018-08-30T12:38:34Z [WARN] - Container runtime error - ApiError(ApiError { code: Unauthorized, content: Some(Object({"message": String("Get https://hebhddauazureiotedgetest1.azurecr.io/v2/azureiotedge-vic-store-linux-arm/manifests/0.3: unauthorized: authentication required")})) })
<6>2018-08-30T12:38:34Z [INFO] - [mgmt] - - - [2018-08-30 12:38:34.175365710 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 270 "-" "-" pid(18772)
<4>2018-08-30T12:38:34Z [WARN] - Container runtime error - ApiError(ApiError { code: Unauthorized, content: Some(Object({"message": String("Get https://hebhddauazureiotedgetest1.azurecr.io/v2/azureiotedge-vic-store-linux-arm/manifests/0.3: unauthorized: authentication required")})) })
<6>2018-08-30T12:38:34Z [INFO] - [mgmt] - - - [2018-08-30 12:38:34.980229446 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 270 "-" "-" pid(18772)
<4>2018-08-30T12:38:40Z [WARN] - Container runtime error - ApiError(ApiError { code: Unauthorized, content: Some(Object({"message": String("Get https://hebhddauazureiotedgetest1.azurecr.io/v2/azureiotedge-vic-store-linux-arm/manifests/0.3: unauthorized: authentication required")})) })
<6>2018-08-30T12:38:40Z [INFO] - [mgmt] - - - [2018-08-30 12:38:40.862863166 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 270 "-" "-" pid(18772)
<4>2018-08-30T12:38:52Z [WARN] - Container runtime error - ApiError(ApiError { code: Unauthorized, content: Some(Object({"message": String("Get https://hebhddauazureiotedgetest1.azurecr.io/v2/azureiotedge-vic-store-linux-arm/manifests/0.3: unauthorized: authentication required")})) })
<6>2018-08-30T12:38:52Z [INFO] - [mgmt] - - - [2018-08-30 12:38:52.380470724 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 270 "-" "-" pid(18772)
<4>2018-08-30T12:38:52Z [WARN] - Container already in this state
<6>2018-08-30T12:38:52Z [INFO] - [mgmt] - - - [2018-08-30 12:38:52.915857148 UTC] "POST /modules/edgeHub/stop?api-version=2018-06-28 HTTP/1.1" 304 Not Modified - "-" "-" pid(18772)
<4>2018-08-30T12:38:54Z [WARN] - Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message": String("driver failed programming external connectivity on endpoint edgeHub (94f93c05c8af7f90d4accb902994061e24cda5b2597c8e205333bbec75891bd0): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use")})) })
<6>2018-08-30T12:38:54Z [INFO] - [mgmt] - - - [2018-08-30 12:38:54.054086895 UTC] "POST /modules/edgeHub/start?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 359 "-" "-" pid(18772)
<4>2018-08-30T12:38:54Z [WARN] - Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message": String("driver failed programming external connectivity on endpoint edgeHub (1cf57f838a57f6ac41059dcf2736795ecd044f54f46683a8f48c716aef5aecc6): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use")})) })
<6>2018-08-30T12:38:54Z [INFO] - [mgmt] - - - [2018-08-30 12:38:54.944141344 UTC] "POST /modules/edgeHub/start?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 359 "-" "-" pid(18772)
<4>2018-08-30T12:39:00Z [WARN] - Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message": String("driver failed programming external connectivity on endpoint edgeHub (6d1c4a4b79bb22ce9102cfc17000ead18452d89a48aafa5429743f9d8b9329db): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use")})) })
<6>2018-08-30T12:39:00Z [INFO] - [mgmt] - - - [2018-08-30 12:39:00.965464173 UTC] "POST /modules/edgeHub/start?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 359 "-" "-" pid(18772)
<6>2018-08-30T12:39:06Z [INFO] - Checking edge runtime status
<6>2018-08-30T12:39:06Z [INFO] - Edge runtime is running.
^C
root@ddau3:/var/run/iotedge# date
Thu Aug 30 12:39:47 UTC 2018
root@ddau3:/var/run/iotedge# /usr/bin/iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeHub          stopped          Stopped          mcr.microsoft.com/azureiotedge-hub:1.0
edgeAgent        running          Up 2 minutes     mcr.microsoft.com/azureiotedge-agent:1.0
root@ddau3:/var/run/iotedge# /usr/bin/iotedge --version
iotedge 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)
root@ddau3:/var/run/iotedge# docker version
Client:
 Version:      unknown-version
 API version:  1.31
 Go version:   go1.9.4
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/arm

Server:
 Version:      17.06.0-dev
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.9.4
 Git commit:   INVALID
 Built:        Mon Jul 16 13:38:24 2018
 OS/Arch:      linux/arm
 Experimental: false
root@ddau3:/var/run/iotedge# docker image ls
REPOSITORY                                                              TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/azureiotedge-hub                                      1.0                 5439a2248b5d        9 days ago          247MB
mcr.microsoft.com/azureiotedge-agent                                    1.0                 da31c1e0df4b        9 days ago          231MB
hebhddauazureiotedgetest1.azurecr.io/azureiotedge-vic-store-linux-arm   0.3                 e9c7737023a3        3 months ago        176MB
root@ddau3:/var/run/iotedge#
```

Why does the edgeHub module stop? 

What does the IoT Edge runtime need?

I've disabled my firewall in my device and filled the 'Azure Portal IoT Edge - Device Details - Set Modules - Container Registry Settings' with the credentials of the registry from which where the wanted module should be downloaded from. 

Help is appreciated.

Thank you.

/Henrik

**Comment by veyalla** [comment]
@HenrikBach1 Could share the logs from the edgeHub: `docker logs edgeHub`?

**Comment by HenrikBach1** [comment]
Hi @veyalla ,

Thank you for your input.

* `docker logs edgeHub` is empty.
* Yes, another application is listening on port 443.

However, even when I follow your instructions, from the portal, to let the runtime not to request port 443, and after a restart of  the runtime, I still get the following results:

```bash
<6>2018-09-10T06:43:26Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2018-09-10T06:43:26Z [INFO] - Version - 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)
<6>2018-09-10T06:43:26Z [INFO] - Using config file: /etc/iotedge/config.yaml
<6>2018-09-10T06:43:26Z [INFO] - Using runtime network id azure-iot-edge
<6>2018-09-10T06:43:26Z [INFO] - Initializing the module runtime...
<6>2018-09-10T06:43:26Z [INFO] - Finished initializing the module runtime.
<6>2018-09-10T06:43:26Z [INFO] - Configuring /var/lib/iotedge as the home directory.
<6>2018-09-10T06:43:26Z [INFO] - Configuring certificates...
<6>2018-09-10T06:43:26Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
<6>2018-09-10T06:43:26Z [INFO] - Finished configuring certificates.
<6>2018-09-10T06:43:26Z [INFO] - Initializing hsm...
<6>2018-09-10T06:43:26Z [INFO] - Finished initializing hsm.
<6>2018-09-10T06:43:26Z [INFO] - Detecting if configuration file has changed...
<6>2018-09-10T06:43:26Z [INFO] - No change to configuration file detected.
<6>2018-09-10T06:43:26Z [INFO] - Obtaining workload CA succeeded.
<6>2018-09-10T06:43:26Z [INFO] - Provisioning edge device...
<6>2018-09-10T06:43:26Z [INFO] - Manually provisioning device "runes_device" in hub "hebh-IoT-Hub-Test.azure-devices.net"
<6>2018-09-10T06:43:26Z [INFO] - Finished provisioning edge device.
<6>2018-09-10T06:43:26Z [INFO] - Starting management API...
<6>2018-09-10T06:43:26Z [INFO] - Listening on unix:///var/run/iotedge/mgmt.sock with 1 thread for management API.
<6>2018-09-10T06:43:26Z [INFO] - Starting workload API...
<6>2018-09-10T06:43:26Z [INFO] - Listening on unix:///var/run/iotedge/workload.sock with 1 thread for workload API.
<6>2018-09-10T06:43:26Z [INFO] - Starting watchdog with 60 second frequency...
<6>2018-09-10T06:43:26Z [INFO] - Checking edge runtime status
<6>2018-09-10T06:43:26Z [INFO] - Edge runtime status is stopped, starting module now...
<6>2018-09-10T06:43:32Z [INFO] - [mgmt] - - - [2018-09-10 06:43:32.316359235 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 912
 "-" "iotedge/0.1.0" pid(15792)
<6>2018-09-10T06:43:41Z [INFO] - [mgmt] - - - [2018-09-10 06:43:41.019702154 UTC] "GET /systeminfo?api-version=2018-06-28 HTTP/1.1" 200 OK
103 "-" "-" pid(15762)
<6>2018-09-10T06:43:42Z [INFO] - [work] - - - [2018-09-10 06:43:42.697679399 UTC] "POST /modules/%24edgeAgent/genid/636673481035774782/decr
ypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1252 "-" "-" pid(15762)
<6>2018-09-10T06:43:44Z [INFO] - [mgmt] - - - [2018-09-10 06:43:44.703319634 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 912
 "-" "-" pid(15762)
<6>2018-09-10T06:43:50Z [INFO] - [work] - - - [2018-09-10 06:43:50.050206646 UTC] "POST /modules/%24edgeAgent/genid/636673481035774782/decr
ypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1252 "-" "-" pid(15762)
<6>2018-09-10T06:43:50Z [INFO] - [mgmt] - - - [2018-09-10 06:43:50.913790626 UTC] "GET /identities/?api-version=2018-06-28 HTTP/1.1" 200 OK
 310 "-" "-" pid(15762)
<6>2018-09-10T06:43:51Z [INFO] - [mgmt] - - - [2018-09-10 06:43:51.419878341 UTC] "PUT /identities/vicStore-1?api-version=2018-06-28 HTTP/1
.1" 200 OK 100 "-" "-" pid(15762)
<4>2018-09-10T06:43:54Z [WARN] - Container runtime error - ApiError(ApiError { code: Unauthorized, content: Some(Object({"message": String(
"Get https://hebhddauazureiotedgetest1.azurecr.io/v2/azureiotedge-vic-store-linux-arm/manifests/0.3: unauthorized: authentication required"
)})) })
<6>2018-09-10T06:43:54Z [INFO] - [mgmt] - - - [2018-09-10 06:43:54.717600240 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Inter
nal Server Error 270 "-" "-" pid(15762)
<4>2018-09-10T06:43:55Z [WARN] - Container runtime error - ApiError(ApiError { code: Unauthorized, content: Some(Object({"message": String(
"Get https://hebhddauazureiotedgetest1.azurecr.io/v2/azureiotedge-vic-store-linux-arm/manifests/0.3: unauthorized: authentication required"
)})) })
<6>2018-09-10T06:43:55Z [INFO] - [mgmt] - - - [2018-09-10 06:43:55.439217407 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Inter
nal Server Error 270 "-" "-" pid(15762)
<4>2018-09-10T06:44:01Z [WARN] - Container runtime error - ApiError(ApiError { code: Unauthorized, content: Some(Object({"message": String(
"Get https://hebhddauazureiotedgetest1.azurecr.io/v2/azureiotedge-vic-store-linux-arm/manifests/0.3: unauthorized: authentication required"
)})) })
<6>2018-09-10T06:44:01Z [INFO] - [mgmt] - - - [2018-09-10 06:44:01.820765449 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Inter
nal Server Error 270 "-" "-" pid(15762)
<4>2018-09-10T06:44:15Z [WARN] - Container runtime error - ApiError(ApiError { code: Unauthorized, content: Some(Object({"message": String(
"Get https://hebhddauazureiotedgetest1.azurecr.io/v2/azureiotedge-vic-store-linux-arm/manifests/0.3: unauthorized: authentication required"
)})) })
<6>2018-09-10T06:44:15Z [INFO] - [mgmt] - - - [2018-09-10 06:44:15.101945295 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Inter
nal Server Error 270 "-" "-" pid(15762)
<4>2018-09-10T06:44:15Z [WARN] - Container already in this state
<6>2018-09-10T06:44:15Z [INFO] - [mgmt] - - - [2018-09-10 06:44:15.761078019 UTC] "POST /modules/edgeHub/stop?api-version=2018-06-28 HTTP/1
.1" 304 Not Modified - "-" "-" pid(15762)
<4>2018-09-10T06:44:16Z [WARN] - Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message":
String("driver failed programming external connectivity on endpoint edgeHub (2e0eb302e6a7b1491eb737533ef0d2323cf556a29bda301c30cd44642d4474
41): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use")})) })
<6>2018-09-10T06:44:16Z [INFO] - [mgmt] - - - [2018-09-10 06:44:16.884121024 UTC] "POST /modules/edgeHub/start?api-version=2018-06-28 HTTP/
1.1" 500 Internal Server Error 359 "-" "-" pid(15762)
<4>2018-09-10T06:44:17Z [WARN] - Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message":
String("driver failed programming external connectivity on endpoint edgeHub (1aba5987ac15ffe96664f49984a095d62fc057fce743f1562839ad551abf2e
15): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use")})) })
<6>2018-09-10T06:44:17Z [INFO] - [mgmt] - - - [2018-09-10 06:44:17.794075762 UTC] "POST /modules/edgeHub/start?api-version=2018-06-28 HTTP/
1.1" 500 Internal Server Error 359 "-" "-" pid(15762)
<4>2018-09-10T06:44:23Z [WARN] - Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message":
String("driver failed programming external connectivity on endpoint edgeHub (50a6844bffdeb459196b0aab1aff1902f9b1f918b9e827807d538dc23b47ae
33): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use")})) })
```

Is there a way on the device to tell the runtime not to request port 443?

/Henrik

**Comment by myagley** [comment]
What operating system is this?

The daemon inherits the previous mode of the socket. To unblock you can try running:

```
chown iotedge:iotedge /var/run/iotedge
chown iotedge:iotedge /var/run/iotedge/workload.sock
chown iotedge:iotedge /var/run/iotedge/mgmt.sock
chmod 660 /var/run/iotedge/mgmt.sock
chmod 666 /var/run/iotedge/workload.sock
```

This setup is done by the package when installing, but it looks like the mode/owners for these files were changed somehow.

**Comment by HenrikBach1** [comment]
It is our own Yocto Distribution for our device. For the moment, I install all by hand, due to there is no deb package management on the device.

The Azure IoT Edge runtime (service) is run, for now, by root with owner and group root permissions.

Before applying the rwx permissions for above files, I stopped the service, then applied the permissions, and restarted the service.

However, for now, only the `edgeAgent` is running with these errors:

```bash
2018-09-12 09:44:54.705 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:44:54.706 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-12 09:44:56.137 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Operation timeout expired.) (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.OpenAsync(ConnectionStatusChangesHandler statusChangedHandler, ModuleClient deviceClient) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 112
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.CreateAndOpenDeviceClient(TransportType transport, Option`1 connectionString, ConnectionStatusChangesHandler statusChangedHandler, Option`1 productInfo) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 101
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.OpenAsync(ConnectionStatusChangesHandler statusChangedHandler, ModuleClient deviceClient) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 112
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.CreateAndOpenDeviceClient(TransportType transport, Option`1 connectionString, ConnectionStatusChangesHandler statusChangedHandler, Option`1 productInfo) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 101
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---

---> (Inner Exception #1) System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.OpenAsync(ConnectionStatusChangesHandler statusChangedHandler, ModuleClient deviceClient) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 112
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.CreateAndOpenDeviceClient(TransportType transport, Option`1 connectionString, ConnectionStatusChangesHandler statusChangedHandler, Option`1 productInfo) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 101
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---

2018-09-12 09:45:04.710 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:45:04.711 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-12 09:45:14.715 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:45:14.715 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-12 09:45:24.719 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:45:24.722 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-12 09:45:34.733 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:45:34.737 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-12 09:45:44.750 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:45:44.751 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-12 09:45:54.755 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:45:54.756 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-12 09:45:56.157 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
2018-09-12 09:46:04.760 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:46:04.761 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-12 09:46:14.762 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-12 09:46:14.763 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
^C
root@ddau3:~# ls -halt /var/run/iotedge/
total 0
drwxr-xr-x  2 root root  80 Sep 12 09:33 .
srw-rw-rw-  1 root root   0 Sep 12 09:33 workload.sock
srw-rw----  1 root root   0 Sep 12 09:33 mgmt.sock
drwxr-xr-x 13 root root 600 Aug 30 11:45 ..
root@ddau3:~#
```

At the moment, about 2018-09-12 09:47 (Z), I also have problems to add modules, from the portal, both to the device and other devices. I don't know whether above errors are related to that fact.

/Henrik

**Comment by HenrikBach1** [comment]
Ok. Not what I'm aware of. Usually other devices on the same network has been able to connect to the IoT Hub. But, of course, something can have happened overnight. I'll try to investigate.

**Comment by HenrikBach1** [comment]
I have a Rpi on the same network as above device without any firewall issues. So, it must be a device specific issue.

Looking at the device internal firewall reveals nothing:

```bash
2018-09-13 06:30:20.891 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
2018-09-13 06:30:30.896 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-09-13 06:30:30.897 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
^C
root@ddau3:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy DROP)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (0 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION (0 references)
target     prot opt source               destination

Chain DOCKER-USER (0 references)
target     prot opt source               destination
root@ddau3:~#
```

**Comment by HenrikBach1** [comment]
Please look at above item.

**Comment by HenrikBach1** [comment]
I'll try the solution given in #9, before you should reply.
