### ISSUE TITLE
Issue behind corporate firewall (zscaler)

### ISSUE THREAD

**Issue by bdewaele** [Azure/iotedge#238]
## Current Behavior
Our basic set-up works fine (via 4G).
Once we're behind our corporate proxy (zscaler), the issue arises.
We added zscaler certificates, whitelisted ip and removed ssl inspection but we're still facing the issue.  Once we connect again on 4G, everything works smoothly.

We see almost the exactly same behavior when we connect via Windows 10 enterprise ltsb with docker and iotedge. Everything works fine there but when we need to connect, it fails with timeout.
Via W10 we did the direct connection test without iotedge and this works fine.  We can connect and run a simulator device.

We already did a lot of tests but it only seems to happen when we start to connect the iotedge behind our Zscaler.

Thanks

## Steps to Reproduce

N/A

## Context (Environment)
Company firewall / Zscaler

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64

### Container Operating System
Linux containers

#### Edge Hub
1.0.0.14487025 

## Logs

[2018-08-13 14:07:26 : Starting Edge Hub
[08/13/2018 02:07:26.345 PM] Edge Hub Main()
2018-08-13 14:07:28.052 +00:00 [INF] - Starting Edge Hub
2018-08-13 14:07:28.069 +00:00 [INF] - Version - 1.0.0.14487025 (52ef77db24126bf473265fc09c53d35290a2dd6b)
2018-08-13 14:07:28.070 +00:00 [INF] - Installing intermediate certificates.
2018-08-13 14:07:28.189 +00:00 [INF] - Attempting to connect to IoT Hub for client edge-xxx/$edgeHub via AMQP...
2018-08-13 14:07:28.262 +00:00 [INF] - Connected to IoT Hub for client edge-xxx/$edgeHub via AMQP, with client operation timeout 60000.
2018-08-13 14:07:28.271 +00:00 [INF] - Created cloud connection for client edge-xxx/$edgeHub
2018-08-13 14:07:28.273 +00:00 [INF] - New cloud connection created for device edge-xxx/$edgeHub
2018-08-13 14:07:28.281 +00:00 [INF] - Initializing configuration
2018-08-13 14:07:29.939 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-08-13 14:07:29.969 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-08-13 14:07:29.969 +00:00 [INF] - Created new message store
2018-08-13 14:07:30.045 +00:00 [INF] - New device connection for device edge-xxx/$edgeHub
2018-08-13 14:08:30.083 +00:00 [WRN] - Error adding subscription DesiredPropertyUpdates for client edge-xxx/$edgeHub.
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub.ProcessSubscription(ICloudProxy cloudProxy, DeviceSubscription deviceSubscription, Boolean addSubscription) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs:line 209
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub.AddSubscription(String id, DeviceSubscription deviceSubscription) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs:line 166
2018-08-13 14:08:30.294 +00:00 [WRN] - Failed to update reported  properties for edge-como/$edgeHub with error Object reference not set to an instance of an object.

**Comment by damonbarry** [comment]
Do you get this _exact same_ error every time you try to run Edge Hub behind the corporate firewall? Edge Hub successfully makes a new AMQP connection to IoT Hub, but then it fails to create one of the links (the link that receives updates to the twin's desired properties). If this is a firewall issue, I would expect the initial AMQP connection to timeout (or be rejected by the firewall).

Also you're using version 1.0.0. We recently released 1.0.1. What happens if you upgrade?

**Comment by bdewaele** [comment]
Hello Barry,

we got it working with version 1.0.1.  It didn't work in the beginning but after adding Environmental Variable : UpstreamProtocol AMQPWS, we got it working.  
Now we're stuk on the OPC Publisher but I posted a message on their github

![image](https://user-images.githubusercontent.com/42928691/45424133-d8e3f300-b695-11e8-8c85-6f5a1412279f.png)

**Comment by damonbarry** [comment]
Good to hear.

Yes Edge Hub will not automatically fall back to web sockets so it needs to be specified, as you did here.

Because AMQP over WebSockets works, that tells me that your corporate network has a firewall that blocks AMQP traffic, but it doesn't use a proxy (we'll support proxies soon in IoT Edge, but the currently released bits do not).

Closing...
