### ISSUE TITLE
Java module refuses to connect

### ISSUE THREAD

**Issue by kgalic** [Azure/iotedge#2397]
I have followed the tutorial for creating IoT Edge Java module, but it does not work always. 
If I run it in the DEBUG mode, I get the following error:

`java module java.io.IOException: Could not open the connection
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
AbstractPlainSocketImpl.java:350
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
AbstractPlainSocketImpl.java:206
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
AbstractPlainSocketImpl.java:188
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
PlainSocketImpl.java:172
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
SocksSocketImpl.java:392
	at java.net.Socket.connect(Socket.java:607)
Socket.java:607
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
SSLSocketImpl.java:666
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)`

If I run it in the simulator, sometimes it works sometimes it doesn't. 

I am using a 1.19.0 version of Java SDK.

**Comment by darobs** [comment]
This project is for the product release of the Azure/iotedge project. Development and bug fixing happens in the repo of the open-source [Azure/iotedge](https://github.com/Azure/iotedge) project. Transferring the issue there.

**Comment by kkdawkins** [comment]
Hi @kgalic  - Are you still seeing this issue? If so, can you please follow our issue reporting template (specificaly the instructions about gathering logs/running iotedge check/etc.). 

Thanks!

**Comment by kkdawkins** [comment]
Closed - no activity
