### ISSUE TITLE
CONNECT failed: RefusedNotAuthorized started happening with NO changes to device or cloud

### ISSUE THREAD

**Issue by scottjreece** [Azure/iotedge#24]
## Expected Behavior
Once working, a module should continue working if no changes are made to device or cloud configuration 

## Current Behavior
Device started getting "CONNECT failed: RefusedNotAuthorized" error and will not connect 

## Steps to Reproduce

1. Install IOT Edge module on Raspberry Pi
2. Wait for a couple weeks or so, YMMV
3. Be unlucky?

### Architecture
arm32 on Raspberry Pi Model 3 B+

### Container Operating System
Raspbian Stretch 9.4

#### iotedged

iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker

Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Wed Jun 27 00:53:52 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Tue Jun 26 23:27:27 2018
  OS/Arch:      linux/arm
  Experimental: false

## Logs

Actual error log:
Unhandled Exception: System.AggregateException: One or more errors occurred. (CONNECT failed: RefusedNotAuthorized) ---> Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at SolarEdgeModule.Logic.CloudConnection.Init() in /app/Logic/CloudConnection.cs:line 49
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SolarEdgeModule.Logic.MainModule.Run() in /app/Logic/MainModule.cs:line 31
   at SolarEdgeModule.Program.Main(String[] args) in /app/Program.cs:line 20

IoT Edge Security Manager logs:
Jul 16 16:00:03 solaredge iotedged[410]: 2018-07-16T16:00:03Z [INFO] - [work] - - - [2018-07-16 16:00:03.625322724 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:08 solaredge iotedged[410]: 2018-07-16T16:00:08Z [INFO] - [mgmt] - - - [2018-07-16 16:00:08.714453834 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:08 solaredge iotedged[410]: 2018-07-16T16:00:08Z [INFO] - [work] - - - [2018-07-16 16:00:08.721569310 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:13 solaredge iotedged[410]: 2018-07-16T16:00:13Z [INFO] - [work] - - - [2018-07-16 16:00:13.795495491 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:13 solaredge iotedged[410]: 2018-07-16T16:00:13Z [INFO] - [mgmt] - - - [2018-07-16 16:00:13.803099609 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:17 solaredge iotedged[410]: 2018-07-16T16:00:17Z [INFO] - Checking edge runtime status
Jul 16 16:00:17 solaredge iotedged[410]: 2018-07-16T16:00:17Z [INFO] - Edge runtime is running.
Jul 16 16:00:18 solaredge iotedged[410]: 2018-07-16T16:00:18Z [INFO] - [work] - - - [2018-07-16 16:00:18.874258644 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:18 solaredge iotedged[410]: 2018-07-16T16:00:18Z [INFO] - [mgmt] - - - [2018-07-16 16:00:18.877130449 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:23 solaredge iotedged[410]: 2018-07-16T16:00:23Z [INFO] - [mgmt] - - - [2018-07-16 16:00:23.943789848 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:23 solaredge iotedged[410]: 2018-07-16T16:00:23Z [INFO] - [work] - - - [2018-07-16 16:00:23.946947276 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:29 solaredge iotedged[410]: 2018-07-16T16:00:29Z [INFO] - [work] - - - [2018-07-16 16:00:29.022481431 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:29 solaredge iotedged[410]: 2018-07-16T16:00:29Z [INFO] - [mgmt] - - - [2018-07-16 16:00:29.024920843 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:34 solaredge iotedged[410]: 2018-07-16T16:00:34Z [INFO] - [work] - - - [2018-07-16 16:00:34.095728121 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:34 solaredge iotedged[410]: 2018-07-16T16:00:34Z [INFO] - [mgmt] - - - [2018-07-16 16:00:34.098554301 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:39 solaredge iotedged[410]: 2018-07-16T16:00:39Z [INFO] - [mgmt] - - - [2018-07-16 16:00:39.166353022 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:39 solaredge iotedged[410]: 2018-07-16T16:00:39Z [INFO] - [work] - - - [2018-07-16 16:00:39.174571096 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:44 solaredge iotedged[410]: 2018-07-16T16:00:44Z [INFO] - [mgmt] - - - [2018-07-16 16:00:44.237868248 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:44 solaredge iotedged[410]: 2018-07-16T16:00:44Z [INFO] - [work] - - - [2018-07-16 16:00:44.245692782 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)
Jul 16 16:00:49 solaredge iotedged[410]: 2018-07-16T16:00:49Z [INFO] - [mgmt] - - - [2018-07-16 16:00:49.313041538 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 1497 "-" "-" pid(1283)
Jul 16 16:00:49 solaredge iotedged[410]: 2018-07-16T16:00:49Z [INFO] - [work] - - - [2018-07-16 16:00:49.317624791 UTC] "POST /modules/%24edgeAgent/genid/636665325156825356/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 1417 "-" "-" pid(1283)

## Additional Information
This started happening while I was on vacation without internet, so I am sure I didn't change anything
I am using the OptimizePerformance=false environment variable

**Comment by varunpuranik** [comment]
Hi @scottjreece,

Thanks for reporting the issue. 
It is not clear to me why you started getting that error. Can you provide us the EdgeHub logs? That might help us figure out what the issue might be. 
$>iotedge logs edgeHub

But my guess is it seems like a random error. Did restarting the module fix it? Or do you have a consistent repro?

**Comment by scottjreece** [comment]
Here are the logs, and this is a persistent issue. Rebooting does not solve
it.

[2018-07-16 21:20:29 +00:00]: Starting Edge Hub
[07/16/2018 09:20:36.820 PM] Edge Hub Main()
2018-07-16 21:20:43.890 +00:00 [INF] - Starting Edge Hub
2018-07-16 21:20:43.955 +00:00 [INF] - Version - 1.0.0.14487025
(52ef77db24126bf473265fc09c53d35290a2dd6b)
2018-07-16 21:20:43.957 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-07-16 21:20:43.957 +00:00 [INF] - Installing intermediate certificates.
2018-07-16 21:20:44.408 +00:00 [INF] - Attempting to connect to IoT Hub for
client CluffHomeA/$edgeHub via AMQP...
2018-07-16 21:20:44.795 +00:00 [INF] - Connected to IoT Hub for client
CluffHomeA/$edgeHub via AMQP, with client operation timeout 60000.
2018-07-16 21:20:44.830 +00:00 [INF] - Created cloud connection for client
CluffHomeA/$edgeHub
2018-07-16 21:20:44.836 +00:00 [INF] - New cloud connection created for
device CluffHomeA/$edgeHub
2018-07-16 21:20:44.868 +00:00 [INF] - Initializing configuration
2018-07-16 21:20:46.658 +00:00 [INF] - Created persistent store at
/tmp/edgeHub
2018-07-16 21:20:46.844 +00:00 [INF] - Created new message store
2018-07-16 21:20:46.858 +00:00 [INF] - Started task to cleanup processed
and stale messages
2018-07-16 21:20:47.137 +00:00 [INF] - New device connection for device
CluffHomeA/$edgeHub
2018-07-16 21:20:51.687 +00:00 [INF] - Entering connected state
2018-07-16 21:20:54.384 +00:00 [INF] - Obtained edge hub config from module
twin
2018-07-16 21:20:54.997 +00:00 [INF] - Set the following 1 route(s) in edge
hub
2018-07-16 21:20:55.002 +00:00 [INF] - SolarEdgeModuleToIoTHub: FROM
/messages/modules/solarmodulev3/outputs/output1 INTO $upstream
2018-07-16 21:20:55.008 +00:00 [INF] - Updated message store TTL to 604800
seconds
2018-07-16 21:20:55.009 +00:00 [INF] - Updated the edge hub store and
forward configuration
2018-07-16 21:20:55.012 +00:00 [INF] - Initialized edge hub configuration
2018-07-16 21:20:55.420 +00:00 [INF] - Starting protocol heads - (HTTP,
MQTT, AMQP)
2018-07-16 21:20:55.434 +00:00 [INF] - Starting HTTP head
2018-07-16 21:20:55.987 +00:00 [INF] - User profile is available. Using
'"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys
will not be encrypted at rest.
2018-07-16 21:20:56.125 +00:00 [INF] - Creating key
{aabb6e6f-983d-4f35-b36e-effbfd6541f3} with creation date 2018-07-16
21:20:56Z, activation date 2018-07-16 21:20:56Z, and expiration date
2018-10-14 21:20:56Z.
2018-07-16 21:20:56.240 +00:00 [WRN] - No XML encryptor configured. Key
{aabb6e6f-983d-4f35-b36e-effbfd6541f3} may be persisted to storage in
unencrypted form.
2018-07-16 21:20:56.286 +00:00 [INF] - Writing data to file
'"/home/edgehubuser/.aspnet/DataProtection-Keys/key-aabb6e6f-983d-4f35-b36e-effbfd6541f3.xml"'.
2018-07-16 21:20:58.025 +00:00 [WRN] - Overriding address(es) '"http://+:80"'.
Binding to endpoints defined in "UseKestrel()" instead.
2018-07-16 21:20:58.145 +00:00 [INF] - Started HTTP head
2018-07-16 21:20:58.175 +00:00 [INF] - Starting MQTT head
2018-07-16 21:20:59.029 +00:00 [INF] - Initializing TLS endpoint on port
8883 for MQTT head.
2018-07-16 21:20:59.681 +00:00 [INF] - Starting AMQP head
2018-07-16 21:20:59.692 +00:00 [INF] - Started MQTT head
2018-07-16 21:21:00.390 +00:00 [INF] - Started AMQP head
2018-07-16 21:50:46.912 +00:00 [INF] - Started task to cleanup processed
and stale messages for endpoint iothub
2018-07-16 21:50:46.987 +00:00 [INF] - Cleaned up 0 messages from queue for
endpoint iothub and 0 messages from message store.
2018-07-16 22:21:16.989 +00:00 [INF] - Started task to cleanup processed
and stale messages for endpoint iothub
2018-07-16 22:21:16.990 +00:00 [INF] - Cleaned up 0 messages from queue for
endpoint iothub and 0 messages from message store.

**Comment by scottjreece** [comment]
Here is some more information about the timeline: 
1. Everything was up and running (after the GA) for several days
2. At some point the device started logging timeouts when my code tried to send collected data via the ModuleClient
3. The logs eventually stopped, and as far as I can tell the device was completely frozen. I couldn't even SSH into it until it was power cycled. During this time no messages were flowing between the device and the hub, even system messages as far as I can tell.
4. After power cycling the device, the IoT Edge system appears to be connected to the hub and sending system messages (not messages from my module)
5. My module (which worked before all of this) is failing on startup when it calls ModuleClient.OpenAsync() with the RefusedNotAuthorized error.

The only 3 modules running on this device are the 2 system modules and my module, which collects solar data every minute and sends it to the hub in a JSON message if there is a change, which usually happens every 5 minutes.

Thanks for your help!

**Comment by scottjreece** [comment]
After setting RuntimeLogLevel: debug in config.yaml and restarting, everything started working again.

**Comment by varunpuranik** [comment]
Looks like the EdgeHub got into a bad state for some reason. Unfortunately, the above EdgeHub logs are not complete, and don't give me any details why the connection from your module was being rejected. 
Now that you have enabled debug logs, we will get more (and hopefully sufficient) information to diagnose the issue. If and when the issue repros, can you copy the entire EdgeHub log and share it (it might be quite big, so you might have to upload it to some sharable storage).

A few questions -
- Does the edge device have intermittent internet connection?
- When you power cycled the device, did you delete any of the containers, or just restarted the device?
- Is your module using MQTT or AMQP for connecting to the EdgeHub? If it is using MQTT, can you try switching over to AMQP? We have found it to be more stable over longer durations.

**Comment by keeper-117** [comment]
Hi, I had the same issue, I wrote a post:
[https://wordpress.com/post/jkeeper.wordpress.com/302](https://wordpress.com/post/jkeeper.wordpress.com/302)
The problem was Raspberry Time @scottjreece .
