### ISSUE TITLE
edgeHub failed to start in RHEL.

### ISSUE THREAD

**Issue by pbiswas-kol** [Azure/iotedge#253]
## Expected Behavior
edgeHub should run stable for long time

## Current Behavior
edgeHub failed  Failed (139). back off

## Steps to Reproduce

1. Install moby-engine rpm from https://github.com/Azure/azure-iotedge/releases/tag/1.0.1
2. Install moby-cli rpm from https://github.com/Azure/azure-iotedge/releases/tag/1.0.1
3. Install iotedge runtime and it's dependency rpm from https://github.com/Azure/azure-iotedge/releases/tag/1.0.1
4. Configure (Manual) config.yml
5.Set tempSensor module in iot edge device
6. restart iotrdge

### Device (Host) Operating System
RHEL

### Architecture
amd64

### Container Operating System
Linux container

### Runtime Versions
1.0.1

#### iotedged
iot edge 1.0.1

#### Edge Agent
 mcr.microsoft.com/azureiotedge-agent:1.0.1

#### Edge Hub
 mcr.microsoft.com/azureiotedge-hub:1.0.1

#### Docker
Docker version 18.09.0-dev, build 021bf39d

## Logs
edgeHub Log

[2018-09-06 15:09:32 : Starting Edge Hub
[09/06/2018 03:09:32.715 PM] Edge Hub Main()
FailFast:
Exception thrown from SocketAsyncEngine event loop: System.TypeInitializationException: The type initializer for 'OperationQueue`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Threading.ThreadPool, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Access is denied.

   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.HandleEvent(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
   at System.Net.Sockets.SocketAsyncEngine+<>c.<.ctor>b__24_0(System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)

Exception details:
System.TypeInitializationException: The type initializer for 'OperationQueue`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Threading.ThreadPool, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Access is denied.

   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.HandleEvent(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()

## Additional Information
NAME             STATUS           DESCRIPTION               CONFIG
edgeHub          failed           Failed (139) 4 hours ago  mcr.microsoft.com/azureiotedge-hub:1.0.1
--other modules --
edgeAgent        running          Up 5 hours                mcr.microsoft.com/azureiotedge-agent:1.0.1

**Comment by pbiswas-kol** [comment]
After Upgrade RHEL 7.4 to RHEL 7.5 . It's working.
