### ISSUE TITLE
EdgeAgent run into fail status and endless loop

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#2565]
## Expected Behavior
EdgeAgent can start normally

## Current Behavior
EdgeAgent run into fail status and endless loop

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. All module (edgeAgent, edgeHub and my custom module) running well before.
2. I lock edgeAgent and edgeHub version as 1.0.8.3 on Azure IoT Hub
3. EdgeAgent get desired properties, and fail on start
4.

## Context (Environment)
ARM32, Debian 9

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Debian 9
* Architecture [e.g. amd64, arm32, arm64]: ARM32
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: iotedge 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.8.3
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.8.3
* Docker/Moby [run `docker version`]: 
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 23:28:44 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Fri Apr 19 07:14:38 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

-- Reboot --
Feb 21 14:22:00 Moxa systemd[1]: Started Azure IoT Edge daemon.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Using config file: /etc/iotedge/config.yaml
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Starting Azure IoT Edge Security Daemon
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Using runtime network id azure-iot-edge
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Initializing the module runtime...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Initializing module runtime...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Successfully initialized module runtime
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Finished initializing the module runtime.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Configuring certificates...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Configuring the Device CA certificate using "/var/thingspro/apps/aie/data/setting/default-certs/iotEdge.crt".
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Configuring the Device private key using "/var/thingspro/apps/aie/data/setting/default-certs/iotEdge.key".
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Configuring the trusted CA certificates using "/var/thingspro/apps/aie/data/setting/default-certs/RootCA.crt".
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Finished configuring certificates.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Initializing hsm...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Finished initializing hsm.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Detecting if configuration file has changed...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - No change to configuration file detected.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Obtaining workload CA succeeded.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Provisioning edge device...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Manually provisioning device "TAIJB1072737" in hub "iothub-ul4ry.azure-devices.net"
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Finished provisioning edge device.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Starting management API...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Starting workload API...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Starting watchdog with 60 second frequency...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Listening on fd://iotedge.mgmt.socket/ with 1 thread for management API.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Listening on fd://iotedge.socket/ with 1 thread for workload API.
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Checking edge runtime status
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Edge runtime status is failed, starting module now...
Feb 21 14:22:00 Moxa iotedged[8295]: 2020-02-21T06:22:00Z [INFO] - Starting module edgeAgent...
Feb 21 14:22:09 Moxa iotedged[8295]: 2020-02-21T06:22:09Z [INFO] - Successfully started module edgeAgent
Feb 21 14:23:00 Moxa iotedged[8295]: 2020-02-21T06:23:00Z [INFO] - Checking edge runtime status
Feb 21 14:23:00 Moxa iotedged[8295]: 2020-02-21T06:23:00Z [INFO] - Edge runtime status is failed, starting module now...
Feb 21 14:23:00 Moxa iotedged[8295]: 2020-02-21T06:23:00Z [INFO] - Starting module edgeAgent...
Feb 21 14:23:03 Moxa iotedged[8295]: 2020-02-21T06:23:03Z [INFO] - Successfully started module edgeAgent
Feb 21 14:23:14 Moxa iotedged[8295]: 2020-02-21T06:23:14Z [INFO] - [mgmt] - - - [2020-02-21 06:23:14.407610320 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 1084 "-" "iotedge/0.1.0" pid(10460)
Feb 21 14:23:40 Moxa iotedged[8295]: 2020-02-21T06:23:40Z [INFO] - [mgmt] - - - [2020-02-21 06:23:40.758106160 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 1082 "-" "iotedge/0.1.0" pid(11154)
Feb 21 14:24:00 Moxa iotedged[8295]: 2020-02-21T06:24:00Z [INFO] - Checking edge runtime status
Feb 21 14:24:00 Moxa iotedged[8295]: 2020-02-21T06:24:00Z [INFO] - Edge runtime status is failed, starting module now...
Feb 21 14:24:00 Moxa iotedged[8295]: 2020-02-21T06:24:00Z [INFO] - Starting module edgeAgent...
Feb 21 14:24:03 Moxa iotedged[8295]: 2020-02-21T06:24:03Z [INFO] - Successfully started module edgeAgent
Feb 21 14:25:00 Moxa iotedged[8295]: 2020-02-21T06:25:00Z [INFO] - Checking edge runtime status
Feb 21 14:25:00 Moxa iotedged[8295]: 2020-02-21T06:25:00Z [INFO] - Edge runtime status is failed, starting module now...
Feb 21 14:25:00 Moxa iotedged[8295]: 2020-02-21T06:25:00Z [INFO] - Starting module edgeAgent...
Feb 21 14:25:03 Moxa iotedged[8295]: 2020-02-21T06:25:03Z [INFO] - Successfully started module edgeAgent
Feb 21 14:26:00 Moxa iotedged[8295]: 2020-02-21T06:26:00Z [INFO] - Checking edge runtime status
Feb 21 14:26:00 Moxa iotedged[8295]: 2020-02-21T06:26:00Z [INFO] - Edge runtime status is failed, starting module now...
Feb 21 14:26:00 Moxa iotedged[8295]: 2020-02-21T06:26:00Z [INFO] - Starting module edgeAgent...
Feb 21 14:26:04 Moxa iotedged[8295]: 2020-02-21T06:26:04Z [INFO] - Successfully started module edgeAgent


```
</details>

<details>
<summary>edge-agent logs</summary>

```

-- Reboot --
Feb 21 14:22:08 Moxa e928be04a113[733]: 2020-02-21 06:22:08 +00:00 Starting Edge Agent
Feb 21 14:22:11 Moxa e928be04a113[733]: 2020-02-21 06:22:11.374 +00:00 Edge Agent Main()
Feb 21 14:22:15 Moxa e928be04a113[733]: <6> 2020-02-21 06:22:15.406 +00:00 [INF] - Initializing Edge Agent.
Feb 21 14:22:19 Moxa e928be04a113[733]: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:22:19 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57
Feb 21 14:22:19 Moxa e928be04a113[733]:    --- End of inner exception stack trace ---
Feb 21 14:22:19 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Feb 21 14:22:19 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.get_Result()
Feb 21 14:22:19 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.Main() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 33
Feb 21 14:22:19 Moxa e928be04a113[733]: ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:22:19 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57<---
Feb 21 14:22:19 Moxa e928be04a113[733]: 
Feb 21 14:23:03 Moxa e928be04a113[733]: 2020-02-21 06:23:03 +00:00 Starting Edge Agent
Feb 21 14:23:04 Moxa e928be04a113[733]: 2020-02-21 06:23:04.682 +00:00 Edge Agent Main()
Feb 21 14:23:10 Moxa e928be04a113[733]: <6> 2020-02-21 06:23:09.573 +00:00 [INF] - Initializing Edge Agent.
Feb 21 14:23:15 Moxa e928be04a113[733]: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:23:15 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57
Feb 21 14:23:15 Moxa e928be04a113[733]:    --- End of inner exception stack trace ---
Feb 21 14:23:15 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Feb 21 14:23:15 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.get_Result()
Feb 21 14:23:15 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.Main() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 33
Feb 21 14:23:15 Moxa e928be04a113[733]: ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:23:15 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57<---
Feb 21 14:23:15 Moxa e928be04a113[733]: 
Feb 21 14:24:03 Moxa e928be04a113[733]: 2020-02-21 06:24:03 +00:00 Starting Edge Agent
Feb 21 14:24:04 Moxa e928be04a113[733]: 2020-02-21 06:24:04.376 +00:00 Edge Agent Main()
Feb 21 14:24:08 Moxa e928be04a113[733]: <6> 2020-02-21 06:24:08.268 +00:00 [INF] - Initializing Edge Agent.
Feb 21 14:24:13 Moxa e928be04a113[733]: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:24:13 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57
Feb 21 14:24:13 Moxa e928be04a113[733]:    --- End of inner exception stack trace ---
Feb 21 14:24:13 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Feb 21 14:24:13 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.get_Result()
Feb 21 14:24:13 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.Main() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 33
Feb 21 14:24:13 Moxa e928be04a113[733]: ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:24:13 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57<---
Feb 21 14:24:13 Moxa e928be04a113[733]: 
Feb 21 14:25:03 Moxa e928be04a113[733]: 2020-02-21 06:25:03 +00:00 Starting Edge Agent
Feb 21 14:25:04 Moxa e928be04a113[733]: 2020-02-21 06:25:04.367 +00:00 Edge Agent Main()
Feb 21 14:25:07 Moxa e928be04a113[733]: <6> 2020-02-21 06:25:07.643 +00:00 [INF] - Initializing Edge Agent.
Feb 21 14:25:11 Moxa e928be04a113[733]: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:25:11 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57
Feb 21 14:25:11 Moxa e928be04a113[733]:    --- End of inner exception stack trace ---
Feb 21 14:25:11 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Feb 21 14:25:11 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.get_Result()
Feb 21 14:25:11 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.Main() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 33
Feb 21 14:25:11 Moxa e928be04a113[733]: ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:25:11 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57<---
Feb 21 14:25:11 Moxa e928be04a113[733]: 
Feb 21 14:26:04 Moxa e928be04a113[733]: 2020-02-21 06:26:04 +00:00 Starting Edge Agent
Feb 21 14:26:06 Moxa e928be04a113[733]: 2020-02-21 06:26:06.284 +00:00 Edge Agent Main()
Feb 21 14:26:10 Moxa e928be04a113[733]: <6> 2020-02-21 06:26:10.018 +00:00 [INF] - Initializing Edge Agent.
Feb 21 14:26:12 Moxa e928be04a113[733]: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:26:12 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57
Feb 21 14:26:12 Moxa e928be04a113[733]:    --- End of inner exception stack trace ---
Feb 21 14:26:12 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Feb 21 14:26:12 Moxa e928be04a113[733]:    at System.Threading.Tasks.Task`1.get_Result()
Feb 21 14:26:12 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.Main() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 33
Feb 21 14:26:12 Moxa e928be04a113[733]: ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
Feb 21 14:26:12 Moxa e928be04a113[733]:    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 57<---
Feb 21 14:26:12 Moxa e928be04a113[733]: 


```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by vipeller** [comment]
@KevinKao809 do you see any "versionInfo.json" file in your agent deployment?

**Comment by KevinKao809** [comment]
Hi vipeller, where I can check it?

**Comment by vipeller** [comment]
@KevinKao809 Hi, sorry for the late answer.
So the line you have the exception in can happen when something wrong with your versionInfo.json file. What I'd like you to do is to open an interactive shell in your agent container and list the files to see if the versionInfo.json in ther, then 'cat' the content.

you need to use 'docker exec' on your agent container to start a shell, and the execute ls. like
docker exec -ti edgeAgent sh

then when you have the prompt, just type ls ver*
if you see the file, then type cat versionInfo.json

let me know the result.

**Comment by KevinKao809** [comment]
![image](https://user-images.githubusercontent.com/3096796/75208425-9002fa00-57b6-11ea-9a22-091288135306.png)
@vipeller file size is 0.

**Comment by vipeller** [comment]
@KevinKao809 ok, so the version you use expects some values. (it is fixed in the following versions) I am not sure how the versionInfo.json content disappeared, but it should look like something like this:

{
  "version": "1.0.8.3",
  "build": "123",
  "commit": "123"
}

A quick workaround would be to create a file like this, and copy it into the container. Here is an example how to copy into container:

https://til.codes/copy-file-from-host-machine-to-docker-container/

also, please make sure that you copy it into the right directory in the container. Sorry for the hacky way to fix it. Let me know how it went or if I can assist with anything.

**Comment by KevinKao809** [comment]
@vipeller Thanks your response. I close this issue from here.
