### ISSUE TITLE
Iotedge Azure Stream Analytics error

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#2675]
My iotedge stopped working the way it should, and the logs of ASA module is :

2020-03-10 17:52:04.165 +00:00 [INF] - Module client initializing ... 
2020-03-10 17:52:04.249 +00:00 [INF] - Opened module client connection.
2020-03-10 17:52:04.318 +00:00 [INF] - ASA getting path: https://storagerailes.blob.core.windows.net/railescontainer/ASAEdgeJobs/0f7b6cd6-951e-47c0-928b-ebd04e5ae06a/9a2a8864-4c4d-433d-aba9-7753aa8ab5dc/ASAEdgeJobDefinition.zip?sv=2018-03-28&sr=b&sig=F1Ll5ZJRben2iw6c5a8%2F7%2BpxAAHxbYt3QHe40z90bEk%3D&st=2020-03-10T16%3A54%3A19Z&se=2023-03-10T17%3A04%3A19Z&sp=r
2020-03-10 17:52:04.320 +00:00 [INF] - Download ASA Job Package from : https://storagerailes.blob.core.windows.net/railescontainer/ASAEdgeJobs/0f7b6cd6-951e-47c0-928b-ebd04e5ae06a/9a2a8864-4c4d-433d-aba9-7753aa8ab5dc/ASAEdgeJobDefinition.zip?sv=2018-03-28&sr=b&sig=F1Ll5ZJRben2iw6c5a8%2F7%2BpxAAHxbYt3QHe40z90bEk%3D&st=2020-03-10T16%3A54%3A19Z&se=2023-03-10T17%3A04%3A19Z&sp=r.
2020-03-10 17:52:06.233 +00:00 [INF] - Unzip /tmp/082f62d8-16a9-42fe-8992-3340085c6142/ASAEdgeJobDefinition.zip ...
2020-03-10 17:52:06.424 +00:00 [INF] - Initalizing ASA Engine ...
2020-03-10 17:52:06.427 +00:00 [INF] - The directory for the executing assembly is /app.
2020-03-10 17:52:06.495 +00:00 [INF] - 
=============================Metrics report=============================
 InputEvents                                  :                   0
 ConversionErrors                             :                   0
 EarlyInputEvents                             :                   0
 InputEventBytes                              :                 0 B
 OutputWatermarkDelaySeconds                  :                 N/A
 InputEventsSources                           :                   0
 LateInputEvents                              :                   0
 DeserializationError                         :                   0
 DroppedOrAdjustedEvents                      :                   0
 OutputEvents                                 :                   0
 Errors                                       :                   0
========================================================================

2020-03-10 17:52:16.695 +00:00 [ERR] - Exception: IsFatal: False; System.AggregateException: One or more errors occurred. (One or more errors occurred. (Invalid integer value in the input stream.)) ---> System.AggregateException: One or more errors occurred. (Invalid integer value in the input stream.) ---> System.Runtime.Serialization.SerializationException: Invalid integer value in the input stream.
   at Microsoft.StreamProcessing.Serializer.BinaryDecoder.DecodeInt() in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\Encoders\BinaryDecoder.cs:line 87
   at lambda_method(Closure , BinaryDecoder )
   at Microsoft.StreamProcessing.Serializer.AvroSerializer`1.Deserialize(Stream stream) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\AvroSerializer.cs:line 90
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLQueryParameter.Parse(String serializedParameters) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLQueryParameter.cs:line 51
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLGeneratedQuery.GetQuery(Dictionary`2 inputs, String serializedParameters, ILookupContext lookupContext) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLGeneratedQuery.cs:line 47
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, Stream stream) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseQueryContainer.cs:line 401
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 619
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.<ProcessBatch>b__72_0(Task`1 t) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 286
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.WaitForBatchTaskCompletion(Boolean initializationTask) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 681
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.ProcessBatch(Boolean async) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 267
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.Process(Boolean isInitialization) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 495
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.Process(Boolean isInitialization) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 477
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeInput() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 391
   at Microsoft.Streaming.StreamingNode.ProcessorScheduler.InitializeTopology(CancellationToken cToken) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorScheduler.cs:line 354
   at Microsoft.Streaming.StreamingNode.ProcessorScheduler.ThreadProc() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorScheduler.cs:line 640
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Streaming.StreamingNode.StreamingNode.WaitForExit(CancellationToken cancellationToken) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\StreamingNode.cs:line 665
   at Microsoft.Streaming.StreamingNode.StreamingNode.StartNode(CancellationToken initializationCancellationToken) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\StreamingNode.cs:line 288
   at Microsoft.Streaming.Runtime.Container.Edge.Container.RunNodeAndHandleExceptions(String jobId, CancellationToken token) in M:\FXAGENT-014\_work\8\s\Product\Source\DotNetCore\Container.Edge\Container.cs:line 365
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Invalid integer value in the input stream.) ---> System.Runtime.Serialization.SerializationException: Invalid integer value in the input stream.
   at Microsoft.StreamProcessing.Serializer.BinaryDecoder.DecodeInt() in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\Encoders\BinaryDecoder.cs:line 87
   at lambda_method(Closure , BinaryDecoder )
   at Microsoft.StreamProcessing.Serializer.AvroSerializer`1.Deserialize(Stream stream) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\AvroSerializer.cs:line 90
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLQueryParameter.Parse(String serializedParameters) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLQueryParameter.cs:line 51
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLGeneratedQuery.GetQuery(Dictionary`2 inputs, String serializedParameters, ILookupContext lookupContext) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLGeneratedQuery.cs:line 47
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, Stream stream) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseQueryContainer.cs:line 401
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 619
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.<ProcessBatch>b__72_0(Task`1 t) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 286
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
---> (Inner Exception #0) System.Runtime.Serialization.SerializationException: Invalid integer value in the input stream.
   at Microsoft.StreamProcessing.Serializer.BinaryDecoder.DecodeInt() in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\Encoders\BinaryDecoder.cs:line 87
   at lambda_method(Closure , BinaryDecoder )
   at Microsoft.StreamProcessing.Serializer.AvroSerializer`1.Deserialize(Stream stream) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\AvroSerializer.cs:line 90
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLQueryParameter.Parse(String serializedParameters) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLQueryParameter.cs:line 51
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLGeneratedQuery.GetQuery(Dictionary`2 inputs, String serializedParameters, ILookupContext lookupContext) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLGeneratedQuery.cs:line 47
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, Stream stream) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseQueryContainer.cs:line 401
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 619<---
<---
; InnerException: System.AggregateException: One or more errors occurred. (Invalid integer value in the input stream.) ---> System.Runtime.Serialization.SerializationException: Invalid integer value in the input stream.
   at Microsoft.StreamProcessing.Serializer.BinaryDecoder.DecodeInt() in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\Encoders\BinaryDecoder.cs:line 87
   at lambda_method(Closure , BinaryDecoder )
   at Microsoft.StreamProcessing.Serializer.AvroSerializer`1.Deserialize(Stream stream) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\AvroSerializer.cs:line 90
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLQueryParameter.Parse(String serializedParameters) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLQueryParameter.cs:line 51
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLGeneratedQuery.GetQuery(Dictionary`2 inputs, String serializedParameters, ILookupContext lookupContext) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLGeneratedQuery.cs:line 47
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, Stream stream) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseQueryContainer.cs:line 401
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 619
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.<ProcessBatch>b__72_0(Task`1 t) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 286
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
---> (Inner Exception #0) System.Runtime.Serialization.SerializationException: Invalid integer value in the input stream.
   at Microsoft.StreamProcessing.Serializer.BinaryDecoder.DecodeInt() in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\Encoders\BinaryDecoder.cs:line 87
   at lambda_method(Closure , BinaryDecoder )
   at Microsoft.StreamProcessing.Serializer.AvroSerializer`1.Deserialize(Stream stream) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\AvroSerializer.cs:line 90
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLQueryParameter.Parse(String serializedParameters) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLQueryParameter.cs:line 51
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLGeneratedQuery.GetQuery(Dictionary`2 inputs, String serializedParameters, ILookupContext lookupContext) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLGeneratedQuery.cs:line 47
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, Stream stream) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseQueryContainer.cs:line 401
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 619<---

System.AggregateException: One or more errors occurred. (One or more errors occurred. (Invalid integer value in the input stream.)) ---> System.AggregateException: One or more errors occurred. (Invalid integer value in the input stream.) ---> System.Runtime.Serialization.SerializationException: Invalid integer value in the input stream.
   at Microsoft.StreamProcessing.Serializer.BinaryDecoder.DecodeInt() in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\Encoders\BinaryDecoder.cs:line 87
   at lambda_method(Closure , BinaryDecoder )
   at Microsoft.StreamProcessing.Serializer.AvroSerializer`1.Deserialize(Stream stream) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\AvroSerializer.cs:line 90
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLQueryParameter.Parse(String serializedParameters) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLQueryParameter.cs:line 51
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLGeneratedQuery.GetQuery(Dictionary`2 inputs, String serializedParameters, ILookupContext lookupContext) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLGeneratedQuery.cs:line 47
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, Stream stream) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseQueryContainer.cs:line 401
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 619
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.<ProcessBatch>b__72_0(Task`1 t) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 286
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.WaitForBatchTaskCompletion(Boolean initializationTask) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 681
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.ProcessBatch(Boolean async) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 267
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.Process(Boolean isInitialization) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 495
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.Process(Boolean isInitialization) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 477
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeInput() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 391
   at Microsoft.Streaming.StreamingNode.ProcessorScheduler.InitializeTopology(CancellationToken cToken) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorScheduler.cs:line 354
   at Microsoft.Streaming.StreamingNode.ProcessorScheduler.ThreadProc() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorScheduler.cs:line 640
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Streaming.StreamingNode.StreamingNode.WaitForExit(CancellationToken cancellationToken) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\StreamingNode.cs:line 665
   at Microsoft.Streaming.StreamingNode.StreamingNode.StartNode(CancellationToken initializationCancellationToken) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\StreamingNode.cs:line 288
   at Microsoft.Streaming.Runtime.Container.Edge.Container.RunNodeAndHandleExceptions(String jobId, CancellationToken token) in M:\FXAGENT-014\_work\8\s\Product\Source\DotNetCore\Container.Edge\Container.cs:line 365
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Invalid integer value in the input stream.) ---> System.Runtime.Serialization.SerializationException: Invalid integer value in the input stream.
   at Microsoft.StreamProcessing.Serializer.BinaryDecoder.DecodeInt() in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\Encoders\BinaryDecoder.cs:line 87
   at lambda_method(Closure , BinaryDecoder )
   at Microsoft.StreamProcessing.Serializer.AvroSerializer`1.Deserialize(Stream stream) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\AvroSerializer.cs:line 90
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLQueryParameter.Parse(String serializedParameters) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLQueryParameter.cs:line 51
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLGeneratedQuery.GetQuery(Dictionary`2 inputs, String serializedParameters, ILookupContext lookupContext) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLGeneratedQuery.cs:line 47
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, Stream stream) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseQueryContainer.cs:line 401
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 619
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Streaming.StreamingNode.ProcessorsCommon.BaseStreamingProcessor.<ProcessBatch>b__72_0(Task`1 t) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\StreamingNode\ProcessorsCommon\BaseStreamingProcessor.cs:line 286
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
---> (Inner Exception #0) System.Runtime.Serialization.SerializationException: Invalid integer value in the input stream.
   at Microsoft.StreamProcessing.Serializer.BinaryDecoder.DecodeInt() in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\Encoders\BinaryDecoder.cs:line 87
   at lambda_method(Closure , BinaryDecoder )
   at Microsoft.StreamProcessing.Serializer.AvroSerializer`1.Deserialize(Stream stream) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing.Serializer\AvroSerializer.cs:line 90
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLQueryParameter.Parse(String serializedParameters) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLQueryParameter.cs:line 51
   at Microsoft.Streaming.StreamingController.ASAImplementations.SQLGeneratedQuery.GetQuery(Dictionary`2 inputs, String serializedParameters, ILookupContext lookupContext) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ASAEnvironment.Azure\SQLGeneratedQuery.cs:line 47
   at Microsoft.Streaming.Processors.Compute.BaseQueryContainer`4.InstantiateTrillQuery(String serializedParameters, Boolean checkpointsEnabled, EventStreamManager sourceManager, Stream stream) in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseQueryContainer.cs:line 401
   at Microsoft.Streaming.Processors.Compute.BaseEventStreamProcessor.InitializeStreamProcessingInternalAsync() in M:\FXAGENT-014\_work\8\s\Product\Source\Framework\ComputeProcessor\BaseEventStreamProcessor.cs:line 619<---
<---

2020-03-10 17:52:16.700 +00:00 [INF] - Metrics is Cancelled.
2020-03-10 17:52:16.700 +00:00 [INF] - Node Exited.
2020-03-10 17:52:16.700 +00:00 [INF] - Will restart engine in one minute.
2020-03-10 17:52:20.005 +00:00 [INF] - Module reported job status successfully, Job Status : Paused, Is Runtime Error : False

**Comment by richma-ms** [comment]
Hi,

This seems like an issue with the ASA module receiving invalid input from its source modules, and not a problem with the Edge runtime itself.  Please double-check the other modules providing input into the ASA modules and make sure they're working correctly.  If you still have problems, please raise the issue for discussion over at the ASA forums:
https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureStreamAnalytics
