### ISSUE TITLE
HSM Failure - EdgeHub not starting - Device CA Certificate expired - similar to #1719

### ISSUE THREAD

**Issue by mathiash98** [Azure/iotedge#2706]
Jump to bottom for findinds after further research. I realize that this isn't a bug. So I would rather have this as a feature request  where iotedge automatically renew self signed CA.

## Expected Behavior
EdgeHub shall be able to retrieve a new Device CA certificate as far as we have understood.

## Current Behavior
EdgeHub crash when retrieving new Device CA Certificate

Solved it by:
`sudo iotedge restart edgeAgent` and `restart edgeHub` -> Did not help
`sudo systemctl restart iotedge`  -> Fixed the issue

## Steps to Reproduce
Not sure how to reproduce

## Context (Environment)
We run IoTEdge on 12 locations with identical setup:
Installed IoTEdge according to instructions on web
We use manual provisioning where we edit `/etc/iotedge/config.yaml` and set device_connection_string to the appropiate IoTedge in IoTHub

Machine: ARK-1124 or similar
OS: Ubuntu Server 18-04
Several modules dependent on edgeHub for sending messages to cloud.
All edgeDevices is independent in that network (we don't use any leaf devices)
Some vessels have very poor internet connection. But these two installations has quite decent speed.

These 2 setups were configured at 2019-12-17, so 3 months ago.

### Output of `iotedge check`

<details>
<summary>Device CA expired</summary>

```
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
× production readiness: certificates expiry - Error
    Device CA certificate in /var/lib/iotedge/hsm/certs/device_ca_aliasazxVrrdEVxd7kvKvne1pOEyuSHF8EXSowNDhMzl30jI_.cert.pem expired at 2020-03-16 09:34:46 UTC
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedged: 1.0.8 
* Edge Agent: 1.0.9-rc5 
* Edge Hub: 1.0.9-rc5 
* Docker/Moby: 3.0.8 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>sudo journalctl -u iotedge -n 100</summary>

```

Mar 18 09:58:14 ksa4011801 iotedged[1966]: 2020-03-18T09:58:14Z [INFO] - Starting module edgeHub...
Mar 18 09:58:15 ksa4011801 iotedged[1966]: 2020-03-18T09:58:15Z [INFO] - Successfully started module edgeHub
Mar 18 09:58:15 ksa4011801 iotedged[1966]: 2020-03-18T09:58:15Z [INFO] - [mgmt] - - - [2020-03-18 09:58:15.658772159 UTC] "POST /modules/edgeHub/start?api-version=2019-01-30 HTTP/1.1" 204 No Content - "-" "-" auth_id(-)
Mar 18 09:58:15 ksa4011801 iotedged[1966]: 2020-03-18T09:58:15Z [INFO] - [work] - - - [2020-03-18 09:58:15.740787492 UTC] "POST /modules/%24edgeAgent/genid/637121720238574019/encrypt?api-version=2019-01-30 HTTP/1.1" 200 OK 688
Mar 18 09:58:17 ksa4011801 iotedged[1966]: [1B blob data]
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:07Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_evp_certificate:1347) Failure setting certificate validity period
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:07Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_pki_cert_and_key_helper:1525) Could not generate certificate create re
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:07Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert_internal:2633) Could not create PKI
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:07Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert:2709) Could not create certificate a
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:07Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:edge_hsm_client_create_certificate:285) Could not create certificate in t
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:10Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert_and_key_exist_by_alias:1443) Certificate and key file for a
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:10Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:validate_certificate_expiration:806) Certificate has expired
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:10Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:cert_set_expiration:849) Issuer certificate expiration failure. Status 0, verif
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:10Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_evp_certificate:1347) Failure setting certificate validity period
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:10Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_pki_cert_and_key_helper:1525) Could not generate certificate create re
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:10Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert_internal:2633) Could not create PKI
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:10Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert:2709) Could not create certificate a
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:53:10Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:edge_hsm_client_create_certificate:285) Could not create certificate in t
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:16Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert_and_key_exist_by_alias:1443) Certificate and key file for a
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:validate_certificate_expiration:806) Certificate has expired
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:cert_set_expiration:849) Issuer certificate expiration failure. Status 0, verif
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_evp_certificate:1347) Failure setting certificate validity period
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_pki_cert_and_key_helper:1525) Could not generate certificate create re
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert_internal:2633) Could not create PKI
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert:2709) <3>2020-03-18T09:58:17Z [ERR!]
Mar 18 09:58:17 ksa4011801 iotedged[1966]:         caused by: An error occurred creating the certificate
Mar 18 09:58:17 ksa4011801 iotedged[1966]:         caused by: HSM failure
Mar 18 09:58:17 ksa4011801 iotedged[1966]:         caused by: HSM API returned an invalid null response
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [INFO] - [work] - - - [2020-03-18 09:58:17.090917009 UTC] "POST /modules/%24edgeHub/genid/637121720238574019/certificate/server?api-version=2019-01-30 HTTP/1.1" 5
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [ERR!] - Internal server error: Could not get server cert
Mar 18 09:58:17 ksa4011801 iotedged[1966]:         caused by: An error occurred creating the certificate
Mar 18 09:58:17 ksa4011801 iotedged[1966]:         caused by: HSM failure
Mar 18 09:58:17 ksa4011801 iotedged[1966]:         caused by: HSM API returned an invalid null response
Mar 18 09:58:17 ksa4011801 iotedged[1966]: 2020-03-18T09:58:17Z [INFO] - [work] - - - [2020-03-18 09:58:17.437197919 UTC] "POST /modules/%24edgeHub/genid/637121720238574019/certificate/server?api-version=2019-01-30 HTTP/1.1" 5
Mar 18 09:58:20 ksa4011801 iotedged[1966]: 2020-03-18T09:58:20Z [ERR!] - Internal server error: Could not get server cert
Mar 18 09:58:20 ksa4011801 iotedged[1966]:         caused by: An error occurred creating the certificate
Mar 18 09:58:20 ksa4011801 iotedged[1966]:         caused by: HSM failure
Mar 18 09:58:20 ksa4011801 iotedged[1966]:         caused by: HSM API returned an invalid null response
Mar 18 09:58:20 ksa4011801 iotedged[1966]: 2020-03-18T09:58:20Z [INFO] - [work] - - - [2020-03-18 09:58:20.619231437 UTC] "POST /modules/%24edgeHub/genid/637121720238574019/certificate/server?api-version=2019-01-30 HTTP/1.1" 5
Mar 18 09:58:20 ksa4011801 iotedged[1966]: 2020-03-18T09:58:20Z [INFO] - [mgmt] - - - [2020-03-18 09:58:20.768117762 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 6355 "-" "-" auth_id(-)
Mar 18 09:58:26 ksa4011801 iotedged[1966]: 2020-03-18T09:58:26Z [INFO] - [mgmt] - - - [2020-03-18 09:58:26.026461275 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 6355 "-" "-" auth_id(-)
Mar 18 09:58:31 ksa4011801 iotedged[1966]: 2020-03-18T09:58:31Z [INFO] - [mgmt] - - - [2020-03-18 09:58:31.288357298 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 6355 "-" "-" auth_id(-)
Mar 18 09:58:34 ksa4011801 iotedged[1966]: 2020-03-18T09:58:34Z [INFO] - Checking edge runtime status
Mar 18 09:58:34 ksa4011801 iotedged[1966]: 2020-03-18T09:58:34Z [INFO] - Edge runtime is running.

```
</details>

<details>
<summary>Nothing particular</summary>

```


```
</details>

<details>
<summary>edge-hub logs same as in journalctl</summary>

```
2020-03-18 09:41:32  Starting Edge Hub
2020-03-18 09:41:32.375 +00:00 Edge Hub Main()

Unhandled Exception: System.AggregateException: One or more errors occurred. (Error calling CreateServerCertificateAsync: Could not get server cert
        caused by: An error occurred creating the certificate
        caused by: HSM failure
        caused by: HSM API returned an invalid null response) ---> Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadCommunicationException: Error calling CreateServerCertificateAsync: Could not get server cert
        caused by: An error occurred creating the certificate
        caused by: HSM failure
        caused by: HSM API returned an invalid null response
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.HandleException(Exception ex, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 106
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 66
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.CreateServerCertificateAsync(String hostname, DateTime expiration) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 35
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetServerCertificatesFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId, String edgeHubHostname, DateTime expiration) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 255
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration, ILogger logger) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 54
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 51
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 30


```
</details>

## Additional Information
Please Correct us if we have misunderstood how Device Certificates are supposed to behave

## After further research:
I realize that this might be an error on our side after reading #1719, we thought we didn't need certificates when we are using device_connection_string to IoTHub.

According to: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-production-certificates
We need Certificates to communicate between runtime and modules which connect to for example EdgeHub.

But couldn't this operation be automated by iotedge when we have no need for downstream devices? We would end up still using self signed certificates on each edgeDevice, this will require us to setup one extra program on the device which generate new certificates every X days.

**Comment by ggjjj** [comment]
Hi, our current design is to self-sign CA for testing purpose only and it is expires after 90 days. Yes it does require to restart iotedged to generate a new certificate. But in our recent release **1.0.9**, there is a feature where the customer can specify the lifetime of the certificate but its recommended for **development and testing scenarios, not production** only. Link [here ](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates#customize-certificate-lifetime) for the new feature. For best practices on deploying certificates on a production environment check this [link](https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist). Currently we are not planning to add this as a feature request.

**Comment by mathiash98** [comment]
Thank you for your response @ggjjj, we will implement production certificates.
I will consider this issue as solved.
