### ISSUE TITLE
[query] MessageResponse.Abandoned behaviour differences between AMQP and MQTT ModuleClients

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iotedge#2813]
## Expected Behavior
After connecting to edgeHub using MQTT protocol, in ModuleClient::SetInputMessageHandlerAsync[[1](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient.setinputmessagehandlerasync?view=azure-dotnet)] MessageHandler, if I return MessageResponse.Abandoned, the MessageHandler is invoked again as expected.

But if I connect to edgeHub using AMQP protocol, and return MessageResponse.Abandoned from the MessageHandler, then the MessageHandler is **not** invoked again.

I understand, as module developers we should not be relying on MessageResponse.Abandoned. But I want to bring this difference to the attention of runtime developers. Kindly close if this is not of importance.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2020-07-06 06:49:35 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

19 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS: Ubuntu 18.04
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* iotedged [1.0.9]: 
* Edge Agent [azureiotedge-agent:1.0 - b768dff3bd78]: 
* Edge Hub [azureiotedge-hub:1.0 - b4d51359cd25]: 
* Docker/Moby:
```
Client:
 Version:           3.0.10+azure
 API version:       1.40
 Go version:        go1.12.14
 Git commit:        99c5edceb48d64c1aa5d09b8c9c499d431d98bb9
 Built:             Tue Nov  5 00:55:15 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          3.0.10+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.14
  Git commit:       ea84732a77
  Built:            Fri Jan 24 20:08:11 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.11
  GitCommit:        f772c10a585ced6be8f86e8c58c2b998412dd963
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by massand** [comment]
@kiranpradeep - thanks for reporting this! 
Past discussions in #2053 indicate that the MessageResponse.Abandoned is definitely not supported. But, the lack of EdgeHub retries after Abandoned was returned to EdgeHub is concerning.  
Few follow ups would help expedite:
- Could you provide a code snippet that repros this issue for you consistently on 1.0.9? 
- Have you hit issues with module going offline and EdgeHub retries not occurring over AMQP? 
- Does this repro on older versions (< 1.0.9) for you using the same snippet?

**Comment by kiranpradeep** [comment]
1. Code sample below. It is the exact sample we get from command (`dotnet new aziotedgemodule -n abandon`) with minor modifications in functions `Init` and method `PipeMessage`.
2. Neither the module nor edgeHub goes offline at any point of time. The system is always online and module never disconnects from edgeHub. Kindly rephrase, if I did not answer the query correctly.
3. I have not tried this sample with older versions.

```csharp
namespace abandon
{
    using System;
    using System.Runtime.Loader;
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Azure.Devices.Client;


    class Program
    {
        static int counter;

        static void Main(string[] args)
        {
            Init().Wait();

            var cts = new CancellationTokenSource();
            AssemblyLoadContext.Default.Unloading += (ctx) => cts.Cancel();
            Console.CancelKeyPress += (sender, cpe) => cts.Cancel();
            WhenCancelled(cts.Token).Wait();
        }

        public static Task WhenCancelled(CancellationToken cancellationToken)
        {
            var tcs = new TaskCompletionSource<bool>();
            cancellationToken.Register(s => ((TaskCompletionSource<bool>)s).SetResult(true), tcs);
            return tcs.Task;
        }

        static async Task Init()
        {
            var amqpSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
            ITransportSettings[] settings = { amqpSetting };

            ModuleClient ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await ioTHubModuleClient.OpenAsync();
            Console.WriteLine("IoT Hub module client initialized.");

            await ioTHubModuleClient.SetInputMessageHandlerAsync("input1", PipeMessage, ioTHubModuleClient);
        }

        static async Task<MessageResponse> PipeMessage(Message message, object userContext)
        {
            int counterValue = Interlocked.Increment(ref counter);
            byte[] messageBytes = message.GetBytes();
            string messageString = Encoding.UTF8.GetString(messageBytes);
            Console.WriteLine($"Received message: {counterValue}, Body: [{messageString}]");
            return await Task.FromResult(MessageResponse.Abandoned);
        }
    }
}
```

**Comment by massand** [comment]
Thanks for the repro. Even though we don't expect modules to return MessageResponse.Abandoned, I captured logs for both MQTT and AMQP inputs for posterity (behavior captured in 1.0.9):
**MQTT** (always retries after receiving Abandoned <-- this shouldn't be used):
```
<4> 2020-04-14 08:10:47.056 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Did not receive ack for message b912bec0-ff3b-4eec-b789-62521126d7e0 from device/module device/InputTestMqtt
<4> 2020-04-14 08:10:47.056 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint] - Error sending messages to module device/InputTestMqtt
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 427
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint
.cs:line 167
```
**AMQP** (behaves as though MessageResponse.Completed was delivered back to EdgeHub <-- Abandoned still shouldn't be used)
```
<7> 2020-04-14 08:10:51.129 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Abandon for message d6f3a8fa-ba2c-4629-a9e9-df91f35d3016 from device/module device/InputTest
<4> 2020-04-14 08:10:51.130 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint] - Non retryable exception occurred while sending message.
Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubMessageRejectedException: Message not completed by client device/InputTest
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 427
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint
.cs:line 167
<4> 2020-04-14 08:10:51.131 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint] - Error sending messages to module device/InputTest
Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubMessageRejectedException: Message not completed by client device/InputTest
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 427
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint
.cs:line 167
```
In MQTT case, the MessageResponse.Abandoned response makes EdgeHub perform a "message send retry" immediately in MQTT case. 

EdgeHub normally performs "message send retry" after a message send is not acknowledged. The Completed response code is always expected within a reasonable timeframe.

**Comment by kiranpradeep** [comment]
@massand Thanks for the response. If you could confirm with a 'yes' on point 3, it will help in a better understanding.

1. As confirmed earlier in #2053 and further in this issue page, `MessageResponse.Abandoned` must never be used by the module developer.
2. The exists difference in behaviour between MQTT and AMQP for the `MessageResponse.Abandoned` response code. This behaviour difference is considered ok and ideally, module developer should not be impacted by this difference.
3. More importantly, the module developer must always return `MessageResponse.Completed`, irrespective of whatever happens in the message callback.

**Comment by massand** [comment]
@kiranpradeep - Yes, the MQTT handler in the C# SDK literally drops responses for messages tagged with MessageResponse.Abandoned. No good comes out of using that response type and Message.Completed is always expected. 

See C# SDK code here - 
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L344
