### ISSUE TITLE
Edge Hub crashes on start because of permission denied exception

### ISSUE THREAD

**Issue by licensedslacker** [Azure/iotedge#2856]
We have encountered a crash problem with IoT Edge Hub image on our arm32-based device. The edge hub throws permission denied exception on startup. Investigated the image and the location mentioned in the exception description is owned by the root user and the edgehubuser does not have write permission the location. The problem seems to occur only on arm32 platform and amd64 version is working correctly.

## Expected Behavior
IoT Edge Hub starts up normally

## Current Behavior
The container crashed with an exception and goes to backoff state.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Make deployment with edgeAgent and edgeHub
2. Activate the deployment
3. Inspect edgeHub's logs on a device

## Context (Environment)
IoT Edge Security daemon runs in the quick start mode (self-generated keys).

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
‼ config.yaml has correct hostname - Warning
    config.yaml has hostname 6000-series which does not comply with RFC 1035.

    - Hostname must be between 1 and 255 octets inclusive.
    - Each label in the hostname (component separated by ".") must be between 1 and 63 octets inclusive.
    - Each label must start with an ASCII alphabet character (a-z, A-Z), end with an ASCII alphanumeric character (a-z, A-Z, 0-9), and must contain only ASCII alphanumeric characters or hyphens (a-z, A-Z, 0-9, "-").

    Not complying with RFC 1035 may cause errors during the TLS handshake with modules and downstream devices.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
× latest security daemon - Error
    Could not spawn iotedged process
‼ host time is close to real time - Warning
    Time on the device is out of sync with the NTP server. This may cause problems connecting to IoT Hub.
    Please ensure time on device is accurate, for example by installing an NTP daemon.
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2020-07-16 15:00:10 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

14 check(s) succeeded.
8 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.


```
The security daemon launch fails because we a custom launch script for it.
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Custom rootbuild linux
* Architecture [e.g. amd64, arm32, arm64]:  arm32
* Container OS [e.g. Linux containers, Windows containers]:  Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.9.29532150 (tag 1.0)
* Edge Hub [image tag (e.g. 1.0.0)]:  1.0 (could not detect the exact version)
* Docker/Moby [run `docker version`]: ~~19.03~~ 18.09.9

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

Unhandled Exception: System.AggregateException: One or more errors occurred. (The X509 certificate could not be added to the store.) ---> System.Security.Cryptography.CryptographicException: The X509 certificate could not be added to the store. ---> System.UnauthorizedAccessException: Access to the path '/home/edgehubuser/.dotnet/corefx/cryptography/x509stores/root' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.AddCertToStore(ICertificatePal certPal)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.InstallCertificates(IEnumerable`1 certificateChain, ILogger logger) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 224
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration, ILogger logger) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 86
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 51
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 30

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by and-rewsmith** [comment]
Hi @licensedslacker. Thanks for reporting the issue!

Can we see more EdgeHub logs (as much context as possible from container start) along with the deployment file you are using **(with sensitive information redacted)**?

**Comment by licensedslacker** [comment]
That's actually almost everything I have received from the EdgeHub.

<details>
<summary>full edge-hub logs</summary>

```
2020-04-17 17:16:17 +00:00 Starting Edge Hub
2020-04-17 17:16:18.192 +00:00 Edge Hub Main()
<6> 2020-04-17 17:16:28.044 +00:00 [INF] - Installing certificates [CN=iotedged workload ca:07/16/2020 15:00:10],[CN=Test Edge Device CA:07/16/2020 15:00:10],[CN=Test Edge Owner CA:07/16/2020 15:00:10] to Root

Unhandled Exception: System.AggregateException: One or more errors occurred. (The X509 certificate could not be added to the store.) ---> System.Security.Cryptography.CryptographicException: The X509 certificate could not be added to the store. ---> System.UnauthorizedAccessException: Access to the path '/home/edgehubuser/.dotnet/corefx/cryptography/x509stores/root' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.AddCertToStore(ICertificatePal certPal)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.InstallCertificates(IEnumerable`1 certificateChain, ILogger logger) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 224
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration, ILogger logger) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 86
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 51
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 30
```
</details>

<details>
<summary>Deployment manifest</summary>

```
{
    "modulesContent": {
        "$edgeAgent": {
            "properties.desired": {
                "modules": {},
                "runtime": {
                    "settings": {
                        "minDockerVersion": "v1.25"
                    },
                    "type": "docker"
                },
                "schemaVersion": "1.0",
                "systemModules": {
                    "edgeAgent": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
                            "createOptions": "{}"
                        },
                        "type": "docker"
                    },
                    "edgeHub": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
                            "createOptions": "{\"Env\":[\"httpSettings__enabled=false\"],\"HostConfig\":{\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
                        },
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always"
                    }
                }
            }
        },
        "$edgeHub": {
            "properties.desired": {
                "routes": {},
                "schemaVersion": "1.0",
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 7200
                }
            }
        }
    }
}
```
</details>

We recently updated the edgelet to version 1.0.9 from version 1.0.9-rc6 and updated all images. We have run the platform successfully on the device with an older version.

Docker version was reported incorrectly. The actual version is 18.09.9.

**Comment by and-rewsmith** [comment]
I wasn't able to reproduce this issue on Raspian 10 on a RaspberryPi. I checked the permissions and they were fine for edgehubuser.
```
pi@raspberrypi:~ $ sudo docker exec -it edgeHub sh
$ cd /home/edgehubuser/.dotnet/corefx/cryptography/x509stores/root
$ namei -l ./
f: ./
drwxr-xr-x edgehubuser edgehubuser .
$ exit
```

I'm not sure what could be causing this, so I'm going to get some help.

**Comment by licensedslacker** [comment]
What version of Raspberry Pi? I think 3b and 4 are ARM64, but we are on ARM32.

**Comment by and-rewsmith** [comment]
You're correct in that it's a 64 bit architecture, but it's running a 32 bit os.

**Comment by licensedslacker** [comment]
Found a workaround for the issue, but it won't solve the root problem.
`docker start edgeHub && docker exec -t --user root edgeHub chown -R 1000:1000 /home/edgehubuser`

`docker run --rm mcr.microsoft.com/azureiotedge-hub:1.0 ls -al /home/edgehubuser`
gives following output for the `/home/edgehubuser`
```
drwxr-xr-x 2 root root 4096 Feb 29 01:23 .
drwxr-xr-x 3 root root 4096 Feb 29 01:23 ..
-rw-r--r-- 1 root root  220 Apr  4  2018 .bash_logout
-rw-r--r-- 1 root root 3771 Apr  4  2018 .bashrc
-rw-r--r-- 1 root root  807 Apr  4  2018 .profile
```
however, on AMD64 version of the image gives following output
```
drwxr-sr-x    2 edgehubu edgehubu      4096 Mar 17 21:28 .
drwxr-xr-x    1 root     root          4096 Mar 17 21:28 ..
```
For some reason, the user's home folder permissions are not set correctly on our platform. I'm trying to wrap my head around could this be a docker configuration issue and what would cause the behaviour.

**Comment by licensedslacker** [comment]
OK, yeah. Made a small test setup where I'm pulling the dotNet core image `mcr.microsoft.com/dotnet/core/runtime:2.1.16-bionic-arm32v7` and added the lines from the base image Dockerfile
```
ARG EDGEHUBUSER_ID=1000
RUN useradd -ms /bin/bash -u ${EDGEHUBUSER_ID} edgehubuser
```
User ID 1000 end up always to be user ID 0 in the image. For instance ID 1001 is working as expected. I think the root problem is coming from the docker where we have configured userns-remapping and that is exactly the user with ID 1000. All references to user ID 1000 get translated to ID 0 in the image this case.

So, I'll close the case because of not a bug in the Edge Hub after all. We have to figure out how to solve the remapping issue with some other measure. One option is to run edgeHub with a root user.
