### ISSUE TITLE
Installation procedure does not work on Windows 10 IoT Enterprise

### ISSUE THREAD

**Issue by The-Judge** [Azure/iotedge#2857]
## Expected Behavior
After following https://docs.microsoft.com/de-de/azure/iot-edge/how-to-install-iot-edge-windows , executing `iotedge check` should not raise an error because there is no such object: edgeHub or at least tell how to solve this.

## Current Behavior
Installation of IoT Edge in Microsoft Windows 10 Enterprise LTSC (Evaluation) Version	10.0.17763 Build 17763 always fails with container `edgeHub` missing. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Download a copy of Microsoft Windows 10 Enterprise LTSC and install it.
2. Follow along https://docs.microsoft.com/de-de/azure/iot-edge/how-to-install-iot-edge-windows
3. When reaching the section where `iotedge check` must be executed, it will always complain about this issue.

## Context (Environment)
I tried this twice with the same result. There is no Proxy or Firewall involved.

### Output of `iotedge check`

<details>
<summary>edgeHub missing</summary>

```

PS C:\Windows\system32> iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2020-07-16 13:47:50 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: docker returned exit code: 1, stderr = Error: No such object: edgeHub

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

18 check(s) succeeded.
2 check(s) raised warnings.
1 check(s) raised errors.


PS C:\Windows\system32>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Microsoft Windows 10 Enterprise LTSC Evaluation
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Windows containers

### Runtime Versions
* iotedged [run `iotedge version`]: iotedge 1.0.9 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.9
* Edge Hub [image tag (e.g. 1.0.0)]: not available
* Docker/Moby [run `docker version`]: 

Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 22:01:41 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          windows/amd64
  Experimental:     false

## Logs

<details>
<summary>iotedged logs</summary>

```

PS C:\Windows\system32> Get-Service iotedge

Status   Name               DisplayName
------   ----               -----------
Running  iotedge            Azure IoT Edge Daemon


PS C:\Windows\system32> . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Get-IoTEdgeLog

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Import-IntermediateCertCh...



TimeCreated         Message
-----------         -------
17.04.2020 17:16:13 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:13.768456200 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:16 info: edgelet_core::watchdog -- Checking edge runtime status
17.04.2020 17:16:16 info: edgelet_core::watchdog -- Edge runtime is running.
17.04.2020 17:16:18 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:18.782327400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:23 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:23.798758700 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:28 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:28.821587 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:33 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:33.831406700 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:38 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:38.836918600 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:43 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:43.869373600 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:48 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:48.901781800 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:53 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:53.913927 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:16:58 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:16:58.927341800 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:03 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:03.944387200 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:08 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:08.955662200 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:13 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:13.961215100 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:16 info: edgelet_core::watchdog -- Checking edge runtime status
17.04.2020 17:17:16 info: edgelet_core::watchdog -- Edge runtime is running.
17.04.2020 17:17:18 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:18.968909600 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:23 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:23.981135900 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:28 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:28.992649 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:34 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:34.003299200 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:39 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:39.017281600 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:44 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:44.024723200 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:49 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:49.040873300 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:54 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:54.067211400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:17:59 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:17:59.083191200 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:04 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:04.118640400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:09 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:09.133809300 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:14 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:14.151747500 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:16 info: edgelet_core::watchdog -- Checking edge runtime status
17.04.2020 17:18:16 info: edgelet_core::watchdog -- Edge runtime is running.
17.04.2020 17:18:19 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:19.166617700 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:24 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:24.195273700 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:29 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:29.202175400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:29 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:29.473618500 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "iotedge/0.1.0" auth_id(-)
17.04.2020 17:18:34 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:34.213489100 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:39 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:39.244721400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:44 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:44.254660 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:49 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:49.267488300 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:54 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:54.272898100 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:18:59 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:18:59.300790600 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:04 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:04.304610400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:09 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:09.317557100 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:14 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:14.323850 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:16 info: edgelet_core::watchdog -- Checking edge runtime status
17.04.2020 17:19:16 info: edgelet_core::watchdog -- Edge runtime is running.
17.04.2020 17:19:19 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:19.335331700 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:24 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:24.354561300 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:29 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:29.367759200 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:34 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:34.403143700 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:39 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:39.407875100 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:44 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:44.418148400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:49 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:49.436828700 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:54 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:54.461861500 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:19:59 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:19:59.470631300 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:04 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:04.487650500 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:09 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:09.504986500 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:14 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:14.518040200 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:16 info: edgelet_core::watchdog -- Checking edge runtime status
17.04.2020 17:20:16 info: edgelet_core::watchdog -- Edge runtime is running.
17.04.2020 17:20:19 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:19.535080900 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:24 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:24.550830400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:29 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:29.565752400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:34 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:34.580974 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:39 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:39.597517900 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:44 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:44.612173 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:49 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:49.620102 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:54 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:54.631490100 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:20:59 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:20:59.642553400 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:21:04 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:21:04.657832 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)
17.04.2020 17:21:09 info: edgelet_http::logging -- [mgmt] - - - [2020-04-17 15:21:09.684664100 UTC] "GET
                    /modules?api-version=2019-11-05 HTTP/1.1" 200 OK 532 "-" "-" auth_id(-)


PS C:\Windows\system32>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<6> 2020-04-17 17:00:17.924 +02:00 [INF] - Initializing Edge Agent.
<6> 2020-04-17 17:00:18.085 +02:00 [INF] - Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
<6> 2020-04-17 17:00:18.085 +02:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-04-17 17:00:18.131 +02:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false,"EnableGetLogs":false,"EnableMetrics":false}
<6> 2020-04-17 17:00:18.314 +02:00 [INF] - Installing certificates [CN=Test Edge Owner CA:7/16/2020 3:47:50 PM] to CertificateAuthority
<6> 2020-04-17 17:00:18.750 +02:00 [INF] - Created persistent store at C:\Windows\TEMP\edgeAgent
<6> 2020-04-17 17:00:18.816 +02:00 [INF] - Started operation refresh twin config
<6> 2020-04-17 17:00:18.837 +02:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2020-04-17 17:00:18.870 +02:00 [INF] - Registering request handler RestartModule
<6> 2020-04-17 17:00:19.591 +02:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2020-04-17 17:00:19.706 +02:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2020-04-17 17:00:19.764 +02:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 20.
<6> 2020-04-17 17:00:19.767 +02:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2020-04-17 17:00:19.769 +02:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\EdgeAgentConnection.cs:line 245
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__29_0(Twin twin) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\EdgeAgentConnection.cs:line 176
<6> 2020-04-17 17:00:20.092 +02:00 [INF] - Updated reported properties

```
</details>

<details>
<summary>edge-hub logs</summary>

```

not available

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by veyalla** [comment]
This error is expected as the device has an empty configuration. Due to this, the edgeHub module is not present on the system and hence cannot be checked. Set a non-empty deployment and re-run the check after the edgeHub module is created, and it should go away (or give you actionable advice).

I'll add a backlog item to clarify this error message in a future release.

**Comment by The-Judge** [comment]
Exactly, that hint (that this is expected) would be helpful to new users, I think. All the other warnings and errors (like those about missing DNS configuration and log retention) do provide aka - Hyperlinks to learn more. This is missing here, leaving one with little clue what the issue is.

**Comment by and-rewsmith** [comment]
@The-Judge I agree. I have created a work item for us to add this context.
