### ISSUE TITLE
Error calling IotHub for connectivity test - Service rejected the message with status: 429

### ISSUE THREAD

**Issue by AMCN41R** [Azure/iotedge#2858]
## Summary
At approx. 05:00 UTC yesterday (20th April 2020) a subset of devices on one of our production IoT Hubs stopped communicating.

Investigations showed the the edgeHub was in a faulty state, reporting the following errors...

**Error calling IotHub for connectivity test**
*System.InvalidOperationException: Service rejected the message with status: 429*

<details>
<summary>edgeHub logs</summary>

```
2020-04-20 04:54:44.485 +00:00 [INF] - Reauthenticating connected clients
2020-04-20 04:54:56.782 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint 8L80N42/Bridge/hub
2020-04-20 04:54:56.783 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint 8L80N42/Bridge/hub and 0 messages from message store.
2020-04-20 04:55:26.787 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint 8L80N42/Scheduler/cbus-heartbeat
2020-04-20 04:55:26.789 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint 8L80N42/Scheduler/cbus-heartbeat and 0 messages from message store.
2020-04-20 04:55:56.794 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint 8L80N42/Bridge/cbus-commands
2020-04-20 04:55:56.796 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint 8L80N42/Bridge/cbus-commands and 0 messages from message store.
2020-04-20 04:56:26.802 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint 8L80N42/Scheduler/hub
2020-04-20 04:56:26.803 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint 8L80N42/Scheduler/hub and 0 messages from message store.
2020-04-20 04:56:56.804 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint 8L80N42/Scheduler/info
2020-04-20 04:56:56.994 +00:00 [INF] - Cleaned up 68 messages from queue for endpoint 8L80N42/Scheduler/info and 68 messages from message store.
2020-04-20 04:57:26.998 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint 8L80N42/Scheduler/cbus-events
2020-04-20 04:57:27.000 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint 8L80N42/Scheduler/cbus-events and 0 messages from message store.
2020-04-20 04:57:57.007 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2020-04-20 04:57:57.061 +00:00 [INF] - Cleaned up 17 messages from queue for endpoint iothub and 17 messages from message store.
2020-04-20 04:58:27.062 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint 8L80N42/Scheduler/cbus-command-response
2020-04-20 04:58:27.064 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint 8L80N42/Scheduler/cbus-command-response and 0 messages from message store.
2020-04-20 04:59:44.483 +00:00 [INF] - Reauthenticating connected clients
2020-04-20 05:04:13.002 +00:00 [INF] - New token received on the Cbs link
2020-04-20 05:04:13.004 +00:00 [INF] - Token updated for 8L80N42/Bridge
2020-04-20 05:04:13.082 +00:00 [INF] - New token received on the Cbs link
2020-04-20 05:04:13.083 +00:00 [INF] - Token updated for 8L80N42/Bridge
2020-04-20 05:04:13.094 +00:00 [INF] - New token received on the Cbs link
2020-04-20 05:04:13.099 +00:00 [INF] - Token updated for 8L80N42/Device
2020-04-20 05:04:15.074 +00:00 [INF] - New token received on the Cbs link
2020-04-20 05:04:15.075 +00:00 [INF] - Token updated for 8L80N42/Scheduler
2020-04-20 05:04:44.481 +00:00 [INF] - Reauthenticating connected clients
2020-04-20 05:05:03.124 +00:00 [WRN] - Error calling IotHub for connectivity test
System.InvalidOperationException: Service rejected the message with status: 429
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.\u003c\u003ec__DisplayClass22_0.\u003c\u003cExecuteWithErrorHandlingAsync\u003eb__0\u003ed.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.\u003c\u003ec__DisplayClass25_0.\u003c\u003cSendTwinPatchAsync\u003eb__0\u003ed.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.\u003c\u003ec__DisplayClass30_0.\u003c\u003cInvokeFunc\u003eb__0\u003ed.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 144
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 171
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 177
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.\u003c\u003ec__DisplayClass22_0.\u003c\u003cExecuteOperation\u003eb__0\u003ed.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.ExecuteOperation[T](Func`2 func, String operation) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 71
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager.ConnectivityChecker.Check() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs:line 208
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager.CheckConnectivity() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs:line 171
```
</details>

This happened simultaneously across approx. 35 devices. The `edgeHub` backed off but kept retrying for more than 12 hours. Throttling errors were continuously reported, and the issue could only be resolved by restarting the `edgeHub` module.

There was no significant increase in Device-to-Cloud messages leading up to this event.

I'm not sure if this is an issue with the edgeHub, or the IoT Hub, however, simply restarting the edgeHub resolved the issue.

## Expected Behavior
`edgeHub` should recover from failed connectivity tests

## Current Behavior
It did not

## Steps to Reproduce
Unsure how to reproduce

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu Core
* Architecture [e.g. amd64, arm32, arm64]:  amd62
* Container OS [e.g. Linux containers, Windows containers]: Linux containers 

### Runtime Versions
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.8.5
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.8.5

## Additional Information
More logs are available if required.

![throttle_errors](https://user-images.githubusercontent.com/15929161/79856088-c7131780-83c3-11ea-8f4a-a3cf686a06b2.PNG)

**Comment by arsing** [comment]
>At approx. 05:00 UTC yesterday (20th April 2020) a subset of devices on one of our production IoT Hubs stopped communicating.

How many total devices are connected to the IoT Hub? ie how many devices connected to that hub did *not* have the problem?

Did all the devices that did have the problem all start having it within a few minutes of each other (as your graph indicates)?

Are the two dips in the errors graph because you restarted the Edge Hubs on the ~35 affected devices in two batches?


>More logs are available if required.

Please give a larger range, specifically starting from the previous (successful) attempt of "Reauthenticating connected clients" before the one in your post (so that we can see what happened between the last successful attempt and the first unsuccessful one), and ending at the next instance of "Service rejected the message with status: 429" after the one in your post (so that we can see what happened between the first unsuccessful attempt and the second one).


>I'm not sure if this is an issue with the edgeHub, or the IoT Hub, however, simply restarting the edgeHub resolved the issue.

One possibility is IoT Hub had poisoned the connection. It seems to me from looking at the code that the client is reused despite errors. Restarting Edge Hub made it create a new connection, so it didn't have the problem any more. I need to check with the code owners.


>`edgeHub` should recover from failed connectivity tests

It seems to me from looking at the code that `DeviceConnectivityManager` only transitions states if the check times out rather than throws an arbitrary HTTP 4xx. That might be an issue. I need to check with the code owners.

**Comment by AMCN41R** [comment]
Thanks for your help @arsing. Here is a bit more information for you... 

> How many total devices are connected to the IoT Hub? ie how many devices connected to that hub did not have the problem?

381 devices total - 35 affected  / 346 not affected

> Did all the devices that did have the problem all start having it within a few minutes of each other (as your graph indicates)?

Yes - all at around 05:00 UTC - each device sends a message every 2 minutes, and the last received were between 04:57 and 05:00

> Are the two dips in the errors graph because you restarted the Edge Hubs on the ~35 affected devices in two batches?

Yes - the dips correlate with two batches of restarts we performed

Additional logs... This is from the same device from the day before (19th April) until the first occurrence.
[EdgeHubLogs.txt](https://github.com/Azure/iotedge/files/4514995/EdgeHubLogs.txt)

**Comment by arsing** [comment]
I talked to Varun and he confirmed that the connection would remain open and be reused in this case. He suggested some part of the call stack ought to be changed to dispose the SDK client if it gets an HTTP 4xx so that it automatically reconnects with a new connection.

**Comment by dylanbronson** [comment]
Hi @AMCN41R, have you seen this issue again/are you able to reproduce it now? 

I was looking into making the fix that @arsing and Varun suggested, but a few things seem odd to me. 

1) A throttling exception shouldn't be immediately resolved on edgeHub restart
2) EdgeHub receives InvalidOperationException with a message of the 429 error. InvalidOperationException doesn't seem like a perfect fit (rather it should be something like IoTHubThrottlingException)

So if we fix this in edgeHub by making InvalidOperationException a NonRecoverable exception, we will likely fix this issue, but it might just be a workaround for the real issue of us receiving an inaccurate exception type. 

To me, it looks like the errors could be reporting the wrong thing, likely from IoTHub side, since 1) there was no large increase in messages at the time and 2) immediately after edgeHub restart we saw the issue fixed. 

EdgeHub actually looks like it is trying to do the "right thing" by retrying every 5 min, but because edgeHub is acting off of incorrect information, then it is in fact not doing the right thing. I'll try to see what I can find out from hub/sdk side

**Comment by AMCN41R** [comment]
Hi @dylanbronson , thanks for the update.

We've not seen this happen again since, and not sure how to replicate it (really unhelpful, sorry 😄).

I understand what you're saying about the exceptions. One thing I would say is that, perhaps all exceptions should have a max retry limit and be non-recoverable? This module is running at the edge, and we want them to self-heal as much as possible. For instance, in this case, our support team have had to manually restart the remote devices to resolve a situation where there was actually no problem.

This is not the only issue we have experienced where the edgeHub has got into a bad state and has been unable to recover, and restarting the module has resolved the issue.

If the edgeHub had a maximum retry limit before exiting and restarting, these transient problems would resolve themselves?

If there's anything I can do to help, let me know.

**Comment by dylanbronson** [comment]
Thank you for the suggestion, @AMCN41R. I've added your suggestion to our bug backlog, as I agree that will improve edgeHub's recoverability.
