### ISSUE TITLE
New Installation of IoTEdge on raspberrypi throws System.ArgumentException: key is null or whitespace.

### ISSUE THREAD

**Issue by tanieee28** [Azure/iotedge#2947]
Hi,
after a long time of non stop running of iotedge on my raspberry pi, today it suddenly stopped sending data to iot hub because the edgeHub was not able to authenticate connection.
So, after long troubleshooting, i finally decided to remove and reinstall iotedge.

But, after installation of iotedge, edgeAgent module started throwing following error :

```
<4> 2020-05-12 08:14:00.376 +00:00 [WRN] - Reconcile failed because of the an exception
System.ArgumentException: key is null or whitespace.
   at Microsoft.Azure.Devices.Edge.Util.Preconditions.CheckNonWhiteSpace(String value, String paramName) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Preconditions.cs:line 191
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Models.EnvVar..ctor(String key, String value) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/models/EnvVar.cs:line 8
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Commands.CreateOrUpdateCommand.<>c.<GetEnvVars>b__14_0(KeyValuePair`2 m) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/CreateOrUpdateCommand.cs:line 95
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Commands.CreateOrUpdateCommand.GetEnvVars(IDictionary`2 moduleEnvVars, IModuleIdentity identity, IConfigSource configSource) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/CreateOrUpdateCommand.cs:line 95
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Commands.CreateOrUpdateCommand.Build(IModuleManager moduleManager, IModule module, IModuleIdentity identity, IConfigSource configSource, Object settings, Operation operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/CreateOrUpdateCommand.cs:line 198
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommandFactory`1.CreateAsync(IModuleWithIdentity module, IRuntimeInfo runtimeInfo) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/EdgeletCommandFactory.cs:line 24
   at Microsoft.Azure.Devices.Edge.Agent.Core.MetricsCommandFactory.CreateAsync(IModuleWithIdentity module, IRuntimeInfo runtimeInfo) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/MetricsCommandFactory.cs:line 28
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.CreateAsync(IModuleWithIdentity module, IRuntimeInfo runtimeInfo) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 21
   at Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner.ProcessAddedUpdatedModules(IList`1 modules, IImmutableDictionary`2 moduleIdentities, Func`2 createUpdateCommandMaker) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs:line 250
   at Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner.PlanAsync(ModuleSet desired, ModuleSet current, IRuntimeInfo runtimeInfo, IImmutableDictionary`2 moduleIdentities) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs:line 88
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 137
```
I have never seen such issue before on my raspberrypi iotedge.
Can someone help me on this ??

**Comment by darobs** [comment]
Hello @tanieee28,

The error message indicates that the deployment has a module with an incorrect key value for an environment variable. The key is either null or all whitespace. This would be unusual, as the portal UI should block this.

1. Would you run `iotedge check` on the device and see what errors come back?

2. Would you look at the deployment and see if there are any incorrect "env" sections?  
If you use "Set Modules" on the device, and go to the "Review+Create" page, you can search for the "env" object for each module.  The "env" section should look something like,
```json
  "env": {
    "key1": {
      "value": "value1"
    },
    "key2": {
      "value": "value2"
    }
  },
```
The keys should not be whitespace or invalid.

**Comment by tanieee28** [comment]
Hi @darobs,
Yes, you are right the  problem was with env variables that i was using, i mistakenly set up a blank env variable and found that in the json of review+create page. I made the changes and now everything seems to be working good.
Thanks
