### ISSUE TITLE
Edge Agent is not running while configuring IoT Edge device to run ML Model 

### ISSUE THREAD

**Issue by pbiswas-kol** [Azure/iotedge#298]
## Expected Behavior
edgeAgent should run stable for long time

## Current Behavior
edgeAgent failed  

## Steps to Reproduce

1. Install moby-engine rpm from https://github.com/Azure/azure-iotedge/releases/tag/1.0.1
2. Install moby-cli rpm from https://github.com/Azure/azure-iotedge/releases/tag/1.0.1
3. Install iotedge runtime and it's dependency rpm from https://github.com/Azure/azure-iotedge/releases/tag/1.0.1
4. Configure (Manual) config.yaml
   a) Set IoT Edge Device Connection string
   b) Change "management_uri" to "http://172.17.0.1:15580" connect section
   c) Change "workload_uri" to "http://172.17.0.1:15581" connect section
   d) Change "management_uri" to "http://172.17.0.1:15580" listen section
   e) Change "workload_uri" to "http://172.17.0.1:15581" listen section
5.Set tempSensor module in iot edge device
6. Set a ML Module in iot edge device
7. set Environment  : export IOTEDGE_HOST="http://172.17.0.1:15580"
8. restart iotedge

### Device (Host) Operating System
RHEL 7.5

### Architecture
amd64

### Container Operating System
Linux container

### Runtime Versions
1.0.1

#### iotedged
iot edge 1.0.1

#### Edge Agent
 mcr.microsoft.com/azureiotedge-agent:1.0.1

#### Docker
Docker version 18.09.0-dev, build 021bf39d

## Logs
edgeAgent Log

2018-09-17 15:29:46.313 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
2018-09-17 15:29:47.140 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2018-09-17 15:29:48.274 +00:00 [FTL] - Fatal error starting Agent.
System.Net.Http.HttpRequestException: Host is unreachable ---> System.Net.Sockets.SocketException: Host is unreachable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.GeneratedCode.EdgeletHttpClient.GetSystemInfoAsync(String api_version, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/generatedCode/EdgeletHttpClient.cs:line 172
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.GetSystemInfoAsync() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 118
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.RuntimeInfoProvider`1.GetSystemInfo() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs:line 33
   at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironmentProvider.CreateAsync(IRuntimeInfoProvider runtimeInfoProvider, IEntityStore`2 store, IRestartPolicyManager restartPolicyManager) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironmentProvider.cs:line 38
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.EdgeletModule.<>c.<<Load>b__9_6>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule.<>c.<<Load>b__13_14>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 159
2018-09-17 15:29:48.309 +00:00 [INF] - Termination requested, initiating shutdown.
2018-09-17 15:29:48.310 +00:00 [INF] - Waiting for cleanup to finish
2018-09-17 15:29:48.310 +00:00 [INF] - Done with cleanup. Shutting down.

## Additional Information
systemctl status iotedge

Sep 17 15:27:44 shRedHatServer iotedged[73323]: 2018-09-17T15:27:44Z [INFO] - Edge runtime status is failed, starting module now...
Sep 17 15:28:44 shRedHatServer iotedged[73323]: 2018-09-17T15:28:44Z [INFO] - Checking edge runtime status
Sep 17 15:28:44 shRedHatServer iotedged[73323]: 2018-09-17T15:28:44Z [INFO] - Edge runtime status is failed, starting module now...
Sep 17 15:29:44 shRedHatServer iotedged[73323]: 2018-09-17T15:29:44Z [INFO] - Checking edge runtime status
Sep 17 15:29:44 shRedHatServer iotedged[73323]: 2018-09-17T15:29:44Z [INFO] - Edge runtime status is failed, starting module now...
Sep 17 15:30:00 shRedHatServer iotedged[73323]: 2018-09-17T15:30:00Z [INFO] - [mgmt] - - - [2018-09-17 15:30:00.839783280 UTC] "GET /modules/edgeAgent/logs?... pid(any)
Sep 17 15:30:44 shRedHatServer iotedged[73323]: 2018-09-17T15:30:44Z [INFO] - Checking edge runtime status
Sep 17 15:30:44 shRedHatServer iotedged[73323]: 2018-09-17T15:30:44Z [INFO] - Edge runtime status is failed, starting module now...
Sep 17 15:31:44 shRedHatServer iotedged[73323]: 2018-09-17T15:31:44Z [INFO] - Checking edge runtime status
Sep 17 15:31:44 shRedHatServer iotedged[73323]: 2018-09-17T15:31:44Z [INFO] - Edge runtime status is failed, starting module now...
Hint: Some lines were ellipsized, use -l to show in full.

**Ifconfig**

![image](https://user-images.githubusercontent.com/41604824/45633761-450f8e00-babe-11e8-96b0-8b0f201f2d49.png)

**Comment by myagley** [comment]
Hello. Thanks for the issue report.

Is the `iotedged` running? (`systemctl status iotedge`). I'm assuming 172.17.0.1 is the address for the `docker0` bridge network? You can verify by running `ip a`.

**Comment by pbiswas-kol** [comment]
@myagley I have shared system status iotedge  and docker 0 bridge network in above additional section

**Comment by pbiswas-kol** [comment]
> Hello. Thanks for the issue report.
> 
> Is the `iotedged` running? (`systemctl status iotedge`). I'm assuming 172.17.0.1 is the address for the `docker0` bridge network? You can verify by running `ip a`.

**Comment by pbiswas-kol** [comment]
Closed by mistake. The issue is still there on RHEL 7.5

**Comment by myagley** [comment]
I just ran this scenario on a CentOS 7.5 VM (I can get a RHEL VM if required), and I can't repro the `host unreachable`. Do you have any additional firewalls setup? What is the output of `iptables -L`?

**Comment by pbiswas-kol** [comment]
@myagley - I created a Azure VM (RHEL 7.5) . Did the above configuration and I got above error in edgeAgent. I have not setup any additional firewalls.

See my RHEL 7.5 iptables -L

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
INPUT_direct  all  --  anywhere             anywhere            
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere            
INPUT_ZONES  all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
FORWARD_direct  all  --  anywhere             anywhere            
FORWARD_IN_ZONES_SOURCE  all  --  anywhere             anywhere            
FORWARD_IN_ZONES  all  --  anywhere             anywhere            
FORWARD_OUT_ZONES_SOURCE  all  --  anywhere             anywhere            
FORWARD_OUT_ZONES  all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
OUTPUT_direct  all  --  anywhere             anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain FORWARD_IN_ZONES (1 references)
target     prot opt source               destination         
FWDI_public  all  --  anywhere             anywhere            [goto] 
FWDI_public  all  --  anywhere             anywhere            [goto] 

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target     prot opt source               destination         

Chain FORWARD_OUT_ZONES (1 references)
target     prot opt source               destination         
FWDO_public  all  --  anywhere             anywhere            [goto] 
FWDO_public  all  --  anywhere             anywhere            [goto] 

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target     prot opt source               destination         

Chain FORWARD_direct (1 references)
target     prot opt source               destination         

Chain FWDI_public (2 references)
target     prot opt source               destination         
FWDI_public_log  all  --  anywhere             anywhere            
FWDI_public_deny  all  --  anywhere             anywhere            
FWDI_public_allow  all  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            

Chain FWDI_public_allow (1 references)
target     prot opt source               destination         

Chain FWDI_public_deny (1 references)
target     prot opt source               destination         

Chain FWDI_public_log (1 references)
target     prot opt source               destination         

Chain FWDO_public (2 references)
target     prot opt source               destination         
FWDO_public_log  all  --  anywhere             anywhere            
FWDO_public_deny  all  --  anywhere             anywhere            
FWDO_public_allow  all  --  anywhere             anywhere            

Chain FWDO_public_allow (1 references)
target     prot opt source               destination         

Chain FWDO_public_deny (1 references)
target     prot opt source               destination         

Chain FWDO_public_log (1 references)
target     prot opt source               destination         

Chain INPUT_ZONES (1 references)
target     prot opt source               destination         
IN_public  all  --  anywhere             anywhere            [goto] 
IN_public  all  --  anywhere             anywhere            [goto] 

Chain INPUT_ZONES_SOURCE (1 references)
target     prot opt source               destination         

Chain INPUT_direct (1 references)
target     prot opt source               destination         

Chain IN_public (2 references)
target     prot opt source               destination         
IN_public_log  all  --  anywhere             anywhere            
IN_public_deny  all  --  anywhere             anywhere            
IN_public_allow  all  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            

Chain IN_public_allow (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW

Chain IN_public_deny (1 references)
target     prot opt source               destination         

Chain IN_public_log (1 references)
target     prot opt source               destination         

Chain OUTPUT_direct (1 references)
target     prot opt source               destination         


**Please note :  I provisioned a Ubuntu 16.04 azure  VM today and do the same configuration as RHEL 7.5 and It's working as expected.**

**Comment by myagley** [comment]
Can you please run `docker network inspect bridge azure-iot-edge` and post the output? This will help understand how the various networks are configured.

**Comment by pbiswas-kol** [comment]
@myagley 
Here is the output of command docker network inspect bridge azure-iot-edge : 


[root@rhel75 iotedge]# docker network inspect bridge azure-iot-edge
[
    {
        "Name": "bridge",
        "Id": "6283fb3c81a590e6d979f20105e814d276184c8d25cfd5010deab420f081fe0e",
        "Created": "2018-09-27T14:09:59.195931874Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    },
    {
        "Name": "azure-iot-edge",
        "Id": "6c2a25a28819fee4cb3ccd6785907c26d3cf2eec3091b22ff63282149163c82b",
        "Created": "2018-09-19T21:20:10.192514793Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

**Comment by pbiswas-kol** [comment]
@myagley any update on this isues ?

Thanks
PB

**Comment by alevincenzi** [comment]
@myagley @pbiswas-kol any update?
I am facing the same kind of error: `systemctl satus iotedge` says that the service is active and running but the edgeAgent never shows up. The watchdog keeps restarting it:
```
<6>2019-03-14T14:00:29Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2019-03-14T14:00:29Z [INFO] - Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
<6>2019-03-14T14:00:29Z [INFO] - Using config file: /etc/iotedge/config.yaml
<6>2019-03-14T14:00:29Z [INFO] - Using runtime network id azure-iot-edge
<6>2019-03-14T14:00:29Z [INFO] - Initializing the module runtime...
<6>2019-03-14T14:00:29Z [INFO] - Initializing module runtime...
<6>2019-03-14T14:00:29Z [INFO] - Successfully initialized module runtime
<6>2019-03-14T14:00:29Z [INFO] - Finished initializing the module runtime.
<6>2019-03-14T14:00:29Z [INFO] - Configuring /var/lib/iotedge as the home directory.
<6>2019-03-14T14:00:29Z [INFO] - Configuring certificates...
<6>2019-03-14T14:00:29Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
<6>2019-03-14T14:00:29Z [INFO] - Finished configuring certificates.
<6>2019-03-14T14:00:29Z [INFO] - Initializing hsm...
<6>2019-03-14T14:00:30Z [INFO] - Finished initializing hsm.
<6>2019-03-14T14:00:30Z [INFO] - Detecting if configuration file has changed...
<6>2019-03-14T14:00:30Z [INFO] - Change to configuration file detected.
<6>2019-03-14T14:00:30Z [INFO] - Removing all modules...
<6>2019-03-14T14:00:30Z [INFO] - Finished removing modules.
<3>2019-03-14T14:00:30Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert_and_key_exist_by_alias:1458) Certificate and key file for alias do not exist iotedged-workload-ca
<6>2019-03-14T14:00:31Z [INFO] - Provisioning edge device...
<6>2019-03-14T14:00:31Z [INFO] - Manually provisioning device "XXX" in hub "XXX.azure-devices.net"
<6>2019-03-14T14:00:31Z [INFO] - Finished provisioning edge device.
<6>2019-03-14T14:00:31Z [INFO] - Starting management API...
<6>2019-03-14T14:00:31Z [INFO] - Starting workload API...
<6>2019-03-14T14:00:31Z [INFO] - Starting watchdog with 60 second frequency...
<6>2019-03-14T14:00:31Z [INFO] - Listening on http://172.19.0.2:15580/ with 1 thread for management API.
<6>2019-03-14T14:00:31Z [INFO] - Listening on http://172.19.0.2:15581/ with 1 thread for workload API.
<6>2019-03-14T14:00:31Z [INFO] - Checking edge runtime status
<6>2019-03-14T14:00:31Z [INFO] - Creating and starting edge runtime module edgeAgent
<6>2019-03-14T14:00:31Z [INFO] - Updating identity for module $edgeAgent
<6>2019-03-14T14:00:31Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0...
<6>2019-03-14T14:00:43Z [INFO] - Successfully pulled image mcr.microsoft.com/azureiotedge-agent:1.0
<6>2019-03-14T14:00:43Z [INFO] - Creating module edgeAgent...
<6>2019-03-14T14:00:43Z [INFO] - Successfully created module edgeAgent
<6>2019-03-14T14:00:43Z [INFO] - Starting module edgeAgent...
<6>2019-03-14T14:00:44Z [INFO] - Successfully started module edgeAgent
<6>2019-03-14T14:01:31Z [INFO] - Checking edge runtime status
<6>2019-03-14T14:01:31Z [INFO] - Edge runtime status is failed, starting module now...
<6>2019-03-14T14:01:31Z [INFO] - Starting module edgeAgent...
<6>2019-03-14T14:01:31Z [INFO] - Successfully started module edgeAgent
<6>2019-03-14T14:02:31Z [INFO] - Checking edge runtime status
<6>2019-03-14T14:02:31Z [INFO] - Edge runtime status is failed, starting module now...
<6>2019-03-14T14:02:31Z [INFO] - Starting module edgeAgent...
<6>2019-03-14T14:02:31Z [INFO] - Successfully started module edgeAgent
<6>2019-03-14T14:03:31Z [INFO] - Checking edge runtime status
```
I got to this point by running the iotedge inside a container as described in [this](https://github.com/Azure/iotedgedev/tree/master/docker/runtime) project (iotedgedev).
From windows+powershell the combo build && export && run works fine. From Ubtuntu 16.04 with docker 3.0.3 if fails. Our network is the following:

```
root@f678b0a31a4c:/# docker network inspect bridge azure-iot-edge
[
    {
        "Name": "bridge",
        "Id": "bfad71262a20b3bffc6988e906b464fa1494d016e04bd8a1b414f598804be8ef",
        "Created": "2019-03-14T15:18:52.180851789Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    },
    {
        "Name": "azure-iot-edge",
        "Id": "b13ebdba7c35f05d41d7b2d2cfbb7f3882bca79d7584f4100c4255d6598c4b55",
        "Created": "2019-03-14T15:18:52.800803006Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
root@f678b0a31a4c:/# 
```

Thank You !

**Comment by lt72** [comment]
Closing as it seems stale. Please re-open if necessary.
