### ISSUE TITLE
X.509 ECC Certs not working

### ISSUE THREAD

**Issue by Tineler** [Azure/iotedge#3038]
For a project, we need to use ECC Certificates on the IoT Edge Gateway, for the whole certificate chain. But it seems that ECC Certificates are not supported?

## Expected Behavior
IoT Edge should be able to use ECC certificates.

## Current Behavior
When using ECC certificates, an error happens:

<summary>iotedged logs</summary>

```

Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [INFO] - Finished removing modules.
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] - The daemon could not start up successfully: Could not prepare workload CA certificate
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] -         caused by: An error occurred getting the certificate
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] -         caused by: HSM failure
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] -         caused by: HSM API returned an invalid null response
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert_and_key_exist_by_alias
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c:parse_validity_timestamps:286) Unsupported
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c:parse_certificate_details:367) Error obtai
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c:parse_certificate:404) Failure obtaining f
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c:certificate_info_create:486) Failure parsi
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com iotedged[2805]: 2020-06-03T08:59:57Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_get_pki_cert:24
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 4.
Jun 03 08:59:57 mttestgateway.northeurope.cloudapp.azure.com systemd[1]: Stopped Azure IoT Edge daemon.


```
</details>

## Steps to Reproduce
We created a chain using the same approach described here: https://github.com/alxayo/Azure-IoTHub-with-X509-ECC#self-signed-ecc-certificate

**Comment by philipktlin** [comment]
@arsing and @eustacea, would you please help to answer this question?

**Comment by arsing** [comment]
Your logs are truncated and so are missing the useful parts of the messages. Given that the error is raised from `parse_validity_timestamps` it's likely because of an invalid not-after/not-before date and not due to using EC keys. Show the full logs to be sure.

**Comment by Tineler** [comment]
Sorry about that. What you say can actually be true. I also had issues using RSA certs having a not-after date later than 2050. I will try again using an earlier date. I'll keep you posted. 

Speaking of which: Is there actually a limitation regarding the not-after date?

**Comment by arsing** [comment]
>Speaking of which: Is there actually a limitation regarding the not-after date?

https://github.com/Azure/iotedge/issues/1960#issuecomment-570719705

**Comment by Tineler** [comment]
After changing the not-after date the `iotedge check` says that everything is okay.

However, I get the following exception in the edgeHub Log-Files:

<details>
<summary>edgeHub logs</summary>

```

Unhandled Exception: System.AggregateException: One or more errors occurred. (Private key is required) ---> System.InvalidOperationException: Private key is required
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.ParseCertificateAndKey(String certificateWithChain, String privateKey) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 384
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetServerCertificatesFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId, String edgeHubHostname, DateTime expiration) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 255
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration, ILogger logger) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 54
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 51
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 30

```
</details>

**Comment by dme-development** [comment]
I have the exact same issue with 1.0.9.2, with a certificate that is valid until end of 2049.
The certificate was working fine with previous release 1.0.9.0 

```
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [INFO] - Initializing hsm X509 interface...
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] - The daemon could not start up successfully: Could not initialize HSM
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] -         caused by: An error occurred when obtaining the device identity certificate.
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] -         caused by: HSM failure
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] -         caused by: HSM certificate info get failed
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c:parse_validity_timestamps:286) Unsupported 'not after' time format in certificate
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c:parse_certificate_details:367) Error obtaining validity timestamps from certificate
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c:parse_certificate:404) Failure obtaining first certificate
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c:certificate_info_create:486) Failure parsing certificate
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_get_pki_cert:2447) Could not obtain certificate info handle for alias: edgelet_device
Jun 16 11:05:46 200401UL3ERQ iotedged[12395]: 2020-06-16T09:05:46Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_x509.c:edge_x509_hsm_get_cert_info:306) Could not create device identity certificate info handle
```

@arsing , any thoughts on this?

**Comment by philipktlin** [comment]
Would you please provide both iotedged and edgeHub logs? if you are using iotedged version >= 1.0.9, you can just run "sudo iotedge support-bundle" to gather all logs for troubleshooting.

**Comment by philipktlin** [comment]
Close for now as it is inactive for a while.
