### ISSUE TITLE
ModuleClient.createFromEnvironment() not working as expected

### ISSUE THREAD

**Issue by marcschroeder** [Azure/iotedge#3061]
## Expected Behavior
Calling `ModuleClient.createFromEnvironment()` creates a new ModuleClient that can be used to communicate with the edgeHub.

## Current Behavior
When calling `ModuleClient.createFromEnvironment()` the following exception is raised:

Expected URL that uses protocol HTTPS but received one that uses protocol 'http'.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create Java Module project
2. Create a ModuleClient using `createFromEnvironment()`
3. Run the module on an edge

## Context (Environment)
When checking the environment variables I noticed that IOTEDGE_WORKLOADURI starts with http:// rater than with https://. Could that cause the issue?

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
√ production readiness: identity certificates expiry - OK
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

21 check(s) succeeded.
4 check(s) raised warnings.


```
</details>

### Device Information
* Host OS: Ubuntu 16.04
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* iotedged: 1.0.9.2
* Edge Agent: 1.0
* Edge Hub: 1.0
* Docker/Moby: 3.0.12+azure 

## Logs
Caused by: java.lang.IllegalArgumentException: Expected URL that uses protocol HTTPS but received one that uses protocol 'http'.

        at com.microsoft.azure.sdk.iot.device.transport.https.HttpsConnection.<init>(HttpsConnection.java:79) ~[iot-device-client-1.22.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.transport.https.HttpsRequest.send(HttpsRequest.java:102) ~[iot-device-client-1.22.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sendRequestBasedOnScheme(HttpsHsmClient.java:204) ~[iot-device-client-1.22.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sign(HttpsHsmClient.java:82) ~[iot-device-client-1.22.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.hsm.HttpHsmSignatureProvider.sign(HttpHsmSignatureProvider.java:89) ~[iot-device-client-1.22.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.hsm.IotHubSasTokenHsmAuthenticationProvider.createNewSasToken(IotHubSasTokenHsmAuthenticationProvider.java:80) ~[iot-device-client-1.22.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.hsm.IotHubSasTokenHsmAuthenticationProvider.create(IotHubSasTokenHsmAuthenticationProvider.java:48) ~[iot-device-client-1.22.0.jar!/:na]
        at com.microsoft.azure.sdk.iot.device.ModuleClient.createFromEnvironment(ModuleClient.java:263) ~[iot-device-client-1.22.0.jar!/:na]

**Comment by marcschroeder** [comment]
During testing of a different component, I found that everything works fine in the Python SDK.

**Comment by marcschroeder** [comment]
The following JDK is installed:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
```
Does the SDK work with OpenJDK?
