### ISSUE TITLE
Module stuck with: Endpoint already exists in network azure-iot-edge

### ISSUE THREAD

**Issue by keesschollaart81** [Azure/iotedge#3170]
## Expected Behavior
Container runtime should run 'forever'

## Current Behavior
In our fleet of ~250 IoT Edge devices, randomly some devices get in a faulty state. One of our containers stops and cannot be started by the egeAgent any more. The error is: `endpoint with name CameraCaptureModule already exists in network azure-iot-edge` (CameraCaptureModule is the name of the name of the edge module)

## Steps to Reproduce
As it happens randomly it's hard to reproduce. When we reboot the dockerd or iotedge, the problem persists. In most of the cases, a server reboot fixes it but in ~5% of the cases it is stuck in this state.

## Context (Environment)
Solution that processes ~15 camera streams and runs some AI modules on the edge, sending alerts to the cloud.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
‼ config.yaml has well-formed connection string - Warning
    Device not configured with manual provisioning, in this configuration 'iotedge check' is not able to discover the device's backing IoT Hub.
    To run connectivity checks in this configuration please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    If no hostname is provided, all hub connectivity tests will be skipped.
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9 but 1.0.9.3 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: identity certificates expiry - OK
√ production readiness: certificates - OK
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK

10 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
9 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

We're not on moby as we need GPU acceleration 

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
Ubuntu 18.04.3

* Architecture [e.g. amd64, arm32, arm64]: 
x86_64

* Container OS [e.g. Linux containers, Windows containers]: 
Linux Containers (Ubuntu 20.04, based on ubuntu:focal)

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
iotedge 1.0.9

* Edge Hub [image tag (e.g. 1.0.0)]: 
mcr.microsoft.com/azureiotedge-agent:1.0

* Docker/Moby [run `docker version`]: 
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 nvidia:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Logs

 
<details>
<summary>edge-agent logs</summary>

``` 
<6> 2020-06-30 13:36:50.465 +00:00 [INF] - Executing command: "Stop module CameraCaptureModule"
<6> 2020-06-30 13:36:50.467 +00:00 [INF] - Executing command: "Start module CameraCaptureModule"
<3> 2020-06-30 13:37:09.139 +00:00 [ERR] - Executing command for operation ["start"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module CameraCaptureModule: Could not start module CameraCaptureModule
        caused by: Could not start module CameraCaptureModule
        caused by: endpoint with name CameraCaptureModule already exists in network azure-iot-edge, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 210
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 127
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 165
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
<3> 2020-06-30 13:37:09.140 +00:00 [ERR] - Executing command for operation ["Command Group: (\n  [Stop module CameraCaptureModule]\n  [Start module CameraCaptureModule]\n  [Saving CameraCaptureModule to store]\n)"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module CameraCaptureModule: Could not start module CameraCaptureModule
        caused by: Could not start module CameraCaptureModule
        caused by: endpoint with name CameraCaptureModule already exists in network azure-iot-edge, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 210
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 127
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 165
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
<3> 2020-06-30 13:37:09.140 +00:00 [ERR] - Step failed in deployment 19, continuing execution. Failure when running command Command Group: (
  [Stop module CameraCaptureModule]
  [Start module CameraCaptureModule]
  [Saving CameraCaptureModule to store]
). Will retry in 00s.
<6> 2020-06-30 13:37:09.141 +00:00 [INF] - Plan execution ended for deployment 19
<3> 2020-06-30 13:37:09.141 +00:00 [ERR] - Edge agent plan execution failed.
System.AggregateException: One or more errors occurred. (Error calling start module CameraCaptureModule: Could not start module CameraCaptureModule
        caused by: Could not start module CameraCaptureModule
        caused by: endpoint with name CameraCaptureModule already exists in network azure-iot-edge) ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException: Error calling start module CameraCaptureModule: Could not start module CameraCaptureModule
        caused by: Could not start module CameraCaptureModule
        caused by: endpoint with name CameraCaptureModule already exists in network azure-iot-edge
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 210
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 127
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 165
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 87
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 115
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 116
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 146
---> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module CameraCaptureModule: Could not start module CameraCaptureModule
        caused by: Could not start module CameraCaptureModule
        caused by: endpoint with name CameraCaptureModule already exists in network azure-iot-edge, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 210
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 127
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 165
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 87<---
<4> 2020-06-30 13:37:09.215 +00:00 [WRN] - Reconcile failed because of the an exception
System.AggregateException: One or more errors occurred. (Error calling start module CameraCaptureModule: Could not start module CameraCaptureModule
        caused by: Could not start module CameraCaptureModule
        caused by: endpoint with name CameraCaptureModule already exists in network azure-iot-edge) ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException: Error calling start module CameraCaptureModule: Could not start module CameraCaptureModule
        caused by: Could not start module CameraCaptureModule
        caused by: endpoint with name CameraCaptureModule already exists in network azure-iot-edge
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 210
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 127
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 165
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 87
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 115
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 116
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 146
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 157
---> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module CameraCaptureModule: Could not start module CameraCaptureModule
        caused by: Could not start module CameraCaptureModule
        caused by: endpoint with name CameraCaptureModule already exists in network azure-iot-edge, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 210
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 127
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 165
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 87<---
 

```
</details>

**Comment by ancaantochi** [comment]
@keesschollaart81, before the error when starting the module is iotedged reinstalled or is the device rebooted?

If you inspect the network does it contain CameraCaptureModule?

`docker network inspect azure-iot-edge`

On the devices where even a reboot doesn't fix the issue can you please try this workaround: 

`docker network disconnect -f azure-iot-edge CameraCaptureModule`

**Comment by keesschollaart81** [comment]
The output of `docker network inspect azure-iot-edge`:
```
[
    {
        "Name": "azure-iot-edge",
        "Id": "9fb82144cd4a2f80*******367b5a39292cce5777",
        "Created": "2020-02-21T10:16:46.332286754Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0af3ff3c17c50ac99*****30aeb5de8b8fc2c9a1f8": {
                "Name": "metricscollector",
                "EndpointID": "b2b0ecca003f9bd23057228*****d848dc0d4ce163ce5c326",
                "MacAddress": "**:**:0a:00:01:03",
                "IPv4Address": "10.0.1.3/24",
                "IPv6Address": ""
            },
            "1c519a1fd247263aa371*****8d1c1c814dc181fc374e7": {
                "Name": "AiModule",
                "EndpointID": "0106008da8032d****5ae7488b581feaa214",
                "MacAddress": "**:**:0a:00:01:07",
                "IPv4Address": "10.0.1.7/24",
                "IPv6Address": ""
            },
            "38b260bf2e6a160129f******cc67e03c9c73427aeaa565f6e": {
                "Name": "AlarmModule",
                "EndpointID": "63d38f9987043b4bb32a969ee9311e7d9e9283978e48abc223cf4980575b8c53",
                "MacAddress": "**:**:0a:00:01:08",
                "IPv4Address": "10.0.1.8/24",
                "IPv6Address": ""
            },
            "3b4a2da2e18180324105b***e798c741f237658095a2b29ea7ab2": {
                "Name": "edgeHub",
                "EndpointID": "bd3c45c6e28016f6***42a618b85cc9a89eb5432a0c",
                "MacAddress": "**:*:0a:00:01:04",
                "IPv4Address": "10.0.1.4/24",
                "IPv6Address": ""
            },
            "781e030029fa4a7db78eaadcf871b57f5b767c1e6846c0e7c15b8da6bf3a3e6e": {
                "Name": "MdModule",
                "EndpointID": "2c8b655400ecb5aeffe83cbcbb2a8c566576da0b0e564ab3fbfc123ae2826575",
                "MacAddress": "02:42:0a:00:01:06",
                "IPv4Address": "10.0.1.6/24",
                "IPv6Address": ""
            },
            "8d51403c979d61dc118e6a****175b0dc5d776a5f0b8": {
                "Name": "TgModule",
                "EndpointID": "c63f6fb3736495f2a1e8***d04bbfaed8b5a18a480b",
                "MacAddress": "**:**:0a:00:01:02",
                "IPv4Address": "10.0.1.2/24",
                "IPv6Address": ""
            },
            "bdbc45865f5ef514a178******81b7a71504d7f53db2": {
                "Name": "CameraCaptureModule",
                "EndpointID": "73dc30c9997b0004dc3****64c7a382a393cbb6a",
                "MacAddress": "**:**:0a:00:01:09",
                "IPv4Address": "10.0.1.9/24",
                "IPv6Address": ""
            },
            "bf8a930995f3678*****76a3a95b663e768": {
                "Name": "azureblobstorageoniotedge",
                "EndpointID": "28aa1230438a049****991b2cdc33e680d334ea8c2",
                "MacAddress": "**:**:0a:00:01:05",
                "IPv4Address": "10.0.1.5/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.name": "br-iotedge0"
        },
        "Labels": {}
    }
]
```

`docker network disconnect -f azure-iot-edge CameraCaptureModule`
Does allow the container to start but then I get logs (in that container) like:

```
2020-07-14 11:14:34,913:DEBUG:asyncio:Using selector: EpollSelector
2020-07-14 11:14:34,914:INFO:__main__:Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0]
2020-07-14 11:14:34,914:INFO:__main__:IoT Hub Client for Python
2020-07-14 11:14:34,918:DEBUG:urllib3.connectionpool:http://localhost:None "GET /trust-bundle?api-version=2019-11-05 HTTP/1.1" 200 1984
2020-07-14 11:14:34,964:DEBUG:urllib3.connectionpool:http://localhost:None "POST /modules/CameraCaptureModule/genid/637275462081665837/sign?api-version=2019-11-05 HTTP/1.1" 200 57
2020-07-14 11:14:34,986:DEBUG:cai_azure.azure_storage_helpers:Making sure container rawimages exists
2020-07-14 11:14:34,994:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): azureblobstorageoniotedge:11002
2020-07-14 11:14:54,927:DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): azureblobstorageoniotedge:11002
2020-07-14 11:15:17,236:DEBUG:urllib3.connectionpool:Starting new HTTP connection (3): azureblobstorageoniotedge:11002
2020-07-14 11:15:57,159:DEBUG:urllib3.connectionpool:Starting new HTTP connection (4): azureblobstorageoniotedge:11002
2020-07-14 11:15:57,160:ERROR:__main__:Unexpected ex when starting camera capture
Traceback (most recent call last):
  File "./main.py", line 28, in main
    hub_manager = HubManager(module_client)
  File "/app/hub_manager.py", line 20, in __init__
    self.camera_capture = CameraCapture(self)
  File "/app/CameraCapture.py", line 41, in __init__
    self.storage.ensure_container(RAW_IMAGES_CONTAINER)
  File "/usr/local/lib/python3.8/dist-packages/cai_azure/azure_storage_helpers.py", line 15, in ensure_container
    self.service_client.create_container(container)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/tracing/decorator.py", line 62, in wrapper_use_tracer
    return func(*args, **kwargs) # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_blob_service_client.py", line 452, in create_container
    container.create_container(
  File "/usr/local/lib/python3.8/dist-packages/azure/core/tracing/decorator.py", line 62, in wrapper_use_tracer
    return func(*args, **kwargs) # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_container_client.py", line 265, in create_container
    return self._client.container.create( # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 100, in create
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 208, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/policies.py", line 543, in send
    raise err
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/policies.py", line 517, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/policies.py", line 318, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 112, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/base_client.py", line 289, in send
    return self._transport.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/transport/_requests_basic.py", line 253, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPConnection object at 0x7ff8187637c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
```
Basically, when the container starts, it fails on it's first try for a outbound HTTP call with a `Temporary failure in name resolution`

However, this happens quite often in a operational environment. New observations seem to connect this event to a deployment. Any idea what could cause this?

**Comment by ancaantochi** [comment]
Is the hostname it tries to connect to resolvable from the host? You can check with: `nslookup <hostname>`

Did you set the DNS server for docker (in daemon.json details [Configure DNS](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device) ) or is the default used by docker (Google’s public DNS server 8.8.8.8)  working from your network?

**Comment by ebertrams** [comment]
@keesschollaart81, did you get a chance to look at the suggestions from ancaantochi? Could you please copy the output here if you re still experiencing an issue? Thanks

**Comment by varunpuranik** [comment]
@keesschollaart81 - you might be running into a docker issue - 
https://github.com/moby/moby/issues/23302
https://stackoverflow.com/questions/43743169/error-response-from-daemon-service-endpoint-with-name

Can you try restarting the docker daemon to see if the issue goes away?

**Comment by ebertrams** [comment]
@keesschollaart81, can we close this issue? Thanks

**Comment by varunpuranik** [comment]
@keesschollaart81 - were you able to try the suggestions above? I will close this issue since we did not hear back from you. Feel free to open a new issue if you run into any more problems with IoT Edge.

**Comment by keesschollaart81** [comment]
Apologies for the late response. I was enjoying some time off 🌞

We're no longer facing this issue. I kept it open to be able to observe the behavior over some time. It turned out to be caused by (or correlated with) a memory leak. One of our modules consumed too much memory. At some point in time the OOM Killer of the host is going to kill random stuff that in some cases resulted in this issue. This ungraceful shutdown of one of the processes gets the network/docker in a faulty state. 

There is probably a way for iot-edge to detect this state and recover from it. It is however an edge case which is very hard to reproduce. I would keep this issue closed unless more people face this. 

For others that run into it end up in this issue, run `grep oom /var/log/kern.log` to see if it has to do with the oom killer...
