### ISSUE TITLE
Module and Edge Hub fail when re-started in offline mode

### ISSUE THREAD

**Issue by adwk67** [Azure/iotedge#320]
I have setup azure iot edge on a raspberry pi device and am testing the sample temperature sensor module. When I take the (registered and running) device offline and then online again (by disconnecting and re-connecting the network cable), the sensor keeps running and the edge module eventually (after about 15-20 minutes) offloads the cached messages to the portal - but when I re-start the registered device when it is offline, neither the sensor nor the edge hub module seem to work at all. I've tried these steps within a 30-40 minute period, so I doubt it has to do with expired certificates. My understanding was that the device needs a cloud connection to be registered, but as long as the certificates are valid, it should be immune to network connectivity if it is re-started for whatever reason. This doesn't seem to be the case with the sample sensor.

## Expected Behavior
On re-start an offline module should continue to process data, which is cached by the edge hub until cloud connectivity is restored.

## Current Behavior
Re-starting an offline device (that was running correctly online a few minutes beforehand) results in error messages in the sensor and edge runtime logs.

## Steps to Reproduce
1. install edge runtime on a raspberry pi and deploy a sample temperature sensor module
2. verify that messages are received in the IoT Hub in the azure portal
3. take the device offline and then re-start it: temperature sensor does not produce any messages

### Device (Host) Operating System
Raspberry Pi running Raspbian

cat /proc/version
Linux version 4.14.62-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1134 SMP Tue Aug 14 17:10:10 BST 2018

### Architecture
arm32

#### iotedged

<6>2018-09-19T11:29:03Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2018-09-19T11:29:03Z [INFO] - Version - 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)
<6>2018-09-19T11:29:03Z [INFO] - Using default configuration
<3>2018-09-19T11:29:03Z [ERR!] - Edge device information is required.
Please update the config.yaml and provide the IoTHub connection information.
See https://aka.ms/iot-edge-configure-linux for more details

I have checked the config.yaml and the connection string is correct (and I get the same output from `iotedged` when everything is running correctly).

#### iotedge list

edgeHub          running          Up an hour       mcr.microsoft.com/azureiotedge-hub:1.0
tempSensor       running          Up an hour       mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent        running          Up an hour       mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

## Logs

When re-starting the device offline the tempSensor logs show:

> Retrying...
Creating ModuleClient failed with exception System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.EnableMethodAsync()
   at Microsoft.Azure.Devices.Client.InternalClient.SetMethodHandlerAsync(String methodName, MethodCallback methodHandler, Object userContext)
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 100
Retrying...
Creating ModuleClient failed with exception System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.EnableMethodAsync()
   at Microsoft.Azure.Devices.Client.InternalClient.SetMethodHandlerAsync(String methodName, MethodCallback methodHandler, Object userContext)
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 100
Retrying...

When I take the device online again, the edgeHub logs show:

> Retrying...
Creating ModuleClient failed with exception System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.EnableMethodAsync()
   at Microsoft.Azure.Devices.Client.InternalClient.SetMethodHandlerAsync(String methodName, MethodCallback methodHandler, Object userContext)
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 100
Retrying...
Creating ModuleClient failed with exception System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.EnableMethodAsync()
   at Microsoft.Azure.Devices.Client.InternalClient.SetMethodHandlerAsync(String methodName, MethodCallback methodHandler, Object userContext)
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 100
Retrying...

Which looks like the same error in both modules.

**Comment by veyalla** [comment]
@adwk67 This is expected behavior. IoT Edge currently only supports [intermittent offline operation](https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-modules#offline-capabilities) which does not include support for device restart when offline. 

However, in our next release we'll add preview support for extended offline which will work as you expect it to.

**Comment by adwk67** [comment]
OK, thank you for the feedback!
