### ISSUE TITLE
Help Needed: Module deployment fails, even when the repository credentials are given in Set Modules blade

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/iotedge#346]
Hi,

I'm trying to deploy an empty module, created from your description given in https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1.

I've pushed the created module image to my private docker repository which is guarded by credentials.

However, when I look in the logs of the deployment, it fails, even when I have given the repository credentials in the portal under "Set Modules" blade:

```bash
pi@raspberrypi:/tmp/iotedge$ iotedge --version
iotedge 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)
pi@raspberrypi:/tmp/iotedge$ service iotedge status
● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset:
   Active: active (running) since Mon 2018-09-24 09:36:13 UTC; 2min 27s ago
     Docs: man:iotedged(8)
 Main PID: 10906 (iotedged)
   CGroup: /system.slice/iotedge.service
           └─10906 /usr/bin/iotedged -c /etc/iotedge/config.yaml

Sep 24 09:38:28 raspberrypi iotedged[10906]: 2018-09-24T09:38:28Z [INFO] - [mgmt
Sep 24 09:38:28 raspberrypi iotedged[10906]: 2018-09-24T09:38:28Z [INFO] - [mgmt
Sep 24 09:38:28 raspberrypi iotedged[10906]: 2018-09-24T09:38:28Z [INFO] - [work
Sep 24 09:38:33 raspberrypi iotedged[10906]: 2018-09-24T09:38:33Z [INFO] - [mgmt
Sep 24 09:38:33 raspberrypi iotedged[10906]: 2018-09-24T09:38:33Z [INFO] - [work
Sep 24 09:38:34 raspberrypi iotedged[10906]: 2018-09-24T09:38:34Z [INFO] - [mgmt
Sep 24 09:38:34 raspberrypi iotedged[10906]: 2018-09-24T09:38:34Z [INFO] - [mgmt
Sep 24 09:38:35 raspberrypi iotedged[10906]: 2018-09-24T09:38:35Z [WARN] - Conta
pi@raspberrypi:/tmp/iotedge$ iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeHub          running          Up a minute      mcr.microsoft.com/azureiotedge-hub:1.0
edgeAgent        running          Up 2 minutes     mcr.microsoft.com/azureiotedge-agent:1.0
pi@raspberrypi:/tmp/iotedge$ iotedge logs edgeAgent --tail 45 -f
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 82
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 114
   at Microsoft.Azure.Devices.Edge.Util.Option`1.ForEach(Action`1 action) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Option.cs:line 135
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 114
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 176
---> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module storage: Container not found, StatusCode:404, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 89
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 82<---

2018-09-24 09:38:36.041 +00:00 [WRN] - Reconcile failed because of the an exception
System.AggregateException: One or more errors occurred. (Error calling Create module storage: Container not found) ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException: Error calling Create module storage: Container not found
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 89
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 82
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 114
   at Microsoft.Azure.Devices.Edge.Util.Option`1.ForEach(Action`1 action) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Option.cs:line 135
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 114
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 176
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 187
---> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module storage: Container not found, StatusCode:404, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 89
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 82<---

2018-09-24 09:38:41.654 +00:00 [INF] - Plan execution started for deployment 5
2018-09-24 09:38:41.656 +00:00 [INF] - Plan execution ended for deployment 5
2018-09-24 09:38:47.557 +00:00 [INF] - Plan execution started for deployment 5
2018-09-24 09:38:47.558 +00:00 [INF] - Plan execution ended for deployment 5
2018-09-24 09:38:52.942 +00:00 [INF] - Plan execution started for deployment 5
2018-09-24 09:38:52.943 +00:00 [INF] - Plan execution ended for deployment 5
2018-09-24 09:38:58.356 +00:00 [INF] - Plan execution started for deployment 5
2018-09-24 09:38:58.357 +00:00 [INF] - Plan execution ended for deployment 5
2018-09-24 09:39:03.775 +00:00 [INF] - Plan execution started for deployment 5
2018-09-24 09:39:03.776 +00:00 [INF] - Plan execution ended for deployment 5
pi@raspberrypi:/tmp/iotedge$ iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeHub          running          Up 16 minutes    mcr.microsoft.com/azureiotedge-hub:1.0
edgeAgent        running          Up 17 minutes    mcr.microsoft.com/azureiotedge-agent:1.0
pi@raspberrypi:/tmp/iotedge$ iotedge logs edgeHub --tail 45 -f

2018-09-24 09:37:43.400 +00:00 [INF] - Installing intermediate certificates.
2018-09-24 09:37:43.611 +00:00 [INF] - Created new message store
2018-09-24 09:37:43.612 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-09-24 09:37:43.616 +00:00 [INF] - Created device scope identities cache
2018-09-24 09:37:43.687 +00:00 [INF] - Starting refresh of device scope identities cache
2018-09-24 09:37:44.341 +00:00 [INF] - Initializing configuration
2018-09-24 09:37:44.480 +00:00 [INF] - New device connection for device hebh-IoT-Edge-Rpi3B/$edgeHub
2018-09-24 09:37:44.774 +00:00 [INF] - Attempting to connect to IoT Hub for client hebh-IoT-Edge-Rpi3B/$edgeHub via AMQP...
2018-09-24 09:37:45.181 +00:00 [INF] - Created cloud proxy for client hebh-IoT-Edge-Rpi3B/$edgeHub via AMQP, with client operation timeout 20000.
2018-09-24 09:37:45.218 +00:00 [INF] - Initialized cloud proxy c12b1cdf-8eb5-48d4-8928-a3dfae82f316 for hebh-IoT-Edge-Rpi3B/$edgeHub
2018-09-24 09:37:45.224 +00:00 [INF] - Created cloud connection for client hebh-IoT-Edge-Rpi3B/$edgeHub
2018-09-24 09:37:45.283 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client hebh-IoT-Edge-Rpi3B/$edgeHub.
2018-09-24 09:37:45.663 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
2018-09-24 09:37:45.873 +00:00 [INF] - Processing subscription Methods for client hebh-IoT-Edge-Rpi3B/$edgeHub.
2018-09-24 09:37:49.471 +00:00 [INF] - Cloud connection for hebh-IoT-Edge-Rpi3B/$edgeHub is True
2018-09-24 09:37:49.525 +00:00 [INF] - Connection status for hebh-IoT-Edge-Rpi3B/$edgeHub changed to ConnectionEstablished
2018-09-24 09:37:49.544 +00:00 [INF] - Exiting disconnected state
2018-09-24 09:37:49.559 +00:00 [INF] - Entering connected state
2018-09-24 09:37:49.574 +00:00 [INF] - Processing subscriptions for client hebh-IoT-Edge-Rpi3B/$edgeHub.
2018-09-24 09:37:49.627 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client hebh-IoT-Edge-Rpi3B/$edgeHub.
2018-09-24 09:37:49.643 +00:00 [INF] - Processing subscription Methods for client hebh-IoT-Edge-Rpi3B/$edgeHub.
2018-09-24 09:37:52.072 +00:00 [INF] - Obtained edge hub config from module twin
2018-09-24 09:37:53.124 +00:00 [INF] - Set the following 1 route(s) in edge hub
2018-09-24 09:37:53.131 +00:00 [INF] - route: FROM /messages/* INTO $upstream
2018-09-24 09:37:53.138 +00:00 [INF] - Updated message store TTL to 7200 seconds
2018-09-24 09:37:53.140 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-09-24 09:37:53.142 +00:00 [INF] - Initialized edge hub configuration
2018-09-24 09:37:53.229 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
2018-09-24 09:37:55.615 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2018-09-24 09:37:55.642 +00:00 [INF] - Starting MQTT head
2018-09-24 09:37:56.071 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-09-24 09:37:56.419 +00:00 [INF] - Starting AMQP head
2018-09-24 09:37:56.795 +00:00 [INF] - Started MQTT head
2018-09-24 09:37:57.183 +00:00 [INF] - Started AMQP head
2018-09-24 09:37:57.198 +00:00 [INF] - Starting HTTP head
2018-09-24 09:37:57.782 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2018-09-24 09:37:57.948 +00:00 [INF] - Creating key {2c934b2e-f955-4e89-8cdb-0cb3bbf191f2} with creation date 2018-09-24 09:37:57Z, activation date 2018-09-24 09:37:57Z, and expiration date 2018-12-23 09:37:57Z.
2018-09-24 09:37:58.026 +00:00 [WRN] - No XML encryptor configured. Key {2c934b2e-f955-4e89-8cdb-0cb3bbf191f2} may be persisted to storage in unencrypted form.
2018-09-24 09:37:58.055 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-2c934b2e-f955-4e89-8cdb-0cb3bbf191f2.xml"'.
2018-09-24 09:38:00.083 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2018-09-24 09:38:00.219 +00:00 [INF] - Started HTTP head
2018-09-24 09:42:53.269 +00:00 [INF] - Reauthenticating connected clients
2018-09-24 09:47:53.232 +00:00 [INF] - Reauthenticating connected clients
2018-09-24 09:52:53.230 +00:00 [INF] - Reauthenticating connected clients
pi@raspberrypi:/tmp/iotedge$ sudo docker image ls
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/azureiotedge-hub     1.0                 c9b30e8a8d13        2 days ago          247MB
mcr.microsoft.com/azureiotedge-agent   1.0                 aeedd41ad3cf        2 days ago          231MB
microsoft/azureiotedge-agent           1.0-preview         fc8adc81efb3        5 months ago        218MB
pi@raspberrypi:/tmp/iotedge$

```

What did I miss?

Help is appreciated.

Thank you.

/Henrik

**Comment by HenrikBach1** [comment]
Dooh, I forgot my private cr-address... :/
