### ISSUE TITLE
Temp sensor fails when re-started in offline mode (Version 1.0.2)

### ISSUE THREAD

**Issue by adwk67** [Azure/iotedge#374]
This issue is a followup/update to issue #320 once I had updated the runtime from 1.0 to 1.0.2.

## Expected Behavior

Updating a previously registered device from version 1.0 to 1.0.2 should result in continuous operation when the device is re-started while offline.

## Current Behavior

This *is* the case with the edgeHub and edgeAgent components, but the sample temperature sensor keeps crashing.

![image](https://user-images.githubusercontent.com/1712947/46195521-da9fee80-c304-11e8-95a1-db4fee96d13b.png)

![image](https://user-images.githubusercontent.com/1712947/46195544-ec819180-c304-11e8-9a96-b41e1c014ea4.png)

![image](https://user-images.githubusercontent.com/1712947/46195559-fc00da80-c304-11e8-8ccd-6396bc8263be.png)

Here is the exception from the tempSensor log:-

> Unhandled Exception: System.AggregateException: One or more errors occurred. (Put token failed. status-code: 400, status-description: Unable to authenticate D1NB106_rpi/tempSensor.) ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubException: Put token failed. status-code: 400, status-description: Unable to authenticate D1NB106_rpi/tempSensor.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 99
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 69
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 34

**Comment by veyalla** [comment]
Hi @adwk67, please see the [extended offline docs](https://aka.ms/exofdocs) for info about this capability.

Few things to take note of 
* Capability is not applied to existing edge devices, you have to create a new edge device.
* Capability is not available in IoT Hubs in East US, West Europe regions while in preview.

**Comment by mrohera** [comment]
@adwk67 were able to move ahead? Any other questions we can help answer?

**Comment by adwk67** [comment]
Thank you for the feedback! Is there a roadmap for the release of 1.0.2 in western europe?

**Comment by veyalla** [comment]
@adwk67 yes, definitely! It will be available in the region when the feature becomes generally available in the next few months.
