### ISSUE TITLE
error BouncyCastle.Crypto - access is denied

### ISSUE THREAD

**Issue by franperezlopez** [Azure/iotedge#3769]
## Expected Behavior
edgeHub container does run

## Current Behavior
edgeHub container does not run

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-01-19 07:38:21 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: SuSE 4.8.5-11
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.10 
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.0
* Docker/Moby [run `docker version`]: engine 3.0.7

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/usr/lib/systemd/system/iotedge.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/iotedge.service.d
           └─override.conf
   Active: active (running) since mié 2020-10-21 12:18:35 CEST; 17min ago
     Docs: man:iotedged(8)
 Main PID: 19889 (iotedged)
   Memory: 6.4M
   CGroup: /system.slice/iotedge.service
           └─19889 /usr/bin/iotedged -c /etc/iotedge/config.yaml

oct 21 12:35:32 slxmit121 iotedged[19889]: 2020-10-21T10:35:32Z [INFO] - [mgmt] - - - [2020-10-21 10:35:32.440138481 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 1041 "-" "-" auth_id(-)
oct 21 12:35:36 slxmit121 iotedged[19889]: 2020-10-21T10:35:36Z [INFO] - Checking edge runtime status
oct 21 12:35:36 slxmit121 iotedged[19889]: 2020-10-21T10:35:36Z [INFO] - Edge runtime is running.
oct 21 12:35:37 slxmit121 iotedged[19889]: 2020-10-21T10:35:37Z [INFO] - [mgmt] - - - [2020-10-21 10:35:37.456941849 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 1041 "-" "-" auth_id(-)
oct 21 12:35:42 slxmit121 iotedged[19889]: 2020-10-21T10:35:42Z [INFO] - [mgmt] - - - [2020-10-21 10:35:42.463940271 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 1041 "-" "-" auth_id(-)
oct 21 12:35:47 slxmit121 iotedged[19889]: 2020-10-21T10:35:47Z [INFO] - [mgmt] - - - [2020-10-21 10:35:47.472095236 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 1041 "-" "-" auth_id(-)
oct 21 12:35:52 slxmit121 iotedged[19889]: 2020-10-21T10:35:52Z [INFO] - [mgmt] - - - [2020-10-21 10:35:52.479386201 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 1041 "-" "-" auth_id(-)
oct 21 12:35:57 slxmit121 iotedged[19889]: 2020-10-21T10:35:57Z [INFO] - [mgmt] - - - [2020-10-21 10:35:57.486698004 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 1041 "-" "-" auth_id(-)
oct 21 12:36:02 slxmit121 iotedged[19889]: 2020-10-21T10:36:02Z [INFO] - [mgmt] - - - [2020-10-21 10:36:02.491753350 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 1041 "-" "-" auth_id(-)
oct 21 12:36:07 slxmit121 iotedged[19889]: 2020-10-21T10:36:07Z [INFO] - [mgmt] - - - [2020-10-21 10:36:07.498172744 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 1041 "-" "-" auth_id(-)

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<6> 2020-10-21 10:18:37.947 +00:00 [INF] - Initializing Edge Agent.
<6> 2020-10-21 10:18:38.101 +00:00 [INF] - Version - 1.0.10.35691904 (c6350db898b2bd7abe1d50a340a1b1a91e72127d)
<6> 2020-10-21 10:18:38.102 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-10-21 10:18:38.146 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2020-10-21 10:18:38.270 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:01/19/2021 07:38:21] to Root
<6> 2020-10-21 10:18:38.396 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics
<6> 2020-10-21 10:18:38.551 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2020-10-21 10:18:38.556 +00:00 [INF] - Started operation Get system resources
<6> 2020-10-21 10:18:38.557 +00:00 [INF] - Collecting metadata metrics
<6> 2020-10-21 10:18:38.616 +00:00 [INF] - Set metadata metrics: 1.0.10.35691904 (c6350db898b2bd7abe1d50a340a1b1a91e72127d), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"x86_64","Version":"1.0.10","Provisioning":{"Type":"manual.device_connection_string","DynamicReprovisioning":false},"ServerVersion":"3.0.7","KernelVersion":"3.10.0-514.26.2.el7.x86_64","OperatingSystem":"Red Hat Enterprise Linux Server 7.5 (Maipo)","NumCpus":2,"Virtualized":"yes"}, True
<6> 2020-10-21 10:18:38.633 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2020-10-21 10:18:38.636 +00:00 [INF] - Started operation refresh twin config
<6> 2020-10-21 10:18:38.659 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2020-10-21 10:18:38.945 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2020-10-21 10:18:38.996 +00:00 [INF] - Started operation Metrics Scrape
<6> 2020-10-21 10:18:38.996 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2020-10-21 10:18:39.229 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2020-10-21 10:18:39.229 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2020-10-21 10:18:39.229 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2020-10-21 10:18:39.229 +00:00 [INF] - Registering request handler RestartModule
<6> 2020-10-21 10:18:39.679 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2020-10-21 10:18:39.840 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2020-10-21 10:18:39.956 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 4 and reported properties version 59.
<6> 2020-10-21 10:18:40.428 +00:00 [INF] - Plan execution started for deployment 4
<6> 2020-10-21 10:18:40.451 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module edgeHub]\n  [Start module edgeHub]\n)"
<6> 2020-10-21 10:18:40.458 +00:00 [INF] - Executing command: "Create module edgeHub"
<6> 2020-10-21 10:18:41.112 +00:00 [INF] - Executing command: "Start module edgeHub"
<6> 2020-10-21 10:18:41.472 +00:00 [INF] - Plan execution ended for deployment 4
<6> 2020-10-21 10:18:41.752 +00:00 [INF] - Updated reported properties
<6> 2020-10-21 10:18:46.771 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 10s (05s left).
<6> 2020-10-21 10:18:47.077 +00:00 [INF] - Updated reported properties
<6> 2020-10-21 10:18:52.102 +00:00 [INF] - Plan execution started for deployment 4
<6> 2020-10-21 10:18:52.103 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module edgeHub]\n  [Start module edgeHub]\n  [Saving edgeHub to store]\n)"
<6> 2020-10-21 10:18:52.103 +00:00 [INF] - Executing command: "Stop module edgeHub"
<6> 2020-10-21 10:18:52.117 +00:00 [INF] - Executing command: "Start module edgeHub"
<6> 2020-10-21 10:18:52.478 +00:00 [INF] - Executing command: "Saving edgeHub to store"
<6> 2020-10-21 10:18:52.479 +00:00 [INF] - Plan execution ended for deployment 4
<6> 2020-10-21 10:18:57.518 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 20s (15s left).
<6> 2020-10-21 10:18:57.683 +00:00 [INF] - Updated reported properties
<6> 2020-10-21 10:19:02.702 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 20s (10s left).
<6> 2020-10-21 10:19:07.713 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 20s (05s left).
<6> 2020-10-21 10:19:12.724 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 20s (00s left).

```
</details>

<details>
<summary>edge-hub logs</summary>

```

2020-10-21 10:18:41  Starting Edge Hub
2020-10-21 10:18:41.503 +00:00 Edge Hub Main()
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=0e99375e54769942'. Access is denied.
)
 ---> System.IO.FileLoadException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=0e99375e54769942'. Access is denied.

File name: 'BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=0e99375e54769942'
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.ParseCertificateAndKey(String certificateWithChain, String privateKey)
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.ParseCertificateResponse(ServerCertificateResponse response) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 339
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetServerCertificatesFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId, String edgeHubHostname, DateTime expiration) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 255
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration, ILogger logger) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 54
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 54


   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 33
```
</details>

## Additional Information
server is behind a proxy, but I already set up all steps using the guide at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support. when I executed `iotedge check` there was no error (but some warnings)

**Comment by dylanbronson** [comment]
Do you have any createOptions set that weren't set by default? 
This problem is quite odd, since we would expect to see it for everyone using the edgeHub 1.0.10 container, but we don't

**Comment by franperezlopez** [comment]
I've got the default create options
```
{
  "HostConfig": {
    "PortBindings": {
      "5671/tcp": [
        {
          "HostPort": "5671"
        }
      ],
      "8883/tcp": [
        {
          "HostPort": "8883"
        }
      ],
      "443/tcp": [
        {
          "HostPort": "443"
        }
      ]
    }
  }
}
```

can you explain me what was the cause of the error in the past? Is this something related with validating SSL certificates?

**Comment by dylanbronson** [comment]
I don't think we've had this error in the past. It happens when validating certificate, but it looks like it's happening because it can't grab the BouncyCastle DLL due to some permissions error. 
It could be related to the user that edgeHub is running, since the error is a permissions one. But if your createOptions is clean, it doesn't make sense to me.

Have you removed the docker container? 'docker rm -f edgeHub' Then iotedge will pull a new edgeHub down and restart it fresh

**Comment by franperezlopez** [comment]
I've got same behaviour removing the image with `docker image rm -f mcr.microsoft.com/azureiotedge-hub:1.0`

I can run 
```
docker run -it 086c8ebad958 sh
/usr/bin/dotnet Microsoft.Azure.Devices.Edge.Hub.Service.dll
```

the error is different, but I suppose it's because I lack some environment setup:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'uriString'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration, ILogger logger) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 47
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 54
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 33
```

**Comment by veyalla** [comment]
Please test with the latest supported release and open a new issue if the problem persists.
