### ISSUE TITLE
MESSAGE_TIMEOUT received as result from send_event_to_output

### ISSUE THREAD

**Issue by mridup** [Azure/iotedge#377]
Python module built for Pi3 stretch.
Example module code from temperature sensor built as custom module.
docker image built on Pi and pushed to registry from Pi.
Messages sent to IoT Hub always receives a result of MESSAGE_TIMEOUT

## Steps to Reproduce

1. VSCode generated example python code used as module code
2. Docker image built on Pi3
3. "Set modules" to deploy from portal manually
4. Module starts and gets deployed but fails to send message with "MESSAGE_TIMEOUT"

### Device (Host) Operating System

Raspian Stretch

### Architecture

arm32

### Container Operating System

linux containers

#### iotedged

iotedge 1.0.2

#### Edge Agent

1.0

#### Edge Hub
1.0

#### Docker

18.05.0-ce

## Logs

```
DevPyTempSensor sending 3 messages
IoTHubModuleClient.send_event_to_output accepted message [0] for transmission to IoT Hub.
IoTHubModuleClient.send_event_to_output accepted message [1] for transmission to IoT Hub.
IoTHubModuleClient.send_event_to_output accepted message [2] for transmission to IoT Hub.
IoTHubModuleClient waiting for commands, press Ctrl-C to exit.
Send status: BUSY
Send status: BUSY
Confirmation[0] received for message with result = MESSAGE_TIMEOUT
    Properties: {'temperatureAlert': 'true'}
    Total calls confirmed: 97
Confirmation[1] received for message with result = MESSAGE_TIMEOUT
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 98
Confirmation[2] received for message with result = MESSAGE_TIMEOUT
    Properties: {'temperatureAlert': 'true'}
    Total calls confirmed: 99
Send status: IDLE
Send status: IDLE

```

**Comment by mridup** [comment]
Some more logs from edgeHub. It looks like AMQP is being used, wherease MQTT was specified in code:

"Attempting to connect to IoT Hub for client iotedge-0/PyTempSensor via AMQP"

```
[2018-10-01 09:11:05 +00:00]: Starting Edge Hub
[10/01/2018 09:11:06.132 AM] Edge Hub Main()
2018-10-01 09:11:17.540 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-10-01 09:11:17.892 +00:00 [INF] - Starting Edge Hub
2018-10-01 09:11:17.897 +00:00 [INF] - Version - 1.0.2.16940264 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)
2018-10-01 09:11:17.899 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-10-01 09:11:17.899 +00:00 [INF] - Installing intermediate certificates.
2018-10-01 09:11:18.163 +00:00 [INF] - Created new message store
2018-10-01 09:11:18.163 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-10-01 09:11:18.178 +00:00 [INF] - Created device scope identities cache
2018-10-01 09:11:18.220 +00:00 [INF] - Starting refresh of device scope identities cache
2018-10-01 09:11:18.865 +00:00 [INF] - Initializing configuration
2018-10-01 09:11:18.996 +00:00 [INF] - New device connection for device iotedge-0/$edgeHub
2018-10-01 09:11:19.259 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedge-0/$edgeHub via AMQP...
2018-10-01 09:11:19.607 +00:00 [INF] - Created cloud proxy for client iotedge-0/$edgeHub via AMQP, with client operation timeout 20000.
2018-10-01 09:11:19.639 +00:00 [INF] - Initialized cloud proxy 63d87506-132b-4d1d-b6ea-6a1cdfab0ab0 for iotedge-0/$edgeHub
2018-10-01 09:11:19.645 +00:00 [INF] - Created cloud connection for client iotedge-0/$edgeHub
2018-10-01 09:11:19.694 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iotedge-0/$edgeHub.
2018-10-01 09:11:20.262 +00:00 [INF] - Processing subscription Methods for client iotedge-0/$edgeHub.
2018-10-01 09:11:27.553 +00:00 [INF] - Cloud connection for iotedge-0/$edgeHub is True
2018-10-01 09:11:27.606 +00:00 [INF] - Connection status for iotedge-0/$edgeHub changed to ConnectionEstablished
2018-10-01 09:11:27.613 +00:00 [INF] - Exiting disconnected state
2018-10-01 09:11:27.627 +00:00 [INF] - Entering connected state
2018-10-01 09:11:27.642 +00:00 [INF] - Processing subscriptions for client iotedge-0/$edgeHub.
2018-10-01 09:11:27.696 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iotedge-0/$edgeHub.
2018-10-01 09:11:27.711 +00:00 [INF] - Processing subscription Methods for client iotedge-0/$edgeHub.
2018-10-01 09:11:31.431 +00:00 [INF] - Obtained edge hub config from module twin
2018-10-01 09:11:32.160 +00:00 [INF] - Set the following 1 route(s) in edge hub
2018-10-01 09:11:32.167 +00:00 [INF] - route: FROM /messages/* INTO $upstream
2018-10-01 09:11:32.173 +00:00 [INF] - Updated message store TTL to 7200 seconds
2018-10-01 09:11:32.175 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-10-01 09:11:32.178 +00:00 [INF] - Initialized edge hub configuration
2018-10-01 09:11:32.263 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
2018-10-01 09:11:32.670 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:11:32.774 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2018-10-01 09:11:32.801 +00:00 [INF] - Starting MQTT head
2018-10-01 09:11:33.475 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-10-01 09:11:33.765 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:11:33.820 +00:00 [INF] - Starting AMQP head
2018-10-01 09:11:33.878 +00:00 [INF] - Started MQTT head
2018-10-01 09:11:34.444 +00:00 [INF] - Started AMQP head
2018-10-01 09:11:34.458 +00:00 [INF] - Starting HTTP head
2018-10-01 09:11:35.030 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2018-10-01 09:11:35.594 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:11:37.185 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2018-10-01 09:11:37.318 +00:00 [INF] - Started HTTP head
2018-10-01 09:11:39.338 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:11:41.257 +00:00 [WRN] - Received null device scope result for iotedge-0/PyTempSensor
2018-10-01 09:11:41.536 +00:00 [INF] - Service identity for iotedge-0/PyTempSensor was removed from device scope, dropping client connection.
2018-10-01 09:11:41.621 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedge-0/PyTempSensor via AMQP...
2018-10-01 09:11:41.651 +00:00 [INF] - Created cloud proxy for client iotedge-0/PyTempSensor via AMQP, with client operation timeout 20000.
2018-10-01 09:11:41.651 +00:00 [INF] - Initialized cloud proxy 3bc79209-59f9-495f-b5a7-39ae45dbf667 for iotedge-0/PyTempSensor
2018-10-01 09:11:41.652 +00:00 [INF] - Created cloud connection for client iotedge-0/PyTempSensor
2018-10-01 09:11:41.656 +00:00 [INF] - New cloud connection created for device iotedge-0/PyTempSensor
2018-10-01 09:11:41.767 +00:00 [INF] - New token requested by client iotedge-0/PyTempSensor, but using existing token as it is usable.
2018-10-01 09:11:42.679 +00:00 [INF] - Cloud connection for iotedge-0/PyTempSensor is True
2018-10-01 09:11:42.680 +00:00 [INF] - Connection status for iotedge-0/PyTempSensor changed to ConnectionEstablished
2018-10-01 09:11:42.681 +00:00 [INF] - Processing subscriptions for client iotedge-0/PyTempSensor.
2018-10-01 09:11:42.718 +00:00 [INF] - Authenticated iotedge-0/PyTempSensor with IotHub
2018-10-01 09:11:42.761 +00:00 [INF] - Successfully generated identity for clientId iotedge-0/PyTempSensor and username Mridu-IotHub.azure-devices.net/iotedge-0/PyTempSensor/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.5%20(native%3b%20Linux%3b%20armv7l)
2018-10-01 09:11:42.786 +00:00 [INF] - ClientAuthenticated, iotedge-0/PyTempSensor, 6ac00040
2018-10-01 09:11:43.190 +00:00 [WRN] - Failed to release a message: PooledUnsafeDirectByteBuffer(freed)
DotNetty.Common.Utilities.IllegalReferenceCountException: refCnt: 0, decrement: 1
   at DotNetty.Buffers.AbstractReferenceCountedByteBuffer.Release0(Int32 decrement)
   at DotNetty.Buffers.AbstractReferenceCountedByteBuffer.Release()
   at DotNetty.Common.Utilities.ReferenceCountUtil.Release(Object msg)
   at DotNetty.Common.Utilities.ReferenceCountUtil.SafeRelease(Object msg)
2018-10-01 09:11:43.367 +00:00 [WRN] - Closing connection for device: iotedge-0/PyTempSensor, scope: ExceptionCaught, System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at DotNetty.Buffers.HeapArena.NewChunk(Int32 pageSize, Int32 maxOrder, Int32 pageShifts, Int32 chunkSize)
   at DotNetty.Buffers.PoolArena`1.AllocateNormal(PooledByteBuffer`1 buf, Int32 reqCapacity, Int32 normCapacity)
   at DotNetty.Buffers.PoolArena`1.Allocate(PoolThreadCache`1 cache, PooledByteBuffer`1 buf, Int32 reqCapacity)
   at DotNetty.Buffers.PooledByteBufferAllocator.NewHeapBuffer(Int32 initialCapacity, Int32 maxCapacity)
   at DotNetty.Buffers.AbstractByteBufferAllocator.HeapBuffer(Int32 initialCapacity)
   at DotNetty.Buffers.UnsafeByteBufferUtil.GetBytes(AbstractByteBuffer buf, Byte* addr, Int32 index, Stream output, Int32 length)
   at DotNetty.Buffers.PooledUnsafeDirectByteBuffer.GetBytes(Int32 index, Stream output, Int32 length)
   at DotNetty.Buffers.AbstractByteBuffer.ReadBytes(Stream destination, Int32 length)
   at DotNetty.Handlers.Tls.TlsHandler.Wrap(IChannelHandlerContext context)
   at DotNetty.Handlers.Tls.TlsHandler.Flush(IChannelHandlerContext context)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeFlush0(), 6ac00040
2018-10-01 09:11:43.376 +00:00 [INF] - Disposing MessagingServiceClient for device Id iotedge-0/PyTempSensor because of exception - System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at DotNetty.Buffers.HeapArena.NewChunk(Int32 pageSize, Int32 maxOrder, Int32 pageShifts, Int32 chunkSize)
   at DotNetty.Buffers.PoolArena`1.AllocateNormal(PooledByteBuffer`1 buf, Int32 reqCapacity, Int32 normCapacity)
   at DotNetty.Buffers.PoolArena`1.Allocate(PoolThreadCache`1 cache, PooledByteBuffer`1 buf, Int32 reqCapacity)
   at DotNetty.Buffers.PooledByteBufferAllocator.NewHeapBuffer(Int32 initialCapacity, Int32 maxCapacity)
   at DotNetty.Buffers.AbstractByteBufferAllocator.HeapBuffer(Int32 initialCapacity)
   at DotNetty.Buffers.UnsafeByteBufferUtil.GetBytes(AbstractByteBuffer buf, Byte* addr, Int32 index, Stream output, Int32 length)
   at DotNetty.Buffers.PooledUnsafeDirectByteBuffer.GetBytes(Int32 index, Stream output, Int32 length)
   at DotNetty.Buffers.AbstractByteBuffer.ReadBytes(Stream destination, Int32 length)
   at DotNetty.Handlers.Tls.TlsHandler.Wrap(IChannelHandlerContext context)
   at DotNetty.Handlers.Tls.TlsHandler.Flush(IChannelHandlerContext context)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeFlush0()
2018-10-01 09:11:43.423 +00:00 [INF] - Failed to close IoT Hub Client cleanly., System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.CloseAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 77
   at Microsoft.Azure.Devices.ProtocolGateway.Mqtt.MqttAdapter.CloseServiceConnection(IChannelHandlerContext context, Exception cause, PublishPacket will), 6ac00040
2018-10-01 09:11:47.245 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:12:05.009 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:12:10.339 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 2e0ae07c
2018-10-01 09:12:35.605 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:13:16.376 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 4d22f659
2018-10-01 09:13:31.924 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:14:31.925 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:15:27.313 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 0cfab3c5
2018-10-01 09:15:31.934 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor
2018-10-01 09:16:31.936 +00:00 [WRN] - Could not get an active Iot Hub connection for device iotedge-0/tempSensor

```

**Comment by mridup** [comment]
The main issue was the OOM warning:
```
2018-10-01 09:11:43.190 +00:00 [WRN] - Failed to release a message: PooledUnsafeDirectByteBuffer(freed)
DotNetty.Common.Utilities.IllegalReferenceCountException: refCnt: 0, decrement: 1
   at DotNetty.Buffers.AbstractReferenceCountedByteBuffer.Release0(Int32 decrement)
   at DotNetty.Buffers.AbstractReferenceCountedByteBuffer.Release()
   at DotNetty.Common.Utilities.ReferenceCountUtil.Release(Object msg)
   at DotNetty.Common.Utilities.ReferenceCountUtil.SafeRelease(Object msg)
```

and it is solved by setting the OptimizeForPerformance env variable in edgeHub to 'false'.
reference https://github.com/Azure/iot-edge-v1/issues/475 and
https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#stability-issues-on-resource-constrained-devices

**Comment by mridup** [comment]
Closing issue.
