### ISSUE TITLE
iotedge check not executing

### ISSUE THREAD

**Issue by MET-Sam** [Azure/iotedge#3776]
## Expected Behavior
iotedge check should return a status report

## Current Behavior
iotedge check does not return a status report and needs to be stopped with ctrl-c

## Steps to Reproduce
Install iotedge runtime following the steps here

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?tabs=linux

and here

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manual-provision-symmetric-key?tabs=azure-portal%2Clinux

then enter iotedge check

## Context (Environment)
Virtual machine using Ubuntu 18.04

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
No output provided by iotedge check
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: ??

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.10
* Edge Agent [image tag (e.g. 1.0.0)]: ??
* Edge Hub [image tag (e.g. 1.0.0)]: ??
* Docker/Moby [run `docker version`]: 19.03.6

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

$ iotedge logs edgeAgent
2020-10-22 12:31:25  Starting Edge Agent
2020-10-22 12:31:25  Changing ownership of management socket: /var/run/iotedge/mgmt.sock
2020-10-22 12:31:25.914 +00:00 Edge Agent Main()
<6> 2020-10-22 12:31:26.201 +00:00 [INF] - Initializing Edge Agent.
<6> 2020-10-22 12:31:26.426 +00:00 [INF] - Version - 1.0.10.35691904 (c6350db898b2bd7abe1d50a340a1b1a91e72127d)
<6> 2020-10-22 12:31:26.426 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-10-22 12:31:26.484 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2020-10-22 12:31:26.643 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:01/19/2021 09:39:57] to Root
<6> 2020-10-22 12:31:26.837 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics
<6> 2020-10-22 12:31:27.073 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2020-10-22 12:31:27.080 +00:00 [INF] - Started operation Get system resources
<6> 2020-10-22 12:31:27.083 +00:00 [INF] - Collecting metadata metrics
<6> 2020-10-22 12:31:27.177 +00:00 [INF] - Set metadata metrics: 1.0.10.35691904 (c6350db898b2bd7abe1d50a340a1b1a91e72127d), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"x86_64","Version":"1.0.10","Provisioning":{"Type":"manual.device_connection_string","DynamicReprovisioning":false},"ServerVersion":"19.03.6","KernelVersion":"4.15.0-122-generic","OperatingSystem":"Ubuntu 18.04.5 LTS","NumCpus":2,"Virtualized":"yes"}, True
<6> 2020-10-22 12:31:27.201 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2020-10-22 12:31:27.206 +00:00 [INF] - Started operation refresh twin config
<6> 2020-10-22 12:31:27.235 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2020-10-22 12:31:27.634 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2020-10-22 12:31:27.696 +00:00 [INF] - Started operation Metrics Scrape
<6> 2020-10-22 12:31:27.696 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2020-10-22 12:31:28.002 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2020-10-22 12:31:28.003 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2020-10-22 12:31:28.003 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2020-10-22 12:31:28.003 +00:00 [INF] - Registering request handler RestartModule
<4> 2020-10-22 12:31:33.104 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<6> 2020-10-22 12:31:33.108 +00:00 [INF] - Edge agent config backup file does not exist - /tmp/edgeAgent/backup.json
<4> 2020-10-22 12:31:43.119 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:31:53.119 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:32:03.126 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:32:13.125 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:32:23.125 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:32:33.136 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:32:43.138 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:32:53.139 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:33:03.136 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:33:13.141 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:33:23.145 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2020-10-22 12:33:33.146 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<6> 2020-10-22 12:33:36.990 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<6> 2020-10-22 12:33:38.060 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_WebSocket_Only.
<6> 2020-10-22 12:33:38.199 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2020-10-22 12:33:38.267 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 14.
<6> 2020-10-22 12:33:38.273 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2020-10-22 12:33:38.275 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 336
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__32_0(Twin twin) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 245
<6> 2020-10-22 12:33:38.572 +00:00 [INF] - Updated reported properties
<6> 2020-10-22 13:31:27.207 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-10-22 13:31:27.230 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 15.
<6> 2020-10-22 13:31:27.230 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2020-10-22 13:31:27.230 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 336
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__32_0(Twin twin) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 245
<6> 2020-10-22 13:31:27.232 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-10-22 13:31:27.692 +00:00 [INF] - Starting periodic operation Metrics Scrape...
<6> 2020-10-22 13:31:27.694 +00:00 [INF] - Scraping Metrics
<6> 2020-10-22 13:31:27.700 +00:00 [INF] - Scraping endpoint http://edgeHub:9600/metrics
<6> 2020-10-22 13:31:32.722 +00:00 [INF] - Error scraping endpoint http://edgeHub:9600/metrics - System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.GetUriWithIpAddress(String endpoint) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 63
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 82
<6> 2020-10-22 13:31:32.725 +00:00 [INF] - Scraping endpoint http://edgeAgent:9600/metrics
<6> 2020-10-22 13:31:33.123 +00:00 [INF] - Storing Metrics
<6> 2020-10-22 13:31:33.244 +00:00 [INF] - Scraped and Stored Metrics
<6> 2020-10-22 13:31:33.244 +00:00 [INF] - Successfully completed periodic operation Metrics Scrape
<6> 2020-10-22 14:31:27.228 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-10-22 14:31:27.255 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 15.
<6> 2020-10-22 14:31:27.256 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2020-10-22 14:31:27.257 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 336
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__32_0(Twin twin) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 245
<6> 2020-10-22 14:31:27.270 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-10-22 14:31:27.637 +00:00 [INF] - Starting compaction of stores
<6> 2020-10-22 14:31:27.638 +00:00 [INF] - Starting compaction of store Metrics
<6> 2020-10-22 14:31:27.639 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-10-22 14:31:27.639 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-10-22 14:31:27.640 +00:00 [INF] - Starting compaction of store default
<6> 2020-10-22 14:31:33.240 +00:00 [INF] - Starting periodic operation Metrics Scrape...
<6> 2020-10-22 14:31:33.242 +00:00 [INF] - Scraping Metrics
<6> 2020-10-22 14:31:33.244 +00:00 [INF] - Scraping endpoint http://edgeHub:9600/metrics
<6> 2020-10-22 14:31:38.251 +00:00 [INF] - Error scraping endpoint http://edgeHub:9600/metrics - System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.GetUriWithIpAddress(String endpoint) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 63
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 82
<6> 2020-10-22 14:31:38.251 +00:00 [INF] - Scraping endpoint http://edgeAgent:9600/metrics
<6> 2020-10-22 14:31:38.259 +00:00 [INF] - Storing Metrics
<6> 2020-10-22 14:31:38.262 +00:00 [INF] - Scraped and Stored Metrics
<6> 2020-10-22 14:31:38.262 +00:00 [INF] - Successfully completed periodic operation Metrics Scrape
```
</details>

<details>
<summary>edge-hub logs</summary>

```

$ iotedge logs edgeHub
A module runtime error occurred

```
</details>

## Additional Information
The VM was set up new, because there was reason to believe that that would help to resolve the problem which was already around in the old VM. Furthermore, iotedge check --help does list all the options

**Comment by veyalla** [comment]
I could not repro this.

 Does the VM have restrictions in accessing the internet or connect via proxy? Can you share the logs from iotedged?

**Comment by veyalla** [comment]
Closing since a support ticket was opened for this
