### ISSUE TITLE
Edge Agent restarts every ~30 minutes without any info in log

### ISSUE THREAD

**Issue by Gimly** [Azure/iotedge#3818]
## Expected Behavior
The Edge agent should stay up as long as possible

## Current Behavior
The Edge Agent restarts around every 30 minutes with seemingly no reason. We have that behavior happening on two different installation.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
Difficult to say, we have a standard installation.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 360 days (at 2021-10-22 12:55:09 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its C:\Windows\Temp\edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

17 check(s) succeeded.
3 check(s) raised warnings.
1 check(s) raised errors.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Windows 10 Pro 1809 (17763.1518)
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Windows containers

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.10 (c6350db898b2bd7abe1d50a340a1b1a91e72127d)
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0
* Docker/Moby [run `docker version`]: 19.03.12+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>
https://gist.github.com/Gimly/a31c26d69424aff2c24b64b3dcfbf564
</details>

<details>
<summary>edge-agent logs</summary>
https://gist.github.com/Gimly/8da9b60b48c93eb24ff010c5e0a29dba
</details>

<details>
<summary>edge-hub logs</summary>
https://gist.github.com/Gimly/9ebc45f3f045e7079851de95db55f386
</details>

## Additional Information

This is happening on two different machines with the same host OS.

**Comment by and-rewsmith** [comment]
From the iotedged logs it seems edge agent is exiting with a failing code. The fact that there are no logs here is certainly a bug. I did notice though that your iotedge check has an error with:
```
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
```

Let's try fixing this and seeing if it helps.

**Comment by Gimly** [comment]
@and-rewsmith well, I'd love to fix it, but I think it's a bug with Moby and, looking at what I have found online it's not really fixable on Windows. As far as I understand it's linked to the use of `npipe://` in the moby_runtime URI in the config.yaml.

```yaml
moby_runtime:
  uri: "npipe://./pipe/iotedge_moby_engine"
```

If you have any way to fix it I'd be happy to try.

**Comment by veyalla** [comment]
>As far as I understand it's linked to the use of npipe:// in the moby_runtime URI in the config.yaml 
Are you saying the restart every 30m is linked to use of npipe? Can you point to some information that makes you think this is a bug in Moby?

**Comment by veyalla** [comment]
Also, this failure is unexpected as well, I don't see it on my system:
```<3> 2020-10-27 08:24:18.629 +01:00 [ERR] - Error creating RocksDB store. Falling back to in-memory store.
RocksDbSharp.RocksDbException: IO error: open folder: C:\Windows\Temp\edgeAgent: Access is denied.

   at RocksDbSharp.Native.rocksdb_open_column_families(IntPtr options, String name, Int32 num_column_families, String[] column_family_names, IntPtr[] column_family_options, IntPtr[] column_family_handles)
   at RocksDbSharp.RocksDb.Open(DbOptions options, String path, ColumnFamilies columnFamilies)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Create(IRocksDbOptionsProvider optionsProvider, String path, IEnumerable`1 partitionsList) in C:\agent\_work\9\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage.RocksDb\RocksDbWrapper.cs:line 42
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.DbStoreProvider.Create(IRocksDbOptionsProvider optionsProvider, String path, IEnumerable`1 partitionsList) in C:\agent\_work\9\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage.RocksDb\DbStoreProvider.cs:line 33
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule.<Load>b__19_6(IComponentContext c) in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Service\modules\AgentModule.cs:line 175
<6> 2020-10-27 08:24:18.770 +01:00 [INF] - Started operation Metrics Scrape
```

**Comment by Gimly** [comment]
@veyalla No, sorry, I wasn't very clear, I have read that the  `config.yaml has correct URIs for daemon mgmt endpoint - Error` seems to be linked to the Moby engine, but I can't find the source on this right now, I'll write a comment on that tomorrow morning when I'm on my work computer.

As for the Access is denied I have fixed that in the meantime, it was an issue with the file access to that folder, but it didn't fix the 30 minutes restart issue.

I'm not sure either of those issues are really linked to that restart every 30 minutes issue. In fact, what I can see is that the restart are exactly after 30 minutes, to the second.

**Comment by Gimly** [comment]
@vayalla About the error in the iotedge check, you have already two issues on that subject opened: #3730 and a fresh #3829.

**Comment by veyalla** [comment]
Yes, I’m aware of those and a fix is in the works. However, they seem unrelated to the 30 min restart you’re reporting here which I haven’t been able to repro.

One edgeAgent change we made in 1.0.10 is running it as non-root user. Can you try running it as root user by adding the following JSON in its **createOptions** and see if it makes a difference:

```
{
   “User”: “ContainerAdministrator”
}
```

**Comment by Gimly** [comment]
@veyella We've tried to put set this in the createOptions for the edge agent:

```json
{
  "HostConfig": {
    "Binds": [
      "C:\\Windows\\Temp\\edgeAgent:C:\\Windows\\Temp\\edgeAgent"
    ]
  },
  "User": "ContainerAdministrator"
}
```

But it gave us the following error when doing the `iotedge check --verbose`:

```
× container engine is installed and functional - Error
    Could not communicate with container engine at npipe://./pipe/iotedge_moby_engine.
    Please check your moby-engine installation and ensure the service is running.
        caused by: docker returned exit code: 1, stderr = error during connect: Get http://%2F%2F.%2Fpipe%2Fiotedge_moby_engine/v1.40/version: open //./pipe/iotedge_moby_engine: Accès refusé.
```

**Comment by and-rewsmith** [comment]
@Gimly did you resolve this new iotedge check error?

**Comment by Gimly** [comment]
@and-rewsmith by removing  the parameter and running the provisioning on the server, it removed the error yes.

But the 30 minutes restart is still here.

**Comment by and-rewsmith** [comment]
What do you mean by "running the provisioning on the server"? We have a bug open right now and are working on an RCA/fix. Unfortunately, I don't think there is an easy workaround here. As a mitigation you can downgrade to edge agent 1.0.9 which should be compatible with the 1.0.10 iotedged service.

**Comment by and-rewsmith** [comment]
Actually this issue appears to also affect 1.0.9, so this mitigation won't work.

**Comment by veyalla** [comment]
@Gimly can you also share the output of 

```
docker context create iotedge --docker "host=npipe:////./pipe/iotedge_moby_engine"
docker context use iotedge

docker inspect edgeAgent
```

**Comment by Gimly** [comment]
@veyalla Here's the output of the inspect edgeAgent.

<details>
<summary>inspect edgeAgent output</summary>

```PowerShell
PS H:\> docker context create iotedge --docker "host=npipe:////./pipe/iotedge_moby_engine"
iotedge
Successfully created context "iotedge"
PS H:\> docker context use iotedge
iotedge
Current context is now "iotedge"
PS H:\> docker inspect edgeAgent
[
    {
        "Id": "85f2d407f0b19156ebc4f3fe3db482ff94bf15b9995800a1c66823c1dd1f73e4",
        "Created": "2020-11-03T07:05:41.6842798Z",
        "Path": "dotnet",
        "Args": [
            "Microsoft.Azure.Devices.Edge.Agent.Service.dll"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 6676,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-11-03T07:05:42.8103113Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:6cb1fab78d24c6a829f8ee4bc6458204566ab21ba6d578e3f3743a2b709cc809",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\iotedge-moby\\containers\\85f2d407f0b19156ebc4f3fe3db482ff94bf15b9995800a1c66823c1dd1f73e4\\85f2d407f0b19156ebc4f3fe3db482ff94bf15b9995800a1c66823c1dd1f73e4-json.log",
        "Name": "/edgeAgent",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\Windows\\Temp\\edgeAgent:C:\\Windows\\Temp\\edgeAgent",
                "C:\\ProgramData\\iotedge\\workload:C:\\ProgramData\\iotedge\\workload",
                "C:\\ProgramData\\iotedge\\mgmt:C:\\ProgramData\\iotedge\\mgmt"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\iotedge-moby\\windowsfilter\\85f2d407f0b19156ebc4f3fe3db482ff94bf15b9995800a1c66823c1dd1f73e4"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\windows\\temp\\edgeagent",
                "Destination": "c:\\windows\\temp\\edgeagent",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\iotedge\\workload",
                "Destination": "c:\\programdata\\iotedge\\workload",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\iotedge\\mgmt",
                "Destination": "c:\\programdata\\iotedge\\mgmt",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "85f2d407f0b1",
            "Domainname": "",
            "User": "ContainerUser",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "EdgeDeviceHostName=iotix",
                "IOTEDGE_APIVERSION=2020-07-07",
                "IOTEDGE_AUTHSCHEME=sasToken",
                "IOTEDGE_DEVICEID=RollomaticSA",
                "IOTEDGE_IOTHUBHOSTNAME=IotixHub.azure-devices.net",
                "IOTEDGE_MANAGEMENTURI=unix:///C:/ProgramData/iotedge/mgmt/sock",
                "IOTEDGE_MODULEGENERATIONID=636873044710039952",
                "IOTEDGE_MODULEID=$edgeAgent",
                "IOTEDGE_WORKLOADURI=unix:///C:/ProgramData/iotedge/workload/sock",
                "Mode=iotedged",
                "NetworkId=nat",
                "RuntimeLogLevel=Information",
                "storageFolder=C:\\Windows\\Temp",
                "ASPNETCORE_URLS=http://+:80",
                "DOTNET_RUNNING_IN_CONTAINER=true"
            ],
            "Cmd": [
                "dotnet",
                "Microsoft.Azure.Devices.Edge.Agent.Service.dll"
            ],
            "ArgsEscaped": true,
            "Image": "mcr.microsoft.com/azureiotedge-agent:1.0",
            "Volumes": null,
            "WorkingDir": "C:\\app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "net.azure-devices.edge.create-options": "{\"HostConfig\":{\"Binds\":[\"C:\\\\Windows\\\\Temp\\\\edgeAgent:C:\\\\Windows\\\\Temp\\\\edgeAgent\"]}}",
                "net.azure-devices.edge.env": "{\"storageFolder\":{\"value\":\"C:\\\\Windows\\\\Temp\"}}",
                "net.azure-devices.edge.owner": "Microsoft.Azure.Devices.Edge.Agent"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "85f2d407f0b19156ebc4f3fe3db482ff94bf15b9995800a1c66823c1dd1f73e4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "85f2d407f0b19156ebc4f3fe3db482ff94bf15b9995800a1c66823c1dd1f73e4",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "1dccdf244d1745910063396a6cc38fcd4a111a5cd611a7b0dcef5ef99394b85c",
                    "EndpointID": "8b97e4334c52e28a34ae54fcb0331b6f64a33070fa3b4ded8270afe1be80ef79",
                    "Gateway": "172.31.16.1",
                    "IPAddress": "172.31.16.73",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:cf:6c:ae",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

</details>

@and-rewsmith I meant that I had called "Remove-IotEdge" and then "Deploy-IotEdge" again and "Initialize-IotEdge".

**Comment by veyalla** [comment]
@Gimly ....Thanks for the 'docker inspect' output. I see that "storageFolder=C:\\Windows\\Temp" but

```
 {
                "Type": "bind",
                "Source": "c:\\windows\\temp\\edgeagent",
                "Destination": "c:\\windows\\temp\\edgeagent",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
```

Can you try making these consistent? bind destination should be same as value of `storageFolder`

**Comment by Gimly** [comment]
@veyalla I made both consistent, here's the output of command again:

<details>
<summary>docker inspect edgeAgent</summary>

```
PS C:\Windows\system32> docker inspect edgeAgent
[
    {
        "Id": "4592a20a590ac8bdecf9728fcba6eb09c43613af1f6d2aa4aee9416fa776f0cc",
        "Created": "2020-11-05T07:07:56.6330154Z",
        "Path": "dotnet",
        "Args": [
            "Microsoft.Azure.Devices.Edge.Agent.Service.dll"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 10468,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-11-05T07:07:57.7190169Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:6cb1fab78d24c6a829f8ee4bc6458204566ab21ba6d578e3f3743a2b709cc809",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\iotedge-moby\\containers\\4592a20a590ac8bdecf9728fcba6eb09c43613af1f6d2aa4aee9416fa776f0cc\\4592a20a590ac8bdecf9728fcba6eb09c43613af1f6d2aa4aee9416fa776f0cc-json.log",
        "Name": "/edgeAgent",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\Windows\\Temp\\edgeAgent:C:\\Windows\\Temp",
                "C:\\ProgramData\\iotedge\\workload:C:\\ProgramData\\iotedge\\workload",
                "C:\\ProgramData\\iotedge\\mgmt:C:\\ProgramData\\iotedge\\mgmt"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "3",
                    "max-size": "10m"
                }
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\iotedge-moby\\windowsfilter\\4592a20a590ac8bdecf9728fcba6eb09c43613af1f6d2aa4aee9416fa776f0cc"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\windows\\temp\\edgeagent",
                "Destination": "c:\\windows\\temp",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\iotedge\\workload",
                "Destination": "c:\\programdata\\iotedge\\workload",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\iotedge\\mgmt",
                "Destination": "c:\\programdata\\iotedge\\mgmt",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "4592a20a590a",
            "Domainname": "",
            "User": "ContainerUser",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "EdgeDeviceHostName=iotix",
                "IOTEDGE_APIVERSION=2020-07-07",
                "IOTEDGE_AUTHSCHEME=sasToken",
                "IOTEDGE_DEVICEID=RollomaticSA",
                "IOTEDGE_IOTHUBHOSTNAME=IotixHub.azure-devices.net",
                "IOTEDGE_MANAGEMENTURI=unix:///C:/ProgramData/iotedge/mgmt/sock",
                "IOTEDGE_MODULEGENERATIONID=636873044710039952",
                "IOTEDGE_MODULEID=$edgeAgent",
                "IOTEDGE_WORKLOADURI=unix:///C:/ProgramData/iotedge/workload/sock",
                "Mode=iotedged",
                "NetworkId=nat",
                "RuntimeLogLevel=Information",
                "storageFolder=C:\\Windows\\Temp",
                "ASPNETCORE_URLS=http://+:80",
                "DOTNET_RUNNING_IN_CONTAINER=true"
            ],
            "Cmd": [
                "dotnet",
                "Microsoft.Azure.Devices.Edge.Agent.Service.dll"
            ],
            "ArgsEscaped": true,
            "Image": "mcr.microsoft.com/azureiotedge-agent:1.0",
            "Volumes": null,
            "WorkingDir": "C:\\app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "net.azure-devices.edge.create-options": "{\"HostConfig\":{\"Binds\":[\"C:\\\\Windows\\\\Temp\\\\edgeAgent:C:\\\\Windows\\\\Temp\"]}}",
                "net.azure-devices.edge.env": "{\"storageFolder\":{\"value\":\"C:\\\\Windows\\\\Temp\"}}",
                "net.azure-devices.edge.owner": "Microsoft.Azure.Devices.Edge.Agent"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "4592a20a590ac8bdecf9728fcba6eb09c43613af1f6d2aa4aee9416fa776f0cc",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "4592a20a590ac8bdecf9728fcba6eb09c43613af1f6d2aa4aee9416fa776f0cc",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2fed02a0e63e97b4d320e0a2a7d7d537d7155c2ec2c0e8dd3de47de74af9985d",
                    "EndpointID": "7e916b4edc95010c8a76398dfd39c90352db8ae2f91b1ae8fe03611bf026054e",
                    "Gateway": "172.27.160.1",
                    "IPAddress": "172.27.172.231",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:87:b3:7e",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

</details>

As you can see, the `storageFolder` and `Destination` are now consistent.

Unfortunately, it doesn't fix the issue of the 30 minutes reboot and it doesn't also remove the warning about the Edge Agent's storage directory persistence.

<details>
<summary>iotedge check --verbose</summary>

```
PS C:\Windows\system32> iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 87 days (at 2021-02-01 06:52:47 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its C:\Windows\Temp\edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

17 check(s) succeeded.
3 check(s) raised warnings.
1 check(s) raised errors.
```

</details>

I've also noticed another thing that might be important, I noticed that the registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NDIS\IfTypes\24\IfUsedNetLuidIndices` is still getting higher and higher, which means that resources are not freed. I think it was a known bug that was supposedly fixed in 1.0.10, but we still experience it in our case, could that be linked somehow?

**Comment by and-rewsmith** [comment]
@Gimly Are you running WSL by chance? If so, relevant issue:
https://github.com/docker/for-win/issues/5770

**Comment by Gimly** [comment]
@and-rewsmith We are not using WSL, I think the container host is moby on the version of IoT Edge we are running ?

But the root of the issue was indeed the same, it was a compatibility issue between Docker and the VMWare tools version we were using. Updating the VMWare tools to a version higher than 11.0.6 (we had 11.0.5) fixed the 30 minutes reboot.
