### ISSUE TITLE
No 'libboost-python1.55.0' on resin/rpi-raspbian:stretch image

### ISSUE THREAD

**Issue by ksaye** [Azure/iotedge#391]
When trying to use the stretch docker image in an iot edge module, I get the error message below when trying to use azure-iothub-device-client==1.4.0.

> root@f43074d05975:/# pip install azure-iothub-device-client==1.4.0
> Collecting azure-iothub-device-client==1.4.0
>   Downloading https://files.pythonhosted.org/packages/42/8c/77f9934a4136f393bfa3372126769a24d188670883d4ceb5ac136af43d7a/azure_iothub_device_client-1.4.0-py2-none-linux_armv7l.whl (901kB)
>     100% |████████████████████████████████| 911kB 132kB/s
> Installing collected packages: azure-iothub-device-client
> Successfully installed azure-iothub-device-client-1.4.0
> root@f43074d05975:/# python
> Python 2.7.13 (default, Sep 26 2018, 18:42:22)
> [GCC 6.3.0 20170516] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import iothub_client
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/iothub_client/__init__.py", line 1, in <module>
>     from .iothub_client import *
> ImportError: libboost_python-py27.so.1.55.0: cannot open shared object file: No such file or directory
> >>>

When I attempt to install libboost, I get the following error:
> root@f43074d05975:/# apt install libboost-python1.55.0
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package libboost-python1.55.0
> E: Couldn't find any package by glob 'libboost-python1.55.0'
> E: Couldn't find any package by regex 'libboost-python1.55.0'
> root@f43074d05975:/#

I believe I need the 1.4.0 of the azure-iothub-device-client.  If I use a newer version (1.4.3) I get the following messages in my docker logs of the edge module

> Error: Time:Wed Oct  3 10:06:49 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_recv Line:364 executing HTTP request fails, status=404, response_buffer={"message":"Module not found"}d, 03 1
> Error: Time:Wed Oct  3 10:06:49 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_error Line:343 on_edge_hsm_http_error invoked.  reason=3
> Error: Time:Wed Oct  3 10:06:49 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:send_http_workload_request Line:483 send_request_to_edge_workload failed
> Error: Time:Wed Oct  3 10:06:49 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:hsm_client_http_edge_sign_data Line:576 send_http_workload_request failed
> Error: Time:Wed Oct  3 10:06:49 2018 File:/usr/sdk/src/c/provisioning_client/src/iothub_auth_client.c Func:iothub_device_auth_generate_credentials Line:339 Failure generate hash from tpm.
> Error: Time:Wed Oct  3 10:06:49 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_authorization.c Func:IoTHubClient_Auth_Get_SasToken Line:348 failure getting credentials from device auth module
> Error: Time:Wed Oct  3 10:06:49 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1944 failure getting sas token from IoTHubClient_Auth_Get_SasToken.

OS info
root@f43074d05975:/# uname -a
Linux f43074d05975 4.14.70-v7+ #1144 SMP Tue Sep 18 17:34:46 BST 2018 armv7l GNU/Linux

steps to reproduce the error:

on a Pi run:
1.  docker run -it resin/rpi-raspbian:stretch bash
2.  apt update
3.  apt install python-pip
4.  pip install azure-iothub-device-client==1.4.0
5.  python and type import iothub_client

**Comment by myagley** [comment]
Thanks for the issue report. Getting the correct version of libboost for the python SDK can be tricky. Is it possible to move this issue report over to the python SDK repo here: https://github.com/Azure/azure-iot-sdk-python/issues? They are in a better position to help. Thanks!

**Comment by ksaye** [comment]
@myagley,
  While I agree that this is rooted at the same issue, the challenge is magnified with IoT Edge, as we have limited 'docker images' that we can build IoT Edge modules from.

  Example, the resin/raspberrypi3-python:2.7.13, which the sample IoT Edge module for Python uses can use version 1.4.0 of the azure-iothub-device-client, but can not install TensorFlow, python version issues that do not upgrade.

  the resin/rpi-raspbian:stretch will install TensorFlow, but has the libboost_python-py27.so.1.55.0 issues listed above.

  Is 'azure-iothub-device-client==1.4.3' supported on IoT Edge?  Are there other rpi docker images supported?
