### ISSUE TITLE
iotedge check error: Address not available var/run/iotedge/mgmt.soc

### ISSUE THREAD

**Issue by russell-cooks** [Azure/iotedge#3965]
When running an iotedge check on an Azure VM via the Live Video Analytics set-up script, I received the following error:
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Address not available var/run/iotedge/mgmt.sock)
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Address not available var/run/iotedge/mgmt.sock)

## Expected Behavior
Expected all iotedge checks to pass

## Current Behavior
I received the following the error when completing an "iotedge check"
_× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Address not available var/run/iotedge/mgmt.sock)
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Address not available var/run/iotedge/mgmt.sock)_

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.

1. Run the following command: bash -c "$(curl -sL https://aka.ms/lva-edge/setup-resources-for-samples)" 
2. Select preferred settings for subscription, region, and resource group
3. Run the following command: az iot edge set-modules --hub-name <iot-hub-name> --device-id lva-sample-device --content ~/clouddrive/lva-sample/edge-deployment/deployment.amd64.json with the your iot-hub-name
4. Connect to the created Azure VM
5. Run the following command: sudo iotedge check --verbose

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Address not available var/run/iotedge/mgmt.sock)
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Address not available var/run/iotedge/mgmt.sock)
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.10.1 but 1.0.10.2 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-02-10 17:34:42 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warnin
g
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
6 check(s) raised warnings.
1 check(s) raised errors.
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu 18.04.5
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.10.1
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0
* Docker/Moby [run `docker version`]: 19.03.13+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```
Check link in Additional Information
```
</details>

<details>
<summary>edge-agent logs</summary>

```
2020-11-12 17:34:51  Starting Edge Agent
2020-11-12 17:34:51  Changing ownership of management socket: /var/run/iotedge/mgmt.sock
2020-11-12 17:34:51.617 +00:00 Edge Agent Main()
<6> 2020-11-12 17:34:51.802 +00:00 [INF] - Initializing Edge Agent.
<6> 2020-11-12 17:34:51.975 +00:00 [INF] - Version - 1.0.10.1.36505953 (3b3dfcc099921bc2e36d005b49df551b1c5211c0)
<6> 2020-11-12 17:34:51.976 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-11-12 17:34:52.024 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2020-11-12 17:34:52.149 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:02/10/2021 17:34:42] to Root
<6> 2020-11-12 17:34:52.297 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics
<6> 2020-11-12 17:34:52.465 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2020-11-12 17:34:52.470 +00:00 [INF] - Started operation Get system resources
<6> 2020-11-12 17:34:52.472 +00:00 [INF] - Collecting metadata metrics
<6> 2020-11-12 17:34:52.552 +00:00 [INF] - Set metadata metrics: 1.0.10.1.36505953 (3b3dfcc099921bc2e36d005b49df551b1c5211c0), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"x86_64","Version":"1.0.10.1","Provisioning":{"Type":"manual.device_connection_string","DynamicReprovisioning":false},"ServerVersion":"19.03.13+azure","KernelVersion":"5.4.0-1031-azure","OperatingSystem":"Ubuntu 18.04.5 LTS","NumCpus":4,"Virtualized":"yes"}, True
<6> 2020-11-12 17:34:52.573 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2020-11-12 17:34:52.576 +00:00 [INF] - Started operation refresh twin config
<6> 2020-11-12 17:34:52.595 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2020-11-12 17:34:52.919 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2020-11-12 17:34:52.972 +00:00 [INF] - Started operation Metrics Scrape
<6> 2020-11-12 17:34:52.972 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2020-11-12 17:34:53.209 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2020-11-12 17:34:53.209 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2020-11-12 17:34:53.209 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2020-11-12 17:34:53.209 +00:00 [INF] - Registering request handler RestartModule
<6> 2020-11-12 17:34:53.248 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2020-11-12 17:34:53.335 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2020-11-12 17:34:53.367 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 1.
<6> 2020-11-12 17:34:53.370 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2020-11-12 17:34:53.373 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 358
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__32_0(Twin twin) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 267
<6> 2020-11-12 17:34:53.632 +00:00 [INF] - Updated reported properties
<6> 2020-11-12 18:34:52.574 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-11-12 18:34:52.580 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 2.
<6> 2020-11-12 18:34:52.581 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2020-11-12 18:34:52.581 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 358
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__32_0(Twin twin) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 267
<6> 2020-11-12 18:34:52.581 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-11-12 18:34:52.972 +00:00 [INF] - Starting periodic operation Metrics Scrape...
<6> 2020-11-12 18:34:52.974 +00:00 [INF] - Scraping Metrics
<6> 2020-11-12 18:34:52.978 +00:00 [INF] - Scraping endpoint http://edgeHub:9600/metrics
<6> 2020-11-12 18:34:53.014 +00:00 [INF] - Error scraping endpoint http://edgeHub:9600/metrics - System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name does not resolve
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.GetUriWithIpAddress(String endpoint) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 63
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 82
<6> 2020-11-12 18:34:53.014 +00:00 [INF] - Scraping endpoint http://edgeAgent:9600/metrics
<6> 2020-11-12 18:34:53.220 +00:00 [INF] - Storing Metrics
<6> 2020-11-12 18:34:53.287 +00:00 [INF] - Scraped and Stored Metrics
<6> 2020-11-12 18:34:53.287 +00:00 [INF] - Successfully completed periodic operation Metrics Scrape
<6> 2020-11-12 19:16:57.665 +00:00 [INF] - Plan execution started for deployment 2
<6> 2020-11-12 19:16:57.682 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module rtspsim]\n  [Start module rtspsim]\n)"
<6> 2020-11-12 19:16:57.687 +00:00 [INF] - Executing command: "Create module rtspsim"
<6> 2020-11-12 19:17:01.700 +00:00 [INF] - Executing command: "Start module rtspsim"
<6> 2020-11-12 19:17:02.158 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module edgeHub]\n  [Start module edgeHub]\n)"
<6> 2020-11-12 19:17:02.158 +00:00 [INF] - Executing command: "Create module edgeHub"
<6> 2020-11-12 19:17:04.330 +00:00 [INF] - Executing command: "Start module edgeHub"
<6> 2020-11-12 19:17:04.860 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module lvaEdge]\n  [Start module lvaEdge]\n)"
<6> 2020-11-12 19:17:04.861 +00:00 [INF] - Executing command: "Create module lvaEdge"
<6> 2020-11-12 19:17:27.319 +00:00 [INF] - Executing command: "Start module lvaEdge"
<6> 2020-11-12 19:17:27.765 +00:00 [INF] - Plan execution ended for deployment 2
<6> 2020-11-12 19:17:27.917 +00:00 [INF] - Updated reported properties
<6> 2020-11-12 19:17:33.100 +00:00 [INF] - Updated reported properties
<6> 2020-11-12 19:34:52.580 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-11-12 19:34:52.592 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 2 and reported properties version 4.
<6> 2020-11-12 19:34:52.594 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-11-12 19:34:52.919 +00:00 [INF] - Starting compaction of stores
<6> 2020-11-12 19:34:52.920 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-11-12 19:34:52.921 +00:00 [INF] - Starting compaction of store default
<6> 2020-11-12 19:34:52.921 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-11-12 19:34:52.921 +00:00 [INF] - Starting compaction of store Metrics
<6> 2020-11-12 19:34:53.285 +00:00 [INF] - Starting periodic operation Metrics Scrape...
<6> 2020-11-12 19:34:53.285 +00:00 [INF] - Scraping Metrics
<6> 2020-11-12 19:34:53.285 +00:00 [INF] - Scraping endpoint http://edgeHub:9600/metrics
<6> 2020-11-12 19:34:53.287 +00:00 [INF] - Scraping endpoint http://edgeAgent:9600/metrics
<6> 2020-11-12 19:34:53.313 +00:00 [INF] - Storing Metrics
<6> 2020-11-12 19:34:53.321 +00:00 [INF] - Scraped and Stored Metrics
<6> 2020-11-12 19:34:53.321 +00:00 [INF] - Successfully completed periodic operation Metrics Scrape
```
</details>

<details>
<summary>edge-hub logs</summary>

```
2020-11-12 19:17:04  Starting Edge Hub
2020-11-12 19:17:04.871 +00:00 Edge Hub Main()
<6> 2020-11-12 19:17:05.595 +00:00 [INF] - Installing certificates [CN=iotedged workload ca:02/10/2021 17:34:42],[CN=Test Edge Device CA:02/10/2021 17:34:42],[CN=Test Edge Owner CA:02/10/2021 17:34:42] to Root
<6> 2020-11-12 19:17:05.632 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:02/10/2021 17:34:42] to Root
<6> 2020-11-12 19:17:05.640 +00:00 [INF] - Enabling SSL protocols: Tls, Tls11, Tls12
<6> 2020-11-12 19:17:05.762 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
<6> 2020-11-12 19:17:06.282 +00:00 [INF] - Created persistent store at /tmp/edgeHub
<6> 2020-11-12 19:17:06.321 +00:00 [INF] - Initializing Edge Hub
<6> 2020-11-12 19:17:06.321 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-11-12 19:17:06.323 +00:00 [INF] - Version - 1.0.10.1.36505953 (3b3dfcc099921bc2e36d005b49df551b1c5211c0)
<6> 2020-11-12 19:17:06.323 +00:00 [INF] - OptimizeForPerformance=True
<6> 2020-11-12 19:17:06.323 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2020-11-12 19:17:06.324 +00:00 [INF] - Loaded server certificate with expiration date of "2021-02-10T17:34:42.0000000+00:00"
<6> 2020-11-12 19:17:06.330 +00:00 [INF] - Using Asp Net server for metrics
<6> 2020-11-12 19:17:06.335 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-11-12 19:17:06.340 +00:00 [INF] - Created device scope identities cache
<6> 2020-11-12 19:17:06.350 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2020-11-12 19:17:06.381 +00:00 [INF] - Created new message store
<6> 2020-11-12 19:17:06.451 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2020-11-12 19:17:06.491 +00:00 [INF] - Initialized storing twin manager
<6> 2020-11-12 19:17:06.507 +00:00 [INF] - Initializing configuration
<6> 2020-11-12 19:17:06.522 +00:00 [INF] - New device connection for device lva-sample-device/$edgeHub
<6> 2020-11-12 19:17:06.524 +00:00 [INF] - Client lva-sample-device/$edgeHub connected to edgeHub, processing existing subscriptions.
<6> 2020-11-12 19:17:06.579 +00:00 [INF] - Attempting to connect to IoT Hub for client lva-sample-device/$edgeHub via AMQP...
<6> 2020-11-12 19:17:06.605 +00:00 [INF] - Processing pending subscriptions for lva-sample-device/$edgeHub
<4> 2020-11-12 19:17:06.975 +00:00 [WRN] - Empty edge hub configuration received. Ignoring...
<6> 2020-11-12 19:17:07.098 +00:00 [INF] - Exiting disconnected state
<6> 2020-11-12 19:17:07.116 +00:00 [INF] - Received device connected callback
<6> 2020-11-12 19:17:07.122 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2020-11-12 19:17:07.123 +00:00 [INF] - Processing subscriptions for client lva-sample-device/$edgeHub on device connected to cloud.
<6> 2020-11-12 19:17:07.123 +00:00 [INF] - Skipping lva-sample-device/$edgeHub for subscription processing, as it is currently being processed.
<6> 2020-11-12 19:17:07.130 +00:00 [INF] - Entering connected state
<6> 2020-11-12 19:17:07.133 +00:00 [INF] - Cloud connection for lva-sample-device/$edgeHub is True
<6> 2020-11-12 19:17:07.135 +00:00 [INF] - Connection status for lva-sample-device/$edgeHub changed to ConnectionEstablished
<6> 2020-11-12 19:17:07.136 +00:00 [INF] - Client lva-sample-device/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2020-11-12 19:17:07.136 +00:00 [INF] - Skipping lva-sample-device/$edgeHub for subscription processing, as it is currently being processed.
<6> 2020-11-12 19:17:07.138 +00:00 [INF] - Created cloud proxy for client lva-sample-device/$edgeHub via AMQP, with client operation timeout 20 seconds.
<6> 2020-11-12 19:17:07.141 +00:00 [INF] - Initialized cloud proxy 05d04c95-2467-4b0d-ac66-7f211f0840b9 for lva-sample-device/$edgeHub
<6> 2020-11-12 19:17:07.142 +00:00 [INF] - Created cloud connection for client lva-sample-device/$edgeHub
<6> 2020-11-12 19:17:07.410 +00:00 [INF] - Processing pending subscriptions for lva-sample-device/$edgeHub
<6> 2020-11-12 19:17:07.456 +00:00 [INF] - Updated reported properties for lva-sample-device/$edgeHub
<6> 2020-11-12 19:17:07.605 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2020-11-12 19:17:07.735 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2020-11-12 19:17:07.880 +00:00 [INF] - Set the following 1 route(s) in edge hub
<6> 2020-11-12 19:17:07.880 +00:00 [INF] - LVAToHub: FROM /messages/modules/lvaEdge/outputs/* INTO $upstream
<6> 2020-11-12 19:17:07.881 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2020-11-12 19:17:07.881 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-11-12 19:17:07.888 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2020-11-12 19:17:07.889 +00:00 [INF] - Initialized edge hub configuration
<6> 2020-11-12 19:17:07.896 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2020-11-12 19:17:07.959 +00:00 [INF] - Scheduling server certificate renewal for "2021-02-10T17:32:12.0001077Z".
<6> 2020-11-12 19:17:07.960 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2020-11-12 19:17:07.964 +00:00 [INF] - Starting MQTT head
<6> 2020-11-12 19:17:07.997 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2020-11-12 19:17:08.046 +00:00 [INF] - Starting AMQP head
<6> 2020-11-12 19:17:08.049 +00:00 [INF] - Started MQTT head
<6> 2020-11-12 19:17:08.122 +00:00 [INF] - Started AMQP head
<6> 2020-11-12 19:17:08.124 +00:00 [INF] - Starting HTTP head
<4> 2020-11-12 19:17:08.278 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2020-11-12 19:17:08.285 +00:00 [INF] - Started HTTP head
<6> 2020-11-12 19:17:11.669 +00:00 [INF] - Updated reported properties for lva-sample-device/$edgeHub
<6> 2020-11-12 19:17:28.378 +00:00 [INF] - Request starting HTTP/1.1 GET https://lva-sample-iot-edge-device/$iothub/websocket  
<6> 2020-11-12 19:17:28.402 +00:00 [INF] - Connection established CorrelationId ca407489-e45a-4c29-b22f-ca7b343dcf40
<6> 2020-11-12 19:17:28.694 +00:00 [INF] - New token received on the Cbs link
<6> 2020-11-12 19:17:28.797 +00:00 [INF] - Client lva-sample-device/lvaEdge in device scope authenticated locally.
<6> 2020-11-12 19:17:28.809 +00:00 [INF] - New device connection for device lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.809 +00:00 [INF] - Client lva-sample-device/lvaEdge connected to edgeHub, processing existing subscriptions.
<6> 2020-11-12 19:17:28.814 +00:00 [INF] - Attempting to connect to IoT Hub for client lva-sample-device/lvaEdge via AMQP...
<6> 2020-11-12 19:17:28.819 +00:00 [INF] - Bind device proxy for device lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.820 +00:00 [INF] - Initialized device listener in the AMQP protocol head for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.825 +00:00 [INF] - Opened link Events for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.922 +00:00 [INF] - Cloud connection for lva-sample-device/lvaEdge is True
<6> 2020-11-12 19:17:28.923 +00:00 [INF] - Connection status for lva-sample-device/lvaEdge changed to ConnectionEstablished
<6> 2020-11-12 19:17:28.923 +00:00 [INF] - Client lva-sample-device/lvaEdge connected to cloud, processing existing subscriptions.
<6> 2020-11-12 19:17:28.923 +00:00 [INF] - Skipping lva-sample-device/lvaEdge for subscription processing, as it is currently being processed.
<6> 2020-11-12 19:17:28.923 +00:00 [INF] - Created cloud proxy for client lva-sample-device/lvaEdge via AMQP, with client operation timeout 20 seconds.
<6> 2020-11-12 19:17:28.923 +00:00 [INF] - Initialized cloud proxy a66fd09f-86b8-4c6e-bfc1-c08972a140aa for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.923 +00:00 [INF] - Created cloud connection for client lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.940 +00:00 [INF] - Opened link TwinSending for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.945 +00:00 [INF] - Opened link TwinReceiving for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.945 +00:00 [INF] - Processing pending subscriptions for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:28.966 +00:00 [INF] - Processing pending subscriptions for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:29.115 +00:00 [INF] - Updated reported properties for lva-sample-device/$edgeHub
<6> 2020-11-12 19:17:29.155 +00:00 [INF] - Processing pending subscriptions for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:29.167 +00:00 [INF] - Processing pending subscriptions for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:29.312 +00:00 [INF] - Processing pending subscriptions for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:29.313 +00:00 [INF] - Opened link MethodSending for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:29.315 +00:00 [INF] - Opened link MethodReceiving for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:30.314 +00:00 [INF] - Processing pending subscriptions for lva-sample-device/lvaEdge
<6> 2020-11-12 19:17:34.434 +00:00 [INF] - Updated reported properties for lva-sample-device/lvaEdge
<6> 2020-11-12 19:22:07.907 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-11-12 19:27:07.902 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-11-12 19:32:07.900 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-11-12 19:34:53.289 +00:00 [INF] - Request starting HTTP/1.1 GET http://172.18.0.4:9600/metrics  
<6> 2020-11-12 19:34:53.313 +00:00 [INF] - Request finished in 23.3077ms 200 text/plain; version=0.0.4; charset=utf-8
<6> 2020-11-12 19:37:07.901 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-11-12 19:42:07.895 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
```
</details>

## Additional Information
Link to support_bundle from running "sudo iotedge support-bundle --since 6h"
https://lvasampleacs3nksrz74l2.blob.core.windows.net/support-bundle/support_bundle.zip

**Comment by ancaantochi** [comment]
1.0.10.2 has been released with the fix
