### ISSUE TITLE
Modules fail to connect to edgeHub on 1.2.0 armhf

### ISSUE THREAD

**Issue by lucarv** [Azure/iotedge#4016]
I have upgraded iotedge to RC2. Modules on the edge can't connect to edgeHub. See below:

-->
## Expected Behavior
Modules should start

## Current Behavior
pi@blackpi:~/iiotedge $ iotedge list
NAME             STATUS           DESCRIPTION                 CONFIG
edgeAgent        running          Up 10 minutes               mcr.microsoft.com/azureiotedge-agent:1.2.0-rc1
edgeHub          running          Up 10 minutes               mcr.microsoft.com/azureiotedge-hub:1.2.0-rc1
publisher        failed           Failed (132) 2 minutes ago  mcr.microsoft.com/iotedge/opc-publisher:2.7.199-linux-arm32v7
tagger           failed           Failed (1) 4 minutes ago    lucarv.azurecr.io/appuritagger:0.0.4-arm32v7

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Upgrade an edge with a few modules to RC2

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.2.0~rc1 but 1.0.10.2 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to reference time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 55 days (at 2021-01-19 11:22:39 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ EdgeAgent module can be pulled from upstream - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with upstream AMQP port - OK
√ host can connect to and perform TLS handshake with upstream HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with upstream MQTT port - OK
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK

18 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS [Raspbian]: 
* Architecture [arm32]: 
* Container OS [Linux containers]: 

### Runtime Versions
* iotedged [run `iotedge version`]: iotedge 1.2.0~rc1
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.0-rc2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.0-rc2
* Docker/Moby [run `docker version`]: 
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
pi@blackpi:~/iiotedge $
pi@blackpi:~/iiotedge $ sudo docker version
Client:
 Version:           3.0.13+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
 Built:             Thu May 28 20:41:25 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       77e06fda0c
  Built:            Mon Jun  1 20:22:16 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Logs

<details>
<summary>iotedged logs</summary>

```
pi@blackpi:~/iiotedge $ iotedge logs -f publisher
[09:13:24 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] 0: Module kuman_publisher disconnected due to Bad_Credential - now Disconnected...
[09:13:24 ERR Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Module Host failed to start.
[09:13:24 ERR Root] Error during module execution - restarting!
System.AggregateException: One or more errors occurred. (CONNECT failed: RefusedNotAuthorized)
 ---> Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.CreateAsync(String product, IotHubConnectionStringBuilder cs, String deviceId, String moduleId, ITransportSettings transportSetting, TimeSpan timeout, IRetryPolicy retry, Action onConnectionLost, ILogger logger) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Hub.Module.Client\src\Default\IoTSdkFactory.cs:line 272
   at Microsoft.Azure.IIoT.Utils.Try.Options[T](Func`1[] options)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String productInfo, String version, IProcessControl reset) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Hub.Module.Framework\src\Hosting\ModuleHost.cs:line 169
   at Microsoft.Azure.IIoT.Modules.OpcUa.Publisher.ModuleProcess.RunAsync() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\ModuleProcess.cs:line 106
[09:13:24 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Stopping worker supervisor
[09:13:24 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Worker supervisor successfully stopped
[09:13:24 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Stopping worker supervisor
[09:13:24 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Worker supervisor successfully stopped
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.IIoT.Modules.OpcUa.Publisher.ModuleProcess.RunAsync() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\ModuleProcess.cs:line 126
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Azure.IIoT.Modules.OpcUa.Publisher.Program.Main(String[] args) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\Program.cs:line 47

pi@blackpi:~/iiotedge $ iotedge logs -f tagger
[09:05:45 INF] - currently with 2 Apps Subscribing to Data
/app/app.js:41
        throw err;
        ^

[UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.4:8883 error] {
  transportError: Error: Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.4:8883
      at /app/node_modules/azure-iot-device-mqtt/dist/mqtt.js:235:104
      at constructor._onEnter (/app/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:208:29)
      at constructor.transition (/app/node_modules/machina/lib/machina.js:653:28)
      at constructor.Fsm.<computed> [as transition] (/app/node_modules/machina/lib/machina.js:466:63)
      at /app/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:287:40
      at /app/node_modules/mqtt/lib/client.js:827:11
      at Store.close (/app/node_modules/mqtt/lib/store.js:124:5)
      at /app/node_modules/mqtt/lib/client.js:821:26
      at Store.close (/app/node_modules/mqtt/lib/store.js:124:5)
      at MqttClient.closeStores (/app/node_modules/mqtt/lib/client.js:820:24)
}
```
</details>

<details>
<summary>edge-agent logs</summary>

```

https://pastebin.com/JGy7pyZn

```
</details>

<details>
<summary>edge-hub logs</summary>

```

https://pastebin.com/V44fewJF
```
</details>

## Additional Information
The exact same setup works on a linux box running Ubuntu 18.04

**Comment by richma-ms** [comment]
@lucarv are the publisher/tagger modules trying to connect over MQTT?  I noticed in that you have the new MQTT broker experimental feature enabled, but didn't specify policies to allow any operations.  This would cause all incoming CONNECTs to be denied.

If so, please reference the new MQTT broker documentation to allow the modules to connect/pub/sub as appropriate.
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11

**Comment by lucarv** [comment]
yes i follow the tutorial that you refer to. I tried on a linux box running ubuntu 18.04 and it worked just fine. The exact same set up didn't work on the raspberry pi.

**Comment by richma-ms** [comment]
The EdgeAgent logs provided indicates that there is no MQTT policy set on EdgeHub, the entire mqttBroker section is missing for the EdgeHub module.

`"edgeHub": {
        "status": "running",
        "restartPolicy": "always",
        "version": "",
        "imagePullPolicy": "on-create",
        "type": "docker",
        "settings": {
            "image": "mcr.microsoft.com/azureiotedge-hub:1.2.0-rc1",
            "createOptions": "{\"ExposedPorts\":{\"9600/tcp\":{}},\"HostConfig\":{\"PortBindings\":{\"9600/tcp\":[{\"HostPort\":\"9601\"}],\"443/tcp\":[{\"HostPort\":\"443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"1883/tcp\":[{\"HostPort\":\"1883\"}]}}"
        },
        "env": {
            "experimentalFeatures__mqttBrokerEnabled": {
                "value": "true"
            },
            "experimentalFeatures__enabled": {
                "value": "true"
            }
        }
    }`

Can you copy+paste the deployment manifest for this Edge device from the portal?
