### ISSUE TITLE
DNS cannot resolve edgeAgent

### ISSUE THREAD

**Issue by waitingkuo** [Azure/iotedge#4149]
## Expected Behavior
My modules should be able to ping edgeHub

## Current Behavior
I can ping edgeHub inside the container.
but I cannot ping edgeAgent inside the container (my own module)
```
willy@cam5:~$ sudo docker exec -ti InferenceModule bash
root@f97458e652dc:/app# ping edgeHub
PING edgeHub (172.18.0.7) 56(84) bytes of data.
64 bytes from edgeHub.azure-iot-edge (172.18.0.7): icmp_seq=1 ttl=64 time=0.074 ms
^C
--- edgeHub ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.074/0.074/0.074/0.000 ms

root@f97458e652dc:/app# ping edgeAgent
ping: edgeAgent: Name or service not known
```

## Steps to Reproduce
It happens randomly right after a new deployment. 
Reboot the system can solve this issues

## Context (Environment)
I deployed this templat
[](https://github.com/linkernetworks/azure-intelligent-edge-patterns/blob/develop/factory-ai-vision/EdgeSolution/deployment.cpu.template.json)

### Output of `iotedge check`
```
willy@cam5:~$ sudo iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9.4 but 1.0.10.4 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 83 days (at 2021-03-16 08:10:58 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.
```

### Device Information
* Host OS Ubuntu 18.04: 
* Architecture amd64 
* Container OS Linux containers

### Runtime Versions
* iotedged  1.0.9.4
* Edge Agent [image tag (e.g. 1.0)]: 
* Edge Hub [image tag (e.g. 1.0)]: 
* Docker/Moby
```
willy@cam5:~$ sudo docker version
Client:
 Version:           19.03.12+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        0ed913b885c8919944a2e4c8d0b80a318a8dd48b
 Built:             Wed Jun 17 17:27:03 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       9dc6525e6118a25fab2be322d1914740ea842495
  Built:            Mon Mar 12 00:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7+azure
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:

```
Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>
Please check it, this is strange

```
<6> 2020-12-22 08:11:06.255 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-12-22 08:11:40.403 +00:00 [INF] - Starting periodic operation Metrics Scrape...
<6> 2020-12-22 08:11:40.403 +00:00 [INF] - Scraping Metrics
<6> 2020-12-22 08:11:40.403 +00:00 [INF] - Scraping endpoint http://edgeHub:9600/metrics
<6> 2020-12-22 08:11:40.447 +00:00 [INF] - Error scraping endpoint http://edgeHub:9600/metrics - System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name does not resolve
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.GetUriWithIpAddress(String endpoint) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 59
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 100
<6> 2020-12-22 08:11:40.447 +00:00 [INF] - Scraping endpoint http://edgeAgent:9600/metrics
<6> 2020-12-22 08:11:40.489 +00:00 [INF] - Error scraping endpoint http://edgeAgent:9600/metrics - System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name does not resolve
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.GetUriWithIpAddress(String endpoint) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 59
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 100
<6> 2020-12-22 08:11:40.489 +00:00 [INF] - Storing Metrics
<6> 2020-12-22 08:11:40.489 +00:00 [INF] - Scraped and Stored Metrics
<6> 2020-12-22 08:11:40.489 +00:00 [INF] - Successfully completed periodic operation Metrics Scrape
```

</details>

<details>
<summary>edge-hub logs</summary>

```

<6> 2020-12-22 06:11:48.137 +00:00 [INF] - metrics: FROM /messages/modules/InferenceModule/outputs/metrics INTO $upstream
<6> 2020-12-22 06:11:48.137 +00:00 [INF] - InferenceToLVA: FROM /messages/modules/InferenceModule/outputs/InferenceToLVA INTO BrokeredEndpoint("/modules/lvaEdge/inputs/recordingTrigger")
<6> 2020-12-22 06:11:48.137 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2020-12-22 06:11:48.137 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-12-22 06:11:48.137 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config
<6> 2020-12-22 06:11:48.309 +00:00 [INF] - Updated reported properties for cam5/$edgeHub
<6> 2020-12-22 06:13:36.600 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-12-22 06:15:18.683 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint cam5/lvaEdge/recordingTrigger
<6> 2020-12-22 06:15:18.684 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint cam5/lvaEdge/recordingTrigger and 0 messages from message store.
<6> 2020-12-22 06:15:48.683 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-12-22 06:15:48.683 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.
<6> 2020-12-22 06:16:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 06:21:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 06:26:17.431 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 06:31:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 06:36:17.434 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 06:41:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 06:46:17.430 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 06:46:18.691 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint cam5/lvaEdge/recordingTrigger
<6> 2020-12-22 06:46:18.692 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint cam5/lvaEdge/recordingTrigger and 0 messages from message store.
<6> 2020-12-22 06:46:48.693 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-12-22 06:46:48.693 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.
<6> 2020-12-22 06:51:17.433 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 06:56:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:01:17.433 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:06:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:11:17.433 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:11:48.136 +00:00 [INF] - Starting periodic operation Get EdgeHub config...
<6> 2020-12-22 07:11:48.297 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2020-12-22 07:11:48.298 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2020-12-22 07:11:48.298 +00:00 [INF] - metrics: FROM /messages/modules/InferenceModule/outputs/metrics INTO $upstream
<6> 2020-12-22 07:11:48.298 +00:00 [INF] - InferenceToLVA: FROM /messages/modules/InferenceModule/outputs/InferenceToLVA INTO BrokeredEndpoint("/modules/lvaEdge/inputs/recordingTrigger")
<6> 2020-12-22 07:11:48.298 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2020-12-22 07:11:48.298 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-12-22 07:11:48.298 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config
<6> 2020-12-22 07:11:48.472 +00:00 [INF] - Updated reported properties for cam5/$edgeHub
<6> 2020-12-22 07:13:37.323 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-12-22 07:16:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:17:18.698 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint cam5/lvaEdge/recordingTrigger
<6> 2020-12-22 07:17:18.699 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint cam5/lvaEdge/recordingTrigger and 0 messages from message store.
<6> 2020-12-22 07:17:48.696 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-12-22 07:17:48.696 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.
<6> 2020-12-22 07:21:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:23:33.783 +00:00 [INF] - Obtained edge hub config patch update from module twin
<6> 2020-12-22 07:23:33.875 +00:00 [INF] - Updating edge hub configuration
<6> 2020-12-22 07:23:33.876 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2020-12-22 07:23:33.876 +00:00 [INF] - metrics: FROM /messages/modules/InferenceModule/outputs/metrics INTO $upstream
<6> 2020-12-22 07:23:33.876 +00:00 [INF] - InferenceToLVA: FROM /messages/modules/InferenceModule/outputs/InferenceToLVA INTO BrokeredEndpoint("/modules/lvaEdge/inputs/recordingTrigger")
<6> 2020-12-22 07:23:33.876 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2020-12-22 07:23:33.876 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-12-22 07:23:34.044 +00:00 [INF] - Updated reported properties for cam5/$edgeHub
<6> 2020-12-22 07:26:17.433 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:31:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:36:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:41:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:46:17.433 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:48:18.704 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint cam5/lvaEdge/recordingTrigger
<6> 2020-12-22 07:48:18.704 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint cam5/lvaEdge/recordingTrigger and 0 messages from message store.
<6> 2020-12-22 07:48:48.707 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-12-22 07:48:48.707 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.
<6> 2020-12-22 07:51:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 07:56:17.433 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 08:01:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 08:06:17.432 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of stores
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store DeviceScopeCache
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store checkpoints
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store sessions
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store MetadataStore
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store iothub
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store default
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store messages
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store cam5/lvaEdge/recordingTrigger
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store twins
<6> 2020-12-22 08:11:16.064 +00:00 [INF] - Starting compaction of store EdgeTwin
<6> 2020-12-22 08:11:17.433 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 08:11:48.299 +00:00 [INF] - Starting periodic operation Get EdgeHub config...
<6> 2020-12-22 08:11:48.450 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2020-12-22 08:11:48.451 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2020-12-22 08:11:48.451 +00:00 [INF] - metrics: FROM /messages/modules/InferenceModule/outputs/metrics INTO $upstream
<6> 2020-12-22 08:11:48.451 +00:00 [INF] - InferenceToLVA: FROM /messages/modules/InferenceModule/outputs/InferenceToLVA INTO BrokeredEndpoint("/modules/lvaEdge/inputs/recordingTrigger")
<6> 2020-12-22 08:11:48.451 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2020-12-22 08:11:48.451 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-12-22 08:11:48.451 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config
<6> 2020-12-22 08:11:48.618 +00:00 [INF] - Updated reported properties for cam5/$edgeHub
<6> 2020-12-22 08:13:38.092 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-12-22 08:16:17.434 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-12-22 08:19:18.711 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint cam5/lvaEdge/recordingTrigger
<6> 2020-12-22 08:19:18.711 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint cam5/lvaEdge/recordingTrigger and 0 messages from message store.
<6> 2020-12-22 08:19:48.712 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-12-22 08:19:48.712 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.
<6> 2020-12-22 08:21:17.433 +00:00 [INF] - Entering periodic task to reauthenticate connected clients

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by vadim-kovalyov** [comment]
Hi @waitingkuo, prior to 1.0.10 edgeAgent runs on its own docker network - https://github.com/Azure/iotedge/blob/release/1.0.9/doc/networking.md

Please try to update to the latest version and try again. Here is the updated documentation for 1.0.10 networking - https://github.com/Azure/iotedge/blob/release/1.0.10/doc/networking.md

Please let me know if that helps.

**Comment by vadim-kovalyov** [comment]
Closing this for now. Feel free to reopen if you have any questions.
