### ISSUE TITLE
Exception with SimulatedTemperatureSensor module

### ISSUE THREAD

**Issue by ramakrpr** [Azure/iotedge#4252]
Hi,

I have an Ubuntu 18.0.4 IOT Edge device which is configured with X509 CA Authentication to connect to IOT Hub.
I see that the device is connected to IOT Hub and also see the status of the running modules. I also see from the IOT Edge status that it is using the CA certificates that I had configured to initialize the runtime

IOT Edge check shows no error as well as the journalctl
However, i get the below error when i deploy the SimulatedTemperatorSensor module and it points to TLS Authtentication error.
Error from container logs as below. Any clue on what is causing this trouble causing the container to be in a failed state

Unhandled exception. System.AggregateException: One or more errors occurred. (TLS authentication error.)
 ---> System.Security.Authentication.AuthenticationException: TLS authentication error.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.StreamExtensions.EndAuthenticateAsClient(SslStream sslStream, IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.Transport.TlsTransport.HandleOpenComplete(IAsyncResult result, Boolean syncComplete)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.HandleTransportOpened(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.OnTransportOpened(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at SimulatedTemperatureSensor.Program.<>c__DisplayClass18_0.<<CreateModuleClientAsync>b__1>d.MoveNext() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 296
--- End of stack trace from previous location where exception was thrown ---
   at SimulatedTemperatureSensor.Program.CreateModuleClientAsync(TransportType transportType, ITransientErrorDetectionStrategy transientErrorDetectionStrategy, RetryStrategy retryStrategy) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 272
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 79
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 48

**Comment by davilu** [comment]
Hi @ramakrpr, thanks for reporting the issue. Could you please provide logs for iotedged and edgeHub and which version were used.

**Comment by ramakrpr** [comment]
> Hi @ramakrpr, thanks for reporting the issue. Could you please provide logs for iotedged and edgeHub and which version were used.

Version Used
==========

iotedge/bionic,now 1.0.10.4-1 amd64 [installed]


Logs Attached
============
EgeAgent and Hub logs attached
[edgehublogs.txt](https://github.com/Azure/iotedge/files/5843926/edgehublogs.txt)
[egeagentlogs.txt](https://github.com/Azure/iotedge/files/5843927/egeagentlogs.txt)

**Comment by davilu** [comment]
Hi @ramakrpr  thanks for sharing edge hub and agent logs. Could you please share TemperatureSensor logs as well? Didn't see any device connect to edge hub from the log.

**Comment by ramakrpr** [comment]
@davilu  uploaded logs for sensor
[sensorlogs.txt](https://github.com/Azure/iotedge/files/5856719/sensorlogs.txt)

in the edge hub i can see the device connected and it says:
This device is being authenticated through a CA Certificate.
IoT Edge Runtime Response
200 -- OK

from the edge agent and hub i see that the certificates being used as well :

6> 2021-01-15 19:18:10.381 +00:00 [INF] - Installing certificates [CN=iotedged workload ca:01/13/2023 15:19:51],[CN=Azazdev01dvm01:01/13/2023 15:19:51] to Root
<6> 2021-01-15 19:18:10.419 +00:00 [INF] - Installing certificates [CN=TSE Enterprise Issuing CA2, OU=Group Information Services, O=ABC in Europe, C=NL:06/16/2024 13:33:53] to Root

Note:  i changed the name to ABC for privacy

**Comment by davilu** [comment]
@ramakrpr  Thanks for the details. We'll give you an update shortly.

**Comment by davilu** [comment]
@ramakrpr   I guess it might be caused by remote cert validation failure. You could either add edge device CA cert as trusted cert on your module deployment or [customize `RemoteCertificateValidationCallback`](https://github.com/Azure/azure-iot-sdk-csharp/blob/dc8b430bdf20522b44e7267a4ef0824ab4092b9f/iothub/device/src/Edge/CustomCertificateValidator.cs) in `MqttTransportSettings`.

**Comment by ramakrpr** [comment]
> MqttTransportSettings

how do you do this for a module from the Marketplace. like for the one i am using is the temperaturesensor

**Comment by gordonwang0** [comment]
Hi @ramakrpr,

The TLS cert issue you're encountering probably has something to do with the server certificate used by the edgeHub module. By default, it's located in `/var/lib/iotedge/hsm/certs` and called something like `iotedge-tls<long sequence of characters>.cert.pem`.

Check that this cert is issued by your device CA cert. Also check that your trust bundle contains the certificate chain from your root CA certificate and any intermediate certificates.

It may help to delete all files in `/var/lib/iotedge/hsm/certs` and `/var/lib/iotedge/hsm/cert_keys`, then restart iotedge. This will regenerate the TLS certificate from the configured CA certificate.

**Comment by ramakrpr** [comment]
Hi @gordonwang0 thanks for your response

- I confirm that the Root, Intermediate and Device certificates were added to the trust bundles
- I tried the above steps, but the module still has same issues . Deleted the certs and cert_keys files but no luck

**Comment by gordonwang0** [comment]
Are you able to get SimulatedTemperatureSensor working with test certificates? If you comment out these lines in /etc/iotedge/config.yaml:
```
#certificates:
  #device_ca_cert: "file://..."
  #device_ca_pk: "file:///..."
  #trusted_ca_certs: "file://..."
```
Then restart iotedge. Does temperature sensor work then?

**Comment by ramakrpr** [comment]
thanks @gordonwang0 and @davilu for your support
well i figured out that the device certificate was not meeting the below crieteria - in the document

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2018-06#create-iot-edge-device-identity-certificates

The name passed to the New-CACertsEdgeDevice command should not be the same as the hostname parameter in config.yaml, or the device's ID in IoT Hub.
Which implies that the device CA certificate shound have a different CN. 
It started working for me once i updated to a completely new device CA certificate, with completely different names than the host name and the device id

**Comment by gordonwang0** [comment]
Correct, the device CA cert CN must be different from the Device ID and hostname. The device ID cert CN must match the Device ID in IoT Hub (as well as the DPS registration ID, if you are using that).

What are the CNs and Issuers in each of your trust bundle, device ID, and device CA certs?

**Comment by ramakrpr** [comment]
> Correct, the device CA cert CN must be different from the Device ID and hostname. The device ID cert CN must match the Device ID in IoT Hub (as well as the DPS registration ID, if you are using that).
> 
> What are the CNs and Issuers in each of your trust bundle, device ID, and device CA certs?

@gordonwang0 

I have the certificates below

Root CErt
Intermediate CErt- CN same as root cert
Device id  cert- CN is same as my device id registered in hub
Device ca cert -  I just choose a random CN since I dint see any specific requirement for this CN. Are there any specific criteria here?

I’ve trusted all the above certificates within the device

**Comment by gordonwang0** [comment]
Could you reissue your intermediate cert so that it has a different CN than the root CA cert?

Your trust bundle should contain your intermediate cert followed by the root cert. They must be in that order. No other certs should be in the trust bundle.

For the device CA cert, the random CN is fine. Although it's easier to identify if the CN is something like "<device-name> ca".

**Comment by ramakrpr** [comment]
@gordonwang0 i checked on the intermediate certificate CN, looks like that is not feasible since it is published from the enterprise issuing authority
so, i cleaned up the trust bundles and just added the intermediate first and then the root. No major breakthrough yet

for the verification i get an OK for both below

openssl verify -CAfile Rootcert.pem Intermediate.pem
openssl verify -CAfile Intermediate.pem DeviceCA.pem

**Comment by gordonwang0** [comment]
I see. There's not much more I can suggest without taking a closer look at your certificates. Would you be able to post the trust bundle and device CA certs that you are using?

**Comment by micahl** [comment]
Hi @ramakrpr, if you require further assistance please open a support ticket ([instructions](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request)) with Issue Type = "Technical" and the Service = "IoT Edge".
