### ISSUE TITLE
IoTEdge is not downloading modules and iotedge check command shows port errors

### ISSUE THREAD

**Issue by niravjprabtani** [Azure/iotedge#4272]
We are using IoT edge in one of our windows device. It doesn't install Edge Hub and other modules after initializing IoT Edge and provides port error as mentioned below.

We use DPS for provisioning with HSM (TPM 2.0). We have already opened all needed ports from the firewall and our network but still, it is not downloading the modules except edgeAgent.

## Expected Behavior
It should download edgeAgent, edgeHub, and respective available modules which are mentioned in deployment.json

## Current Behavior
It executes edgeAgent only, and we are getting AMQP port issue while checking **iotedge check**
Ports are 443, 8883, 5671

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the nat network could not connect to **iothubhostname.net**:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the nat network could not connect to **iothubhostname.net**:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the nat network could not connect to **iothubhostname.net**:8883

15 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
4 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Windows 10 Enterprise LTSC (1809)
* Architecture [amd64]: 
* Windows container: 

### Runtime Versions
* aziot-edged [**iotedge 1.0.10.4**]: 
* Edge Agent [**1.0**]: 
* Docker/Moby [**19.03.12+azure**]: 

## Logs

<details>
<summary>edge-agent logs</summary>

```

<6> 2021-01-22 04:22:44.167 -08:00 [INF] - Registering request handler UploadModuleLogs
<6> 2021-01-22 04:22:44.168 -08:00 [INF] - Registering request handler GetModuleLogs
<6> 2021-01-22 04:22:44.168 -08:00 [INF] - Registering request handler UploadSupportBundle
<6> 2021-01-22 04:22:44.168 -08:00 [INF] - Registering request handler RestartModule
<4> 2021-01-22 04:22:49.218 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<6> 2021-01-22 04:22:49.220 -08:00 [INF] - Edge agent config backup file does not exist - C:\Windows\TEMP\edgeAgent\backup.json
<4> 2021-01-22 04:22:59.240 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:23:09.269 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<6> 2021-01-22 04:23:17.168 -08:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2021-01-22 04:23:19.292 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:23:29.305 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:23:39.322 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:23:49.348 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:23:50.582 -08:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) (Transient network error occurred, please retry.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 218
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.<>c__DisplayClass19_1.<<CreateSdkModuleClient>b__2>d.MoveNext() in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.CreateClientWebSocketAsync(Uri websocketUri, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.CreateClientWebSocketTransportAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 218
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.<>c__DisplayClass19_1.<<CreateSdkModuleClient>b__3>d.MoveNext() in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---
<6> 2021-01-22 04:23:50.636 -08:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<4> 2021-01-22 04:23:59.365 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:24:09.399 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:24:19.412 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<6> 2021-01-22 04:24:23.976 -08:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2021-01-22 04:24:29.427 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:24:39.442 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:24:49.445 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:24:57.356 -08:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) (Transient network error occurred, please retry.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 218
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.<>c__DisplayClass19_1.<<CreateSdkModuleClient>b__2>d.MoveNext() in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.CreateClientWebSocketAsync(Uri websocketUri, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.CreateClientWebSocketTransportAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 218
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.<>c__DisplayClass19_1.<<CreateSdkModuleClient>b__3>d.MoveNext() in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---
<4> 2021-01-22 04:24:59.456 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<6> 2021-01-22 04:25:03.740 -08:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<4> 2021-01-22 04:25:09.458 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:25:19.475 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:25:29.488 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<6> 2021-01-22 04:25:37.107 -08:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2021-01-22 04:25:39.497 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:25:49.521 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:25:59.537 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:26:09.566 -08:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<4> 2021-01-22 04:26:10.474 -08:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) (Transient network error occurred, please retry.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.

```
</details>

<details>
<summary>iotedge check</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the nat network could not connect to **iothubhostname.net**:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the nat network could not connect to **iothubhostname.net**:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the nat network could not connect to **iothubhostname.net**:8883

15 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
4 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

## Additional Information
We have opened the outbound port of the firewall and our network is also not blocking any kind of port for the same.
We are not able to find out the exact cause for this issue.

Can you guys please help us, we are in huge trouble due to this ?

I have uploaded all the needed logs and screenshots.
[EdgeAgent.Log](https://github.com/Azure/iotedge/files/5856899/EdgeAgent.Log)

![Firewall](https://user-images.githubusercontent.com/49067519/105511973-92d3db00-5cf6-11eb-93b6-ab090aa74089.JPG)
![IoT Edge Check](https://user-images.githubusercontent.com/49067519/105511978-949d9e80-5cf6-11eb-9be0-c50eefba5bd4.JPG)
![Iot Edge List](https://user-images.githubusercontent.com/49067519/105511992-99625280-5cf6-11eb-85e6-f66e96f92994.JPG)
![Wifi Drivers](https://user-images.githubusercontent.com/49067519/105511994-99fae900-5cf6-11eb-9378-c9db0267ba2c.JPG)

**Comment by davilu** [comment]
@niravjprabtani Thanks for reporting the issue. For the log:
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
It looks like it's not port got blocked but DNS can't resolve the host.
Please check edge configure file at C:\ProgramData\iotedge\config.yaml. There should have `iothub_hostname` or `device_connection_string`. Figure out what is host name and try to ping it to see if DNS could resolve the IP address.

**Comment by niravjprabtani** [comment]
> @niravjprabtani Thanks for reporting the issue. For the log:
> ---> System.Net.Sockets.SocketException (11001): No such host is known.
> It looks like it's not port got blocked but DNS can't resolve the host.
> Please check edge configure file at C:\ProgramData\iotedge\config.yaml. There should have `iothub_hostname` or `device_connection_string`. Figure out what is host name and try to ping it to see if DNS could resolve the IP address.

Hey, Thanks for the response !!

I have checked it already, hostname is correct and we are using tpm authentication and in that scene we have provided correct registrationId and DPSScopeId too.

What can be the issue?

You can check the logs of iotedge check, it says all the configurations are correct

**Comment by niravjprabtani** [comment]
That is quite similar to this one [#226](https://github.com/Azure/iotedge/issues/226)
I have seen many similar threads over here but all of them are stale due to inactivity.

**Comment by niravjprabtani** [comment]
**One more update** 

We have tried two gateways having the same configuration and network. Among of them, one is working fine and one is having the above-mentioned issue.

Can somebody guide, what can be the probable reason for the same in one of the gateway only?

**Comment by davilu** [comment]
@niravjprabtani  There was a solution provided on #226 which is [adding the dns entry in docker `daemon.json`](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file).  Something like:
```
{
    "dns": ["8.8.8.8"]
}
```

**Comment by darobs** [comment]
Hello @niravjprabtani! Expanding on what @davilu wrote, we have a troubleshooting article on DNS issues:

[Edge Agent module reports 'empty config file' and no modules start on the device](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2018-06#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device)

**Comment by davilu** [comment]
@niravjprabtani Do you still have issue to download modules?

**Comment by niravjprabtani** [comment]
> @niravjprabtani Do you still have issue to download modules?

Hi,

No, It is not resolved. I am not sure what is causing the issue.

**Comment by davilu** [comment]
Hi @niravjprabtani could you please run following command to check the environment variables of edge agent?
`docker inspect -f '{{range $index, $value := .Config.Env}}export {{$value}}{{println}}{{end}}' edgeAgent` 

Please compare the results from 2 gateways.

**Comment by niravjprabtani** [comment]
> Hi @niravjprabtani could you please run following command to check the environment variables of edge agent?
> `docker inspect -f '{{range $index, $value := .Config.Env}}export {{$value}}{{println}}{{end}}' edgeAgent`
> 
> Please compare the results from 2 gateways.

Hi davilu,

We have updated daemon.json with dns and it worked. Can you let us know how it makes difference?

Previous daemon

{
	"fixed-cidr" : "172.16.0.0/24"
}

Latest daemon

{
    "dns":["1.1.1.1"],
	"fixed-cidr" : "172.16.0.0/24"
}

We have updated daemon.json as mentioned above, we restarted moby-engine service and it worked.

**Questions**
1. What does it make the difference between both scenarios?
2. Why some of the devices are working fine without dns in daemon.json ?

**Comment by davilu** [comment]
Hi @niravjprabtani, the root cause is described here: [Edge Agent module reports 'empty config file' and no modules start on the device](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2018-06#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device)
```
By default, IoT Edge starts modules in their own isolated container network. The device may be having trouble with DNS name resolution within this private network.
```

**Comment by niravjprabtani** [comment]
> Hi @niravjprabtani, the root cause is described here: [Edge Agent module reports 'empty config file' and no modules start on the device](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2018-06#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device)
> 
> ```
> By default, IoT Edge starts modules in their own isolated container network. The device may be having trouble with DNS name resolution within this private network.
> ```

Thank you !!
