### ISSUE TITLE
discovery module: System.AggregateException

### ISSUE THREAD

**Issue by logg-sar** [Azure/iotedge#4466]
## Expected Behavior
Newly added device should appear in the IOT Hub

## Current Behavior
Discovery doesnt find the device
The "Layered Deployment" is applied but in the connections the /discovers is missing

## Steps to Reproduce
Installed Centos in a clean VM and installed 1.0.10.4
iotedge check says no error
discovery module isnt connected.

Removed 1.0.10.4, purged all container and installed 1.1.0
iotege haves warnings (see below)
discovery module still not connected.

### Output of `iotedge check`
```
 iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 19 days (at 2021-03-15 09:45:52 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

20 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS CentOS 7.9
* Architecture amd64
* Container OS Linux container

### Runtime Versions
* aziot-edged [run `iotedge version`]:  multiple versions
* Edge Agent [image tag (e.g. 1.0.0)]:  matching
* Edge Hub [image tag (e.g. 1.0.0)]:    matching
* Docker/Moby [run `docker version`]: newest
* 

## Logs
```
[13:45:47 INF Root] Stopped prometheus metric server
[13:45:47 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Cancelling all pending requests...
[13:45:47 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Pending requests cancelled...
[13:45:47 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Stopped discovery processor.
[13:45:47 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Connecting all clients to ie-a700-7879ed using MqttOverTcp.
[13:45:47 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Starting discovery processor...
[13:45:48 INF Root] Starting module OpcDiscovery version 2.7.206.36449.
[13:45:48 INF Root] Initiating prometheus at port 9700/metrics
[13:45:48 INF Root] Prometheus metric server started.
[13:45:48 WRN Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Bypassing certificate validation for client.
[13:45:48 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Running in iotedge context.
[13:45:48 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] 0: Module Koebru01_discovery disconnected due to Retry_Expired - now Disconnected...
[13:50:55 ERR Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Module Host failed to start.
[13:50:55 ERR Root] Error during module execution - restarting!
System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.CreateAsync(String product, IotHubConnectionStringBuilder cs, String deviceId, String moduleId, ITransportSettings transportSetting, TimeSpan timeout, IRetryPolicy retry, Action onConnectionLost, ILogger logger) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Hub.Module.Client\src\Default\IoTSdkFactory.cs:line 274
   at Microsoft.Azure.IIoT.Utils.Try.Options[T](Func`1[] options)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String productInfo, String version, IProcessControl reset) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Hub.Module.Framework\src\Hosting\ModuleHost.cs:line 169
   at Microsoft.Azure.IIoT.Modules.Discovery.ModuleProcess.RunAsync() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.Discovery\src\ModuleProcess.cs:line 103
[13:50:55 INF Root] Stopped prometheus metric server
[13:50:55 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Cancelling all pending requests...
[13:50:55 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Pending requests cancelled...
[13:50:55 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Stopped discovery processor.
[13:50:55 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Connecting all clients to ie-a700-7879ed using MqttOverTcp.
[13:50:55 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Starting discovery processor...
[13:50:55 INF Root] Starting module OpcDiscovery version 2.7.206.36449.
[13:50:55 INF Root] Initiating prometheus at port 9700/metrics
[13:50:55 INF Root] Prometheus metric server started.
[13:50:55 WRN Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Bypassing certificate validation for client.
[13:50:55 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Running in iotedge context.
[13:50:55 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] 0: Module Koebru01_discovery disconnected due to Retry_Expired - now Disconnected...

```

## Additional Information

<img width="1650" alt="AzurePortal_IoT_Edge" src="https://user-images.githubusercontent.com/2551814/108870364-57c80e80-75f8-11eb-8c44-08b9eed191b1.png">

**Comment by pmzara** [comment]
@logg-sar Thanks for reporting this issue. We're investigating.

**Comment by pmzara** [comment]
@logg-sar Could you check your DNS configuration? Docker containers might not be getting the right DNS service. Check this doc - https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2018-06#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device

**Comment by logg-sar** [comment]
@pmzara 

my daemon,json looks like this:

```
{
    "dns": ["8.8.8.8"],
    "log-driver": "json-file",
    "log-opts": {
         "max-size": "10m",
         "max-file": "3"
         }
}
```

This should work. Or?

**Comment by logg-sar** [comment]
@pmzara
I´ve tested bit more and - its weird. There seems to be a issue with the hostname.

First - I have to make multiple deployments. So I made a Linux-VM and preinstalled the Packages.
Of course the deployments haves different hostnames. So I changed the hostname, rebooted and occured the issue after starting the services.

If I install the packages without changing the hostname before installing the packages its working!
So I made a new Image, adjusted the hostname first, and wrote a script which installs moby, libiothsm and iotedge and it works.

On one side its working this way - on the other side changing the hostname shouldn´t break the deployment - so its your decision if you to value this as  a bug and look forward to fix it.

**Comment by logg-sar** [comment]
So - we found the reason of this error.

The discovery-Module is connecting to the host via the _internal_ variable IOTEDGE_GATEWAYHOSTNAME.
To have this working the DNS-Server in the Network haves to be set up to use DDNS.
If this isnt configured the connection via IOTEDGE_GATEWAYHOSTNAME wont work.

Workaround: Set - _**inside of the container**_ - the correct values to the /etc/hosts and commit this change.
This will at least work until the local IP is changed.
