### ISSUE TITLE
Setting usePersistentStorage to false causes edgeHub to crash

### ISSUE THREAD

**Issue by stevebus** [Azure/iotedge#456]
If you set the usePersistentStorage environment variable to false, edgeHub crashes with the exception shown in the logs below.  

## Expected Behavior
Edge Hub should keep running, and not persistent messages to disk between routing  (which my customer considers a security risk)

## Current Behavior
if you set the flag in the environment variables section for Edge Hub, it crashes upon start up with the error in the logs below.  If you subsequently either set the variable to true, or remove it (the default is true), then the problem goes away and Edge Hub works as expected.

## Steps to Reproduce
1.   Build Edge device per the instructions (mine happens to be setup as a transparent gateway)
2.  in the azure portal, under Advanced Runtime Configuration, add an environment variable to Edge Hub called usePersistentStorage and set to 'false'
3.  Observe Edge Hub abending, restarting, abending, etc..

I've repo'ed on multiple IoT Edge boxes (one running 1.0.3 and one running 1.0.2)

### Device (Host) Operating System
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

### Architecture
amd64  (a VM in azure)

### Container Operating System
linux

### Runtime Versions

this is 1.0.3, however the same problem occurs in 1.0.2

#### iotedged
iotedge 1.0.3 (1ccb9b0728cd046f89a7d6eb0af000b3cbd7bb6a)

#### Edge Agent
1.0.3

#### Edge Hub
1.0.3

#### Docker
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Mon Jun 25 21:07:53 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   09f5e9d
  Built:        Wed Sep 19 16:55:45 2018
  OS/Arch:      linux/amd64
  Experimental: false

## Logs
Edge Hub logs below...   Edge Agent logs don't know anything interesting other than edgeHub crashing and restarting

Edge Hub logs...

[2018-10-17 20:15:18 : Starting Edge Hub
[10/17/2018 08:15:18.392 PM] Edge Hub Main()
2018-10-17 20:15:20.986 +00:00 [INF] - Using in-memory store
2018-10-17 20:15:21.020 +00:00 [INF] - Starting Edge Hub
2018-10-17 20:15:21.021 +00:00 [INF] - Version - 1.0.3.17521421 (1ccb9b0728cd046f89a7d6eb0af000b3cbd7bb6a)
2018-10-17 20:15:21.021 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-10-17 20:15:21.021 +00:00 [INF] - Installing intermediate certificates.
2018-10-17 20:15:21.070 +00:00 [INF] - Created new message store
2018-10-17 20:15:21.070 +00:00 [INF] - Started task to cleanup processed and stale messages

Unhandled Exception: System.AggregateException: One or more errors occurred. (Access to the path '/EdgeHubIV' is denied.) ---> System.UnauthorizedAccessException: Access to the path '/EdgeHubIV' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.Azure.Devices.Edge.Util.DiskFile.WriteAllAsync(String path, String content) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/DiskFile.cs:line 23
   at Microsoft.Azure.Devices.Edge.Util.Edged.EncryptionProvider.CreateAsync(String storagePath, Uri workloadUri, String edgeletWorkloadApiVersion, String moduleId, String genId, String initializationVectorFileName) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/EncryptionProvider.cs:line 36
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__15_17(String uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 143
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__15_4(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 139
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.GetEncryptedStore(IComponentContext context, String entityName) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 307
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__15_8(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 188
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__16_10(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 172
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__16_11(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 193
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<>c.<<Load>b__16_24>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 341
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__16_27(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 379
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 104
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 32

## Additional Information

Customer is concerned about messages being persisted in Edge Hub unencrypted.  This flag was suggested as a workaround.

**Comment by varunpuranik** [comment]
Thanks for reporting the issue. We will investigate..
