### ISSUE TITLE
Could not create project 

### ISSUE THREAD

**Issue by strowk** [Azure/iotedge#4783]
While following this guide - https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-node-module?view=iotedge-2018-06
 the command `npm install -g yo generator-azure-iot-edge-module` 
failed with this log:

```
3112 warn checkPermissions Missing write access to /usr/local/lib/node_modules/yo
3113 warn checkPermissions Missing write access to /usr/local/lib/node_modules
3114 timing stage:rollbackFailedOptional Completed in 0ms
3115 timing stage:runTopLevelLifecycles Completed in 23634ms
3116 verbose stack Error: EACCES: permission denied, access '/usr/local/lib/node_modules/yo'
3117 verbose cwd /home/tim/concept/azure-iot
3118 verbose Linux 5.8.0-48-generic
3119 verbose argv "/snap/node/3292/bin/node" "/snap/node/3292/bin/npm" "install" "-g" "yo" "generator-azure-iot-edge-module"
3120 verbose node v12.19.0
3121 verbose npm  v6.14.8
3122 error code EACCES
3123 error syscall access
3124 error path /usr/local/lib/node_modules/yo
3125 error errno -13
3126 error Error: EACCES: permission denied, access '/usr/local/lib/node_modules/yo'
3126 error  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/yo'] {
3126 error   errno: -13,
3126 error   code: 'EACCES',
3126 error   syscall: 'access',
3126 error   path: '/usr/local/lib/node_modules/yo'
3126 error }
3127 error The operation was rejected by your operating system.
3127 error It is likely you do not have the permissions to access this file as the current user
3127 error
3127 error If you believe this might be a permissions issue, please double-check the
3127 error permissions of the file and its containing directories, or try running
3127 error the command again as root/Administrator.
3128 verbose exit [ -13, true ]
```

, then I tried running with sudo and got this: 

```
29591 info lifecycle ejs@2.7.4~postinstall: ejs@2.7.4
29592 warn lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/3292/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
29593 verbose lifecycle ejs@2.7.4~postinstall: unsafe-perm in lifecycle false
29594 verbose lifecycle ejs@2.7.4~postinstall: PATH: /snap/node/3292/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/generator-azure-iot-edge-module/node_modules/ejs/node_modules/.bin:/usr/local/lib/node_modules/generator-azure-iot-edge-module/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
29595 verbose lifecycle ejs@2.7.4~postinstall: CWD: /usr/local/lib/node_modules/generator-azure-iot-edge-module/node_modules/ejs
29596 silly lifecycle ejs@2.7.4~postinstall: Args: [ '-c', 'node ./postinstall.js' ]
29597 silly lifecycle ejs@2.7.4~postinstall: Returned: code: 1  signal: null
29598 info lifecycle ejs@2.7.4~postinstall: Failed to exec postinstall script
29599 timing action:postinstall Completed in 139ms
29600 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
29601 timing stage:rollbackFailedOptional Completed in 461ms
29602 timing stage:runTopLevelLifecycles Completed in 77197ms
29603 verbose stack Error: ejs@2.7.4 postinstall: `node ./postinstall.js`
29603 verbose stack Exit status 1
29603 verbose stack     at EventEmitter.<anonymous> (/snap/node/3292/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
29603 verbose stack     at EventEmitter.emit (events.js:314:20)
29603 verbose stack     at ChildProcess.<anonymous> (/snap/node/3292/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
29603 verbose stack     at ChildProcess.emit (events.js:314:20)
29603 verbose stack     at maybeClose (internal/child_process.js:1021:16)
29603 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
29604 verbose pkgid ejs@2.7.4
29605 verbose cwd /home/tim/concept/azure-iot
29606 verbose Linux 5.8.0-48-generic
29607 verbose argv "/snap/node/3292/bin/node" "/snap/node/3292/bin/npm" "install" "-g" "yo" "generator-azure-iot-edge-module"
29608 verbose node v12.19.0
29609 verbose npm  v6.14.8
29610 error code ELIFECYCLE
29611 error errno 1
29612 error ejs@2.7.4 postinstall: `node ./postinstall.js`
29612 error Exit status 1
29613 error Failed at the ejs@2.7.4 postinstall script.
```
then I had to run it like this:
```
 sudo npm install -g yo generator-azure-iot-edge-module --scripts-prepend-node-path=true
```
that worked.

## Expected Behavior
Guide should tell exactly what to run. 

## Current Behavior
Need to figure out how to modify command.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. go to https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-node-module?view=iotedge-2018-06
2. try to install generator

### Device Information
* Host OS: Ubuntu 20.04 
* Architecture: amd64

**Comment by davilu** [comment]
It looks like a document issue deploy node.js module. It requires admin access and extra parameter to run the install yeoman and the generator for Node.js Azure IoT Edge module.
`sudo npm install -g yo generator-azure-iot-edge-module --scripts-prepend-node-path=true`

**Comment by veyalla** [comment]
Please report this issue on https://github.com/microsoft/vscode-azure-iot-edge repo.
