### ISSUE TITLE
Command failed with exit code 1

### ISSUE THREAD

**Issue by strowk** [Azure/iotedge#4784]
After running command `Azure IoT Edge: New IoT Edge solution` from https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-node-module?view=iotedge-2018-06 I've got following: 
```
Node.js Module creation may take about 1 minute.
Executing npx -p yo -p generator-azure-iot-edge-module -- yo azure-iot-edge-module -n "SampleModule" -r str4dev1test.azurecr.io/samplemodule
Error: Please make sure the prerequisites are installed for Node.js module. Error: Command failed with exit code 1. Detail: 
```

## Expected Behavior
No errors

## Current Behavior
`Command failed with exit code 1` without any details.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Run `Azure IoT Edge: New IoT Edge solution` in vscode

### Device Information
* Host OS: Ubuntu 20.04
* Architecture: amd64

## Logs

Under modules folder there is `yarn-error.log` :

```
Arguments: 
  /snap/node/3292/bin/node /snap/node/3292/bin/yarn.js global dir

PATH: 
  /home/tim/.npm/_npx/569543/bin:/home/tim/.local/bin:/home/tim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version: 
  1.22.5

Node version: 
  12.19.0

Platform: 
  linux x64

Trace: 
  Error: EACCES: permission denied, write
      at writeSync (fs.js:679:3)
      at SyncWriteStream._write (internal/fs/sync_write_stream.js:24:3)
      at doWrite (_stream_writable.js:403:12)
      at writeOrBuffer (_stream_writable.js:387:5)
      at SyncWriteStream.Writable.write (_stream_writable.js:318:11)
      at ConsoleReporter._log (/snap/node/3292/lib/cli.js:96770:17)
      at ConsoleReporter.log (/snap/node/3292/lib/cli.js:96758:10)
      at dir (/snap/node/3292/lib/cli.js:36256:14)
      at Object.<anonymous> (/snap/node/3292/lib/cli.js:25940:25)
      at Generator.next (<anonymous>)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

```

**Comment by davilu** [comment]
Another document issue. Seems it requires access to file system. Consider to add `sudo` in the document.

**Comment by veyalla** [comment]
Please report this issue on https://github.com/microsoft/vscode-azure-iot-edge repo
