### ISSUE TITLE
Hierarchy of IoT-edge devices: registry-module "failed"

### ISSUE THREAD

**Issue by TheRealSvc** [Azure/iotedge#4800]
## Expected Behavior
I want to create a hierachy of edge-devices. After that, on the topmost edgehub-device, i would expect all modules to be reported as  "running". 

## Current Behavior
The registry module reports "failed", while the other modules are properly pulled and running. 
So the registry cannot act as a local registry to the downstream edge devices.  

## Steps to Reproduce
[This MS Tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11&tabs=azure-portal). Specific is this:
1.  All modules (including edgeHub and edgeAgent) are in a private ACR 

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot)
----------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ identityd config toml file specifies a valid hostname - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK

Connectivity checks (aziot)
---------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ EdgeAgent module can be pulled from upstream - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
27 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
```
</details>

### Device Information
* Ubuntu 18.04
* amd64
* Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.2.0~rc4
* Edge Agent: 1.2.0-rc4
* Edge Hub:  1.2.0-rc4
* Docker/Moby [run `docker version`]: 

<details>
<summary>Click here</summary>

```
Client:
 Version:           20.10.5+azure
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88966a912ddb365e2d73a4969e700fc458f
 Built:             Tue Mar  2 17:58:58 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5+azure
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a88a11be517d9e8c65c998ff56f774eb4dc
  Built:            Thu Feb 25 06:27:18 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4+azure
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:
```
</details>

## Logs

<details>
<summary>registry logs</summary>

```
goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0xff1820, 0xc0003e98c0, 0xc0004d8000, 0x0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:323 +0x290b
github.com/docker/distribution/registry.NewRegistry(0xff1820, 0xc0003e98c0, 0xc0004d8000, 0xc0004d8000, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:105 +0x1dc
github.com/docker/distribution/registry.glob..func1(0x171ae40, 0xc0004a80f0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:63 +0x187
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x171ae40, 0xc0004a80b0, 0x1, 0x1, 0x171ae40, 0xc0004a80b0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x191
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x171afe0, 0xc000219f88, 0xc000090058)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2f4
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
time="2021-04-07T11:38:53.844032812Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.11.2 instance.id=1d8679fd-c194-452b-991f-50398b65fcbc service=registry version=v2.7.1 
time="2021-04-07T11:38:53.844090456Z" level=info msg="redis not configured" go.version=go1.11.2 instance.id=1d8679fd-c194-452b-991f-50398b65fcbc service=registry version=v2.7.1 
time="2021-04-07T11:38:53.844085684Z" level=info msg="Starting upload purge in 49m0s" go.version=go1.11.2 instance.id=1d8679fd-c194-452b-991f-50398b65fcbc service=registry version=v2.7.1 
time="2021-04-07T11:38:53.855664707Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.11.2 instance.id=1d8679fd-c194-452b-991f-50398b65fcbc service=registry version=v2.7.1 
time="2021-04-07T11:38:53.855811051Z" level=info msg="Starting cached object TTL expiration scheduler..." go.version=go1.11.2 instance.id=1d8679fd-c194-452b-991f-50398b65fcbc service=registry version=v2.7.1 
panic: Get svcsolutionscontainerregistry.azurecr.io/v2/: unsupported protocol scheme ""

```
</details>

<details>
<summary>IoTEdgeAPIProxy logs</summary>

```
2021/04/07 11:32:08 [error] 14#14: *109 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:32:08 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:33:06 [error] 14#14: *110 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:33:06 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:33:06 [error] 14#14: *111 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:33:06 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:34:06 [error] 14#14: *112 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:34:06 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:34:06 [error] 14#14: *113 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:34:06 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:35:07 [error] 14#14: *114 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:35:07 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:35:07 [error] 14#14: *115 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:35:07 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:36:07 [error] 14#14: *116 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:36:07 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:36:07 [error] 14#14: *117 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:36:07 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:37:08 [error] 14#14: *118 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:37:08 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:37:08 [error] 14#14: *119 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:37:08 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:38:06 [error] 14#14: *120 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:38:06 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:38:06 [error] 14#14: *121 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:38:06 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:39:07 [error] 14#14: *122 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:39:07 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:39:07 [error] 14#14: *123 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:39:07 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:40:07 [error] 14#14: *124 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:40:07 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:40:07 [error] 14#14: *125 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:40:07 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:41:07 [error] 14#14: *126 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:41:07 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:41:08 [error] 14#14: *127 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:41:08 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:42:06 [error] 14#14: *128 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/ HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:42:06 +0000] "GET /v2/ HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"
2021/04/07 11:42:06 [error] 14#14: *129 registry could not be resolved (3: Host not found), client: 192.168.0.187, server: , request: "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1", host: "192.168.0.246:8000"
192.168.0.187 - - [07/Apr/2021:11:42:06 +0000] "GET /v2/azureiotedge-agent/manifests/1.2.0-rc4 HTTP/1.1" 502 157 "-" "docker/3.0.13+azure go/go1.13.11 git-commit/77e06fda0c kernel/5.10.17-v7l+ os/linux arch/arm UpstreamClient(edgelet/0.1.0)"

```
</details>
[support_bundle.zip](https://github.com/Azure/iotedge/files/6271694/support_bundle.zip)

**Comment by vadim-kovalyov** [comment]
Hey @TheRealSvc, thanks for trying Nested Edge! And thanks for sharing the support bundle. PLEASE NOTE: you had secrets in the support bundle. Please rotate your ACR and Iothub credentials.

My guess is that you did not specify https:// in front of the registry address. In your top level deployment manifest, section for "registry" module should look like below. If it does not solve the issue, please share your deployment file, but sanitize all secrets before sharing :)

```json
                    "registry": {
                        "version": "1.0",
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "env": {
                            "REGISTRY_PROXY_REMOTEURL": {
                                "value": "https://<redacred>.azurecr.io"
                            },
                            "REGISTRY_PROXY_USERNAME": {
                                "value": "<redacred>"
                            },
                            "REGISTRY_PROXY_PASSWORD": {
                                "value": "<redacred>"
                            }
                        },
                        "settings": {
                            "image": "registry:latest",
                            "createOptions": "{}"
                        }
                    },
```

**Comment by TheRealSvc** [comment]
Hi @vadim-kovalyov ... you were right. Adding  _https://_ in front of REGISTRY_PROXY_REMOTEURL did the trick. The registry works now and all modules are pulled into the lower layer devices.  Although i don't understand why here the _https//_ is necessary while in all other places it's not. Maybe it would help others if that was pointed out in the Tutorial.   Anyways, thank a lot !
