### ISSUE TITLE
Migration of state of edgeHub fails from 1.1 to 1.2. DeviceScopeIdentitiesCache couldn't read value.

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#4828]
## Expected Behavior
EdgeHub module 1.2 should start.

## Current Behavior
```
<6> 2021-04-12 05:34:19.998 +00:00 [INF] - Initializing Edge Hub
<6> 2021-04-12 05:34:19.998 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2021-04-12 05:34:19.999 +00:00 [INF] - Version - 1.2.0.41251928 (27661e55482c30597850f5e7af345814f3e26864)
<6> 2021-04-12 05:34:19.999 +00:00 [INF] - OptimizeForPerformance=True
<6> 2021-04-12 05:34:20.000 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2021-04-12 05:34:20.000 +00:00 [INF] - Loaded server certificate with expiration date of "2021-05-12T05:34:19.0000000+00:00"
<6> 2021-04-12 05:34:20.007 +00:00 [INF] - Using Asp Net server for metrics
<6> 2021-04-12 05:34:20.052 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2021-04-12 05:34:20.052 +00:00 [INF] - Created new message store
<6> 2021-04-12 05:34:20.108 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'parentScopes'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'parentScopes')
   at Microsoft.Azure.Devices.Edge.Util.Preconditions.CheckNotNull[T](T reference, String paramName, String message) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Preconditions.cs:line 47
   at Microsoft.Azure.Devices.Edge.Util.Preconditions.CheckNotNull[T](T reference, String paramName) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Preconditions.cs:line 23
   at Microsoft.Azure.Devices.Edge.Hub.Core.Identity.Service.ServiceIdentity..ctor(String deviceId, String moduleId, String deviceScope, IEnumerable`1 parentScopes, String generationId, IEnumerable`1 capabilities, ServiceAuthentication authentication, ServiceIdentityStatus status) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/service/ServiceIdentity.cs:line 37
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.<>c__DisplayClass42_0.<ReadCacheFromStore>b__0(String key, String value) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 303
   at Microsoft.Azure.Devices.Edge.Storage.EncryptedStore`2.<>c__DisplayClass19_1.<IterateBatch>b__1(String d) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EncryptedStore.cs:line 99
   at Microsoft.Azure.Devices.Edge.Util.Option`1.ForEachAsync(Func`2 action) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Option.cs:line 163
   at Microsoft.Azure.Devices.Edge.Storage.EncryptedStore`2.<>c__DisplayClass19_0.<<IterateBatch>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EncryptedStore.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.ColumnFamilyDbStore.IterateBatch(Action`1 seeker, Int32 batchSize, Func`3 callback, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs:line 156
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 143
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.ReadCacheFromStore(IKeyValueStore`2 encryptedStore) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 306
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.Create(IServiceIdentityHierarchy serviceIdentityHierarchy, IServiceProxy serviceProxy, IKeyValueStore`2 encryptedStorage, TimeSpan refreshRate, TimeSpan refreshDelay) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 77
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__27_15(IComponentContext c) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 326
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__35_10(IComponentContext c) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 244
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__35_14(IComponentContext c) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 312
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__35_27(IComponentContext c) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 496
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__35_30(IComponentContext c) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 555
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 79
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 36
Apr 12 05:34:20.644  INFO watchdog::child: Edge Hub process has stopped
Apr 12 05:34:20.644  INFO watchdog: Successfully stopped Edge Hub process
Apr 12 05:34:20.644  INFO watchdog: Stopped Watchdog process
```

I believe that all relevant information could be retrieved from the callstack. If you need additional information please don't hesitate to ask. Thanks in advance for your assistance.

**Comment by alaendle** [comment]
Btw, the workaround is clear/simple - just stop the edge service, delete the local edgeHub state and restart the edge service.

**Comment by vadim-kovalyov** [comment]
Thanks @alaendle for reporting this. Looks like a legit bug, we'll investigate and fix.
