### ISSUE TITLE
On Simulation my Edge Module work Fine but when i deploy it will be cresh 

### ISSUE THREAD

**Issue by nainesh72** [Azure/iotedge#4845]
Hi
I develop a small module, it work fine on simulation mode on my laptop, but when i deploy in rasbari pi it will show me following 
error 
i send error log please guide me
IoT Hub module client initialized.
Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the path '/app/libplctag.so' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '/app/libplctag.so' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at libplctag.NativeImport.LibraryExtractor.ExtractAppropriateLibraryToDirectory(String outputDirectory)
   at libplctag.NativeImport.LibraryExtractor.Init(Boolean forceExtract)
   at libplctag.NativeImport.plctag.ExtractLibraryIfRequired()
   at libplctag.NativeImport.plctag.plc_tag_create(String lpString, Int32 timeout)
   at libplctag.NativeTag.plc_tag_create(String lpString, Int32 timeout)
   at libplctag.NativeTagWrapper.Initialize()
   at libplctag.Tag.Initialize()
   at libplctag.Tag`2.Read()
   at test1.Program.Init() in /app/Program.cs:line 66
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at test1.Program.Main(String[] args) in /app/Program.cs:line 21
pi@raspberrypi:/bin $

**Comment by nainesh72** [comment]
Hi
I create a module to read plc tag, so  use nugget packet linplctag and libplctag.native, using this i create a module on vs2019, it will run on my pc in simulation mode but when. i deploy on Rabari pi this error is come, my desktop docker is on Linux and I create Linux arm module, if need more detail please let me know 
Thanks
Nainesh

**Comment by lfitchett** [comment]
Hmm, you can try explicitly setting the permissions of the needed library in the docker file. In the "Dockerfile.arm32v7" file, add the following line `RUN chmod 777 /app/libplctag.so`  above `RUN useradd -ms /bin/bash moduleuser`. 

The resulting file should look like:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN chmod 777 /app/libplctag.so

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "CogTest.dll"]
```

**Comment by lfitchett** [comment]
This is assuming you're using arm32. If using arm64, change "Dockerfile.arm64v8" instead

**Comment by nainesh72** [comment]
Hi 
When i add above line it show following error 
![image](https://user-images.githubusercontent.com/50742468/114760082-9343a700-9d24-11eb-81cd-9fe7f8388e56.png)

**Comment by nainesh72** [comment]
Hi
I sapratly copy libplctag.so in my module folder and then i add copy command before Chmod command like this 
![image](https://user-images.githubusercontent.com/50742468/114766818-80cd6b80-9d2c-11eb-8f4d-448100e720f5.png)
now problem solved thanks for support

**Comment by nainesh72** [comment]
Thank for support
