### ISSUE TITLE
DeviceMessageLockLostException when sending telemetry

### ISSUE THREAD

**Issue by niksacdev** [Azure/iotedge#495]
## Expected Behavior
No exception should occur when the message load increases.
## Current Behavior

Hi Guys
I see that this issue has been closed as a warning for C2D scenarios. https://github.com/Azure/iotedge/issues/111
I am getting this exception as well but in a telemetry (D2C) scenario right now where we are pushing around 10K messages from one module on the IoT Edge message pipeline and attempting to read into another custom module.
The error does not show up if the message limits are low but as soon as we start dispatching more messages, these errors show up in the logs.
 
Any thoughts why this would be occurring and should we just suppress it (as mentioned in the issue comments)?
 
Unhandled Exception: Microsoft.Azure.Devices.Client.Exceptions.DeviceMessageLockLostException: Exception of type 'Microsoft.Azure.Devices.Client.Exceptions.DeviceMessageLockLostException' was thrown.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__61_1(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.OnReceiveEventMessageCalled(String input, Message message)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.ProcessReceivedEventMessage(AmqpMessage amqpMessage)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

## Steps to Reproduce

1. Create a Custom Module
2. Run messages over 10K in the message pipeline
3. The custom module crashes with the above exception
4.

### Device (Host) Operating System
Windows Server 1803

### Architecture
amd64

### Container Operating System
Windows containers

#### iotedged

1.0.3

## Logs

 
Unhandled Exception: Microsoft.Azure.Devices.Client.Exceptions.DeviceMessageLockLostException: Exception of type 'Microsoft.Azure.Devices.Client.Exceptions.DeviceMessageLockLostException' was thrown.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__61_1(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.OnReceiveEventMessageCalled(String input, Message message)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.ProcessReceivedEventMessage(AmqpMessage amqpMessage)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by darobs** [comment]
Thank you @niksacdev 

I think @CIPop's answer [here](https://github.com/Azure/iotedge/issues/111#issuecomment-417432318) still applies. 

What is the TTL set to in the edgeHub?  If this is happening often, I'm wondering if the TTL is shorter than the longest time to respond to a message.

**Comment by myagley** [comment]
Closing due to inactivity.
