### ISSUE TITLE
Does Azure-Python-SDK or Node.JS SDK  work for EFLOW?

### ISSUE THREAD

**Issue by chunsheong** [Azure/iotedge#4965]
**Question Summary**
I am more familiar with Python or Node.js. I would like to know if it works with eflow at the moment.

**Detailed background**
I have managed to deploy and tested the first sample interop-textmsg-consoleapp succesfully with my setup. Next, as I am more familiar with Python and Node.js, I tried to deploy a sample Python module (MQTT) and two Node.js (tried both MQTT and AMQP based) modules created with VSCode Azure Extension onto eflow. However, in both python and Node.js, it can't seem to be able to connect to the MQTT/AMQP of EdgeHub.

This is the error I got from Python Module, for Node.js the error is similar.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 395, in connect
    host=self._hostname, port=8883, keepalive=self._keep_alive
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 34, in handle_result
    return callback.wait_for_completion()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/evented_callback.py", line 70, in wait_for_completion
    raise self.exception
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 193, in _run_op
    self.transport.connect(password=password)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 417, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by timeout('timed out')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./main.py", line 19, in <module>
    module_client.connect()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/patch_documentation.py", line 142, in connect
    return super(IoTHubModuleClient, self).connect()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 194, in connect
    handle_result(callback)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 38, in handle_result
    raise exceptions.ConnectionFailedError(message="Could not connect to IoTHub", cause=e)
azure.iot.device.exceptions.ConnectionFailedError: ConnectionFailedError('Could not connect to IoTHub') caused by ConnectionFailedError(None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 395, in connect
    host=self._hostname, port=8883, keepalive=self._keep_alive
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 34, in handle_result
    return callback.wait_for_completion()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/evented_callback.py", line 70, in wait_for_completion
    raise self.exception
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 193, in _run_op
    self.transport.connect(password=password)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 417, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by timeout('timed out')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./main.py", line 19, in <module>
    module_client.connect()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/patch_documentation.py", line 142, in connect
    return super(IoTHubModuleClient, self).connect()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 194, in connect
    handle_result(callback)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 38, in handle_result
    raise exceptions.ConnectionFailedError(message="Could not connect to IoTHub", cause=e)
azure.iot.device.exceptions.ConnectionFailedError: ConnectionFailedError('Could not connect to IoTHub') caused by ConnectionFailedError(None)
```

Iotedge check as below
```
iotedge-user@DESKTOP-OAE0HK6-EFLOW-7674f853 [ ~ ]$ sudo iotedge check                                                                                       
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname 192.168.2.128 but device reports hostname DESKTOP-OAE0HK6-EFLOW-7674f853.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

18 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
```

**Comment by dylanbronson** [comment]
Hello, I see this in your iotedge check response

```
× config.yaml has correct hostname - Error
    config.yaml has hostname 192.168.2.128 but device reports hostname DESKTOP-OAE0HK6-EFLOW-7674f853.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
```

Can you try using the device hostname "DESKTOP-OAE0HK6-EFLOW-7674f853"? I believe if this check is failing, connectivity failure is expected.

Also, it should be noted that by sharing your connection string publicly, it is no longer secure. You should generate a new device with a new connection string

**Comment by chunsheong** [comment]
> Thanks @chunsheong, the config.yaml seems to be correct. I have a couple of more questions that could help us determine the problem.
> 
> 1. If you run `sudo iptables -L` inside the EFLOW VM, what's the output? Do you have the correct firewall entries?
> 2. Have you tried the same Python configuration using another Linux VM?
> 
> I'll transfer the issue to the IoT-Edge team, as they can have a better understanding of what's happening.

@fcabrera23 

1. this is the entry of iptables -l
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:5671

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere

Chain DOCKER (2 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:secure-mqtt
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:5671
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:https

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
2. No, I have not tried this on another Linux VM.

**Comment by chunsheong** [comment]
> > Hello, I see this in your iotedge check response
> > ```
> > × config.yaml has correct hostname - Error
> >     config.yaml has hostname 192.168.2.128 but device reports hostname DESKTOP-OAE0HK6-EFLOW-7674f853.
> >     Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
> > ```
> > 
> > 
> >   
> >     
> >     
> >   
> > 
> > 
> > Can you try using the device hostname "DESKTOP-OAE0HK6-EFLOW-7674f853"? I believe if this check is failing, connectivity failure is expected.
> > Also, it should be noted that by sharing your connection string publicly, it is no longer secure. You should generate a new device with a new connection string
> 
> @dylanbronson I will get TLS error if I use the device hostname hence I used the first troubleshooting steps listed here (https://github.com/Azure/iotedge-eflow/blob/main/samples/interop-customvision-textmsg-uwpapp/Documentation/Troubleshooting.MD)

@dylanbronson sorry, disregard my comment above, I managed to fix the connection issue by changing the hostname in config.yaml back to the device hostname. And to solve the TLS error at the device hostname, I hardcoded the ip address mapping at /etc/hosts and it works. Thanks for the help, closing the issue now.
