### ISSUE TITLE
failed to create endpoint edgeHub on network nat

### ISSUE THREAD

**Issue by terrymandin** [Azure/iotedge#5005]
## Expected Behavior
edgehub container should start

## Current Behavior
The edgeAgent log is showing a "failed to create endpoint edgeHub on network nat" error.  

Note that this is a locked down Purdue network with no access to a public DNS.  The computer is configured to use a private OT DNS server.  Both the IoT Hub and Container Registry url's and ExpressRoute private endpoints have been added to the DNS. 

I noted in the troubleshooting documentation [here ](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2020-11#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device)that this error can occur when the DNS isn't specified so I added the DNS ip to the HostConfig for both edgeAgent and edgeHub, but it still didn't start.

```
{
    "HostConfig": {
        "ExtraHosts": null,
        "Dns": [
            "<dns ip>",
            "<backup dns ip>"
        ]
    }
}
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.Install IoT Edge Windows version 1.1
2.Add edgeHub and edgeAgent to a private Azure Container Registry.
3.Configure the IOT Edge device to pull from the private Container Registry
4.Configure the HostConfig to have the primary and secondary DNS ips.
5.Start IoT Edge

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

 iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.1.1' locally
    docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
    See 'docker run --help'.
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
‼ host time is close to real time - Warning
    Could not query NTP server
× container time is close to host time - Error
    Could not query local time inside container
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 64 days (at 2021-07-22 21:03:34 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its C:\Windows\Temp\edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with IoT Hub AMQP port - Error
    Could not connect to ioth-lpiiot-dev-cac.azure-devices.net:5671
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the nat network could not connect to ioth-lpiiot-dev-cac.azure-devices.net:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the nat network could not connect to ioth-lpiiot-dev-cac.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the nat network could not connect to ioth-lpiiot-dev-cac.azure-devices.net:8883

8 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.
6 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS: Windows 10 Enterprise N Version 1809 (OS Build 17763.1879)
* Architecture: amd64 (Windows Azure VM)
* Container OS: Windows containers

### Runtime Versions
* aziot-edged: iotedge 1.1.1
* Edge Agent: 1.1
* Edge Hub: 1.1
* Docker/Moby: 19.03.12+azure

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

  caused by: Could not start module edgeHub
        caused by: failed to create endpoint edgeHub on network nat: failed during hnsCallRawResponse: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. (0x20), StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\version_2020_07_07\ModuleManagementHttpClient.cs:line 235
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\versioning\ModuleManagementHttpClientVersioned.cs:line 144
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.StartModuleAsync(String name) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\version_2020_07_07\ModuleManagementHttpClient.cs:line 178
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\commands\GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\planrunners\OrdererdRetryPlanRunner.cs:line 87
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\planrunners\OrdererdRetryPlanRunner.cs:line 115
   at Microsoft.Azure.Devices.Edge.Util.Option`1.ForEach(Action`1 action) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\Option.cs:line 141
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\planrunners\OrdererdRetryPlanRunner.cs:line 116
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 162
<4> 2021-05-19 12:27:10.872 -07:00 [WRN] - Reconcile failed because of the an exception
System.AggregateException: One or more errors occurred. (Error calling start module edgeHub: Could not start module edgeHub
        caused by: Could not start module edgeHub
        caused by: failed to create endpoint edgeHub on network nat: failed during hnsCallRawResponse: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. (0x20))
 ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module edgeHub: Could not start module edgeHub

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by darobs** [comment]
Hi @terrymandin 

It looks like there's some possibilities for this problem:
source: https://stackoverflow.com/questions/53836103/failed-to-create-endpoint-on-network-nat-hnscall-failed-in-win32-the-process-c

1. This could be a port conflict, and the Windows Docker service is returning an unusual error.
  EdgeHub tries to map ports 443, 5671, and 8883 to the host - port 443 seems to be the most common conflict.
2. There is something in the Docker service that has left a file open.  The SO link above suggests these steps to clean this up:
```powershell
Stop-Service docker
Stop-service hns
Start-service hns
Start-Service docker
docker network prune
```
I haven't verified this.
3. Running `docker logs -f` may also leave a file open and the Docker daemon can't write/overwrite it.

I'd start with checking port conflicts.

**Comment by darobs** [comment]
Hi @terrymandin 

Did this suggestion help?

**Comment by terrymandin** [comment]
Hi @darobs, we removed all configOptions from both edgeHub and edgeAgent and it started working.
