### ISSUE TITLE
Could not pull image xxxxxmodulecontainer.azurecr.io/samplemodule:0.0.2-amd64, unauthorized: Application not registered with AAD

### ISSUE THREAD

**Issue by kharsha345** [Azure/iotedge#5085]
Hi Team,
I have created an IoT Edge module which is an image stored in the Azure Container Registry, I am able to successfully push the module into the Azure CR. After that did "Create Deployment for a Single Device" in VS Code which i am able to see my custom module under my IoT Edge Device in Azure Portal. 
When i do `sudo iotedge system restart` all the images has to be pulled from the Azure CR and should start running on the Edge Device. 
I am getting errors for pulling image.
Below are the edgeAgent logs.
Please help me with the issue. Thanks.

```
<6> 2021-06-06 11:54:00.133 +00:00 [INF] - Plan execution started for deployment 7
<6> 2021-06-06 11:54:00.133 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module SampleModule]\n  [Start module SampleModule]\n)"
<6> 2021-06-06 11:54:00.133 +00:00 [INF] - Executing command: "Create module SampleModule"
<3> 2021-06-06 11:54:21.540 +00:00 [ERR] - Executing command for operation ["create"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module SampleModule: Could not create module SampleModule
	caused by: Could not pull image xxxxxmodulecontainer.azurecr.io/samplemodule:0.0.2-amd64
	caused by: Head https://xxxxxmodulecontainer.azurecr.io/v2/samplemodule/manifests/0.0.2-amd64: unauthorized: Application not registered with AAD., StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 235
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 151
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 100
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
<3> 2021-06-06 11:54:21.540 +00:00 [ERR] - Executing command for operation ["Command Group: (\n  [Create module SampleModule]\n  [Start module SampleModule]\n)"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module SampleModule: Could not create module SampleModule
	caused by: Could not pull image xxxxxmodulecontainer.azurecr.io/samplemodule:0.0.2-amd64
	caused by: Head https://xxxxxmodulecontainer.azurecr.io/v2/samplemodule/manifests/0.0.2-amd64: unauthorized: Application not registered with AAD., StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 235
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 151
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 100
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
<3> 2021-06-06 11:54:21.541 +00:00 [ERR] - Step failed in deployment 7, continuing execution. Failure when running command Command Group: (
  [Create module SampleModule]
  [Start module SampleModule]
). Will retry in -01s.
```

**Comment by pmzara** [comment]
@kharsha345 Could you send a copy of your deployment configuration file, please?

**Comment by kharsha345** [comment]
Hi pmzara, 

Thanks for the reply.
I have first tried directly replacing the `$CONTAINER_REGISTRY_USERNAME_xxxxxxxmodulecontainer` and `$CONTAINER_REGISTRY_PASSWORD_xxxxxxxxmodulecontainer` with username and password of the Azure CR. it didnt quite work and gave some errors. 
Then i tried to first login using `docker login -u xxxxxxModuleContainer -p <password> xxxxxxxmodulecontainer.azurecr.io` and then did "Create Deployment for Single Device" then it worked. At least i am able to see the module in Azure CR --> Repositories.
Below is the "deployment.template.json" file
 ```
{
  "$schema-template": "2.0.0",
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {
              "xxxxxxxmodulecontainer": {
                "username": "$CONTAINER_REGISTRY_USERNAME_xxxxxxxmodulecontainer",
                "password": "$CONTAINER_REGISTRY_PASSWORD_xxxxxxxmodulecontainer",
                "address": "xxxxxxxxmodulecontainer.azurecr.io"
              }
            }
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.1",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.1",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "modules": {
          "SampleModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULES.SampleModule}",
              "createOptions": {}
            }
          },
          "SimulatedTemperatureSensor": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
              "createOptions": {}
            }
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {
          "SampleModuleToIoTHub": "FROM /messages/modules/SampleModule/outputs/* INTO $upstream",
          "sensorToSampleModule": "FROM /messages/modules/SimulatedTemperatureSensor/outputs/temperatureOutput INTO BrokeredEndpoint(\"/modules/SampleModule/inputs/input1\")"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
  }
}
```

**Comment by kharsha345** [comment]
Hi pmzara,

Now its working fine. I am able to pull all the custom modules deployed in Azure CR. 

Changes made:
In the `deployment.template.json` file
I have changed this to `"image": "${MODULES.SampleModule}"` to  `"image": "xxxxxxxmodulecontainer.azurecr.io/samplemodule:0.0.2-amd64"`

Basically updated the URI manually and restarted the IoT Edge which happens to download and run the SampleModule.

Thanks a lot for the help.

You can close this issue.
