### ISSUE TITLE
IoT Edge 1.2 issue with firewalld

### ISSUE THREAD

**Issue by abhilashcachar** [Azure/iotedge#5125]
1.	In previous versions of iotedge we had firewalld service running after which we were activating the device. This used to work fine and caused no issues while device acticvation.
2.	But in iotedge 1.2, if we have firewalld service running, device activation fails. 

a. As a workaround we are now activating the device first and then installing the firewalld. When this is the case, as soon as we install firewalld, here is the status for the service:

 
![image](https://user-images.githubusercontent.com/57358630/122393266-526d4600-cf92-11eb-8534-e56edd2b6e14.png)

Now at this point,  we will see only edgeAgent and no other modules get downloaded. If we look into the logs for edgeAgent, we see:
                                      
```
<4> 2021-06-01 14:16:28.487 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2021-06-01 14:16:38.156 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) (Transient network error occurred, please retry.)
---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass26_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass37_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
```

b. So we found a workaround that if we now reboot the device, things start to work fine. And now if we look into the status of firewalld service, we see the below:

![image](https://user-images.githubusercontent.com/57358630/122393408-7a5ca980-cf92-11eb-9482-dfd4cdb608b3.png)

So (comparing the above 2 screenshots), from iotedge 1.2 version, iotedge is not able to override firewalld to add the above rules to iptables. This used to work fine with previous versions of iotedge without reboot.

Questions:
a.	What has changed in iotedge 1.2, due to which it is not able to override firewalld and add the rules that it needs to iptables?
b.	Why does it work when we reboot the VM but not when we restart iotedge or firewalld or both the services.

**Comment by darobs** [comment]
Hi @abhilashcachar 

Acknowledging this issue, and adding @varunpuranik for awareness.

**Comment by abhilashcachar** [comment]
Hello @darobs @varunpuranik,
Checking if there is any update on this.

**Comment by varunpuranik** [comment]
@abhilashcachar - we are still working on this, and we don't have a update to share yet. We will keep you posted when we have something to share.

**Comment by ancaantochi** [comment]
@abhilashcachar, can you please check what docker version you're using:

 docker version

It looks like is related to docker, I assume the workaround to restart the device is working because docker needs to be restarted and that's why restarting firewalld or iotedge is not helping. Please try to restart just docker and let us know if it works as a workaround.

**Comment by abhilashcachar** [comment]
Hi @ancaantochi,
Yes restarting docker helped. Here is the version of docker we are using:

![image](https://user-images.githubusercontent.com/57358630/126915359-844c7a3b-03ef-4103-94ad-4b290664b3fc.png)

We can see that the cotainerd version is 1.4.6+azure.

Since there was an update to containerd, I ran sudo apt upgrade which updated the version of containerd to 1.4.8+azure as below.

![image](https://user-images.githubusercontent.com/57358630/126918363-9ee7fc60-f0f7-4d15-b882-4ca538443d49.png)

Now, iotedge gets activated even in the presence of firewalld. I believe containerd comes with installation of iotedge binaries, if this is true can we make sure latest version of containerd gets installed if not done already.

Thank you so much for the investigation and the support.

**Comment by abhilashcachar** [comment]
@ancaantochi, docker is opening up inbound ports 443, 8883 and amqps even though they are not allowed on firewalld. Any idea if this is needed or a way to close these ports?

**Comment by ancaantochi** [comment]
It's because by default edgeHub sets the PortBindings in createOptions, that is only needed if you have leaf devices. If you only need modules to connect to edgeHub you can remove the PortBindings.

**Comment by ancaantochi** [comment]
Closing this issue, please reopen if needed.
