### ISSUE TITLE
IoT Edge 1.2 clean deployment fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by denizetkar** [Azure/iotedge#5141]
## Expected Behavior
I would expect the checks made by `sudo iotedge check --verbose` command to return no errors (warnings are acceptable).

## Current Behavior
The output of my check looks like below:
```bash
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: docker returned exit code: 1, stderr = Error: No such object: edgeHub
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
34 check(s) succeeded.
1 check(s) raised warnings.
1 check(s) raised errors.
```

## Steps to Reproduce
1. Find an AMD64 based machine with Ubuntu 20.04.2 installed.
2. Following [THIS](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2020-11) official tutorial, run the following commands:
    ```bash
    curl https://packages.microsoft.com/config/ubuntu/18.04/multiarch/prod.list > ./microsoft-prod.list
    sudo mv ./microsoft-prod.list /etc/apt/sources.list.d/
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    sudo mv ./microsoft.gpg /etc/apt/trusted.gpg.d/
    
    sudo apt-get update
    # Install moby-engine only if it is not already installed.
    dpkg-query -l moby-engine &> /dev/null
    retVal=$?
    if [[ retVal -ne 0 ]]; then
        sudo apt-get install -y moby-engine
    fi
    sudo python3 docker-configure.py
    sudo service docker restart
    
    sudo apt-get install -y aziot-edge
    sudo cp /etc/aziot/config.toml.edge.template ./config.toml
    sudo chown $USER: ./config.toml
    ```
   Below is the `docker-configure.py` python file:
    ```python3
    import argparse
    import json
    import os
    from typing import Any, Dict
    
    
    def main(args: argparse.Namespace):
        docker_daemon_path = "/etc/docker/daemon.json"
        config: Dict[str, Any] = {}
        if os.path.isfile(docker_daemon_path):
            with open(docker_daemon_path, "rt") as f:
                config = json.load(f)
        config["log-driver"] = "json-file"
        config["log-opts"] = {"max-size": "10m", "max-file": "3"}
        config["dns"] = ["8.8.8.8", "8.8.4.4"]
        with open(docker_daemon_path, "wt") as f:
            json.dump(config, f, default=str, indent=2)
    
    
    if __name__ == "__main__":
        parser = argparse.ArgumentParser()
        main(parser.parse_args())
    ```
3. Modify `./config.toml` file using some text editor by uncommenting and editing these lines:
    ```ini
    [provisioning]
    source = "manual"
    connection_string = "<my-conn-string>"
    ```
   Where `<my-conn-string>` is the connection string of an IoT edge device that I have registered myself manually on my Azure IoTHub.
4. Put the config back where it belongs, then apply the changes:
    ```bash
    sudo mv ./config.toml /etc/aziot/config.toml
    sudo chown root: /etc/aziot/config.toml
    sudo iotedge config apply
    ```
5. After some time, run `sudo iotedge check --verbose` and observe the **Current Behaviour** as I shared above.

## Context (Environment)
Not sure what context means here. However, I followed this official tutorial: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2020-11

### Output of `iotedge check`
Already shared it above in **Current Behaviour** section.

### Device Information
* Host OS: Ubuntu 20.04.2 LTS
* Architecture: AMD64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged: iotedge 1.2.1
* Edge Agent: mcr.microsoft.com/azureiotedge-agent:1.2
* Edge Hub: There is no docker image for the edge hub!
* Docker/Moby:
  ```
  Client:
   Version:           20.10.6+azure
   API version:       1.41
   Go version:        go1.13.15
   Git commit:        370c28948e3c12dce3d1df60b6f184990618553f
   Built:             Fri Apr  9 17:01:36 2021
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
  Server:
   Engine:
    Version:          20.10.6+azure
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.13.15
    Git commit:       8728dd246c3ab53105434eef8ffe997b6fd14dc6
    Built:            Fri Apr  9 22:06:18 2021
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.4.6+azure
    GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
   runc:
    Version:          1.0.0-rc95
    GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
   docker-init:
    Version:          0.19.0
    GitCommit:
  ```

## Logs
* I have already shared iotedge checks. Here are support bundle logs:
   [support_bundle.zip](https://github.com/Azure/iotedge/files/6697211/support_bundle.zip)
* Here is the output of `sudo iotedge system status`:
  ```bash
  System services:
      aziot-edged             Running
      aziot-identityd         Running
      aziot-keyd              Running
      aziot-certd             Running
      aziot-tpmd              Ready
  
  Use 'iotedge system logs' to check for non-fatal errors.
  Use 'iotedge check' to diagnose connectivity and configuration issues.
  ```
* Here is the output of `sudo iotedge list`:
  ```bash
  NAME             STATUS           DESCRIPTION      CONFIG
  edgeAgent        running          Up 36 minutes    mcr.microsoft.com/azureiotedge-agent:1.2
  ```

## Additional Information
Not sure what more to say. But I would be open to go through more troubleshooting steps if instructed.

**Comment by dmolokanov** [comment]
Hello @denizetkar ! So let me clarify you've installed iotedge on the ubuntu 20.04 and it works successfully. The issue you have is for `iotedge check` command error entries, right?

**Comment by denizetkar** [comment]
@dmolokanov I wouldn't say it works successfully, so no. But I'm definitely getting some errors from `iotedge check`, yes.

**Comment by dmolokanov** [comment]
from the support bundle I see that you have iotedge components running with no errors after restart and edgeAgent is deployed and running. 
`iotedge check` production readiness errors are for the case when user wants to ensure their edge installation is fully production ready. iotedge should continue to operate even with production readiness errors.

what is exactly errors you are referring to?

**Comment by denizetkar** [comment]
I was getting `417 -- The device's deployment configuration is not set` as the IoT edge runtime response while looking at my edge device in Azure Portal. Is this not an error?

**Comment by dmolokanov** [comment]
Got it! This is expected actually. It means you have a clean iotedge setup without any modules. You need to apply some deployments with some modules to see a different response. Please try [temp sensor example](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux?view=iotedge-2020-11#deploy-a-module) which we usually use to smoke test installation.

**Comment by denizetkar** [comment]
I'm having another deployment issue now and since all the context I provided here are valid, I didn't want to open another issue. So, now that I understand after setting some modules to run on my device from Azure portal, the deployment manifest is automatically created and soon after my device picks it up, pulls the image and runs the module. However, the problem I get now is the following:
The edge module that I'm deploying is written in Node JS. In fact, I'm deploying a custom docker image of node-red where I have developed my own node-red node which was forked from [THIS](https://github.com/iotblackbelt/node-red-contrib-azure-iot-device) repo. Anyways, I modified the `node-red-contrib-azure-iot-device` to have an option to connect to Azure IoTHub using [THIS](https://docs.microsoft.com/en-us/javascript/api/azure-iot-device/moduleclient?view=azure-node-latest#fromEnvironment_any_) option. Basically I want my edge module to automatically connect to the IoTHub by taking all the necessary credentials from the environment variables and the IoT edge security daemon. But when I deploy the edge module from Azure portal on my device, I get the following container log for my module:
```
> node-red-docker@1.3.5 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data" "/data/flows.json"

29 Jun 00:23:59 - [info] 

Welcome to Node-RED
===================

29 Jun 00:23:59 - [info] Node-RED version: v1.3.5
29 Jun 00:23:59 - [info] Node.js  version: v12.22.1
29 Jun 00:23:59 - [info] Linux 5.8.0-59-generic x64 LE
29 Jun 00:23:59 - [info] Loading palette nodes
29 Jun 00:24:00 - [info] Settings file  : /data/settings.js
29 Jun 00:24:00 - [info] Context store  : 'default' [module=memory]
29 Jun 00:24:00 - [info] User directory : /data
29 Jun 00:24:00 - [warn] Projects disabled : editorTheme.projects.enabled=false
29 Jun 00:24:00 - [info] Flows file     : /data/flows.json
29 Jun 00:24:00 - [info] Server now running at http://127.0.0.1:1880/
29 Jun 00:24:00 - [info] Starting flows
29 Jun 00:24:00 - [info] [azureiotdevice:987b12d6.8d941]  -> Initiate IoT Device settings.
29 Jun 00:24:00 - [info] Started flows
29 Jun 00:24:00 - [info] [azureiotdevice:987b12d6.8d941] edge-test-device-1 -> Listening to C2D messages
29 Jun 00:24:00 - [error] [azureiotdevice:987b12d6.8d941] edge-test-device-1 -> Device connection failed
(node:18) UnhandledPromiseRejectionWarning: Error: UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): getaddrinfo ENOTFOUND deniz-virtualbox error
    at /usr/src/node-red/modules/node-red-contrib-azure-iot-device/azureiotdevice/azureiotdevice.js:219:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I check the environment variable of the `node-red` process running in the container with `cat /proc/$(pgrep node-red)/environ | tr '\0' '\n' | sort | grep IOTEDGE_`, here is what I get:
```bash
IOTEDGE_APIVERSION=2019-01-30
IOTEDGE_AUTHSCHEME=sasToken
IOTEDGE_DEVICEID=edge-test-device-1
IOTEDGE_GATEWAYHOSTNAME=deniz-virtualbox
IOTEDGE_IOTHUBHOSTNAME=<my-iothub-name>.azure-devices.net
IOTEDGE_MODULEGENERATIONID=637605219790277624
IOTEDGE_MODULEID=<my-module-name>
IOTEDGE_WORKLOADURI=unix:///var/run/iotedge/workload.sock
```

If, for instance, you check the Azure Python iot device SDK (which should do very similar things), [the corresponding module client code](https://github.com/Azure/azure-iot-sdk-python/blob/d5856b40405b5edffeff8deeed9f0445fbfa60ca/azure-iot-device/azure/iot/device/iothub/abstract_clients.py#L669) looks for the above environment variables all of which are already given by the edge runtime successfully. However, there still seems to be a problem with the module client connecting to the IoTHub.

I would be happy if you could help me solve it soon as I'm in a bit of a tight schedule to finish this task. By the way, further troubleshooting is perfectly fine for me, if needed.

**Comment by denizetkar** [comment]
I'm having another deployment issue now and since all the context I provided here are valid, I didn't want to open another issue. So, now that I understand after setting some modules to run on my device from Azure portal, the deployment manifest is automatically created and soon after my device picks it up, pulls the image and runs the module. However, the problem I get now is the following:

The edge module that I'm deploying is written in Node JS. In fact, I'm deploying a custom docker image of node-red where I have developed my own node-red node which was forked from [THIS](https://github.com/iotblackbelt/node-red-contrib-azure-iot-device) repo. Anyways, I modified the `node-red-contrib-azure-iot-device` to have an option to connect to Azure IoTHub using [THIS](https://docs.microsoft.com/en-us/javascript/api/azure-iot-device/moduleclient?view=azure-node-latest#fromEnvironment_any_) option. Basically I want my edge module to automatically connect to the IoTHub by taking all the necessary credentials from the environment variables and the IoT edge security daemon. But when I deploy the edge module from Azure portal on my device, I get the following container log for my module:
```
> node-red-docker@1.3.5 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data" "/data/flows.json"

29 Jun 00:59:54 - [info] 

Welcome to Node-RED
===================

29 Jun 00:59:54 - [info] Node-RED version: v1.3.5
29 Jun 00:59:54 - [info] Node.js  version: v12.22.1
29 Jun 00:59:54 - [info] Linux 5.8.0-59-generic x64 LE
29 Jun 00:59:54 - [info] Loading palette nodes
29 Jun 00:59:55 - [info] Settings file  : /data/settings.js
29 Jun 00:59:55 - [info] Context store  : 'default' [module=memory]
29 Jun 00:59:55 - [info] User directory : /data
29 Jun 00:59:55 - [warn] Projects disabled : editorTheme.projects.enabled=false
29 Jun 00:59:55 - [info] Flows file     : /data/flows.json
29 Jun 00:59:55 - [info] Server now running at http://127.0.0.1:1880/
29 Jun 00:59:55 - [info] Starting flows
29 Jun 00:59:55 - [info] [azureiotdevice:987b12d6.8d941]  -> Initiate IoT Device settings.
29 Jun 00:59:55 - [info] Started flows
29 Jun 00:59:55 - [info] [azureiotdevice:987b12d6.8d941] edge-test-device-1 -> Listening to C2D messages
29 Jun 00:59:56 - [error] [azureiotdevice:987b12d6.8d941] edge-test-device-1 -> Device connection failed
(node:17) UnhandledPromiseRejectionWarning: Error: UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): getaddrinfo ENOTFOUND deniz-virtualbox error
    at /usr/src/node-red/modules/node-red-contrib-azure-iot-device/azureiotdevice/azureiotdevice.js:219:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My auto-generated deployment manifest looks like the following:
```json
{
    "modulesContent": {
        "$edgeAgent": {
            "properties.desired": {
                "modules": {
                    "<my-module-name>": {
                        "settings": {
                            "image": "<my-private-image-registry>/<my-module-image>:latest",
                            "createOptions": ""
                        },
                        "type": "docker",
                        "version": "1.0",
                        "status": "running",
                        "restartPolicy": "always"
                    }
                },
                "runtime": {
                    "settings": {
                        "minDockerVersion": "v1.25",
                        "registryCredentials": {
                            "<my-image-registry-name>": {
                                "address": "<my-image-registry-address>",
                                "password": "<my-image-registry-password>",
                                "username": "<my-image-registry-username>"
                            }
                        }
                    },
                    "type": "docker"
                },
                "schemaVersion": "1.1",
                "systemModules": {
                    "edgeAgent": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-agent:1.2",
                            "createOptions": ""
                        },
                        "type": "docker"
                    },
                    "edgeHub": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-hub:1.2",
                            "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"443/tcp\":[{\"HostPort\":\"443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}]}}}"
                        },
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always"
                    }
                }
            }
        },
        "$edgeHub": {
            "properties.desired": {
                "routes": {
                    "route": "FROM /messages/* INTO $upstream"
                },
                "schemaVersion": "1.1",
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 7200
                }
            }
        },
        "<my-module-name>": {
            "properties.desired": {}
        }
    }
}
```

When I check the environment variable of the `node-red` process running in the container with `cat /proc/$(pgrep node-red)/environ | tr '\0' '\n' | sort | grep IOTEDGE_`, here is what I get:
```bash
IOTEDGE_APIVERSION=2019-01-30
IOTEDGE_AUTHSCHEME=sasToken
IOTEDGE_DEVICEID=edge-test-device-1
IOTEDGE_GATEWAYHOSTNAME=deniz-virtualbox
IOTEDGE_IOTHUBHOSTNAME=<my-iothub-name>.azure-devices.net
IOTEDGE_MODULEGENERATIONID=637605219790277624
IOTEDGE_MODULEID=<my-module-name>
IOTEDGE_WORKLOADURI=unix:///var/run/iotedge/workload.sock
```

If, for instance, you check the Azure Python iot device SDK (which should do very similar things), [the corresponding module client code](https://github.com/Azure/azure-iot-sdk-python/blob/d5856b40405b5edffeff8deeed9f0445fbfa60ca/azure-iot-device/azure/iot/device/iothub/abstract_clients.py#L669) looks for the above environment variables all of which are already given by the edge runtime successfully. However, there still seems to be a problem with the module client connecting to the IoTHub.

I would be happy if you could help me solve it soon as I'm in a bit of a tight schedule to finish this task. By the way, further troubleshooting is perfectly fine for me, if needed.

**Comment by dmolokanov** [comment]
Yes, this is what I'd expect from the iot sdk client to do. Unfortunately, we have limited resources to investigate all possible clients community produces. I'd recommend to check with original authors if it the client should work as you expected. Cheers!
