### ISSUE TITLE
edge_ca configuration not working, logs indicate the PEM pass phrase is unknown

### ISSUE THREAD

**Issue by ckarrasalithya** [Azure/iotedge#5160]
I'm trying to configure certificates on an IoT Edge device using the procedure in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2020-11. To generate the certificates, I'm using the sample scripts (for testing only) provided in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2020-11.

I have set the trust_bundle_cert parameter and the cert and pk parameters under [edge_ca]:
```
trust_bundle_cert = "file:///cert/certs/azure-iot-test-only.root.ca.cert.pem
```
```
cert = "file:///cert/certs/iot-edge-device-ca-myhostnameCA-full-chain.cert.pem"
pk = "file:///cert/private/azure-iot-test-only.root.ca.key.pem"
```

edgeHub is unable to CreateServerCertificateAsync. In iotedge logs, I found that it was trying to obtain the "PEM pass phrase" from the user and failed (since this is a background service). This makes sense as the scripts generate certificates with a passphrase (1234 by default). 

**How do I specify that pass phrase?**
I tried adding pin-value=1234 to the key URL (as shown in examples using PKCS#11 URIs), but it did not work:
```
pk = "file:///cert/private/azure-iot-test-only.root.ca.key.pem?pin-value=1234"
```

I have also tried changing the permissions to my certificate files, as I have seen other similar issues where this was the suggested solution, but it did not make any difference.

What's the correct way to specify the pass phrase associated to the key?
Also, is the config.toml file documented somewhere?

### Device Information
* Host OS: Raspberry PI OS Buster Lite
* Architecture: arm32
* Container OS: Linux

### Runtime Versions
* aziot-edged: 1.2.2
* Edge Agent: 1.2.0
* Edge Hub: 1.2.0
* Docker/Moby: 3.0.13+azure

## Logs
<details>
<summary>iotedge logs edgeHub</summary>

```
Jun 25 15:00:01.706  INFO watchdog: MQTT broker is disabled
Jun 25 15:00:01.706  INFO watchdog::child: Launched Edge Hub process with pid 9
2021-06-25 15:00:02.447 +00:00 Edge Hub Main()
<7> 2021-06-25 15:00:03.848 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient] - Making a Http call to unix:///var/run/iotedge/workload.sock to CreateServerCertificateAsync
<7> 2021-06-25 15:00:05.533 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connecting socket /var/run/iotedge/workload.sock
<7> 2021-06-25 15:00:05.570 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connected socket /var/run/iotedge/workload.sock
<7> 2021-06-25 15:00:05.600 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Sending request http://workload.sock/modules/%24edgeHub/genid/637601546056173205/certificate/server?api-version=2019-01-30
<7> 2021-06-25 15:00:08.227 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Response received InternalServerError
<7> 2021-06-25 15:00:08.722 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient] - Retrying Http call to unix:///var/run/iotedge/workload.sock to CreateServerCertificateAsync because of error Error, retry count = 1
<7> 2021-06-25 15:00:08.733 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connecting socket /var/run/iotedge/workload.sock
<7> 2021-06-25 15:00:08.735 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connected socket /var/run/iotedge/workload.sock
<7> 2021-06-25 15:00:08.737 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Sending request http://workload.sock/modules/%24edgeHub/genid/637601546056173205/certificate/server?api-version=2019-01-30
<7> 2021-06-25 15:00:11.118 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Response received InternalServerError
<7> 2021-06-25 15:00:11.133 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient] - Retrying Http call to unix:///var/run/iotedge/workload.sock to CreateServerCertificateAsync because of error Error, retry count = 2
<7> 2021-06-25 15:00:14.104 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connecting socket /var/run/iotedge/workload.sock
<7> 2021-06-25 15:00:14.110 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connected socket /var/run/iotedge/workload.sock
<7> 2021-06-25 15:00:14.114 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Sending request http://workload.sock/modules/%24edgeHub/genid/637601546056173205/certificate/server?api-version=2019-01-30
<7> 2021-06-25 15:00:15.710 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Response received InternalServerError
<7> 2021-06-25 15:00:15.724 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient] - Retrying Http call to unix:///var/run/iotedge/workload.sock to CreateServerCertificateAsync because of error Error, retry count = 3
<7> 2021-06-25 15:00:18.735 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connecting socket /var/run/iotedge/workload.sock
<7> 2021-06-25 15:00:18.740 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connected socket /var/run/iotedge/workload.sock
<7> 2021-06-25 15:00:18.747 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Sending request http://workload.sock/modules/%24edgeHub/genid/637601546056173205/certificate/server?api-version=2019-01-30
<7> 2021-06-25 15:00:27.211 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Response received InternalServerError
<7> 2021-06-25 15:00:27.257 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient] - Error when getting an Http response from unix:///var/run/iotedge/workload.sock for CreateServerCertificateAsync
HTTP Response:

{"message":"Could not get server cert\n\tcaused by: internal error"}

Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.IoTEdgedException`1[Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.ErrorResponse]: Error
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.CreateServerCertificateAsync(String api_version, String name, String genid, ServerCertificateRequest request, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/generatedCode/HttpWorkloadClient.cs:line 648
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 126
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 59
Unhandled exception. System.AggregateException: One or more errors occurred. (Error calling CreateServerCertificateAsync: Could not get server cert
        caused by: internal error)
 ---> Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadCommunicationException- Message:Error calling CreateServerCertificateAsync: Could not get server cert
        caused by: internal error, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.HandleException(Exception ex, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 106
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 76
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.CreateServerCertificateAsync(String hostname, DateTime expiration) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 35
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetServerCertificatesFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId, String edgeHubHostname, DateTime expiration) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 259
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration, ILogger logger) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 54
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 57
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 36
Jun 25 15:00:27.710  INFO watchdog::child: Edge Hub process has stopped
```
</details>

<details>
<summary>iotedge system logs</summary>

```
Jun 25 11:06:00 myhostname aziot-certd[21909]: 2021-06-25T15:06:00Z [INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "2f72756e2f617a696f742f63657274642e736f636b:0"}
Jun 25 11:06:00 myhostname aziot-certd[21909]: 2021-06-25T15:06:00Z [INFO] - --> 200 {"content-type": "application/json"}
Jun 25 11:06:00 myhostname aziot-keyd[21897]: 2021-06-25T15:06:00Z [INFO] - <-- GET /keypair/aziot-edged-ca?api-version=2020-09-01 {}
**Jun 25 11:06:00 myhostname aziot-keyd[21897]: Enter PEM pass phrase:** # The issue seems to be here
Jun 25 11:06:00 myhostname aziot-keyd[21897]: 2021-06-25T15:06:00Z [ERR!] - error:2807106B:UI routines:UI_process:processing error:../crypto/ui/ui_lib.c:545:while reading strings, error:0906406D:PEM routines:PEM_def_callback:problems getting password:../crypto/pem/pem_lib.c:59:, error:0906A068:PEM routines:PEM_do_header:bad password read:../crypto/pem/pem_lib.c:434:
Jun 25 11:06:00 myhostname aziot-keyd[21897]: 2021-06-25T15:06:00Z [ERR!] - !!! internal error
Jun 25 11:06:00 myhostname aziot-keyd[21897]: 2021-06-25T15:06:00Z [ERR!] - !!! caused by: could not load key pair
Jun 25 11:06:00 myhostname aziot-keyd[21897]: 2021-06-25T15:06:00Z [ERR!] - !!! caused by: could not load key pair: AZIOT_KEYS_RC_ERR_EXTERNAL
Jun 25 11:06:00 myhostname aziot-keyd[21897]: 2021-06-25T15:06:00Z [INFO] - --> 500 {"content-type": "application/json"}
Jun 25 11:06:00 myhostname aziot-edged[21883]: 2021-06-25T15:06:00Z [WARN] - Error in workload API when requesting certificate:
Jun 25 11:06:00 myhostname aziot-edged[21883]: 2021-06-25T15:06:00Z [WARN] - Could not get server cert
Jun 25 11:06:00 myhostname aziot-edged[21883]: 2021-06-25T15:06:00Z [WARN] -         caused by: internal error
Jun 25 11:06:00 myhostname aziot-edged[21883]: 2021-06-25T15:06:00Z [ERR!] - Internal server error: Could not get server cert
Jun 25 11:06:00 myhostname aziot-edged[21883]:         caused by: internal error
Jun 25 11:06:00 myhostname aziot-edged[21883]: 2021-06-25T15:06:00Z [INFO] - [work] - - - [2021-06-25 15:06:00.640400694 UTC] "POST /modules/%24edgeHub/genid/637601546056173205/certificate/server?api-version=2019-01-30 HTTP/1.1" 500 Internal Server Error 68 "-" "-" auth_id(-)
```
</details>

**Comment by dmolokanov** [comment]
Hello! Thanks for reaching out! @arsing / @gordonwang0 Do you have any pointers for @ckarrasalithya ?

**Comment by arsing** [comment]
>`pk = "file:///cert/private/azure-iot-test-only.root.ca.key.pem"`

Root CA != Edge CA.

You've used the cert and key from https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2020-11#create-root-ca-certificate

You're supposed to use the cert and key from https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2020-11#create-iot-edge-device-ca-certificates

(The latter should be updated to say "Edge CA" instead of "Device CA". @dmolokanov please follow up with docs team.)

**Comment by ckarrasalithya** [comment]
Thanks @arsing, changing to the following value appears to have resolved the issue
```
pk = "file:///cert/private/iot-edge-device-ca-myhostname.key.pem"
```

As you mentioned, it would help to update the documentation to make this clearer.

However, before I got your response, I tried another workaround: I modified the certGen.sh script so that it would work without passwords (skip all passphrase-related parameters if the password is empty), and I tested your suggested solution with the resulting certificates, which succeeded.

Now, I'm trying to switch to password-protected certificate. I tried both with the default "1234" and with complex secret passwords. In both cases, edgeHub can start successfully, but clients connecting to it fail to validate the certificate. (I have configured the client to recognize the 3 certificates I created - the one without a password, the one with 1234, and the one with the complex secret passwords).

When I switch back to the original certificates that I got working (without a password), the client starts connecting successfully again.

Is there anything other than the following steps I would need to do to update a certificate?
1. Replace the certificate and key files references in /etc/aziot/config.toml
2. Make the machine's own certificate trusted by itself, by using 
```
sudo cp /cert/certs/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
sudo update-ca-certificates
```
3. Restart IoT Edge (`sudo iotedge config apply`)

**Comment by arsing** [comment]
>I modified the certGen.sh script so that it would work without passwords

That is unnecessary. The script does not generate the Edge CA privkey with a password in the first place. The root CA privkey is only used when issuing new Edge CA certs, which is a manual operation when generating them via the script, so keeping it password-protected causes no problem.

>Now, I'm trying to switch to password-protected certificate.

IoT Edge does not support Edge CA with private key on the filesystem that is password-protected.

**Comment by dmolokanov** [comment]
Do you need any further assistance?

**Comment by dmolokanov** [comment]
Please feel free to re-open the issue if you have any additional questions.

**Comment by amit12cool** [comment]
@dmolokanov I have generated my self signed Edge CA certs not from the test scripts provided by Azure but my own cert generation solution. My Edge CA certs are password protected. Is there a way I can mention the passphrase in config.toml file anywhere so that edge hub starts.? Right now I see this error reported in this issue.
