### ISSUE TITLE
Solution not supported in Gov Cloud

### ISSUE THREAD

**Issue by JLaw046** [Azure/iotedge#5209]
## Expected Behavior
After deploying the metricCollector module, start operation to scrape and upload metrics.

## Current Behavior
Registering agent with OMS failed.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.
2.
3.
4.

## Context (Environment)
GovCloud

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 55 days (at 2021-08-18 14:24:50 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>metricsCollector logs</summary>

```

[2021-06-22 19:46:06.257 INF] Initializing metrics collector
[2021-06-22 19:46:06.364 INF] Version - 1.0.0
[2021-06-22 19:46:06.368 DBG] Waiting on shutdown handler to trigger
[2021-06-22 19:46:06.452 INF] Metrics collector initialized with the following settings:^M
Settings:
LogAnalyticsWorkspaceId=REMOVED
Endpoints=[
  "http://edgeHub:9600/metrics",
  "http://edgeAgent:9600/metrics"
]
ScrapeFrequencySecs=300
UploadTarget=AzureMonitor
CompressForUpload=True
TransformForIoTCentral=False
AllowedMetrics=
BlockedMetrics=
ResourceId=/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Devices/Iothubs/TXBDigFacIoTD
[2021-06-22 19:46:06.630 DBG] Starting periodic operation Scrape and Upload Metrics...
[2021-06-22 19:46:06.634 INF] Scraping endpoint http://edgeHub:9600/metrics
[2021-06-22 19:46:06.659 INF] Scraping endpoint http://edgeAgent:9600/metrics
[2021-06-22 19:46:06.661 INF] Started operation Scrape and Upload Metrics
[2021-06-22 19:46:06.712 INF] Scraping finished, received 100 metrics from endpoint http://edgeHub:9600/metrics
[2021-06-22 19:46:06.713 INF] Scraping finished, received 137 metrics from endpoint http://edgeAgent:9600/metrics
Successfully created self-signed certificate  for agentGuid : {REMOVED} and workspace: REMOVED
OMS endpoint Url : https://REMOVED.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
sent registration request
OMS endpoint Url : https://REMOVED.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
sent registration request
OMS endpoint Url : https://REMOVED.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
sent registration request
OMS endpoint Url : https://REMOVED.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
sent registration request
exception occurred : One or more errors occurred. (Name does not resolve)
Registering agent with OMS failed (are the Log Analytics Workspace ID and Key correct?) : One or more errors occurred. (Name does not resolve)
[2021-06-22 19:46:07.413 FTL] System.AggregateException: One or more errors occurred. (Name does not resolve)
 ---> System.Net.Http.HttpRequestException: Name does not resolve
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<6> 2021-06-23 14:02:07.168 +00:00 [INF] - Successfully handled request UploadModuleLogs
<6> 2021-06-23 14:02:07.169 +00:00 [INF] - Initiating streaming logs for edgeHub
<6> 2021-06-23 14:02:07.169 +00:00 [INF] - Initiating streaming logs for metricsCollector
<6> 2021-06-23 14:02:07.169 +00:00 [INF] - Initiating streaming logs for edgeAgent
<6> 2021-06-23 14:02:07.170 +00:00 [INF] - Initiating streaming logs for OPCPublisher
<6> 2021-06-23 14:02:07.171 +00:00 [INF] - Initiating streaming logs for DigFactASAEdgeD
<6> 2021-06-23 14:09:14.995 +00:00 [INF] - Starting compaction of stores
<6> 2021-06-23 14:09:14.995 +00:00 [INF] - Starting compaction of store default
<6> 2021-06-23 14:09:14.995 +00:00 [INF] - Starting compaction of store moduleState
<6> 2021-06-23 14:09:14.995 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2021-06-23 14:09:14.995 +00:00 [INF] - Starting compaction of store Metrics
<6> 2021-06-23 14:09:15.030 +00:00 [INF] - Starting periodic operation Metrics Upload...
<6> 2021-06-23 14:09:15.033 +00:00 [INF] - Uploading Metrics
<6> 2021-06-23 14:09:15.230 +00:00 [INF] - Published metrics
<6> 2021-06-23 14:09:15.249 +00:00 [INF] - Successfully completed periodic operation Metrics Upload
<6> 2021-06-23 14:09:15.437 +00:00 [INF] - Starting periodic operation Metrics Scrape...
<6> 2021-06-23 14:09:15.437 +00:00 [INF] - Scraping Metrics
<6> 2021-06-23 14:09:15.437 +00:00 [INF] - Scraping endpoint http://edgeHub:9600/metrics
<6> 2021-06-23 14:09:15.438 +00:00 [INF] - Scraping endpoint http://edgeAgent:9600/metrics
<6> 2021-06-23 14:09:15.439 +00:00 [INF] - Storing Metrics
<6> 2021-06-23 14:09:15.443 +00:00 [INF] - Scraped and Stored Metrics
<6> 2021-06-23 14:09:15.443 +00:00 [INF] - Successfully completed periodic operation Metrics Scrape
<6> 2021-06-23 14:09:15.906 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2021-06-23 14:09:15.956 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 382 and reported properties version 1153.
<6> 2021-06-23 14:09:15.957 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2021-06-23 14:17:08.851 +00:00 [INF] - Received direct method call - UploadModuleLogs
<6> 2021-06-23 14:17:08.851 +00:00 [INF] - Received request UploadModuleLogs with payload
<6> 2021-06-23 14:17:08.851 +00:00 [INF] - Processing request to upload logs for {"schemaVersion":"1.0","items":{"id":".*","filter":{"tail":null,"since":"15m","until":null,"loglevel":null,"regex":".*"}},"encoding":1,"contentType":0}

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<6> 2021-06-24 14:09:43.631 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<4> 2021-06-24 14:09:46.199 +00:00 [WRN] - Module TXBFFIOTALTD01/DigFactASAEdgeD is not connected
<4> 2021-06-24 14:09:46.918 +00:00 [WRN] - Module TXBFFIOTALTD01/DataSplit is not connected
<6> 2021-06-24 14:09:51.069 +00:00 [INF] - Starting periodic operation Get EdgeHub config...
<6> 2021-06-24 14:09:51.218 +00:00 [INF] - Obtained edge hub config from module twin
<4> 2021-06-24 14:09:51.220 +00:00 [WRN] - Module TXBFFIOTALTD01/DigFactASAEdgeD is not connected
<4> 2021-06-24 14:09:51.220 +00:00 [WRN] - Module TXBFFIOTALTD01/DataSplit is not connected
<4> 2021-06-24 14:09:51.220 +00:00 [WRN] - Module TXBFFIOTALTD01/DataSplit is not connected
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - Set the following 6 route(s) in edge hub
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - OPCPublisherToStreamAnalytics: FROM /messages/modules/OPCPublisher/* INTO BrokeredEndpoint("modules/DigFactASAEdgeD/inputs/OPCPublisherInput")
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - StreamAnalyticsToUpstream: FROM /messages/modules/DigFactASAEdgeD/outputs/FutureFactoryDev INTO $upstream
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - OPCPublisherToUpstream: FROM /messages/modules/OPCPublisher/* INTO $upstream
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - MTCEventProcessingModuleToIoTHub: FROM /messages/modules/OPCPublisher/* INTO BrokeredEndpoint("/modules/DataSplit/inputs/OPCPublisherInput")
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - OPCModuleToStream: FROM /messages/modules/OPCPublisher/* INTO BrokeredEndpoint("/modules/DataSplit/inputs/OPCPublisherInput")
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - OPCModuleToIoTHub: FROM /messages/modules/OPCPublisher/* INTO $upstream
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2021-06-24 14:09:51.220 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config
<6> 2021-06-24 14:09:51.411 +00:00 [INF] - Updated reported properties for TXBFFIOTALTD01/$edgeHub
<4> 2021-06-24 14:09:52.220 +00:00 [WRN] - Module TXBFFIOTALTD01/DigFactASAEdgeD is not connected
<4> 2021-06-24 14:09:52.220 +00:00 [WRN] - Module TXBFFIOTALTD01/DataSplit is not connected
<4> 2021-06-24 14:09:54.210 +00:00 [WRN] - Module TXBFFIOTALTD01/DataSplit is not connected
<4> 2021-06-24 14:09:54.244 +00:00 [WRN] - Module TXBFFIOTALTD01/DigFactASAEdgeD is not connected
<4> 2021-06-24 14:09:58.425 +00:00 [WRN] - Module TXBFFIOTALTD01/DataSplit is not connected
<4> 2021-06-24 14:09:58.518 +00:00 [WRN] - Module TXBFFIOTALTD01/DigFactASAEdgeD is not connected
<4> 2021-06-24 14:10:05.197 +00:00 [WRN] - Module TXBFFIOTALTD01/DataSplit is not connected
<6> 2021-06-24 14:10:06.721 +00:00 [INF] - Starting refresh of device scope identities cache
<4> 2021-06-24 14:10:07.730 +00:00 [WRN] - Module TXBFFIOTALTD01/DigFactASAEdgeD is not connected
<4> 2021-06-24 14:10:18.317 +00:00 [WRN] - Module TXBFFIOTALTD01/DataSplit is not connected
```
</details>

## Additional Information
From my understanding, the Gov Cloud domain needs to be added to this solution.

<details>
<summary>iotedge list</summary>
```

NAME              STATUS           DESCRIPTION            CONFIG
DigFactASAEdgeD   stopped          Stopped                mcr.microsoft.com/azure-stream-analytics/azureiotedge:1.0.8
OPCPublisher      running          Up 2 days              mcr.microsoft.com/iotedge/opc-publisher:latest
edgeAgent         running          Up 2 days              mcr.microsoft.com/azureiotedge-agent:1.1
edgeHub           running          Up 2 days              mcr.microsoft.com/azureiotedge-hub:1.1
metricsCollector  failed           Failed (1) 2 days ago  mcr.microsoft.com/azureiotedge-metrics-collector:1.0

```
</details>

**Comment by veyalla** [comment]
Thanks for the report @JLaw046. We're aware of this limitation and plan to address it in the next release of the metrics collector (expected later this month). 

FYI @and-rewsmith

**Comment by veyalla** [comment]
Let’s keep this open until we release an update.

**Comment by and-rewsmith** [comment]
@nlcamp I think I remember you putting out a fix for this?

**Comment by veyalla** [comment]
@and-rewsmith This is about ability to set Azure domain, not making the image available in container registry for gov.

**Comment by veyalla** [comment]
azureiotedge-metrics-collector [v1.0.1 ](https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/azureiotedge-metrics-collector?P1=1626471000&P2=1&P3=1&P4=bir6kR5RDrngxxVycRELMkZ5I49kmgcJd6rtHbmlFus%3D&se=2021-07-16T21%3A30%3A00Z&sig=WWS%2BDQyEcHI8sfwJfUP2LBQix72Ubiqk2ANOXGJ1tI0%3D&sp=r&sr=b&sv=2015-02-21)is now available with the ability to specify Azure Domain to enable sending metrics to Azure government and regional clouds. See https://aka.ms/edgemon-config for details. There is a new environment variable named `AzureDomain`.

This should unblock you, so closing the issue. Please re-open if run into any problems.
