### ISSUE TITLE
facing issue with blob upload module in Nested Edge

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#5249]
## Expected Behavior
Following the instructions at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob?view=iotedge-2020-11
expects the module should upload the blob to cloud storage.

## Current Behavior
expect following is the root cause for this issue.
[bob_upload_error.txt](https://github.com/Azure/iotedge/files/6818077/bob_upload_error.txt)

x-ms-client-request-id:21f8d1b4-d620-4685-9e04-41209ad83b52
x-ms-date:Wed, 14 Jul 2021 15:23:24 GMT
x-ms-version:2020-04-08
/edgestore/edgestore
restype:container'.
---> Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException: The MAC signature found in the HTTP request 'C/TsG70dzNihXP27wckXUGx/5ZII+MbTnk8o5kt2Oe4=' is not the same as any computed signature. Server used following string to sign: 'PUT

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Follow the instruction at  https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob?view=iotedge-2020-11

### Output of `iotedge check`
Configuration checks (aziot-identity-service)
support bundles
[support_bundle.zip](https://github.com/Azure/iotedge/files/6818057/support_bundle.zip)

---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct parent_hostname - OK
× parent hostname is resolvable from inside container - Error
    Failed to resolve parent hostname outeredge.internal.cloudapp.net
× configuration has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'outeredge.internal.cloudapp.net/azureiotedge-diagnostics:1.2.3' locally
    docker: Error response from daemon: error parsing HTTP 404 response body: unexpected end of JSON input: "".
    See 'docker run --help'.
× container time is close to host time - Error
    Could not query local time inside container
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
× container on the default network can connect to upstream  AMQP port - Error
    Container on the default network could not connect to outeredge.internal.cloudapp.net:5671
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to outeredge.internal.cloudapp.net:443
× container on the default network can connect to upstream MQTT port - Error
    Container on the default network could not connect to outeredge.internal.cloudapp.net:8883
× container on the IoT Edge module network can connect to upstream AMQP port - Error
    Container on the azure-iot-edge network could not connect to outeredge.internal.cloudapp.net:5671
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to outeredge.internal.cloudapp.net:443
× container on the IoT Edge module network can connect to upstream MQTT port - Error
    Container on the azure-iot-edge network could not connect to outeredge.internal.cloudapp.net:8883
23 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
9 check(s) raised errors. Re-run with --verbose for more details.
<details>
<summary></summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.0.4
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]:  Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.3
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2
* Docker/Moby [run `docker version`]: 20.10.7+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by ksaye** [comment]
@pratson20 , I think you are seeing an issue with Storage Explorer and not the Blob Storage Module.

Using Storage Explorer, I got the same error.  Using Python (script below), I was successful.  Do you need to use Storage Explorer for now or can you use [Python](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python) to get what you need?

I got the same error (shown in the logs on the Blob Storage Module) when using Storage Explorer shown below.  It appears that there is an issue setting the accountName????
```
[2021-07-16 21:51:04.126] [info    ] [tid 32] Info: Accepting {0} request for '{1}'. RemoteEndPoint='{2}', Via='{3}', Expect='{4}', Connection='{5}', Version='{6}', ClientRequestId='{7}', UserAgent='{8}' DurationStayedInQueueInMs='{9}', RemainingRequestsInQueueAtEnqueue='{10}', RemainingRequestsInQueueAtDequeue='{11}', WasInHighPriorityQueue='{12}', ToSetKeepAliveToFalse='{13}', ActiveWorkerThreads='{14}', ActiveCompletionThreads='{15}' PassedInActivityId={16}, EnqueueTime={17}, DequeueTime={18}, RequestTraceActvityId = '{19}', p0="GET", p1="http://192.168.15.46:11002/?restype=account&comp=properties", p2="192.168.15.68:52610", p3="", p4="", p5="keep-alive", p6="2020-04-08", p7="d3107814-7d4b-4d4c-9ba1-ad0ab73b505c", p8="Microsoft Azure Storage Explorer", p9="0.0442", p10="0", p11="0", p12="False", p13="False", p14="2", p15="0", p16="null", p17="2021-07-16T21:51:04.1265891Z", p18="2021-07-16T21:51:04.1266142Z", p19="f9b25645-306c-4d86-9fc7-fcbdb7a82ad2"
[2021-07-16 21:51:04.128] [info    ] [tid 216] Info: Processing exception: {0}, p0="Microsoft.Cis.Services.Nephos.Common.Storage.XStoreArgumentException: accountName cannot be null or empty
 ---> Microsoft.Cis.Services.Nephos.Common.Storage.XStoreArgumentException: accountName cannot be null or empty
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.ValidationHelper.CheckStorageAccountName(String accountName)
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WStorageAccount..ctor(WStorageStamp stamp, String accountName)
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WStorageStamp.Microsoft.Cis.Services.Nephos.Common.Storage.IStorageStamp.CreateAccountInstance(String accountName, ITableServerCommandFactory tableServerCommandFactory)
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WStorageManager.CreateAccountInstance(String accountName)
   at Microsoft.Cis.Services.Nephos.Common.Storage.PerRequestStorageManager.CreateAccountInstance(String accountName)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.GetResourceAccountPropertiesImpl(String accountName, Boolean isAdminAccess, TimeSpan timeout, AsyncIteratorContext`1 context)+MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndGetResourceAccountProperties(IAsyncResult asyncResult)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext()"
[2021-07-16 21:51:04.133] [info    ] [tid 216] Info: Setting status description as "{0}", p0="One of the request inputs is not valid."
[2021-07-16 21:51:04.136] [error   ] [tid 216] Error: Billing: TransformNephosStatusForPreAuthFailures some unrecognized failure before authentication with status code {0}, p0="ExpectedFailure"
[2021-07-16 21:51:04.138] [error   ] [tid 216] Error: IsValidAccountName: accountName: {0} Exception Message: {1}, p0="", p1="Value cannot be null. (Parameter 'accountName')"
[2021-07-16 21:51:04.138] [info    ] [tid 216] Perf: PerfCounters: Account={0} Operation={1} on Container={2} with Status={3} RequestHeaderSize={4} RequestSize={5} ResponseHeaderSize={6} ResponseSize={7} ErrorResponseByte={8} TimeInMs={9} ProcessingTimeInMs={10} UserTimeoutInMs={11} OperationTimeoutInMs={12} MaxAllowedTimeoutInMs={13} SlaUsedInMs={14} ReadLatencyInMs={15} WriteLatencyInMs={16} ClientIP={17} UserAgent='{18}' RequestVersion='{19}' ProcessorVersionUsed='{20}' RequestUrl='{21}' ClientRequestId='{22}' MeasurementStatus={23} HttpStatusCode={24} TotalFeTimeInMs={25} TotalTableServerTimeInMs={26} TotalTableServerRoundTripCount={27} TotalPartitionWaitTimeInMs={28} TotalXStreamTimeInMs={29} TotalXStreamRoundTripCount={30} SmbOpLockBreakLatency={31} LastTableServerInstanceName={32} LastTableServerErrorCode={33} TotalAccountCacheWaitTimeInMs={34} TotalContainerCacheWaitTimeInMs={35} InternalStatus={36} RequestContentType='{37}' ResponseContentType='{38}' PartitionKey='{39}' ItemsReturned='{40}' BatchOperationCount='{41}' LastXStreamErrorCode={42} AuthenticationType='{43}' AccountConcurrentReq='{44}' OverallConcurrentReq='{45}' Range='{46}' EntityType='{47}' {48} LastTSPartition={49} TotalXCacheTimeInMs={50} TotalXCacheRoundTripCount={51} TotalTableServerOnlyTimeInMicroSeconds={52} TotalAuthTimeInMs={53} AuthenticationTimeInMs={54} AuthorizationTimeInMs={55} GetAuthenticationDataTimeInMs={56} GetAuthorizationDataTimeInMs={57} VnetPolicyCheckTimeInMs={58} PerfFeatureFlags={59}, p0="null", p1="PreAuthenticationFailure", p2="null", p3="InvalidInput", p4="0", p5="0", p6="0", p7="0", p8="0", p9="NA", p10="NA", p11="NA", p12="NA", p13="NA", p14="NA", p15="NA", p16="NA", p17="192.168.15.68:52610", p18="Microsoft Azure Storage Explorer, 1.20.0, win32 azsdk-js-storageblob/12.4.1 (NODE-VERSION v12.16.3; Windows_NT 10.0.19043)", p19="2020-04-08", p20="2020-04-08", p21="http://192.168.15.46:11002/?restype=account&comp=properties", p22="d3107814-7d4b-4d4c-9ba1-ad0ab73b505c", p23="PreauthenticationFailure", p24="400", p25="NA", p26="NA", p27="NA", p28="NA", p29="NA", p30="NA", p31="NA", p32="NA", p33="NA", p34="0", p35="0", p36="ClientOtherError", p37="", p38="application/xml", p39="", p40="0", p41="0", p42="NA", p43="NA", p44="", p45="1", p46="NA", p47="", p48="", p49="NA", p50="NA", p51="NA", p52="0", p53="0", p54="0", p55="0", p56="0", p57="0", p58="NA", p59="null"
```

Using the following python script (change your connection string), I was able to upload the blob:
```
# use 'pip install azure-storage-blob --upgrade' to make sure we are on version 12
import os
from azure.storage.blob import BlobServiceClient
connect_str = "DefaultEndpointsProtocol=http;BlobEndpoint=http://192.168.15.46:11002/lowerlayerstorage;AccountName=lowerlayerstorage;AccountKey=cZbMZYOURCODEHEREskxg==;"

blob_service_client = BlobServiceClient.from_connection_string(connect_str)
container_client = blob_service_client.get_container_client("edge")
if not container_client.exists():
	container_client.create_container()

blob_client = container_client.get_blob_client("demo.txt")
with open("c:\\users\\kevinsay\\test.txt", "rb") as data:
	blob_client.upload_blob(data, blob_type="BlockBlob", overwrite=True)
```

In the log files on the Blob Storage I see success:
```
root@lowerlayer:~# docker logs -f AzureBlobStorageonIoTEdge | grep demo.txt
[2021-07-16 21:46:49.258] [info    ] [tid 33] Info: Accepting {0} request for '{1}'. RemoteEndPoint='{2}', Via='{3}', Expect='{4}', Connection='{5}', Version='{6}', ClientRequestId='{7}', UserAgent='{8}' DurationStayedInQueueInMs='{9}', RemainingRequestsInQueueAtEnqueue='{10}', RemainingRequestsInQueueAtDequeue='{11}', WasInHighPriorityQueue='{12}', ToSetKeepAliveToFalse='{13}', ActiveWorkerThreads='{14}', ActiveCompletionThreads='{15}' PassedInActivityId={16}, EnqueueTime={17}, DequeueTime={18}, RequestTraceActvityId = '{19}', p0="PUT", p1="http://192.168.15.46:11002/lowerlayerstorage/edge/demo.txt", p2="192.168.15.68:51255", p3="", p4="", p5="keep-alive", p6="2020-06-12", p7="52fc7cb1-e67f-11eb-a0f4-e454e8803499", p8="azsdk-python-storage-blob/12.8.1", p9="0.08", p10="0", p11="0", p12="False", p13="False", p14="2", p15="0", p16="null", p17="2021-07-16T21:46:49.2581476Z", p18="2021-07-16T21:46:49.2581862Z", p19="04acf515-5226-4c9a-89c5-d76a3dd95936"
[2021-07-16 21:46:49.263] [info    ] [tid 193] WossProvider : PutBlobAsync >> Account = {0}, Container = {1}, Blob = {2}, Timeout = {3}, ContentLength = {4}, OverwriteOption = {5}, Condition = {6}., p0="lowerlayerstorage", p1="edge", p2="demo.txt", p3="00:01:59.9980001", p4="8", p5="CreateNewOrUpdateExisting", p6="[includeDisabledContainers = False, includeExpiredBlobs = False, ifModifiedSinceTime = <null>, ifNotModifiedSinceTime = <null>, leaseId = <null>, isIncludingUncommittedBlobs = True, isFetchingMetadata = False, isIncludingSnapshots = False, isIncludingPageBlobs = False, isIncludingAppendBlobs = False, isDeletingOnlySnapshots = False, ifLastModificationTimeMatch = <null>, ifLastModificationTimeMismatch = <null>, isRequiringNoSnapshots = False, isSkippingLastModificationTimeUpdate = False, sequenceNumberOperator = <null>, sequenceNumber = <null>, requiredBlobType = None, isMultipleConditionalHeaderEnabled = False, IsOperationOnAppendBlobsAllowed = True, IsRequiringLeaseIfNotModifiedSince = <null>, isDiskMountStateConditionRequired = False, ExcludeSoftDeletedBlobs = True, ExcludeAutomaticSnapshots = True, IncludeBlobVersionId = False, EnsureBlobIsAlreadySoftdeleted = False, isOperationAllowedOnArchivedBlobs = False, skipLeaseCheck = False, internalArchiveBlobLMT = <null>, internalArchiveBlobGenerationId = <null>, internalArchvieRequestId = <null>, includeSoftDeletedBlobsOnly = False, enforceWormPolicy = True, updateSequenceNumber = False, blobDeletePermissionLevel = RootBlobAndUserSnapshotOnly, ActiveNamespaceTransactionId = , excludeDFSCapacity = False, excludeNfsV3Capacity = False, RequireFileEntity = False, BlobPropertiesOwner = None, GetSoftDeleteInfoOnNotFound = False, ExcludeExpiredSoftDeletedBlob = False, EnforcedAccessTier = <null>, IsOperationBlockedOnGizafiedBlobs = True, LastAccessTimeTrackCondition = None, LastTrackingTime = <null>, LastAutoUptierTime = <null>, IncludeGeoReplicationLockedRows = False, DisableWriteOnSymLink = False]"
[2021-07-16 21:46:49.266] [info    ] [tid 193] [BlobInterface.cc:66] [PutBlob] PutBlob received. Container:edge Blob:demo.txt BlobType:block_blob ContentLength:8 Overwrite:create_new_or_update_existing SvcMetadataSize:36 AppMetadataSize:0 DataSize:8
[2021-07-16 21:46:49.267] [error   ] [tid 193] [MetaStore.cc:1530] [GetBlobRecord] Blob not found. ContainerName:edge BlobName:demo.txt
[2021-07-16 21:46:49.267] [error   ] [tid 193] [MetaStore.cc:1530] [GetBlobRecord] Blob not found. ContainerName:edge BlobName:demo.txt
[2021-07-16 21:46:49.268] [info    ] [tid 193] [DataStoreCommon.cc:199] [GetBlobFilePath] Insert BlobFilePath record. key:edge.demo.txt value:edge/demo.txt
[2021-07-16 21:46:49.269] [info    ] [tid 193] [DataStoreCommon.cc:119] [RecordChunk] Insert ChunksToDelete record. key:edge.demo.txt.00000000000000000000 chunkId:0 chunkSize:8
[2021-07-16 21:46:49.418] [info    ] [tid 193] [BlobInterface.cc:179] [PutBlob] PutBlob Filepath:edge/demo.txt
[2021-07-16 21:46:49.419] [error   ] [tid 193] [MetaStore.cc:1530] [GetBlobRecord] Blob not found. ContainerName:edge BlobName:demo.txt
[2021-07-16 21:46:49.420] [info    ] [tid 193] [MetaStore.cc:1168] [InsertBlobRecord] Insert blob update metadata record. key:edge.00132709456094201688.demo.txt value:3
[2021-07-16 21:46:49.420] [info    ] [tid 193] [MetaStore.cc:1196] [InsertBlobRecord] Delete BlobFilePath record. key:edge.demo.txt
[2021-07-16 21:46:49.421] [info    ] [tid 193] [MetaStore.cc:1229] [InsertBlobRecord] Delete ChunksToDelete record. key:edge.demo.txt.00000000000000000000
[2021-07-16 21:46:49.422] [info    ] [tid 193] [BlobInterface.cc:218] [PutBlob] PutBlob completed. Container:edge Blob:demo.txt
[2021-07-16 21:46:49.426] [info    ] [tid 193] Perf: PerfCounters: Account={0} Operation={1} on Container={2} with Status={3} RequestHeaderSize={4} RequestSize={5} ResponseHeaderSize={6} ResponseSize={7} ErrorResponseByte={8} TimeInMs={9} ProcessingTimeInMs={10} UserTimeoutInMs={11} OperationTimeoutInMs={12} MaxAllowedTimeoutInMs={13} SlaUsedInMs={14} ReadLatencyInMs={15} WriteLatencyInMs={16} ClientIP={17} UserAgent='{18}' RequestVersion='{19}' ProcessorVersionUsed='{20}' RequestUrl='{21}' ClientRequestId='{22}' MeasurementStatus={23} HttpStatusCode={24} TotalFeTimeInMs={25} TotalTableServerTimeInMs={26} TotalTableServerRoundTripCount={27} TotalPartitionWaitTimeInMs={28} TotalXStreamTimeInMs={29} TotalXStreamRoundTripCount={30} SmbOpLockBreakLatency={31} LastTableServerInstanceName={32} LastTableServerErrorCode={33} TotalAccountCacheWaitTimeInMs={34} TotalContainerCacheWaitTimeInMs={35} InternalStatus={36} RequestContentType='{37}' ResponseContentType='{38}' PartitionKey='{39}' ItemsReturned='{40}' BatchOperationCount='{41}' LastXStreamErrorCode={42} AuthenticationType='{43}' AccountConcurrentReq='{44}' OverallConcurrentReq='{45}' Range='{46}' EntityType='{47}' {48} LastTSPartition={49} TotalXCacheTimeInMs={50} TotalXCacheRoundTripCount={51} TotalTableServerOnlyTimeInMicroSeconds={52} TotalAuthTimeInMs={53} AuthenticationTimeInMs={54} AuthorizationTimeInMs={55} GetAuthenticationDataTimeInMs={56} GetAuthorizationDataTimeInMs={57} VnetPolicyCheckTimeInMs={58} PerfFeatureFlags={59}, p0="lowerlayerstorage", p1="PutBlob", p2="edge", p3="Success", p4="513", p5="8", p6="283", p7="0", p8="0", p9="165.4425", p10="165.3465", p11="922337203685477", p12="120000", p13="120000", p14="0", p15="0.096", p16="0", p17="192.168.15.68:51255", p18="azsdk-python-storage-blob/12.8.1 Python/3.8.5 (Windows-10-10.0.19041-SP0)", p19="2020-06-12", p20="2020-06-12", p21="http://192.168.15.46:11002/lowerlayerstorage/edge/demo.txt", p22="52fc7cb1-e67f-11eb-a0f4-e454e8803499", p23="Success", p24="201", p25="165.346", p26="0", p27="0", p28="0", p29="0", p30="0", p31="0", p32="", p33="0", p34="0", p35="0", p36="ExpectedSuccess", p37="application/octet-stream", p38="", p39="demo.txt", p40="0", p41="0", p42="0", p43="NA", p44="", p45="1", p46="", p47="BlockBlob", p48="", p49="", p50="0", p51="0", p52="0", p53="0.747", p54="0.673", p55="0.074", p56="0", p57="0", p58="0", p59="null"
[2021-07-16 21:46:50.103] [info    ] [tid 189] [BlobInterface.cc:1528] [ListBlobsInOrder] ListBlobsInOrder completed. Container:edge BlobEntryCount:1 NextBlobName:edge.00132709456094201688.demo.txt
[2021-07-16 21:46:50.104] [info    ] [tid 189] [BlobInterface.cc:1494] [ListBlobsInOrder] ListBlobsInOrder received. Container:edge BlobNameStart:edge.00132709456094201688.demo.txt MaxBlobNames:1 OrderType:0 Flags:1
[2021-07-16 21:46:50.105] [info    ] [tid 189] Microsoft.Azure.Devices.BlobStorage.Tiering.TieringOrchestrator: Found edge.demo.txt.2021-07-16T21:46:49.4201688Z
[2021-07-16 21:46:50.106] [info    ] [tid 189] Microsoft.Azure.Devices.BlobStorage.Tiering.BlobUpload: Uploading edge.demo.txt.2021-07-16T21:46:49.4201688Z
[2021-07-16 21:46:50.107] [info    ] [tid 193] [BlobInterface.cc:255] [GetBlobProperties] GetBlobProperties received. Container:edge Blob:demo.txt
[2021-07-16 21:46:50.109] [info    ] [tid 193] [BlobInterface.cc:283] [GetBlobProperties] GetBlobProperties completed. Container:edge Blob:demo.txt BlobType:block_blob ContentLength:8 SvcMetadataSize:36 AppMetadataSize:0 NumCommittedBlocks:1
[2021-07-16 21:46:50.111] [info    ] [tid 195] [BlobInterface.cc:1029] [GetBlockList] GetBlockList received. Container:edge Blob:demo.txt BlockListType:1
[2021-07-16 21:46:50.112] [info    ] [tid 195] [BlobInterface.cc:1119] [GetBlockList] GetBlockList completed. Container:edge Blob:demo.txt BlockIdSize:0 UncommitedBlocksCount:0 CommitedBlocksCount:0 ContentLength:8 ModificationTime:132709456094201688
[2021-07-16 21:46:50.116] [info    ] [tid 195] [BlobInterface.cc:321] [GetBlobData] GetBlobData received. Container:edge Blob:demo.txt Offset:0 Length:8 DataBufferOffset:0
[2021-07-16 21:46:50.117] [info    ] [tid 195] [BlobInterface.cc:356] [GetBlobData] Blob retrieved. Container:edge Blob:demo.txt CommittedBlockListSize:1
[2021-07-16 21:46:50.117] [info    ] [tid 195] [BlobInterface.cc:415] [GetBlobData] GetBlobData completed. Container:edge Blob:demo.txt ReturnedBytes:8
^C
root@lowerlayer:~#
```

And when I look at the host, I see the blob file there:
```
root@lowerlayer:~# ls -all -h /blobstorage/BlockBlob/edge/*.*
-rwx------ 1 11000 11000 4.0K Jul 16 21:46 /blobstorage/BlockBlob/edge/demo.txt
```

**Comment by pratson20** [comment]
@ksaye thanks for info.  it seems like there is a issue in Azure storage explorer. i am not able to create container in local storage connection string. When i tried the same thing VS code storage extension. its worked perfectly fine. I can push the blob to cloud and can create containers.

Closing this issue as VS code storage extension fixed the issue.

Thanks
