### ISSUE TITLE
SimulatedTemperatureSensor fails while following QuickStart guide

### ISSUE THREAD

**Issue by dzimine** [Azure/iotedge#527]
- **OS version and architecture used:** Ubuntu 16.04 x86_64, a VirtualBox VM on MacOS

- **Version used:**  iotedge 1.0.4 (2835ac47fbb944ba628a5cfe812ff394768842e0)

- **V2 Docker version and container type** Docker version 3.0.1, build 021bf39d on Linux (Moby per tutorial)

# Description of the issue:
When following the [Quickstart: Deploy your first IoT Edge module to a Linux x64 device](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux), the `tempSensor` module failed to communicate with the Hub with the following exception: *Put token failed. status-code: 400, status-description: Unable to authenticate EdgeModbus/tempSensor.*, and a correspondent *Error creating or updating the cloud proxy for client EdgeModbus/$edgeHub* in edgeHub. 

PS. I first filed it in [iot-edge-v1](https://github.com/Azure/iot-edge-v1/issues/661) where the sample is, but the iotedge version is here, so re-filing, please feel free to close one of the two, but attend the case. Thank you for considerations.

# Console log of the issue:

Error in *tempSensor* log:

```
[2018-11-08 00:52:11 : Starting Module
[11/08/2018 12:52:11.898 AM] Main()
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Using transport Amqp_Tcp_Only

Unhandled Exception: System.AggregateException: One or more errors occurred. (Put token failed. status-code: 400, status-description: Unable to authenticate EdgeModbus/tempSensor.) ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubException: Put token failed. status-code: 400, status-description: Unable to authenticate EdgeModbus/tempSensor.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 106
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 74
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 33
```

And a correspondent error in *edgeHub*: `Error creating or updating the cloud proxy for client EdgeModbus/$edgeHub`

```
[2018-11-08 00:44:57 : Starting Edge Hub
[11/08/2018 12:44:57.643 AM] Edge Hub Main()
[11/08/2018 12:44:58.499 AM] Found intermediate certificates.
2018-11-08 00:44:59.201 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-11-08 00:44:59.252 +00:00 [INF] - Created device scope identities cache
2018-11-08 00:44:59.256 +00:00 [INF] - Starting Edge Hub
2018-11-08 00:44:59.257 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-11-08 00:44:59.258 +00:00 [INF] - Starting refresh of device scope identities cache
2018-11-08 00:44:59.259 +00:00 [INF] - Version - 1.0.4.18259757 (2835ac47fbb944ba628a5cfe812ff394768842e0)
2018-11-08 00:44:59.265 +00:00 [INF] - Loaded server certificate with expiration date of "2019-02-06T00:36:23.0000000+00:00"
2018-11-08 00:44:59.300 +00:00 [INF] - Created new message store
2018-11-08 00:44:59.465 +00:00 [INF] - Initializing configuration
2018-11-08 00:44:59.488 +00:00 [INF] - New device connection for device EdgeModbus/$edgeHub
2018-11-08 00:44:59.533 +00:00 [INF] - Attempting to connect to IoT Hub for client EdgeModbus/$edgeHub via AMQP...
2018-11-08 00:44:59.796 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-11-08 00:45:19.620 +00:00 [ERR] - Error creating or updating the cloud proxy for client EdgeModbus/$edgeHub
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs:line 49
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 132
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 179
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.GetCloudProxyAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 157
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateOrUpdateAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 101
2018-11-08 00:45:19.623 +00:00 [WRN] - Error creating cloud connection for client EdgeModbus/$edgeHub
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs:line 49
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 132
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 179
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.GetCloudProxyAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 157
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateOrUpdateAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.Connect(IClientCredentials identity, Action`2 connectionStatusChangedHandler) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 130
2018-11-08 00:45:19.630 +00:00 [INF] - Error getting cloud connection for device EdgeModbus/$edgeHub
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs:line 49
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 132
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 179
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.GetCloudProxyAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 157
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateOrUpdateAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.Connect(IClientCredentials identity, Action`2 connectionStatusChangedHandler) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 130
```

**Comment by mrohera** [comment]
@dzimine any update for us?

**Comment by myagley** [comment]
What is the output of `docker exec edgeHub cat /etc/resolv.conf`?

**Comment by risro** [comment]
> 
> 
> What is the output of `docker exec edgeHub cat /etc/resolv.conf`?

since no one else has aswered and I have the same problem, mine is: 
nameserver 127.0.0.11
options ndots:0

**Comment by myagley** [comment]
There are usually two reasons why these timeouts are seen:
1. The Edge Hub can't connect to the IoT Hub. [IoT Edge Networking](https://github.com/Azure/iotedge/blob/master/doc/networking.md) for more information.
2. DNS is timing out trying to resolve the ip of the IoT Hub

If on linux amd64, you can verify connectivity by running `docker exec -it edgeHub nc -vz <your iot hub>.azure-devices.net`. This should return a "connected" message.

Item 2 is a little trickier. We have seen increased stability by manually specifying a DNS server in the Docker engine's config. More information is here: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file The gist is to add a file like below to `/etc/docker/daemon.json`:

```json
{
    "dns": ["8.8.8.8"]
}
```

The `8.8.8.8` is Google's public DNS server. It is just an example and you should replace it with the appropriate DNS server for your environment.

**Comment by ancaantochi** [comment]
Closing, please reopen if you still have this issue.
