### ISSUE TITLE
[metricsCollector] random errors when scraping iotedge Prometheus endpoints (edgeagent,edgehub ...)

### ISSUE THREAD

**Issue by omarine** [Azure/iotedge#5307]
## Expected Behavior
MetrisCollector should be able to Scrap metrics without throwing random errors

like the following : 
[2021-08-03 15:37:45 : Starting Module
[2021-08-03 15:37:46.081 INF] Initializing metrics collector
[2021-08-03 15:37:46.192 INF] Version - 1.0.0
[2021-08-03 15:37:46.197 DBG] Waiting on shutdown handler to trigger
[2021-08-03 15:37:46.298 INF] Metrics collector initialized with the following settings:
Settings:
LogAnalyticsWorkspaceId=
Endpoints=[
  "http://edgeAgent:9601/metrics",
  "http://edgeHub:9602/metrics",
  "http://opcpublisherLBTWR:9702/metrics"
]
ScrapeFrequencySecs=300
UploadTarget=IotMessage
CompressForUpload=False
TransformForIoTCentral=False
AllowedMetrics=
BlockedMetrics=
ResourceId=/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Devices/IotHubs/darwin-iot-dev-ne-iothub02
IotHubConnectFrequency=1.00:00:00
AzureDomain=azure.com
[2021-08-03 15:37:47.310 INF] Started operation Reconnect to IoT Hub
[2021-08-03 15:37:47.311 INF] Started operation Scrape and Upload Metrics
[2021-08-03 15:38:47.310 INF] Starting periodic operation Scrape and Upload Metrics...
[2021-08-03 15:38:47.310 INF] Starting periodic operation Reconnect to IoT Hub...
[2021-08-03 15:38:47.317 INF] Scraping endpoint http://edgeAgent:9601/metrics
[2021-08-03 15:38:47.323 INF] Scraping endpoint http://edgeHub:9602/metrics
[2021-08-03 15:38:47.323 INF] Scraping endpoint http://opcpublisherLBTWR:9702/metrics
[2021-08-03 15:38:47.379 INF] Scraping finished, received 49 metrics from endpoint http://opcpublisherLBTWR:9702/metrics
[2021-08-03 15:38:47.382 INF] Scraping finished, received 116 metrics from endpoint http://edgeHub:9602/metrics
[2021-08-03 15:38:47.400 INF] Scraping finished, received 26 metrics from endpoint http://edgeAgent:9601/metrics
[2021-08-03 15:38:47.542 INF] Closed and re-established connection to IoT Hub
[2021-08-03 15:38:47.542 INF] Successfully completed periodic operation Reconnect to IoT Hub
[2021-08-03 15:38:47.611 INF] Successfully sent metrics via IoT message
[2021-08-03 15:38:47.611 INF] Successfully completed periodic operation Scrape and Upload Metrics
[2021-08-03 15:43:47.614 INF] Starting periodic operation Scrape and Upload Metrics...
[2021-08-03 15:43:47.614 INF] Scraping endpoint http://edgeAgent:9601/metrics
[2021-08-03 15:43:47.616 INF] Scraping endpoint http://edgeHub:9602/metrics
[2021-08-03 15:43:47.617 INF] Scraping endpoint http://opcpublisherLBTWR:9702/metrics
[2021-08-03 15:43:47.624 INF] Scraping finished, received 26 metrics from endpoint http://edgeAgent:9601/metrics
[2021-08-03 15:43:47.625 INF] Scraping finished, received 116 metrics from endpoint http://edgeHub:9602/metrics
[2021-08-03 15:43:47.662 INF] Scraping finished, received 49 metrics from endpoint http://opcpublisherLBTWR:9702/metrics
[2021-08-03 15:43:47.706 INF] Successfully sent metrics via IoT message
[2021-08-03 15:43:47.706 INF] Successfully completed periodic operation Scrape and Upload Metrics

## Current Behavior
[2021-08-03 15:48:47.708 INF] Starting periodic operation Scrape and Upload Metrics...
[2021-08-03 15:48:47.709 INF] Scraping endpoint http://edgeAgent:9601/metrics
[2021-08-03 15:48:47.710 INF] Scraping endpoint http://edgeHub:9602/metrics
[2021-08-03 15:48:47.711 INF] Scraping endpoint http://opcpublisherLBTWR:9702/metrics
[2021-08-03 15:48:52.734 ERR] Error scraping endpoint http://edgeHub:9602/metrics - System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-modules/azure-monitor/src/MetricsScraper.cs:line 72
[2021-08-03 15:48:52.734 ERR] Error scraping endpoint http://opcpublisherLBTWR:9702/metrics - System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-modules/azure-monitor/src/MetricsScraper.cs:line 72
[2021-08-03 15:48:52.735 INF] Scraping finished, received 0 metrics from endpoint http://edgeHub:9602/metrics
[2021-08-03 15:48:52.735 INF] Scraping finished, received 0 metrics from endpoint http://opcpublisherLBTWR:9702/metrics
[2021-08-03 15:48:52.734 ERR] Error scraping endpoint http://edgeAgent:9601/metrics - System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-modules/azure-monitor/src/MetricsScraper.cs:line 72
[2021-08-03 15:48:52.735 INF] Scraping finished, received 0 metrics from endpoint http://edgeAgent:9601/metrics
[2021-08-03 15:48:52.758 INF] Successfully sent metrics via IoT message
[2021-08-03 15:48:52.758 INF] Successfully completed periodic operation Scrape and Upload Metrics

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.Deploy iotedge runtime into a azure kubernetes namespace
2. Deploy metricsCollector and have it scrap (http://edgeAgent:9601/metrics/, http://edgeHub:9602/metrics )
3. check logs of metricsCollector
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

N/A

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Aks Cluster 1.19.7 - AKSUbuntu-1804containerd-2021.02.10
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]:  Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: n/a
* Edge Agent [image tag (e.g. 1.0.0)]: azureiotedge/azureiotedge-agent:0.1.0-beta15
* Edge Hub [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-hub:1.1
* Docker/Moby [run `docker version`]: Kubernetes

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

I suspect dns(coreDns) issues related to my aks cluster that is why i am going provide you with different logs

<details>
<summary>kubectl exec -it metricscollector-74c94567f4-s2xw6 -c metricscollector -n iotedge-sof-lbtwr -- nslookup edgeagent</summary>

```

Server:         10.246.0.10
Address:        10.246.0.10:53

** server can't find edgeagent.svc.cluster.local: NXDOMAIN

** server can't find edgeagent.svc.cluster.local: NXDOMAIN

** server can't find edgeagent.cluster.local: NXDOMAIN

** server can't find edgeagent.cluster.local: NXDOMAIN

Name:   edgeagent.iotedge-sof-lbtwr.svc.cluster.local
Address: 10.246.226.209

*** Can't find edgeagent.iotedge-sof-lbtwr.svc.cluster.local: No answer

** server can't find edgeagent.reddog.microsoft.com: NXDOMAIN

** server can't find edgeagent.reddog.microsoft.com: NXDOMAIN

command terminated with exit code 1


```
</details>

<details>
<summary>kubectl exec -it metricscollector-74c94567f4-s2xw6 -c metricscollector -n iotedge-sof-lbtwr -- nslookup edgehub</summary>

```

Server:         10.246.0.10
Address:        10.246.0.10:53

** server can't find edgehub.cluster.local: NXDOMAIN

** server can't find edgehub.svc.cluster.local: NXDOMAIN

** server can't find edgehub.svc.cluster.local: NXDOMAIN

Name:   edgehub.iotedge-sof-lbtwr.svc.cluster.local
Address: 10.246.35.231

*** Can't find edgehub.iotedge-sof-lbtwr.svc.cluster.local: No answer

** server can't find edgehub.cluster.local: NXDOMAIN

** server can't find edgehub.reddog.microsoft.com: NXDOMAIN

** server can't find edgehub.reddog.microsoft.com: NXDOMAIN

command terminated with exit code 1

```
</details>

<details>

<summary>kubectl exec -it metricscollector-74c94567f4-s2xw6 -c metricscollector -n iotedge-sof-lbtwr -- nslookup edgehub</summary>

```

;; connection timed out; no servers could be reached

command terminated with exit code 1

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

- resolv.conf 
~~~
search iotedge-sof-lbtwr.svc.cluster.local svc.cluster.local cluster.local reddog.microsoft.com
nameserver 10.246.0.10
options ndots:5
~~~

- DnsPolicy : ClusterFirst
- Azure Kubernetes networking : Kubenet

**Comment by veyalla** [comment]
Thanks for the report @omarine! I think you may be correct about suspecting DNS issues in the K8s cluster. As such there is nothing much we can do from the metrics collector standpoint as it relies on the configured metrics endpoints being reachable. 

Couple of follow up questions:

* Does the issue fix itself or remain in broken state forever?
* Is it more stable if you provide more specific endpoint names like `http://edgeagent.iotedge-sof-lbtwr.svc.cluster.local:9601` in the metrics-collector config?

**Comment by veyalla** [comment]
Closing this issue as it seems related more to the K8s environment.
