### ISSUE TITLE
edgeHub module not publishing to IoT Hub when any route is wrong

### ISSUE THREAD

**Issue by iconics-pavel** [Azure/iotedge#5308]
## Expected Behavior
Expected behavior is that invalid route is ignored and edgeHub module is working and connected to IoT Hub.

## Current Behavior
The edgeHub module not publishing to IoT Hub when any route is wrong. 

## Steps to Reproduce
Set the routes on Azure Portal in IoT Edge device configuration, e.g.
"$edgeHub": {
            "properties.desired": {
                "routes": {
                    "route": "FROM /messages/* INTO $upstream",
                    "FromDeviceGatewayToCloud": "FROM /messages/modules/<FROM_MODULE_NAME>/outputs INTO $upstream"
                },
                "schemaVersion": "1.0",
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 7200
                }
            }
        },

The route "FromDeviceGatewayToCloud" is wrongly configured with the template part <FROM_MODULE_NAME> instead of the module name.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

not needed

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04.5 LTS
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.0
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1.4
* Docker/Moby [run `docker version`]: 20.10.7

## Logs

<details>
<summary>edge-hub logs</summary>

```

<6> 2021-08-03 17:17:14.016 +00:00 [INF] - Entering connected state
<6> 2021-08-03 17:17:14.019 +00:00 [INF] - Cloud connection for ubuntu-iot-demo/$edgeHub is True
<6> 2021-08-03 17:17:14.021 +00:00 [INF] - Connection status for ubuntu-iot-demo/$edgeHub changed to ConnectionEstablished
<6> 2021-08-03 17:17:14.022 +00:00 [INF] - Client ubuntu-iot-demo/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2021-08-03 17:17:14.022 +00:00 [INF] - Skipping ubuntu-iot-demo/$edgeHub for subscription processing, as it is currently being processed.
<6> 2021-08-03 17:17:14.023 +00:00 [INF] - Created cloud proxy for client ubuntu-iot-demo/$edgeHub via AMQP, with client operation timeout 20 seconds.
<6> 2021-08-03 17:17:14.026 +00:00 [INF] - Initialized cloud proxy 770505c7-d477-41e2-adbc-3d08ca8f74ab for ubuntu-iot-demo/$edgeHub
<6> 2021-08-03 17:17:14.027 +00:00 [INF] - Created cloud connection for client ubuntu-iot-demo/$edgeHub
<6> 2021-08-03 17:17:14.154 +00:00 [INF] - Processing pending subscriptions for ubuntu-iot-demo/$edgeHub
<6> 2021-08-03 17:17:14.246 +00:00 [INF] - Updated reported properties for ubuntu-iot-demo/$edgeHub
<6> 2021-08-03 17:17:14.315 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<4> 2021-08-03 17:17:14.417 +00:00 [WRN] - Error getting edge hub config from twin desired properties
System.InvalidOperationException: Error parsing route FromDeviceGatewayToCloud - Exception of type 'Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException' was thrown.
 ---> Compilation errors:
StartLine[1], StartColumn[24], EndLine[1], EndColumn[25], Severity[Error], Message: Syntax error.
Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException: Exception of type 'Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException' was thrown.
   at Microsoft.Azure.Devices.Routing.Core.Query.ErrorListener.Validate() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/query/ErrorListener.cs:line 26
   at Microsoft.Azure.Devices.Routing.Core.RouteFactory.ParseRoute(String routeString, IMessageSource& messageSource, String& condition, Endpoint& endpoint) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/RouteFactory.cs:line 66
   at Microsoft.Azure.Devices.Routing.Core.RouteFactory.Create(String routeString, UInt32 priority, UInt32 timeToLiveSecs) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/RouteFactory.cs:line 44
   at Microsoft.Azure.Devices.Edge.Hub.Core.Config.EdgeHubConfigParser.GetEdgeHubConfig(EdgeHubDesiredProperties desiredProperties, RouteFactory routeFactory) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/EdgeHubConfigParser.cs:line 22

   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Config.EdgeHubConfigParser.GetEdgeHubConfig(EdgeHubDesiredProperties desiredProperties, RouteFactory routeFactory) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/EdgeHubConfigParser.cs:line 31
   at Microsoft.Azure.Devices.Edge.Hub.Core.Config.TwinConfigSource.GetConfigInternal() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/TwinConfigSource.cs:line 98
   at Microsoft.Azure.Devices.Edge.Hub.Core.Config.TwinConfigSource.GetConfigInternal() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/TwinConfigSource.cs:line 105
<4> 2021-08-03 17:17:14.434 +00:00 [WRN] - Empty edge hub configuration received. Ignoring...
<6> 2021-08-03 17:17:14.438 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2021-08-03 17:17:14.439 +00:00 [INF] - Initialized edge hub configuration
<6> 2021-08-03 17:17:14.442 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2021-08-03 17:17:14.502 +00:00 [INF] - Scheduling server certificate renewal for "2021-08-10T12:34:41.0000885Z".
<6> 2021-08-03 17:17:14.502 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2021-08-03 17:17:14.504 +00:00 [INF] - Starting MQTT head
<6> 2021-08-03 17:17:14.523 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2021-08-03 17:17:14.561 +00:00 [INF] - Starting AMQP head
<6> 2021-08-03 17:17:14.565 +00:00 [INF] - Started MQTT head
<6> 2021-08-03 17:17:14.626 +00:00 [INF] - Started AMQP head
<6> 2021-08-03 17:17:14.627 +00:00 [INF] - Starting HTTP head
<4> 2021-08-03 17:17:14.757 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2021-08-03 17:17:14.763 +00:00 [INF] - Started HTTP head


```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by nyanzebra** [comment]
Hi, so to be clear... the issue is that in portal the route contains `<FROM_MODULE_NAME>` and instead of issuing an error/warning it allowed one to proceed and then cause errors in EdgeHub later post-deployment?

**Comment by iconics-pavel** [comment]
> 
> 
> Hi, so to be clear... the issue is that in portal the route contains `<FROM_MODULE_NAME>` and instead of issuing an error/warning it allowed one to proceed and then cause errors in EdgeHub later post-deployment?

Yes, exactly.
In my opinion these are two cases that have the same effect:
1. One bad route causes exception in edgeHub module and prevents messages to be sent from my module to IoT Hub.
2. Inconsistency in the routes validation in Azure Portal configuration and in edge runtime module. Even the route is valid in Azure Portal configuration it is not accepted by the runtime module and causes crash.

**Comment by nyanzebra** [comment]
I will respond here for the portal side, I agree that this should be easy to catch and validated before allowing deployment. Let me figure out who is the appropriate team that owns this part of portal and log a bug on them. As I 100% concur that there should be consistency, and if edge doesn't like the route then neither should portal when configuring a device.

**Comment by nyanzebra** [comment]
I have communicated with the team that owns this part of portal and have asked them for a fix, I will see if one of their team members can comment here henceforth

**Comment by iconics-pavel** [comment]
The issue is not fixed yet, I can still see it on my IoT Edge device.
