### ISSUE TITLE
Retrying cloud proxy operation UpdateReportedPropertiesAsync for Station1/$edgeHub.

### ISSUE THREAD

**Issue by nainesh72** [Azure/iotedge#5440]
Hi
I get an error in my IoT edge hub log please give solution 
![image](https://user-images.githubusercontent.com/50742468/131518263-fcee6eea-1f4b-4472-834e-dc64f9bd9da3.png)

<6> 2021-08-31 13:40:10.611 +00:00 [INF] - Closed cloud proxy 3f28ebd3-78f6-4186-ac6b-0560bf627cf7 for Station1/eip2
<6> 2021-08-31 13:40:10.617 +00:00 [INF] - Closing receiver in cloud proxy ed4ff83a-ddeb-4d37-bafc-889bf87ccd16 for Station1/telemetry
<6> 2021-08-31 13:40:10.627 +00:00 [INF] - Closed cloud proxy ed4ff83a-ddeb-4d37-bafc-889bf87ccd16 for Station1/telemetry
<6> 2021-08-31 13:40:10.633 +00:00 [INF] - Retrying cloud proxy operation UpdateReportedPropertiesAsync for Station1/$edgeHub.
System.TimeoutException: The operation timed out.
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.RoundTripTwinMessage(AmqpTwinMessageType amqpTwinMessageType, TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass26_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass29_0.<<SendTwinPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass30_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 180
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 180
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 226
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 226
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.<>c__DisplayClass24_0.<<ExecuteOperation>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.ExecuteOperation[T](Func`2 func, String operation) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 76
<6> 2021-08-31 13:40:10.646 +00:00 [INF] - Attempting to connect to IoT Hub for client Station1/$edgeHub via AMQP...
<6> 2021-08-31 13:40:11.531 +00:00 [INF] - Exiting disconnected state
<6> 2021-08-31 13:40:11.531 +00:00 [INF] - Received device connected callback
<6> 2021-08-31 13:40:11.532 +00:00 [INF] - Done syncing reported properties for Station1/kpi2
<6> 2021-08-31 13:40:11.536 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2021-08-31 13:40:11.536 +00:00 [INF] - Processing subscriptions for client Station1/kpi2 on device connected to cloud.
<6> 2021-08-31 13:40:11.538 +00:00 [INF] - Attempting to connect to IoT Hub for client Station1/kpi2 via AMQP...
<6> 2021-08-31 13:40:11.541 +00:00 [INF] - Processing subs

## Expected Behavior
Tell us what should happen

## Current Behavior
Tell us what happens instead of the expected behavior

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.
2.
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by and-rewsmith** [comment]
@nainesh72 It seems that your device was in a disconnected state, then once it reconnected the updates started going through.
```
<6> 2021-08-31 13:40:11.531 +00:00 [INF] - Exiting disconnected state
<6> 2021-08-31 13:40:11.531 +00:00 [INF] - Received device connected callback
<6> 2021-08-31 13:40:11.532 +00:00 [INF] - Done syncing reported properties for Station1/kpi2
```

That is the intended behavior. Let me know if you have any questions.

**Comment by nainesh72** [comment]
When this 
 2021-08-31 13:40:10.633 +00:00 [INF] - Retrying cloud proxy operation UpdateReportedPropertiesAsync
that time some duplicate message is come not every time but some time

**Comment by and-rewsmith** [comment]
Also, recommend updating to 1.1. See you are still running some 1.0.x.

**Comment by nainesh72** [comment]
Hi
I send a word file for your investigation where i take screen short so you better investinagtion  
![image](https://user-images.githubusercontent.com/50742468/132016083-258b47a9-926e-4180-86b9-d874e7abd624.png)
![image](https://user-images.githubusercontent.com/50742468/132016110-715f22b4-f38c-4a8a-9014-be57cb847f51.png)
![image](https://user-images.githubusercontent.com/50742468/132016143-78ba4e1a-951d-49ca-8ac6-016430603a4c.png)
this one example where the record comes duplicate on a cloud every time the same thing happen i use latest Mobin and edge module 
NAME                        STATUS           DESCRIPTION      CONFIG
IotEdgeModule1              running          Up 17 minutes    iotedgereg.azurecr.io/iotedgemodule1:0.0.1-arm32v7
SimulatedTemperatureSensor  running          Up 17 minutes    mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent                   running          Up 19 minutes    mcr.microsoft.com/azureiotedge-agent:1.2
edgeHub                     running          Up 17 minutes    mcr.microsoft.com/azureiotedge-hub:1.2
pi@raspberrypi:~ $

**Comment by and-rewsmith** [comment]
@nainesh72 I agree with this comment regarding dup messages:
https://github.com/Azure/iotedge/issues/1538#issuecomment-576848708


Since mqtt3 protocol means we have to close the connection for the client, there would have to be some complex synchronization to avoid a dup in any case where we disconnect the client. So given that we support qos1 (at least once) messaging this has been acceptable to us.

Regarding mitigations, if each message was tagged with a unique identifier then it would be possible to filter the dups on the consuming side. Does this mitigation work for you?

**Comment by nainesh72** [comment]
Hi
Here one problem is when the module sends the duplicate record in one after another then we filter, but some time after re-authentication of the module, he does not send the record in  sequence, he send duplicate record after new record so each time we did not go in the database then verified that this record are preset or not, so here record sequence or record number  logic are not working,

**Comment by nainesh72** [comment]
Hi 
I have questaion Rasbarian Bustere is support Tire1 OS for Auzre IOT device

**Comment by nainesh72** [comment]
Hi
I get Solution, I use  Raspbian Buster, But it does not come with  SSL Library libssl1.0.2 os i install SSL Library libssl1.0.2 on Raspbian Buster then all problem solved thanks for support

**Comment by nainesh72** [comment]
Hi
I get Solution, I use Raspbian Buster, But it does not come with SSL Library libssl1.0.2 os i install SSL Library libssl1.0.2 on Raspbian Buster then all problems were solved thanks for the support
