### ISSUE TITLE
edgeAgent cannot start after updating edge runtime from 1.1.3 to 1.1.5

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/iotedge#5465]
## Expected Behavior
The agent should start and work

## Current Behavior
The agent cannot start

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Update runtime by the command `. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Update-IoTEdge`
2. Restart machine
3. edgeAgent cannot start

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Windows Enterprise LTSC 1809
* Architecture [e.g. amd64, arm32, arm64]: AMD64
* Container OS [e.g. Linux containers, Windows containers]: Windows

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.5
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1
* Docker/Moby [run `docker version`]: 19.03.12+azure

## Logs
output of edgeAgent:
```
<6> 2021-09-04 14:45:48.551 +08:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<0> 2021-09-04 14:45:48.824 +08:00 [FTL] - Fatal error building application.
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions. C:\ProgramData\iotedge\workload\sock
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.GetConnectedSocketAsync() in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\uds\HttpUdsMessageHandler.cs:line 47
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\uds\HttpUdsMessageHandler.cs:line 23
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\generatedCode\HttpWorkloadClient.cs:line 700
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 126
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\WorkloadClientVersioned.cs:line 59
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.HandleException(Exception ex, String operation) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\WorkloadClient.cs:line 122
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\WorkloadClientVersioned.cs:line 77
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.GetTrustBundleAsync() in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\WorkloadClient.cs:line 49
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetTrustBundleFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\CertificateHelper.cs:line 266
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Service\Program.cs:line 177
```

**Comment by arsing** [comment]
@yophilav is fixing this in the Windows install script. Once we release it you'll be need to re-download the script from https://github.com/Azure/azure-iotedge/releases/tag/1.1.6 and re-install.

**Comment by yophilav** [comment]
Hello @Dolphinsimon !

Thank you for your patience. We have resolved the issue!
Please feel free to reinstall the iotedge here: https://github.com/Azure/azure-iotedge/releases/tag/1.1.6

You have a wonderful day :)

**Comment by Dolphinsimon** [comment]
> Hello @Dolphinsimon !
> 
> Thank you for your patience. We have resolved the issue!
> Please feel free to reinstall the iotedge here: https://github.com/Azure/azure-iotedge/releases/tag/1.1.6
> 
> You have a wonderful day :)

Do I need to Remove & Re-deploy the runtime? Or just update the runtime to version 1.1.6 ?

**Comment by yophilav** [comment]
@Dolphinsimon 
> Do I need to Remove & Re-deploy the runtime? Or just update the runtime to version 1.1.6 ?

Update the runtime should work.  If somehow your machine got into a weird state, the remove & redeploy will certainly fix it.

**Comment by yophilav** [comment]
@Dolphinsimon 
May I close the issue?

**Comment by Dolphinsimon** [comment]
> @Dolphinsimon
> May I close the issue?

We tested version 1.1.6, problem is fixed.
