### ISSUE TITLE
EdgeAgent module multiple attempts to start the modules lead to instability in the deployment process

### ISSUE THREAD

**Issue by theluckyoak** [Azure/iotedge#5489]
## Expected Behavior
- The IoT Hub where the device is connected contains multiple layered deployments executed on a set of devices depending on the device twin of each. 
- Device connects to the IoT Hub and receives the new deployment according its device twin tags.
- The edgeAgent module starts by pulling all the modules needed to execute the deployment planning and performs the [create/start] actions.
- All modules are up and running with no problems.

## Current Behavior
- The hub where the device is connected contains multiple layered deployments executed on a set of devices depending on the device twin of each. 
- When I connect the device to the Hub initially is possible to see that the edgeAgent is downloaded and after a few minutes the edgeHub is also starts. From then on in a matter of minutes the edgeAgent receives the new manifest according to the tags included in the device twin. Up to this point the behaviour seems to be as expected.
- As soon as the download of the several modules is started, for each one the edgeAgent performs a couple of actions [create/start] where it fails almost in all of them with the error message that I show in the edgeAgent logs below. It should be noted that the errors presented are then overcome by edgeAgent that manages to run all the modules. However, in this trial/error process the time to apply a manifest is really high (around 18 minutes to run 7/8 modules).
- Also the initialization time of the same modules after a reboot is really huge, and no modifications were added on manifest meanwhile.

## Steps to Reproduce
1. Connect device to the IoT Hub
2. Change tags on device twin
3. Wait until new deployment planning starts on edgeAgent side

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname <ADD HOSTNAME HERE> but device reports hostname iot-gate-imx8.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.1.3 but 1.1.6 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-12-09 09:31:33 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
```
</details>

### Device Information
* **Host OS:** Yocto Project Based Distro (dunfell)
* **Architecture:** arm64
* **Container OS:** Linux Containers

### Runtime Versions
* **aziot-edged:** 1.1.3
* **Edge Agent:** 1.1 
* **Edge Hub:** 1.1 
* **Docker:** 19.03.8-ce, build afacb8b7f0

## Logs

<details>
<summary>edge-agent logs</summary>

```

<6> 2021-09-10 11:18:37.263 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module mwEdgeAccount]\n  [Start module mwEdgeAccount]\n)"
<6> 2021-09-10 11:18:37.263 +00:00 [INF] - Executing command: "Create module mwEdgeAccount"
<3> 2021-09-10 11:20:17.272 +00:00 [ERR] - Executing command for operation ["create"] failed.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(Memory`1 buffer, CancellationToken cancellationToken, Int32 bytesAlreadySatisfied, Task semaphoreLockTask)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpBufferedStream.ReadLineAsync(CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpBufferedStream.cs:line 62
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.SetResponseStatusLine(HttpResponseMessage httpResponse, HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 158
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.DeserializeResponse(HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 69
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs:line 40
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.GeneratedCode.EdgeletHttpClient.CreateModuleAsync(String api_version, ModuleSpec module, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/generatedCode/EdgeletHttpClient.cs:line 164
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 128
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 155
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 155
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 102
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 67
<3> 2021-09-10 11:20:17.278 +00:00 [ERR] - Executing command for operation ["Command Group: (\n  [Create module mwEdgeAccount]\n  [Start module mwEdgeAccount]\n)"] failed.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(Memory`1 buffer, CancellationToken cancellationToken, Int32 bytesAlreadySatisfied, Task semaphoreLockTask)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpBufferedStream.ReadLineAsync(CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpBufferedStream.cs:line 62
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.SetResponseStatusLine(HttpResponseMessage httpResponse, HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 158
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.DeserializeResponse(HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 69
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs:line 40
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.GeneratedCode.EdgeletHttpClient.CreateModuleAsync(String api_version, ModuleSpec module, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/generatedCode/EdgeletHttpClient.cs:line 164
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 128
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 155
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 155
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 102
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 67
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 67
<3> 2021-09-10 11:20:17.284 +00:00 [ERR] - Step failed in deployment 7, continuing execution. Failure when running command Command Group: (
  [Create module mwEdgeAccount]
  [Start module mwEdgeAccount]
). Will retry in -05s.
<6> 2021-09-10 11:20:17.284 +00:00 [INF] - Plan execution ended for deployment 7
<3> 2021-09-10 11:20:17.285 +00:00 [ERR] - Edge agent plan execution failed.

```
</details>

<details>
<summary>edge-hub logs</summary>

```
<4> 2021-09-10 10:42:33.258 +00:00 [WRN] - Empty edge hub configuration received. Ignoring...
<6> 2021-09-10 10:42:33.259 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config
<6> 2021-09-10 10:42:33.581 +00:00 [INF] - Updated reported properties for imx8-yocto-pt/$edgeHub
<6> 2021-09-10 10:47:32.752 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-09-10 10:52:32.752 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-09-10 10:57:32.749 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-09-10 11:02:32.750 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-09-10 11:07:32.750 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-09-10 11:12:32.752 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-09-10 11:17:32.753 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-09-10 11:22:32.753 +00:00 [INF] - Entering periodic task to reauthenticate connected clients

```
</details>

## Additional Information
- The gateway runs a very restricted OS in terms of folders and files permissions.
- @jaypaddy

**Comment by ggjjj** [comment]
Can you enable Debug logs for Edge Agent and share them?

**Comment by ggjjj** [comment]
Also if you can provide the conditions for the layer deployments? Just make sure you are not giving any conflicting tag conditions

**Comment by theluckyoak** [comment]
@ggjjj sorry for my late response and thanks in advance for your help with this.

- there is a lot of layered deployments available but all of them follow the same target condition pattern like this one for example: ``tags.application.localApi='0.1.8' and (tags.env='dev' or tags.env='qa' or tags.env='prod')``

- I would find it strange if it is some tag conditions problem because the error still exists even if there is only one module being deployed.

- Regarding the edgeAgent logs with debug mode enabled, I don't find any other relevant information there to be honest and it also logs a lot of stuff containing information I don't want to post here.

**Comment by theluckyoak** [comment]
@ggjjj You can have a look into these logs for example (got them with debug mode enabled): [edgeAgent_log.txt](https://pastebin.com/ktYF5Bp4)

**Comment by derSchtefan** [comment]
@theluckyoak  I had similar errors that were gone after setting the edgeAgent version to 1.1.4

**Comment by theluckyoak** [comment]
> @theluckyoak I had similar errors that were gone after setting the edgeAgent version to 1.1.4
> 
> You might want to also do it in the config.yaml of the iotedged.

@derSchtefan I will try your solution today, expect some feedback in the next hours.
In fact, I changed the Yocto build we have to include the LTS iotedge version (1.1.3) hoping it would solve the problem but never had the idea to update to new versions of edgeAgent or edgeHub.

Thanks in advance!

**Comment by theluckyoak** [comment]
- @derSchtefan After some stress tests using "heavy" deployments (some were the same causing described issue) it seems that updating the `edgeAgent` version from `1.1` to  `1.1.4` solved the problem.
- @ggjjj  I think is still relevant if we can know the meaning of logged errors to make debugging easier in case of similar future issues.

Thanks a lot! 👍🏼
