### ISSUE TITLE
CloudProxy uses IClient that can be disposed out of its own scope

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#57]
## Expected Behavior
Once IClient is disposed it should try to recreate connection.

## Current Behavior
Somewhere in the edgeHub IClient is disposed and this object is passed into CloudProxy. Once it is disposed edge hub is unable to receive messages from cloud.

2018-07-23 13:43:29.347 +00:00 [ERR] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy] - Error receiving message for device cmk21218-99999
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The object has been closed and cannot be reopened.'.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutMessage>b__63_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.CloudReceiver.SetupMessageListening(IClient deviceClient) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 239
2018-07-23 13:43:29.347 +00:00 [ERR] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy] - Error receiving message for device cmk21218-99999
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The object has been closed and cannot be reopened.'.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutMessage>b__63_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.CloudReceiver.SetupMessageListening(IClient deviceClient) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 239
2018-07-23 13:43:29.348 +00:00 [ERR] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy] - Error receiving message for device cmk21218-99999
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The object has been closed and cannot be reopened.'.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutMessage>b__63_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.CloudReceiver.SetupMessageListening(IClient deviceClient) in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 239

EdgeHub is flooded with logs because it ends in infinite loop

 async Task SetupMessageListening(IClient deviceClient)
            {
                Message clientMessage = null;
                try
                {
                    **while (!this.cancellationTokenSource.Token.IsCancellationRequested)**
                    {
                        try
                        {
                            clientMessage = await deviceClient.ReceiveAsync(ReceiveMessageTimeout);
                            if (clientMessage != null)
                            {
                                Events.MessageReceived(this.cloudProxy.clientId);
                                IMessageConverter<Message> converter = this.cloudProxy.messageConverterProvider.Get<Message>();
                                IMessage message = converter.ToMessage(clientMessage);
                                // TODO: check if message delivery count exceeds the limit?
                                await this.cloudListener.ProcessMessageAsync(message);
                            }
                        }
                        catch (Exception e)
                        {
                            if (e is UnauthorizedException)
                            {
                                throw;
                            }
                            // continue when the client times out
                            // TODO: should limit the timeout?
                            Events.ErrorReceivingMessage(this.cloudProxy.clientId, e);
                        }
                    }
                    Events.ReceiverStopped(this.cloudProxy.clientId);
                }
                catch (Exception ex)
                {
                    Events.TerminatingErrorReceivingMessage(this.cloudProxy.clientId, ex);
                    this.receiveMessageTask = Option.None<Task>();
                    await this.cloudProxy.HandleException(ex);
                }
                finally
                {
                    clientMessage?.Dispose();
                }
            }

## Steps to Reproduce

Edge was running for a 5 days and we observed this problem today.

### Device (Host) Operating System

Ubuntu 18.04

### Architecture

amd64

### Container Operating System

Linux

#### iotedged

iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent

 mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub

 mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker

Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Mon Jun 25 21:07:53 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Mon Jun 25 20:43:05 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by darobs** [comment]
Hello @AdamMachera,

Thank you for reporting this bug.  I will log this in our backlog and let the development team know.

**Comment by myagley** [comment]
This should be fixed by https://github.com/Azure/iotedge/pull/28/ and will be in the next release.

**Comment by myagley** [comment]
This has been fixed in version 1.0.1 of the IoT Edge runtime, released this morning. Closing this issue.
