### ISSUE TITLE
EdgeHub cannot start after restarted with different Edge Device Identity

### ISSUE THREAD

**Issue by Suizi11** [Azure/iotedge#5725]
Our Edge Devices in the IoT Hub are logical entities which are assigned to a specific user. Sometimes it's necessary to switch the physical devices between different users. This means, that the device reboots and the provisioning services provides another Edge Device ID. Of course, the DPS individual enrollment was changed before.

Sometimes it happens that the edgeHub module crashes repeatedly, when it was already used at another customer. The initial start does always work.

It has something to do with the persistent storage, because if the edgeHub folder is deleted and the edgeHub is restarted everything works as expected.

Log of edgeHub:
```
[root@ntuity-4c38d5121c18 ~]# docker logs edgeHub
2021-10-18 12:22:45  Starting Edge Hub
2021-10-18 12:22:45.998 +00:00 Edge Hub Main()
<6> 2021-10-18 12:22:48.002 +00:00 [INF] - Installing certificates [CN=iotedged workload ca, *********] to Root
<6> 2021-10-18 12:22:48.099 +00:00 [INF] - Installing certificates [CN=********] to Root
<6> 2021-10-18 12:22:48.125 +00:00 [INF] - Enabling SSL protocols: Tls, Tls11, Tls12
<6> 2021-10-18 12:22:48.485 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
<6> 2021-10-18 12:22:49.868 +00:00 [INF] - Created persistent store at /iotedge/storage/edgeHub
<6> 2021-10-18 12:22:50.050 +00:00 [INF] - Initializing Edge Hub
<6> 2021-10-18 12:22:50.051 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2021-10-18 12:22:50.055 +00:00 [INF] - Version - 1.1.7.47774436 (3af6c9732c7a26027e4dc9973ab34038abcb81ab)
<6> 2021-10-18 12:22:50.056 +00:00 [INF] - OptimizeForPerformance=False
<6> 2021-10-18 12:22:50.056 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2021-10-18 12:22:50.064 +00:00 [INF] - Loaded server certificate with expiration date of "2022-01-16T12:22:46.0000000+00:00"
<6> 2021-10-18 12:22:50.091 +00:00 [INF] - Using Asp Net server for metrics
<6> 2021-10-18 12:22:50.271 +00:00 [INF] - Created new message store
<6> 2021-10-18 12:22:50.280 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2021-10-18 12:22:50.519 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
Unhandled exception. System.AggregateException: One or more errors occurred. (Operation timed out)
 ---> System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 141
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.ReadCacheFromStore(IKeyValueStore`2 encryptedStore) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 202
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.Create(IServiceProxy serviceProxy, IKeyValueStore`2 encryptedStorage, TimeSpan refreshRate, TimeSpan refreshDelay) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 69
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__24_14(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 295
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__31_10(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 228
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__31_12(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 265
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__31_25(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 450
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__31_29(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 520
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 76
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 33
```

The edgeHub config in the deployment manifest:
```
"edgeHub": {
                    "type": "docker",
                    "status": "running",
                    "restartPolicy": "always",
                    "settings": {
                        "image": "mcr.microsoft.com/azureiotedge-hub:1.1",
                        "createOptions": "{\"HostConfig\":{\"Binds\":[\"/etc/iotedge/storage/:/iotedge/storage/\"],\"PortBindings\":{\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}]}}}"
                    },
                    "env": {
                        "OptimizeForPerformance": {
                            "value": "false"
                        },
                        "storageFolder": {
                            "value": "/iotedge/storage/"
                        }
                    }
                }
```

### Device Information
CentOS 8 Stream
1.0.10.1
Linux Containers

### Runtime Versions
iotedge 1.0.10.1
Edge Agent 1.1.7
Edge Hub 1.1.7
Moby 3.0.8

**Comment by nlcamp** [comment]
@Suizi11 - I 'm working on a repro at the moment but haven't yet seen the errors you're reporting. Can you answer the following questions to help me create a closer match to your scenario?

1. You mentioned that initial startup is always fine but eventually Edge Hub starts to repeatedly crash. How long after startup did it usually take for this to occur? Did it vary? Looking at the log output you provided, unfortunately the 'Unhandled exception' doesn't have a timestamp.
2. Are you using symmetric key or X.509 authentication?
3. Are you still experiencing this with the latest 1.1.8 release?

**Comment by Suizi11** [comment]
@nlcamp thank, I know that it's not that easy to reproduce this. We're in this state every 1-2 weeks, should I export anything else the next time? E.g. the storage directory of the edgeHub, journald logs of the daemon, etc.?

1. Sorry, with initial startup I meant the first time. The device ID must be changed in the DPS (for the same enrollment) and restart the edge daemon (systemctl restart iotedge). Then the edgeAgent and edgeHub start up with a new device identity, although in the storage there's still some data of the identity before.
2. Neither nor, TPM
3. Will test it this week

In the meanwhile we had also an issue in the edgeAgent after changing the device identity:
```
2021-11-22T15:56:13.349381320Z 2021-11-22 15:56:13  Starting Edge Agent
2021-11-22T15:56:13.373209346Z 2021-11-22 15:56:13  Changing ownership of storage folder: /iotedge/storage//edgeAgent to 1000
2021-11-22T15:56:13.380467084Z 2021-11-22 15:56:13  Changing ownership of management socket: /var/lib/iotedge/mgmt.sock
2021-11-22T15:56:17.641610733Z 2021-11-22 15:56:17.531 +00:00 Edge Agent Main()
2021-11-22T15:56:18.642024772Z <6> 2021-11-22 15:56:18.568 +00:00 [INF] - Initializing Edge Agent.
2021-11-22T15:56:19.436781459Z <6> 2021-11-22 15:56:19.436 +00:00 [INF] - Version - 1.1.8.48502653 (54b31809c98ee83e36679ecf92c5582de37172c4)
2021-11-22T15:56:19.438427249Z <6> 2021-11-22 15:56:19.437 +00:00 [INF] - 
2021-11-22T15:56:19.438504853Z         █████╗ ███████╗██╗   ██╗██████╗ ███████╗
2021-11-22T15:56:19.438515203Z        ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
2021-11-22T15:56:19.438522654Z        ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
2021-11-22T15:56:19.438529653Z        ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
2021-11-22T15:56:19.438536755Z        ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
2021-11-22T15:56:19.438543985Z        ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
2021-11-22T15:56:19.438551567Z 
2021-11-22T15:56:19.438557898Z  ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
2021-11-22T15:56:19.438565330Z  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
2021-11-22T15:56:19.438572648Z  ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
2021-11-22T15:56:19.438614432Z  ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
2021-11-22T15:56:19.438622721Z  ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
2021-11-22T15:56:19.438630072Z  ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝
2021-11-22T15:56:19.438637216Z 
2021-11-22T15:56:19.633848321Z <6> 2021-11-22 15:56:19.633 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
2021-11-22T15:56:20.653901433Z <6> 2021-11-22 15:56:20.653 +00:00 [INF] - Installing certificates [CN=**** IoT Root CA, OU=****, O=****, L=****, S=****, C=AT:09/01/2030 14:01:00] to Root
2021-11-22T15:56:21.117094767Z <6> 2021-11-22 15:56:21.116 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics
2021-11-22T15:56:22.140047050Z <6> 2021-11-22 15:56:22.139 +00:00 [INF] - Updating performance metrics every 05m:00s
2021-11-22T15:56:22.153822743Z <6> 2021-11-22 15:56:22.153 +00:00 [INF] - Started operation Get system resources
2021-11-22T15:56:22.159474109Z <6> 2021-11-22 15:56:22.158 +00:00 [INF] - Collecting metadata metrics
2021-11-22T15:56:22.461686033Z <6> 2021-11-22 15:56:22.461 +00:00 [INF] - Set metadata metrics: 1.1.8.48502653 (54b31809c98ee83e36679ecf92c5582de37172c4), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"x86_64","Version":"1.0.10.1","Provisioning":{"Type":"dps.tpm","DynamicReprovisioning":false},"ServerVersion":"3.0.8","KernelVersion":"4.18.0-277.el8.x86_64","OperatingSystem":"CentOS Stream 8","NumCpus":4,"Virtualized":"no"}, True
2021-11-22T15:56:22.538276402Z <6> 2021-11-22 15:56:22.537 +00:00 [INF] - Started operation Checkpoint Availability
2021-11-22T15:56:22.581011170Z <6> 2021-11-22 15:56:22.580 +00:00 [INF] - Started operation refresh twin config
2021-11-22T15:56:22.657383615Z <6> 2021-11-22 15:56:22.656 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
2021-11-22T15:56:24.207649286Z <6> 2021-11-22 15:56:24.207 +00:00 [INF] - Created persistent store at /iotedge/storage/edgeAgent
2021-11-22T15:56:24.479982628Z <6> 2021-11-22 15:56:24.479 +00:00 [INF] - Started operation Metrics Scrape
2021-11-22T15:56:24.484025460Z <6> 2021-11-22 15:56:24.483 +00:00 [INF] - Started operation Metrics Upload
2021-11-22T15:56:24.489272165Z Scraping frequency: 01:00:00
2021-11-22T15:56:24.489353438Z Upload Frequency: 1.00:00:00
2021-11-22T15:56:25.449421722Z <6> 2021-11-22 15:56:25.448 +00:00 [INF] - Registering request handler UploadModuleLogs
2021-11-22T15:56:25.449980338Z <6> 2021-11-22 15:56:25.449 +00:00 [INF] - Registering request handler GetModuleLogs
2021-11-22T15:56:25.450758997Z <6> 2021-11-22 15:56:25.450 +00:00 [INF] - Registering request handler UploadSupportBundle
2021-11-22T15:56:25.451404354Z <6> 2021-11-22 15:56:25.451 +00:00 [INF] - Registering request handler RestartModule
2021-11-22T15:56:25.474413666Z <6> 2021-11-22 15:56:25.473 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
2021-11-22T15:56:25.775754551Z <6> 2021-11-22 15:56:25.775 +00:00 [INF] - Initialized new module client with subscriptions enabled
2021-11-22T15:56:25.953085375Z <6> 2021-11-22 15:56:25.952 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 2 and reported properties version 5.
2021-11-22T15:56:32.120530064Z <4> 2021-11-22 15:56:31.878 +00:00 [WRN] - There was an error deserializing stored deployment configuration information
2021-11-22T15:56:32.120649794Z Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadCommunicationException- Message:Error calling Decrypt: Could not decrypt
2021-11-22T15:56:32.120666049Z 	caused by: An error occurred in the key store.
2021-11-22T15:56:32.120708469Z 	caused by: HSM failure
2021-11-22T15:56:32.120718209Z 	caused by: HSM API failure occurred: 431, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2018_06_28.WorkloadClient.HandleException(Exception ex, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2018_06_28/WorkloadClient.cs:line 109
2021-11-22T15:56:32.120726685Z    at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 77
2021-11-22T15:56:32.120734873Z    at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2018_06_28.WorkloadClient.DecryptAsync(String initializationVector, String encryptedText) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2018_06_28/WorkloadClient.cs:line 79
2021-11-22T15:56:32.120742675Z    at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.<>c__DisplayClass16_0.<<Create>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 89
2021-11-22T15:56:32.120751281Z --- End of stack trace from previous location where exception was thrown ---
2021-11-22T15:56:32.120758474Z    at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.Create(IConfigSource configSource, IPlanner planner, IPlanRunner planRunner, IReporter reporter, IModuleIdentityLifecycleManager moduleIdentityLifecycleManager, IEnvironmentProvider environmentProvider, IEntityStore`2 configStore, ISerde`1 deploymentConfigInfoSerde, IEncryptionProvider encryptionProvider, IDeploymentMetrics deploymentMetrics) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 86
2021-11-22T15:56:33.583670038Z <6> 2021-11-22 15:56:33.583 +00:00 [INF] - Plan execution started for deployment 2
```

**Comment by nlcamp** [comment]
@Suizi11 - I see that you also have an active support ticket. Next time this happens, please capture a full support-bundle and upload it to your support ticket (not to this GH issue so that we avoid posting any private information in this public forum). To generate a support bundle, run `sudo iotedge support-bundle` from the command line on the Edge device.

I'm wondering if this issue has something to do with some kind of race condition where the data in edgeHub and edgeAgent storage is not fully cleaned up before the device identity change. If so, EH or EA may be attempting to decrypt data associated with the old device identity, which of course won't work. I'll look into whether this is possible.

**Comment by nlcamp** [comment]
Note: This appears to be the same error that another user reported in https://github.com/Azure/iotedge/issues/5503. In that case, the fix was to use the same workaround that @Suizi11 has mentioned on this ticket (i.e. delete the persisted storage directory and restart iotedge).
