### ISSUE TITLE
edgeAgent 1.1.8 - Error socket forbidden on Windows Server 2019

### ISSUE THREAD

**Issue by nouira** [Azure/iotedge#5860]
## Expected Behavior
edgeAgent boot without errors

## Current Behavior
Starting edgeAgent fail with an exception
```
<0> 2021-11-22 16:39:15.775 -05:00 [FTL] - Fatal error building application.
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions. C:\ProgramData\iotedge\workload\sock
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.GetConnectedSocketAsync() in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\uds\HttpUdsMessageHandler.cs:line 47
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\uds\HttpUdsMessageHandler.cs:line 23
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\generatedCode\HttpWorkloadClient.cs:line 700
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 126
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\WorkloadClientVersioned.cs:line 59
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.HandleException(Exception ex, String operation) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\WorkloadClient.cs:line 122
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\WorkloadClientVersioned.cs:line 77
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.GetTrustBundleAsync() in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\WorkloadClient.cs:line 49
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetTrustBundleFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\CertificateHelper.cs:line 266
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in D:\a\_work\1\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Service\Program.cs:line 177
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Update iotedged and edgeAgent to 1.1.8 from 1.0.10

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: identity certificates expiry - OK
√ production readiness: certificates - OK
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

19 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS : Windows Server 2019
* Architecture : amd64
* Container OS : Windows containers

### Runtime Versions
* aziot-edged : iotedge 1.1.8 (54b31809c98ee83e36679ecf92c5582de37172c4)
* Edge Agent : 1.1.8 
* Edge Hub : - 
* Docker/Moby: 
```
      Client:
       Version:           19.03.12+azure
       API version:       1.40
       Go version:        go1.13.11
       Git commit:        0ed913b885c8919944a2e4c8d0b80a318a8dd48b
       Built:             Wed Jun 17 17:27:03 2020
       OS/Arch:           windows/amd64
       Experimental:      false
      
      Server:
       Engine:
        Version:          19.03.12+azure
        API version:      1.40 (minimum version 1.24)
        Go version:       go1.13.11
        Git commit:       9dc6525e6118a25fab2be322d1914740ea842495
        Built:            Fri Jul 31 21:31:52 2020
        OS/Arch:          windows/amd64
        Experimental:     false
```

## Logs
<details>
<summary>edge-agent logs</summary>

```

2021-11-22 21:39:13.302 +00:00 Edge Agent Main()
<6> 2021-11-22 16:39:14.821 -05:00 [INF] - Initializing Edge Agent.
<6> 2021-11-22 16:39:15.450 -05:00 [INF] - Version - 1.1.8.48502653 (54b31809c98ee83e36679ecf92c5582de37172c4)
<6> 2021-11-22 16:39:15.451 -05:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2021-11-22 16:39:15.520 -05:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<0> 2021-11-22 16:39:15.775 -05:00 [FTL] - Fatal error building application.
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions. C:\ProgramData\iotedge\workload\sock
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.GetConnectedSocketAsync() in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\uds\HttpUdsMessageHandler.cs:line 47
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\uds\HttpUdsMessageHandler.cs:line 23
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\generatedCode\HttpWorkloadClient.cs:line 700
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 126
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\WorkloadClientVersioned.cs:line 59
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.HandleException(Exception ex, String operation) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\WorkloadClient.cs:line 122
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\WorkloadClientVersioned.cs:line 77
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.GetTrustBundleAsync() in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\WorkloadClient.cs:line 49
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetTrustBundleFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId) in D:\a\_work\1\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\CertificateHelper.cs:line 266
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in D:\a\_work\1\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Service\Program.cs:line 177

```
</details>

**Comment by huguesBouvier** [comment]
1.1.8 has some changes related to workload socket.
Each module now has its own workload socket and those sockets are located here: $EdgeDataDirectory\mnt

The permissions for this mnt folder is set in the install script: IotEdgeSecurityDaemon.ps1 but only in the script provided with the latest version:
![image](https://user-images.githubusercontent.com/33438817/143162215-bd8a9c7d-d88c-4831-a05f-863147fa0880.png)

Can you check that you are using the latest script and not the one from 1.0.10?
Could you also check the permissions on the mnt folder?

**Comment by nouira** [comment]
Actually, I used the last script.
The problem is resolved when I did an uninstall and then a new installation.
I guess the update doesn't change the folder permissions.
I tried manually but without success.

**Comment by huguesBouvier** [comment]
Thanks for the feedback, we will check it out
