### ISSUE TITLE
Azure module mcr.microsoft.com/azureiotedge-simulated-temperature-sensor does not works when network mode is host

### ISSUE THREAD

**Issue by allenzt** [Azure/iotedge#6096]
## Expected Behavior
azureiotedge-simulated-temperature-sensor can connect to edgeHub and report its message to IoT Hub

## Current Behavior
I encounter the below issue when azureiotedge-simulated-temperature-sensor's network mode is HOST
```sh
[2022-02-07 09:14:39 +00:00]: Starting Module
SimulatedTemperatureSensor Main() started.
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Start delay set to 00:00:00.
[Information] [02/07/2022 09:14:42]: Trying to initialize module client using transport type [Amqp_Tcp_Only].
Unhandled exception. System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at SimulatedTemperatureSensor.Program.<>c__DisplayClass19_0.<<CreateModuleClientAsync>b__1>d.MoveNext() in /mnt/vss/_work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 299
--- End of stack trace from previous location where exception was thrown ---
   at SimulatedTemperatureSensor.Program.CreateModuleClientAsync(TransportType transportType, ITransientErrorDetectionStrategy transientErrorDetectionStrategy, RetryStrategy retryStrategy) in /mnt/vss/_work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 277
   at SimulatedTemperatureSensor.Program.MainAsync() in /mnt/vss/_work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 85
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SimulatedTemperatureSensor.Program.Main() in /mnt/vss/_work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 50
[2022-02-07 09:19:05 +00:00]: Starting Module
```

## Steps to Reproduce
Please use the below deploment.json and let  Azure IoT edge device connect to it
[deployment.log](https://github.com/Azure/iotedge/files/8022277/deployment.log)

### Device Information
* Host OS : Linux 4.4.60
* Architecture : arm32 
* Container OS : Linux containers

### Runtime Versions
* iotedged:  1.1.3
* Edge Agent  : 1.1
* Edge Hub : 1.1
* Docker/Moby [run `docker version`]: 
 ```sh
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74
 Built:             Thu Feb 13 01:25:46 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74
  Built:            Thu Feb 13 01:51:06 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

**Comment by brotherneeru** [comment]
@allenzt Taking a look at this for you. I deployed your manifest and see no issue with the simulated-temp-sensor:
```
SimulatedTemperatureSensor Main() started.
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Start delay set to 00:00:00.
[Information] [03/16/2022 20:32:39]: Trying to initialize module client using transport type [Amqp_Tcp_Only].
[Information] [03/16/2022 20:32:44]: Successfully initialized module client of transport type [Amqp_Tcp_Only].
        03/16/2022 20:32:44> Sending message: 1, Body: [{"machine":{"temperature":21.440412723780803,"pressure":1.0501736014433827},"ambient":{"temperature":20.617717052399048,"humidity":26},"timeCreated":"2022-03-16T20:32:44.4667017Z"}]
        03/16/2022 20:32:49> Sending message: 2, Body: [{"machine":{"temperature":21.304038247467968,"pressure":1.0346372686988825},"ambient":{"temperature":21.314574089280597,"humidity":24},"timeCreated":"2022-03-16T20:32:49.5822876Z"}]
        03/16/2022 20:32:54> Sending message: 3, Body: [{"machine":{"temperature":21.523185506590263,"pressure":1.0596034121431945},"ambient":{"temperature":20.619724902845793,"humidity":26},"timeCreated":"2022-03-16T20:32:54.6147182Z"}]
```

**Comment by brotherneeru** [comment]
@allenzt Following up on the comment above. Issue seems to be resolved. Can you retry with latest versions?

**Comment by dengzt-inhand** [comment]
@brotherneeru Thanks anyway, I deploy this manifest on Ubuntu 18.04 virtual machine with 1.1.3 iotedge, it works normal. And I also do the test per #1982, but it does not works.  Could you give me some suggestion to further debug?

**Comment by brotherneeru** [comment]
@dengzt-inhand Hello . Glad to help, but I will go ahead and close this issue due to it being related to azureiotedge-simulated-temperature-sensor failing. Please open another issue with the problem at hand and additional details and we will be able to help you
