### ISSUE TITLE
Best practice to anonymously send blob connection string to iot edge module?

### ISSUE THREAD

**Issue by ziutoslav** [Azure/iotedge#6124]
Hi,

Right now I'm facing problem how to properly use IoT edge modules and key vault secrets. I would like to provide iot edge module information about connection string, to use it to download data from blob storage. I added blob container and iot hub services to key vault access policies, however when I try to connect to key vault to read secret value (via PythonSDK and DefaultAzureCredential), I've got following information 
```
Traceback (most recent call last):
  File "./key_vault.py", line 22, in <module>
    retrieved_secret = client.get_secret(secretName)
  File "/root/.local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret
    **kwargs
  File "/root/.local/lib/python3.7/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1515, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/azure/keyvault/secrets/_generated/v7_2/operations/_key_vault_client_operations.py", line 286, in get_secret
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/root/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/root/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/root/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/root/.local/lib/python3.7/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/root/.local/lib/python3.7/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/root/.local/lib/python3.7/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 111, in send
    self._handle_challenge(request, challenge)
  File "/root/.local/lib/python3.7/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 137, in _handle_challenge
    self._token = self._credential.get_token(scope)
  File "/root/.local/lib/python3.7/site-packages/azure/identity/_credentials/default.py", line 150, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/azure/identity/_credentials/chained.py", line 90, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
        AzureCliCredential: Azure CLI not found on path
        AzurePowerShellCredential: PowerShell is not installed

```

Unfortunately until now I was not able to find any tutorial or example, how to handle similar problem. I would be more than grateful if I could receive some hints how to progress.

**Comment by nlcamp** [comment]
@ziutoslav - The stacktrace in your post seems to indicate that you need to specify credentials using one of the mechanisms listed on the following page: https://docs.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#defaultazurecredential

As a test, you can try the environment variable mechanism by specifying credentials using one of the 3 sets of env vars listed on the following page (i.e. you would specify the env vars in your Edge deployment in the section associated with the module that's using the PythonSDK): https://docs.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#environment-variables.

**Comment by micahl** [comment]
@ziutoslav did nlcamp's response help address your question on ways to progress?

**Comment by nlcamp** [comment]
@ziutoslav - I hope you have resolved the errors you were seeing. I'm closing this ticket because we have not heard from you. Please feel free to re-open it if necessary.
