### ISSUE TITLE
EdgeAgent doesnt start after setting up TPM

### ISSUE THREAD

**Issue by hari0015** [Azure/iotedge#6228]
All the steps provided in this link https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-devices-at-scale-linux-tpm?view=iotedge-2020-11&tabs=physical-device%2Cubuntu were followed.  Bur the EdgeAgent failed to start. 

2022-03-09 14:05:25  Starting Edge Agent
2022-03-09 14:05:25  Changing ownership of storage folder: /tmp/edgeAgent to 1000
2022-03-09 14:05:25  Changing ownership of management socket: /var/run/iotedge/mgmt.sock
2022-03-09 14:05:25.263 +00:00 Edge Agent Main()
<6> 2022-03-09 14:05:25.372 +00:00 [INF] - Initializing Edge Agent.
<6> 2022-03-09 14:05:25.453 +00:00 [INF] - Version - 1.2.8.52451243 (9a0b369e60ef4cc8716d5fa8659a6f9c327eb43a)
<6> 2022-03-09 14:05:25.454 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2022-03-09 14:05:25.476 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<0> 2022-03-09 14:05:25.511 +00:00 [FTL] - Fatal error building application.
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (13): Permission denied /var/run/iotedge/workload.sock
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs:line 30
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/generatedCode/HttpWorkloadClient.cs:line 700
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 126
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 59
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.HandleException(Exception ex, String operation) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 122
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 77
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.GetTrustBundleAsync() in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 49
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetTrustBundleFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 263
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 183

**Comment by huguesBouvier** [comment]
Could you do ls -l in the repo  /var/lib/aziot/edged/mnt/ and  /var/run/iotedge/workload.sock   and show us the result?
Let's check the permissions.

**Comment by yophilav** [comment]
@hari0015 
Could you provide us with more information please?

**Comment by hari0015** [comment]
> @hari0015 Could you provide us with more information please?
Here is attached results in screen shot 
<img width="1167" alt="Screenshot 2022-04-01 at 11 53 30" src="https://user-images.githubusercontent.com/6584281/161230049-bad73ad6-81a7-460b-8838-2395b32a6374.png">

**Comment by huguesBouvier** [comment]
This might be the issue:
Which version of iotedge runtime are you using? It looks like you are using edgeHub 1.2.8 but edge runtime is older 1.1.x
Older edge runtime (below 1.1.9) will exhibit that behavior.

**Comment by hari0015** [comment]
> This might be the issue: Which version of iotedge runtime are you using? It looks like you are using edgeHub 1.2.8 but edge runtime is older 1.1.x Older edge runtime (below 1.1.9) will exhibit that behavior.

@huguesBouvier   Here is version number 
![image](https://user-images.githubusercontent.com/6584281/161329340-bf023b39-391b-4253-807f-e3c468e83382.png)

**Comment by huguesBouvier** [comment]
With 1.2.8 you should have the folder /var/lib/aziot/edge/mnt something seems wrong.

1. Have you changed the default option?
![image](https://user-images.githubusercontent.com/33438817/161855888-fd864cc6-f7f6-4b49-81fe-6d843a2e6544.png)
2. Did you upgrade from 1.1.x? If you did, have you applied the config/restart/deleted the container?
3. Is the higher level repo present?  /var/lib/aziot

Could you give us the following?:
sudo docker inspect edgeAgent
sudo journalctl -u aziot-edged (with the beginning of the log, you might have to restart_

**Comment by garyJune** [comment]
encountering similar issue on a Stack Edge Server. Any Suggestions?

**Comment by micahl** [comment]
Closing as the issue has gone stale.  If someone has additional info to share (using a recent release) that might help with the investigation then please reactivate.
