### ISSUE TITLE
Collect and transport metrics

### ISSUE THREAD

**Issue by samuelracine1994** [Azure/iotedge#6237]
I'm trying to add the module Azure IoT Edge Metrics Collector in edge,
the upload target is IoTMessage, (Please tell me the information you would need other than this.)
 but I'm getting the following errors : 

[2022-03-25 17:13:16.370 ERR] Error occurred during metrics collection setup.

System.Net.Http.HttpRequestException: Name does not resolve

---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve

at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

--- End of inner exception stack trace ---

at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

at Microsoft.Azure.Devices.Client.HsmAuthentication.GeneratedCode.HttpHsmClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken)

at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleWithRetry(HttpHsmClient hsmHttpClient, String apiVersion)

at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleAsync(Uri providerUri, String apiVersion)

at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()

at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.BuildModuleClientWrapperAsync(ITransportSettings[] transportSettings) in /home/vsts/work/1/s/edge-modules/azure-monitor/src/ModuleClientWrapper.cs:line 28

at Microsoft.Azure.Devices.Edge.Azure.Monitor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/azure-monitor/src/Program.cs:line 54

[2022-03-25 17:13:16.384 INF] MetricsCollector Main() finished.

[2022-03-25 17:13:16.385 INF] Termination requested, initiating shutdown.

[2022-03-25 17:13:16.385 INF] Waiting for cleanup to finish

[2022-03-25 17:13:16.385 INF] Done with cleanup. Shutting down.

[2022-03-25 17:18:16 : Starting Module

[2022-03-25 17:18:17.106 INF] Initializing metrics collector

[2022-03-25 17:18:17.195 INF] Version - 1.0.0

[2022-03-25 17:18:17.198 DBG] Waiting on shutdown handler to trigger

[2022-03-25 17:18:17.282 INF] Metrics collector initialized with the following settings:



**Comment by huguesBouvier** [comment]
I am not familiar with metric collector but it looks like it is not able to resolve the name of the upstream host.
The process to set it up is here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-collect-and-transport-metrics?view=iotedge-2020-11&tabs=iothub#upload-target
What is the value of the "upload target"? Can you resolve the address from inside the container (You can test it by simply curling it from inside, you may have to install curl inside)?

**Comment by samuelracine1994** [comment]
The upload target is "IoTMessage", and the container does not live long enough to be able to debug it correctly because it crashes at the start...
though I do have other container linked to the edge agent and edge hub that works perfectly.
I have already succeded to create a functionning metric collector but this time it cause this error and I can't seem to find the cause... But I am sure that the configuration should be okay

**Comment by huguesBouvier** [comment]
From the error: System.Net.Http.HttpRequestException: Name does not resolve
It mean that it is not able to resolve the endpoint from inside the container.
- That would happen if the endpoint is a hostname not on the docker network and not separated by "."
- Simply not existing

**Comment by jlian** [comment]
Hi @samuelracine1994 have you had a chance to try @huguesBouvier's suggestion of 

> Can you resolve the address from inside the container (You can test it by simply curling it from inside, you may have to install curl inside)?
