### ISSUE TITLE
IotHubCommunicationException: MQTT channel open failed

### ISSUE THREAD

**Issue by bruno-motacardoso** [Azure/iotedge#6277]
## Expected Behavior
Our module should be able to continuously send telemetry messages. Connectivity issues to the cloud and to edgeHub are expected to be handled by Microsoft modules.

## Current Behavior
Our module should can't send telemetry message, the following exception is throw:

```
2022-04-10T17:51:45.360905041Z       Error: MQTT channel open failed.
2022-04-10T17:51:45.360908441Z Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel open failed.
2022-04-10T17:51:45.360914241Z    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<>c__DisplayClass102_0.<<CreateChannelFactory>b__0>d.MoveNext()
2022-04-10T17:51:45.360918141Z --- End of stack trace from previous location where exception was thrown ---
2022-04-10T17:51:45.360921341Z    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
2022-04-10T17:51:45.360924542Z    at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
2022-04-10T17:51:45.360927842Z    at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
2022-04-10T17:51:45.360931042Z    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
2022-04-10T17:51:45.360934742Z --- End of stack trace from previous location where exception was thrown ---
2022-04-10T17:51:45.360937842Z    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
2022-04-10T17:51:45.360941242Z    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass38_0.<<OpenInternalAsync>b__0>d.MoveNext()
2022-04-10T17:51:45.360951442Z --- End of stack trace from previous location where exception was thrown ---
2022-04-10T17:51:45.360954842Z    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
2022-04-10T17:51:45.360958042Z    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext()
2022-04-10T17:51:45.360961542Z --- End of stack trace from previous location where exception was thrown ---
2022-04-10T17:51:45.360964642Z    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
2022-04-10T17:51:45.360967942Z    at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
2022-04-10T17:51:45.360971742Z    at M2C.Edge.Module.Acquisition.Orbiwise.Program.PipeMessage(MqttApplicationMessage message, Object userContext) in /app/M2C.Edge.Module.Acquisition.Orbiwise/Program.cs:line 271
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Develop a custom module and configure iot edge device to use this module
2. As news features are developed on module, trigger a CI/CD pipeline that redeploy the module.
3. After some days of running (maybe 1-2 months), the error occurs.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```json

{
  "additional_info": {
    "aziot_edged_version": "1.2.4",
    "docker_version": "20.10.6+azure",
    "now": "2022-04-11T06:54:03.123129869Z",
    "os": {
      "arch": "x86_64",
      "bitness": 64,
      "id": "ubuntu",
      "version_id": "18.04"
    },
    "system_info": {
      "disks": [],
      "total_ram": "7.77 GiB",
      "total_swap": "0 B",
      "used_ram": "1.44 GiB",
      "used_swap": "0 B"
    }
  },
  "checks": {
    "aziot-edge-version": {
      "result": {
        "result": "warning",
        "details": [
          "Installed IoT Edge daemon has version 1.2.4 but 1.2.9 is the latest stable version available.\nPlease see https://aka.ms/iotedge-update-runtime for update instructions."
        ]
      },
      "additional_info": {
        "actual_version": "1.2.4",
        "expected_version": "1.2.9"
      }
    },
    "aziot-edged-config-well-formed": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "aziot-version": {
      "result": {
        "result": "warning",
        "details": [
          "Installed aziot-identity-service package has version 1.2.3 but 1.2.6 is the latest stable version available.\nPlease see https://aka.ms/aziot-update-runtime for update instructions."
        ]
      },
      "additional_info": {
        "actual_version": "1.2.3",
        "expected_version": "1.2.6"
      }
    },
    "certd-config-well-formed": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "certd-running": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "certs-match-private-keys": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "certs-preloaded": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "certs-read": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "check-agent-image": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "config-up-to-date": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "configs-up-to-date": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "connect-management-uri": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "connect_management_uri": "unix:///var/run/iotedge/mgmt.sock",
        "listen_management_uri": "fd://aziot-edged.mgmt.socket"
      }
    },
    "container-connect-upstream-amqp": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "diagnostics_image_name": "/azureiotedge-diagnostics:1.2.4",
        "network_name": "azure-iot-edge",
        "port_number": 5671,
        "proxy": null,
        "upstream_hostname": "***.azure-devices.net"
      }
    },
    "container-connect-upstream-https": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "diagnostics_image_name": "/azureiotedge-diagnostics:1.2.4",
        "network_name": "azure-iot-edge",
        "port_number": 443,
        "proxy": null,
        "upstream_hostname": "***.azure-devices.net"
      }
    },
    "container-connect-upstream-mqtt": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "diagnostics_image_name": "/azureiotedge-diagnostics:1.2.4",
        "network_name": "azure-iot-edge",
        "port_number": 8883,
        "proxy": null,
        "upstream_hostname": "***.azure-devices.net"
      }
    },
    "container-default-connect-upstream-amqp": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "diagnostics_image_name": "/azureiotedge-diagnostics:1.2.4",
        "network_name": "azure-iot-edge",
        "port_number": 5671,
        "proxy": null,
        "upstream_hostname": "***.azure-devices.net"
      }
    },
    "container-default-connect-upstream-https": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "diagnostics_image_name": "/azureiotedge-diagnostics:1.2.4",
        "network_name": "azure-iot-edge",
        "port_number": 443,
        "proxy": null,
        "upstream_hostname": "***.azure-devices.net"
      }
    },
    "container-default-connect-upstream-mqtt": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "diagnostics_image_name": "/azureiotedge-diagnostics:1.2.4",
        "network_name": "azure-iot-edge",
        "port_number": 8883,
        "proxy": null,
        "upstream_hostname": "***.azure-devices.net"
      }
    },
    "container-engine-dns": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "container_engine_config_path": "/etc/docker/daemon.json",
        "dns": [
          "1.1.1.1"
        ]
      }
    },
    "container-engine-ipv6": {
      "result": {
        "result": "ignored"
      },
      "additional_info": {
        "actual_use_ipv6": null,
        "expected_use_ipv6": false
      }
    },
    "container-engine-is-moby": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "docker_server_version": "20.10.6+azure",
        "moby_runtime_uri": null
      }
    },
    "container-engine-logrotate": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "daemon_config": {
          "log-driver": "json-file",
          "log-opts": {
            "max-file": "3",
            "max-size": "10m"
          }
        }
      }
    },
    "container-engine-uri": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "docker_host_arg": "unix:///var/run/docker.sock",
        "docker_server_version": "20.10.6+azure"
      }
    },
    "container-local-time": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "actual_duration": {
          "nanos": 0,
          "secs": 1649660045
        },
        "diff": 0,
        "expected_duration": {
          "nanos": 853222928,
          "secs": 1649660045
        }
      }
    },
    "container-resolve-parent-hostname": {
      "result": {
        "result": "ignored"
      },
      "additional_info": {}
    },
    "edge-agent-storage-mounted-from-host": {
      "result": {
        "result": "warning",
        "details": [
          "The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.\nData might be lost if the module is deleted or updated.\nPlease see https://aka.ms/iotedge-storage-host for best practices."
        ]
      },
      "additional_info": {
        "container_directories": [
          "/var/run/iotedge/mgmt.sock",
          "/var/run/iotedge/workload.sock"
        ],
        "storage_directory": "/tmp/edgeAgent"
      }
    },
    "edge-hub-storage-mounted-from-host": {
      "result": {
        "result": "warning",
        "details": [
          "The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.\nData might be lost if the module is deleted or updated.\nPlease see https://aka.ms/iotedge-storage-host for best practices."
        ]
      },
      "additional_info": {
        "container_directories": [
          "/var/run/iotedge/workload.sock"
        ],
        "storage_directory": "/tmp/edgeHub"
      }
    },
    "est-identity-and-bootstrap-certificate-expiry": {
      "result": {
        "result": "ignored"
      },
      "additional_info": {
        "bootstrap_certificate_info": null,
        "identity_certificate_info": null
      }
    },
    "host-connect-dps-endpoint": {
      "result": {
        "result": "ignored"
      },
      "additional_info": {
        "dps_endpoint": null,
        "dps_hostname": null,
        "proxy": null
      }
    },
    "host-connect-iothub-amqp": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "iothub_hostname": "***.azure-devices.net",
        "port_number": 5671,
        "proxy": null
      }
    },
    "host-connect-iothub-https": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "iothub_hostname": "***.azure-devices.net",
        "port_number": 443,
        "proxy": null
      }
    },
    "host-connect-iothub-mqtt": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "iothub_hostname": "***.azure-devices.net",
        "port_number": 8883,
        "proxy": null
      }
    },
    "host-local-time": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "offset": 0
      }
    },
    "hostname": {
      "result": {
        "result": "ok"
      },
      "additional_info": {
        "config_hostname": "***-qlt-edge-vm01",
        "machine_hostname": "***-qlt-edge-vm01"
      }
    },
    "identity-certificate-expiry": {
      "result": {
        "result": "ignored"
      },
      "additional_info": {
        "certificate_info": null,
        "provisioning_mode": "manual-other"
      }
    },
    "identityd-config-well-formed": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "identityd-running": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "key-pairs-read": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "keyd-config-well-formed": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "keyd-running": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "local-ca-certificate-expiry": {
      "result": {
        "result": "ignored"
      },
      "additional_info": {
        "certificate_info": null
      }
    },
    "parent_hostname": {
      "result": {
        "result": "ignored"
      },
      "additional_info": {
        "config_parent_hostname": null
      }
    },
    "tpmd-config-well-formed": {
      "result": {
        "result": "ok"
      },
      "additional_info": {}
    },
    "tpmd-running": {
      "result": {
        "result": "ignored"
      },
      "additional_info": {}
    }
  }
}

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04.5 LTS
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.4
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1
* Docker/Moby [run `docker version`]: 20.10.6+azure

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by bruno-motacardoso** [comment]
Hi @nyanzebra , see below my clarifications:

1. It fails every couple of days.
2. Yes, the iotedge check is from the time when the issue was present.
3. Yes, it happebs in my module at this line:
```c#
try
{
    await moduleClient.SendEventAsync("output1", pipeMessage); <---- exception at this line
}
catch (Exception ex)
{
    _logger.LogError(ex, "Error: {Message}", ex.Message);

    if (ex.InnerException != null)
    {
        _logger.LogWarning(ex.InnerException, "Inner exception : {InnerMessage}.", ex.InnerException.Message);
    }

    return MessageResponse.Abandoned;
}
```

The moduleClient is defined like this :
```c#
// Open a connection to the Edge runtime
_ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);

_ioTHubModuleClient.SetRetryPolicy(new RetryPolicy(_logger, 3));

_ioTHubModuleClient.SetConnectionStatusChangesHandler(ConnectionStatusChanged);

await _ioTHubModuleClient.OpenAsync();

_logger.LogInformation("IoT Hub module client initialized: {ProductInfo}", _ioTHubModuleClient.ProductInfo);

```

**Comment by nyanzebra** [comment]
Okay, interesting, from the logs/check I don't see anything too out of the ordinary... other than not being able to load the key pair (this was not configured with PKCS#11 so it loaded the keypair from a file, but the file didn't contain a keypair)

Are there any additional errors or logs from edgeHub (by the way, this is the doc for enabling debug logs in edgeHub and other edge modules: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11)? From what I see there it seems like there is likely connectivity issue, but if iotedge check is current with the time in which the issue was seen then it seems like certificates and connectivity are good...

Also, what SDK and version are you using? Are there additional logs beyond the stack trace on the mqtt channel failing to open?

Final question for now, what are you doing to get the modules running again? A simple restart? I ask in that I am curious if there are any other resources that might be getting used up like memory that could cause the process to slow down or not function properly. The check seems to show good memory usage, but still want to double check and understand your device situation fully.

**Comment by nyanzebra** [comment]
@bruno-motacardoso if you are willing to share a support bundle that will help in debugging, if you don't want to reveal anything you don't want to in the logs then we can open an internal issue and support you that way too.

For support bundle please see: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11

**Comment by jlian** [comment]
@bruno-motacardoso have you had the chance to try @nyanzebra suggestions?

**Comment by varunpuranik** [comment]
@drwill-ms / @azabbasi - any idea why/when the module client could get into this state and throw the exception above to application code?

**Comment by drwill-ms** [comment]
> Connectivity issues to the cloud and to edgeHub are expected to be handled by Microsoft modules.

The SDK will retry only so much before it gives up on a connection. It is expected of a device/module developer to monitor the connection status callback and take action in some cases. We have a [device app sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/main/iot-hub/Samples/device/DeviceReconnectionSample) showing how to responsibly take action. I see this line in the code snippet `_ioTHubModuleClient.SetConnectionStatusChangesHandler(ConnectionStatusChanged);`, but wonder what the implementation of the handler is.

Getting [SDK logs](https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs) during a repro might help.

**Comment by jlian** [comment]
@bruno-motacardoso :
- Does the issue persist (e.g. until restart) or does the module eventually recover?
- Do you experience any message loss?
- Have you considered @drwill-ms suggestion?
- Do you have any IoT Hub diagnostic logs?

**Comment by bruno-motacardoso** [comment]
@nyanzebra thanks for your help. See below more details about your questions.

> Okay, interesting, from the logs/check I don't see anything too out of the ordinary... other than not being able to load the key pair (this was not configured with PKCS#11 so it loaded the keypair from a file, but the file didn't contain a keypair)

It means that my custom TLS certificate is not used by the iotedge ? If my certificate is not used, maybe the default certifcate is used and it causes problems when it is trying to renew it ? 

> Are there any additional errors or logs from edgeHub (by the way, this is the doc for enabling debug logs in edgeHub and other edge modules: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11)? From what I see there it seems like there is likely connectivity issue, but if iotedge check is current with the time in which the issue was seen then it seems like certificates and connectivity are good...

Yes iotedge check seems good.. I enabled debug for edgeHub by running the command `iotedge system set-log-level debug`. Now I have to wait to have the problem another time and have the debug logs.. (I cannot trigger the problem)

> Also, what SDK and version are you using? Are there additional logs beyond the stack trace on the mqtt channel failing to open?

I use the framework `netcoreapp3.1` and the dependency `<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.37.2" />` on my iotedge modules.

> Final question for now, what are you doing to get the modules running again? A simple restart? I ask in that I am curious if there are any other resources that might be getting used up like memory that could cause the process to slow down or not function properly. The check seems to show good memory usage, but still want to double check and understand your device situation fully.

I simply do a `iotedge system restart` and all works fine.

**Comment by bruno-motacardoso** [comment]
@jlian :

> * Does the issue persist (e.g. until restart) or does the module eventually recover?
The issues appears each N weeks (btw 1 and 2 months)
> * Do you experience any message loss?
All the communication and modules are down and I restart it to recover the running state. So all the message are lost.
This is the reason why this problem is critical in my app.
> * Have you considered @drwill-ms suggestion?
See my message above.
> * Do you have any IoT Hub diagnostic logs?
Yes diagnotics settings are enabled on my iot hub. Where can I find the logs for my iotedge issue ? 
I think that no log is upload to iohub because the communication btw my modules and edgeHub is lost..

**Comment by nyanzebra** [comment]
@varunpuranik, do we have a link for creating a support issue internal to MSFT?

**Comment by nyanzebra** [comment]
@bruno-motacardoso you can log a bug on us and then we can ask for the support-bundle

**Comment by bishal41** [comment]
@bruno-motacardoso here is the link to create a support request https://azure.microsoft.com/en-us/support/create-ticket/

In the wizard for "Create a support request" you can select Issue type = "Technical" and then Service = "IoT Edge"

Once you open the support request, please let us know that way we are in sync and look at the support bundle to take this forward.

**Comment by bishal41** [comment]
@bruno-motacardoso, were you able to open a support request using the instructions above? Please let us know so we can  track the support request and get the logs and perhaps close this in GH?

**Comment by bishal41** [comment]
@bruno-motacardoso following up on this again to ensure your issue is resolved and whether further action is needed on this? Please let us know.

**Comment by bruno-motacardoso** [comment]
@bishal41 I had the problem, one more time this morning.
So I created a support request (2206020050000495) with iotedge support-bundle attached.

**Comment by micahl** [comment]
@bruno-motacardoso please use the support request to provide the team with debug logs and SDK logs.  Closing this issue.
