### ISSUE TITLE
Edge Agent can't connect to IoT Hub behind Zscaler with Zscaler certs installed

### ISSUE THREAD

**Issue by Maci3jPy** [Azure/iotedge#6291]
## Expected Behavior
Edge Agent should connect to IoT Hub behind Zscaler and firewall if port are opened and certificates are provided.

## Current Behavior
Host machine can connect to azure-devices.net but container network and Edge Agent can't connect to azure-devices.net. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install IoT Edge behind Zscaler and firewall and provision within cloud
2. Install Zscaler certificate in ubuntu trust store
3. Install Zscaler certificate in edgeAgent container
4. Provide UpstreamProtocol to edgeAgent in config.toml = AmqpWs

## Context (Environment)

Machine is behind firewall and Zscaler. The only port opened is 443, so edgeAgent Upstreamprotocol is set to AmqpWs in config.toml.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
× host can connect to and perform TLS handshake with iothub AMQP port - Error
    Could not connect to .azure-devices.net : could not complete TLS handshake
        caused by: tcp connect error: Connection timed out (os error 110)
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with iothub MQTT port - Error
    Could not connect to .azure-devices.net : could not complete TLS handshake
        caused by: tcp connect error: Connection timed out (os error 110)

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: docker returned exit code: 1, stderr = Error: No such object: edgeHub
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
× container on the default network can connect to upstream  AMQP port - Error
    Container on the default network could not connect to .azure-devices.net:5671
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Operation timed out [::ffff:40.113.176.171]:5671)
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to .azure-devices.net:443
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (The SSL connection could not be established, see inner exception.)
× container on the default network can connect to upstream MQTT port - Error
    Container on the default network could not connect to .azure-devices.net:8883
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Operation timed out [::ffff:40.113.176.171]:8883)
× container on the IoT Edge module network can connect to upstream AMQP port - Error
    Container on the azure-iot-edge network could not connect to .azure-devices.net:5671
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Operation timed out [::ffff:40.113.176.171]:5671)
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to .azure-devices.net:443
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (The SSL connection could not be established, see inner exception.)
× container on the IoT Edge module network can connect to upstream MQTT port - Error
    Container on the azure-iot-edge network could not connect to .azure-devices.net:8883
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Operation timed out [::ffff:40.113.176.171]:8883)
26 check(s) succeeded.
1 check(s) raised warnings.
9 check(s) raised errors.

```
</details>

### Output of openssl s_client

Here is the output of openssl s_client -connect myhub.azure-devices.net:443 on the host machine

```
CONNECTED(00000003)
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

I instaled openssl in edgeAgent container. Here is the output of openssl s_client -connect myhub.azure-devices.net:443 inside edgeAgent container:

```
CONNECTED(00000003)
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

### Device Information
* Host OS Ubuntu 20.04: 
* Architecture amd64
* Container OS Linux Containers

### Runtime Versions
* aziot-edged : 1.2.9
* Edge Agent : 1.2
* Edge Hub : -
* Docker/Moby : 20.10.14+azure-1

## Logs

<details>
<summary>aziot-edged logs</summary>

```

Apr 15 07:52:14 [7037]: 2022-04-15T11:52:14Z [INFO] - Checking edge runtime status
Apr 15 07:52:14 [7037]: 2022-04-15T11:52:14Z [INFO] - Edge runtime is running.
Apr 15 07:52:17 [7037]: 2022-04-15T11:52:17Z [INFO] - [mgmt] - - - [2022-04-15 11:52:17.439301306 UTC] "GET /modules?api-version=2021-12-07 HTTP/1.1" 200 OK 692 "-" "-" auth_id(-)
Apr 15 07:52:17 [7037]: 2022-04-15T11:52:17Z [INFO] - Querying system info...
Apr 15 07:52:17 [9263]: none
Apr 15 07:52:17 [7037]: 2022-04-15T11:52:17Z [INFO] - [mgmt] - - - [2022-04-15 11:52:17.704989969 UTC] "GET /systeminfo?api-version=2021-12-07 HTTP/1.1" 200 OK 410 "-" "-" auth_id(-)
Apr 15 07:52:23 [7037]: 2022-04-15T11:52:23Z [INFO] - Querying system resources...
Apr 15 07:52:25 [7037]: 2022-04-15T11:52:25Z [INFO] - [mgmt] - - - [2022-04-15 11:52:25.009919956 UTC] "GET /systeminfo/resources?api-version=2021-12-07 HTTP/1.1" 200 OK 4200 "-" "-" auth_id(-)
Apr 15 07:52:27 [7037]: 2022-04-15T11:52:27Z [INFO] - [mgmt] - - - [2022-04-15 11:52:27.440523430 UTC] "GET /modules?api-version=2021-12-07 HTTP/1.1" 200 OK 692 "-" "-" auth_id(-)
Apr 15 07:52:37 [7037]: 2022-04-15T11:52:37Z [INFO] - [mgmt] - - - [2022-04-15 11:52:37.447379455 UTC] "GET /modules?api-version=2021-12-07 HTTP/1.1" 200 OK 692 "-" "-" auth_id(-)
Apr 15 07:52:47 [7037]: 2022-04-15T11:52:47Z [INFO] - [mgmt] - - - [2022-04-15 11:52:47.445103536 UTC] "GET /modules?api-version=2021-12-07 HTTP/1.1" 200 OK 692 "-" "-" auth_id(-)
Apr 15 07:52:57 [7037]: 2022-04-15T11:52:57Z [INFO] - [mgmt] - - - [2022-04-15 11:52:57.452590350 UTC] "GET /modules?api-version=2021-12-07 HTTP/1.1" 200 OK 692 "-" "-" auth_id(-)
Apr 15 07:53:07 [7037]: 2022-04-15T11:53:07Z [INFO] - [mgmt] - - - [2022-04-15 11:53:07.454021741 UTC] "GET /modules?api-version=2021-12-07 HTTP/1.1" 200 OK 692 "-" "-" auth_id(-)

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<4> 2022-04-15 11:51:22.424 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:51:32.426 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:51:42.428 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:51:52.429 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:52:02.431 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:52:12.433 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<6> 2022-04-15 11:52:17.671 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<4> 2022-04-15 11:52:22.432 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:52:32.434 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:52:42.437 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:52:52.445 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:53:02.446 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:53:12.448 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<6> 2022-04-15 11:53:17.717 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2022-04-15 11:53:22.448 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:53:32.450 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:53:42.452 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:53:52.454 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:54:02.456 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:54:12.457 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-04-15 11:54:18.752 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) (The operation timed out.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (110): Operation timed out
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass38_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 234
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.<>c__DisplayClass20_1.<<CreateSdkModuleClient>b__2>d.MoveNext() in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.TimeoutException: The operation timed out.
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object out-connection13.
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass38_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 234
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.<>c__DisplayClass20_1.<<CreateSdkModuleClient>b__3>d.MoveNext() in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---

```
</details>

## Additional Information
Before I installed certificates in edgeAgent container on edgeAgent logs I got the error about SSL, after installing there is time out error. Proper dns is provided inside daemon.json

**Comment by nyanzebra** [comment]
Hi @Maci3jPy could you provide can you provide any documentation, if any, that you followed for setting up edge with zscaler?

**Comment by nyanzebra** [comment]
@Maci3jPy Just want to check again and see if you can share any documentation you followed. If it is something outside to MSFT it might be useful for us to create official documentation, but want to follow same steps you did to figure out the solution.

**Comment by Maci3jPy** [comment]
> @Maci3jPy Just want to check again and see if you can share any documentation you followed. If it is something outside to MSFT it might be useful for us to create official documentation, but want to follow same steps you did to figure out the solution.

Hi @nyanzebra. Unfortunately, there isn't any documentation regarding Edge and Zscaler. I followed official Zscaler documentation  on how to add custom certificates. 
[https://help.zscaler.com/zia/adding-custom-certificate-application-specific-trusted-store?_gl=1*1043n7o*_ga*MjAwNDQ1MzkxOC4xNjQ5NjY1NDAy*_ga_10SPJ4YJL9*MTY0OTg0Njg4OC4zLjEuMTY0OTg0ODEwOS41Nw..&_ga=2.102765312.1650678294.1649846889-2004453918.1649665402#docker-compose-file](url)
Then I found some threads on stackoverflow that I tried to follow but, there isn't any specific documentation or threads that address this specific problem.

**Comment by jlian** [comment]
@markrad do you maybe know the answer?

**Comment by nyanzebra** [comment]
@Maci3jPy thanks, I will try to replicate and speak internally if we need to create documentation in relation to zscaler integration

**Comment by Maci3jPy** [comment]
We can close the issue as it was resolved. The fix was to add the azure-devices.net URL to the SSL bypass list in Zscaler.

**Comment by jlian** [comment]
Can you confirm what steps you took for the community? Looks like you

1. Install IoT Edge behind Zscaler and firewall and provision within cloud
2. Install Zscaler certificate in ubuntu trust store
3. Install Zscaler certificate in edgeAgent container
4. Provide UpstreamProtocol to edgeAgent in config.toml = AmqpWs
5. Added azure-devices.net to the SSL bypass list in Zscaler

Anything I missed?

**Comment by Maci3jPy** [comment]
> Can you confirm what steps you took for the community? Looks like you
> 
> 1. Install IoT Edge behind Zscaler and firewall and provision within cloud
> 2. Install Zscaler certificate in ubuntu trust store
> 3. Install Zscaler certificate [in edgeAgent container](https://help.zscaler.com/zia/adding-custom-certificate-application-specific-trusted-store?_gl=11043n7o_gaMjAwNDQ1MzkxOC4xNjQ5NjY1NDAy_ga_10SPJ4YJL9*MTY0OTg0Njg4OC4zLjEuMTY0OTg0ODEwOS41Nw..&_ga=2.102765312.1650678294.1649846889-2004453918.1649665402#docker-compose-file)
> 4. Provide UpstreamProtocol to edgeAgent in config.toml = AmqpWs
> 5. Added azure-devices.net to the SSL bypass list in Zscaler
> 
> Anything I missed?

Yes, that's the steps I took in my case. Additionally it turns out that after adding azure-devices.net to the SSL bypass list in Zscaler, the zscaler certificates are only required in ubuntu trust store. I didn't need to place them in edge agent container. It's also worth to mention that you only need to add azure-devices.net or also global.azure-devices-provisioning.net if you use DPS to this ZScaler list. For example blob storage and azure container registry will still work even without bypass, they just need certificate in host store. So the final list looks like this:

1. Install IoT Edge behind Zscaler and firewall and provision within cloud
2. Install Zscaler certificate in ubuntu trust store
3. Add required URLs and ports to firewall whitelist (azaure-devices.net, blob storage, container registry, DPS if you use, mcr.microsoft.com if you want to use public repo)
4. Provide UpstreamProtocol to edgeAgent in config.toml = AmqpWs if your firewall only supports port 443
5. Add azure-devices.net to the SSL bypass list in Zscaler
6. If you are using other ports than 443 - for example AMQP 5671, you also need to add a firewall filtering rule in Zscaler to allow the traffic.

**Comment by jlian** [comment]
Cool thanks a lot! Looks like we should update our docs
