### ISSUE TITLE
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred

### ISSUE THREAD

**Issue by wiltonkkw** [Azure/iotedge#6292]
## Expected Behavior
I'm using Ubuntu 20.04 and setting the network mode to "host" since I need to access the network interface (CAN interface) from the host. I can get the interfaces but ModuleClient got network error.

## Current Behavior
After add the options in my custom edge module:
```
                "NetworkingConfig": {
                    "EndpointsConfig": {
                         "host": {}
                    }
                },
                "HostConfig": {
                    "NetworkMode": "host"
                }
```
The edge module can access the network interface from the host. But got the follow error when executing
```
            var _ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await _ioTHubModuleClient.OpenAsync();
```
Error message:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass39_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.OpenInternalAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at InzightEdge.Program.Init() in /app/Program.cs:line 72
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at InzightEdge.Program.Main(String[] args) in /app/Program.cs:line 32
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Add the network options to the **Container Create Options** in the IoT Edge on IoT Hub
```
                "NetworkingConfig": {
                    "EndpointsConfig": {
                         "host": {}
                    }
                },
                "HostConfig": {
                    "NetworkMode": "host"
                }
```
3.
4.
5.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
34 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS: Ubuntu 20.04 
* Architecture: amd64 
* Container OS: Linux containers 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.9
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.9
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.9
* Docker/Moby [run `docker version`]: 20.10.14+azure-1

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
**docker inspect <module_name>**
```
[
    {
        "Id": "bf8aa3ac19530a2903dac188f038a02c67899f27fa4163cdcab43a370e60257a",
        "Created": "2022-04-17T09:20:32.367760055Z",
        "Path": "dotnet",
        "Args": [
            "InzightEdge.dll"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 139,
            "Error": "",
            "StartedAt": "2022-04-18T05:08:37.542616127Z",
            "FinishedAt": "2022-04-18T05:12:43.661989296Z"
        },
        "Image": "sha256:cdf41e5580ac4ee51ddd1cb2153c9a9d7b8a051d59fa1ed51ad1a747b76f7014",
        "ResolvConfPath": "/var/lib/docker/containers/bf8aa3ac19530a2903dac188f038a02c67899f27fa4163cdcab43a370e60257a/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/bf8aa3ac19530a2903dac188f038a02c67899f27fa4163cdcab43a370e60257a/hostname",
        "HostsPath": "/var/lib/docker/containers/bf8aa3ac19530a2903dac188f038a02c67899f27fa4163cdcab43a370e60257a/hosts",
        "LogPath": "/var/lib/docker/containers/bf8aa3ac19530a2903dac188f038a02c67899f27fa4163cdcab43a370e60257a/bf8aa3ac19530a2903dac188f038a02c67899f27fa4163cdcab43a370e60257a-json.log",
        "Name": "/inzightedge",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "unconfined",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/test/Videos:/app/dms",
                "/home/test/Pictures:/app/adas",
                "/home/test/Documents:/app/db",
                "/dev/v4l:/dev/v4l",
                "/var/run/iotedge/workload.sock:/var/run/iotedge/workload.sock"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ],
                "5671/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5671"
                    }
                ],
                "8883/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8883"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [
                "8.8.8.8",
                "192.168.1.1"
            ],
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [
                {
                    "PathOnHost": "/dev/ttyUSB0",
                    "PathInContainer": "/dev/ttyUSB0",
                    "CgroupPermissions": "666"
                },
                {
                    "PathOnHost": "/dev/ttyACM0",
                    "PathInContainer": "/dev/ttyACM0",
                    "CgroupPermissions": "666"
                },
                {
                    "PathOnHost": "/dev/video0",
                    "PathInContainer": "/dev/video0",
                    "CgroupPermissions": "666"
                }
            ],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/952a527abccc2200913b15e57a4a41f444f9be89b7352d73f53eb1e4eb9b7acd-init/diff:/var/lib/docker/overlay2/c3397766e14eeea3712eeba43d7c595d6b52ba3fa33ba272fb6cbfd275e0097b/diff:/var/lib/docker/overlay2/ad532a1be3b900ce2b8d658d27e21cd93141efd7096aa457f196734d2d4ed746/diff:/var/lib/docker/overlay2/85ed15ddbcb51b439a32bc82ce73d2a4c2fc102a8529707d6e85ba47283db16a/diff:/var/lib/docker/overlay2/49fbb0d151104f1c247de6f1b5247fb6b4d68267520c38ec8e8fe56ad9acd46d/diff:/var/lib/docker/overlay2/95d43a7f55ad074b4fd6a66f23c661ceec324373ca6aaeab343cf34d7aa8f99e/diff:/var/lib/docker/overlay2/73974c88590fd8b9294d65bf3a83c076d83885e9724e95edd33317c90235f8dd/diff:/var/lib/docker/overlay2/718af65166aaff49abed371423f9760ff7725087eb3c72d75843d23032aa5350/diff:/var/lib/docker/overlay2/1cd8e3cb69bf8d55c103bf51fb88b6df3d28290fc75f1cf11752940a7689662a/diff:/var/lib/docker/overlay2/ac28234fbd05509662742595ddcd3c01122a626ba2f189e02f5ed1d27c19a9f7/diff:/var/lib/docker/overlay2/6c596c9eb7763b627cba74066bdb7d610e0ce57e6fc56ad062f9f8a73fc59b5b/diff:/var/lib/docker/overlay2/c10c0ca8a19b2fad64fd62fe53522dd2fb2802c33a252d72ddb7283d269b879e/diff:/var/lib/docker/overlay2/85909a4bbe1da72e505fd0394a9232f9f86aa301a69dc4404f82b5048f575b6f/diff:/var/lib/docker/overlay2/f01d9f6c984c357670e31e5a536608b0dbdb53d6a41c85d85f769627fcd16f80/diff:/var/lib/docker/overlay2/63f8ecb2a73b03e5af11fbc31273ec5462b2d7a7e7e547688f537c42c6af7808/diff:/var/lib/docker/overlay2/c5d6fdb09a7706344cb8c6701e8990813e7460cf6ba6d4d6d335707ba3e463ae/diff:/var/lib/docker/overlay2/cc5b2905ba1d0cd1cb8847cb647564a62a95e6f0863f736f6cc25fac9c65970e/diff:/var/lib/docker/overlay2/2e13afd06f68d0b5c172b76411c4dcc7d88dba82b08d92b3e5587af1cc5a242c/diff",
                "MergedDir": "/var/lib/docker/overlay2/952a527abccc2200913b15e57a4a41f444f9be89b7352d73f53eb1e4eb9b7acd/merged",
                "UpperDir": "/var/lib/docker/overlay2/952a527abccc2200913b15e57a4a41f444f9be89b7352d73f53eb1e4eb9b7acd/diff",
                "WorkDir": "/var/lib/docker/overlay2/952a527abccc2200913b15e57a4a41f444f9be89b7352d73f53eb1e4eb9b7acd/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/test/Videos",
                "Destination": "/app/dms",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/test/Pictures",
                "Destination": "/app/adas",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/test/Documents",
                "Destination": "/app/db",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/dev/v4l",
                "Destination": "/dev/v4l",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/iotedge/workload.sock",
                "Destination": "/var/run/iotedge/workload.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "ubuntu",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "IOTEDGE_APIVERSION=2021-12-07",
                "IOTEDGE_AUTHSCHEME=sasToken",
                "IOTEDGE_DEVICEID=SE50-02",
                "IOTEDGE_GATEWAYHOSTNAME=ubuntu",
                "IOTEDGE_IOTHUBHOSTNAME=inzight-dev.azure-devices.net",
                "IOTEDGE_MODULEGENERATIONID=637850918090336770",
                "IOTEDGE_MODULEID=inzightedge",
                "IOTEDGE_WORKLOADURI=unix:///var/run/iotedge/workload.sock",
                "RuntimeLogLevel=Information",
                "storageContainername=files",
                "storageconnectionstring=DefaultEndpointsProtocol=https;xxxxxxx",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ASPNETCORE_URLS=http://+:80",
                "DOTNET_RUNNING_IN_CONTAINER=true"
            ],
            "Cmd": null,
            "Image": "inzightdev.azurecr.io/inzightedge:0.0.45-amd64.debug",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "dotnet",
                "InzightEdge.dll"
            ],
            "OnBuild": null,
            "Labels": {
                "net.azure-devices.edge.original-image": "inzightdev.azurecr.io/inzightedge:0.0.45-amd64.debug",
                "net.azure-devices.edge.owner": "Microsoft.Azure.Devices.Edge.Agent"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ee8d2fb0f3b110f49c5a57d85997f12861366d4700909798a868c540d037f50f",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "cd607b7d139e98bc4cd939a88b155a0fcf558f2d068ad8d5fbcdfd183733248e",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by and-rewsmith** [comment]
@wiltonkkw Thanks for the report. Questions:
1. I assume that if you are running a module with default docker settings (i.e. no network host mode), this SDK exception does not happen?
2. If setting network mode to host is what causes this failure, is your host dns configured properly? My first guess is something is going wrong here with host dns.

**Comment by wiltonkkw** [comment]
@and-rewsmith Thank you very much.
1. Yes. The default docker settings works fine
2. Is there any reference link for DNS setting?

**Comment by and-rewsmith** [comment]
@wiltonkkw As long as DNS works, this scenario should be supported. Can you test host DNS by performing nslookup on your iothub hostname?

**Comment by wiltonkkw** [comment]
I ran and the result:
```
$ sudo docker exec inzightedge nslookup www.google.com

Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	www.google.com
Address: 172.217.27.4
Name:	www.google.com
Address: 2404:6800:4005:801::2004
```

**Comment by and-rewsmith** [comment]
@wiltonkkw I just tried this scenario out on an ubuntu 20 amd64 host. I used the following ModuleClient initialization code and it worked:
```
MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);
ITransportSettings[] settings = { mqttSetting };

// Open a connection to the Edge runtime
ModuleClient ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
await ioTHubModuleClient.OpenAsync();
Console.WriteLine("IoT Hub module client initialized.");
```

I was also using the same version of iotedge and docker. So this leads me to believe there is some DNS misconfiguration going on. Can you think of anything that may be causing this? Also what is this CAN interface you are referring to? Did this require special setup?

**Comment by wiltonkkw** [comment]
We installed **net-tools** and **can-utils** for CAN. The hardware support CAN socket.


I set the DNS in the Container Create Options:
```
{
   :
   :
   "Dns": [
       "1.1.1.1",
       "8,8,8,8"
   ]
}
```
I tried **curl** in the edge module is also working fine for external web url. But ModuleClient still not work.

**Comment by and-rewsmith** [comment]
@wiltonkkw Since this is looking like it isn't a problem with your DNS config, I am thinking the root cause is going to be something internal to the Devices SDK. The SDK project lives here:
https://github.com/Azure/azure-iot-sdk-csharp/issues

I recommend creating an issue and linking it to this one.

**Comment by and-rewsmith** [comment]
Hi @wiltonkkw. Did you log an issue with C# SDK repo?

**Comment by wiltonkkw** [comment]
@and-rewsmith  Yes Thanks

**Comment by bqstony** [comment]
I add the link here for following it
https://github.com/Azure/azure-iot-sdk-csharp/issues/2356
