### ISSUE TITLE
Error Message unclear: Error scraping edgeHub metrics endpoint connection refused

### ISSUE THREAD

**Issue by harounshehata** [Azure/iotedge#6296]
When the test CA certificates expires, the cloud telemetry stops. The edgeHub and other custom module (OPCPublisher) still run without issues and don't show any errors or warnings in the log. 
The edgeAgent logs show the following error:
```

```
## Expected Behavior
If the CA certificate expires it should be shown in the logs or in the iotedge check command.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Setup IoT Edge device with Test Ca certificate
2. After certificate expires check the logs of the running modules

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
‼ daemon configurations up-to-date with config.toml - Warning
    /etc/aziot/config.toml was modified after keyd's config
    You must run 'aziotctl config apply' to update keyd's config with the latest config.toml
√ identityd config toml file specifies a valid hostname - OK
× aziot-identity-service package is up-to-date - Error
    could not query https://raw.githubusercontent.com/Azure/azure-iotedge/master/latest-aziot-identity-service.json for latest available version
‼ host time is close to reference time - Warning
    Could not query NTP server
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
‼ configuration up-to-date with config.toml - Warning
    /etc/aziot/config.toml was modified after edged's config
    You must run 'iotedge config apply' to update edged's config with the latest config.toml
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
‼ aziot-edge package is up-to-date - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
29 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]:  Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.5
* Edge Agent [image tag (e.g. 1.0.0)]:  1.2.7
* Edge Hub [image tag (e.g. 1.0.0)]:  1.2.7
* Docker/Moby [run `docker version`]: 20.10.11+azure-3

## Logs
<details>
<summary>edge-agent logs</summary>

```
<6> 2022-04-19 06:19:03.233 +00:00 [INF] - Error scraping endpoint http://172.18.0.4:9600/metrics - System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 102
```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by and-rewsmith** [comment]
@harounshehata I think you forgot to paste your logs. Yes I agree iotedge check should cover this and I will take a look.

**Comment by jlian** [comment]
@and-rewsmith looks like the logs can be expanded

```
<6> 2022-04-19 06:19:03.233 +00:00 [INF] - Error scraping endpoint http://172.18.0.4:9600/metrics - System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 102
```

**Comment by and-rewsmith** [comment]
@jilian The root cause of the issue is missing iotedge check features in main / 1.2 branches. These logs aren't super relevant. I started an email thread with Damon and Micah last week and am having a discussion regarding when we will tackle this work today.

**Comment by programmers-github** [comment]
> @Jilian The root cause of the issue is missing iotedge check features in main / 1.2 branches. These logs aren't super relevant. I started an email thread with Damon and Micah last week and am having a discussion regarding when we will tackle this work today.

@jlian :)

**Comment by harounshehata** [comment]
Good to know thank you, anything else you would need from my side?

**Comment by DarthLowen** [comment]
I have the same issue, but with production certificates. When the edgeHub certificate expires, the connection of our docker container doesn't recover and edgeAgent complains about a connection refused wrt metrics for edgeHub. Iotedge runtime 1.4.2, running on Ubuntu 18.04.

when edgeHub started in november, it said this:
```
2022-11-07 10:05:04  Starting Edge Hub
2022-11-07 10:05:04  Starting Edge Hub
2022-11-07 10:05:04  Changing ownership of storage folder: /hostStorage/edgeHub to 13623
2022-11-07 10:05:04  Changing ownership of backup folder: /tmp/edgeHub_backup to 13623
2022-11-07 10:05:04.267 +00:00 Edge Hub Main()
<6> 2022-11-07 10:05:06.309 +00:00 [INF] - Installing certificates [CN=iotedge:08/28/2032 06:44:34] to Root
<6> 2022-11-07 10:05:06.468 +00:00 [INF] - Installing certificates [CN=iotedge:08/28/2032 06:44:34],[CN=OURCOMPANY IoT Root CA, C=BE:11/23/2031 10:32:38],[CN=OURCOMPANY IoT Intermediate CA, C=BE:11/23/2031 10:32:38],[CN=OURDAUGHTERCOMPANY IoT Root CA, C=BE:02/03/2032 11:55:33],[CN=OURDAUGHTERCOMPANY IoT Intermediate CA, C=BE:02/03/2032 11:55:33] to Root
<6> 2022-11-07 10:05:06.527 +00:00 [INF] - Enabling SSL protocols: Tls12
<6> 2022-11-07 10:05:06.889 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
```
A bit later it states:
```
...
<6> 2022-11-07 10:05:16.707 +00:00 [INF] - Scheduling server certificate renewal for "2022-12-07T10:02:35.0003343Z".
...
Cloud connection for Edge-abc123/OurModule is True
<6> 2022-11-07 10:05:21.817 +00:00 [INF] - Connection status for Edge-abc123/OurModule changed to ConnectionEstablished
...
```
So all seems OK, certificate renewal is scheduled, our module is online, all is well. Then on December 7th:
```
<6> 2022-12-07 10:02:35.002 +00:00 [INF] - Restarting process to perform server certificate renewal.
<6> 2022-12-07 10:02:35.010 +00:00 [INF] - Stopping the protocol heads...
<6> 2022-12-07 10:02:35.017 +00:00 [INF] - Closing protocol heads - (MQTT, AMQP, HTTP)
<6> 2022-12-07 10:02:35.027 +00:00 [INF] - Stopping MQTT protocol head
<6> 2022-12-07 10:02:35.057 +00:00 [INF] - Closing HTTP head
<6> 2022-12-07 10:02:35.092 +00:00 [INF] - Closed HTTP head
```

That's when things started to go wrong. Our module didn't recover (the `Connection status for ... changed to ConnectionEstablished` log doesn't come back). At the same time, the edgeAgent module started complaining about scraping the metrics endpoint with a connection refused:
```
<6> 2022-12-07 12:05:47.626 +00:00 [INF] - Scraping endpoint http://edgeHub:9600/metrics
<6> 2022-12-07 12:05:47.627 +00:00 [INF] - Scraping endpoint http://edgeAgent:9600/metrics
<6> 2022-12-07 12:05:47.643 +00:00 [INF] - Error scraping endpoint http://172.18.0.3:9600/metrics - System.Net.Http.HttpRequestException: Connection refused (172.18.0.3:9600)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.Devices.Edge.Agent.Diagnostics.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs:line 102
<6> 2022-12-07 12:05:47.662 +00:00 [INF] - Storing Metrics
<6> 2022-12-07 12:05:47.676 +00:00 [INF] - Scraped and Stored Metrics
<6> 2022-12-07 12:05:47.676 +00:00 [INF] - Successfully completed periodic operation Metrics Scrape
<6> 2022-12-07 12:43:59.516 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2022-12-07 12:43:59.574 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 19 and reported properties version 772.
<6> 2022-12-07 12:43:59.578 +00:00 [INF] - Successfully completed periodic operation refresh twin config
```
I verified using docker inspect that 172.18.0.3 is the edgeHub module.

For completeness sake, the config.toml file:
```
trust_bundle_cert = "file:///var/secrets/cert_chain.pem"
hostname = "Edge-abc123"
[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "0ab1248ABCD"
[provisioning.attestation]
method = "x509"
registration_id = "Edge-abc123"
identity_cert = "file:///var/secrets/device-id.pem"
identity_pk = "file:///var/secrets/device-id.private.pem"
[edge_ca]
cert = "file:///var/secrets/iotedge.cert.pem"
pk = "file:///var/secrets/iotedge.key.pem"
```

This issue has been bugging us for a long time already (always the certificate stuff), but we're running out of
* things to try
* time (this is deployed at our customers and we're already at 30-40 devices now)
