### ISSUE TITLE
Edge Hub Received Unknown Message Feedback

### ISSUE THREAD

**Issue by zachcdr** [Azure/iotedge#6448]
## Expected Behavior
Edge hub routes message to the module
Module processes and returns `MessageResponse.Completed`
Edge hub does not retry message

## Current Behavior
Edge hub routes message to the module
Module processes and returns `MessageResponse.Completed`
Edge hub retries the message over and over, on 90-second intervals (blocking all other messages in queue)

## Logs
<details>
<summary>edge-hub logs</summary>

```
<!--
<4> 2022-06-15 16:45:45.218 +00:00 [WRN] - Received unknown feedback message from <module> with lock token <token> and status Complete. Abandoning message.
<4> 2022-06-15 16:46:14.969 +00:00 [WRN] - Did not receive ack for message 58baec18-726a-4229-ad63-4614e82ecc28 from device/module <module>
<4> 2022-06-15 16:46:14.969 +00:00 [WRN] - Error sending messages to module <module>
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 494
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 167
-->
```
</details>

<details>
<summary>edge-hub logs after restart</summary>

```
<!--
<6> 2022-06-16 15:03:50.130 +00:00 [INF] - Termination requested, initiating shutdown.
<6> 2022-06-16 15:03:50.130 +00:00 [INF] - Stopping the protocol heads...
<6> 2022-06-16 15:03:50.130 +00:00 [INF] - Closing protocol heads - (MQTT, AMQP, HTTP)
<6> 2022-06-16 15:03:50.131 +00:00 [INF] - Stopping
<6> 2022-06-16 15:03:50.144 +00:00 [INF] - Closing HTTP head
<6> 2022-06-16 15:03:50.147 +00:00 [INF] - Closed HTTP head
<6> 2022-06-16 15:03:50.147 +00:00 [INF] - Waiting for cleanup to finish
2022-06-16 15:04:00  Starting Edge Hub
2022-06-16 15:04:01.050 +00:00 Edge Hub Main()
<6> 2022-06-16 15:04:01.871 +00:00 [INF] - Installing certificates <certificate> to Root
<6> 2022-06-16 15:04:01.909 +00:00 [INF] - Installing certificates <certificate> to Root
<6> 2022-06-16 15:04:01.917 +00:00 [INF] - Enabling SSL protocols: Tls, Tls11, Tls12
<6> 2022-06-16 15:04:02.054 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
<6> 2022-06-16 15:04:02.467 +00:00 [INF] - Created persistent store at /tmp/edgeHub
<6> 2022-06-16 15:04:02.505 +00:00 [INF] - Initializing Edge Hub
<6> 2022-06-16 15:04:02.505 +00:00 [INF] - 
        ââââââ âââââââââââ   ââââââââââ ââââââââ
       âââââââââââââââââââ   âââââââââââââââââââ
       ââââââââ  âââââ âââ   âââââââââââââââââ
       ââââââââ âââââ  âââ   âââââââââââââââââ
       âââ  âââââââââââââââââââââââ  âââââââââââ
       âââ  âââââââââââ âââââââ âââ  âââââââââââ

 âââ âââââââ âââââââââ    âââââââââââââââ  âââââââ ââââââââ
 âââââââââââââââââââââ    ââââââââââââââââââââââââ ââââââââ
 ââââââ   âââ   âââ       ââââââ  âââ  ââââââ  ââââââââââ
 ââââââ   âââ   âââ       ââââââ  âââ  ââââââ   âââââââââ
 ââââââââââââ   âââ       âââââââââââââââââââââââââââââââââ
 âââ âââââââ    âââ       âââââââââââââââ  âââââââ ââââââââ

<6> 2022-06-16 15:04:02.507 +00:00 [INF] - Version - 1.1.8.48502653 (54b31809c98ee83e36679ecf92c5582de37172c4)
<6> 2022-06-16 15:04:02.507 +00:00 [INF] - OptimizeForPerformance=True
<6> 2022-06-16 15:04:02.507 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2022-06-16 15:04:02.510 +00:00 [INF] - Loaded server certificate with expiration date of "2022-09-14T15:04:00.0000000+00:00"
<6> 2022-06-16 15:04:02.524 +00:00 [INF] - Using Asp Net server for metrics
<6> 2022-06-16 15:04:02.572 +00:00 [INF] - Created new message store
<6> 2022-06-16 15:04:02.572 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2022-06-16 15:04:02.639 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2022-06-16 15:04:04.064 +00:00 [INF] - Created device scope identities cache
<6> 2022-06-16 15:04:04.069 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2022-06-16 15:04:04.079 +00:00 [INF] - Initialized storing twin manager
<6> 2022-06-16 15:04:04.088 +00:00 [INF] - Initializing configuration
<6> 2022-06-16 15:04:04.103 +00:00 [INF] - New device connection for device <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:04.117 +00:00 [INF] - Client <edgeDevice>/$edgeHub connected to edgeHub, processing existing subscriptions.
<6> 2022-06-16 15:04:04.238 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:04.246 +00:00 [INF] - Attempting to connect to IoT Hub for client <edgeDevice>/$edgeHub via AMQP...
<6> 2022-06-16 15:04:04.708 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2022-06-16 15:04:04.931 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2022-06-16 15:04:04.931 +00:00 [INF] - messagesTo<module>: FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint("/modules/<module>/inputs/input1")
<6> 2022-06-16 15:04:04.931 +00:00 [INF] - <module>ToIoTHub: FROM /messages/modules/<module>/outputs/crate-bundle INTO $upstream
<6> 2022-06-16 15:04:04.932 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2022-06-16 15:04:04.933 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2022-06-16 15:04:04.957 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2022-06-16 15:04:04.958 +00:00 [INF] - Initialized edge hub configuration
<6> 2022-06-16 15:04:04.966 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2022-06-16 15:04:05.029 +00:00 [INF] - Scheduling server certificate renewal for "2022-09-14T15:01:30.0000885Z".
<6> 2022-06-16 15:04:05.030 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2022-06-16 15:04:05.032 +00:00 [INF] - Starting MQTT head
<6> 2022-06-16 15:04:05.091 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2022-06-16 15:04:05.148 +00:00 [INF] - Exiting disconnected state
<6> 2022-06-16 15:04:05.170 +00:00 [INF] - Received device connected callback
<6> 2022-06-16 15:04:05.177 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2022-06-16 15:04:05.179 +00:00 [INF] - Processing subscriptions for client <edgeDevice>/$edgeHub on device connected to cloud.
<6> 2022-06-16 15:04:05.179 +00:00 [INF] - Skipping <edgeDevice>/$edgeHub for subscription processing, as it is currently being processed.
<6> 2022-06-16 15:04:05.193 +00:00 [INF] - Entering connected state
<6> 2022-06-16 15:04:05.196 +00:00 [INF] - Cloud connection for <edgeDevice>/$edgeHub is True
<6> 2022-06-16 15:04:05.199 +00:00 [INF] - Connection status for <edgeDevice>/$edgeHub changed to ConnectionEstablished
<6> 2022-06-16 15:04:05.207 +00:00 [INF] - Client <edgeDevice>/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2022-06-16 15:04:05.207 +00:00 [INF] - Skipping <edgeDevice>/$edgeHub for subscription processing, as it is currently being processed.
<6> 2022-06-16 15:04:05.209 +00:00 [INF] - Created cloud proxy for client <edgeDevice>/$edgeHub via AMQP, with client operation timeout 20 seconds.
<6> 2022-06-16 15:04:05.214 +00:00 [INF] - Starting AMQP head
<6> 2022-06-16 15:04:05.220 +00:00 [INF] - Initialized cloud proxy 133ec3db-685c-4d66-ae66-97a49fb2189d for <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:05.232 +00:00 [INF] - Started MQTT head
<6> 2022-06-16 15:04:05.233 +00:00 [INF] - Created cloud connection for client <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:05.385 +00:00 [INF] - Started AMQP head
<6> 2022-06-16 15:04:05.387 +00:00 [INF] - Starting HTTP head
<6> 2022-06-16 15:04:05.495 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/$edgeHub
<4> 2022-06-16 15:04:05.568 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2022-06-16 15:04:05.574 +00:00 [INF] - Started HTTP head
<6> 2022-06-16 15:04:05.584 +00:00 [INF] - Updated reported properties for <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:05.672 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2022-06-16 15:04:05.768 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - messagesTo<module>: FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint("/modules/<module>/inputs/input1")
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - <module>ToIoTHub: FROM /messages/modules/<module>/outputs/crate-bundle INTO $upstream
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2022-06-16 15:04:05.956 +00:00 [INF] - Client <edgeDevice>/<module> in device scope authenticated locally.
<6> 2022-06-16 15:04:05.964 +00:00 [INF] - Successfully generated identity for clientId <edgeDevice>/<module> and username <edgeDevice>/<edgeDevice>/<module>/?api-version=2020-09-30&DeviceClientType=.NET%2F1.41.0%20%28.NET%20Core%203.1.26%3B%20Linux%205.4.0-65-generic%20%2373-Ubuntu%20SMP%20Mon%20Jan%2018%2017%3A25%3A17%20UTC%202021%3B%20X64%29
<6> 2022-06-16 15:04:05.970 +00:00 [INF] - ClientAuthenticated, <edgeDevice>/<module>, 6e58d842
<6> 2022-06-16 15:04:06.000 +00:00 [INF] - New device connection for device <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.001 +00:00 [INF] - Client <edgeDevice>/<module> connected to edgeHub, processing existing subscriptions.
<6> 2022-06-16 15:04:06.012 +00:00 [INF] - Bind device proxy for device <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.013 +00:00 [INF] - Binding message channel for device Id <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.032 +00:00 [INF] - Processing subscriptions TwinResponse, ModuleMessages, DesiredPropertyUpdates for client <edgeDevice>/<module>.
<6> 2022-06-16 15:04:06.033 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.040 +00:00 [INF] - Attempting to connect to IoT Hub for client <edgeDevice>/<module> via AMQP...
<6> 2022-06-16 15:04:06.046 +00:00 [INF] - Set subscriptions from session state for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.051 +00:00 [INF] - Processing subscriptions TwinResponse, ModuleMessages, DesiredPropertyUpdates for client <edgeDevice>/<module>.
<6> 2022-06-16 15:04:06.052 +00:00 [INF] - Set subscriptions from session state for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.054 +00:00 [INF] - Processing subscriptions TwinResponse, ModuleMessages, DesiredPropertyUpdates for client <edgeDevice>/<module>.
<6> 2022-06-16 15:04:06.055 +00:00 [INF] - Set subscriptions from session state for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Cloud connection for <edgeDevice>/<module> is True
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Connection status for <edgeDevice>/<module> changed to ConnectionEstablished
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Client <edgeDevice>/<module> connected to cloud, processing existing subscriptions.
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Skipping <edgeDevice>/<module> for subscription processing, as it is currently being processed.
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Created cloud proxy for client <edgeDevice>/<module> via AMQP, with client operation timeout 20 seconds.
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Initialized cloud proxy 9704530f-ac86-4288-a3ac-4988c5675ee9 for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Created cloud connection for client <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.239 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.240 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.240 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.240 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.240 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:09.270 +00:00 [INF] - Updated reported properties for <edgeDevice>/$edgeHub
<6> 2022-06-16 15:05:03.065 +00:00 [INF] - Client <leafDevice> in device scope authenticated locally.
<6> 2022-06-16 15:05:03.066 +00:00 [INF] - Successfully generated identity for clientId <leafDevice> and username <edgeDevice>/<leafDevice>/?api-version=2020-09-30&DeviceClientType=.NET%2F1.40.0%20%28.NET%206.0.3%3B%20Microsoft%20Windows%2010.0.19044%20WindowsProduct%3A0x00000004%3B%20X64%3B%20%7Bdb4c906c-0f48-4e1c-9957-662bf3106537%7D%29
<6> 2022-06-16 15:05:03.067 +00:00 [INF] - ClientAuthenticated, <leafDevice>, 594816b0
<6> 2022-06-16 15:05:03.068 +00:00 [INF] - New device connection for device <leafDevice>
<6> 2022-06-16 15:05:03.069 +00:00 [INF] - Client <leafDevice> connected to edgeHub, processing existing subscriptions.
<6> 2022-06-16 15:05:03.070 +00:00 [INF] - Bind device proxy for device <leafDevice>
<6> 2022-06-16 15:05:03.070 +00:00 [INF] - Binding message channel for device Id <leafDevice>
<6> 2022-06-16 15:05:03.070 +00:00 [INF] - Attempting to connect to IoT Hub for client <leafDevice> via AMQP...
<6> 2022-06-16 15:05:03.070 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.155 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, C2D for client <leafDevice>.
<6> 2022-06-16 15:05:03.155 +00:00 [INF] - Set subscriptions from session state for <leafDevice>
<6> 2022-06-16 15:05:03.160 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, C2D for client <leafDevice>.
<6> 2022-06-16 15:05:03.161 +00:00 [INF] - Set subscriptions from session state for <leafDevice>
<6> 2022-06-16 15:05:03.244 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, C2D for client <leafDevice>.
<6> 2022-06-16 15:05:03.244 +00:00 [INF] - Set subscriptions from session state for <leafDevice>
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Cloud connection for <leafDevice> is True
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Connection status for <leafDevice> changed to ConnectionEstablished
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Client <leafDevice> connected to cloud, processing existing subscriptions.
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Skipping <leafDevice> for subscription processing, as it is currently being processed.
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Created cloud proxy for client <leafDevice> via AMQP, with client operation timeout 20 seconds.
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Initialized cloud proxy 3946b286-4635-4d77-8f98-a90b548b6010 for <leafDevice>
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Created cloud connection for client <leafDevice>
<6> 2022-06-16 15:05:03.248 +00:00 [INF] - Start listening for C2D messages for <leafDevice>
<6> 2022-06-16 15:05:03.351 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.351 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.351 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.351 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.352 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.379 +00:00 [INF] - Updated reported properties for <edgeDevice>/$edgeHub
<4> 2022-06-16 15:05:33.505 +00:00 [WRN] - Did not receive ack for message 39db8087-d4e3-4c11-bbd4-d6ef44d0d5ee from device/module <edgeDevice>/<module>
<4> 2022-06-16 15:05:33.507 +00:00 [WRN] - Error sending messages to module <edgeDevice>/<module>
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 491
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 167
-->
```
</details>

## Additional Information
This started happening out of the blue. The only way we have been able to actually 'unclog' the messages is by deploying a version of the module that does not attempt to invoke any direct method on leaf devices. 

Essentially our module receives a message, transforms the message, and attempts to send the transformed message to many leaf devices via a collection of tasks: 

```
        public static async Task SendMessage<T>(ModuleClient moduleClient, T message, string methodName)
        {
            if (message != null)
            {
                MethodRequest methodRequest = new MethodRequest(methodName, Encoding.UTF8.GetBytes(Converter<T>.ToJson(message)));

                var deviceIds = GetDeviceIds(await moduleClient.GetTwinAsync());

                IEnumerable<Task<bool>> tasks =
                    from deviceId in deviceIds
                    select InvokeMethod(moduleClient, methodRequest, deviceId);

                List<Task<bool>> tasksToRun = tasks.ToList();

                while (tasksToRun.Any())
                {
                    Task<bool> finishedTask = await Task.WhenAny(tasksToRun);
                    tasksToRun.Remove(finishedTask);
                    await finishedTask;
                }
            }
        }

        private static async Task<bool> InvokeMethod(ModuleClient moduleClient, MethodRequest methodRequest, string deviceId)
        {
            var doRetry = true;
            var retryCount = 3;
            var cancelAfter = 3000;
            var attempt = 0;

            while (doRetry && attempt < retryCount)
            {
                var cts = new CancellationTokenSource();
                cts.CancelAfter(cancelAfter);

                try
                {
                    Console.WriteLine($"Invoking direct method on device: {deviceId}");

                    var response = await moduleClient.InvokeMethodAsync(deviceId, methodRequest, cts.Token);

                    Console.WriteLine($"Successfully invoked direct method on device: {deviceId}");

                    doRetry = false;

                }
                catch (OperationCanceledException)
                {
                    Console.WriteLine($"Failed to invoke direct method on device: {deviceId} :: RETRYING");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to invoke direct method on device: {deviceId} :: Exception {ex.Message}");

                    doRetry = false;
                }

                attempt++;
                cancelAfter += 1000;
            }

            return !doRetry;
        }
```

**Comment by scb01** [comment]
@zachcdr 
Can you share the version details of IotEdge and EdgeHub.

**Comment by zachcdr** [comment]
@scb01 it appears to be 1.1 for both the hub and agent. Is that what you were hoping for?
![image](https://user-images.githubusercontent.com/9221566/173909740-a06f0f03-f160-4747-94c5-2b9d8ed47a86.png)
![image](https://user-images.githubusercontent.com/9221566/173909746-14ccaadd-5f82-474a-973e-db4409cd54ef.png)

**Comment by zachcdr** [comment]
I also updated the initial comment with some additional edge hub logs that show the issue immediately after a restart. The hub abandons the message that it was previously choking on and begins retrying the next message in the queue over and over.

**Comment by varunpuranik** [comment]
From the EdgeHub logs and the code you provided above, here is what I believe is happening: 
- You are invoking the direct method as an async call  from the context of the callback. 
- This is causing the callback to not complete correctly because of some threading issue. (I am not sure why, maybe @drwill-ms or @andyk-ms might know.) 
- Because of that EdgeHub does not get the ACK from the client, so it attempts to re-send the message. 

One workaround I would suggest would be to pipe the messages to an internal queue, and have another thread (started from your app, not in the callback), that monitors the queue and sends the direct methods when it finds a message in the queue. I believe that would solve the problem.

**Comment by zachcdr** [comment]
Hey @varunpuranik I really appreciate the feedback.

We have been running this paradigm in production for nearly a year now and have never experienced the issue before. It just began happening with our latest release in both our dev and production edge environments. I can definitely implement your suggestions, but I am excited to understand a little bit more about the issue as well.

**Comment by varunpuranik** [comment]
@zachcdr - that is interesting. What change caused to start repro'ing? Did you update the IoT Edge runtime, the SDK used in the module, the module logic, or a combination of those?

**Comment by zachcdr** [comment]
@varunpuranik @scb01 

We figured it out!

The module was created in Visual Studio over a year ago via the template. I believe that the template auto-generated this line of code in the project file:
`<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.*" />`

This totally explains why the same SHA build on day X would work and when built on day Y (after a new SDK release for example) would not. 

We explicitly downgraded to 1.40.0:
`<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.40.0" />`
and no longer are experiencing the issue. I feel silly for missing this as I was so caught up in the diffs between SHAs and in not seeing a change to the project file assumed there were no dependency updates.

It would seem that there is some breaking change in SDK 1.41.0.. perhaps something related to this:
![image](https://user-images.githubusercontent.com/9221566/174150083-94917588-3687-4422-b00c-3fec3b7c3444.png)

**Comment by varunpuranik** [comment]
@zachcdr - thanks, that makes sense - this seems something related to the C# SDK. 
I am not able to transfer the issue to that repo, so can you please close this issue and open an issue on the C# SDK repo instead? https://github.com/Azure/azure-iot-sdk-csharp

Thanks!

**Comment by zachcdr** [comment]
@varunpuranik I definitely can. Thanks again for being our Rubber Ducky and helping us through this!
