### ISSUE TITLE
Unexpected "Operation timeout expired" exception when offline

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/iotedge#654]
### Current behavior

Logging in edgeHub shows "Unexpected Operation timeout expired"  when I disable my WIFI on my IoTEge device (Surface device with Windows 10 and running Linux containers). 

### Expected behavior

I run only one module, a heartbeat. Code is available at [here on github](https://github.com/sandervandevelde/iot-edge-heartbeat/). Image is available from [Docker Hubs](https://cloud.docker.com/u/svelde/repository/docker/svelde/iot-edge-heartbeat).

I expect no exception in the log when being offline.

### Steps to reproduce

Steps:

1. Run an IoTEdge only with the heartbeat module
2. See that the module produces messages and they arrive at the IoTHub 
3. Check the edgeHub logging. No exceptions.
4. Disable Wifi
5. See that the module still produces messages
6. The edgeHub logging is filled with these exceptions as shown below
7. Enable Wifi again
8. The exceptions are not shown anymore

### Exception from log

this is the exception from the *edgeHub* log:

> 2018-12-17 22:03:41.034 +00:00 [WRN] - Could not get an active Iot Hub connection for device surfaceDemo/heartBeat
2018-12-17 22:04:09.321 +00:00 [INF] - Reauthenticating connected clients
2018-12-17 22:04:13.199 +00:00 [INF] - Attempting to connect to IoT Hub for client surfaceDemo/heartBeat via AMQP...
2018-12-17 22:04:33.214 +00:00 [ERR] - Error creating or updating the cloud proxy for client surfaceDemo/heartBeat
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs:line 49
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 132
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 179
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.GetCloudProxyAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 157
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.<>c__DisplayClass26_0.<<CreateOrUpdateAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateOrUpdateAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 101
2018-12-17 22:04:33.218 +00:00 [INF] - Error getting cloud connection for device surfaceDemo/heartBeat
Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Error updating identity for device surfaceDemo/heartBeat ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs:line 49
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 132
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 179
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.GetCloudProxyAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 157
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.<>c__DisplayClass26_0.<<CreateOrUpdateAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateOrUpdateAsync(IClientCredentials newCredentials) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager.<>c__DisplayClass30_0.<<CreateOrUpdateCloudConnection>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs:line 173
   --- End of inner exception stack trace ---
2018-12-17 22:04:33.219 +00:00 [WRN] - Could not get an active Iot Hub connection for device surfaceDemo/heartBeat

### Notes

PS C:\WINDOWS\system32> iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeHub          running          Up 32 minutes    mcr.microsoft.com/azureiotedge-hub:1.0.4
heartBeat        running          Up 33 minutes    svelde/iot-edge-heartbeat:2.2.3-amd64
edgeAgent        running          Up 33 minutes    mcr.microsoft.com/azureiotedge-agent:1.0.4

PS C:\WINDOWS\system32> docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d0138d4
ID: VVMH:S45J:BDJR:4KS5:VZT2:5PUI:ZNPH:JFD5:AHGJ:NDY5:A7JP:E373
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 58
 Goroutines: 77
 System Time: 2018-12-17T22:26:30.8406877Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by varunpuranik** [comment]
@sandervandevelde - what do your routes look like? From the logs you have provided and from your module code, it looks like the module is sending telemetry that is being routed to IoTHub. And when offline, when the EdgeHub tries to route the messages to IoTHub, it gets a Timeout exception. This seems as expected/designed.

**Comment by sandervandevelde** [comment]
Yes, it's is just routed to the IoTHub. 
This timeout seems silly, the edgeHub is already in offline mode (Connection status for surfaceDemo/heartBeat changed to Disconnected; Cloud connection for surfaceDemo/$edgeHub is False; etc.).
Why throw an exception though?

**Comment by varunpuranik** [comment]
EdgeHub will continuously try to retry the operation to IoTHub even when offline, as there is no event triggered when the device goes back online. Because of that you see the timeout exceptions. 
We are planning to make some updates to our logs in one of the upcoming releases, but the underlying behavior will stay the same (at least for now).

**Comment by sandervandevelde** [comment]
OK. this explanation makes the decision behind the exception more clear. Thanks for the update.
