### ISSUE TITLE
Edge Hub module can't change the permissions of the host folder

### ISSUE THREAD

**Issue by lucianoctorres** [Azure/iotedge#6541]
## Expected Behavior
According to the [documentation ](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-2020-11#host-system-permissions), giving permission 700 to user 1000 on the host storage should work.

## Current Behavior
Since version 1.3.0 of edgeHub, it uses a different user (13623), which can't access to the storage folder set for uid 1000. The script startHub.sh tries to change the owner (as edgeAgent does), but it does not work (perhaps because edgeHub does not start as root?)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Configure a host folder for storage for edgeAgent and edgeHub
2. Set the owner to uid 1000, permissions 700
3. edge hub will not start
4.

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.3.0
* Edge Agent [image tag (e.g. 1.0.0)]: 1.3.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.3.0
* Docker/Moby [run `docker version`]: 20.10.17+azure-1, build 100c70180fde3601def79a59cc3e996aa553c9b9

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>edge-hub logs</summary>
```
<6> 2022-07-27 13:13:24.486 +00:00 [INF] - Initializing Edge Hub
<6> 2022-07-27 13:13:24.487 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2022-07-27 13:13:24.490 +00:00 [INF] - Version - 1.3.0.57041647 (b022069058d21deb30c7760c4e384b637694f464)
<6> 2022-07-27 13:13:24.490 +00:00 [INF] - OptimizeForPerformance=True
<6> 2022-07-27 13:13:24.491 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2022-07-27 13:13:24.493 +00:00 [INF] - Loaded server certificate with expiration date of "2022-08-26T13:13:22.0000000+00:00"
<6> 2022-07-27 13:13:24.516 +00:00 [INF] - Using Asp Net server for metrics
<6> 2022-07-27 13:13:24.666 +00:00 [INF] - Created new message store
<6> 2022-07-27 13:13:24.666 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2022-07-27 13:13:24.879 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<3> 2022-07-27 13:13:24.924 +00:00 [ERR] - Stopping with exception
System.UnauthorizedAccessException: Access to the path '/iotedge/storage/edgeHub/EdgeHubIV' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode)
   at Microsoft.Azure.Devices.Edge.Util.DiskFile.<>c__DisplayClass4_0.<<WriteAllAsync>g__WriteOperation|0>d.MoveNext() in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/DiskFile.cs:line 34
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout, Action action) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 158
   at Microsoft.Azure.Devices.Edge.Util.Edged.EncryptionProvider.CreateAsync(String storagePath, Uri workloadUri, String edgeletApiVersion, String edgeletClientApiVersion, String moduleId, String genId, String initializationVectorFileName) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/EncryptionProvider.cs:line 30
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__28_29(String uri) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 240
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__28_8(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 236
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.GetTwinStore(IComponentContext context) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 662
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__36_25(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 467
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__36_28(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 527
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 80
Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the path '/iotedge/storage/edgeHub/EdgeHubIV' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '/iotedge/storage/edgeHub/EdgeHubIV' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode)
   at Microsoft.Azure.Devices.Edge.Util.DiskFile.<>c__DisplayClass4_0.<<WriteAllAsync>g__WriteOperation|0>d.MoveNext() in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/DiskFile.cs:line 34
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout, Action action) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 158
   at Microsoft.Azure.Devices.Edge.Util.Edged.EncryptionProvider.CreateAsync(String storagePath, Uri workloadUri, String edgeletApiVersion, String edgeletClientApiVersion, String moduleId, String genId, String initializationVectorFileName) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/EncryptionProvider.cs:line 30
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__28_29(String uri) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 240
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__28_8(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 236
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.GetTwinStore(IComponentContext context) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 662
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__36_25(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 467
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__36_28(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 527
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 80
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 35

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by huguesBouvier** [comment]
Hello!

We set the owner to be 13623 on purpose. 1000 was flag as a security risk because it usually have more power than regular users.
EdgeHub operates on 13623 so you need to allow 700 to 13623.

**Comment by lucianoctorres** [comment]
It makes sense, should then the documentation be updated?

**Comment by DarthLowen** [comment]
I completely agree with @lucianoctorres , edge servers that have shipped with 1.2.x runtime and are now upgraded to 1.3 for LTS reasons will need to have some sort of fix applied. This is never explained in detail how we're (1) supposed to know this and (2) supposed to do this! Very annoying! Apparently edgeAgent automatically changes ownership of its folder to 13622. Is there a reason edgeHub can't do this?

Related question, we're also supposed to use edgeHub and edgeAgent version 1.3 together with the iotedge 1.3 runtime. What is the correct procedure to upgrade, first the runtime and then the modules or vice versa? Our edge server management tool needs some time to upgrade all of our edge servers and we can't synchronize the upgrade of the runtime with a new deployment. The existing edgeHub folder contains many items already, if we change ownership of the folder to 13623 before we deploy the 1.3 images, will the 1.2 image still be able to use them?

I'm a big fan of the edge-server functionality, but I feel like it's being treated a bit 'step-motherly'...

**Comment by jelalanne** [comment]
Hello there,
Same issue here, with both edgeHub et Agent. I have tried setting owner to 13623 for edgeHub and 13622 for edgeAgent but doesn't work. Thanks for the help!

```
sudo mkdir -p /etc/iotedge/storage/edgeAgent
sudo mkdir -p /etc/iotedge/storage/edgeHub
sudo chown -R 13622:13622 /etc/iotedge/storage/edgeAgent
sudo chown -R 13623:13623 /etc/iotedge/storage/edgeHub
sudo chmod -R 700 /etc/iotedge/storage/
```

![image](https://user-images.githubusercontent.com/32770824/182805151-5263a377-3e1f-44db-96a0-69f4339fc6ca.png)
![image](https://user-images.githubusercontent.com/32770824/182805526-52b2cc70-fbc3-40ea-ae32-c8616081e657.png)
![image](https://user-images.githubusercontent.com/32770824/182805628-5bca0499-fb43-47fc-b77c-54c60739b02a.png)

**Comment by orjanto** [comment]
Hi, 
I also have the same issue. This fix works for both clean install of 1.3.0 and upgrade from 1.2.x to 1.3.0:
```
sudo chmod 770 /etc/iotedge/storage
sudo chown 13622:13623 /etc/iotedge/storage
```

**Comment by jelalanne** [comment]
What did work for me, but i'm not sure if it's ok:

```
sudo mkdir /etc/aziot/storage/edgeAgent (Binds instead of volumes in deployment make the module unable to create folders, no permissions for that)
sudo mkdir /etc/aziot/storage/edgeHub
sudo chown -R 13623:iotedge /etc/aziot/storage (Don't forget the -R option for recursive)
sudo chmod -R /etc/aziot/storage
```

**Comment by enterz** [comment]
Ahh this sounds like the same issue I posted to [stackoverflow](https://stackoverflow.com/questions/73034539/azure-edgeagent-not-starting-after-upgrade-to-1-3-0) 2 weeks ago. Was about to open an issue here when I saw this one open already.

Let me try the work-a-round suggested above on one of our test systems.

**Comment by DarthLowen** [comment]
> Ahh this sounds like the same issue I posted to [stackoverflow](https://stackoverflow.com/questions/73034539/azure-edgeagent-not-starting-after-upgrade-to-1-3-0) 2 weeks ago. Was about to open an issue here when I saw this one open already.
> 
> Let me try the work-a-round suggested above on one of our test systems.

The workaround works for sure, the question is how we can deploy this consistently to devices in the field (and/or devices on their way to the field). Basically if edgeHub were able to change the ownership of its own folder, all would be well (because edgeAgent already successfully does this)

**Comment by jelalanne** [comment]
> > Ahh this sounds like the same issue I posted to [stackoverflow](https://stackoverflow.com/questions/73034539/azure-edgeagent-not-starting-after-upgrade-to-1-3-0) 2 weeks ago. Was about to open an issue here when I saw this one open already.
> > Let me try the work-a-round suggested above on one of our test systems.
> 
> The workaround works for sure, the question is how we can deploy this consistently to devices in the field (and/or devices on their way to the field). Basically if edgeHub were able to change the ownership of its own folder, all would be well (because edgeAgent already successfully does this)

For this to happen, we should be able to use Volume and not Bind as shared storage option. Volume gives the module the same permission on the shared folder than the ones on the host storage. (From what I understood)

**Comment by jelalanne** [comment]
But currently the documentation forces us to use Binds in the deployment manifests

**Comment by gordonwang0** [comment]
edgeHub is supposed to be able to fix its directory permissions just like edgeAgent. However, there's a typo in the startup script that breaks it:
https://github.com/Azure/iotedge/blob/1b3f818c2eecd08d9442eee98f1b57f5502f166b/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/hubStart.sh#L50

The script is expecting the default folder to be edge**h**ub, while I'm guessing everyone here has the folder mounted as edge**H**ub.

We'll release a fix for this. In the meantime, you can use the workarounds mentioned above, or rename the folder to **edgehub**.

**Comment by DarthLowen** [comment]
> We'll release a fix for this. In the meantime, you can use the workarounds mentioned above, or rename the folder to **edgehub**.

Awesome! Any idea when this fix will be released? We're having issues with 1.2.6 and 1.2.8 and were urged to upgrade to 1.3 because of those (as part of azure support ticket 2207070050001721)

And special thanks to the originator of this bug report, Luciano!

Cheers,
Nic.

**Comment by StephanZaat** [comment]
I also just found this issue by accident because the edgeHub container was not writing logs to the storage directory since the upgrade.

Perhaps an additional check can be added in the `iotedge check --verbose` command to check for directory permissions?

**Comment by gordonwang0** [comment]
I have merged the PR that implements the fix. It will be released officially in the 1.4 version. Unfortunately, I don't have a estimated date of release.

**Comment by micahl** [comment]
@gordonwang0 recommend we close this issue given the fix is done and only pending a release.

**Comment by jelalanne** [comment]
> That workaround did work for me, but i'm not sure if it's ok:
> 
> ```
> sudo mkdir /etc/aziot/storage/edgeAgent (Binds instead of volumes in deployment make the module unable to create folders, no permissions for that)
> sudo mkdir /etc/aziot/storage/edgeHub
> sudo chown -R 13623:iotedge /etc/aziot/storage (Don't forget the -R option for recursive)
> sudo chmod -R /etc/aziot/storage
> ```

Guys, just found out my workaround works like a charm for edgeAgent and edgeHub, but one of my other modules which also uses storage's folder is not working anymore. Something missing I can't see?
