### ISSUE TITLE
Error while I try to change the timeToLiveSecs property

### ISSUE THREAD

**Issue by aleducq** [Azure/iotedge#6551]
## Expected Behavior
Updating timeToLiveSecs property shouldn't make crash other modules

## Current Behavior
Just changing the timeToLiveSecs property.
The edgeAgent stop all modules (Azure IIoT publisher, twin, discoverer)
The edgeHub throws this message:

```
<4> 2022-08-01 08:40:17.449 +00:00 [WRN] - Error merging desired properties patch with existing desired properties for edge hub
System.ArgumentNullException: Value cannot be null. (Parameter 'routes')
   at Microsoft.Azure.Devices.Edge.Util.Preconditions.CheckNotNull[T](T reference, String paramName, String message) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Preconditions.cs:line 43
   at Microsoft.Azure.Devices.Edge.Hub.Core.Config.EdgeHubDesiredProperties..ctor(String schemaVersion, IDictionary`2 routes, StoreAndForwardConfiguration storeAndForwardConfiguration) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/EdgeHubDesiredProperties.cs:line 15
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Azure.Devices.Edge.Hub.Core.Config.TwinConfigSource.PatchDesiredProperties(TwinCollection baseline, TwinCollection patch) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/TwinConfigSource.cs:line 153
```
Other modules don't restart

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Clone iiotedge deployment manifest
2. Change timeToLiveSecs value (set to 172800 to have 48 hours of rentention)
3. Apply changes

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Error while fetching latest versions of edge components: could not create HTTP client
        caused by: invalid uri character

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: CentOS Linux release 7.9.2009 (Core)
* Architecture [e.g. amd64, arm32, arm64]: Linux 3.10.0-1160.42.2.el7.x86_64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.1.5
* Edge Agent [image tag (e.g. 1.0.0)]: azureiotedge-agent:1.1
* Edge Hub [image tag (e.g. 1.0.0)]: azureiotedge-hub:1.1
* Docker/Moby [run `docker version`]: 3.0.6

## Additional Information
Deployment manifest generated using Helm chart for Azure IIoT 2.8.3. 
Clone once to add proxy settings, it works fine.
Clone a second time to change timeToLiveSecs value --> KO

## Deployment Manifest Content
```json
{
    "modulesContent": {
        "$edgeAgent": {
            "properties.desired": {
                "schemaVersion": "1.0",
                "runtime": {
                    "type": "docker",
                    "settings": {
                        "minDockerVersion": "v1.25",
                        "loggingOptions": "",
                        "registryCredentials": {}
                    }
                },
                "systemModules": {
                    "edgeAgent": {
                        "env": {
                            "ExperimentalFeatures__Enabled": {
                                "value": "true"
                            },
                            "ExperimentalFeatures__EnableGetLogs": {
                                "value": "true"
                            },
                            "ExperimentalFeatures__EnableUploadLogs": {
                                "value": "true"
                            },
                            "ExperimentalFeatures__EnableMetrics": {
                                "value": "true"
                            },
                            "http_proxy": {
                                "value": "http://<proxy_address>:<proxy_port>"
                            },
                            "https_proxy": {
                                "value": "http://<proxy_address>:<proxy_port>"
                            }
                        },
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-agent:1.1",
                            "createOptions": "{}"
                        },
                        "type": "docker"
                    },
                    "edgeHub": {
                        "env": {
                            "SslProtocols": {
                                "value": "tls1.2"
                            },
                            "http_proxy": {
                                "value": "http://<proxy_address>:<proxy_port>"
                            },
                            "https_proxy": {
                                "value": "http://<proxy_address>:<proxy_port>"
                            }
                        },
                        "restartPolicy": "always",
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-hub:1.1",
                            "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"443/tcp\":[{\"HostPort\":\"443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}]}},\"ExposedPorts\":{\"5671/tcp\":{},\"8883/tcp\":{}}}"
                        },
                        "status": "running",
                        "type": "docker"
                    }
                },
                "modules": {}
            }
        },
        "$edgeHub": {
            "properties.desired": {
                "schemaVersion": "1.0",
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 172800
                }
            }
        }
    }
}
```

**Comment by and-rewsmith** [comment]
@aleducq I would have thought predeployment checks would have prevented that deployment manifest to be applied as it is missing routes field in $edgeHub desired properties. I tested this myself just now via CLI and it prevents this deployment from being applied.

To fix your issue you will need to add this under "properties.desired" object:
```
                "routes": {
                    "ToUpstream": "FROM /messages/* INTO $upstream"
                },
```

**Comment by aleducq** [comment]
Hello @and-rewsmith , 
Thanks for your help. I've applied this change and I don't see the Warning message but it doesn't restart the other modules from aure iiot (twin, publisher and discovery) and neither the iot edge collector metrics.
Edge Agent:
```
2022-08-02 07:19:11  Starting Edge Agent
2022-08-02 07:19:11  Changing ownership of management socket: /var/lib/iotedge/mgmt.sock
2022-08-02 07:19:12.014 +00:00 Edge Agent Main()
<6> 2022-08-02 07:19:12.229 +00:00 [INF] - Initializing Edge Agent.
<6> 2022-08-02 07:19:12.411 +00:00 [INF] - Version - 1.1.15.57634071 (01685778d8320f126f2daf2f86a78a3d9d4b2f2c)
<6> 2022-08-02 07:19:12.411 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2022-08-02 07:19:12.431 +00:00 [INF] - Detected proxy http://xxxxxxxxxxx.zscaler.net:9480/
<6> 2022-08-02 07:19:12.466 +00:00 [INF] - Experimental features configuration: {"Enabled":true,"DisableCloudSubscriptions":false}
<6> 2022-08-02 07:19:12.622 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:02/26/2024 08:47:56] to Root
<6> 2022-08-02 07:19:12.727 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics
<6> 2022-08-02 07:19:12.875 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2022-08-02 07:19:12.880 +00:00 [INF] - Started operation Get system resources
<6> 2022-08-02 07:19:12.881 +00:00 [INF] - Collecting metadata metrics
<6> 2022-08-02 07:19:12.951 +00:00 [INF] - Set metadata metrics: 1.1.15.57634071 (01685778d8320f126f2daf2f86a78a3d9d4b2f2c), {"Enabled":true,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"x86_64","Version":"1.0.9.4","Provisioning":{"Type":"","DynamicReprovisioning":false},"ServerVersion":"","KernelVersion":"","OperatingSystem":"","NumCpus":0,"Virtualized":""}, True
<6> 2022-08-02 07:19:12.971 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2022-08-02 07:19:12.975 +00:00 [INF] - Started operation refresh twin config
<6> 2022-08-02 07:19:12.998 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<6> 2022-08-02 07:19:13.430 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2022-08-02 07:19:13.485 +00:00 [INF] - Started operation Metrics Scrape
<6> 2022-08-02 07:19:13.485 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2022-08-02 07:19:14.050 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2022-08-02 07:19:14.050 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2022-08-02 07:19:14.050 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2022-08-02 07:19:14.051 +00:00 [INF] - Registering request handler RestartModule
<6> 2022-08-02 07:19:14.676 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_WebSocket_Only.
<6> 2022-08-02 07:19:14.794 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2022-08-02 07:19:14.861 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 29 and reported properties version 101.
<6> 2022-08-02 07:19:15.376 +00:00 [INF] - Plan execution started for deployment 29
<6> 2022-08-02 07:19:15.394 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module edgeHub]\n  [Create module edgeHub]\n)]\n  [Start module edgeHub]\n)"
<6> 2022-08-02 07:19:15.399 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module edgeHub]\n  [Create module edgeHub]\n)"
<6> 2022-08-02 07:19:17.235 +00:00 [INF] - Executing command: "Start module edgeHub"
<6> 2022-08-02 07:19:17.752 +00:00 [INF] - Plan execution ended for deployment 29
<6> 2022-08-02 07:19:18.136 +00:00 [INF] - Updated reported properties
<6> 2022-08-02 07:19:23.317 +00:00 [INF] - Updated reported properties
```
Edge Hub:
```
2022-08-02 07:19:17  Starting Edge Hub
2022-08-02 07:19:17.840 +00:00 Edge Hub Main()
<6> 2022-08-02 07:19:18.688 +00:00 [INF] - Installing certificates [CN=iotedged workload ca:02/26/2024 08:47:56],[CN=Test Edge Device CA:02/26/2024 08:47:56],[CN=Test Edge Owner CA:02/26/2024 08:47:56] to Root
<6> 2022-08-02 07:19:18.727 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:02/26/2024 08:47:56] to Root
<6> 2022-08-02 07:19:18.741 +00:00 [INF] - Enabling SSL protocols: Tls12
<6> 2022-08-02 07:19:18.886 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
<6> 2022-08-02 07:19:19.017 +00:00 [INF] - Detected proxy http://xxxxxxxxxxxx.zscaler.net:9480/
<6> 2022-08-02 07:19:19.334 +00:00 [INF] - Created persistent store at /tmp/edgeHub
<6> 2022-08-02 07:19:19.386 +00:00 [INF] - Initializing Edge Hub
<6> 2022-08-02 07:19:19.386 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2022-08-02 07:19:19.388 +00:00 [INF] - Version - 1.1.15.57634071 (01685778d8320f126f2daf2f86a78a3d9d4b2f2c)
<6> 2022-08-02 07:19:19.389 +00:00 [INF] - OptimizeForPerformance=True
<6> 2022-08-02 07:19:19.389 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2022-08-02 07:19:19.391 +00:00 [INF] - Loaded server certificate with expiration date of "2022-10-31T07:19:17.0000000+00:00"
<6> 2022-08-02 07:19:19.403 +00:00 [INF] - Using Asp Net server for metrics
<6> 2022-08-02 07:19:19.431 +00:00 [INF] - Created device scope identities cache
<6> 2022-08-02 07:19:19.455 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2022-08-02 07:19:19.494 +00:00 [INF] - Created new message store
<6> 2022-08-02 07:19:19.545 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2022-08-02 07:19:19.661 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2022-08-02 07:19:19.688 +00:00 [INF] - Initialized storing twin manager
<6> 2022-08-02 07:19:19.717 +00:00 [INF] - Initializing configuration
<6> 2022-08-02 07:19:19.730 +00:00 [INF] - New device connection for device iotedgerumillynoprod/$edgeHub
<6> 2022-08-02 07:19:19.743 +00:00 [INF] - Client iotedgerumillynoprod/$edgeHub connected to edgeHub, processing existing subscriptions.
<6> 2022-08-02 07:19:19.922 +00:00 [INF] - Processing pending subscriptions for iotedgerumillynoprod/$edgeHub
<4> 2022-08-02 07:19:20.390 +00:00 [WRN] - Empty edge hub configuration received. Ignoring...
<6> 2022-08-02 07:19:20.584 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedgerumillynoprod/$edgeHub via AMQP over WebSockets...
<6> 2022-08-02 07:19:21.368 +00:00 [INF] - Exiting disconnected state
<6> 2022-08-02 07:19:21.382 +00:00 [INF] - Received device connected callback
<6> 2022-08-02 07:19:21.387 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2022-08-02 07:19:21.388 +00:00 [INF] - Processing subscriptions for client iotedgerumillynoprod/$edgeHub on device connected to cloud.
<6> 2022-08-02 07:19:21.389 +00:00 [INF] - Skipping iotedgerumillynoprod/$edgeHub for subscription processing, as it is currently being processed.
<6> 2022-08-02 07:19:21.416 +00:00 [INF] - Entering connected state
<6> 2022-08-02 07:19:21.419 +00:00 [INF] - Cloud connection for iotedgerumillynoprod/$edgeHub is True
<6> 2022-08-02 07:19:21.421 +00:00 [INF] - Connection status for iotedgerumillynoprod/$edgeHub changed to ConnectionEstablished
<6> 2022-08-02 07:19:21.422 +00:00 [INF] - Client iotedgerumillynoprod/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2022-08-02 07:19:21.422 +00:00 [INF] - Skipping iotedgerumillynoprod/$edgeHub for subscription processing, as it is currently being processed.
<6> 2022-08-02 07:19:21.424 +00:00 [INF] - Created cloud proxy for client iotedgerumillynoprod/$edgeHub via AMQP over WebSockets, with client operation timeout 20 seconds.
<6> 2022-08-02 07:19:21.427 +00:00 [INF] - Initialized cloud proxy 7eb1d457-1a9d-4509-aafc-1aa3cb6dd744 for iotedgerumillynoprod/$edgeHub
<6> 2022-08-02 07:19:21.428 +00:00 [INF] - Created cloud connection for client iotedgerumillynoprod/$edgeHub
<6> 2022-08-02 07:19:21.661 +00:00 [INF] - Processing pending subscriptions for iotedgerumillynoprod/$edgeHub
<6> 2022-08-02 07:19:21.881 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2022-08-02 07:19:21.893 +00:00 [INF] - Updated reported properties for iotedgerumillynoprod/$edgeHub
<6> 2022-08-02 07:19:22.131 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2022-08-02 07:19:22.274 +00:00 [INF] - Set the following 1 route(s) in edge hub
<6> 2022-08-02 07:19:22.274 +00:00 [INF] - ToUpstream: FROM /messages/* INTO $upstream
<6> 2022-08-02 07:19:22.275 +00:00 [INF] - Updated message store TTL to 172800 seconds
<6> 2022-08-02 07:19:22.276 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2022-08-02 07:19:22.282 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2022-08-02 07:19:22.283 +00:00 [INF] - Initialized edge hub configuration
<6> 2022-08-02 07:19:22.289 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2022-08-02 07:19:22.336 +00:00 [INF] - Scheduling server certificate renewal for "2022-10-31T07:16:47.0000926Z".
<6> 2022-08-02 07:19:22.337 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2022-08-02 07:19:22.339 +00:00 [INF] - Starting MQTT head
<6> 2022-08-02 07:19:22.362 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2022-08-02 07:19:22.421 +00:00 [INF] - Starting AMQP head
<6> 2022-08-02 07:19:22.433 +00:00 [INF] - Started MQTT head
<6> 2022-08-02 07:19:22.528 +00:00 [INF] - Started AMQP head
<6> 2022-08-02 07:19:22.530 +00:00 [INF] - Starting HTTP head
<4> 2022-08-02 07:19:22.684 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2022-08-02 07:19:22.694 +00:00 [INF] - Started HTTP head
<6> 2022-08-02 07:19:24.875 +00:00 [INF] - Updated reported properties for iotedgerumillynoprod/$edgeHub
<6> 2022-08-02 07:24:22.293 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
```

**Comment by aleducq** [comment]
Update: @and-rewsmith, I don't understand why but after a new clone from the generated manifest from helm charts, it' up now.
Still have the problem for iot edge metrics collector but I will put a message in #6552

**Comment by aleducq** [comment]
Oh non still have the issue...
```
<6> 2022-08-02 08:03:10.347 +00:00 [INF] - Plan execution started for deployment 37
<6> 2022-08-02 08:03:10.348 +00:00 [INF] - Executing command: "Stop module twin"
<6> 2022-08-02 08:03:10.662 +00:00 [INF] - Executing command: "Stop module publisher"
<6> 2022-08-02 08:03:10.867 +00:00 [INF] - Executing command: "Stop module discovery"
<6> 2022-08-02 08:03:11.045 +00:00 [INF] - Executing command: "Stop module IoTEdgeMetricsCollector"
<6> 2022-08-02 08:03:11.236 +00:00 [INF] - Executing command: "Remove module twin"
<6> 2022-08-02 08:03:11.300 +00:00 [INF] - Executing command: "Remove module publisher"
<6> 2022-08-02 08:03:11.362 +00:00 [INF] - Executing command: "Remove module discovery"
<6> 2022-08-02 08:03:11.401 +00:00 [INF] - Executing command: "Remove module IoTEdgeMetricsCollector"
<6> 2022-08-02 08:03:11.446 +00:00 [INF] - Executing command: "Saving twin to store"
<6> 2022-08-02 08:03:11.455 +00:00 [INF] - Executing command: "Saving publisher to store"
<6> 2022-08-02 08:03:11.456 +00:00 [INF] - Executing command: "Saving discovery to store"
<6> 2022-08-02 08:03:11.456 +00:00 [INF] - Executing command: "Saving IoTEdgeMetricsCollector to store"
<6> 2022-08-02 08:03:11.456 +00:00 [INF] - Plan execution ended for deployment 37
<6> 2022-08-02 08:03:11.692 +00:00 [INF] - Updated reported properties
<6> 2022-08-02 08:03:16.949 +00:00 [INF] - Updated reported properties
```

**Comment by and-rewsmith** [comment]
@aleducq 

> Thanks for your help. I've applied this change and I don't see the Warning message but it doesn't restart the other modules from azure iiot (twin, publisher and discovery) and neither the iot edge collector metrics.

According to the deployment file posted, all that should be deployed is EdgeHub and EdgeAgent. So it seems to me like it is working as expected. If you need to deploy other modules you will have to make another deployment with those modules included in the deployment manifest.

**Comment by aleducq** [comment]
@and-rewsmith ,
What I have posted is the deployment manifest for EdgeHub and EdgeAgent but I have Layered deployment manifest for other modules. When I keep original TTL properties to 7200 seconds, other modules are deployed. Why when I just change this value (and adding the routes as you suggest) this is not the case ?
Maybe someone from @yophilav of the azure iiot team can help on this.

**Comment by and-rewsmith** [comment]
@aleducq

I read through the docs here:
https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring?view=iotedge-2020-11

Relevant description here.
> The system runtime modules, edgeAgent and edgeHub, are not configured as part of a layered deployment. Any IoT Edge device targeted by a layered deployment needs a standard automatic deployment applied to it first. The automatic deployment provides the base upon which layered deployments can be added.

An IoT Edge device can apply one and only one standard automatic deployment, but it can apply multiple layered automatic deployments. Any layered deployments targeting a device must have a higher priority than the automatic deployment for that device.

Based on this description, what you are trying to is set a "standard automatic deployment". You are saying when you change the "standard automatic deployment", the layered deployments you expect to see take effect don't, and your custom modules don't run on the device. Is that correct?

If so, do you think you could be running into this?
https://stackoverflow.com/questions/65320773/azure-edge-layered-deployment-not-reapplied-when-base-deployment-modified

**Comment by aleducq** [comment]
@and-rewsmith, 
In the docs you mentionned, there is something which I didn't know:
> Any layered deployments targeting a device must have a higher priority than the automatic deployment for that device.

As I made a lot of configuration for test, I change the priority to apply one or another but don't pay attention to that.
I've changed the priority to apply the TTL and be careful that it has a lower priority than layered deployments and it's ok now, all modules are running.

Thank you
