### ISSUE TITLE
Why is edgeHub AMQP required for the MetricsCollector using AzureMonitor UploadTarget?

### ISSUE THREAD

**Issue by sebboer** [Azure/iotedge#6642]
## Expected Behavior
I deployed the azure metrics collector with UploadTarget = AzureMonitor and the edgeHub with `amqpSettings__enabled = false` this should work since the AzureMonitor UploadTarget uses the REST API and the documentation for the metrics collector does no mention `amqpSettings__enabled = true`.

## Current Behavior
The edgeHub settings for disabling the AMQP connection crashes the metrics-collector. See logs.
This is not mentioned in the [documentation](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-monitor-with-workbooks?view=iotedge-1.4). 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. use edgeHub with `amqpSettings__enabled = false`
2. use metrics-collector with UploadTarget=AzureMonitor
4. deploy

### Device Information
* Host OS: yocto build
* Architecture: arm64
* Container OS: Linux containers 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.11
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1
* azure metrics collector: 1.0.9
* Docker/Moby [run `docker version`]: 19.03.15 

## Logs

```
[2022-09-01 11:34:15.274 INF] Initializing metrics collector
[2022-09-01 11:34:16.030 INF] Version - 1.0.9
[2022-09-01 11:34:16.058 DBG] Waiting on shutdown handler to trigger
[2022-09-01 11:34:16.690 INF] Metrics collector initialized with the following settings:
Settings:
LogAnalyticsWorkspaceId=XXX
Endpoints=[
  "http://edgeAgent:9600/metrics",
  "http://edgeHub:9600/metrics"
]
ScrapeFrequencySecs=300
UploadTarget=AzureMonitor
CompressForUpload=True
TransformForIoTCentral=False
ExperimentalFeatureAddIdentifyingTags=False
AllowedMetrics=
BlockedMetrics=
ResourceId=/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Devices/IotHubs/XXX
IotHubConnectFrequency=1.00:00:00
AzureDomain=azure.com
[2022-09-01 11:38:25.151 ERR] Error occurred during metrics collection setup.
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.BuildModuleClientWrapperAsync(ITransportSettings[] transportSettings) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper.cs:line 30
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Program.MainAsync() in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/Program.cs:line 54
[2022-09-01 11:38:25.434 INF] MetricsCollector Main() finished.
[2022-09-01 11:38:25.447 INF] Termination requested, initiating shutdown.
[2022-09-01 11:38:25.449 INF] Waiting for cleanup to finish
[2022-09-01 11:38:25.451 INF] Done with cleanup. Shutting down.
```

**Comment by jlian** [comment]
@ggjjj for on-call - thanks for taking a look.

**Comment by ggjjj** [comment]
Does it not crash when you set amqpSettings__enabled = true.?

**Comment by ggjjj** [comment]
We are aware of this issue and would work on a fix. Thanks for reporting it.

**Comment by ggjjj** [comment]
closing it for now and once a fix is available - the PR would tag this issue.
