### ISSUE TITLE
EdgeAgent 1.2.10 is unable to connect to workload.sock after device became full

### ISSUE THREAD

**Issue by FinitelyFailed** [Azure/iotedge#6677]
We run iot edge runtime 1.2.7 and system modules 1.2.6. We have a couple of devices that have become full, as our image creation didn't use cached layers from previous deployment until recently. And nothing on the device cleans up old unused images. Which is a new feature in 1.4.0 ... 

When a device have zero diskspace left it naturally doesn't work correctly. So we have manage to connect remotely via ssh to fix this issue, which we try to do by removing all docker images and layers and restart the iotedge system.

What happens now is that iotedge runtime pulls a default version of edgeAgent, 1.2, which seems to be 1.2.10 and the module doesn't start, so we try to run iotedge restart edgeAgent. Which runs edgeAgent which in turn craches as it doesn't manage to connect to a unix socket.

We have tried to reinstall the iotedge runtime but that doesn't help.

What can we do to make edgeAgent able to connect to the socket?
```

2022-09-12 13:07:35 +00:00 Starting Edge Agent
2022-09-12 13:07:35 +00:00 Changing ownership of management socket: /var/run/iotedge/mgmt.sock
2022-09-12 13:07:35.358 +00:00 Edge Agent Main()
<6> 2022-09-12 13:07:35.991 +00:00 [INF] - Initializing Edge Agent.
<6> 2022-09-12 13:07:36.440 +00:00 [INF] - Version - 1.2.10.55800403 (719bffd58b353dc0156010ad76ede96c611fb4ef)
<6> 2022-09-12 13:07:36.441 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

 

<6> 2022-09-12 13:07:36.567 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<3> 2022-09-12 13:07:36.774 +00:00 [ERR] - Shutting down because no response from unix:///var/run/iotedge/workload.sock for TrustBundleAsync
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused /var/run/iotedge/workload.sock
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs:line 30
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/generatedCode/HttpWorkloadClient.cs:line 700
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout, Action action) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 135
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 59
```

**Comment by gordonwang0** [comment]
Do you have logs from aziot-edged? Check to see if a request on the workload socket is shown in the logs.

Also, note that deleting the container through docker might still leave some files that still refer to the old container in edged's caches. When you reinstall the edge runtime, could you also try deleting everything in /var/lib/aziot/edged?

**Comment by FinitelyFailed** [comment]
Thanks, we will try to resolve the issue by cleaning up edge runtimes cache. And get you a log from aziot-edged.

We remove all docker images and layer by running:
`sudo iotedge system stop && sudo systemctl stop docker && sudo ls -lha /var/lib/docker/ && cd /var/lib/docker/ && sudo rm -rf builder buildkit containerd containers image network overlay2 plugins runtimes swarm tmp trust volumes && sudo systemctl start docker && sudo iotedge system restart`

Which has worked for us when a baselayer has become corrupt.

**Comment by jlian** [comment]
BTW any chance you could update to a newer version?

**Comment by FinitelyFailed** [comment]
We run debian buster (10) arm32 (RaspberryPi OS). Which makes it a bit of a headache to update, as version 1.3 and above of the runtime has a known issue on debian buster. And it's kind of hard to know how that issue will impact our solution, if we ignore that, apply the workaround, and update.

See https://github.com/Azure/iotedge/issues/6672

Side note:
We are also a bit stuck on ADU 0.7.0 (swupdate) at the moment, and our modified Raspberry Pi image does not support any kind of A-B image update. So we have to rely on apt or anything we can script. So at the moment we try to focus on moving to ADU 0.8.0.

**Comment by FinitelyFailed** [comment]
@gordonwang0 here is the log from aziot-edged daemon:

```
-- Logs begin at Fri 2022-09-16 16:08:56 CEST, end at Fri 2022-09-16 16:14:52 CEST. --
sep 16 16:11:37 edge-dev-pi systemd[1]: Started Azure IoT Edge daemon.
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Starting Azure IoT Edge Module Runtime
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Version - 1.2.7
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Initializing the module runtime...
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Initializing module runtime...
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Using runtime network id azure-iot-edge
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Successfully initialized module runtime
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Finished initializing the module runtime.
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Obtaining edge device provisioning data...
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Finished provisioning edge device.
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Stopping all modules...
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Finished stopping modules.
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Detecting if device information has changed...
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Starting management API...
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Starting watchdog with 60 second frequency...
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Listening on fd://aziot-edged.mgmt.socket with 1 thread for management API.
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Checking edge runtime status
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Creating and starting edge runtime module edgeAgent
sep 16 16:11:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:37Z [INFO] - Pulling image via tag mcr.microsoft.com/azureiotedge-agent:1.2...
sep 16 16:11:39 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:39Z [INFO] - [mgmt] - - - [2022-09-16 14:11:39.457861806 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" auth_id(-)
sep 16 16:11:40 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:11:40Z [INFO] - [mgmt] - - - [2022-09-16 14:11:40.827659725 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" auth_id(-)
sep 16 16:12:00 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:00Z [INFO] - Successfully pulled image mcr.microsoft.com/azureiotedge-agent:1.2
sep 16 16:12:00 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:00Z [INFO] - Creating module edgeAgent...
sep 16 16:12:00 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:00Z [INFO] - Creating image via tag mcr.microsoft.com/azureiotedge-agent:1.2...
sep 16 16:12:01 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:01Z [INFO] - Successfully created module edgeAgent
sep 16 16:12:01 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:01Z [INFO] - Starting module edgeAgent...
sep 16 16:12:01 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:01Z [INFO] - Starting new listener for module edgeAgent
sep 16 16:12:01 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:01Z [WARN] - Error in watchdog when checking for edge runtime status:
sep 16 16:12:01 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:01Z [WARN] - A module runtime error occurred.
sep 16 16:12:01 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:01Z [WARN] -         caused by: Could not get module edgeAgent
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [INFO] - Checking edge runtime status
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [INFO] - Edge runtime status is stopped, starting module now...
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [INFO] - Starting module edgeAgent...
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [INFO] - Starting new listener for module edgeAgent
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [INFO] - Listener  edgeAgent already started, removing old listener
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [WARN] - The workload service encountered an error
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [WARN] - Error in watchdog when checking for edge runtime status:
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [WARN] - A module runtime error occurred.
sep 16 16:12:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:12:37Z [WARN] -         caused by: Could not get module edgeAgent
sep 16 16:13:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:13:37Z [INFO] - Checking edge runtime status
sep 16 16:13:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:13:37Z [INFO] - Edge runtime status is stopped, starting module now...
sep 16 16:13:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:13:37Z [INFO] - Starting module edgeAgent...
sep 16 16:13:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:13:37Z [INFO] - Starting new listener for module edgeAgent
sep 16 16:13:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:13:37Z [WARN] - Error in watchdog when checking for edge runtime status:
sep 16 16:13:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:13:37Z [WARN] - A module runtime error occurred.
sep 16 16:13:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:13:37Z [WARN] -         caused by: Could not get module edgeAgent
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [INFO] - Checking edge runtime status
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [INFO] - Edge runtime status is stopped, starting module now...
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [INFO] - Starting module edgeAgent...
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [INFO] - Starting new listener for module edgeAgent
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [INFO] - Listener  edgeAgent already started, removing old listener
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [WARN] - The workload service encountered an error
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [WARN] - Error in watchdog when checking for edge runtime status:
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [WARN] - A module runtime error occurred.
sep 16 16:14:37 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:37Z [WARN] -         caused by: Could not get module edgeAgent
sep 16 16:14:52 edge-dev-pi aziot-edged[1347]: 2022-09-16T14:14:52Z [INFO] - [mgmt] - - - [2022-09-16 14:14:52.706452436 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 561 "-" "iotedge/0.1.0" auth_id(-)

```

The edgeAgent module is installed but is stopped and when checking logs, I can see that it has never ran:

```
pi@edge-dev-pi:~ $ iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeAgent        stopped          Stopped          mcr.microsoft.com/azureiotedge-agent:1.2
pi@edge-dev-pi:~ $ iotedge logs edgeAgent
pi@edge-dev-pi:~ $ 
```

If I try to restart it:

```
pi@edge-dev-pi:~ $ iotedge restart edgeAgent
edgeAgent
pi@edge-dev-pi:~ $ iotedge logs edgeAgent
2022-09-16 14:18:52 +00:00 Starting Edge Agent
2022-09-16 14:18:52 +00:00 Changing ownership of management socket: /var/run/iotedge/mgmt.sock
2022-09-16 14:18:52.280 +00:00 Edge Agent Main()
<6> 2022-09-16 14:18:52.929 +00:00 [INF] - Initializing Edge Agent.
<6> 2022-09-16 14:18:53.375 +00:00 [INF] - Version - 1.2.10.55800403 (719bffd58b353dc0156010ad76ede96c611fb4ef)
<6> 2022-09-16 14:18:53.376 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2022-09-16 14:18:53.497 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<3> 2022-09-16 14:18:53.703 +00:00 [ERR] - Shutting down because no response from unix:///var/run/iotedge/workload.sock for TrustBundleAsync
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused /var/run/iotedge/workload.sock
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs:line 30
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/generatedCode/HttpWorkloadClient.cs:line 700
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout, Action action) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 135
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 59
pi@edge-dev-pi:~ $ 

```

I have reinstalled edge runtime, cleared the cache and removed all docker images and layers before I tried to run everything again.

**Comment by gordonwang0** [comment]
From the edged log
> caused by: Could not get module edgeAgent

It seems that edged is not able to communicate with docker to start edgeAgent. Could you verify that the iotedge user has permissions to access the docker socket? i.e. check that the iotedge user is in the docker group and that the docker socket is group rw.

**Comment by FinitelyFailed** [comment]
@gordonwang0 
```
pi@edge-dev-pi:~ $ groups iotedge
iotedge : iotedge systemd-journal docker aziotks aziotcs aziotid
pi@edge-dev-pi:~ $ ls -lha /var/run/docker.sock 
srw-rw---- 1 root docker 0 sep 16 16:08 /var/run/docker.sock

```

I reinstalled both aziot-edge (and aziot-identity-service), moby-engine (and moby-cli), removed all docker layers and images and removed the aziot-edged cache.. Got the exact same behavior as before.

**Comment by gordonwang0** [comment]
And could you also ls /var/run/iotedge/workload.sock?

**Comment by FinitelyFailed** [comment]
@gordonwang0 
```
pi@edge-dev-pi:~ $ ls -all /var/run/iotedge/
totalt 0
drwxr-xr-x  2 root    root     80 sep 19 10:42 .
drwxr-xr-x 29 root    root    920 sep 20 07:54 ..
srw-rw----  1 iotedge iotedge   0 sep 19 10:42 mgmt.sock
srw-rw-rw-  1 iotedge iotedge   0 sep 19 10:42 workload.sock
```

**Comment by jlian** [comment]
@gordonwang0 any ideas?

**Comment by gordonwang0** [comment]
It's not immediately obvious to me what's going on here, as all the permissions and sockets appear correct.

Just to confirm, your Edge runtime is 1.2.7, but Hub/Agent are 1.2.10? Could you try setting your config.toml to pull edgeAgent 1.2.7 or update the Edge runtime to 1.2.10? Not sure if the version mismatch is the issue.

**Comment by FinitelyFailed** [comment]
The edge runtime is 1.2.7, in config.toml the version of edgeAgent is "1.2", which seems to pull 1.2.10 to bootstrap the deployment. The deployment in the iot hub is set to use edgeAgent/edgeHub 1.2.7. In the normal case this seems to work fine.

I'll try to upgrade the runtime to 1.2.10, on a device with this issue in our lab and see what happens.

At the moment we are trying to figure out if we can use iot edge runtime 1.4.1 on buster or not.

**Comment by jlian** [comment]
@FinitelyFailed how did the test go in the lab?

**Comment by raisalitch** [comment]
@FinitelyFailed Did you manage to do the test in the lab?

**Comment by FinitelyFailed** [comment]
Sorry, my plate has been a bit full with other stuff (ADU). I haven't been able to find the time to test. :/

**Comment by raisalitch** [comment]
@FinitelyFailed Have you had a chance to look at this?

**Comment by raisalitch** [comment]
@FinitelyFailed We're going to close this. Please reopen if you need further help thanks!
