### ISSUE TITLE
edgeHub got Error creating cloud connection

### ISSUE THREAD

**Issue by eddylawsurgere** [Azure/iotedge#6692]
## Expected Behavior
I followed the instructions [Create and provision an IoT Edge device on Linux using symmetric keys - Azure IoT Edge | Microsoft Learn](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11&tabs=azure-portal%2Cubuntu) to install IoT Edge into a client VM Ubuntu server 20.04. The edgeAgent worked fine. But the edgeHub couldn’t connect to the cloud. The client firewall only opened port 443 (blocked 5671 and 8883). The error message is:
_"Error creating cloud connection for client AssociatedMaterials_146_iotedge/$edgeHub
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---"_

### Device Information
* Host OS: Ubuntu 20.04 server
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.4.1
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2
* Docker/Moby [run `docker version`]: 20.10.18

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
<details>
<summary>edge-hub logs</summary>

```
[AssociatedMaterials_146_iotedge_$edgeHub_Logs (1).txt](https://github.com/Azure/iotedge/files/9680352/AssociatedMaterials_146_iotedge_.edgeHub_Logs.1.txt)
```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by veyalla** [comment]
Setting an Edge Hub environment variable named `UpstreamProtocol` to `AMQPWS` might help.

Reference: https://learn.microsoft.com/azure/iot-edge/production-checklist?view=iotedge-1.4#choose-upstream-protocol

**Comment by eddylawsurgere** [comment]
Thanks veyalla. It works after setting UPstreamProtocol to AMQPWS.
