### ISSUE TITLE
Edge Hub will not start after update

### ISSUE THREAD

**Issue by lucianoctorres** [Azure/iotedge#6736]
## Expected Behavior
After updating the iotedge runtime from 1.2 to 1.4, it should restart as it always did in previous updates

## Current Behavior
The iotedge log throws errors that it can't decrypt

caused by: could not decrypt: AZIOT_KEYS_RC_ERR_EXTERNAL

And edgeHub fails to start.

The error has been reported at https://github.com/Azure/iotedge/issues/6537 and https://github.com/Azure/iotedge/issues/6593,
but the suggested mitigation (deleting the local storage of edgeHub) is not a solution. We keep the local storage in a persistent partition, which remains after OS and IoT Runtime updates, so we keep log files, the message queue, and cold data in parquet files during updates

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Update from Iotedge Runtime 1.2 to 1.4
2. Edge Hub will not restart

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ tpmd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
38 check(s) succeeded.
1 check(s) raised warnings. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS: Ubuntu 18.04
* Architecture:  amd64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged : 1.4.2 
* Edge Agent: 1.4 
* Edge Hub: 1.4 
* Docker/Moby : 20.10.18+azure-2

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```
[iotedgeLogs..log](https://github.com/Azure/iotedge/files/9830232/iotedgeLogs.log)


```
</details>

<details>
<summary>edge-agent logs</summary>

```

2022-10-20 12:49:12  Starting Edge Agent
2022-10-20 12:49:12  Creating UID 13622 as edgeagentuser
2022-10-20 12:49:12  Changing ownership of storage folder: /iotedge/storage//edgeAgent to 13622
2022-10-20 12:49:12  Creating backup folder: /tmp/edgeAgent_backup
2022-10-20 12:49:12  Changing ownership of management socket: /var/run/iotedge/mgmt.sock
2022-10-20 12:49:12  Completed necessary setup. Starting Edge Agent.
2022-10-20 12:49:12.571 +00:00 Edge Agent Main()
<6> 2022-10-20 12:49:13.156 +00:00 [INF] - Initializing Edge Agent.
<6> 2022-10-20 12:49:13.701 +00:00 [INF] - Version - 1.4.2.61356014 (bb9a26162c4c88b3ef9a50d33632ab78bd4247d6)
<6> 2022-10-20 12:49:13.703 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2022-10-20 12:49:13.713 +00:00 [INF] - ModuleUpdateMode: NonBlocking
<6> 2022-10-20 12:49:13.878 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2022-10-20 12:49:14.336 +00:00 [INF] - Installing certificates [O=Zededa Inc.:01/18/2023 12:40:09],[CN=Bobst-IoT, OU=IT Infrastructure, O=Bobst Mex S.A., L=Mex, S=Vaud, C=CH:08/17/2036 08:40:51],[CN=BobstRootSHA2:03/06/2042 12:17:11],[CN=Bobst-IoT, OU=IT Infrastructure, O=Bobst Mex S.A., L=Mex, S=Vaud, C=CH:08/17/2036 08:40:51],[CN=BobstRootSHA2:03/06/2042 12:17:11] to Root
<6> 2022-10-20 12:49:14.959 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: metrics
<6> 2022-10-20 12:49:15.008 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2022-10-20 12:49:15.026 +00:00 [INF] - Started operation Get system resources
<6> 2022-10-20 12:49:15.032 +00:00 [INF] - Collecting metadata metrics
<6> 2022-10-20 12:49:15.273 +00:00 [INF] - Set metadata metrics: 1.4.2.61356014 (bb9a26162c4c88b3ef9a50d33632ab78bd4247d6), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"Linux","Architecture":"x86_64","Version":"1.4.2","Provisioning":{"Type":"ProvisioningType","DynamicReprovisioning":false,"AlwaysReprovisionOnStartup":false},"ServerVersion":"20.10.18+azure-2","KernelVersion":"#163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021","OperatingSystem":"ubuntu","NumCpus":3,"TotalMemory":2935835648,"Virtualized":"yes"}, True
<6> 2022-10-20 12:49:15.341 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2022-10-20 12:49:15.352 +00:00 [INF] - Started operation refresh twin config
<6> 2022-10-20 12:49:15.405 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<6> 2022-10-20 12:49:16.385 +00:00 [INF] - Created persistent store at /iotedge/storage/edgeAgent
<6> 2022-10-20 12:49:16.664 +00:00 [INF] - Started operation Metrics Scrape
<6> 2022-10-20 12:49:16.665 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2022-10-20 12:49:17.488 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2022-10-20 12:49:17.489 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2022-10-20 12:49:17.489 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2022-10-20 12:49:17.490 +00:00 [INF] - Registering request handler RestartModule
<6> 2022-10-20 12:49:18.180 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_WebSocket_Only.
<6> 2022-10-20 12:49:18.493 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2022-10-20 12:49:18.646 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 72 and reported properties version 2392.
<6> 2022-10-20 12:49:31.225 +00:00 [INF] - Plan execution started for deployment 72
<6> 2022-10-20 12:49:31.236 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.249 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.249 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.249 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.249 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.250 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.251 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.251 +00:00 [INF] - Executing command: "[Null]"
<6> 2022-10-20 12:49:31.310 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module edgeHub]\n  [Create module edgeHub]\n)]\n  [Start module edgeHub]\n)"
<6> 2022-10-20 12:49:31.318 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module edgeHub]\n  [Create module edgeHub]\n)"
<6> 2022-10-20 12:49:38.135 +00:00 [INF] - Executing command: "Start module edgeHub"
<6> 2022-10-20 12:49:39.390 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module edgeMonitoringSystem]\n  [Create module edgeMonitoringSystem]\n)]\n  [Start module edgeMonitoringSystem]\n)"
<6> 2022-10-20 12:49:39.390 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module edgeMonitoringSystem]\n  [Create module edgeMonitoringSystem]\n)"
<6> 2022-10-20 12:49:51.789 +00:00 [INF] - Executing command: "Start module edgeMonitoringSystem"
<6> 2022-10-20 12:49:52.935 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module edgeMonitoring]\n  [Create module edgeMonitoring]\n)]\n  [Start module edgeMonitoring]\n)"
<6> 2022-10-20 12:49:52.935 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module edgeMonitoring]\n  [Create module edgeMonitoring]\n)"
<6> 2022-10-20 12:49:53.948 +00:00 [INF] - Executing command: "Start module edgeMonitoring"
<6> 2022-10-20 12:49:55.149 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module opcuaSimulator]\n  [Create module opcuaSimulator]\n)]\n)"
<6> 2022-10-20 12:49:55.149 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module opcuaSimulator]\n  [Create module opcuaSimulator]\n)"
<6> 2022-10-20 12:50:13.977 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module cubeSimulator]\n  [Create module cubeSimulator]\n)]\n  [Start module cubeSimulator]\n)"
<6> 2022-10-20 12:50:13.977 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module cubeSimulator]\n  [Create module cubeSimulator]\n)"
<6> 2022-10-20 12:50:26.264 +00:00 [INF] - Executing command: "Start module cubeSimulator"
<6> 2022-10-20 12:50:27.398 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module notificationSimulator]\n  [Create module notificationSimulator]\n)]\n  [Start module notificationSimulator]\n)"
<6> 2022-10-20 12:50:27.398 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module notificationSimulator]\n  [Create module notificationSimulator]\n)"
<6> 2022-10-20 12:50:30.701 +00:00 [INF] - Executing command: "Start module notificationSimulator"
<6> 2022-10-20 12:50:32.119 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module fileTransferSimulator]\n  [Create module fileTransferSimulator]\n)]\n  [Start module fileTransferSimulator]\n)"
<6> 2022-10-20 12:50:32.119 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module fileTransferSimulator]\n  [Create module fileTransferSimulator]\n)"
<6> 2022-10-20 12:50:36.091 +00:00 [INF] - Executing command: "Start module fileTransferSimulator"
<6> 2022-10-20 12:50:37.339 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module machineEventSimulator]\n  [Create module machineEventSimulator]\n)]\n  [Start module machineEventSimulator]\n)"
<6> 2022-10-20 12:50:37.339 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module machineEventSimulator]\n  [Create module machineEventSimulator]\n)"
<6> 2022-10-20 12:50:40.924 +00:00 [INF] - Executing command: "Start module machineEventSimulator"
<6> 2022-10-20 12:50:42.061 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module edgeBlob]\n  [Create module edgeBlob]\n)]\n  [Start module edgeBlob]\n)"
<6> 2022-10-20 12:50:42.061 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module edgeBlob]\n  [Create module edgeBlob]\n)"
<6> 2022-10-20 12:50:54.149 +00:00 [INF] - Executing command: "Start module edgeBlob"
<6> 2022-10-20 12:50:55.297 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module edgeStorage]\n  [Create module edgeStorage]\n)]\n  [Start module edgeStorage]\n)"
<6> 2022-10-20 12:50:55.298 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module edgeStorage]\n  [Create module edgeStorage]\n)"
<6> 2022-10-20 12:50:58.969 +00:00 [INF] - Executing command: "Start module edgeStorage"
<6> 2022-10-20 12:51:00.172 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module machineEventPublisher]\n  [Create module machineEventPublisher]\n)]\n  [Start module machineEventPublisher]\n)"
<6> 2022-10-20 12:51:00.173 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module machineEventPublisher]\n  [Create module machineEventPublisher]\n)"
<6> 2022-10-20 12:51:03.884 +00:00 [INF] - Executing command: "Start module machineEventPublisher"
<6> 2022-10-20 12:51:05.208 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module edgePublisher]\n  [Create module edgePublisher]\n)]\n  [Start module edgePublisher]\n)"
<6> 2022-10-20 12:51:05.208 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module edgePublisher]\n  [Create module edgePublisher]\n)"
<6> 2022-10-20 12:51:08.881 +00:00 [INF] - Executing command: "Start module edgePublisher"
<6> 2022-10-20 12:51:10.148 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module fileTransferBlob]\n  [Create module fileTransferBlob]\n)]\n  [Start module fileTransferBlob]\n)"
<6> 2022-10-20 12:51:10.149 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module fileTransferBlob]\n  [Create module fileTransferBlob]\n)"
<6> 2022-10-20 12:51:11.263 +00:00 [INF] - Executing command: "Start module fileTransferBlob"
<6> 2022-10-20 12:51:12.650 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module fileTransfer]\n  [Create module fileTransfer]\n)]\n  [Start module fileTransfer]\n)"
<6> 2022-10-20 12:51:12.651 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module fileTransfer]\n  [Create module fileTransfer]\n)"
<6> 2022-10-20 12:51:16.362 +00:00 [INF] - Executing command: "Start module fileTransfer"
<6> 2022-10-20 12:51:17.756 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module notificationPublisher]\n  [Create module notificationPublisher]\n)]\n  [Start module notificationPublisher]\n)"
<6> 2022-10-20 12:51:17.756 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module notificationPublisher]\n  [Create module notificationPublisher]\n)"
<6> 2022-10-20 12:51:21.345 +00:00 [INF] - Executing command: "Start module notificationPublisher"
<6> 2022-10-20 12:51:22.661 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module recordPublisher]\n  [Create module recordPublisher]\n)]\n  [Start module recordPublisher]\n)"
<6> 2022-10-20 12:51:22.661 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module recordPublisher]\n  [Create module recordPublisher]\n)"
<6> 2022-10-20 12:51:26.011 +00:00 [INF] - Executing command: "Start module recordPublisher"
<6> 2022-10-20 12:51:27.317 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module cubePublisher]\n  [Create module cubePublisher]\n)]\n  [Start module cubePublisher]\n)"
<6> 2022-10-20 12:51:27.317 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module cubePublisher]\n  [Create module cubePublisher]\n)"
<6> 2022-10-20 12:51:30.651 +00:00 [INF] - Executing command: "Start module cubePublisher"
<6> 2022-10-20 12:51:31.899 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module opcuaAdapter]\n  [Create module opcuaAdapter]\n)]\n  [Start module opcuaAdapter]\n)"
<6> 2022-10-20 12:51:31.900 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module opcuaAdapter]\n  [Create module opcuaAdapter]\n)"
<6> 2022-10-20 12:51:35.412 +00:00 [INF] - Executing command: "Start module opcuaAdapter"
<6> 2022-10-20 12:51:36.766 +00:00 [INF] - Executing command: "Command Group: (\n  [Command Group: (\n  [Prepare module opcuaPublisher]\n  [Create module opcuaPublisher]\n)]\n  [Start module opcuaPublisher]\n)"
<6> 2022-10-20 12:51:36.766 +00:00 [INF] - Executing command: "Command Group: (\n  [Prepare module opcuaPublisher]\n  [Create module opcuaPublisher]\n)"
<6> 2022-10-20 12:51:48.547 +00:00 [INF] - Executing command: "Start module opcuaPublisher"
<6> 2022-10-20 12:51:49.610 +00:00 [INF] - Plan execution ended for deployment 72
<6> 2022-10-20 12:51:50.166 +00:00 [INF] - Updated reported properties
<6> 2022-10-20 12:51:55.583 +00:00 [INF] - Updated reported properties


```
</details>

<details>
<summary>edge-hub logs</summary>

```

2022-10-20 12:49:39  Starting Edge Hub
2022-10-20 12:49:39  Starting Edge Hub
2022-10-20 12:49:39  Creating UID 13623 as edgehubuser
2022-10-20 12:49:39  Changing ownership of storage folder: /iotedge/storage//edgeHub to 13623
2022-10-20 12:49:39  Creating backup folder: /tmp/edgeHub_backup
2022-10-20 12:49:39.539 +00:00 Edge Hub Main()
<6> 2022-10-20 12:49:41.561 +00:00 [INF] - Installing certificates [O=Zededa Inc.:01/18/2023 12:40:09],[CN=Bobst-IoT, OU=IT Infrastructure, O=Bobst Mex S.A., L=Mex, S=Vaud, C=CH:08/17/2036 08:40:51],[CN=BobstRootSHA2:03/06/2042 12:17:11] to Root
<6> 2022-10-20 12:49:41.773 +00:00 [INF] - Installing certificates [O=Zededa Inc.:01/18/2023 12:40:09],[CN=Bobst-IoT, OU=IT Infrastructure, O=Bobst Mex S.A., L=Mex, S=Vaud, C=CH:08/17/2036 08:40:51],[CN=BobstRootSHA2:03/06/2042 12:17:11],[CN=Bobst-IoT, OU=IT Infrastructure, O=Bobst Mex S.A., L=Mex, S=Vaud, C=CH:08/17/2036 08:40:51],[CN=BobstRootSHA2:03/06/2042 12:17:11] to Root
<6> 2022-10-20 12:49:41.908 +00:00 [INF] - Enabling SSL protocols: Tls12
<6> 2022-10-20 12:49:42.384 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
<6> 2022-10-20 12:49:44.022 +00:00 [INF] - Created persistent store at /iotedge/storage/edgeHub
<6> 2022-10-20 12:49:44.243 +00:00 [INF] - Initializing Edge Hub
<6> 2022-10-20 12:49:44.245 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2022-10-20 12:49:44.249 +00:00 [INF] - Version - 1.4.2.61356014 (bb9a26162c4c88b3ef9a50d33632ab78bd4247d6)
<6> 2022-10-20 12:49:44.250 +00:00 [INF] - OptimizeForPerformance=True
<6> 2022-10-20 12:49:44.251 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2022-10-20 12:49:44.253 +00:00 [INF] - Loaded server certificate with expiration date of "2022-11-19T12:49:40.0000000+00:00"
<6> 2022-10-20 12:49:44.285 +00:00 [INF] - Using Asp Net server for metrics
<6> 2022-10-20 12:49:44.479 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2022-10-20 12:49:44.480 +00:00 [INF] - Created new message store
<6> 2022-10-20 12:49:44.723 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<3> 2022-10-20 12:51:44.313 +00:00 [ERR] - Stopping with exception
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.<>c.<.cctor>b__27_0() in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 114
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter(Task task, TimeSpan timeout, Action action) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 149
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.ServiceIdentityStore.ReadCacheFromStore(IKeyValueStore`2 encryptedStore, String actorDeviceId) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 500
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.Create(IServiceIdentityHierarchy serviceIdentityHierarchy, IServiceProxy serviceProxy, IKeyValueStore`2 encryptedStorage, TimeSpan refreshRate, TimeSpan refreshDelay, TimeSpan initializationRefreshDelay) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 93
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__28_15(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 336
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__36_10(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 245
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__36_12(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 284
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__36_25(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 468
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule.<Load>b__36_28(IComponentContext c) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs:line 527
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 80


```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by vadim-kovalyov** [comment]
Hey @lucianoctorres, thanks for your patience and sorry you're having this issue. 

> After updating the iotedge runtime from 1.2 to 1.4, it should restart as it always did in previous updates

Can you please be more specific on how did you install the new version? If you just did, `apt upgrade aziot-edge`, and updated deployment manifest to use `edgeHub:1.4` that should have worked. 

If, by any chance, you re-installed edge completely or installed on a clean box, the previous keys will be lost and decrypt will not work.  Also, If edgeHub module was "removed" at any point in time, then the older keys are rotated, and then decrypt won't work as well.

**Comment by lucianoctorres** [comment]
Hi
we push a new image to the remote devices, containing the base OS, Iotedge runtime, moby etc. We keep the storage for edgeHub and edgeAgent in a persistent partition. For our setup, we need to update using full images, package update is not an option.
The persistent partition is supposed to keep the message queue, so we don't lose data if there's anything still on it when we push the updates. For some reason this was never a problem, we've been doing it like this for the past 2 years ... I only started having this issue now moving from 1.2 to 1.4.
If we need to delete the local storage, what is the point of storing data outside of the container?

**Comment by vadim-kovalyov** [comment]
Hey @lucianoctorres, I see what you mean. If you do a full image update you need to make sure that you preserve the content of `/var/lib/aziot/` - that's where we keep provisioning state and all the certs/keys, also used for decrypting the store. The normal package upgrade would do that for you. Otherwise, the keys would be lost and re-generated, and you will not be able to recover the store.

I wounder how it used to work for you before, you must have preserved the encryption keys somehow. If you do have a backup image of 1.2, you can get the old keys from there.

I guess we could do a better job documenting such case, I'll pass this feedback to our docs team. Meanwhile, the only way to recover the stored messages is to recover the keys from 1.2 version.

**Comment by lucianoctorres** [comment]
Hi @vadim-kovalyov , thanks for the info. I'll see if I can mount /var/lib/aziot in the persistent partition. Is there any configuration where I can tell the runtime to use another path for the keys?

**Comment by vadim-kovalyov** [comment]
> Hi @vadim-kovalyov , thanks for the info. I'll see if I can mount /var/lib/aziot in the persistent partition. Is there any configuration where I can tell the runtime to use another path for the keys?

The path ` /var/lib/aziot` cannot be changed via config.

**Comment by vadim-kovalyov** [comment]
I'm closing this for now. Please let me know if you have further questions.
