### ISSUE TITLE
start module doesn't work, restart module works

### ISSUE THREAD

**Issue by Giusmon94** [Azure/iotedge#6856]
I have developed a module and built the image in arm32v7 architecture to run on a Raspberry Pi 4b. The module is not working when the edgeAgent is starting the module, running the command "start module". 
However forcing manually the restart through the IoT Hub the module runs correctly "restart module".

## Expected Behavior
Modules should start as it is working properly when restarted

## Current Behavior
The modules is in backoff state

### Device Information
* Host OS: Raspberry OS
* Architecture: Arm32v7
* Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2
* Docker/Moby [run `docker version`]: 4.12

## Logs

<details>
<summary>edge-agent logs</summary>

```

2023-01-13 11:00:18.169 +00:00 [ERR] - Executing command for operation ["start"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module camera-capture: runtime operation error: start module "camera-capture", StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2021_12_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2021_12_07/ModuleManagementHttpClient.cs:line 232
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 152
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2021_12_07.ModuleManagementHttpClient.StartModuleAsync(String name) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2021_12_07/ModuleManagementHttpClient.cs:line 178
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.<>c__DisplayClass26_0.<<Throttle>b__0>d.MoveNext() in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Throttle[T](Func`1 identityOperation) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 153
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
<3> 2023-01-13 11:00:18.271 +00:00 [ERR] - Executing command for operation ["Command Group: (\n  [Stop module camera-capture]\n  [Start module camera-capture]\n  [Saving camera-capture to store]\n)"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module camera-capture: runtime operation error: start module "camera-capture", StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2021_12_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2021_12_07/ModuleManagementHttpClient.cs:line 232
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 152
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2021_12_07.ModuleManagementHttpClient.StartModuleAsync(String name) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2021_12_07/ModuleManagementHttpClient.cs:line 178
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.<>c__DisplayClass26_0.<<Throttle>b__0>d.MoveNext() in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Throttle[T](Func`1 identityOperation) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 153
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
<3> 2023-01-13 11:00:18.279 +00:00 [ERR] - Step failed in deployment 186, continuing execution. Failure when running command Command Group: (
  [Stop module camera-capture]
  [Start module camera-capture]
  [Saving camera-capture to store]


2023-01-17 11:47:19.280 +00:00 [INF] - Received direct method call - RestartModule
<6> 2023-01-17 11:47:19.280 +00:00 [INF] - Received request RestartModule with payload
<6> 2023-01-17 11:47:19.280 +00:00 [INF] - Processing request to restart camera-capture
<6> 2023-01-17 11:47:19.344 +00:00 [INF] - Restarting camera-capture...
<6> 2023-01-17 11:47:19.345 +00:00 [INF] - Executing command: "Restart module camera-capture"
<6> 2023-01-17 11:47:30.953 +00:00 [INF] - Restarted camera-capture
<6> 2023-01-17 11:47:30.954 +00:00 [INF] - Successfully handled request RestartModule
<6> 2023-01-17 11:47:31.400 +00:00 [INF] - Updated reported properties

```
</details>

<details>
<summary>module logs</summary>

```

No logs, the module is not running at all.

```
</details>

**Comment by lfitchett** [comment]
@Giusmon94 Does this consistently happen? Did the module fail to start one time, or is this reproducible?

**Comment by Giusmon94** [comment]
@lfitchett each time the raspberry is restarted the module gives the error. Only a manual restart of the module in the azure portal solves the issue.

**Comment by lfitchett** [comment]
Ok, can you please try updating to our LTS 1.4.x and see if the issue persists? We no longer support 1.2.x: https://learn.microsoft.com/en-us/lifecycle/products/azure-iot-edge

**Comment by varunpuranik** [comment]
@Giusmon94 - 
Can you please provide iotedge system logs (in debug mode, and sanitized for sensitive information) as described here - https://learn.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-1.4#check-the-status-of-the-iot-edge-security-manager-and-its-logs. 
That might tell us why EdgeAgent is not able to start your module.

**Comment by arsing** [comment]
>Failed to start module camera-capture, error Failed to listen on workload socket: Is a directory (os error 21)

This means that at some point that module was started by something else than Edge Agent or Edge Daemon while Edge Daemon was not running.

For 1.4+, the relevant path is `/var/lib/iotedge/mnt/${module_id}.sock`. You should see that path is actually a directory instead of a socket file.

Anyway, to resolve this: stop the Edge Daemon (`systemctl stop aziot-edge`), make sure it's not running, make sure none of the module containers are running (`docker ps -a`), delete everything under `/var/lib/iotedge/mnt/`, restart the Edge Daemon.

**Comment by david-emakenemi** [comment]
Hi, @Giusmon94 checking in to see if the instruction provided by @arsing worked for you. Let us know

**Comment by Giusmon94** [comment]
Hi arsing,
I have checked and the ${module_id}.sock was a directory instead of a socket file. I have removed that file but it was still not working.
I removed all the docker files, updated the iot edge and reprovisioned the device everything worked fine in the end.

Thank you for your help.
