### ISSUE TITLE
EdgeHub tries to connect over Amqp although it is configured to use Mqtt

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#7046]
I'm actually using EFLOW, but I think the problem exists in IoT Edge itself.

I have an IoT Edge solution that previously connected to Azure IoT Hub via the Amqp protocol.

Today, I have changed the upstream protocol to be Mqtt.  In order to do this, I have:

- modified all my custom Edge Modules to use the Mqtt protocol in the ModuleClient
- changed the deployment manifest in where I specify the upstream-protocol of the system - modules (edgeHub & edgeAgent) must be MQTT.  I've also disabled the other communication protocls:
```json
"systemModules": {
          "edgeAgent": {
            "type": "docker",
            "env": {
              "storageFolder": {
                "value": "/var/lib/edgeAgent/storage"
              },
              "UpstreamProtocol": {
                "value": "MQTT"
              }
            },
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.4.8",
              "createOptions": "{\"HostConfig\":{\"Binds\":[\"/var/lib/vesselgateway/systemmodules/storage:/var/lib/edgeAgent/storage\"],\"LogConfig\":{\"Type\":\"local\",\"Config\":{\"max-size\":\"#{ModuleLoggingConfig.MaxLogFileSize}#\",\"max-file\":\"#{ModuleLoggingConfig.MaxLogFiles}#\"}}}}"
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "env": {
              "storageFolder": {
                "value": "/var/lib/edgeHub/storage"
              },
              "UpstreamProtocol": {
                "value": "MQTT"
              },
              "MaxUpstreamBatchSize": {
                "value": 15
              },
              "AmqpSettings__Enabled": {
                "value": false
              },
              "MqttSettings__Enabled": {
                "value": true
              },
              "HttpSettings__Enabled": {
                "value": false
              }
            }
```

When the solution is deployed however, the ModuleClient in my custom modules fail to open a connection:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (MQTT channel open failed.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel open failed.s
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.RunWithRetryAsync[T](Func`1 taskFunc, ShouldRetry shouldRetry, Func`2 isTransient, Action`3 onRetrying, Boolean fa
stFirstRetry, CancellationToken cancellationToken)i
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.RunWithRetryAsync(Func`1 taskFunc, ShouldRetry shouldRetry, Func`2 isTransient, Action`3 onRetrying, Boolean fastF
irstRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.OpenInternalAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   --- End of inner exception stack trace ---
```

In the logs of the edgeHub module, I can also see that AMQP is still being used :

```
<6> 2023-06-14 15:09:40.396 +00:00 [INF] - Attempting to connect to IoT Hub for client 9330874-elar/$edgeHub via AMQP...
<4> 2023-06-14 15:10:00.521 +00:00 [WRN] - Error creating cloud connection for client 9330874-elar/$edgeHub
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.ConnectAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
```

```
<6> 2023-06-14 15:52:58.306 +00:00 [INF] - New device connection for device xxxxx-yyy/$edgeHub
<6> 2023-06-14 15:52:58.314 +00:00 [INF] - Client 9330874-elar/$edgeHub connected to edgeHub, processing existing subscriptions.
<6> 2023-06-14 15:52:58.341 +00:00 [INF] - Attempting to connect to IoT Hub for client xxxxx-yyy/$edgeHub via AMQP...
```

and
```
<6> 2023-06-14 15:52:59.485 +00:00 [INF] - Updated message store TTL to 2592000 seconds
<6> 2023-06-14 15:52:59.489 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2023-06-14 15:52:59.510 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2023-06-14 15:52:59.513 +00:00 [INF] - Initialized edge hub configuration
<6> 2023-06-14 15:52:59.514 +00:00 [INF] - Starting protocol heads - (AMQP)I
<6> 2023-06-14 15:53:06.536 +00:00 [INF] - Not changed node: xxxxx-yyy/$edgeAgent
<6> 2023-06-14 15:53:06.536 +00:00 [INF] - Updated node: xxxxx-yyy/$edgeHub
```

When looking at the logs of `edgeAgent` however, I can see it's trying to connect via MQTT:

```
<6> 2023-06-14 18:21:48.365 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2023-06-14 18:21:48.367 +00:00 [INF] - Started operation refresh twin config
<6> 2023-06-14 18:21:48.385 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Mqtt_Tcp_Only...
<6> 2023-06-14 18:21:48.731 +00:00 [INF] - Created persistent store at /var/lib/edgeAgent/storage/edgeAgent
<6> 2023-06-14 18:21:48.881 +00:00 [INF] - Started operation Metrics Scrape
<6> 2023-06-14 18:21:48.881 +00:00 [INF] - Started operation Metrics Upload
```

We are using edgeHub 1.4.8 and edgeAgent 1.4.8 with Edge Daemon 1.4.9

I have another device where the same solution is deployed (which was previously also using AMQP, where it works without issues.
On that device, we're running IoT Edge Daemon 1.4.2

**Comment by ancaantochi** [comment]
@fgheysels,
After you made the change to add UpstreamProtocol, did the module restart? It should happen automatically when you applied the change to deployment. 
Please check that the env variable UpstreamProtocol is there for edgeHub and set to Mqtt:

`docker inspect edgeHub `

**Comment by varunpuranik** [comment]
@fgheysels - were you able to try the suggestions from Anca above? 
Any updates?
Also, will you be able to provide the EdgeHub debug from when it restarts? That might tell us if the right protocol heads are starting up. 
Please make sure to sanitize your logs for sensitive information, before sharing them.

**Comment by fgheysels** [comment]
I have reverted the situation on the machine where we had the problem to a previous version as it was a production environment.
I can re-visit this later.

In the meantime, I have the same deployment running (without this issue) on another machine.  if I inspect the environment of the edgeHub module, I can see that the `UpstreamProtocol` is defined:

![image](https://github.com/Azure/iotedge/assets/3605786/968ab863-8979-4bca-930e-915321150cdb)

**Comment by varunpuranik** [comment]
@fgheysels - You should see the same set of environment variables, and behavior on all devices. 
Can you please provide info for a device where you have a repro? If not, can we close the bug for now? If you see this behavior again, you can open a new issue.

**Comment by ancaantochi** [comment]
closing because no response, please reopen if you still have this issue.
