### ISSUE TITLE
IotEdgeMetricsCollector Stops Working

### ISSUE THREAD

**Issue by PedroBuhigas** [Azure/iotedge#7092]
I am having a chronic problem with IotEdgeMetricsCollector. It will work for several months, and all of the sudden it will stop working with the following log entries bellow. Removing the docker container and forcing IotEdge to recreate solves the problem.

[2023-08-18 07:47:18.810 INF] Started operation Reconnect to IoT Hub
[2023-08-18 07:47:18.828 INF] Started operation Scrape and Upload Metrics
[2023-08-18 07:48:18.833 INF] Starting periodic operation Scrape and Upload Metrics...
[2023-08-18 07:48:18.833 INF] Starting periodic operation Reconnect to IoT Hub...
[2023-08-18 07:48:18.862 INF] Scraping endpoint http://edgeHub:9600/metrics
[2023-08-18 07:48:18.864 INF] Trying to initialize module client using transport type [Amqp_Tcp_Only]
[2023-08-18 07:48:18.995 INF] Scraping endpoint  http://edgeAgent:9600/metrics
[2023-08-18 07:48:18.997 INF] Scraping endpoint  http://IotEdgeEcoView:9600/metrics
[2023-08-18 07:48:19.332 INF] Scraping finished, received 37 metrics from endpoint  http://IotEdgeEcoView:9600/metrics
[2023-08-18 07:48:19.351 INF] Scraping finished, received 60 metrics from endpoint http://edgeHub:9600/metrics
[2023-08-18 07:48:19.357 INF] Scraping finished, received 141 metrics from endpoint  http://edgeAgent:9600/metrics
[2023-08-18 07:48:22.700 INF] Successfully created self-signed certificate  for agentGuid : {3f26d4e0-64b6-46c3-8bea-e0540a3b3aa0} and workspace: 61ca6587-9689-4c80-acc4-58f22c2676c9
[2023-08-18 07:48:22.710 INF] OMS endpoint Url : https://61ca6587-9689-4c80-acc4-58f22c2676c9.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
[2023-08-18 07:48:22.714 INF] sending registration request
[2023-08-18 07:48:22.720 INF] waiting for response to registration request
[2023-08-18 07:48:27.808 INF] OMS endpoint Url : https://61ca6587-9689-4c80-acc4-58f22c2676c9.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
[2023-08-18 07:48:27.810 INF] sending registration request
[2023-08-18 07:48:27.810 INF] waiting for response to registration request
[2023-08-18 07:48:32.828 INF] OMS endpoint Url : https://61ca6587-9689-4c80-acc4-58f22c2676c9.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
[2023-08-18 07:48:32.828 INF] sending registration request
[2023-08-18 07:48:32.828 INF] waiting for response to registration request
[2023-08-18 07:48:37.856 INF] OMS endpoint Url : https://61ca6587-9689-4c80-acc4-58f22c2676c9.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
[2023-08-18 07:48:37.856 INF] sending registration request
[2023-08-18 07:48:37.856 INF] waiting for response to registration request
[2023-08-18 07:48:42.875 WRN] exception occurred : One or more errors occurred. (Resource temporarily unavailable (61ca6587-9689-4c80-acc4-58f22c2676c9.oms.opinsights.azure.com:443))
[2023-08-18 07:48:42.878 ERR] Registering agent with OMS failed (are the Log Analytics Workspace ID and Key correct?) : One or more errors occurred. (Resource temporarily unavailable (61ca6587-9689-4c80-acc4-58f22c2676c9.oms.opinsights.azure.com:443))
[2023-08-18 07:48:42.908 FTL] System.AggregateException: One or more errors occurred. (Resource temporarily unavailable (61ca6587-9689-4c80-acc4-58f22c2676c9.oms.opinsights.azure.com:443))
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable (61ca6587-9689-4c80-acc4-58f22c2676c9.oms.opinsights.azure.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Certificategenerator.CertGenerator.RegisterWithOms(X509Certificate2 cert, String AgentGuid, String logAnalyticsWorkspaceId, String logAnalyticsWorkspaceKey, String logAnalyticsWorkspaceDomainPrefixOms) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/CertificateGenerator/CertGenerator.cs:line 188
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Certificategenerator.CertGenerator.RegisterWithOmsWithBasicRetryAsync(X509Certificate2 cert, String AgentGuid, String logAnalyticsWorkspaceId, String logAnalyticsWorkspaceKey, String logAnalyticsWorkspaceDomainPrefixOms) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/CertificateGenerator/CertGenerator.cs:line 208
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Certificategenerator.CertGenerator.RegisterAgentWithOMS(String logAnalyticsWorkspaceId, String logAnalyticsWorkspaceKey, String logAnalyticsWorkspaceDomainPrefixOms) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/CertificateGenerator/CertGenerator.cs:line 267
[2023-08-18 07:48:42.911 INF] Termination requested, initiating shutdown.
[2023-08-18 07:48:42.912 INF] Waiting for cleanup to finish
[2023-08-18 07:48:42.914 INF] Done with cleanup. Shutting down.
[2023-08-18 07:48:42.915 INF] MetricsCollector Main() finished.

**Comment by jlian** [comment]
@huguesBouvier would you mind also taking a look at this one

**Comment by huguesBouvier** [comment]
Does the contain "stops"?
I see: [2023-08-18 07:48:42.915 INF] MetricsCollector Main() finished..

Changing the restart policy of the pod should mitigate the issue. So if it stops it gets restarted automatically:
The restart policies are:
- Default: not to restart 
**- `always` Always restart 
- `unless-stopped` Restart always except when the user has manually stopped the container** 
- `on-failure` Restart only when the container exit code is non-zero

**Comment by PedroBuhigas** [comment]
Restart policy is set to Always already

**Comment by TheVexy** [comment]
Hi, we're also experimenting the same issue, restart policy is set to always yet the modules remain in an error state until it's restarted mannualy 

`>>> Start logging the last 100 lines from the exited container: MetricsModule <<<
>>> wo 20 mrt 2024 11:07:56 UTC <<<

   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/MetricsScraper.cs:line 72
[2023-12-04 12:13:36.936 ERR] Error scraping endpoint  http://ExportCloud:9600/metrics - System.Net.Http.HttpRequestException: Connection refused (exportcloud:9600)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/MetricsScraper.cs:line 72
[2023-12-04 12:13:36.940 INF] Scraping finished, received 0 metrics from endpoint  http://TelemetryCalculator:9600/metrics
[2023-12-04 12:13:36.940 INF] Scraping finished, received 0 metrics from endpoint  http://AzureBlobStorage:9600/metrics
[2023-12-04 12:13:36.940 INF] Scraping finished, received 0 metrics from endpoint  http://ExportDB:9600/metrics
[2023-12-04 12:13:36.940 INF] Scraping finished, received 0 metrics from endpoint  http://InfluxDB:9600/metrics
[2023-12-04 12:13:36.940 INF] Scraping finished, received 0 metrics from endpoint  http://ExportCloud:9600/metrics
[2023-12-04 12:13:36.940 INF] Scraping finished, received 0 metrics from endpoint  http://HealthMonitor:9600/metrics
[2023-12-04 12:13:36.964 INF] Scraping finished, received 19 metrics from endpoint  http://DredgeViewParser:9600/metrics
[2023-12-04 12:13:36.964 INF] Scraping finished, received 25 metrics from endpoint  http://FuelMonitoringCalculations:9600/metrics
[2023-12-04 12:13:36.964 INF] Scraping finished, received 84 metrics from endpoint  http://DataServiceToDVCovaro:9600/metrics
[2023-12-04 12:13:36.964 INF] Scraping finished, received 84 metrics from endpoint  http://DataServiceToDVSurveyData:9600/metrics
[2023-12-04 12:13:36.965 INF] Scraping finished, received 86 metrics from endpoint  http://DataServiceFromDVDTM:9600/metrics
[2023-12-04 12:13:36.966 INF] Scraping finished, received 84 metrics from endpoint  http://DataServiceFromDVLogBase1:9600/metrics
[2023-12-04 12:13:36.966 INF] Scraping finished, received 85 metrics from endpoint  http://IotEdgeCloudFileTransfer:9600/metrics
[2023-12-04 12:13:36.970 INF] Scraping finished, received 163 metrics from endpoint  http://edgeHub:9600/metrics
[2023-12-04 12:13:36.971 INF] Scraping finished, received 315 metrics from endpoint http://edgeAgent:9600/metrics
[2023-12-04 12:13:40.353 INF] Successfully initialized module client using transport type [Amqp_Tcp_Only]
[2023-12-04 12:13:40.354 INF] Successfully completed periodic operation Reconnect to IoT Hub
[2023-12-04 12:13:41.905 ERR] Error scraping endpoint  http://Grafana:9600/metrics - System.Net.Http.HttpRequestException: Resource temporarily unavailable (grafana:9600)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.MetricsScraper.ScrapeEndpoint(String endpoint, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/MetricsScraper.cs:line 72
[2023-12-04 12:13:41.905 INF] Scraping finished, received 0 metrics from endpoint  http://Grafana:9600/metrics
[2023-12-04 12:13:42.470 INF] Successfully created self-signed certificate  for agentGuid : {81888590-2639-49c7-a23a-ab7b81f8e9b6} and workspace: 3d828817-02d2-41f6-b6da-e9b02be6ee9b
[2023-12-04 12:13:42.472 INF] OMS endpoint Url : https://3d828817-02d2-41f6-b6da-e9b02be6ee9b.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
[2023-12-04 12:13:42.472 INF] sending registration request
[2023-12-04 12:13:42.473 INF] waiting for response to registration request
[2023-12-04 12:13:47.480 INF] OMS endpoint Url : https://3d828817-02d2-41f6-b6da-e9b02be6ee9b.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
[2023-12-04 12:13:47.480 INF] sending registration request
[2023-12-04 12:13:47.480 INF] waiting for response to registration request
[2023-12-04 12:13:52.487 INF] OMS endpoint Url : https://3d828817-02d2-41f6-b6da-e9b02be6ee9b.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
[2023-12-04 12:13:52.488 INF] sending registration request
[2023-12-04 12:13:52.488 INF] waiting for response to registration request
[2023-12-04 12:13:57.495 INF] OMS endpoint Url : https://3d828817-02d2-41f6-b6da-e9b02be6ee9b.oms.opinsights.azure.com/AgentService.svc/AgentTopologyRequest
[2023-12-04 12:13:57.495 INF] sending registration request
[2023-12-04 12:13:57.495 INF] waiting for response to registration request
[2023-12-04 12:14:02.503 WRN] exception occurred : One or more errors occurred. (Resource temporarily unavailable (3d828817-02d2-41f6-b6da-e9b02be6ee9b.oms.opinsights.azure.com:443))
[2023-12-04 12:14:02.503 ERR] Registering agent with OMS failed (are the Log Analytics Workspace ID and Key correct?) : One or more errors occurred. (Resource temporarily unavailable (3d828817-02d2-41f6-b6da-e9b02be6ee9b.oms.opinsights.azure.com:443))
[2023-12-04 12:14:02.505 FTL] System.AggregateException: One or more errors occurred. (Resource temporarily unavailable (3d828817-02d2-41f6-b6da-e9b02be6ee9b.oms.opinsights.azure.com:443))
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable (3d828817-02d2-41f6-b6da-e9b02be6ee9b.oms.opinsights.azure.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Certificategenerator.CertGenerator.RegisterWithOms(X509Certificate2 cert, String AgentGuid, String logAnalyticsWorkspaceId, String logAnalyticsWorkspaceKey, String logAnalyticsWorkspaceDomainPrefixOms) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/CertificateGenerator/CertGenerator.cs:line 188
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Certificategenerator.CertGenerator.RegisterWithOmsWithBasicRetryAsync(X509Certificate2 cert, String AgentGuid, String logAnalyticsWorkspaceId, String logAnalyticsWorkspaceKey, String logAnalyticsWorkspaceDomainPrefixOms) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/CertificateGenerator/CertGenerator.cs:line 208
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Certificategenerator.CertGenerator.RegisterAgentWithOMS(String logAnalyticsWorkspaceId, String logAnalyticsWorkspaceKey, String logAnalyticsWorkspaceDomainPrefixOms) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/CertificateGenerator/CertGenerator.cs:line 267
[2023-12-04 12:14:02.507 INF] Termination requested, initiating shutdown.
[2023-12-04 12:14:02.507 INF] Waiting for cleanup to finish
[2023-12-04 12:14:02.522 INF] Done with cleanup. Shutting down.
[2023-12-04 12:14:02.522 INF] MetricsCollector Main() finished.
>>> End logging MetricsModule <<<`
