### ISSUE TITLE
Custom module fails with "System.Net.Sockets.SocketException (13): Permission denied"

### ISSUE THREAD

**Issue by chatnoir1982** [Azure/iotedge#7125]
My custom module was working fine for months, but started failing all of a sudden, with **System.Net.Sockets.SocketException (13): Permission denied**. 
This is thrown when the module tries to initialize a ModuleClient to connect to the IoTHub. The ModuleClient uses "Amqp_WebSocket_Only" to talk to the IoT hub.

My version of IoTEdge is 1.4.2, EdgeAgent and EdgeHub are on 1.4.21.

It's rather clear that it's a permissions issue, but it's unclear which permission(s) and for which resource(s), whether on host or container. It's also unclear why this started happening all of a sudden. 

If anyone has encountered this before, any pointers as to what could suddenly be missing would be appreciated.

See the stack below:

`Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (Permission denied))
 ---> System.AggregateException: One or more errors occurred. (Permission denied)
 ---> System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.GetConnectedSocketAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.GetConnectedSocketAsync()
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.GeneratedCode.HttpHsmClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.GeneratedCode.HttpHsmClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.GeneratedCode.HttpHsmClient.TrustBundleAsync(String api_version)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.<>c__DisplayClass3_0.<GetTrustBundleWithRetryAsync>b__0()
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.RunWithRetryAsync[T](Func`1 taskFunc, ShouldRetry shouldRetry, Func`2 isTransient, Action`3 onRetrying, Boolean fastFirstRetry, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.RunWithRetryAsync[T](Func`1 taskFunc, ShouldRetry shouldRetry, Func`2 isTransient, Action`3 onRetrying, Boolean fastFirstRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.RunWithRetryAsync[TResult](Func`1 taskFunc, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.RunWithRetryAsync[TResult](Func`1 taskFunc)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleWithRetryAsync(HttpHsmClient hsmHttpClient, String apiVersion)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleWithRetryAsync(HttpHsmClient hsmHttpClient, String apiVersion)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleAsync(Uri providerUri, String apiVersion)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleAsync(Uri providerUri, String apiVersion)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateAsync()
   at Microsoft.Azure.Devices.Client.ModuleClient.CreateFromEnvironmentAsync(ITransportSettings[] transportSettings, ClientOptions options)

........shortened for brevity............`

**Comment by gordonwang0** [comment]
Please check the permissions on the module workload sockets. By default, they are located in /var/run/iotedge. Could you post the permissions on all files (including in subdirectories) under /var/run/iotedge?

**Comment by chatnoir1982** [comment]
Hi @gordonwang0, here's a screengrab of /var/run/iotedge. 
No other files/dirs present.

![image](https://github.com/Azure/iotedge/assets/23624740/0480e569-8208-43ae-baa4-f60757121d72)

**Comment by gordonwang0** [comment]
There is a bug (fixed in recent versions) where the sockets getting created as directories causes some permissions errors as you are seeing.

Please try the following:
- stop iotedge (`sudo iotedge system stop`)
- delete those two directories
- restart iotedge (`sudo iotedge system restart`)

**Comment by chatnoir1982** [comment]
The two items are files, not directories. Output below using "ls -lp":

![image](https://github.com/Azure/iotedge/assets/23624740/5e83ea6d-5786-454b-b13d-1a4753ef3bd9)

**Comment by chatnoir1982** [comment]
@gordonwang0 I checked the **/var/lib/aziot/edged/mnt** path, it seems the behavior you described for /var/run/iotedge  applies to the socket for our custom module under this path. Also the owner is root, where it should have been "iotedge".

Should I proceed with the above instructions for this particular directory?

![image](https://github.com/Azure/iotedge/assets/23624740/04bdd8f0-a782-46e5-a056-5d4d964ec302)

**Comment by gordonwang0** [comment]
Yes, you should delete any directories you find in the socket paths.

**Comment by chatnoir1982** [comment]
Solved, thanks.
