### ISSUE TITLE
Regarding the behavior of the metrics-collector module.

### ISSUE THREAD

**Issue by shunya355** [Azure/iotedge#7139]
### Current Configuration
metrics-collector → edgeHub(child：Ubuntu) → edgeHub(Parent：RHEL) → IoTHub

#### Parent Device Information
Host OS RHEL 8.8
aziot-edge:1.4.16-1.el8
azureiotedge-agent:1.4.16
azureiotedge-hub:1.4.16
azureiotedge-metrics-collector:1.1.8

#### Child Device Information
Host OS Ubuntu 22.04
aziot-edge:1.4.16-1
azureiotedge-agent:1.4.16
azureiotedge-hub:1.4.16
azureiotedge-metrics-collector:1.1.8
（Similar error in azureiotedge-metrics-collector:1.1.15）

#### Configuration of metrics-collector
ResourceID: Resource ID of TargetIoTHub
UploadTarget: IoTHub
MetricsEndpointsCSV: http://edgeHub:9600/metrics,http://edgeAgent:9600/metrics
ScrapeFrequencyInSecs: 300
AllowMetrics: edgeAgent_available_disk_space_bytes edgeAgent_total_disk_space_bytes edgeAgent_used_memory_bytes edgeAgent_total_memory_bytes edgeAgent_used_cpu_percent cpu_* disk_* mem_*
CompressForUpload: true

An error occurs in the communication between metrics-collector → edgeHub when the connection between parent and child is interrupted in the above configuration.
（Drop 8883, 443, 5671 port in iptables of parent device.）
The time of blocking is 4 hours, and the error does not occur at a fixed time, such as after 30 minutes, 40 minutes, or 1.5 hours.
I don't think an error will occur with metrics-collector since I am only blocking traffic between the parent and the child.

<details>
<summary>metrics-collector error log</summary>

{"log":"[2023-10-26 07:32:52.321 ERR] Failed sending metrics as IoT message: System.TimeoutException: The operation timed out.\n","stream":"stdout","time":"2023-10-26T07:32:52.3218631Z"}
{"log":" ---\u003e System.Threading.Tasks.TaskCanceledException: A task was canceled.\n","stream":"stdout","time":"2023-10-26T07:32:52.3220605Z"}
{"log":"   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)\n","stream":"stdout","time":"2023-10-26T07:32:52.3220925Z"}
{"log":"   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)\n","stream":"stdout","time":"2023-10-26T07:32:52.3220991Z"}
{"log":"   --- End of inner exception stack trace ---\n","stream":"stdout","time":"2023-10-26T07:32:52.3221024Z"}
{"log":"   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)\n","stream":"stdout","time":"2023-10-26T07:32:52.3221051Z"}
{"log":"   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.BasicModuleClientWrapper.SendMessageAsync(String outputName, Message message) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/BasicModuleClientWrapper.cs:line 64\n","stream":"stdout","time":"2023-10-26T07:32:52.3221081Z"}
{"log":"   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.IotMessageModuleClientWrapper.SendMessageAsync(String outputName, Message message) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/IotMessageModuleClientWrapper.cs:line 50\n","stream":"stdout","time":"2023-10-26T07:32:52.3221333Z"}
</details>

After the above error occurs about 10 times, the following error occurs and the module is restarted, but the restart fails and then restarts normally when IPtables is restored.

<details>
<summary>Error log before restart</summary>

[2023-10-26 09:08:47.391 ERR] Failed sending metrics as IoT message: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.BasicModuleClientWrapper.SendMessageAsync(String outputName, Message message) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/BasicModuleClientWrapper.cs:line 64
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.IotMessageModuleClientWrapper.SendMessageAsync(String outputName, Message message) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/IotMessageModuleClientWrapper.cs:line 50
[2023-10-26 09:08:47.391 INF] Successfully completed periodic operation Scrape and Upload Metrics
[2023-10-26 09:08:47.393 ERR] Failed closing and re-establishing connection to IoT Hub: System.TimeoutException: The operation timed out.
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c.<SendTokenAsync>b__4_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTCbsLink.SendTokenAsync(ICbsTokenProvider tokenProvider, Uri namespaceAddress, String audience, String resource, String[] requiredClaims, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher.InitLoopAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTConnection.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass44_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.OpenInternalAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.BasicModuleClientWrapper.InitializeModuleClientAsync() in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/BasicModuleClientWrapper.cs:line 81
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.BasicModuleClientWrapper.RecreateClientAsync() in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/BasicModuleClientWrapper.cs:line 36
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.IotMessageModuleClientWrapper.RecreateClientAsync() in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/IotMessageModuleClientWrapper.cs:line 31
[2023-10-26 09:08:47.393 INF] Successfully completed periodic operation Reconnect to IoT Hub
[2023-10-26 09:08:47.407 ERR] Unexpected error in periodic operation Scrape and Upload Metrics
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Edge.Util.PeriodicTask.DoWork() in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/PeriodicTask.cs:line 114
</details>

<details>
<summary>Error log on restart</summary>

[2023-10-26 09:14:01.176 ERR] Error occurred during metrics collection setup.
System.TimeoutException: The operation timed out.
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.AmqpCbsLink.EndSendToken(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c.<SendTokenAsync>b__4_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTCbsLink.SendTokenAsync(ICbsTokenProvider tokenProvider, Uri namespaceAddress, String audience, String resource, String[] requiredClaims, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher.InitLoopAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTConnection.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionIsOpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass44_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.OpenInternalAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.BasicModuleClientWrapper.InitializeModuleClientAsync() in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/BasicModuleClientWrapper.cs:line 81
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.BasicModuleClientWrapper.BuildModuleClientWrapperAsync() in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/BasicModuleClientWrapper.cs:line 24
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.ModuleClientWrapper.IotMessageModuleClientWrapper.BuildModuleClientWrapperAsync(CancellationTokenSource cts) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/ModuleClientWrapper/IotMessageModuleClientWrapper.cs:line 23
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Program.BuildModuleClientWrapperAsync(UploadTarget uploadTarget, CancellationTokenSource cts) in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/Program.cs:line 98
   at Microsoft.Azure.Devices.Edge.Azure.Monitor.Program.MainAsync() in /mnt/vss/_work/1/s/edge-modules/metrics-collector/src/Program.cs:line 52
</details>

Could you please advise the cause of this error and how to resolve it?
The expected behavior is that metric information is stored in the EdgeHub of the child device while connection between parent and child is interrupted, and is sent to the IoTHub when connections are restored.
The current behavior is that until an error occurs in the metrics-collector, data is stored in the EdgeHub of the child device and sent to the IoTHub when communication is restored.
Is this behavior normal for this module?
Are there any restrictions, such as the metrics-collector not working properly if the connection between the parent device and the child device is not normal?

**Comment by david-emakenemi** [comment]
@lfitchett any ideas?

**Comment by damonbarry** [comment]
@shunya355 Sorry for the delay on this. The errors in Metrics Collector seem to be happening because the _child's_ Edge Hub is not available/responding. I don't see a direct correlation between these errors and the loss of network connectivity between child and parent edge devices.

To investigate, we'd really need to see what's wrong with the **child's Edge Hub**. Do you have those logs?

**Comment by jlian** [comment]
@shunya355 any updates?

**Comment by jlian** [comment]
@shunya355 ping again

**Comment by bishal41** [comment]
@shunya355 I will proceed and close this issue but feel free to re-open the issue if needed. Thanks!
