### ISSUE TITLE
Fatal error starting Agent (1.0.0 and 1.0.5)

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#723]
## Expected Behavior

edgeAgent shall start normally

## Current Behavior

edgeAgent fail in loop

## Steps to Reproduce

1.
2.
3.
4.

### Device (Host) Operating System

Platform: Debian 8, ARM CPU
### Container Operating System

Linux
#### iotedged

1.0.0
1.0.5
## Logs

[2019-01-09 04:49:04 +00:00]: Starting Edge Agent
[01/09/2019 04:49:07.499 AM] Edge Agent Main()
2019-01-09 04:49:14.218 +00:00 [INF] - Starting module management agent.
2019-01-09 04:49:21.815 +00:00 [INF] - Version - 1.0.5.19141174 (d76e0316c6f324345d77c48a83ce836d09392699)
2019-01-09 04:49:21.821 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
 
 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝
 
2019-01-09 04:49:27.251 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
2019-01-09 04:50:03.883 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
2019-01-09 04:50:06.940 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2019-01-09 04:50:16.774 +00:00 [FTL] - Fatal error starting Agent.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Getting System Info: 0
 
, StatusCode:404, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 204
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.GetSystemInfoAsync() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 118
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.RuntimeInfoProvider`1.GetSystemInfo() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs:line 33
   at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironmentProvider.CreateAsync(IRuntimeInfoProvider runtimeInfoProvider, IEntityStore`2 store, IRestartPolicyManager restartPolicyManager) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironmentProvider.cs:line 38
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.EdgeletModule.<>c.<<Load>b__9_6>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule.<>c.<<Load>b__13_14>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 159
2019-01-09 04:50:18.642 +00:00 [INF] - Termination requested, initiating shutdown.
2019-01-09 04:50:18.666 +00:00 [INF] - Waiting for cleanup to finish
2019-01-09 04:50:18.667 +00:00 [INF] - Done with cleanup. Shutting down.

**Comment by avranju** [comment]
Could you share what you're seeing when you run `journalctl -u iotedge`? You can redirect the output to a file and share that if you like by running -- `journalctl -u iotedge > iotegded.log`.

**Comment by MaxKhlupnov** [comment]
Hello! I have the same issue on Windows 10 after upgrading to 1.0.5.
Issue looks very similar as @KevinKao809 describe above.
edgeAgent started, trying open connections and restart.

[edgeAgent.logs.txt](https://github.com/Azure/iotedge/files/2779482/edgeAgent.logs.txt)
[service.log.txt](https://github.com/Azure/iotedge/files/2779506/service.log.txt)

**Comment by Strandfelt** [comment]
I am experiencing the same issue on Windows 10 1809 with 1.0.5.
Any luck yet, @MaxKhlupnov?

**Comment by MaxKhlupnov** [comment]
Hello, @Strandfelt !
As a workaround I installed 1.0.6-rc version:
- Remove docker
- Remove Hyper-V
- Reboot
- Install Hyper-V
- Install Docker
Install 10.0.6-rc1
. {Invoke-WebRequest -useb https://raw.githubusercontent.com/Azure/iotedge/1.0.6-rc1/scripts/windows/setup/IotEdgeSecurityDaemon.ps1} | Invoke-Expression; `
 Install-SecurityDaemon  -Manual -ContainerOs Linux

**Comment by myagley** [comment]
@Strandfelt The 1.0.5 version of the install script no longer opens up the firewall for Linux containers. We've added this back in 1.0.6 (yet to be released). However, as @MaxKhlupnov suggested you can try using the install script from the 1.0.6 release candidate (linked above).

This will set things up properly for linux containers on windows.

**Comment by myagley** [comment]
This has been fixed in version `1.0.6`. Closing this issue for now.
