### ISSUE TITLE
azure-blob-storage 1.4.4 Unable to load DLL 'blobsvc.dll'

### ISSUE THREAD

**Issue by dperez83** [Azure/iotedge#7379]
## Expected Behavior
Use azure-blob-storage 1.4.4 (https://hub.docker.com/r/microsoft/azure-blob-storage)

## Current Behavior
The container does not start. 
```
Starting Azure Blob Storage on IoT Edge, version 1.4.4.0.
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (An error occurred while writing to logger(s). (Unable to load DLL 'blobsvc.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A))))
---> System.AggregateException: One or more errors occurred. (An error occurred while writing to logger(s). (Unable to load DLL 'blobsvc.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)))
---> System.AggregateException: An error occurred while writing to logger(s). (Unable to load DLL 'blobsvc.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A))
---> System.DllNotFoundException: Unable to load DLL 'blobsvc.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
   at Microsoft.Azure.Devices.BlobStorage.Common.BlobLogger.BlobTrace(BackendLogLevel LogLevel, String Message)
   at Microsoft.Azure.Devices.BlobStorage.Common.BlobLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args)
   at Microsoft.Azure.Devices.BlobStorage.IoT.ModuleTwinConfigurationProvider.Initialize()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Azure.Devices.BlobStorage.IoT.ModuleTwinConfigurationProvider..ctor(ModuleClient iotModuleClient)
   at Microsoft.Azure.Devices.BlobStorage.IoT.ModuleTwinConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AzureStack.Services.Storage.FrontEnd.Program.BuildServices(String[] args)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AzureStack.Services.Storage.FrontEnd.Program.Main(String[] args)
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
Add the azureBlobStorage module deployment with the latest version 1.4.4-nanoserver-1809
or simply run `docker run mcr.microsoft.com/azure-blob-storage:1.4.4-nanoserver-1809`

### Device Information
* Host OS [e.g. Ubuntu 22.04, Windows Server IoT 2019]: Windows Server 2019
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Windows containers 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.15
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1.18
* Edge Hub [image tag (e.g. 1.0.0)]:  1.1.18
* Docker/Moby [run `docker version`]: 19.03.12+azure

**Comment by ryanwinter** [comment]
This Github repo is for the core IoT Edge runtime. For Blob storage issues, please open an Azure Technical Support ticket: https://azure.microsoft.com/support/create-ticket/
