### ISSUE TITLE
Leaf device cannot connect to Edge gateway - The token could not be parsed

### ISSUE THREAD

**Issue by krokoko** [Azure/iotedge#743]
Hello,

  I have a setup where a leaf device is connecting and sending data to an edge device in transparent mode. Everything is working fine. I did update all the packages to the latest versions, and i'm not able to connect properly anymore.

## Expected Behavior
The leaf device connect to the edge gateway

## Current Behavior
The leaf device cannot connect and the edgeHub print an error "The token could not be parsed"

## Steps to Reproduce
1. Create a leaf device running the C SDK version 1.2.12
2. Setup an edge device in transparent gateway mode with iotedge runtime 1.0.4
3. Deploy edgeHub and edgeAgent v 1.0.5
4. Try to authenticate to the edge gateway from the leaf device

### Device (Host) Operating System
Debian 9

### Architecture
edge gateway : x86_64, leaf device armv7

### Container Operating System
Linux

#### iotedged
1.0.4

#### Edge Agent
1.0.5

#### Edge Hub
1.0.5

#### IoT C SDK
1.2.12

#### Docker
18.09.1

## Logs
edgeHub : 
```
2019-01-24 19:17:18.233 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Authenticators.DeviceScopeTokenAuthenticator] - Error authenticating token for sbrio_lcdaq because the token could not be parsed
System.UnauthorizedAccessException: The specified SAS token is expired
   at Microsoft.Azure.Devices.Common.Security.SharedAccessSignature..ctor(String iotHubName, DateTime expiresOn, String expiry, String keyName, String signature, String encodedAudience)
   at Microsoft.Azure.Devices.Common.Security.SharedAccessSignature.Parse(String iotHubName, String rawToken)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Authenticators.DeviceScopeTokenAuthenticator.TryGetSharedAccessSignature(String token, IIdentity identity, SharedAccessSignature& sharedAccessSignature) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs:line 46
2019-01-24 19:17:18.234 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeAuthenticator] - Credentials for client sbrio_lcdaq are not valid.
2019-01-24 19:17:18.234 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeAuthenticator] - Client sbrio_lcdaq in device scope not authenticated locally.
2019-01-24 19:17:18.234 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Authenticator] - Unable to authenticated client sbrio_lcdaq
2019-01-24 19:17:18.238 +00:00 [ERR] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.DeviceIdentityProvider] - Unable to generate identity for clientId sbrio_lcdaq and username HBM-XXXX.azure-devices.net/sbrio_lcdaq/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.12%20(native%3b%20Linux%3b%20armv7l)
2019-01-24 19:17:18.239 +00:00 [INF] [ProtocolGateway] - ClientNotAuthenticated, Client ID: sbrio_lcdaq; Username: XXXXX.azure-devices.net/sbrio_lcdaq/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.12%20(native%3b%20Linux%3b%20armv7l), 0df5c829
```

leaf device : 
```
-> 17:40:22 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXXXX.azure-devices.net/sbrio_lcdaq/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.12%20(                                                native%3b%20Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 17:40:22 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Thu Jan 24 17:40:22 2019 File:XXXXX/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1724 Connection Not                                                 Accepted: 0x5: Not Authorized
[connection_status_callback] The device client has been disconnected : CLIENT_CONNECTION_DEVICE_DISABLED

[connection_status_callback] The device client has been disconnected : CLIENT_CONNECTION_NO_NETWORK

```
## Additional Information
The system was working fine before the upgrade. The certificate is valid when testing with openssl command. I replaced the sensitive information with 'XXX' values.

**Comment by krokoko** [comment]
Ok it's back after unplugging-plugging back the power to the leaf device board. Seems to be a clock issue.
