### ISSUE TITLE
Port Binding in Container Create Options fails container creation

### ISSUE THREAD

**Issue by Strandfelt** [Azure/iotedge#744]
I have a custom Edge module that needs to expose some ports on the host.
This has worked fine until recently, but after updating the IoT Edge runtime, module creation fails.
The port binding which fails (tcp 50051) is exposed in the Dockerfile of the edge module.

## Expected Behavior
Ports should be exposed and visible from netstat command

## Current Behavior
Module start fails

## Steps to Reproduce

1. Set a module with PortBindings in the Container Create options

### Device (Host) Operating System
Windows 10 Pro

### Architecture
64-bit

### Container Operating System
Linux Containers

#### iotedged
iotedge 1.0.6~rc1 (8a38db421acf732c5d24f83cb71cb93d0db4ea96)
Also tried 1.0.5

#### Edge Agent
 mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
 mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Logs
```
2019-01-24 19:36:33.866 +00:00 [WRN] - Reconcile failed because of the an exception
System.AggregateException: One or more errors occurred. (Error calling start module hiddenmodulename: Could not start module hiddenmodulename
        caused by: Could not start module hiddenmodulename
        caused by: driver failed programming external connectivity on endpoint hiddenmodulename (b9526fd7aeefb585ada4e93f7eb6dd130c0bbba1a2eb9c745a0f9cca5b65ebe1): Error starting userland proxy: Bind for 0.0.0.0:50051: unexpected error Permission denied) ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException: Error calling start module hiddenmodulename: Could not start module hiddenmodulename
        caused by: Could not start module hiddenmodulename
        caused by: driver failed programming external connectivity on endpoint hiddenmodulename (b9526fd7aeefb585ada4e93f7eb6dd130c0bbba1a2eb9c745a0f9cca5b65ebe1): Error starting userland proxy: Bind for 0.0.0.0:50051: unexpected error Permission denied
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 142
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 86
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 114
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 115
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 176
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 187
---> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module hiddenmodulename: Could not start module hiddenmodulename
        caused by: Could not start module hiddenmodulename
        caused by: driver failed programming external connectivity on endpoint hiddenmodulename (b9526fd7aeefb585ada4e93f7eb6dd130c0bbba1a2eb9c745a0f9cca5b65ebe1): Error starting userland proxy: Bind for 0.0.0.0:50051: unexpected error Permission denied, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 142
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 86<---
```

## Additional Information
Container Create Options:
```
{
    "Hostname": "hiddenmodulename",
    "Cmd": [        
    ],
    "HostConfig": {
        "PortBindings": {
            "50051/tcp": [
                {
                    "HostPort": "50051"
                }
            ],
            "51210/tcp": [
                {
                    "HostPort": "51210"
                }
            ]
        },
        "Binds": [
            "d:/iotedge"
        ],
        "ExtraHosts": [
            "localhost:127.0.0.1"
        ]
    }
}
```

**Comment by varunpuranik** [comment]
@Strandfelt - The createOptions are not processed by the IoT Edge runtime as such and are directly passed to docker to process. So this seems like something to do with the create options that are being set. 
In particular, the Binds part doesn't look right - it should be in the format "<HostStoragePath>:<ModuleStoragePath>". 
Also, looks like the ExtraHosts should be specified in the format ["hostname:IP"]. 
You can reference the schema for the createOptions here - https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate

Also, can you share the iotedged logs? That will give the actual errors that the edge runtime is getting. 
You can refer to this on how to get the iotedged logs - https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#check-the-status-of-the-iot-edge-security-manager-and-its-logs

**Comment by Strandfelt** [comment]
Hi @varunpuranik. Thanks for replying.

I am using the exact same format as is used for the Edge Hub container (seen on the portal) and also the IoT Edge OPC publisher: https://github.com/Azure/iot-edge-opc-publisher#using-it-as-a-module-in-azure-iot-edge

Here is the related iotedged logs:
```
1/29/2019 10:10:46 AM info: edgelet_docker::runtime -- Pulling image hiddencustomer.azurecr.io/hiddenmodulename:50265...
1/29/2019 10:10:46 AM info: edgelet_docker::runtime -- Successfully removed module hiddenmodulename
1/29/2019 10:10:46 AM info: edgelet_docker::runtime -- Creating module hiddenmodulename...
1/29/2019 10:10:46 AM info: edgelet_docker::runtime -- Successfully pulled image hiddencustomer.azurecr.io/hiddenmodulename:50265
1/29/2019 10:10:46 AM info: edgelet_http::logging -- [mgmt] - - - [2019-01-29 09:10:46.922247700 UTC] "PUT /modules/hiddenmodulename?api-version=2018-06-28 HTTP/1.1" 200 OK
                      1226 "-" "-" pid(any)
1/29/2019 10:10:46 AM info: edgelet_docker::runtime -- Successfully created module hiddenmodulename
1/29/2019 10:10:46 AM info: edgelet_docker::runtime -- Starting module hiddenmodulename...
1/29/2019 10:10:47 AM warn: edgelet_utils::logging -- Could not start module hiddenmodulename
1/29/2019 10:10:47 AM warn: edgelet_utils::logging --   caused by: driver failed programming external connectivity on endpoint hiddenmodulename
                      (135c103e441f38cd8c29c6d6f5d6188feb0c56df69f98425e96138a4f6628c20): Error starting userland proxy: Bind for 0.0.0.0:50051: unexpected error Permission denied
1/29/2019 10:10:47 AM info: edgelet_http::logging -- [mgmt] - - - [2019-01-29 09:10:47.453359500 UTC] "POST /modules/hiddenmodulename/start?api-version=2018-06-28 HTTP/1.1"
                      500 Internal Server Error 368 "-" "-" pid(any)
1/29/2019 10:10:47 AM info: edgelet_docker::runtime -- Starting module hiddenmodulename...
1/29/2019 10:10:48 AM warn: edgelet_utils::logging --   caused by: driver failed programming external connectivity on endpoint hiddenmodulename
                      (697404faf4fa700c3c85d5cca470fc99b0860be6a6a8dc4045bd1d244bbcf6ed): Error starting userland proxy: Bind for 0.0.0.0:50051: unexpected error Permission denied
1/29/2019 10:10:48 AM warn: edgelet_utils::logging -- Could not start module hiddenmodulename
1/29/2019 10:10:48 AM info: edgelet_http::logging -- [mgmt] - - - [2019-01-29 09:10:48.082119200 UTC] "POST /modules/hiddenmodulename/start?api-version=2018-06-28 HTTP/1.1"
                      500 Internal Server Error 368 "-" "-" pid(any)
1/29/2019 10:10:49 AM info: edgelet_core::watchdog -- Checking edge runtime status
1/29/2019 10:10:49 AM info: edgelet_core::watchdog -- Edge runtime is running.
1/29/2019 10:10:49 AM info: edgelet_docker::runtime -- Getting logs for module edgeAgent...
1/29/2019 10:10:49 AM info: edgelet_http::logging -- [mgmt] - - - [2019-01-29 09:10:49.849565800 UTC] "GET /modules/edgeAgent/logs?api-version=2018-06-28&follow=true&tail=all
                      HTTP/1.1" 200 OK - "-" "iotedge/0.1.0" pid(any)
1/29/2019 10:10:49 AM info: edgelet_docker::runtime -- Successfully got logs for module edgeAgent
1/29/2019 10:10:53 AM info: edgelet_docker::runtime -- Starting module hiddenmodulename...
1/29/2019 10:10:53 AM warn: edgelet_utils::logging --   caused by: driver failed programming external connectivity on endpoint hiddenmodulename
                      (362badc71b22460716ce183209a7dba7374e0e748e8c00d3f37522b5fdddf9c3): Error starting userland proxy: Bind for 0.0.0.0:50051: unexpected error Permission denied
1/29/2019 10:10:53 AM warn: edgelet_utils::logging -- Could not start module hiddenmodulename
1/29/2019 10:10:53 AM info: edgelet_http::logging -- [mgmt] - - - [2019-01-29 09:10:53.860065500 UTC] "POST /modules/hiddenmodulename/start?api-version=2018-06-28 HTTP/1.1"
                      500 Internal Server Error 368 "-" "-" pid(any)
1/29/2019 10:11:04 AM info: edgelet_docker::runtime -- Starting module hiddenmodulename...
1/29/2019 10:11:05 AM warn: edgelet_utils::logging -- Could not start module hiddenmodulename
1/29/2019 10:11:05 AM info: edgelet_http::logging -- [mgmt] - - - [2019-01-29 09:11:05.131854400 UTC] "POST /modules/hiddenmodulename/start?api-version=2018-06-28 HTTP/1.1"
                      500 Internal Server Error 368 "-" "-" pid(any)
1/29/2019 10:11:05 AM warn: edgelet_utils::logging --   caused by: driver failed programming external connectivity on endpoint hiddenmodulename
                      (f1f77e007bb850d3763e81c6dbd8d088189ba078758c085fa86a913356c9d73d): Error starting userland proxy: Bind for 0.0.0.0:50051: unexpected error Permission denied
1/29/2019 10:11:05 AM info: edgelet_http::logging -- [work] - - - [2019-01-29 09:11:05.199841100 UTC] "POST
                      /modules/%24edgeAgent/genid/636839267837477279/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 2433 "-" "-" pid(any)
```

**Comment by myagley** [comment]
It's failing to bind to port 50051 on the host machine. Is it possible that something else is also listening on this port? I believe on Windows you can get a permissions denied if another process is bound to the same port in exclusive mode.

**Comment by Strandfelt** [comment]
Correct. I need to listen to port 50051 on the host machine. I checked using `netstat` to see if there was anything listening on the port already, but there wasn't

**Comment by myagley** [comment]
To narrow the issue can you try changing the port you are binding to on the host? Something like:

```json
{
    "Hostname": "hiddenmodulename",
    "Cmd": [        
    ],
    "HostConfig": {
        "PortBindings": {
            "50051/tcp": [
                {
                    "HostPort": "15000"
                }
            ],
            "51210/tcp": [
                {
                    "HostPort": "15001"
                }
            ]
        },
        "Binds": [
            "d:/iotedge"
        ],
        "ExtraHosts": [
            "localhost:127.0.0.1"
        ]
    }
}
```
It also might help to run `netsh interface ipv4 show excludedportrange protocol=tcp` to see if these ports are being excluded.

**Comment by Strandfelt** [comment]
We ended up switching to Windows Containers in the meantime, since this was breaking required functionality in our solution.

**Comment by myagley** [comment]
Are you unblocked now on Windows Containers?

**Comment by Strandfelt** [comment]
Yes, IoT Edge on Windows Containers does not have the same issue.

**Comment by mdmorar** [comment]
Was this ever resolved. I'm trying to get a server iot edge module to communicate via tcp with an ubuntu client iot edge module on the same device. The device is ubuntu 16.04.

**Comment by veyalla** [comment]
What do your createOptions look like and what’s the error?

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.

**Comment by PCSmithy** [comment]
I am experiencing a the same issue running where Docker cannot start a container in my iotedge solution. Here is the full error as listed from the IoT Edge Security Manager logs:

```
Apr 07 09:51:36 tx2-quasar-1 iotedged[8257]: 2020-04-07T14:51:36Z [WARN] - Could not start module cps
Apr 07 09:51:36 tx2-quasar-1 iotedged[8257]: 2020-04-07T14:51:36Z [WARN] -         caused by: driver failed programming external connectivity on endpoint cps (d9ff2d4996f6e9076a527fc61f488bbbb68cebda8438eadc4cba86d23a54c5bb): Bind for 0.0.0.0:5678 failed: port is already allocated
Apr 07 09:51:36 tx2-quasar-1 iotedged[8257]: 2020-04-07T14:51:36Z [INFO] - [mgmt] - - - [2020-04-07 14:51:36.555011358 UTC] "POST /modules/cps/start?api-version=2019-01-30 HTTP/1.1" 500 Internal Server Error 283 "-" "-" auth_id(-)
```

The the edge runtime on a Linux 18.04 machine ( a Jetson TX2)

My iotedge solution was built on a windows 10 pc with docker version 2.2.0.5

This error only occurs when I build and deploy the deployment.debug.template.json. If I use the regular (non debug) deployment template, everything is fine. This is obviously because the non-debug deployment doesn't open a bunch of ports for debugging. 

I don't open any ports in my custom modules, the only ports specified in the deployment.debug.template.json are the _default ones to support debugging_ (which I'm currently not using, so I may just delete them to get past this...I'm using the debug template to support additional debugging features in the modules without maintaining multiple, similar iotedge solutions).

My solution currently has 3 custom iotedge modules, and it was functioning perfectly fine with just the 3, deploying off of the debug deployment template, with all 3 custom modules binding to the same port 5678 according to the default debug ports. Interestingly, this problem only started for me after I created a 4th custom module. And I'm fairly certain there isn't an error in the contents on the module, because after several reboots and redeployments through troubleshooting, I've seen that when there are 4 custom modules, the one that fails to start is not always predictable, it seems to be whichever module of the 4 boots last.

Does anyone have any idea why adding a 4th custom module is causing docker to fail to start a container on the basis that the port it wants to bind to is already allocated? When running the first 3 modules all binding to the same port wasn't an issue?

Here is a snippet of my deployment.debug.template.json file of the two modules that are failing to start:
```
          "cps": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULES.cps.debug}",
              "createOptions": {
                "ExposedPorts": {
                  "5678/tcp": {}
                },
                "HostConfig": {
                  "PortBindings": {
                    "5678/tcp": [
                      {
                        "HostPort": "5678"
                      }
                    ]
                  }
                }
              }
            }
          },
          "telemetry": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULES.telemetry.debug}",
              "createOptions": {
                "ExposedPorts": {
                  "5678/tcp": {}
                },
                "HostConfig": {
                  "PortBindings": {
                    "5678/tcp": [
                      {
                        "HostPort": "5678"
                      }
                    ]
                  }
                }
              }
            }
          }
```
Any insight is appreciated, let me know if I need to provide additional logs / configs / etc.

**Comment by skvark** [comment]
@PCSmithy Did you manage to solve the issue? I'm experiencing the exact same behavior after adding 4th edge module.

**Comment by skvark** [comment]
Thanks! I managed to get the 4th module working by changing the auto-generated HostPort value in `deployment.debug.template.json` from 5678 to 5681 for the 4th module. Other modules were numbered 5678, 5679 and 5680. For some reason the port number was 5678 for the 4th module which conflicts with the first module.

**Comment by PCSmithy** [comment]
Gotcha, I guess I never realized the port numbers were supposed to auto-increment like that, but that makes a lot of sense. Glad you got it working!
