### ISSUE TITLE
SimulatedTemperatureSensor reports errors, but messages show up in dashboard

### ISSUE THREAD

**Issue by anonymouse64** [Azure/iotedge#746]
## Expected Behavior

I should see the same output after enabling the SimulatedTemperatureSensor as from the docs [here](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux):

![image](https://user-images.githubusercontent.com/6006573/51737321-ede57f80-2094-11e9-8745-86badcf21be9.png)

## Current Behavior

I see the following errors show up in the logs of the SimulatedTemperatureSensor container/module:

```
[2019-01-25 07:53:21 : Starting Module
[01/25/2019 07:53:21.333 AM] Main()
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Using transport Amqp_Tcp_Only

Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to open Events link as the connection could not be authenticated) ---> System.InvalidOperationException: Unable to open Events link as the connection could not be authenticated
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 106
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 74
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 33
```

However I have no other devices running Azure IoT Edge, and my messages/day seems to go up anyways while this is running. If I stop all the Azure IoT Edge services then the messages/day stops rising.

## Steps to Reproduce

1. Follow the instructions from the quick-start

## Context (Environment)

I am using a slightly different deployment than the quick-start, I am using the docker snap rather than the moby engine. You can see the build process for the docker snap to see how it differs from the moby package here: https://git.launchpad.net/~docker/+git/snap/tree/snap/snapcraft.yaml 
I couldn't find where the moby package build script lives so I'm not sure how the moby package differs from the snap package...

### Device (Host) Operating System

Ubuntu 16.04 Server

### Architecture
x86-64

### Container Operating System
Docker

#### iotedged

`iotedge 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)`

#### Edge Agent
the docker container ID is a5c65293c4d0 (as reported as `docker ps`)
#### Edge Hub
the docker container ID is dd8b7dfacc87 (as reported as `docker ps`)

#### Docker

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Mon Oct  1 14:25:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Mon Oct  1 14:25:31 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Logs

iotedged log: https://gist.github.com/anonymouse64/809b54c0370bae6614da71e5c7c08760

## Additional Information

This is what my connection string looks like: 
```
  device_connection_string: "HostName=MY-HUB-NAME.azure-devices.net;DeviceId=myEdgeDevice;SharedAccessKey=SOME-PRIVATE-KEY"
```

My setting for the hostname in config.yaml looks like this:
```
hostname: "MY-HUB-NAME.azure-devices.net"
```

The docs don't say anything about changing the hostname, but when I don't change that setting I see a different error in the logs for SimulatedTemperatureSensor:

```
[2019-01-25 10:00:53 : Starting Module
[01/25/2019 10:00:53.598 AM] Main()
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Using transport Amqp_Tcp_Only

Unhandled Exception: System.AggregateException: One or more errors occurred. (The connection string has an invalid value for property: GatewayHostName
Parameter name: iotHubConnectionString) ---> System.ArgumentException: The connection string has an invalid value for property: GatewayHostName
Parameter name: iotHubConnectionString
   at Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.ValidateFormat(String value, String propertyName, Regex regex)
   at Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.Validate()
   at Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.Create(String hostname, String gatewayHostname, IAuthenticationMethod authenticationMethod)
   at Microsoft.Azure.Devices.Client.ClientFactory.Create(String hostname, String gatewayHostname, IAuthenticationMethod authenticationMethod, ITransportSettings[] transportSettings)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 104
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 74
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 33
```

**Comment by varunpuranik** [comment]
@anonymouse64 - Looks like there are a couple of things going on here - 
1. The messages/day count increasing in the portal when the SimulatedTemperatureSensor is throwing errors - have you checked how many messages you are seeing in the portal? The Edge runtime itself sends a few messages (in the form of twin requests, etc). which might be the increase you are seeing. If the number is significant (close to 500), then maybe you have some other device that is sending telemetry. You can use a tool like the device explorer to view the telemetry being sent by the devices to IoTHub - https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer
2. As for the error you are getting, I believe it is because your hostname is not correct. The hostname is supposed to be the name of the Edge device on which the edge runtime has been installed (not the name of the IoTHub host). 
After updating the hostname in the config.yaml, you will have to restart iotedge for the changes to take effect.

**Comment by myagley** [comment]
How is the IoT Edge runtime being installed? The installer should select an appropriate `hostname` automatically. You should only need to update the connection string for your device.

**Comment by anonymouse64** [comment]
I was able to resolve this by setting the hostname in the configuration file.
