### ISSUE TITLE
System.Net.Sockets.SocketException (104): Connection reset by peer

### ISSUE THREAD

**Issue by kgalic** [Azure/iotedge#755]
I have set my IoT Edge to work as a transparent Gateway. I enabled certificate authentication and connected my downstream device and I managed to send messages to IoT Hub through my Iot Edge GW.
At some point I need to set a module that takes file from shared network location and uploads it to the blob storage. I implemented a module in c# and deployed it successfully to the IoT Edge.
Since I was getting another exception here and I could not get it working, I removed module from the deployment script and deployed it again.
At this point I initiated a connection from my downstream device and I got an exception that is presented in the title.
So now, after removing this module, my Edge device doesn't work as a transparent gateway anymore.
In the logs I can see that it receives messages, and my downstream device does not get any exception, it reports that messages are successfully sent. However, messages are not passed to the IoT Hub.

## Expected Behavior
Messages should be passed to the Iot Hub

## Current Behavior
System.Net.Sockets.SocketException (104): Connection reset by peer

## Steps to Reproduce

1. Setup Iot Edge to work as a transparent gateway with x509 auth(enable this in env variables)
2. Enable Downstream device and make sure that messages can be sent to IoT Hub through Edge Gw
3. Install module, and deploy
4. Remove Module and re-deploy
5. Try to send messages again from downstream device

### Device (Host) Operating System

Ubuntu 18.04
### Architecture

amd64
### Container Operating System

Linux
#### iotedged
 1.05

## Logs

2019-01-28 09:32:34.890 +00:00 [INF] - Client new-dev in device scope authenticated locally.
2019-01-28 09:32:34.890 +00:00 [INF] - Successfully generated identity for clientId new-dev and username kresimir-vm/new-dev/?api-version=2018-06-30&DeviceClientType=.NET%2F1.19.0%20%28.NET%20Core%204.6.26628.05%3B%20Microsoft%20Windows%2010.0.14393%20WindowsProduct%3A0x00000004%3B%20X64%29
2019-01-28 09:32:34.894 +00:00 [INF] - ClientAuthenticated, new-dev, 5ecea359
2019-01-28 09:32:34.903 +00:00 [INF] - New device connection for device new-dev
2019-01-28 09:32:34.904 +00:00 [INF] - Bind device proxy for device new-dev
2019-01-28 09:32:34.905 +00:00 [INF] - Binding message channel for device Id new-dev
2019-01-28 09:32:34.976 +00:00 [INF] - Processing subscription TwinResponse for client new-dev.
2019-01-28 09:32:34.976 +00:00 [INF] - Processing subscription C2D for client new-dev.
2019-01-28 09:32:34.978 +00:00 [INF] - Start listening for C2D messages for device new-dev
2019-01-28 09:32:35.080 +00:00 [INF] - Set subscriptions from session state for new-dev
2019-01-28 09:32:35.084 +00:00 [INF] - Processing subscription TwinResponse for client new-dev.
2019-01-28 09:32:35.084 +00:00 [INF] - Processing subscription C2D for client new-dev.
2019-01-28 09:32:35.086 +00:00 [INF] - Set subscriptions from session state for new-dev
2019-01-28 09:32:35.233 +00:00 [WRN] - Closing connection for device: new-dev, scope: ExceptionCaught, System.Net.Sockets.SocketException (104): Connection reset by peer
   at DotNetty.Transport.Channels.Sockets.TcpSocketChannel.DoReadBytes(IByteBuffer byteBuf)
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation), 5ecea359
2019-01-28 09:32:35.234 +00:00 [INF] - Disposing MessagingServiceClient for device Id new-dev because of exception - System.Net.Sockets.SocketException (104): Connection reset by peer
   at DotNetty.Transport.Channels.Sockets.TcpSocketChannel.DoReadBytes(IByteBuffer byteBuf)
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
2019-01-28 09:32:35.235 +00:00 [INF] - Setting device proxy inactive for device Id new-dev
2019-01-28 09:32:35.239 +00:00 [INF] - Device connection removed for device new-dev
2019-01-28 09:32:35.242 +00:00 [INF] - Remove device connection for device new-dev

## Additional Information
IoT Edge 1.05
Also I have tried to setup IoT Edge simulator on my Edge device. But this also did not work, but could be that it caused some conflict

**Comment by kgalic** [comment]
This issue was because my downstream device application finishes execution before messages are passed to the IoT Hub. Since it was a console appliaction, at the end of the main function, Console.Readline() solved the problem
