### ISSUE TITLE
edgeHub throws System.OutOfMemoryException

### ISSUE THREAD

**Issue by phasepilot** [Azure/iotedge#760]
## Expected Behavior
edgeHub routes messages to Azure Stream Analytics Edge container

## Current Behavior
edgeHub throws System.OutOfMemoryException

## Steps to Reproduce

1. Deploy tempSensor module to device
2. Deploy Stream Analytics Edge to device
3. View logs of edgeHub

### Device (Host) Operating System
Raspbian Stretch

### Architecture
arm32

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)

#### Edge Agent
1.0                 c093b23f246a

#### Edge Hub
1.0                 915b566be668

#### Docker
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 17:16:17 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       74baf62
  Built:            Tue Dec  4 23:30:17 2018
  OS/Arch:          linux/arm
  Experimental:     false

## Logs
[2019-01-28 22:08:35 +00:00]: Starting Edge Hub
[01/28/2019 10:08:36.195 PM] Edge Hub Main()
[01/28/2019 10:08:42.010 PM] Found intermediate certificates: [CN=iotedged workload ca:04/28/2019 21:17:19],[CN=Test Edge Device CA:04/28/2019 21:17:19],[CN=Test Edge Owner CA:04/28/2019 21:17:19]
2019-01-28 22:08:47.051 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2019-01-28 22:08:47.688 +00:00 [INF] - Starting Edge Hub
2019-01-28 22:08:47.691 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2019-01-28 22:08:47.703 +00:00 [INF] - Version - 1.0.5.19141174 (d76e0316c6f324345d77c48a83ce836d09392699)
2019-01-28 22:08:47.723 +00:00 [INF] - Loaded server certificate with expiration date of "2019-04-28T21:17:19.0000000+00:00"
2019-01-28 22:08:47.879 +00:00 [INF] - Started task to cleanup processed and stale messages
2019-01-28 22:08:47.880 +00:00 [INF] - Created new message store
2019-01-28 22:08:47.879 +00:00 [INF] - Created device scope identities cache
2019-01-28 22:08:47.919 +00:00 [INF] - Starting refresh of device scope identities cache
2019-01-28 22:08:48.680 +00:00 [INF] - Initializing configuration
2019-01-28 22:08:48.810 +00:00 [INF] - New device connection for device iot-edge-pi/$edgeHub
2019-01-28 22:08:49.102 +00:00 [INF] - Attempting to connect to IoT Hub for client iot-edge-pi/$edgeHub via AMQP...
2019-01-28 22:08:53.139 +00:00 [INF] - Exiting disconnected state
2019-01-28 22:08:53.155 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
2019-01-28 22:08:53.171 +00:00 [INF] - Processing subscriptions for client iot-edge-pi/$edgeHub.
2019-01-28 22:08:53.203 +00:00 [INF] - Cloud connection for iot-edge-pi/$edgeHub is True
2019-01-28 22:08:53.236 +00:00 [INF] - Connection status for iot-edge-pi/$edgeHub changed to ConnectionEstablished
2019-01-28 22:08:53.266 +00:00 [INF] - Entering connected state
2019-01-28 22:08:53.285 +00:00 [INF] - Created cloud proxy for client iot-edge-pi/$edgeHub via AMQP, with client operation timeout 20 seconds.
2019-01-28 22:08:53.317 +00:00 [INF] - Initialized cloud proxy 31672269-a47d-4cd9-ae3e-63119e9c1215 for iot-edge-pi/$edgeHub
2019-01-28 22:08:53.332 +00:00 [INF] - Created cloud connection for client iot-edge-pi/$edgeHub
2019-01-28 22:08:53.483 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iot-edge-pi/$edgeHub.
2019-01-28 22:08:53.558 +00:00 [INF] - Processing subscription Methods for client iot-edge-pi/$edgeHub.
2019-01-28 22:08:54.051 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iot-edge-pi/$edgeHub.
2019-01-28 22:08:54.068 +00:00 [INF] - Processing subscription Methods for client iot-edge-pi/$edgeHub.
2019-01-28 22:08:56.684 +00:00 [INF] - Obtained edge hub config from module twin
2019-01-28 22:08:56.720 +00:00 [INF] - Obtained edge hub config patch update from module twin
2019-01-28 22:08:57.688 +00:00 [INF] - Set the following 4 route(s) in edge hub
2019-01-28 22:08:57.695 +00:00 [INF] - alertsToCloud: FROM /messages/modules/iotedgestreamanalytics/* INTO $upstream
2019-01-28 22:08:57.696 +00:00 [INF] - alertsToReset: FROM /messages/modules/iotedgestreamanalytics/* INTO BrokeredEndpoint("/modules/tempSensor/inputs/control")
2019-01-28 22:08:57.697 +00:00 [INF] - telemetryToAsa: FROM /messages/modules/tempSensor/* INTO BrokeredEndpoint("/modules/iotedgestreamanalytics/inputs/temperature")
2019-01-28 22:08:57.699 +00:00 [INF] - telemetryToAsaToo: FROM /messages/modules/tempSensor/* INTO BrokeredEndpoint("/modules/iot-stream-a/inputs/tempinput")
2019-01-28 22:08:57.713 +00:00 [INF] - Updated message store TTL to 7200 seconds
2019-01-28 22:08:57.716 +00:00 [INF] - Updated the edge hub store and forward configuration
2019-01-28 22:08:57.720 +00:00 [INF] - Initialized edge hub configuration
2019-01-28 22:08:57.819 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
2019-01-28 22:08:57.988 +00:00 [WRN] - Module iot-edge-pi/iot-stream-a is not connected
2019-01-28 22:08:58.316 +00:00 [INF] - Scheduling server certificate renewal for "2019-04-28T21:14:49.0006070Z".
2019-01-28 22:08:58.326 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2019-01-28 22:08:58.353 +00:00 [INF] - Starting MQTT head
2019-01-28 22:08:58.828 +00:00 [INF] - Updating edge hub configuration
2019-01-28 22:08:58.951 +00:00 [WRN] - Module iot-edge-pi/iot-stream-a is not connected
2019-01-28 22:08:58.955 +00:00 [INF] - Set the following 4 route(s) in edge hub
2019-01-28 22:08:58.956 +00:00 [INF] - alertsToCloud: FROM /messages/modules/iotedgestreamanalytics/* INTO $upstream
2019-01-28 22:08:58.956 +00:00 [INF] - alertsToReset: FROM /messages/modules/iotedgestreamanalytics/* INTO BrokeredEndpoint("/modules/tempSensor/inputs/control")
2019-01-28 22:08:58.956 +00:00 [INF] - telemetryToAsa: FROM /messages/modules/tempSensor/* INTO BrokeredEndpoint("/modules/iotedgestreamanalytics/inputs/temperature")
2019-01-28 22:08:58.957 +00:00 [INF] - telemetryToAsaToo: FROM /messages/modules/tempSensor/* INTO BrokeredEndpoint("/modules/iot-stream-a/inputs/tempinput")
2019-01-28 22:08:58.957 +00:00 [INF] - Updated message store TTL to 7200 seconds
2019-01-28 22:08:58.957 +00:00 [INF] - Updated the edge hub store and forward configuration
2019-01-28 22:08:59.067 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2019-01-28 22:08:59.407 +00:00 [INF] - Starting AMQP head
2019-01-28 22:08:59.463 +00:00 [INF] - Started MQTT head
2019-01-28 22:09:00.057 +00:00 [WRN] - Module iot-edge-pi/iot-stream-a is not connected
2019-01-28 22:09:00.075 +00:00 [INF] - Started AMQP head
2019-01-28 22:09:00.090 +00:00 [INF] - Starting HTTP head
2019-01-28 22:09:00.645 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2019-01-28 22:09:02.077 +00:00 [WRN] - Module iot-edge-pi/iot-stream-a is not connected
2019-01-28 22:09:02.929 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2019-01-28 22:09:03.067 +00:00 [INF] - Started HTTP head
2019-01-28 22:09:04.735 +00:00 [INF] - New token received on the Cbs link
2019-01-28 22:09:05.701 +00:00 [INF] - Client iot-edge-pi/tempSensor in device scope authenticated locally.
2019-01-28 22:09:05.761 +00:00 [INF] - New device connection for device iot-edge-pi/tempSensor
2019-01-28 22:09:05.937 +00:00 [INF] - Bind device proxy for device iot-edge-pi/tempSensor
2019-01-28 22:09:05.944 +00:00 [INF] - Initialized device listener in the AMQP protocol head for iot-edge-pi/tempSensor
2019-01-28 22:09:05.995 +00:00 [INF] - Opened link Events for iot-edge-pi/tempSensor
2019-01-28 22:09:06.001 +00:00 [WRN] - Module iot-edge-pi/iot-stream-a is not connected
2019-01-28 22:09:06.230 +00:00 [INF] - Client iot-edge-pi/iotedgestreamanalytics in device scope authenticated locally.
2019-01-28 22:09:06.238 +00:00 [INF] - Successfully generated identity for clientId iot-edge-pi/iotedgestreamanalytics and username iot-edge-pi/iot-edge-pi/iotedgestreamanalytics/?api-version=2018-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.18.1%20%28.NET%20Core%204.6.26515.07%3B%20Linux%204.14.79-v7%2B%20%231159%20SMP%20Sun%20Nov%204%2017%3A50%3A20%20GMT%202018%3B%20Arm%29
2019-01-28 22:09:06.262 +00:00 [INF] - ClientAuthenticated, iot-edge-pi/iotedgestreamanalytics, 0739b3b3
2019-01-28 22:09:06.464 +00:00 [INF] - Opened link MethodReceiving for iot-edge-pi/tempSensor
2019-01-28 22:09:06.492 +00:00 [INF] - Attempting to connect to IoT Hub for client iot-edge-pi/tempSensor via AMQP...
2019-01-28 22:09:06.678 +00:00 [INF] - New device connection for device iot-edge-pi/iotedgestreamanalytics
2019-01-28 22:09:06.685 +00:00 [INF] - Bind device proxy for device iot-edge-pi/iotedgestreamanalytics
2019-01-28 22:09:06.692 +00:00 [INF] - Cloud connection for iot-edge-pi/tempSensor is True
2019-01-28 22:09:06.692 +00:00 [INF] - Connection status for iot-edge-pi/tempSensor changed to ConnectionEstablished
2019-01-28 22:09:06.693 +00:00 [INF] - Binding message channel for device Id iot-edge-pi/iotedgestreamanalytics
2019-01-28 22:09:06.693 +00:00 [INF] - Created cloud proxy for client iot-edge-pi/tempSensor via AMQP, with client operation timeout 20 seconds.
2019-01-28 22:09:06.694 +00:00 [INF] - Initialized cloud proxy 43425a25-be61-4cf8-be89-1d558fec36c7 for iot-edge-pi/tempSensor
2019-01-28 22:09:06.695 +00:00 [INF] - Created cloud connection for client iot-edge-pi/tempSensor
2019-01-28 22:09:06.695 +00:00 [INF] - Processing subscription Methods for client iot-edge-pi/tempSensor.
2019-01-28 22:09:06.953 +00:00 [INF] - Opened link MethodSending for iot-edge-pi/tempSensor
2019-01-28 22:09:06.999 +00:00 [INF] - Attempting to connect to IoT Hub for client iot-edge-pi/iotedgestreamanalytics via AMQP...
2019-01-28 22:09:07.166 +00:00 [INF] - Processing subscription ModuleMessages for client iot-edge-pi/tempSensor.
2019-01-28 22:09:07.172 +00:00 [INF] - Opened link ModuleMessages for iot-edge-pi/tempSensor
2019-01-28 22:09:07.291 +00:00 [INF] - Cloud connection for iot-edge-pi/iotedgestreamanalytics is True
2019-01-28 22:09:07.293 +00:00 [INF] - Connection status for iot-edge-pi/iotedgestreamanalytics changed to ConnectionEstablished
2019-01-28 22:09:07.294 +00:00 [INF] - Created cloud proxy for client iot-edge-pi/iotedgestreamanalytics via AMQP, with client operation timeout 20 seconds.
2019-01-28 22:09:07.296 +00:00 [INF] - Initialized cloud proxy f9343b31-770a-40dc-82ce-25cd102b1aed for iot-edge-pi/iotedgestreamanalytics
2019-01-28 22:09:07.298 +00:00 [INF] - Created cloud connection for client iot-edge-pi/iotedgestreamanalytics
2019-01-28 22:09:07.299 +00:00 [INF] - Processing subscription TwinResponse for client iot-edge-pi/iotedgestreamanalytics.
2019-01-28 22:09:07.307 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iot-edge-pi/iotedgestreamanalytics.
2019-01-28 22:09:07.483 +00:00 [INF] - Processing subscription ModuleMessages for client iot-edge-pi/iotedgestreamanalytics.
2019-01-28 22:09:07.527 +00:00 [INF] - Set subscriptions from session state for iot-edge-pi/iotedgestreamanalytics
2019-01-28 22:09:08.528 +00:00 [WRN] - Non retryable exception occurred while sending message.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at DotNetty.Buffers.HeapArena.NewChunk(Int32 pageSize, Int32 maxOrder, Int32 pageShifts, Int32 chunkSize)
   at DotNetty.Buffers.PoolArena`1.AllocateNormal(PooledByteBuffer`1 buf, Int32 reqCapacity, Int32 normCapacity)
   at DotNetty.Buffers.PoolArena`1.Allocate(PoolThreadCache`1 cache, PooledByteBuffer`1 buf, Int32 reqCapacity)
   at DotNetty.Buffers.PooledByteBufferAllocator.NewHeapBuffer(Int32 initialCapacity, Int32 maxCapacity)
   at DotNetty.Buffers.AbstractByteBufferAllocator.Buffer(Int32 initialCapacity, Int32 maxCapacity)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ByteBufferConverter.ToByteBuffer(Byte[] bytes) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ByteBufferConverter.cs:line 39
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ProtocolGatewayMessageConverter.FromMessage(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.DeviceProxy.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs:line 73
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 256
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.<>c__DisplayClass5_2.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 98
2019-01-28 22:09:08.667 +00:00 [WRN] - Error sending messages to module iot-edge-pi/iotedgestreamanalytics
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at DotNetty.Buffers.HeapArena.NewChunk(Int32 pageSize, Int32 maxOrder, Int32 pageShifts, Int32 chunkSize)
   at DotNetty.Buffers.PoolArena`1.AllocateNormal(PooledByteBuffer`1 buf, Int32 reqCapacity, Int32 normCapacity)
   at DotNetty.Buffers.PoolArena`1.Allocate(PoolThreadCache`1 cache, PooledByteBuffer`1 buf, Int32 reqCapacity)
   at DotNetty.Buffers.PooledByteBufferAllocator.NewHeapBuffer(Int32 initialCapacity, Int32 maxCapacity)
   at DotNetty.Buffers.AbstractByteBufferAllocator.Buffer(Int32 initialCapacity, Int32 maxCapacity)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ByteBufferConverter.ToByteBuffer(Byte[] bytes) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ByteBufferConverter.cs:line 39
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ProtocolGatewayMessageConverter.FromMessage(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.DeviceProxy.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs:line 73
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 256
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.<>c__DisplayClass5_2.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 98
2019-01-28 22:09:09.889 +00:00 [INF] - Processing subscription TwinResponse for client iot-edge-pi/iotedgestreamanalytics.
2019-01-28 22:09:09.889 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iot-edge-pi/iotedgestreamanalytics.
2019-01-28 22:09:09.892 +00:00 [INF] - Processing subscription ModuleMessages for client iot-edge-pi/iotedgestreamanalytics.
2019-01-28 22:09:09.894 +00:00 [INF] - Set subscriptions from session state for iot-edge-pi/iotedgestreamanalytics
2019-01-28 22:09:13.560 +00:00 [WRN] - Non retryable exception occurred while sending message.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at DotNetty.Buffers.HeapArena.NewChunk(Int32 pageSize, Int32 maxOrder, Int32 pageShifts, Int32 chunkSize)
   at DotNetty.Buffers.PoolArena`1.AllocateNormal(PooledByteBuffer`1 buf, Int32 reqCapacity, Int32 normCapacity)
   at DotNetty.Buffers.PoolArena`1.Allocate(PoolThreadCache`1 cache, PooledByteBuffer`1 buf, Int32 reqCapacity)
   at DotNetty.Buffers.PooledByteBufferAllocator.NewHeapBuffer(Int32 initialCapacity, Int32 maxCapacity)
   at DotNetty.Buffers.AbstractByteBufferAllocator.Buffer(Int32 initialCapacity, Int32 maxCapacity)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ByteBufferConverter.ToByteBuffer(Byte[] bytes) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ByteBufferConverter.cs:line 39
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ProtocolGatewayMessageConverter.FromMessage(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.DeviceProxy.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs:line 73
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 256
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.<>c__DisplayClass5_2.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 98
2019-01-28 22:09:13.563 +00:00 [WRN] - Error sending messages to module iot-edge-pi/iotedgestreamanalytics
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at DotNetty.Buffers.HeapArena.NewChunk(Int32 pageSize, Int32 maxOrder, Int32 pageShifts, Int32 chunkSize)
   at DotNetty.Buffers.PoolArena`1.AllocateNormal(PooledByteBuffer`1 buf, Int32 reqCapacity, Int32 normCapacity)
   at DotNetty.Buffers.PoolArena`1.Allocate(PoolThreadCache`1 cache, PooledByteBuffer`1 buf, Int32 reqCapacity)
   at DotNetty.Buffers.PooledByteBufferAllocator.NewHeapBuffer(Int32 initialCapacity, Int32 maxCapacity)
   at DotNetty.Buffers.AbstractByteBufferAllocator.Buffer(Int32 initialCapacity, Int32 maxCapacity)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ByteBufferConverter.ToByteBuffer(Byte[] bytes) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ByteBufferConverter.cs:line 39
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ProtocolGatewayMessageConverter.FromMessage(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.DeviceProxy.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs:line 73
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 256
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.<>c__DisplayClass5_2.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 98
2019-01-28 22:09:13.625 +00:00 [WRN] - Module iot-edge-pi/iot-stream-a is not connected
2019-01-28 22:09:18.871 +00:00 [WRN] - Non retryable exception occurred while sending message.
[edgeHubLog.txt](https://github.com/Azure/iotedge/files/2805193/edgeHubLog.txt)

**Comment by myagley** [comment]
We are making the `OptimizeForPerformance=false` setting the default on arm32 platforms. This was just merged in #766 and will be in the `1.0.7` release

**Comment by myagley** [comment]
This has been released as part of the 1.0.7 release candidate. You can get the fix by using the following image for the Edge Hub. `mcr.microsoft.com/azureiotedge-hub:1.0.7-rc2`. This release will GA in a few weeks.
