### ISSUE TITLE
Custom module was closed without logging any error 

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#796]
On 2019-01-25  around 19:09 in one of our production installations our custom module DispatcherModule was stopped without logging any information.

In the Program.cs we subscribe into 
AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
            TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException1;

but nothing was logged that would indicate problem in DispatcherModule.

We collected logs from edgeAgent and edgeHub and DispatcherModule but we are not sure what went wrong.

In edgeHub there is some information that connetion was closed for DispatcherModule
2019-01-25 19:10:18.337 +00:00 [WRN] - Closing connection for device: itcarsu-ceccavi-01/DispatcherModule, Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed., 

In edgeAgent we saw plenty of repeating entries:

2019-01-25 19:04:06.528 +00:00 [WRN] - Updating reported properties failed with error Operation timeout expired. type System.TimeoutException
2019-01-25 19:04:11.553 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 159
2019-01-25 19:04:37.329 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutTwin>b__64_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.RefreshTwinAsync() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 144

but they were happening before module crashed/stopped or whatever happened with the module.

Detailed logs were attached.

[edge_logs.zip](https://github.com/Azure/iotedge/files/2827778/edge_logs.zip)

**Comment by myagley** [comment]
Hi Adam. I believe you are running into a bug that was fixed in https://github.com/Azure/iotedge/pull/684 This fix is in the `1.0.6` release.

@varunpuranik can you verify?

**Comment by AdamMachera** [comment]
Hi Mike,

we had updated the iotedge to version 1.0.6.
However our custom module is being killed from time to time.
In the edgeHub we still see exception:
**2019-02-22 06:56:52.887** +00:00 [WRN] - Closing connection for device: seoarsu-cecoatl-01/DispatcherModule, Microsoft.Azure.Devices.ProtocolGateway.ProtocolGatewayException: Channel closed.,

In the applicationinsights we received logs from ApplicationInsight module:
**2019-02-22T06:56:53.095Z**,"docker-container-die",customEvent,"{""docker-duration-days"":""0.9595470184606482"",""docker-status"":""die"",""docker-FinishedAt"":""2019-02-22T06:56:52.9068515Z"",""Docker image"":""ta01pmcpcr01.azurecr.io/dispatchermodule:1.0.0.43-prod"",""docker-StartedAt"":""2019-02-21T07:55:08.0444561Z"",""docker-duration-hours"":""23.029128443055555"",""Docker container name"":""/DispatcherModule"",""docker-Error"":"""",""Docker host"":""iotedgemodules"",""docker-ExitCode"":""139"",""docker-duration-minutes"":""1381.7477065833334"",""docker-RestartCount"":""0"",""docker-duration-seconds"":""82904.862395"",""Docker container id"":""828cade89784cd87fe71cc795df075fb85a4d7da925e787d7d8d4a9d474eeb54"",""docker-Created"":""2019-02-07T13:03:31.1016958Z""}",null,"docker-container-die",828cade89784cd87fe71cc795df075fb85a4d7da925e787d7d8d4a9d474eeb54,828cade89784cd87fe71cc795df075fb85a4d7da925e787d7d8d4a9d474eeb54,,,,,,,PC,Other,Linux,"0.0.0.0",,,Sweden,"Apache-HttpClient 4.3",,,"64b31a9d-3e14-4986-9383-f89326d6ddd0",ta01pmcpai01,"49a12914-bbaa-4585-8dd0-b29a63bb46cc","Java 1.0.3","0c120c90-366f-11e9-ada7-1b660b1c6923",1

So the module is killed couple of milliseconds once this exception was raised.

**Comment by myagley** [comment]
The IoT Edge runtime won't actively kill your container unless a restart is requested, which I doubt is the case here. This must be being killed by docker. Is it possible the system is running out of memory and is being reaped by the out of memory killer?

**Comment by AdamMachera** [comment]
We will have to check this.

**Comment by ancaantochi** [comment]
Closing because no activity. Please reopen if you still have this issue.
