### ISSUE TITLE
EdgeHub module crashes with "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by markphillips100** [Azure/iotedge#843]
## Expected Behavior
EdgeHub module should not crash when online.

## Current Behavior
EdgeHub operates normally for anywhere between 30 minutes and 1.5 hours and then terminates with the following error:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```
The edge hub repeats this cycle of running fine for anywhere between 30 minutes and 1.5 hours and errors again.  After 10 or so cycles of this an `OutOfMemoryException` occurred:
```
[ERR] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MqttProtocolHead] - Failed to start MQTT server "System.InvalidOperationException: failed to create a child event loop. ---> System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
```
From this point on it appears no messages are sent to the cloud.  And there are further exceptions indicating connectivity issues, even though the network has not disconnected:
```
[WRN] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager] - Error calling IotHub for connectivity test
System.Exception: request 8fc90e16-92e8-43b7-84ab-fb4e0b514c55 returned status 400
```

The analytics module also logs the following on occasion:
```
[ERR] [Microsoft.Streaming.Diagnostics.Tracing.FLog] - Exception: Microsoft.Streaming.Diagnostics.Exceptions.FrameworkException
Message: An error occurred while sending data to Edge Hub.  The following information could be helpful in diagnosing the EdgeHub issue: failed to flush events. Operation timeout expired.  Operation timeout expired.
```

## Steps to Reproduce
1. Built and deployed configuration as defined in Additional Information section.
2. Watch (-f) edgeHub logs through PuTTy from Windows 10 on same network.
3. Wait from logs to stop following due to process termination.

## Context (Environment)
Raspbian PI 3 B+, 16Gb SD card, Ethernet connected to Internet via Internet Service Provider.

### Device (Host) Operating System
Raspbian Stretch (Lite)

### Architecture
arm32

### Container Operating System
Linux containers

#### iotedged

1.0.6.1

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 17:16:17 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       74baf62
  Built:            Tue Dec  4 23:30:17 2018
  OS/Arch:          linux/arm
  Experimental:     false

## Additional Information
To support memory stats via `sudo docker stats` I enabled cgroup_memory in the file /boot/cmdline.txt: `dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p7 rootfstype=ext4 cgroup_enable=memory cgroup_memory=1 elevator=deadline fsck.repair=yes rootwait`

Modified `/etc/iotedge/config.yaml` with the following to enable debug and MQTT only upstream protocol (to allow edgeAgent on first startup to use MQTT):
```
agent:
  name: "edgeAgent"
  type: "docker"
  env:
    RuntimeLogLevel: debug
    UpstreamProtocol: "Mqtt"
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}
```
### Modules used in testing
I duplicated the simulated temperature sensor code from the IoT Edge repo to create my own C# module.  Functionality identical except for an extra desired property to give a SensorId in produced messages, and an additional property to indicate the type of message, i.e. TemperatorSensor in this case.  I run 2 of these modules producing an event each every 5 seconds.  Both route messages upstream and also to a stream analytics module.

The stream analytics uses the following query to average the sensor averages:
```
-- First query produces event every 5 seconds with the average machine temperature per sensor
WITH SamplingData AS
(
SELECT sensorId, Avg(machine.temperature) as averageTemperature
FROM temperature TIMESTAMP BY timeCreated
GROUP BY sensorId, HoppingWindow(second, 30, 5)
)

-- Final query outputs an event that contains the average of all sensor temperature averages
SELECT 
    Avg(averageTemperature) OVER () as totalAverageTemperature,
    System.Timestamp as timeCreated
INTO
    result
FROM SamplingData
GROUP BY HoppingWindow(second, 15, 5)
```

I route the analytics events upstream and also to another C# module that simply formats a new message  with a similar schema to that output by the temp sensor modules, and then this is routed upstream.  I have a simple webapp (the nodejs app from the tutorials) that reads both the temp sensor events and the formatted analytics events to render nice plots over time.

The system modules are configured as follows.  Note `OptimizeForPerformance` is `false`, `AMQP` is `disabled` and `UpstreamProtocol` is `MQTT`:
```
"systemModules": {
          "edgeAgent": {
            "type": "docker",
            "env": {
              "UpstreamProtocol": {
                "value": "MQTT"
              }
            },
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "env": {
              "amqpSettings__enabled": {
                "value": false
              },
              "mqttSettings__enabled": {
                "value": true
              },
              "httpSettings__enabled": {
                "value": true
              },
              "OptimizeForPerformance": {
                "value": "false"
              },
              "UpstreamProtocol": {
                "value": "MQTT"
              }
            },
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
```

### Memory usage
I've run `sudo docker stats` during the test and can see the following:
tempSensorModules: ~10Mb each (C# custom)
analyticsModule: ~40Mb (stream analytics)
messageFormatterModule: ~10Mb (C# custom)
edgeAgent: ~22Mb
edgeHub: ~40Mb climbing to 65Mb+

**Comment by markphillips100** [comment]
I've also tried swapping to AMQP for everything, which includes;
1. disabling the MQTT protocol head in the edge hub environment variables, 
2. switching the 3 custom modules to use AMQP_With_TCP, 
3. changing the UpstreamProtocol for both agent and hub to AMQP, and
4. changing the config.yaml UpstreamProtocol to AMQP.
NOTE: I don't know how to change the ASA module to just use AMQP, or even if it can be set for only this protocol.

The result of this is that the ASA module fails to initialize its module client so I suspect it doesn't automatically try AMQP if MQTT fails:
```
2019-02-14 06:18:41.712 +00:00 [INF] - Module client initializing ...
2019-02-14 06:19:41.985 +00:00 [WRN] - Exception thrown during job status report: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Streaming.Runtime.Container.Edge.EdgeJobStatusManager.<>c__DisplayClass32_0.<<ReportJobStatus>b__0>d.MoveNext() in M:\FXAGENT-006\_work\5\s\Product\Source\DotNetCore\Container.Edge\EdgeJobStatusManager.cs:line 152; InnerException:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Streaming.Runtime.Container.Edge.EdgeJobStatusManager.<>c__DisplayClass32_0.<<ReportJobStatus>b__0>d.MoveNext() in M:\FXAGENT-006\_work\5\s\Product\Source\DotNetCore\Container.Edge\EdgeJobStatusManager.cs:line 152
2019-02-14 06:22:44.204 +00:00 [INF] - Module client initializing ...
2019-02-14 06:26:50.833 +00:00 [INF] - Module client initializing ...
```

**Comment by markphillips100** [comment]
So just made a guess that the ASA module may have been written using similar/same code as the temp sensor so specified the following for environment variable and now it at least initializes:

```
"env": {
  "PlanId": {
    "value": "stream-analytics-on-iot-edge"
  },
  "ClientTransportType": {
    "value": "3"
  }
}
```

**Comment by markphillips100** [comment]
And after running with just AMQP everywhere everything is fine up until an hour in when a NullReferenceException occurs.  The cloud proxy seems to recover but a null reference worries me.  I'll let the test run overnight and see what happens.

EdgeHub log (no exception reported in ASA module log):
```
2019-02-14 07:30:04.539 +00:00 [INF] - Closing receiver in cloud proxy 8445c381-4f22-4890-bb98-7e5e50c17653 for mark-pi/rexiotTemperatureJob
2019-02-14 07:30:04.540 +00:00 [INF] - Closed cloud proxy 8445c381-4f22-4890-bb98-7e5e50c17653 for mark-pi/rexiotTemperatureJob
2019-02-14 07:30:04.549 +00:00 [WRN] - Error disposing message in ModuleMessages link for mark-pi/rexiotTemperatureJob
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__61_1(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 134
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SendFeedbackMessageAsync(String messageId, FeedbackStatus feedbackStatus) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 185
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SendFeedbackMessageAsync(String messageId, FeedbackStatus feedbackStatus) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 204
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.ProcessMessageFeedbackAsync(String messageId, FeedbackStatus feedbackStatus) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 109
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler.DisposeMessageAsync(Delivery delivery) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/SendingLinkHandler.cs:line 132
2019-02-14 07:30:09.525 +00:00 [INF] - Attempting to connect to IoT Hub for client mark-pi/rexiotTemperatureJob via AMQP...
2019-02-14 07:30:09.673 +00:00 [INF] - Cloud connection for mark-pi/rexiotTemperatureJob is True
2019-02-14 07:30:09.675 +00:00 [INF] - Connection status for mark-pi/rexiotTemperatureJob changed to ConnectionEstablished
2019-02-14 07:30:09.677 +00:00 [INF] - Created cloud proxy for client mark-pi/rexiotTemperatureJob via AMQP, with client operation timeout 20 seconds.

```

**Comment by markphillips100** [comment]
Just an update.  EdgeHub module is still running after 15+ hours, without termination.  So going to only use AMQP from here as it "appears" there's an issue with MQTT and/or the ASA module using it.

Looking at the edgehub logs, the NullReferenceException posted above occurred a few more times.

**Comment by lt72** [comment]
Closing issues as it seems stale. please feel free to re-open as needed.
