### ISSUE TITLE
IotEdge fails with : Attempting to connect to IoT Hub for client mydevice/$edgeHub via AMQP...

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#853]
Hi all,

I have setup a fresh iotedge with two modules. Both modules receive messages correctly. Unfortunately edghub fails to connect to cloud.
`Attempting to connect to IoT Hub for client mydevice/$edgeHub via AMQP...`

It looks like networking issue, but it is not. I have created a small console application with the same connection string, which send data to some device. It works well.

See error below: 
```
## Context (Environment)

### Device (Host) Operating System
<!-- Windows 10 -->

### Architecture
<!-- x64 -->

### Container Operating SystemLinux containers

### Runtime Versions
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)


#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
Docker version 18.09.2, build 6247962

## Logs

> 
> Attempting to connect to IoT Hub for client mydevice/$edgeHub via AMQP...
> 2019-02-19 11:19:12.419 +00:00 [WRN] - Error creating cloud connection for client basta/$edgeHub
> System.TimeoutException: Operation timeout expired.
>    at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ModuleClientWrapper.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs:line 48
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass28_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 174
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 134
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(ITokenProvider newTokenProvider) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 126
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateNewCloudProxyAsync(ITokenProvider newTokenProvider) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 97
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.Create(IIdentity identity, Action`2 connectionStatusChangedHandler, ITransportSettings[] transportSettings, IMessageConverterProvider messageConverterProvider, IClientProvider clientProvider, ICloudListener cloudListener, ITokenProvider tokenProvider, TimeSpan idleTimeout, Boolean closeOnIdleTimeout, TimeSpan operationTimeout) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 86
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.<>c__DisplayClass15_1.<<Connect>b__2>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 134
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.Connect(IIdentity identity, Action`2 connectionStatusChangedHandler) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 129
> 2019-02-19 11:19:12.430 +00:00 [INF] - Error getting cloud connection for device basta/$edgeHub
> System.TimeoutException: Operation timeout expired.

**Comment by myagley** [comment]
Thank you for the issue. This is most likely a firewall issue and can be verified by running the following command on the host machine:

`docker exec -it edgeHub nc -vz <your iot hub>.azure-devices.net 5671`

This command attempts to make a connection to your IoT Hub from within the same networking context as the Edge Hub. It should return "open" if successful.

Please note that Linux containers on Windows is **not** a [supported scenario](https://docs.microsoft.com/en-us/azure/iot-edge/support). We do not test this configuration and it's possible that there has been a change here.

Also note that the networking setup when running linux containers on windows is especially complex. The container is running inside of a VM on a bridge network. This setup is explained in [IoT Edge networking](https://github.com/Azure/iotedge/blob/master/doc/networking.md).

**Comment by ddobric** [comment]
Thanks for your quick response Mike. You are right, the issue is related to firewall or better to say to infrastructure. 
All code which uses Mqtt (probably AMQP too - didn't test) works fine. I can send commands to devices invoke methods etc.
However all code which uses websockets (i.e.: Amqp_WebSocket_Only) does not work. Because edgeHub uses websocket connection to communicated tit iothub, my gateway in iotedge does not work.

My question is how to change the protocol of the edgeHub? Event better, where is edgeHub configuration at all?

Thanks
Damir

**Comment by myagley** [comment]
The Edge Hub should be defaulting to AMQP. I believe it will attempt to fallback to websockets if the connection fails.

Most of the Edge Hub configuration happens through setting environment variables. You can change the upstream protocol by setting the `UpstreamProtocol` environment variable, described here: https://github.com/Azure/iotedge/blob/master/doc/networking.md#upstream-protocol

**Comment by ddobric** [comment]
Hi Mike,

I have tried to set environment variable 'UpstreamProtocol'. Unfortunately, it seems not to be deployed.
 
![image](https://user-images.githubusercontent.com/1756871/53276048-ca4a3f00-36fd-11e9-8226-bebfb7a7f080.png)

Here is docker inspect of a running container:

>  "Env": [
>                 "IOTEDGE_MODULEID=mymodule",
>                 "IOTEDGE_DEVICEID=mydevice",
>                 "IOTEDGE_APIVERSION=2018-06-28",
>                 "IOTEDGE_IOTHUBHOSTNAME=daenet-iothub.azure-devices.net",
>                 "IOTEDGE_MODULEGENERATIONID=636861597680727646",
>                 "IOTEDGE_GATEWAYHOSTNAME=dado-sr1",
>                 "RuntimeLogLevel=Information",
>                 "IOTEDGE_WORKLOADURI=http://10.0.75.1:15581/",
>                 "IOTEDGE_AUTHSCHEME=sasToken",
>                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>                 "ASPNETCORE_URLS=http://+:80",
>                 "DOTNET_RUNNING_IN_CONTAINER=true",
>                 "DOTNET_VERSION=2.1.8"
>             ],

Using: iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
Current version of runtime is not stable. There too many issues, which are mostly already commented in issue list.  Is there some newer RC/BETA version in the meantime?

**Comment by myagley** [comment]
Can we see the logs for the Edge Agent? The issues you are seeing are all related to network connectivity to the IoT Hub. It is entirely plausible that this connectivity is preventing the deployment from occurring. We can verify this by looking at the Edge Agent logs

`iotedge logs edgeAgent > edge-agent.log` and send the `edge-agent.log` file in the current directory.

**Comment by ddobric** [comment]
## EDGE AGENT
```
2019-02-26 08:22:41.024 +00:00 [INF] - Version - 1.0.6.19913336 (8288bc9bd6f6e15295fea506cd3f99d7f6347a6a)
2019-02-26 08:22:41.024 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2019-02-26 08:22:41.154 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
2019-02-26 08:22:41.877 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2019-02-26 08:22:42.771 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
2019-02-26 08:22:43.336 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 10s (04s left).
2019-02-26 08:22:43.358 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:22:43.366 +00:00 [INF] - Executing command: "Command Group: (
  [Stop module tempsensor]
  [Start module tempsensor]
  [Saving tempsensor to store]
)"
2019-02-26 08:22:43.368 +00:00 [INF] - Executing command: "Stop module tempsensor"
2019-02-26 08:22:43.409 +00:00 [INF] - Executing command: "Start module tempsensor"
2019-02-26 08:22:44.334 +00:00 [INF] - Executing command: "Saving tempsensor to store"
2019-02-26 08:22:44.353 +00:00 [INF] - Executing command: "Command Group: (
  [Stop module mymodule]
  [Start module mymodule]
  [Saving mymodule to store]
)"
2019-02-26 08:22:44.353 +00:00 [INF] - Executing command: "Stop module mymodule"
2019-02-26 08:22:44.369 +00:00 [INF] - Executing command: "Start module mymodule"
2019-02-26 08:22:45.252 +00:00 [INF] - Executing command: "Saving mymodule to store"
2019-02-26 08:22:45.254 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:22:45.585 +00:00 [INF] - Updated reported properties
2019-02-26 08:22:50.633 +00:00 [INF] - Module 'mymodule' scheduled to restart after 20s (15s left).
2019-02-26 08:22:50.642 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:22:50.642 +00:00 [INF] - Executing command: "Command Group: (
  [Stop module edgeHub]
  [Start module edgeHub]
  [Saving edgeHub to store]
)"
2019-02-26 08:22:50.642 +00:00 [INF] - Executing command: "Stop module edgeHub"
2019-02-26 08:22:50.649 +00:00 [INF] - Executing command: "Start module edgeHub"
2019-02-26 08:22:52.227 +00:00 [INF] - Executing command: "Saving edgeHub to store"
2019-02-26 08:22:52.228 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:22:52.441 +00:00 [INF] - Updated reported properties
2019-02-26 08:22:57.456 +00:00 [INF] - Module 'mymodule' scheduled to restart after 20s (08s left).
2019-02-26 08:22:57.654 +00:00 [INF] - Updated reported properties
2019-02-26 08:23:02.676 +00:00 [INF] - Module 'mymodule' scheduled to restart after 20s (03s left).
2019-02-26 08:23:07.708 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:23:07.708 +00:00 [INF] - Executing command: "Command Group: (
  [Stop module mymodule]
  [Start module mymodule]
  [Saving mymodule to store]
)"
2019-02-26 08:23:07.710 +00:00 [INF] - Executing command: "Stop module mymodule"
2019-02-26 08:23:07.720 +00:00 [INF] - Executing command: "Start module mymodule"
2019-02-26 08:23:08.639 +00:00 [INF] - Executing command: "Saving mymodule to store"
2019-02-26 08:23:08.640 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:23:13.875 +00:00 [INF] - Updated reported properties
2019-02-26 08:32:32.430 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'tempsensor' as it has been running healthy for 00:10:00.
2019-02-26 08:32:32.431 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:32:32.432 +00:00 [INF] - Executing command: "Saving tempsensor to store"
2019-02-26 08:32:32.437 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:32:37.636 +00:00 [INF] - Updated reported properties
2019-02-26 08:32:42.667 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'edgeHub' as it has been running healthy for 00:10:00.
2019-02-26 08:32:42.668 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:32:42.668 +00:00 [INF] - Executing command: "Saving edgeHub to store"
2019-02-26 08:32:42.668 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:32:47.712 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'mymodule' as it has been running healthy for 00:10:00.
2019-02-26 08:32:47.712 +00:00 [INF] - Plan execution started for deployment 15
```




## EDGE HUB
```

2019-02-26 08:22:44.353 +00:00 [INF] - Executing command: "Stop module mymodule"
2019-02-26 08:22:44.369 +00:00 [INF] - Executing command: "Start module mymodule"
2019-02-26 08:22:45.252 +00:00 [INF] - Executing command: "Saving mymodule to store"
2019-02-26 08:22:45.254 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:22:45.585 +00:00 [INF] - Updated reported properties
2019-02-26 08:22:50.633 +00:00 [INF] - Module 'mymodule' scheduled to restart after 20s (15s left).
2019-02-26 08:22:50.642 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:22:50.642 +00:00 [INF] - Executing command: "Command Group: (
  [Stop module edgeHub]
  [Start module edgeHub]
  [Saving edgeHub to store]
)"
2019-02-26 08:22:50.642 +00:00 [INF] - Executing command: "Stop module edgeHub"
2019-02-26 08:22:50.649 +00:00 [INF] - Executing command: "Start module edgeHub"
2019-02-26 08:22:52.227 +00:00 [INF] - Executing command: "Saving edgeHub to store"
2019-02-26 08:22:52.228 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:22:52.441 +00:00 [INF] - Updated reported properties
2019-02-26 08:22:57.456 +00:00 [INF] - Module 'mymodule' scheduled to restart after 20s (08s left).
2019-02-26 08:22:57.654 +00:00 [INF] - Updated reported properties
2019-02-26 08:23:02.676 +00:00 [INF] - Module 'mymodule' scheduled to restart after 20s (03s left).
2019-02-26 08:23:07.708 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:23:07.708 +00:00 [INF] - Executing command: "Command Group: (
  [Stop module mymodule]
  [Start module mymodule]
  [Saving mymodule to store]
)"
2019-02-26 08:23:07.710 +00:00 [INF] - Executing command: "Stop module mymodule"
2019-02-26 08:23:07.720 +00:00 [INF] - Executing command: "Start module mymodule"
2019-02-26 08:23:08.639 +00:00 [INF] - Executing command: "Saving mymodule to store"
2019-02-26 08:23:08.640 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:23:13.875 +00:00 [INF] - Updated reported properties
2019-02-26 08:32:32.430 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'tempsensor' as it has been running healthy for 00:10:00.
2019-02-26 08:32:32.431 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:32:32.432 +00:00 [INF] - Executing command: "Saving tempsensor to store"
2019-02-26 08:32:32.437 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:32:37.636 +00:00 [INF] - Updated reported properties
2019-02-26 08:32:42.667 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'edgeHub' as it has been running healthy for 00:10:00.
2019-02-26 08:32:42.668 +00:00 [INF] - Plan execution started for deployment 15
2019-02-26 08:32:42.668 +00:00 [INF] - Executing command: "Saving edgeHub to store"
2019-02-26 08:32:42.668 +00:00 [INF] - Plan execution ended for deployment 15
2019-02-26 08:32:47.712 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'mymodule' as it has been running healthy for 00:10:00.
2019-02-26 08:32:47.712 +00:00 [INF] - Plan execution started for deployment 15
PS C:\WINDOWS\system32> iotedge logs -f edgeHub --tail 100
2019-02-26 08:22:58.528 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2019-02-26 08:22:58.531 +00:00 [INF] - Starting MQTT head
2019-02-26 08:22:58.588 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2019-02-26 08:22:58.613 +00:00 [INF] - Started MQTT head
2019-02-26 08:22:58.617 +00:00 [INF] - Starting AMQP head
2019-02-26 08:22:58.705 +00:00 [INF] - Started AMQP head
2019-02-26 08:22:58.708 +00:00 [INF] - Starting HTTP head
2019-02-26 08:22:58.793 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2019-02-26 08:22:59.070 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2019-02-26 08:22:59.094 +00:00 [INF] - Started HTTP head
2019-02-26 08:23:01.844 +00:00 [INF] - New token received on the Cbs link
2019-02-26 08:23:02.028 +00:00 [INF] - Client mydevice/tempsensor in device scope authenticated locally.
2019-02-26 08:23:02.037 +00:00 [INF] - New device connection for device mydevice/tempsensor
2019-02-26 08:23:02.047 +00:00 [INF] - Bind device proxy for device mydevice/tempsensor
2019-02-26 08:23:02.048 +00:00 [INF] - Initialized device listener in the AMQP protocol head for mydevice/tempsensor
2019-02-26 08:23:02.055 +00:00 [INF] - Opened link Events for mydevice/tempsensor
2019-02-26 08:23:02.133 +00:00 [INF] - Opened link MethodReceiving for mydevice/tempsensor
2019-02-26 08:23:02.137 +00:00 [INF] - Attempting to connect to IoT Hub for client mydevice/tempsensor via MQTT...
2019-02-26 08:23:03.159 +00:00 [INF] - Cloud connection for mydevice/tempsensor is True
2019-02-26 08:23:03.159 +00:00 [INF] - Connection status for mydevice/tempsensor changed to ConnectionEstablished
2019-02-26 08:23:03.159 +00:00 [INF] - Created cloud proxy for client mydevice/tempsensor via MQTT, with client operation timeout 20 seconds.
2019-02-26 08:23:03.159 +00:00 [INF] - Initialized cloud proxy 40d90f57-2437-4991-a760-9a52dbec0092 for mydevice/tempsensor
2019-02-26 08:23:03.159 +00:00 [INF] - Created cloud connection for client mydevice/tempsensor
2019-02-26 08:23:03.159 +00:00 [INF] - Processing subscription Methods for client mydevice/tempsensor.
2019-02-26 08:23:03.261 +00:00 [INF] - Opened link MethodSending for mydevice/tempsensor
2019-02-26 08:23:03.289 +00:00 [INF] - Processing subscription ModuleMessages for client mydevice/tempsensor.
2019-02-26 08:23:03.290 +00:00 [INF] - Opened link ModuleMessages for mydevice/tempsensor
2019-02-26 08:23:03.545 +00:00 [WRN] - Module mydevice/mymodule is not connected
2019-02-26 08:23:04.555 +00:00 [WRN] - Module mydevice/mymodule is not connected
2019-02-26 08:23:06.385 +00:00 [WRN] - Module mydevice/mymodule is not connected
2019-02-26 08:23:09.578 +00:00 [INF] - Client mydevice/mymodule in device scope authenticated locally.
2019-02-26 08:23:09.579 +00:00 [INF] - Successfully generated identity for clientId mydevice/mymodule and username dado-sr1/mydevice/mymodule/?api-version=2018-06-30&DeviceClientType=.NET%2F1.19.0%20%28.NET%20Core%204.6.27317.03%3B%20Linux%204.9.125-linuxkit%20%231%20SMP%20Fri%20Sep%207%2008%3A20%3A28%20UTC%202018%3B%20X64%29
2019-02-26 08:23:09.581 +00:00 [INF] - ClientAuthenticated, mydevice/mymodule, 29d05add
2019-02-26 08:23:09.606 +00:00 [INF] - New device connection for device mydevice/mymodule
2019-02-26 08:23:09.607 +00:00 [INF] - Bind device proxy for device mydevice/mymodule
2019-02-26 08:23:09.608 +00:00 [INF] - Binding message channel for device Id mydevice/mymodule
2019-02-26 08:23:09.658 +00:00 [INF] - Attempting to connect to IoT Hub for client mydevice/mymodule via MQTT...
2019-02-26 08:23:09.938 +00:00 [INF] - Cloud connection for mydevice/mymodule is True
2019-02-26 08:23:09.938 +00:00 [INF] - Connection status for mydevice/mymodule changed to ConnectionEstablished
2019-02-26 08:23:09.938 +00:00 [INF] - Created cloud proxy for client mydevice/mymodule via MQTT, with client operation timeout 20 seconds.
2019-02-26 08:23:09.938 +00:00 [INF] - Initialized cloud proxy 4c46a94c-e3e3-4edf-9c0a-dbe55f3051dd for mydevice/mymodule
2019-02-26 08:23:09.938 +00:00 [INF] - Created cloud connection for client mydevice/mymodule
2019-02-26 08:23:09.938 +00:00 [INF] - Processing subscription TwinResponse for client mydevice/mymodule.
2019-02-26 08:23:09.940 +00:00 [INF] - Processing subscription ModuleMessages for client mydevice/mymodule.
2019-02-26 08:23:09.946 +00:00 [INF] - Set subscriptions from session state for mydevice/mymodule
2019-02-26 08:23:09.990 +00:00 [INF] - Processing subscription TwinResponse for client mydevice/mymodule.
2019-02-26 08:23:09.990 +00:00 [INF] - Processing subscription ModuleMessages for client mydevice/mymodule.
2019-02-26 08:23:09.990 +00:00 [INF] - Set subscriptions from session state for mydevice/mymodule
2019-02-26 08:27:58.428 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 08:29:11.680 +00:00 [INF] - Exiting connected state
2019-02-26 08:29:11.681 +00:00 [INF] - Entering unreachable state
2019-02-26 08:29:11.879 +00:00 [INF] - Entering connected state
2019-02-26 08:32:58.427 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 08:37:58.413 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 08:42:58.415 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 08:47:58.424 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 08:52:54.299 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2019-02-26 08:52:54.409 +00:00 [INF] - Cleaned up 381 messages from queue for endpoint iothub and 381 messages from message store.
2019-02-26 08:52:58.416 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 08:53:24.415 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint mydevice/mymodule/input1
2019-02-26 08:53:24.515 +00:00 [INF] - Cleaned up 382 messages from queue for endpoint mydevice/mymodule/input1 and 382 messages from message store.
2019-02-26 08:57:58.414 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:02:58.423 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:07:58.416 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:12:58.417 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:17:58.425 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:21:02.014 +00:00 [INF] - New token received on the Cbs link
2019-02-26 09:21:02.015 +00:00 [INF] - Token updated for mydevice/tempsensor
2019-02-26 09:22:55.337 +00:00 [INF] - Starting refresh of device scope identities cache
2019-02-26 09:22:58.422 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:23:54.524 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2019-02-26 09:23:54.570 +00:00 [INF] - Cleaned up 145 messages from queue for endpoint iothub and 145 messages from message store.
2019-02-26 09:24:24.565 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint mydevice/mymodule/input1
2019-02-26 09:24:24.589 +00:00 [INF] - Cleaned up 138 messages from queue for endpoint mydevice/mymodule/input1 and 138 messages from message store.
2019-02-26 09:27:58.415 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:32:58.419 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:32:58.421 +00:00 [INF] - Error authenticating token for mydevice/mymodule because the token is expired or could not be parsed
2019-02-26 09:32:58.422 +00:00 [INF] - Credentials for client mydevice/mymodule are not valid.
2019-02-26 09:32:58.422 +00:00 [WRN] - Reauthenticating client mydevice/mymodule failed, removing client connection
2019-02-26 09:32:58.422 +00:00 [INF] - Unable to re-authenticate mydevice/mymodule, dropping client connection.
2019-02-26 09:32:58.429 +00:00 [WRN] - Closing connection for device: mydevice/mymodule, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device mydevice/mymodule.,
2019-02-26 09:32:58.430 +00:00 [INF] - Disposing MessagingServiceClient for device Id mydevice/mymodule because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device mydevice/mymodule.
2019-02-26 09:32:58.442 +00:00 [INF] - Closing device proxy for device Id mydevice/mymodule
2019-02-26 09:32:58.442 +00:00 [INF] - Device connection removed for device mydevice/mymodule
2019-02-26 09:32:58.520 +00:00 [INF] - Client mydevice/mymodule in device scope authenticated locally.
2019-02-26 09:32:58.520 +00:00 [INF] - Successfully generated identity for clientId mydevice/mymodule and username dado-sr1/mydevice/mymodule/?api-version=2018-06-30&DeviceClientType=.NET%2F1.19.0%20%28.NET%20Core%204.6.27317.03%3B%20Linux%204.9.125-linuxkit%20%231%20SMP%20Fri%20Sep%207%2008%3A20%3A28%20UTC%202018%3B%20X64%29
2019-02-26 09:32:58.520 +00:00 [INF] - ClientAuthenticated, mydevice/mymodule, 223497de
2019-02-26 09:32:58.521 +00:00 [INF] - New device connection for device mydevice/mymodule
2019-02-26 09:32:58.522 +00:00 [INF] - Bind device proxy for device mydevice/mymodule
2019-02-26 09:32:58.522 +00:00 [INF] - Binding message channel for device Id mydevice/mymodule
2019-02-26 09:32:58.523 +00:00 [INF] - Processing subscription TwinResponse for client mydevice/mymodule.
2019-02-26 09:32:58.523 +00:00 [INF] - Processing subscription ModuleMessages for client mydevice/mymodule.
2019-02-26 09:32:58.524 +00:00 [INF] - Set subscriptions from session state for mydevice/mymodule
2019-02-26 09:32:58.527 +00:00 [INF] - Processing subscription TwinResponse for client mydevice/mymodule.
2019-02-26 09:32:58.527 +00:00 [INF] - Processing subscription ModuleMessages for client mydevice/mymodule.
2019-02-26 09:32:58.527 +00:00 [INF] - Set subscriptions from session state for mydevice/mymodule
2019-02-26 09:37:58.423 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:42:58.429 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:47:58.414 +00:00 [INF] - Reauthenticating connected clients
2019-02-26 09:52:58.424 +00:00 [INF] - Reauthenticating connected clients

```

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
