### ISSUE TITLE
EdgeletCommunicationException - edgehub - Error starting userland proxy

### ISSUE THREAD

**Issue by gverstraete** [Azure/iotedge#856]
## Expected Behavior
So I'm trying to run the default [quickstart](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart) in order to extend it later with my own custom module.

I just want to make this work at this stage

## Current Behavior
Instead of the expected behavior I get following exception:
````
2019-02-19 13:23:08.151 +00:00 [WRN] - Reconcile failed because of the an exception
System.AggregateException: One or more errors occurred. (Error calling start module edgeHub: Could not start module edgeHub
        caused by: Could not start module edgeHub
        caused by: driver failed programming external connectivity on endpoint edgeHub (f7fa34a4e1c371ddf38e187f0f251b97c6dc2c0f846b91ad11c0e0669939ebff): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8883:tcp:172.18.0.3:8883: input/output error) ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException: Error calling start module edgeHub: Could not start module edgeHub
        caused by: Could not start module edgeHub
        caused by: driver failed programming external connectivity on endpoint edgeHub (f7fa34a4e1c371ddf38e187f0f251b97c6dc2c0f846b91ad11c0e0669939ebff): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8883:tcp:172.18.0.3:8883: input/output error
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 205
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 144
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 87
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 115
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 116
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 132
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 143
---> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module edgeHub: Could not start module edgeHub
        caused by: Could not start module edgeHub
        caused by: driver failed programming external connectivity on endpoint edgeHub (f7fa34a4e1c371ddf38e187f0f251b97c6dc2c0f846b91ad11c0e0669939ebff): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8883:tcp:172.18.0.3:8883: input/output error, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 205
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 144
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 87<---
````

## Steps to Reproduce
1. I followed the quickstart, but with Linux containers as windows containers only starts the edgeAgent process.

### Device (Host) Operating System
Windows 10 Enterprise Build 1809

### Architecture
amd64

### Container Operating System
Linux

#### iotedged
iotedge 1.0.6.1

#### Edge Agent
 mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
Docker Desktop 2.0.0.3

## Additional Information
Could you tell me what the problem is I am facing? Thank you!

**Comment by fgheysels** [comment]
Can you try using mcr.microsoft.com/azureiotedge-hub:1.0.6 instead of mcr.microsoft.com/azureiotedge-hub:1.0 ?

**Comment by gverstraete** [comment]
After trying this I still get the same exception on `iotedge loge edgeAgent`

**Comment by gverstraete** [comment]
Fixed it.. Had an issue with my docker network. after removing  with "docker network prune" and restart of machine it was resolved..
