### ISSUE TITLE
Edge Module is not working on Windows Container with 443 port

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#868]
Edge Module is not working on Windows Container with 443 port

2019-02-21 06:44:01.494 +00:00 [INF] - sensorToLargeTwinReadModule: FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO B
rokeredEndpoint("/modules/LargeTwinReadModule/inputs/input1")
2019-02-21 06:44:01.495 +00:00 [INF] - Updated message store TTL to 7200 seconds
2019-02-21 06:44:01.495 +00:00 [INF] - Updated the edge hub store and forward configuration
2019-02-21 06:46:31.384 +00:00 [INF] - Reauthenticating connected clients
2019-02-21 06:50:36.308 +00:00 [INF] - Obtained edge hub config patch update from module twin
2019-02-21 06:50:36.437 +00:00 [INF] - Updating edge hub configuration
2019-02-21 06:50:36.439 +00:00 [INF] - Set the following 2 route(s) in edge hub
2019-02-21 06:50:36.439 +00:00 [INF] - LargeTwinReadModuleToIoTHub: FROM /messages/modules/porttesting/outputs/* INTO $upstream
2019-02-21 06:50:36.439 +00:00 [INF] - sensorToLargeTwinReadModule: FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO B
rokeredEndpoint("/modules/LargeTwinReadModule/inputs/input1")
2019-02-21 06:50:36.439 +00:00 [INF] - Updated message store TTL to 7200 seconds
2019-02-21 06:50:36.439 +00:00 [INF] - Updated the edge hub store and forward configuration
2019-02-21 06:51:09.855 +00:00 [INF] - Obtained edge hub config patch update from module twin
2019-02-21 06:51:09.984 +00:00 [INF] - Updating edge hub configuration
2019-02-21 06:51:09.985 +00:00 [INF] - Set the following 2 route(s) in edge hub
2019-02-21 06:51:09.985 +00:00 [INF] - LargeTwinReadModuleToIoTHub: FROM /messages/modules/porttesting/outputs/* INTO $upstream
2019-02-21 06:51:09.985 +00:00 [INF] - sensorToLargeTwinReadModule: FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO B
rokeredEndpoint("/modules/LargeTwinReadModule/inputs/input1")
2019-02-21 06:51:09.985 +00:00 [INF] - Updated message store TTL to 7200 seconds
2019-02-21 06:51:09.985 +00:00 [INF] - Updated the edge hub store and forward configuration
2019-02-21 06:51:31.381 +00:00 [INF] - Reauthenticating connected clients
2019-02-21 06:51:51.057 +00:00 [INF] - Connection id ""0HLKNP477IA0F"" request processing ended abnormally.
System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: The certificat
e chain was issued by an authority that is not trusted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.AdaptedPipeline.ReadInputAsync(Stream stream)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)

**Comment by myagley** [comment]
I want to understand the scenario a little more. Is `0HLKNP477IA0F` a device? Is this device connecting using `MQTT`/`AMQP` over websockets?

**Comment by sachidanand** [comment]
We are using amqp over websocket 443 port and the container is windows

**Comment by sachidanand** [comment]
Device Connection is using 443 AMQP overwebsocket and this is  `0HLKNP477IA0F` not device. The device is different .. 
We are using Windows based Host machine and the container is also windows based only. We have installed Edge runtime for windows on this VM. It is working fine with port 5671 AMQP but we want to run it on the AMQP Over websocket 443 port. This is not working for us..

**Comment by sachidanand** [comment]
System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: The certificat
e chain was issued by an authority that is not trusted
--- End of inner exception stack trace ---

**Comment by myagley** [comment]
On windows, we do not currently support a module connecting to the Edge Hub over websockets. This is because there is no way to tell C# to use a CA certificate that is not in the root store, which is required to validate the Edge Hub's server cert.

IoT Edge does support a downstream device to connect over websockets because you can presumably install the CA cert in the trust store on the device. This set of tutorials discusses all of the steps required to set this up: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway

Can I ask why does the module need to communicate over websockets? This is typically an issue when you want to firewall all ports except for 443. However, in this case, the communication between the Edge Hub and module is all internal to the host machine. It shouldn't require you to expose the AMQP or MQTT ports externally to connect.

**Comment by sachidanand** [comment]
Our requirement is to communicate over 443 only and other ports such as 5671 AMQP would not be opened on the firewall. So we need to set the upstream communication over websocket 443 port only using the Windows container. Could you suggest the work around for this or is there any fix in process for this issue ???

**Comment by sachidanand** [comment]
Hi Team,
   Is there any update on??? please respond on my queries 

Our requirement is to communicate over 443 only and other ports such as 5671 AMQP would not be opened on the firewall. So we need to set the upstream communication over websocket 443 port only using the Windows container. Could you suggest the work around for this or is there any fix in process for this issue ???

**Comment by veyalla** [comment]
@sachidanand, the setup is not clear to me...
1. What protocol is being used to connect from edgeHub to IoT Hub?
2. How many other modules are being used in the deployment?
3. Do the other modules use Azure IoT SDKs? if yes, which language?
4. Which protocols do the other modules use to connect to edgeHub?
5. Do you have downstream device connecting to the Edge device?

**Comment by sachidanand** [comment]
* What protocol is being used to connect from edgeHub to IoT Hub?
--5671 as of now as 443 is not working on Windows Container. But we need to use 443 so could you let me know when it would be supported??
* How many other modules are being used in the deployment?
--Single module as of now.
* Do the other modules use Azure IoT SDKs? if yes, which language?
--We have single module as of now.
* Which protocols do the other modules use to connect to edgeHub?
--5671 AMQP 5671 as 443 is not working.
* Do you have downstream device connecting to the Edge device?
Yes we have but we are connecting them over Modbus and TCP.

**Comment by myagley** [comment]
The Edge Hub supports connecting upstream to IoT Hub over 443 (websockets) on all platforms. I don't see any errors in the logs that indicate that this is an issue (the upstream connection). This scenario is part of our automated test matrix and is passing. If we can get the logs from when the Edge Hub starts it will list the protocol being used to connect upstream to verify.

On the flip side, modules/devices connecting to the Edge Hub over 443 (websockets) on Windows is *not* currently supported. This is actually a client-side issue (not an issue in the Edge Hub). There is no dotnet API that allows a custom CA certificate to be used for a websocket connection on Windows in dotnet core 2.1. This means that TLS server certificate validation fails on the connection. This was fixed in dotnet core 2.2 but will not be backported to 2.1. We will need to understand when the API is being added to .NET Standard so that the C# library can be updated to take advantage of it.

**Comment by veyalla** [comment]
Note, for the module to connect to the edgeHub via AMQP port, you don't have to open up that port on the host. A module and edgeHub can connect via AMQP within their private network (setup automatically) without the AMQP port opened on the host.

**Comment by sachidanand** [comment]
So Do you mean that we no need to open 5671 AMQP on our firewall?? However, we are connecting the module with 5671 so how would it work if we will not open it on Firewall?? 
Could you please send me more details on the ports, supported ports, firewall rules if applicable etc..

**Comment by avranju** [comment]
Connectivity between modules does not require opening up ports in the firewall. This is because modules are running as containers on the same host so this is really just inter-process communication and this traffic never leaves the host. So you should be able to just use plain AMQP instead of AMQP over WebSockets.

**Comment by ancaantochi** [comment]
Closing, please reopen if you still have this issue.

**Comment by sachidanand** [comment]
Is it supported now with C# to use 443 port
