### ISSUE TITLE
Calling direct method from iotedge module using amqp

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iotedge#893]
I need to trigger a direct method of an iotedge module from within another iotedge module on the same edge device.

Since we are running iotEdge on a raspberry and there are memory issues with multiple protocol heads enabled, we only enable the AMQP-Head.

When calling a direct method like this
```
MethodRequest request = new MethodRequest("MyDirectMethod", Encoding.UTF8.GetBytes(payload));
var response = await _ioTHubModuleClient.InvokeMethodAsync(_deviceId, "MyModule", request).ConfigureAwait(false);
```
we get the following exception
```
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Connection refused ---> System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.ModuleClient.InvokeMethodAsync(Uri uri, MethodRequest methodRequest, CancellationToken cancellationToken)
```
So it seems like Http is used to trigger the direct method.
After enabling the Http-Protocol-Head, our code works fine.

The direct method can be triggered from VisualStudioCode using the Azure IoT Edge Extension with only the AMQP Head enabled, so Http does not seem to be a general requirement for direct methods.

Please let me know, how I can trigger a direct method from within an iotedge module with only the AMQP-Head enabled.

**Comment by myagley** [comment]
Yes, the only way to trigger a direct method is via HTTP. The VSCode extension is most likely making an HTTP call through IoT Hub (not the Edge Hub) which is why it still works with the HTTP protocol head disabled in the Edge Hub.

**Comment by BewaControl-ReneDivossen** [comment]
@myagley Thanks for your reply.
This leaves me with some questions though:
1.  Does this mean, that disabling protocol heads for edgeHub via environment variables only affects communication between modules on the edge device?  Communication between IotHub and the edge device can use any protocol if the corresponding HostPort is opened?
2. In the [IotHub DevGuide](https://docs.microsoft.com/en-US/azure/iot-hub/iot-hub-devguide-protocols) it says 

> Cloud-to-device pattern. HTTPS does not have an efficient way to implement server push. As such, when you are using HTTPS, devices poll IoT Hub for cloud-to-device messages. This approach is inefficient for both the device and IoT Hub. Under current HTTPS guidelines, each device should poll for messages every 25 minutes or more. MQTT and AMQP support server push when receiving cloud-to-device messages.

Why are direct methods triggered by HTTPS if it is lacking server push capabilities?

3. In the [IotHub C2D Guidance](https://docs.microsoft.com/en-US/azure/iot-hub/iot-hub-devguide-c2d-guidance) it says that Direct Methods are "**Available using MQTT or AMQP**".  Why can direct methods be triggered via MQTT/AMQP by IotHub but not by EdgeHub?

**Comment by sebader** [comment]
You have to differentiate between a) triggering Direct Methods and b) receiving direct method calls.
a) is done through the IoT Hub services side APIs - for which there are only HTTP APIs.
b) Is done on the device client (or in our case here module client). Those do connect to IoT Hub via MQTT/AMQP and receive their method calls over those connections.

For the IoT Hub scenario only HTTP-support is by design and okay. That's why probably there is no implementation so far to trigger DM over MQTT/AMQP from the [ModuleClient](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/ModuleClient.cs#L635).

But I agree that for the ModuleClient case this would make a lot of sense. @myagley could you consider this an enhancement request? 
At least for now you should probably add a note to the [Edge dev guide](https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist#disable-unused-protocols) that turning off the HTTP protocol head leads to direct methods cannot be called from modules.

**Comment by BewaControl-ReneDivossen** [comment]
@sebader Thanks for the insight.
@myagley Accepting this as an enhancement request would be great.

**Comment by myagley** [comment]
Yes, we have discussed adding the "invoke direct method" API to the device-side surface area (AMQP/MQTT) in the past. The main issue here is that we need to coordinate that change with IoT Hub because the SDKs are used against both endpoints. This work hasn't yet been scheduled.
