### ISSUE TITLE
edgeAgent 1.0.6.19913336 crashes when running IoTEdge in container

### ISSUE THREAD

**Issue by alevincenzi** [Azure/iotedge#960]
The edgeAgent crashes when run inside a container as proposed by the tool [iotedgedev](https://github.com/Azure/iotedgedev/tree/master/docker/runtime)

## Expected Behavior
The edge agent should run, pull the edgeHub and other modules.
Edge device should be up and running in the container.
D2C messages sent from modules should be visible in the iot hub.

## Current Behavior
An exception is risen and the edgeAgent stops.
The watchdogs restarts it every minute.

## Steps to Reproduce

1. Create an IotEdge Device
2. Add module `mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0`
3. Copy connection string
4. `git clone https://github.com/Azure/iotedgedev`
5. `cd iotedgedev/docker/runtime`
6. `dos2unix *.sh`
7. `./build-container.sh`
8. `export IOT_DEVICE_CONNSTR=' .... paste string ...'`
9. `./run-container.sh`

### Device (Host) Operating System
```
vincenzi@ubuntu:~/iotedgedev/docker/runtime$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

### Architecture
```
vincenzi@ubuntu:~/iotedgedev/docker/runtime$ uname -a
Linux ubuntu 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

#### iotedged

```
vincenzi@ubuntu:~/iotedgedev/docker/runtime$ docker exec -it iotedgec bash
root@e2a5a93a1977:/# iotedge --version
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
```

#### Edge Agent
1.0.6.19913336 (8288bc9bd6f6e15295fea506cd3f99d7f6347a6a)

#### Edge Hub
None

#### Docker
```
vincenzi@ubuntu:~/iotedgedev/docker/runtime$ docker --version
Docker version 3.0.3, build 48bd4c6d
```

## Logs

Log of the container iotedgec:
```
vincenzi@ubuntu:~/iotedgedev/docker/runtime$ ./run-container.sh 
=> detecting IP
=> creating config.yaml
provisioning:
  source: "manual"
  device_connection_string: " ....XXX...."
agent:
  name: "edgeAgent"
  type: "docker"
  env: {}
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}
hostname: "edgehub"
connect:
  management_uri: "http://host.docker.internal:15580"
  workload_uri: "http://host.docker.internal:15581"
listen:
  management_uri: "http://172.19.0.2:15580"
  workload_uri: "http://172.19.0.2:15581"
homedir: "/var/lib/iotedge"
moby_runtime:
  docker_uri: "/var/run/docker.sock"
  network: "azure-iot-edge"
=> running iotedge daemon
<6>2019-03-15T07:43:30Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2019-03-15T07:43:30Z [INFO] - Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
<6>2019-03-15T07:43:30Z [INFO] - Using config file: /etc/iotedge/config.yaml
<6>2019-03-15T07:43:30Z [INFO] - Using runtime network id azure-iot-edge
<6>2019-03-15T07:43:30Z [INFO] - Initializing the module runtime...
<6>2019-03-15T07:43:30Z [INFO] - Initializing module runtime...
<6>2019-03-15T07:43:30Z [INFO] - Successfully initialized module runtime
<6>2019-03-15T07:43:30Z [INFO] - Finished initializing the module runtime.
<6>2019-03-15T07:43:30Z [INFO] - Configuring /var/lib/iotedge as the home directory.
<6>2019-03-15T07:43:30Z [INFO] - Configuring certificates...
<6>2019-03-15T07:43:30Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
<6>2019-03-15T07:43:30Z [INFO] - Finished configuring certificates.
<6>2019-03-15T07:43:30Z [INFO] - Initializing hsm...
<6>2019-03-15T07:43:32Z [INFO] - Finished initializing hsm.
<6>2019-03-15T07:43:32Z [INFO] - Detecting if configuration file has changed...
<6>2019-03-15T07:43:32Z [INFO] - Change to configuration file detected.
<6>2019-03-15T07:43:32Z [INFO] - Removing all modules...
<6>2019-03-15T07:43:32Z [INFO] - Removing module edgeAgent...
<6>2019-03-15T07:43:32Z [INFO] - Successfully removed module edgeAgent
<6>2019-03-15T07:43:32Z [INFO] - Finished removing modules.
<3>2019-03-15T07:43:32Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert_and_key_exist_by_alias:1458) Certificate and key file for alias do not exist iotedged-workload-ca
<6>2019-03-15T07:43:32Z [INFO] - Provisioning edge device...
<6>2019-03-15T07:43:32Z [INFO] - Manually provisioning device "XXX" in hub "XXX.azure-devices.net"
<6>2019-03-15T07:43:32Z [INFO] - Finished provisioning edge device.
<6>2019-03-15T07:43:32Z [INFO] - Starting management API...
<6>2019-03-15T07:43:32Z [INFO] - Starting workload API...
<6>2019-03-15T07:43:32Z [INFO] - Starting watchdog with 60 second frequency...
<6>2019-03-15T07:43:32Z [INFO] - Listening on http://172.19.0.2:15580/ with 1 thread for management API.
<6>2019-03-15T07:43:32Z [INFO] - Listening on http://172.19.0.2:15581/ with 1 thread for workload API.
<6>2019-03-15T07:43:32Z [INFO] - Checking edge runtime status
<6>2019-03-15T07:43:32Z [INFO] - Creating and starting edge runtime module edgeAgent
<6>2019-03-15T07:43:33Z [INFO] - Updating identity for module $edgeAgent
<6>2019-03-15T07:43:33Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0...
<6>2019-03-15T07:43:34Z [INFO] - Successfully pulled image mcr.microsoft.com/azureiotedge-agent:1.0
<6>2019-03-15T07:43:34Z [INFO] - Creating module edgeAgent...
<6>2019-03-15T07:43:34Z [INFO] - Successfully created module edgeAgent
<6>2019-03-15T07:43:34Z [INFO] - Starting module edgeAgent...
<6>2019-03-15T07:43:34Z [INFO] - Successfully started module edgeAgent
<6>2019-03-15T07:44:32Z [INFO] - Checking edge runtime status
<6>2019-03-15T07:44:32Z [INFO] - Edge runtime status is failed, starting module now...
<6>2019-03-15T07:44:32Z [INFO] - Starting module edgeAgent...
<6>2019-03-15T07:44:33Z [INFO] - Successfully started module edgeAgent
<6>2019-03-15T07:45:32Z [INFO] - Checking edge runtime status
<6>2019-03-15T07:45:32Z [INFO] - Edge runtime status is failed, starting module now...
<6>2019-03-15T07:45:32Z [INFO] - Starting module edgeAgent...
<6>2019-03-15T07:45:33Z [INFO] - Successfully started module edgeAgent
<6>2019-03-15T07:46:32Z [INFO] - Checking edge runtime status
<6>2019-03-15T07:46:32Z [INFO] - Edge runtime status is failed, starting module now...
<6>2019-03-15T07:46:32Z [INFO] - Starting module edgeAgent...
<6>2019-03-15T07:46:33Z [INFO] - Successfully started module edgeAgent

...
```

Stack trace from edgeAgent:

```
vincenzi@ubuntu:~/iotedgedev/docker/runtime$ docker exec -it iotedgec /bin/bash
root@742dc7bb89a3:/# docker logs edgeAgent
[2019-03-15 07:04:28 : Starting Edge Agent
[03/15/2019 07:04:28.915 AM] Edge Agent Main()
2019-03-15 07:04:29.128 +00:00 [INF] - Starting module management agent.
2019-03-15 07:04:29.289 +00:00 [INF] - Version - 1.0.6.19913336 (8288bc9bd6f6e15295fea506cd3f99d7f6347a6a)
2019-03-15 07:04:29.290 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2019-03-15 07:04:29.456 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
2019-03-15 07:04:30.379 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2019-03-15 07:04:30.656 +00:00 [FTL] - Fatal error starting Agent.
System.Net.Http.HttpRequestException: No such device or address ---> System.Net.Sockets.SocketException: No such device or address
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()w
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.GeneratedCode.EdgeletHttpClient.GetSystemInfoAsync(String api_version, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/generatedCode/EdgeletHttpClient.cs:line 173
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.GetSystemInfoAsync() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 120
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.RuntimeInfoProvider`1.GetSystemInfo() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs:line 33
   at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironmentProvider.CreateAsync(IRuntimeInfoProvider runtimeInfoProvider, IEntityStore`2 store, IRestartPolicyManager restartPolicyManager) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironmentProvider.cs:line 39
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.EdgeletModule.<>c.<<Load>b__10_6>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule.<>c.<<Load>b__13_14>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs:line 249
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 160
2019-03-15 07:04:30.692 +00:00 [INF] - Termination requested, initiating shutdown.
2019-03-15 07:04:30.692 +00:00 [INF] - Waiting for cleanup to finish
2019-03-15 07:04:30.692 +00:00 [INF] - Done with cleanup. Shutting down.
root@742dc7bb89a3:/#
```

## Additional Information

The same steps run to simulate iotedge on a container (same connection string) works fine in Windows 10 with build and run commands run via powershell.  Same iotedged and same edgeAgent. I can see messages from the simulated temperature sensor in the hub.

**Comment by varunpuranik** [comment]
Hi @alevincenzi - It looks like EdgeAgent is crashing because it does not have the management api socket mounted inside the container. (see here for more details - https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-security-manager)

I am not sure what that is the case. Can you please open an issue against the https://github.com/Azure/iotedgedev repo? Someone there should be able to help you with it.

**Comment by alevincenzi** [comment]
Done! See https://github.com/Azure/iotedgedev/issues/380

**Comment by alevincenzi** [comment]
Hello
i tried to search for any socket dll inside the image edgeAgent:
```
vincenzi@ubuntu:/$ docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
iot-edge-c                             latest              65ba2efa5485        3 days ago          342MB
<none>                                 <none>              6db758cc0cae        3 days ago          342MB
ubuntu                                 16.04               9361ce633ff1        6 days ago          118MB
mcr.microsoft.com/azureiotedge-agent   1.0                 e4917eb97425        6 weeks ago         146MB
vincenzi@ubuntu:/$ docker run e4917eb find / -type f -name "*.dll" | grep ocket
/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.6/System.Net.Sockets.dll
/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.6/System.Net.WebSockets.Client.dll
/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.6/System.Net.WebSockets.dll
```
It seems to be there ...

**Comment by myagley** [comment]
I am going to close this issue for now as it seems to be related to `iotedgedev`.
