### ISSUE TITLE
EdgeHub RocksDbException: Corruption: block checksum mismatch

### ISSUE THREAD

**Issue by bachmeierm** [Azure/iotedge#961]
After running fine for about 2 days edgeHub is not sending any messages to IoT Hub.
Since then `RocksDbException: Corruption: block checksum mismatch` exceptions are being thrown.

The attached log belog shows the point where the first exception started to happen.

## Expected Behavior
edgeHub should run and forward messages to IoT Hub.

## Current Behavior
edgeHub is not sending any data to IoT Hub and throws the following exception:
`RocksDbException: Corruption: block checksum mismatch`

## Steps to Reproduce
1. Run custom modules that send data to IoT Hub
2. Keep running for about two days
3. ???

### Device (Host) Operating System
Windows 10 IoT Enterprise 1809

### Architecture
amd64

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent
1.0.6

#### Edge Hub
1.0.6

#### Docker
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.11.4
  Git commit:       5ec3138
  Built:            Thu Jan 24 17:16:18 2019
  OS/Arch:          windows/amd64
  Experimental:     false

## Logs

```
2019-03-15 01:02:13.184 +01:00 [WRN] - Did not receive ack for message 1158583b-4c59-4929-ba8a-af914c6f9ad1 from device/module deviceId/apiconnector
2019-03-15 01:02:13.184 +01:00 [WRN] - Error sending messages to module deviceId/apiconnector
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\device\DeviceMessageHandler.cs:line 361
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\routing\ModuleEndpoint.cs:line 164
2019-03-15 01:03:43.195 +01:00 [WRN] - Did not receive ack for message 9c7d6bc9-c918-4553-ba80-2c66ea7942ae from device/module deviceId/apiconnector
2019-03-15 01:03:43.196 +01:00 [WRN] - Error sending messages to module deviceId/apiconnector
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\device\DeviceMessageHandler.cs:line 361
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\routing\ModuleEndpoint.cs:line 164
2019-03-15 01:04:13.197 +01:00 [WRN] - Did not receive ack for message bd839807-14bd-4424-9e10-070d30c75153 from device/module deviceId/apiconnector
2019-03-15 01:04:13.198 +01:00 [WRN] - Error sending messages to module deviceId/apiconnector
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\device\DeviceMessageHandler.cs:line 361
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\routing\ModuleEndpoint.cs:line 164
2019-03-15 01:04:57.325 +01:00 [INF] - Starting compaction of stores
2019-03-15 01:04:57.325 +01:00 [INF] - Starting compaction of store default
2019-03-15 01:04:57.325 +01:00 [INF] - Starting compaction of store DeviceScopeCache
2019-03-15 01:04:57.355 +01:00 [INF] - Starting compaction of store sessions
2019-03-15 01:04:57.375 +01:00 [INF] - Starting compaction of store messages
2019-03-15 01:04:57.818 +01:00 [INF] - Starting compaction of store twins
2019-03-15 01:04:57.818 +01:00 [INF] - Starting compaction of store deviceId/apiconnector/input
2019-03-15 01:04:58.807 +01:00 [WRN] - Error opening events link for deviceId/localapi
RocksDbSharp.RocksDbException: Corruption: block checksum mismatch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage.RocksDb\RocksDbWrapper.cs:line 59
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.ExecuteUntilCancelled(Task task, CancellationToken cancellationToken) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 268
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass22_1.<<PutOrUpdate>b__1>d.MoveNext() in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage\EntityStore.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator, CancellationToken cancellationToken) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage\EntityStore.cs:line 113
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout)
   at Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore.Add(String endpointId, IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\storage\MessageStore.cs:line 97
   at Microsoft.Azure.Devices.Routing.Core.Endpoints.StoringAsyncEndpointExecutor.Invoke(IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\endpoints\StoringAsyncEndpointExecutor.cs:line 60
   at Microsoft.Azure.Devices.Routing.Core.Dispatcher.DispatchInternal(IEndpointExecutor exec, IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\Dispatcher.cs:line 222
   at Microsoft.Azure.Devices.Routing.Core.Router.RouteAsync(IEnumerable`1 messages) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\Router.cs:line 98
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.EventsLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Amqp\linkhandlers\EventsLinkHandler.cs:line 63
2019-03-15 01:04:58.854 +01:00 [WRN] - Error opening events link for deviceId/localapi
RocksDbSharp.RocksDbException: Corruption: block checksum mismatch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage.RocksDb\RocksDbWrapper.cs:line 59
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.ExecuteUntilCancelled(Task task, CancellationToken cancellationToken) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 268
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass22_1.<<PutOrUpdate>b__1>d.MoveNext() in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage\EntityStore.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator, CancellationToken cancellationToken) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage\EntityStore.cs:line 113
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout)
   at Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore.Add(String endpointId, IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\storage\MessageStore.cs:line 97
   at Microsoft.Azure.Devices.Routing.Core.Endpoints.StoringAsyncEndpointExecutor.Invoke(IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\endpoints\StoringAsyncEndpointExecutor.cs:line 60
   at Microsoft.Azure.Devices.Routing.Core.Dispatcher.DispatchInternal(IEndpointExecutor exec, IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\Dispatcher.cs:line 222
   at Microsoft.Azure.Devices.Routing.Core.Router.RouteAsync(IEnumerable`1 messages) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\Router.cs:line 98
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.EventsLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Amqp\linkhandlers\EventsLinkHandler.cs:line 63
2019-03-15 01:04:58.858 +01:00 [WRN] - Error opening events link for deviceId/localapi
RocksDbSharp.RocksDbException: Corruption: block checksum mismatch
   at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Put(Byte[] key, Byte[] value, ColumnFamilyHandle handle) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage.RocksDb\RocksDbWrapper.cs:line 59
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.ExecuteUntilCancelled(Task task, CancellationToken cancellationToken) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 268
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.<>c__DisplayClass22_1.<<PutOrUpdate>b__1>d.MoveNext() in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage\EntityStore.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Storage.EntityStore`2.PutOrUpdate(TK key, TV value, Func`2 updator, CancellationToken cancellationToken) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Storage\EntityStore.cs:line 113
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout)
   at Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore.Add(String endpointId, IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\storage\MessageStore.cs:line 97
   at Microsoft.Azure.Devices.Routing.Core.Endpoints.StoringAsyncEndpointExecutor.Invoke(IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\endpoints\StoringAsyncEndpointExecutor.cs:line 60
   at Microsoft.Azure.Devices.Routing.Core.Dispatcher.DispatchInternal(IEndpointExecutor exec, IMessage message) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\Dispatcher.cs:line 222
   at Microsoft.Azure.Devices.Routing.Core.Router.RouteAsync(IEnumerable`1 messages) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Routing.Core\Router.cs:line 98
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.EventsLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Amqp\linkhandlers\EventsLinkHandler.cs:line 63
```

@sebader

**Comment by varunpuranik** [comment]
@bachmeierm - Thanks for the issue. We haven't seen this exception before - we will investigate.

**Comment by lt72** [comment]
Closing issues as it seems stale. please feel free to re-open as needed.
We recommend upgrading to 1.0.8.4 (released today) where we implemented lots of reliability improvements.
