### ISSUE TITLE
ModuleClient.OpenAsync throws Transient network error

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#980]
Hi,

I have got a device which is **behind proxy** with following details:
OS: RHEL 7.6
Moby from:
https://github.com/Azure/azure-iotedge/releases/download/1.0.5/moby-engine-3.0.2-centos.x86_64.rpm
https://github.com/Azure/azure-iotedge/releases/download/1.0.5/moby-cli-3.0.2-centos.x86_64.rpm

IoT Edge runtime from:
https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/libiothsm-std-1.0.6.1-1.el7.x86_64.rpm
https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/iotedge-1.0.6.1-1.el7.x86_64.rpm

Proxy configured by following link: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support

When it calls OpenAsync it throws Transient error logs are shown below:

```
[root@devbox ~]# sudo docker logs -f filterModule
Begin Init
transport type: Amqp_WebSocket_Only
Creating ioTHubModileClient from settings...
Calling await ioTHubModuleClient.OpenAsync()...

Unhandled Exception: System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.IotHubConnection.CreateClientWebSocketAsync(Uri websocketUri, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.IotHubConnection.CreateClientWebSocketTransportAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.IotHubConnection.CreateSessionAsync(TimeSpan timeout, CancellationToken token)
   at Microsoft.Azure.Devices.Client.IotHubSingleTokenConnection.CreateSessionAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.CreateValue(TaskCompletionSource`1 tcs, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.IotHubConnection.GetSessionAsync(TimeoutHelper timeoutHelper, CancellationToken token)
   at Microsoft.Azure.Devices.Client.IotHubConnection.CreateSendingLinkAsync(String path, IotHubConnectionString connectionString, String corrId, SendingLinkType linkType, TimeSpan timeout, ProductInfo productInfo, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.CreateEventSendingLinkAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.CreateValue(TaskCompletionSource`1 tcs, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at FilterModule.Program.Init() in C:\FilterModule\Program.cs:line 79
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at FilterModule.Program.Main(String[] args) in C:\FilterModule\Program.cs:line 42
[root@devbox ~]#
```

Can anyone assist on this?

Thanks,
Muhammad Masood

**Comment by varunpuranik** [comment]
Hi @m4masood - 
 I wonder whether the proxy is playing into this, or is it independent of that. Few questions - 
- Are all your modules running into this issue?
- Can you also provide the EdgeHub logs for the repro scenario? 
- Which version of the SDK is the FilterModule using?

**Comment by m4masood** [comment]
Hi, 
All my modules are having same issue.
.net core 2.1

Here are the logs:
[dev2-edgeHub-logs.txt](https://github.com/Azure/iotedge/files/2994513/dev2-edgeHub-logs.txt)
[dev2-edgeAgent-logs.txt](https://github.com/Azure/iotedge/files/2994515/dev2-edgeAgent-logs.txt)

Thanks,
Muhammad Masood

**Comment by m4masood** [comment]
Hi,
Its been resolved. There was some proxy configuration issue.

Thanks,
Muhammad Masood
