### ISSUE TITLE
Message not being send, Topic name could not be matched

### ISSUE THREAD

**Issue by wijkjh** [Azure/iotedge#985]
I have a custom module written in Python, which gets data from a data acquisition module sends it to IoTHub.
But when looking into edgeHub logging the following eror/warning is shown:

`2019-03-21 10:11:37.304 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessageAddressConverter] - Message address devices/vm-edge-001/modules/iotedge_module/messages/events/messageType=telemetry&%24.cid=correlation_1553163097302169&%24.mid=1553163097302169&%24.on=telemetryOutput/ does not match any topic.
2019-03-21 10:11:37.305 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Message was not sent for device Id vm-edge-001/iotedge_module exception System.InvalidOperationException: Topic name could not be matched against any of the configured routes.
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ProtocolGatewayMessageConverter.ToMessage(IMessage sourceMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs:line 28
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient.ProcessMessageAsync(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MessagingServiceClient.cs:line 166
`

And when monitoring the IoT Hub device using VS Code I also do not see any messages coming in.

I tried deploying the temperature simulator and that worked just fine.

The route is defined as:

`        "routes": {
          "iotedge_moduleToIoTHub": "FROM /messages/modules/iotedge_module/outputs/* INTO $upstream"
        },
`

I wonder I am doing something wrong.
The module itself works just fine.
I use `send_event_async(outputQueueName, event, self.callbacks.send_confirmation_callback, send_context)` as method to send data to the output queue.

## Expected Behavior
I would expect the message to be received by the IoT Hub.

## Current Behavior
No messages are being sent.

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
 iotedge 1.0.6.1

#### Edge Agent
 1.0

#### Edge Hub
1.0

#### Docker
Using moby.

Client:
 Version:           3.0.3
 API version:       1.40
 Go version:        go1.11.4
 Git commit:        48bd4c6d
 Built:             Wed Jan 23 16:17:56 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       8ecd530
  Built:            Fri Jan 25 01:45:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.2
  GitCommit:        9754871865f7fe2f4e74d43e2fc7ccd237edcbce
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        96ec2177ae841256168fcf76954f7177af9446eb
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Logs

`2019-03-21 10:11:22.253 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Adding subscription TwinResponse for client vm-edge-001/iotedge_module.
2019-03-21 10:11:22.253 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Obtained cloud connection for device vm-edge-001/iotedge_module
2019-03-21 10:11:22.254 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Processing subscription TwinResponse for client vm-edge-001/iotedge_module.
2019-03-21 10:11:22.254 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider] - Adding subscription devices/vm-edge-001/modules/iotedge_module/# for client vm-edge-001/iotedge_module.
2019-03-21 10:11:22.254 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Adding subscription ModuleMessages for client vm-edge-001/iotedge_module.
2019-03-21 10:11:22.254 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Obtained cloud connection for device vm-edge-001/iotedge_module
2019-03-21 10:11:22.255 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Processing subscription ModuleMessages for client vm-edge-001/iotedge_module.
2019-03-21 10:11:22.255 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider] - Adding subscription $iothub/twin/PATCH/properties/desired/# for client vm-edge-001/iotedge_module.
2019-03-21 10:11:22.255 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Adding subscription DesiredPropertyUpdates for client vm-edge-001/iotedge_module.
2019-03-21 10:11:22.256 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Obtained cloud connection for device vm-edge-001/iotedge_module
2019-03-21 10:11:22.256 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Processing subscription DesiredPropertyUpdates for client vm-edge-001/iotedge_module.
2019-03-21 10:11:22.256 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Operation SetDesiredPropertyUpdateCallbackAsync succeeded for vm-edge-001/iotedge_module
2019-03-21 10:11:22.257 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStateStoragePersistenceProvider] - Set subscriptions from session state for vm-edge-001/iotedge_module
2019-03-21 10:11:22.332 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager] - IotHub call succeeded
2019-03-21 10:11:22.333 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Operation UpdateReportedPropertiesAsync succeeded for vm-edge-001/$edgeHub
2019-03-21 10:11:22.333 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy] - Updating reported properties for device vm-edge-001/$edgeHub
2019-03-21 10:11:22.333 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager] - Successfully sent reported properties to cloud for vm-edge-001/$edgeHub and reported properties version 0
2019-03-21 10:11:22.334 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.TwinManager] - Updated cached reported property for vm-edge-001/$edgeHub at reported property version 251 cloudVerified True
2019-03-21 10:11:23.729 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 105 with batch size 10.
2019-03-21 10:11:23.729 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 105.
2019-03-21 10:11:33.730 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 105 with batch size 10.
2019-03-21 10:11:33.730 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 105.
2019-03-21 10:11:37.304 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessageAddressConverter] - Message address devices/vm-edge-001/modules/iotedge_module/messages/events/messageType=telemetry&%24.cid=correlation_AAA001_1_1553163097302169&%24.mid=AAA001_1_1553163097302169&%24.on=telemetryOutput/ does not match any topic.
2019-03-21 10:11:37.305 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Message was not sent for device Id vm-edge-001/iotedge_module exception System.InvalidOperationException: Topic name could not be matched against any of the configured routes.
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ProtocolGatewayMessageConverter.ToMessage(IMessage sourceMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs:line 28
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient.ProcessMessageAsync(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MessagingServiceClient.cs:line 166
2019-03-21 10:11:37.306 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessageAddressConverter] - Message address devices/vm-edge-001/modules/iotedge_module/messages/events/messageType=telemetry&%24.cid=correlation_AAA001_2_1553163097302169&%24.mid=AAA001_2_1553163097302169&%24.on=telemetryOutput/ does not match any topic.
2019-03-21 10:11:37.306 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Message was not sent for device Id vm-edge-001/iotedge_module exception System.InvalidOperationException: Topic name could not be matched against any of the configured routes.
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ProtocolGatewayMessageConverter.ToMessage(IMessage sourceMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs:line 28
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient.ProcessMessageAsync(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MessagingServiceClient.cs:line 166
`

**Comment by wijkjh** [comment]
Reproduced by creating a new Python IoT Edge module in VS Code.

Updated the main() function to:
`def main(protocol):
    try:
        print ( "\nPython %s\n" % sys.version )
        print ( "IoT Hub Client for Python" )

        hub_manager = HubManager(protocol)

        print ( "Starting the IoT Hub Python sample using protocol %s..." % hub_manager.client_protocol )
        print ( "The sample is now waiting for messages and will indefinitely.  Press Ctrl-C to exit. ")

        while True:
            msg_id = "msg-{}".format(int(time.time() *1000000))   
            values = {'messageType': 'telemetry', 'moduleType': 'sample/1.0', 'telemetry': 
                        {'ref': '1234567', 'result': 0.7829191088676, 'phenomenonTime': '2019-03-21T10:59:10.426122', 'resultTime': '2019-03-21T10:59:10.425373'}}
            header = {'id': msg_id, 'data': values}
            data = json.dumps(header)
            message = IoTHubMessage(data)
            message_id = header['id']
            message.message_id = message_id
            message.correlation_id = 'correlation_{}'.format(message_id)
            prop_map = message.properties()
            prop_map.add("messageType", values['messageType'])
            prop_map.add("moduleType", values['moduleType'])
            print('Sending message {}'.format(values))
            hub_manager.forward_event_to_output('sampleOutput', message, 0)
            time.sleep(10)

    except IoTHubError as iothub_error:
        print ( "Unexpected error %s from IoTHub" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubModuleClient sample stopped" )
`

The issue is solved when I removed the `prop_map.add("moduleType", values['moduleType'])` statement or update the value to `sample` (without the forward slash).
The forward slash in the message properties causes the error not sending the message.

So it seems forward slashes in the message properties causes unexpected issues (which I could not determine from the edgehub log).

Solved.
