### ISSUE TITLE
A null system property can cause an NRE

### ISSUE THREAD

**Issue by drwill-ms** [Azure/iotedge#998]
If a system property gets set to null, processing of that message by the service can hit a null reference exception because the values are assumed to not be null.

How is this likely to happen? An Edge module that copies messages and resends them will want to proxy the ContentType and ContentEncoding from the device. If the device didn't set it, the default value is null, and then it gets set.

## Expected Behavior
You could say that they shouldn't do this if the value is null, but we should just make the service resilient to user input.

## Current Behavior
Message fails to be processed due to NRE.

## Steps to Reproduce

1. From a client C# SDK, construct a new message and explicitly set ContentType and ContentEncoding to null
2. Send message

### Device (Host) Operating System

I was building a c# Edge module, debugging using simulated device data.

### Architecture

amd64

### Container Operating System

Linux container

### Runtime Versions
<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.*"/>

#### Docker

Docker version 18.09.2, build 6247962

## Logs

``` callstack
at Microsoft.Azure.Devices.Routing.Core.Message.<>c.<Size>b__34_1(Int32 acc, KeyValuePair`2 pair) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Message.cs:line 139
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Microsoft.Azure.Devices.Routing.Core.Message.Size() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Message.cs:line 139
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub.ValidateMessageSize(IMessage messageToBeValidated) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs:line 221
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub.ProcessDeviceMessage(IIdentity identity, IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs:line 60
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient.ProcessMessageAsync(IMessage message) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MessagingServiceClient.cs:line 168
2019-03-24 02:38:50.111 +00:00 [WRN] - Message was not sent for device Id WorkshopEdgeDevice/FilterModule exception System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Routing.Core.Message.<>c.<Size>b__34_1(Int32 acc, KeyValuePair`2 pair) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Message.cs:line 139
```

**Comment by drwill-ms** [comment]
I've submitted a [PR](https://github.com/Azure/iotedge/pull/1000).
